### ISSUE TITLE
UtBS S9: Dialogue to explain rebel recruits with zero upkeep costs

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6365] opened 2021-12-07 11:55 UTC
Extension of #6362 as requested by @max-torch. Add some dialogue or narration to explain that the rebels who join Kaleh have no upkeep costs, but only for the remainder of the scenario. An example of something similar is in SoF:
https://github.com/wesnoth/wesnoth/blob/77eed10a098579ddb8ac20bbdadbf05b69541203/data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg#L1100-L1108

**Comment by nemaara** [comment] 2021-12-07 22:04
Oops I didn't look at your PR in time before you merged it, but can you just make the rebel units loyal forever after they join you?

**Comment by Wedge009** [comment] 2021-12-07 22:15
I think the discussion in the original #6229 leant against that idea, plus when I played that scenario recently I noted this line seemed to contrast against the idea of in-story loyalty:
https://github.com/wesnoth/wesnoth/blob/c1c5af1aacac64b22681a7f21c572193a0b2f0b0/data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg#L2334

Thus it doesn't seem right to suddenly have all these loyal units join Kaleh's roster (the story implies there are many other elves besides the ones Kaleh can recall).

**Comment by nemaara** [comment] 2021-12-07 22:19
Gameplay perspective is a better reward though. Otherwise you might as well just farm them for exp since they'll be useless to you next scenario anyway.

**Comment by Descacharrado** [comment] 2021-12-07 22:26
I agree that no upkeep on level 1s for the last two scenarios may be cool gameplaywise, and I think it would be easy to fit lorewise (they just want to fight for free for the cause) but in that case I would use the loyal trait instead of no upkeep, so the player can spot these units quickly in the recall list.

**Comment by Wedge009** [comment] 2021-12-07 22:48
Yeah, I suppose there's only one more 'real' scenario after S9 so it wouldn't be that game-play skewing to have so many loyal (trait) units, plus it looks more like an actual reward that 'punishment' as @max-torch put it. As for dialogue, I'm not keen on having some loyal and some not, but if you're able to implement that it might turn out all right.

**Closed** 2021-12-08 04:08 UTC
Labels: Enhancement, Campaign, Prose

**Comment by max-torch** [comment] 2021-12-08 08:45
> Yeah, I suppose there's only one more 'real' scenario after S9 so it wouldn't be that game-play skewing to have so many loyal (trait) units, plus it looks more like an actual reward that 'punishment' as @max-torch put it. As for dialogue, I'm not keen on having some loyal and some not, but if you're able to implement that it might turn out all right.

Regarding "some loyal and some not"... Actually this can make sense dialog-wise. The reason being the rebels feel like they have to make up for what they did. They are extra keen on serving effectively to prove their loyalty and regain their honor.

**Comment by Wedge009** [comment] 2021-12-08 08:55
That might be overly complicating things in terms of scenario implementation and rather subtle for most players to notice, but as I said, if you're that keen on it anyone is welcome to implement it if they want. I don't think I will be trying, I think the original issue of being 'punished' has been resolved.

**Comment by Descacharrado** [comment] 2021-12-08 13:04
> I think the original issue of being 'punished' has been resolved.

Agreed, now we wait for further normal playthrough feedback.
