### ISSUE TITLE
MP Create Game dialogue introduces some fun translucency when display resolution is too small (GNA #25107)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1583] opened 2017-05-08 12:10 UTC
**[Original submission](https://gna.org/bugs/index.php?25107)** by wedge009 on 2016-09-23

Tested on d1053abe in both Windows and Linux. I realise the dialogue may be undergoing continuing development.

1. Go to MP Create Game - Local Game is sufficient.

2. If necessary, shrink your horizontal resolution so that scroll bars are necessary. Keep your view so that the General / Custom Options / Game Settings dialogue on the right remains partially off-screen.

3. In any of those three tabs on the right, in the uppermost box, move the mouse over the check boxes (Shuffle Sides, Observers, etc).

4. As the tool-tips pop on and off, observe that the translucency of the containing box vacillates between normal and completely black/opaque.

Oh, fun times. ):

(Reproduced on All)
Release: 1.13.5+dev
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment] 2017-05-08 12:10
**Modified on 2016-09-23**

**wedge009 added attachment:** [bad_translucency.png](http://gna.org/bugs/download.php?file_id=28729)

**Comment by wesnoth-bugs** [comment] 2017-05-08 12:10
**Modified on 2016-09-23**

**vultraz changed status:** None -> Confirmed

**vultraz wrote:**

> Known :( There's something screwy with partially obscured rects and the canvas drawing code.

**Comment by Wedge009** [comment] 2017-05-11 04:26
Marking @Vultraz and myself in this report.

**Comment by CelticMinstrel** [comment] 2017-05-11 04:29
Looks like this is a duplicate of #1591. Or that's a duplicate of this. Whichever you prefer, I guess.

**Comment by Wedge009** [comment] 2017-05-11 04:33
Mine was reported first. I did remark in #1591 that I thought it might be separate as I couldn't get the precise conditions @matthiaskrgr was reporting. But I do think they're very closely related if not the same.

**Comment by CelticMinstrel** [comment] 2017-05-11 04:38
I think it could depend on which scenario you're starting.

**Closed** 2017-12-12 19:42 UTC
Labels: Bug, Confirmed, Regression, UI

**Comment by Wedge009** [comment] 2017-12-13 05:43
Confirmed, thank you!
