### ISSUE TITLE
Unit's image is missing when attacking

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#6960] opened 2022-08-12 19:57 UTC
### Game and System Information

The Battle for Wesnoth version 1.17.6+dev (https://github.com/wesnoth/wesnoth/commit/565b318c9f0166d09f2dbff8f7982a52cd382dbb-Modified) x86_64
Running on Fedora Linux 36 (Workstation Edition) x86_64
Distribution channel: Default

SDL video drivers: wayland [x11] KMSDRM dummy
Window size: 1920x1021
Game canvas size: 1920x1021
Final render target size: 1920x1021
Screen refresh rate: 60
Boost: 1.76
Lua: 5.4.4
OpenSSL/libcrypto: 3.0.0e-dev (runtime 3.0.0e-dev)
Cairo: 1.17.6 (runtime 1.17.6)
Pango: 1.50.8 (runtime 1.50.8)
SDL: 2.0.22 (runtime 2.0.22)
SDL_image: 2.0.5 (runtime 2.0.5)
SDL_mixer: 2.0.4 (runtime 2.0.4)

### Description of the bug

Unit's image is missing at the destination hex, sometimes the unit's image is irregularly blinking at hex when the unit was previously standing:
![image](https://user-images.githubusercontent.com/3605541/184431941-45cd8b2e-4c30-4e6b-9c50-09ee7439add2.png)
![image](https://user-images.githubusercontent.com/3605541/184432177-c24ddcb0-be73-465f-a165-889ee2b8c7ba.png)

### Steps to reproduce the behavior

1. Select unit then move&attack another unit

**Comment by Wedge009** [comment] 2022-08-28 12:33
It's not entirely clear to me what the issue is - is the heavy infantryman blinking on attack? I have not observed anything like this in 1.17.7+dev (314f6f7c78d). knyghtmare, how did you confirm this?

Also, the build version indicates a modified source - what was changed?

**Comment by grz0** [comment] 2022-08-28 12:56
> It's not entirely clear to me what the issue is - is the heavy infantryman blinking on attack?

There are two issue, one is missing unit's sprite  (Heavy infantry) at village location. The second issue is that unit's sprite (Heavy infantry) stays at the old position, and it is blinking in an irregular glitchy way (game display switches between those two screenshots, some times Heavy infantry is also cropped at the top).

**Comment by Wedge009** [comment] 2022-08-28 12:59
How should one replicate what you described? It has to be more than just 'select unit then move&attack another unit', unless I'm missing something obvious.

**Comment by grz0** [comment] 2022-08-28 13:14
> It has to be more than just 'select unit then move&attack another unit'

It's just that simple, I don't know how to explain this better :slightly_smiling_face:, here is a screenshot of almost all game's window:
![image](https://user-images.githubusercontent.com/3605541/187075548-e2b97d68-4196-4369-83e8-e7cac367f054.png)

In this case, the second issue with old sprite is a bit different, it's not blinking but half of the sprite is drawn under the ice layer. When I close 'Attack Enemy' dialog the sprite is redrawn correctly.

**Comment by knyghtmare** [comment] 2022-08-28 15:46
@Wedge009 the screenshot provided by @grz0 confirms it. This was not present in 1.16.x So, it's a confirmed bug.

**Comment by Wedge009** [comment] 2022-08-28 21:11
So it's the unit on the village in the original report that's missing? And in that last image, the unit in the water?

As I said, I'm testing on 314f6f7c78d and I *cannot* replicate this.

**Comment by grz0** [comment] 2022-08-28 22:14
> As I said, I'm testing on [314f6f7](https://github.com/wesnoth/wesnoth/commit/314f6f7c78d5fe1588e34acf0a73463197654b7f) and I **cannot** replicate this.

I just compiled from 314f6f7c78d and I still see the same issue:
![image](https://user-images.githubusercontent.com/3605541/187096557-88cdaa4a-3fb8-4cc7-ace9-43620ad712de.png)

On which platform do you test?

**Comment by Wedge009** [comment] 2022-08-28 22:43
Linux/X11.

Your comments suggest you are encountering this with every attack interaction, so I am not trying to replicate any specific circumstances, just randomly attacking units. Strangely enough I can also confirm this now. I recall seeing a similar issue logged previously...

![image](https://user-images.githubusercontent.com/13679322/187097582-3ad59234-0d5a-4eb7-80d3-9ba584d87855.png)

**Comment by grz0** [comment] 2022-08-28 22:52
I just compiled 1.16.5 and I cant reproduce the issue. Screenshot from 1.16.6:
![image](https://user-images.githubusercontent.com/3605541/187097841-a586f3fc-47fc-4b0e-9618-0014d51f007e.png)

**Comment by grz0** [comment] 2022-08-29 13:39
It looks that the issue has been introduced in commit 06254e5581cbb79b5eaf72bec0dbb3fc1566b7a4. @mesilliac 

```
$ git bisect log
git bisect start
# status: waiting for both good and bad commits
# good: [f6cfad7b5065d0a99f1c2d9e5115f6d97d08d56b] 1.17.5.
git bisect good f6cfad7b5065d0a99f1c2d9e5115f6d97d08d56b
# status: waiting for bad commit, 1 good commit known
# bad: [ab8fe65b8381fd78d953719193c8e30888caf29a] 1.17.6
git bisect bad ab8fe65b8381fd78d953719193c8e30888caf29a
# good: [0fbc12ea01986bc97ef6426e0edc89f12224a0d5] Remove largely incorrect usage of floating_to_fixed_point()
git bisect good 0fbc12ea01986bc97ef6426e0edc89f12224a0d5
# bad: [2279ec99eb8bed477bdddda4595f2f4afe53e2e0] Fix crash when resizing window in map editor
git bisect bad 2279ec99eb8bed477bdddda4595f2f4afe53e2e0
# good: [c8e948a62b8432c9f66ec5e5ecb93b319e4ce5c4] std::cerr -> PLAIN_LOG, to stop bypassing the logging system
git bisect good c8e948a62b8432c9f66ec5e5ecb93b319e4ce5c4
# good: [b063bb5e2e7f961a23dbcc3ece4432d7ee1ee982] Split ubuntu build into separate steps
git bisect good b063bb5e2e7f961a23dbcc3ece4432d7ee1ee982
# bad: [06254e5581cbb79b5eaf72bec0dbb3fc1566b7a4] Mega draw manager implementation
git bisect bad 06254e5581cbb79b5eaf72bec0dbb3fc1566b7a4
# good: [09fe5a19fda9884b70aed413de84d4f0672d3f1a] Adding Amorphous to credits
git bisect good 09fe5a19fda9884b70aed413de84d4f0672d3f1a
# good: [a964c807ab80daad1eeb661a904fa7218c5ef9bf] Update changelog.md
git bisect good a964c807ab80daad1eeb661a904fa7218c5ef9bf
# good: [3dbf212f8cdeea132617d0d5d61c8ad280ba26c8] Add a draw manager, to manage drawing to the screen
git bisect good 3dbf212f8cdeea132617d0d5d61c8ad280ba26c8
# first bad commit: [06254e5581cbb79b5eaf72bec0dbb3fc1566b7a4] Mega draw manager implementation
```

**Comment by Toranks** [comment] 2023-01-27 21:07
I've captured this video with a more serious version of this glitch, where the unit stays displaced and blinking permanently until I select it again. This occurs randomly, so far I haven't been able to figure out any more pattern than what seems to be related to scenarios with water (but not always), and that as you can see in the second half of the video, it is not always reproducible.

https://user-images.githubusercontent.com/40789364/215198682-6347d70b-0236-4c52-a06e-4c5bc51675bc.mp4

**Comment by gfgtdf** [comment] 2023-06-06 17:45
So from the 1.16 screenshot i take that the expected behaviour is that there is simply no unit&halthbar shown at the destination hex? Because the the first message it sounds like it is expected to be there.

**Comment by Toranks** [comment] 2023-06-06 18:44
On the contrary, the unit should be seen where the HP bar is visible on the screenshot, it doesn't matter if these bars are visible or not, but the unit should be seen at the attack target.

**Comment by gfgtdf** [comment] 2023-06-06 19:36
> On the contrary, the unit should be seen where the HP bar is visible on the screenshot, it doesn't matter if these bars are visible or not, but the unit should be seen at the attack target.

But the post which says "Screenshot from 1.16.6:" also doesn't show any unit there from what i can see

**Comment by Toranks** [comment] 2023-06-06 20:16
Oh that's right. I'm so used to the unit disappearing in 1.17 that I forgot that the original behavior didn't alter the attacking unit until you hit the attack button. So you're probably right.

**Comment by Pentarctagon** [comment] 2024-01-14 06:56
1.16:
![Screenshot from 2024-01-14 00-53-22](https://github.com/wesnoth/wesnoth/assets/3030250/4d9e866d-63e3-432e-ac16-fb6682132c46)

1.17:
![Screenshot from 2024-01-14 00-47-49](https://github.com/wesnoth/wesnoth/assets/3030250/129a00dc-d185-4179-868b-ed60aa5223ce)

**Comment by Pentarctagon** [comment] 2024-01-14 18:21
@mesilliac is this something you'd be willing to look into, given the bisect above by grz0 points to 06254e5581cbb79b5eaf72bec0dbb3fc1566b7a4 as the cause?

**Comment by gfgtdf** [comment] 2024-01-14 19:35
I tested a bit and its really odd, sometimes the unit shows in the original  hex, sometimes it doesn't, playing other units next to it seems to have an influence. the bar+orb is always drawn on the new hex

**Comment by gfgtdf** [comment] 2024-01-14 19:48
We move the unit here: https://github.com/wesnoth/wesnoth/blob/27e5dd50d2e6f03c12adcb6572d819155ff3be2d/src/mouse_events.cpp#L938 but appearently this only moves the unit on the board and and the bars/orbs, the units image is somwhow left behind.

The two obvious way to fix it would then be:
1) Don't move the unit there ("there" = that line in the code not that mp location), (instead move the unit somewheere else, so that the unit is only moved during the calculation of the attack stats not all the time while the dialog is shown. )
2) Fix the drawing code to be able to handle this case.

**Comment by Pentarctagon** [comment] 2024-01-20 20:45
I'm not sure where else it could be moved from. If it's moved any later then the unit doesn't exist to trigger the attack dialog, and if it's moved any earlier it's before the check to make sure it can actually reach the hex to attack from.

**Comment by Pentarctagon** [comment] 2024-01-21 18:09
Something else I noticed - if a unit has a standing animation (such as a drake over water), then the unit flickers in place on its starting hex with the animation continuing as normal even if you can only see the frame for an instant. So I wonder if this is related to dialogs no longer blocking animations on the map, and this is what it always would have done except that previously the attack dialog opening prevented this from being seen.

**Comment by Pentarctagon** [comment] 2024-01-22 04:17
Would it make sense to spawn a temporary copy of the unit at the hex for the attack dialog to use rather than use the temporary_unit_mover?

**Comment by CelticMinstrel** [comment] 2024-01-22 06:14
Well… I think the `temporary_unit_mover` should do what it's supposed to…

**Comment by Pentarctagon** [comment] 2024-01-22 18:35
Interestingly, if I do just the move logic of `temporary_unit_mover`:
`auto [iter, success] = pc_.get_units().move(src, attack_from);`
then after closing the attack dialog the unit's actual location is moved, but has no image:
![Screenshot from 2024-01-22 12-32-14](https://github.com/wesnoth/wesnoth/assets/3030250/26d2d469-b6e9-4b1d-8ac9-8ff1bf003851)

Then hovering over the new location makes it draw at the old location:
![Screenshot from 2024-01-22 12-33-52](https://github.com/wesnoth/wesnoth/assets/3030250/13d8e262-5067-40d5-9d7a-62817ddb31ca)

And then hovering over the old location removes it again:
![Screenshot from 2024-01-22 12-34-37](https://github.com/wesnoth/wesnoth/assets/3030250/8b39f0ba-82b0-4318-b95b-d826a770e150)

So something it out of sync between where the unit actually is and wherever the rendering code is checking to determine where to draw the unit.

**Comment by mesilliac** [comment] 2024-01-23 23:02
> @mesilliac is this something you'd be willing to look into, given the bisect above by grz0 points to [06254e5](https://github.com/wesnoth/wesnoth/commit/06254e5581cbb79b5eaf72bec0dbb3fc1566b7a4) as the cause?

As mentioned elsewhere, I touched unit animation as little as possible, and frankly have no more idea how it works than anybody else.

There were weird problems like this before my changes, and there were slightly fewer weird problems like this after my changes. I could never replicate this particular bug, and i'm not familiar with any of the code that seems to be related.

**Closed** 2024-01-26 22:18 UTC
Labels: Bug, Confirmed, Blocker: New Stable, Graphics, Regression
