### ISSUE TITLE
Something wrong in lobby

### ISSUE THREAD

**Issue by GliderMaster** [wesnoth/wesnoth#4858] opened 2020-04-19 15:25 UTC
### Game and System Information
 - What version of the game are you running? 1.14.11
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.) Website
 - If you're using a custom build, what compiler did you use, and what commit did you build at? I'm not
 - What OS are you running? Windows 10
### Describe the bug
I'm receiving the messare 
Error
Something is wrong with the addon version check database supporting the multiplayer lobby 

when I try to join some games.

**Comment by Pentarctagon** [comment] 2020-04-19 16:46
Duplicate of #4055, it looks like.

**Closed** 2020-04-19 16:47 UTC
Labels: Duplicate
