### ISSUE TITLE
Better error message for ActionWML [unit] with invalid type 

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#9382] opened 2024-09-25 21:03 UTC
![unknown-lua](https://github.com/user-attachments/assets/a283596c-e93c-4ae0-8d0a-8331f2a0a19c)

Needs a clear error message instead. It is triggered by:
```
[unit]
    type=nonexistant_unit
```

Tested in 1.18 and master.

**Comment by Wedge009** [comment] 2024-09-25 22:52
It wasn't clear to me at first, but presumably the 'non-existent unit' type just needs to be anything that's not a valid, recognised type. Similarly for #9383.

**Comment by CelticMinstrel** [comment] 2024-09-25 23:54
Is this using system Lua or submodule Lua? I seem to recall something similar to this being a downside of the system Lua PR.

**Comment by Wedge009** [comment] 2024-09-26 00:23
I wasn't aware it was possible to choose - wouldn't Wesnoth use what it was built with?

**Comment by sevu** [comment] 2024-09-26 00:42
It uses system Lua.

With scons, it is possible to use it by setting `system_lua=True`

**Comment by CelticMinstrel** [comment] 2024-09-26 01:25
> I wasn't aware it was possible to choose - wouldn't Wesnoth use what it was built with?

Yes, it's chosen at build time.

**Comment by soliton-** [comment] 2024-10-02 12:04
This does not happen with lua as a submodule.

**Comment by soliton-** [comment] 2024-10-02 12:20
Actually this is a duplicate of #8847.

**Closed by soliton-** 2024-10-02 12:20 UTC
Labels: Enhancement, WML

**Comment by Wedge009** [comment] 2024-10-02 12:23
Well spotted.
