### ISSUE TITLE
Oldania ADF Std Font encoding

### ISSUE THREAD

**Issue by MultiSeptim** [wesnoth/wesnoth#5351] opened 2020-12-09 20:09 UTC
### Game and System Information
 - version 1.15.7 downloaded from webside
 - operation system Windows (but also appears on MacOS)

### Describe the bug
Font Oldania ADF Std used for some credits has an inappropriate character set for some non-English languages.

### To Reproduce
Just see it.

### Screenshots
![obrazek](https://user-images.githubusercontent.com/71945783/101681700-da621880-3a62-11eb-82ce-6115e793bb91.png)

![obrazek](https://user-images.githubusercontent.com/71945783/101681602-b0105b00-3a62-11eb-9bcf-4324338ea8d4.png)

**Comment by Pentarctagon** [comment] 2020-12-09 20:12
What language is in the screenshots?

**Comment by hrubymar10** [comment] 2020-12-09 20:14
> What language is in the screenshots?

It is Czech (Čeština)

**Comment by hrubymar10** [comment] 2020-12-09 20:16
On macOS using 1.15.7 package it at least fill missing letters from other font
![image](https://user-images.githubusercontent.com/2218817/101682290-b3581680-3a63-11eb-858b-8e711c40da4b.png)

Also you can see all missing letters here for example: https://www.1001fonts.com/oldania-adf-std-font.html?text=%C4%9B%C5%A1%C4%8D%C5%99%C5%BE%C3%BD%C3%A1%C3%AD%C3%A9%C3%BA%C5%AF

**Comment by MultiSeptim** [comment] 2020-12-09 20:30
It has also problems with characters: Ű;Ő;Ż;Ę or Ą.

**Comment by kabachuha** [comment] 2020-12-09 20:31
Seems it's the same problem as in #5007 and #1549.

**Comment by hrubymar10** [comment] 2020-12-09 20:33
It indeed is duplicate of #5007 I don't know if #1549 too

**Comment by Pentarctagon** [comment] 2020-12-10 00:01
Closing as it's a duplicate then.

**Closed by Pentarctagon** 2020-12-10 00:01 UTC
Labels: Bug, Duplicate, UI
