### ISSUE TITLE
KDE5: wesnoth startup problem with fullscreen mode (GNA #24984)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1569] opened 2017-05-08 11:52 UTC
**[Original submission](https://gna.org/bugs/index.php?24984)** by shiki on 2016-08-16

When using KDE5, this is what it looks like when I start the game.

Using Alt+Tab twice, or Alt+Tab and clicking on the icon in taskbar, then fullscreen works. (otherwise it stays the whole game like that)

Also, if I instead switch the workspace after startup, the game is shown as minimized in the taskbar.

If I instead first resolve the fullscreen problem like shown above, then it isn't. (like it should be)

For the case you wonder, it has no effect if you click on the part of the desktop which is shown on the screenshot.

(Reproduced on Archlinux)
Release: 1.13.5+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:52
**Modified on 2016-08-16**

**shiki added attachment:** [after_startup.jpg](http://gna.org/bugs/download.php?file_id=28357)

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:52
**Modified on 2016-08-16**

**wedge009 wrote:**

> I'm also using Plasma 5 (5.6.5 to be exact), but I've just discovered I get a variety of segmentation faults and 'wanted size x, available size less than x' errors. Starting in windowed mode is fine.
> 
> 
> 
> I wonder if it's because my Linux test platform only has a 1280x800 monitor while your display is 1920x1080.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:52
**Modified on 2016-08-16**

**shiki wrote:**

> I thought in gnome are no problems, but ... - they just appear after launching wesnoth the 2nd time.
> 
> 
> 
> Switching workspaces brings me to the normal startscreen.
> 
> Same if I press the screenshot button, or if i press the key for adjusting the lightning or audio.
> 
> E.g. I use the win/super key, and it seems that the wesnoth screen just refreshes every time I press the win key twice. So, I click the add-ons button, but it looks like nothing happens, but after pressing the win key twice i see that something happened.
> 
> 
> 
> I attached a photo of the screen I get initially. When starting wesnoth the FIRST time, this get's shown shortly too, but then the game normal screen shows up.
> 
> (file #28363)

**shiki added attachment:** [gnome-2nd-startup.jpg](http://gna.org/bugs/download.php?file_id=28363)

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:52
**Modified on 2016-08-19**

**shiki wrote:**

> About the gnome part, 1-2 weeks ago, xf86-video-intel in Archlinux switched default to DRI 3, if I set DRI to 2 this problem doesn't occur.
> 
> 
> 
> KDE part remains the same.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:52
**Modified on 2016-11-14**

**shiki wrote:**

> Tested it again with current master and gnome 3.22.1 / kde 5.8.3
> 
>  - gnome starts fine now with DRI 3. Maybe not totally fancy (for a moment it looks like in the attachement), but no problems
> 
>  - kde startup remains the same

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:52
**Modified on 2017-04-12**

**wedge009 wrote:**

> Possibly as a result of work on bug #21564 and bug #25290, I don't get crashes when starting in full-screen mode any more. However, full-screen on start-up isn't really full-screen either - it looks more like a window filling the full screen aside from the task bar and without window decorations. Manually toggling window and then full-screen mode restores proper full-screen display.
> 
> 
> 
> The above comment is from running under Ubuntu with KDE desktop. Full screen works fine in Windows 7.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:52
**Modified on 2017-04-15**

**stikonas wrote:**

> This seems to happen only on X11.
> 
> 
> 
> Curiously fullscreen mode seems to work fine when in Plasma Wayland session when Wesnoth runs as Wayland client. Well, it has other problems (no icon, no window decoration).

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:52
**Modified on 2017-04-16**

**wedge009 wrote:**

> Yeah, I think I'm still using X11... you'd have to do something special to set-up Wayland, right?

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:52
**Modified on 2017-04-16**

**stikonas wrote:**

> Not really much special. I just have a choice between X11 and Wayland session in my login manager (SDDM).
> 
> 
> 
> Well, I'm still using X11 too but for Wayland to come eventually, application developers actually need to test for any issues.
> 
> 
> 
> Well, I also had to run via "SDL_VIDEODRIVER=wayland wesnoth". I guess this bug doesn't appear in that case because SDL uses different code path. The way full screen is set up must be quite different...

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:52
**Modified on 2017-04-16**

**wedge009 wrote:**

> I just meant that X11 is still seems to be the default for most distributions - I don't do much experimentation with display stuff, if I break anything it can be hard for me to get back what I had before.
> 
> 
> 
> Certainly, if you're confident to test things under Wayland, go for it.

**Comment by Wedge009** [comment] 2017-05-09 11:44
I'm confirming because I still get issues with full-screen mode and window decorations in Plasma 5.

**Comment by jyrkive** [comment] 2017-06-09 13:20
Marked as a blocker, this bug is severe enough.

**Comment by vn971** [comment] 2017-06-09 13:21
Got the same bug with a fresh install of wesnoth (git version). OS is ArchLinux, desktop environment is XFCE. The directory ~/.local/share/wesnoth/git did not exist, so this bug exists with a fresh install.

**Comment by jyrkive** [comment] 2017-08-08 05:04
Cannot reproduce with latest Git master. I'm on Siduction GNU/Linux. KDE Plasma 5.8.7, SDL 2.0.5.

**Comment by Wedge009** [comment] 2017-08-08 07:55
Hmm, I still have not-quite-full-screen when starting in full-screen mode, as of 48c6c630, similar to what @sevu posted in the original submission on 16th August 2016.

Pinging @stikonas for his input too. (Pity about the import from gna.org not carrying notifications.)

**Comment by stikonas** [comment] 2017-08-09 20:36
Well, I can still reproduce it on Plasma 5.10 on Gentoo. Maybe SDL 2.0.5 fixes it, I still have an older one.

**Comment by jyrkive** [comment] 2017-08-10 03:41
Another possibility is the fact that I have a dual-monitor setup (left 3840x2160, right 1920x1080). It might be that it *only* works correctly on multi-monitor systems, and maybe even only if the screens have different pixel dimensions.

**Comment by Wedge009** [comment] 2017-08-11 11:00
Hmm, I seem to be using SDL 2.0.5 on Linux, so that doesn't look like a factor. Plasma is at 5.10.4... maybe it's okay on Plasma 5.8? Oh, I'm on Kubuntu.

My Linux Wesnoth test box is an old laptop, single 1280x800 screen.

**Comment by Wedge009** [comment] 2017-09-21 01:30
@jcdenton2k It's good that you've looked through the issue list, but I think what you describe is different to this particular issue which is about problems with full-screen mode on start-up.

I don't have difficulty switching windows in either window or full-screen mode but if you're having difficulty I would suggest you submit a new issue report for that. Just wondering if the issue might be with respect to you particular hardware and/or video drivers.

As for the full-screen windowed mode, at least on my single monitor Linux platform full-screen behaves like this, but it might be worth doing as a proper enhancement in which case you should submit a separate issue for that as well.

**Comment by vn971** [comment] 2017-09-21 06:47
+1 to what @Wedge009 said. It's a different issue. Please raise your own as I've got comments on the new one, too.

**Comment by jyrkive** [comment] 2017-09-21 06:57
Wesnoth 1.13 already uses borderless fullscreen mode.

**Comment by Wedge009** [comment] 2017-09-21 07:41
Good to know! Matches the behaviour I've seen, at any rate.

**Comment by sevu** [comment] 2017-09-21 10:20
Did you build latest master or 1.13.8? It reminds me of #1606.

**Comment by jcdenton2k** [comment] 2017-09-23 23:17
I had build from source with the latest sources for both v1.12.x and v1.13.x
Both exhibited the 'no alt tabbing' behavior but it seems it may be some distribution-related video driver issue as it seems my integrated graphics open-source driver may not be as fully-featured as I thought it would be.
I thought my issues were related to this one but I'll make a new issue if these things persist.  I'll wait for the next version to drop before building from source and testing it again.

**Comment by GregoryLundberg** [comment] 2017-09-24 00:02
Today's master works for me. Probably is a video issue.

Noted when I clicked "X" to close:
```
Battle for Wesnoth v1.13.10 (bc911f8c46-Clean)
Started on Sat Sep 23 19:00:29 2017

Automatically found a possible data directory at /home/lundberg/wesnoth

Data directory:               /home/lundberg/wesnoth
User configuration directory: /home/lundberg/.config/wesnoth
User data directory:          /home/lundberg/.local/share/wesnoth/1.13
Cache directory:              /home/lundberg/.cache/wesnoth

Setting mode to 1440x845
Checking lua scripts... ok
*** Error in `wesnoth': free(): invalid pointer: 0x00007f219f4cd000 ***
Aborted (core dumped)


```

**Comment by sevu** [comment] 2017-09-24 01:16
possibly related to @jyrkive's last commit, some more info:
(1) https://bpaste.net/show/fc0011d30476
(2) https://bpaste.net/show/32cb59dab6e9
I think if you are quickly leaving wesnoth you trigger (1), if you wait a few sec (2)

**Comment by vn971** [comment] 2017-09-24 12:20
@sevu @GregoryLundberg I have SDL 2.0.5 (from ArchLinux), and I've re-built wesnoth just now (`v1.13.10 (33fe9823-Clean)`).

The bug sometimes does reproduce, and sometimes not. About 50% of invocations (on a cleaned home directory) lead to the bug. I can't understand what leads to wesnoth resizing or not.

Interestingly, the game is drawn on a small rectangle, yet a bigger area is actually considered to be a part of wesnoth window (considered by my window manager). For example, if I click "outside" of the drawn area, I still see the wesnoth-type cursor.

**Comment by Wedge009** [comment] 2017-09-25 02:04
@GregoryLundberg @sevu Is this still related to the KDE full-screen issue? Testing at 33fe9823 in Windows and Linux, I don't have any problems arising from closing the window during or after start-up. Is it a deterministic error?

From @vn971's comments, it looks like maybe not. I've tried this quite a few times now and have not been able to replicate the described issue.

I have libsdl 2.0.6 on Windows and 2.0.5 on Linux.

**Comment by sevu** [comment] 2017-09-26 00:11
Looks like I mixed up the locally installed wesnoth versions, and tested probably with a 1.13.9 release build. Can't reproduce it with 33fe982. In any case, it was unrelated to the KDE full screen issue.

**Comment by Vultraz** [comment] 2018-01-18 02:12
@shikadilord just tested with Git master with Plasma 5.10.5 on Debian Buster (testing), and both starting the app in fullscreen and fullscreen/windowed toggling works fine.

Removing the Blocker label.

**Comment by Wedge009** [comment] 2018-01-18 03:44
I just tested b8703b4527 with SDL 2.0.6 on Plasma 5.11.5 and everything seems fine now. Starting in either window or full-screen mode, switching between the two works and leaves no issues with window decorations.

I'm comfortable with this one being closed as resolved.

**Comment by sevu** [comment] 2018-01-29 02:27
I tested it with a few different Settings on KDE/xorg and I had no issues at all.
On gnome/xorg I have in difference to KDE a startup like shown on the 2nd picture, but that shouldn't disturb.

**Closed by sevu** 2018-01-29 02:27 UTC
Labels: Bug, Confirmed, Linux, Needs more info
