### ISSUE TITLE
Graphics overhaul regressions

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#7657] opened 2023-05-23 23:40 UTC
Attempting to collect together outstanding issues resulting from the graphics overhaul done between 1.17.4 and 1.17.7. While that work, including hardware-accelerated rendering (introduced in 1.17.6), resolved a lot of graphics-related issues, it also introduced a few of its own. This list is likely to be incomplete so additions are welcome.

### Confirmed link to overhaul
**Missing Text**
These are essentially duplicate issues but for the fact that they differ only in symptom details.
- [x] #6879 While I am unable to replicate the graphical symptoms in Linux I can confirm the `gui` error messages in the log were introduced in 06254e5581cbb79b5eaf72bec0dbb3fc1566b7a4.
- [x] #7093
- [x] #7565
- [x] #7655

**Campaign Story Screen**
- [x] #6922

**Zoom Artefacts**
- [ ] #6959

**Disappearing Units**
- [x] #6960

**Main Menu Transparency**
- [ ] #6988

**Crash on Campaign End**
- [x] #7395

**CPU Usage**
- [x] #7615

**Distorted images in side-bar**
- [x] #7472
- [x] #8303

**CLI Screenshots**
- [x] #7747

**SDL_RenderSetClipRect**
- [x] #7864

**Redraw on Windows**
- [x] #8038

**macOS crash**
- [x] #8044

**Full screen animation**
- [x] #8276

### Unconfirmed link
**Dialogue Drawing**
- [x] #7617

### Confirmed unrelated
**Flickering UI elements**
- [x] #7700 

**Title Screen Aliasing**
- [x] #7741

**Comment by Pentarctagon** [comment] 2023-05-23 23:45
https://github.com/wesnoth/wesnoth/issues/7615 can be moved to confirmed.

**Comment by Wedge009** [comment] 2023-05-23 23:47
I missed the bit in your write-up that it started with 1.17.6. I was inclined to confirm links via git bisect but that's probably sufficient.

**Comment by Wedge009** [comment] 2023-05-24 00:20
Added #6959.

**Comment by Wedge009** [comment] 2023-05-24 01:24
I had a closer look at #7626 but I could replicate it in 1.16 so it doesn't appear related to this.

**Comment by gfgtdf** [comment] 2023-06-07 01:11
This flickering of transparent elements over water, in particular chat messages probably too, not sure wheterh there is a bugreport for it:

[Screencast from 06.06.2023 23:19:30.webm](https://github.com/wesnoth/wesnoth/assets/4893136/8d505804-70c3-421c-9009-023f4574e00e)

**Comment by Wedge009** [comment] 2023-06-07 02:28
I don't think there's been an issue recorded for that. I assume you confirmed it doesn't happen in 1.16.x or with 1.17.4 or earlier.

I thought I had encountered an issue like the chat messages symptom before, but I realised I was thinking of #7100 (unrelated cause).

With respect to the flickering I wonder if that's related to mesilliac's comment in https://github.com/wesnoth/wesnoth/issues/6870#issuecomment-1183985864. I reported both #6869 and #6870 and they seemed to relate to animations, which includes water (by default).

**Comment by gfgtdf** [comment] 2023-06-07 02:56
> I assume you confirmed it doesn't happen in 1.16.x or with 1.17.4 or earlier.


I didn't test early 1.17 but i would have noticed if it happend on 1.16.

**Comment by Wedge009** [comment] 2023-06-07 21:55
I split the flickering UI issue into #7700, as it is not a direct result of mesilliac's work (which is the focus of this aggregate issue).

**Comment by Pentarctagon** [comment] 2023-06-30 17:56
#7747 is another one.

**Comment by Wedge009** [comment] 2023-06-30 23:04
Your bisect shows it was Vultraz's commit, plus it was before 1.17.4. I think SDL was just flagged to use acceleration before the engine itself was actually using acceleration properly..

**Comment by Wedge009** [comment] 2023-07-27 22:50
With respect to the missing text, @stevecotton states in #7565 that he can see the symptom in Linux. I still can't replicate in Linux (unmodified b5821d9611c) even with long text in the inspect dialogue, but I suppose we have to assume it's something non-deterministic as to cause issues like #6988.

**Comment by Wedge009** [comment] 2023-07-27 23:15
Moved #6988 to confirmed.

**Comment by gfgtdf** [comment] 2023-07-31 16:29
Could https://github.com/wesnoth/wesnoth/issues/7087 also be related?

**Comment by Wedge009** [comment] 2023-08-22 06:10
Added #7864.

**Comment by cooljeanius** [comment] 2023-10-19 07:07
Copying and pasting @mesilliac's latest comment from #1066 to here, since this is really where it's for:

> I commented on a couple, but the rest i could either never reproduce (like scaling artifacts and scrolled stuff not drawing) or they deal with systems i never went into (like animations or lua widgets).
>
> #7617, #7615, #6922 should be easy to fix but i don't really have the time or inclination.

**Comment by mesilliac** [comment] 2023-11-02 23:02
I finished off and improved a few small things in the rendering framework, which addressed some of these. The rest i can't reproduce, and/or don't really know anything about those game systems.

#6959 should be possible to fix just by randomly tweaking things until it works, as mentioned in the discussion there. I can't do it as it doesn't reproduce for me. The proposed solution in #7395 looks fine. The scrollbar/disappearing text issues don't reproduce for me, and i don't know anything about how gui layout is done. Similarly i could never reproduce the missing unit frame issue, and don't really know anything about how the unit animation system works.

**Comment by Wedge009** [comment] 2023-11-02 23:11
Thanks again for your efforts. You're exclusively on Linux, right? I found those missing text issues replicate reliably on Windows, though others have noticed them on Linux.

**Comment by mesilliac** [comment] 2023-11-02 23:25
Yeah i only have access fo Linux machines to test on. I did at the time try quite a lot of things to try to reproduce the disappearing text issue with the addon manager, but the text never vanished for me no matter what i did, even viewing the problematic addon and trying all different sorts of window sizes.

More gui error messages started showing up not because they got triggered by the new code but because i added more error messages for things that shouldn't be happening. They didnt help much as i got the errors too, but without the visual problems.

**Comment by Wedge009** [comment] 2023-11-11 00:06
Added #8038

**Comment by Wedge009** [comment] 2023-11-18 22:07
Added #8044

**Comment by grz0** [comment] 2023-11-22 00:48
https://github.com/wesnoth/wesnoth/issues/8061 - I'm not sure but this could be another regression

**Comment by Wedge009** [comment] 2024-01-24 01:08
Added #8276

**Comment by Wedge009** [comment] 2024-01-27 00:47
Added #7472 + #8303

**Comment by Pentarctagon** [comment] 2024-02-01 21:40
It looks like everything here has been fixed as much as it can be fixed, so any objection to closing this?

**Comment by knyghtmare** [comment] 2024-02-01 23:04
> It looks like everything here has been fixed as much as it can be fixed, so any objection to closing this?

It shows 18/20. Are those 2 remainders not worth the fix?

**Comment by Pentarctagon** [comment] 2024-02-01 23:24
For both issues, the latest comments indicate that the problem is essentially as fixed as it's going to get.

**Comment by Wedge009** [comment] 2024-02-01 23:34
Yes, notwithstanding any new issues reported I think this okay to close.

**Closed** 2024-02-03 04:14 UTC
Labels: Bug, Blocker: New Stable, Graphics, Regression

**Comment by gfgtdf** [comment] 2024-02-04 21:19
What, how is #6959 fixed? It still looks like this on 1.17.24
![image](https://github.com/wesnoth/wesnoth/assets/4893136/72b506ee-037e-4758-a09b-bf59b723c6db)

**Comment by Wedge009** [comment] 2024-02-04 21:25
Better to discuss in #6959 directly. But note that it's not marked as fixed on this aggregation either. My recollection is I only note it's a problem at 50% zoom, and its current state is certainly much better than straight after the change that triggered the issue.
