### ISSUE TITLE
i18n: Unlocalized strings in various UI elements

### ISSUE THREAD

**Issue by CloudiDust** [wesnoth/wesnoth#2732] opened 2018-03-24 15:07 UTC
Game Version: 1.13.12 (downloaded from sourceforge)
Locale: zh_CN (Simplified Chinese)
Pot Revision: Commit cdd1cb692bbb121a1650a45789b7f9e9059cd06d 

This is similar to #2709. Despite having 100% translated `wesnoth` and `wesnoth-lib` textdomains, various UI elements still display unlocalized strings. (I am currently testing and yet to submit the updated translations.)

The missing localized strings are the following:

![recruit unit dialog](https://user-images.githubusercontent.com/30068/37865282-7a05c3ca-2fb5-11e8-8df7-bd2b0760e195.PNG)

In the Recruit Unit dialog, weapon ranges and attack types.

![recall unit dialog](https://user-images.githubusercontent.com/30068/37865275-62a565b4-2fb5-11e8-9060-41c83d4de59e.PNG)

In the Recall Unit dialog, weapon ranges and attack types, also "Search" in the search bar.

![attack enemy dialog](https://user-images.githubusercontent.com/30068/37865315-2148afb2-2fb6-11e8-8abc-3c8e8408484f.PNG)

In the Attack Enemy dialog, the unit alignments.

![unit description dialog](https://user-images.githubusercontent.com/30068/37865386-b5e05f26-2fb6-11e8-8a88-5760c6e614b8.PNG)

In the Unit Description dialog, "Level".

![press t to keep moving](https://user-images.githubusercontent.com/30068/37865410-05d60b20-2fb7-11e8-9747-a76763e9f413.png)

"press t to keep moving" when an enemy is sighted.

![dextrous tooltip](https://user-images.githubusercontent.com/30068/37865421-28beb484-2fb7-11e8-898f-06c2d2fa4966.PNG)

![resilient tooltip](https://user-images.githubusercontent.com/30068/37865431-500cf8c0-2fb7-11e8-93e4-69e341aae2bf.PNG)

![strong tooltip](https://user-images.githubusercontent.com/30068/37865443-82841f68-2fb7-11e8-8fc4-5e1790d7406b.PNG)

And the tooltips for some traits in the status panel: Dextrous, Resilient and Strong. (Other than "HP", where I intentionally left the "translation" the same as the untranslated string, there should not be any English words in the three screenshots above, which means "damage" and "per level" are not localized. And I am not sure if "HP" is also not localized.)

EDIT: I tested again with "HP" translated to its corresponding Chinese word in both `wesnoth` and `wesnoth-lib`, but the tooltips remained the same, which means "HP" in the tooltips are not localized.

Also I haven't tested all the trait tooltips, and there may be other unlocalized strings in those.

**Comment by Vultraz** [comment] 2018-03-24 17:59
The alignment issue is likely caused by those strings also using `N_()` in a header.

**Comment by shikadiqueen** [comment] 2018-03-25 07:42
The "press t to keep moving" string issue is already fixed by commits 69c28e5088b6a9624e08c72be510e0a670d030f0 and dbac6e4e08f304f113538cd637868fb4544df71a I had pushed previously.

**Comment by shikadiqueen** [comment] 2018-03-25 22:51
Same applies to the unit trait effect tooltips. In particular, the HP tooltip is the one that necessitated a string thaw to be fully fixed, as per the 5th paragraph in the description for commit 69c28e5088b6a9624e08c72be510e0a670d030f0.

That means the only issues remaining to be solved are the Level label in help pages, which I'm waiting/leaving for @Vultraz to decide on; and the Search box label (also part of #2703), which is 100% his domain.

**Comment by shikadiqueen** [comment] 2018-03-26 06:29
All issues are fixed now, pending a pot-update for translators to be able to translate the strings in question.
(I've already confirmed the fixes work with a local pot-update and translation updates.)

**Closed by shikadiqueen** 2018-03-26 06:29 UTC
Labels: Bug, Translations, UI
