### ISSUE TITLE
Planning Mode is broken

### ISSUE THREAD

**Issue by kallaballa** [wesnoth/wesnoth#5812] opened 2021-05-28 07:09 UTC
### Game and System Information
 - What version of the game are you running?
 1.14.16
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Website
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
gcc, 1.14.16 release
 - What OS are you running?
OpenSUSE Tumbleweed (Linux twiggy 5.11.15-1-default #1 SMP Fri Apr 16 16:47:34 UTC 2021 (64fb5bf) x86_64 x86_64 x86_64 GNU/Linux
)

### Describe the bug
When using planing mode, (at least) multiplayer games sometimes crash or get corrupted. I've seen game crashes, OOS errors and disconnects without a network issue.

### To Reproduce
I don't have a exact procedure yet to reproduce the problems. It seems it is a combination of the actions of several players.

### Expected behavior
No crashes, No OOS, no disconnects.

**Comment by kallaballa** [comment] 2021-05-28 07:15
also.. i highly suspect now and then people attribute bugs to planning mode while it wasn't the culprit... disabling it would reveal potentially "shadowed" bugs as being not planning mode related.

**Comment by Wedge009** [comment] 2021-06-02 07:09
Planning mode really is a complex beast and doesn't always work the way it should, from what I recall looking at the whiteboard code all those years ago. I did wonder if it was worth keeping around at the time and I was told there are a number of people who still wish to use it. However, it would be important to isolate issues specific to planning mode from other problems like OOS network connectivity. If these issues are only observed with MP games I wonder if the issue is more with OOS problems or with interactions between planning mode states and communicating that across different players?

**Comment by gfgtdf** [comment] 2023-03-21 15:03
Since the  report is rather unspecific and since we have a few fixes related to whiteboard, for 1.16.9/1.17.5, i vote for closing this (not of whn 1.16.9 is out) since it might be fixed by them and we have no way to reproduce.

**Comment by Wedge009** [comment] 2023-03-21 23:32
It can always be re-opened if anyone is able to re-confirm this. I assume that was meant to say 1.17.**15** rather than 1.17.5.

**Closed by Wedge009** 2023-03-21 23:32 UTC
Labels: Bug, Needs more info, Whiteboard
