### ISSUE TITLE
Addons mysteriously vanishing at random

### ISSUE THREAD

**Issue by MXB2001** [wesnoth/wesnoth#4931] opened 2020-06-01 20:01 UTC
### Game and System Information
 - What version of the game are you running?
1.14.5
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Debian package 
 - What OS are you running?
Debian 9

### Describe the bug
Addons get uninstalled by themselves. It has happened twice now. First time the War of Legends addon was uninstalled. Second time the Dominus Maps were uninstalled.

### To Reproduce
Very sorry, it is rare, has happened twice in a year. I have no idea how to make it happen. I can only guess that it happens when I uninstall a different addon. It may be that more than the selected addon were uninstalled at that juncture.

### Expected behavior
Only the addons I want removed ought to be removed, not extra ones at random.

**Comment by soliton-** [comment] 2020-06-02 19:10
Without a couple more hints on how to reproduce I'm afraid this is not very helpful.

**Comment by rubyFeedback** [comment] 2020-06-17 18:20
> Without a couple more hints on how to reproduce I'm afraid this is not very helpful.
That is true, but I also had a problem with the add-ons, in particular the server. I think
in general it would help if we users could see more information displayed within the
widgets. That would in turn make it simpler to report helpful information upstream.
(See what the KDE devs did lately with simpler report-upstream functionality.)

**Comment by Wedge009** [comment] 2022-02-17 03:58
I'm inclined to close this because of its age. While there are older 'needs more info' issues, they have more discussion and/or details to warrant their remaining open. Will close in a day or so unless there are objections.

**Closed** 2022-02-18 06:01 UTC
Labels: Bug, Needs more info, Add-ons
