### ISSUE TITLE
Make it less easy to misclick and miss an event-triggered dialog (GNA #17472)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1249] opened 2017-05-08 05:54 UTC
**[Original submission](https://gna.org/bugs/index.php?17472)** by hagabaka on 2011-01-12

When I move a unit triggering an event which shows a dialog, I often miss the dialog and try to click on the next unit I wanted to move, thereby making the dialog disappear before I can read it. I then have to reload the turn if I want to see the dialog.

The main cause of this inconvenience is that I am used to moving/attacking units one by one, and when a dialog suddenly shows up, I do not have enough time to respond and not click as usual. So, one of the following suggestions applied only to the *first* dialog in each sequence would be necessary to fix the problem:

* Require clicking a "Close" button to close a dialog

* Require waiting for 1 second before the dialog can be closed with a click

(Reproduced on Any)
Release: 1.9.3
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 05:54
**Modified on 2011-01-18**

**anonymous wrote:**

> I would prefer that the entire sequence of dialogs behave in the same way, so I favor the "close button" idea applied to every message.  It might be worth considering the keyboard the preferred way of closing a dialog - even adding an option to the preferences to make it impossible to close a non-choice dialog with the mouse.

**Comment by wesnoth-bugs** [comment] 2017-05-08 05:54
**Modified on 2011-04-26**

**scaeb wrote:**

> Alternatively, one could do an "recall" feature for dismissed dialogs which shows the last (or just dismissed) dialog window...

**Comment by Pentarctagon** [comment] 2021-08-22 05:15
Closing as duplicate of #1118

**Closed by Pentarctagon** 2021-08-22 05:15 UTC
Labels: Enhancement, UI
