### ISSUE TITLE
Strange artifacts on the edges of the map in multiplayer

### ISSUE THREAD

**Issue by amakriLexa04** [wesnoth/wesnoth#8665] opened 2024-03-30 13:23 UTC
### Game and System Information

- **Version:** 1.16.12
- **OS:** Windows 10

### Description of the bug

They appear under unknown circumstances and disappear after a while

https://github.com/wesnoth/wesnoth/assets/165188749/2b184ab0-0fdf-458f-bc42-f970a6672235

https://github.com/wesnoth/wesnoth/assets/165188749/1a16eb9d-7404-4687-b4d5-fc8b81050c2b

**Comment by Wedge009** [comment] 2024-03-31 08:05
I was surprised to see this again, given that I noted 1.18 was used in #8668, but now I see that you're actually using 1.16. This is a duplicate of #1350 and possibly others. Presumably this doesn't happen for you with 1.18, in which case this can be considered closed.

If it's something we really want to revisit specifically for 1.16 (I wouldn't think so), then please re-open.

**Closed by Wedge009** 2024-03-31 08:05 UTC
Labels: Bug, Duplicate, Graphics, Stable 1.16
