### ISSUE TITLE
statistics dialog is shown after closing "Current status" dialog (with hotkey)

### ISSUE THREAD

**Issue by ePaul** [wesnoth/wesnoth#1736] opened 2017-05-28 12:41 UTC
Trying out the 1.13 series first, with 1.13.8+dev (a25f3d3, compiled myself and run on Linux).

When I use Alt+S to open the "game overview" dialog (dialog title is either "Current status" or "Szenrioeinstellungen" (szenario settings in German)), after closing that dialog the statistics dialog (which you normally get with just the S key) opens.

When opening the game overview dialog from the menu, that doesn't happen.

**Comment by CelticMinstrel** [comment] 2017-05-28 16:25
Probably related to #1711

**Comment by CelticMinstrel** [comment] 2017-05-29 12:46
I can't reproduce this, unfortunately. However I'm getting another bug that seems similar, so I think I can probably fix it... assuming I'm right that they're related.

**Comment by Wedge009** [comment] 2017-06-01 11:34
I couldn't replicate this either, though it does sound like the keys are not being 'debounced' properly - or rather the keys are registering multiple times incorrectly.

**Comment by Wedge009** [comment] 2017-06-01 12:18
Strangely enough I can confirm this now, albeit only on Linux.

**Comment by CelticMinstrel** [comment] 2017-06-02 01:15
The similar case I've experienced with opening the Lua console appears to be caused by the action being triggered on both "key down" and "text input" events. Aginor implemented the use of text input events in order to better support arbitrary keyboard layouts, so we can't just drop that outright; I think what we need is some way for "key down" to record that the event was handled so that "text input" can skip it. Either that or some way for "key down" to recognize that a "text input" will be generated from this event, but... I think that's actually impossible here.

**Comment by sevu** [comment] 2017-09-11 23:23
I have the issue from above with alt+s

**Comment by CelticMinstrel** [comment] 2017-09-12 00:52
On latest master?

**Comment by Wedge009** [comment] 2017-09-12 01:09
Confirming I also still have this issue on Linux as of 20eb4247. Still can't get it on Windows...

**Comment by sevu** [comment] 2017-09-12 13:01
yes

**Comment by Vultraz** [comment] 2018-03-05 02:44
Can someone re-text this? @jyrkive 's recent changes might have fixed it.

**Comment by Wedge009** [comment] 2018-03-05 07:17
Unfortunately it's still the same for me, as of 900a159c. Issue is present in Linux build but not in Windows.

**Comment by stevecotton** [comment] 2018-03-17 12:54
If both "key" and "alt+key" are assigned as hotkeys, it seems that pressing alt+key triggers both commands. The bug also happens with the unit status table (alt+u) which also triggers an undo (u).

Build version: Linux f6428edabddba4db7cf5c48fbf82df967b340f1e

**Comment by Vultraz** [comment] 2018-03-17 12:55
That's actually really helpful, thanks!

**Comment by stevecotton** [comment] 2018-03-17 13:54
One more finding - if you are still holding the 'alt' key when closing the first dialog, the second thing does not happen (you can close the first dialog with alt+enter).

IIUC, the hotkey_keyboard::matches_helper is reading the current keyboard state via SDL_GetModState(), ignoring the modifiers that are in the SDL_Event itself.

**Comment by sevu** [comment] 2018-04-08 18:58
May I mark this as blocker?

**Comment by jyrkive** [comment] 2018-04-09 06:50
@CelticMinstrel hasn't worked on this for a long time. Unassigning.

**Comment by jyrkive** [comment] 2018-04-10 04:29
Debugging this on GNU/Linux shows that the "current status" dialog is shown in response to a SDL_KEYDOWN event, whereas the statistics dialog is shown in response to a SDL_TEXTINPUT event for the same keypress.

That's what we get for using two distinct events for hotkeys, I guess...

**Comment by jyrkive** [comment] 2018-04-10 05:02
Okay, the difference on Windows is that SDL_TEXTINPUT events are not generated when Alt is held down.

**Comment by Wedge009** [comment] 2018-04-10 08:26
I'm away from home at the moment so I can't check for myself - it seems like there's different handling for the state of Alt being held down... in OS or SDL I wonder. That's a good find, though,

**Comment by CelticMinstrel** [comment] 2018-04-10 16:49
That doesn't look like a good fix to me; can you still type eg "é" on a Mac with this fix?

**Comment by jyrkive** [comment] 2018-04-11 15:59
Reopening because I reverted the fix.

**Closed** 2018-04-12 16:47 UTC
Labels: Blocker, Bug, Confirmed, Linux, UI

**Comment by ePaul** [comment] 2018-04-14 20:43
I can confirm that the issue doesn't appear anymore on my system with a fresh build on the 1.4 branch (76cf5baf5dd). Thanks!

**Comment by Wedge009** [comment] 2018-04-26 12:06
Sorry for the late confirmation, but this seems okay to me too. Tested within a few commits of the recently tagged 1.14.0.
