### ISSUE TITLE
Wesnoth exits due to 'cannot figure out scenario_id' asserion

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5104] opened 2020-08-26 14:32 UTC
### Game and System Information
 - What version of the game are you running?
Battle for Wesnoth v1.15.3+dev (0c4c8d6a-Clean)
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Flatpak
 - What OS are you running?
Linux

### Describe the bug

1. Start a new local multiplayer game with bots
2. Win or lose the game
3. Open autosaved game while you are still in game(do not press End scenario)
4. Wesnoth exits due to a failed assertion:
wesnoth: src/saved_game.cpp:658: std::string saved_game::get_scenario_id(): Assertion `!"cannot figure out scenario_id"' failed.

### Expected behavior
Wesnoth should not exit, it should open saved game

**Comment by Pentarctagon** [comment] 2020-08-26 14:34
Duplicate of #5097 and will be fixed in 1.15.5.

**Closed by Pentarctagon** 2020-08-26 14:34 UTC
