### ISSUE TITLE
Lua API: #wesnoth.unit_types crashes wesnoth

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2381] opened 2018-01-19 13:58 UTC
1.13.6 changelog says    * Lua unit_type lists (wesnoth.unit_types and unit_type.variations) are now
     countable with the Lua length operator.

Using wesnoth.message(#wesnoth.unit_types) results in APPCRASH. Log file has nothing relevant.

Tested with 1.13.10 on windows.

**Comment by GregoryLundberg** [comment] 2018-01-19 14:02
Unconfirmed but I've heard similar comments and will be there fixing the iterator so I'll take this.

**Comment by Pentarctagon** [comment] 2018-01-19 15:07
Backtrace: https://pastebin.com/eZPaMQnt

**Comment by vgaming** [comment] 2018-01-19 17:53
Interesting, it's somewhat counter-intuitive to Lua-s meaning of length. Usually, length means the number of consequent keys "1", "2", "3",... a table contains. Which, in case of `unit_types`, is 0, because keys are not integers. From pure Lua perspective, it sounds surprising.

**Comment by GregoryLundberg** [comment] 2018-01-19 18:25
@vgaming is sorta correct:

> The length operator applied on a table returns a border in that table. A border in a table t
> is any natural number that satisfies the following condition:
> 
>      (border == 0 or t[border] ~= nil) and t[border + 1] == nil
> In words, a border is any (natural) index in a table where a non-nil value is followed by a
> nil value (or zero, when index 1 is nil).

So, yes, the length operator (#) should normally return 0 when applied to wesnoth.unit_types. But

> A program can modify the behavior of the length operator for any value but strings
> through the __len metamethod (see §2.4).

So, while surprising that it does not return 0, as long as we document that `#wesnoth.unit_types` returns the number of unit types (so we can tell the programmer to RTFM) we're fine. Frankly, without consulting the Lua manual, I expected the length operator to return a count, not a 'border' and wasn't concerned about what the manual said because it's userdata and pretty much anything goes for userdata.

In any case, it's a confirmed bug since it should not crash and I'll fix it once I get unit_types Lua iteration to be O(1).

**Comment by GregoryLundberg** [comment] 2018-01-19 18:49
Code reading.

@CelticMinstrel Any chance you remember what you were thinking when you wrote this? Why do you expect a Lua global named "base"? The crash is getting the raw value for it (lua_rawget), before you pass it to luaW_getunittype. So I'm assuming you want "base" to be a unit_type name and we're not counting the total number of unit _types but the number of variants for a single type?

I think the length operator (#) should return either 0, or the number of results to expect for pairs(wesnoth.unit_types). In this case, I like it being the number of results. IF someone really objects, changing it to return 0 is trivial.

**Comment by vgaming** [comment] 2018-01-19 18:56
// @GregoryLundberg I do not object, if anything. Your reasoning and quote are valid. I would _personally_ prefer this to be 0, but that's only a vote, I can easily agree to other solutions on this too.

**Comment by GregoryLundberg** [comment] 2018-01-19 19:21
Oh hell. So I'm trying to reconcile the length operator with the pairs() function and after a while of "TILT!" I realized the issue is that whoever it was who said it needs a complete rewrite is partially correct: it needs a design, first.

I am ignoring that pairs(wesnoth.unit_types) does not iterate the unit types, but the unit type variations.

I want the length (#) operator to be O(1) so it's going to be the number of unit types, not variants.

And I highly recommend that nobody use this pile of crap for 1.13 and 1.14; and we can include a complete rewrite for 1.15.

**Comment by CelticMinstrel** [comment] 2018-01-20 02:38
Okay, so about how these things _should_ work:

1. `#wesnoth.unit_types` returns the total number of unit type definitions in the game (not counting variations).
2. `pairs(wesnoth.unit_types)` can be used to iterate through all the unit types, outputting a pair of values: the unit type ID, and the unit type userdata which wraps a value of the C++ `unit_type` class.
3. `wesnoth.unit_types[some_id]` returns the unit type userdata for the specified unit type.
4. `#wesnoth.unit_types[some_id].variations` returns the total number of variations for the unit with the specified ID, including gender variations. Obviously, this will always be at least 1. It needs to count the base variation, the `[male]` or `[female]` variation if present, and any `[variation]`.
5. `pairs(wesnoth.unit_types[some_id].variations)` can be used to iterate through all the variations of the specified unit type. It should return the male variation first, then the female variation, and then any other variations in arbitrary order. (If the unit uses a `[male]` tag it could perhaps swap the male and female variations.)
6. `wesnoth.unit_types[some_id].variations[some_var]` returns the unit type userdata for the specified `[variation]` of the specified unit.
7. `wesnoth.unit_types[some_id].variations.male` returns the unit type userdata for the male variation of the specified unit.
8. `wesnoth.unit_types[some_id].variations.female` returns the unit type userdata for the female variation of the specified unit.

**Comment by CelticMinstrel** [comment] 2018-01-20 03:00
>@CelticMinstrel Any chance you remember what you were thinking when you wrote this? Why do you expect a Lua global named "base"? The crash is getting the raw value for it (lua_rawget), before you pass it to luaW_getunittype. So I'm assuming you want "base" to be a unit_type name and we're not counting the total number of unit _types but the number of variants for a single type?

I think the idea was that the unit types list is a table with a member "base" that, if present, held a reference to an existing unit type for which you want a list of variations for; and if not present, the assumption would be that you want a list of all base unit types in the game. I guess at some point the unit types list was turned into a userdata though, which would break that method.

Perhaps it would be better to just split the thing in two - one userdata represents the list of unit types, while another new userdata represents the list of variations of some unit type.

**Comment by GregoryLundberg** [comment] 2018-01-20 04:47
OK. I will take you comment about how things should work as cannon. It makes sense and should not be hard to implement any missing/broken parts.

Once I'm up to making a PR, I'll reference both Issues and do a checklist like I did for the MP Moderation work.

I'm beginning to wonder if both Issues should be marked as a Blocker for 1.14. I'm estimating a week or so to do all the bench testing and coding and a week or two of review so I'm not sure it's really needed.

**Comment by CelticMinstrel** [comment] 2018-01-20 05:28
(I forgot to mention this explicitly, but `pairs` on the variations list would work the same as it does on the full units list, with the ID being "male" or "female" for the gender variations.)

**Closed** 2018-01-24 17:08 UTC
Labels: Bug, Confirmed, In-progress

**Comment by GregoryLundberg** [comment] 2018-01-24 17:20
I direct pushed the specific fix for the crash.

When I put up a PR to fix the glacial pairs() implementation, I'll add CM's list of operations and part of a TODO checklist on it.

At this point, the only things which work from that list are:

 * #wesnoth.unit_types is O(1) and returns the number of unit types

 * pairs(wesnoth.unit_types), while glacial, does return the key and userdata value for each unit type. There is a lot of lame shit in the function about genders and variations which needs to be deleted.
