### ISSUE TITLE
Non-host clients incorrectly don't disable some add-ons, resulting in OOS when [resistance_defaults] is used.

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#6650] opened 2022-04-28 16:14 UTC
### Game and System Information

- **Version:** 1.16.2

### Description of the bug

Some users have OOSes about a wrong checksum when Undead units (Ghost, Skeleton Archer, Ghoul confirmed) are bought. I haven't yet identified which Wesnoth versions/builds are susceptible because some people with 1.16.2 have it, others don't. Unconfirmed: Steam build.

In the attachments (sorry I zipped bz2 archives cause GitHub rejected bz2) two replays with player CGM. In one of the games (SeeOOS.bz2) he plays undead and when he buys a unit, I see OOS (I have 1.16.2 from flatpak) as well as all players who played with him reported OOS and left.

In another game (DoNotSeeOOS) other guy plays Undead, when he recruits, CGM reports OOS according to the chat, I see nothing

[SeeOOS.zip](https://github.com/wesnoth/wesnoth/files/8584507/SeeOOS.zip)

[DoNotSeeOOS.zip](https://github.com/wesnoth/wesnoth/files/8584513/DoNotSeeOOS.zip)

The problem was reported with other players too, not only CGM

### Expected behavior

No OOS

### Additional context

Recently some fix about OOSes of wrong checksums was merged, maybe it's connected with it? But it was done in Sep, 2021 afaik and some 1.16 builds have trouble and others don't

**Comment by Pentarctagon** [comment] 2022-04-28 22:37
Can you link to the commit? Also is it certain that there were no changes made to one client's mainline units and there were no add-ons installed?

**Comment by Discontinuum** [comment] 2022-04-29 01:06
> Also is it certain that there were no changes made to one client's mainline units and there were no add-ons installed?

My certainty comes from the fact that this problem is observed with different players, and exactly with these units each times. Also if two of those problematic players happen to be in a game together, they don't report OOS on each other

**Comment by Pentarctagon** [comment] 2022-04-29 02:37
If it's specific to certain builds/download sources, then at a minimum we'd need to know where people are downloading from for both those who see the OOS and those who don't.

**Comment by Hejnewar** [comment] 2022-05-12 21:23
The problem seems to be US translation for some reason.

**Comment by Pentarctagon** [comment] 2022-05-12 22:05
That seems... odd? Can you provide more details?

**Comment by Hejnewar** [comment] 2022-05-14 18:54
I dont think I can, I simply went into a game where one of the players had OOS already (with GB translation) and I got nothing, then I tried the same with US translation and suddenly there was quiet a few of them, after that I also tried with PL but I didnt get any OOS with it.

**Comment by Pentarctagon** [comment] 2022-05-14 19:50
Is there anything in the log for when the OOS errors occur?

**Comment by Hejnewar** [comment] 2022-05-16 22:46
I will share the logs whenever I get the chance to get my hands on them. Would you happen to know a way to disable log clearing every so often?

**Comment by Pentarctagon** [comment] 2022-05-16 22:49
I don't believe there's an option for that.

**Comment by Hejnewar** [comment] 2022-05-19 21:37
So I finally managed to obtain the logs and here they are. Just look at the last lines. 

[wesnoth-20220519-233007-11324.log](https://github.com/wesnoth/wesnoth/files/8734370/wesnoth-20220519-233007-11324.log)

**Comment by Pentarctagon** [comment] 2022-05-19 23:06
So the commit mentioned in the OP is 93fe5607a658c74b987eeae25c25d6189ffcdf03, however it doesn't look like that commit was ever applied to 1.16.

Is it possible to check if this same issue happens on 1.17?

**Comment by Discontinuum** [comment] 2022-05-20 00:14
Hm, it wasn't applied? I believe if it was made on Sep, 2021 it would go into 1.16. What if it's the bug that was closed by the commit?

**Comment by Pentarctagon** [comment] 2022-05-20 00:40
1.16 first separated from the master branch in June.

**Comment by Hejnewar** [comment] 2022-05-20 17:53
I can try to check latter. No idea if it will work tho.

**Comment by knyghtmare** [comment] 2022-06-14 12:21
I was able to reproduce this issue with 2 clients on 1.17.4+dev / windows 10 / msys2

[2p — Fallenstar Lake Turn 1.gz](https://github.com/wesnoth/wesnoth/files/8899636/2p.Fallenstar.Lake.Turn.1.gz)
[2p — Fallenstar Lake-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/8899637/2p.Fallenstar.Lake-Auto-Save1.gz)

```
20220614 18:16:31 error replay: SYNC: In recruit Ghoul: has checksum 3Z.8kocoLYhqliGc8hb421i6b,W1z2P58w3cas,cuWhD1+oq3ger79C>>-f,o3ko9cka27,MX+6kP2l>262KxydlLMeKm,F,sIuwiKQ5,h8rkQrdc9NRn8PXwDimdP1. while datasource has checksum clp5<><ex-5J0.yi+m6c65j4jgjcvax-2OW9as,cuWhD1+oq3ger79C>>-f,o3ko9cka27,MX+6kP2l>262KxydlLMeKm1qXNFP+XKre>ggu6HBkeioSHlHcwFnmpNdg
20220614 18:16:57 error replay: SYNC: In recruit Ghost: has checksum .3tnxFGR8KAeyLGCvAqFrNuwG0vBEpEQCxSMTpTHgBmyxKr3tDI.L46NyZDJOwpxzs5bKDRTyPw2IQbwIDspbOHlIR4b-22BpOGP<JUAOCfK.3rfAIqoYKsOI9vwQNAF while datasource has checksum >7CMJBvv>sq0FrtHMIAPAAKQSZttr,QsQnQqI,THgBmyxKr3tDI.L46NyZDJOwpxzs5bKDRTyPw2IQbwIDspbOHlIR4b-22BpTpMbEp<vC8tmpx-TnVvbLyBz5GwqQAt
```

Method of Reproduction:
1. Make 2 clients (doable via terminal/gitbas/cmd prompt)
2. Set language of Client 1 to English_GB
3. Set Language of Client 2 to English_US
4. Join MP server with both clients
5. Start a game with Default Era with any and have the other join
6. One of the factions MUST be Undead
7. On undead side turn, recruit a Ghoul.
8. See error

**Comment by soliton-** [comment] 2022-06-14 16:29
Doesn't reproduce for me either.

@knyghtmare Can you try that again with `--log-debug=unit` on both clients?
It'll spam quite a lof of stuff but when recruiting you should get output of the unit WML or at least the parts that go in the checksum. If you could post that from both clients we should be able to see exactly what is different.

From what I can see the only translatable stuff is indeed the weapon special keys (testing on 1.16) but those should be excluded on 1.17...

**Comment by knyghtmare** [comment] 2022-06-14 17:12
[wesnoth-20220614-230254-14804.log](https://github.com/wesnoth/wesnoth/files/8901990/wesnoth-20220614-230254-14804.log)
[wesnoth-20220614-230311-7444.log](https://github.com/wesnoth/wesnoth/files/8901991/wesnoth-20220614-230311-7444.log)
[2p — Swamp of Dread-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/8901993/2p.Swamp.of.Dread-Auto-Save1.gz)
[2p — Swamp of Dread Turn 1.gz](https://github.com/wesnoth/wesnoth/files/8901994/2p.Swamp.of.Dread.Turn.1.gz)

**Comment by Discontinuum** [comment] 2022-06-14 17:15
@knyghtmare could you also please watch two replays in my first post here?
If my assumptions are correct, you should see OOS on SeeOOS in English GB and on DoNotSeeOOS in English US, and vice versa

**Comment by knyghtmare** [comment] 2022-06-14 17:17
Wait...I got this OOS when both clients EN_GB...set..only noticed it now...huh...

**Comment by Discontinuum** [comment] 2022-06-14 17:19
Hm, in your logs the unit has difference here
```
[resistance]
	arcane = 80
	arcane_focus = 120
	blade = 90
	cold = 60
	electric = 110
	energy = 120
	fire = 90
	impact = 100
	pierce = 70
[/resistance]
```
what are those strange arcane_focus, electric, energy damage types?

**Comment by knyghtmare** [comment] 2022-06-14 17:22
> Hm, in your logs the unit has difference here
> 
> ```
> [resistance]
> 	arcane = 80
> 	arcane_focus = 120
> 	blade = 90
> 	cold = 60
> 	electric = 110
> 	energy = 120
> 	fire = 90
> 	impact = 100
> 	pierce = 70
> [/resistance]
> ```
> 
> what are those strange arcane_focus, electric, energy damage types?

I am pretty sure MP deactivates non-use addons...how'd they get there?

**Comment by Discontinuum** [comment] 2022-06-14 17:23
they are even not default 100, I'd notice

**Comment by knyghtmare** [comment] 2022-06-14 17:26
I reproduced it again on Spanish client and English GB this time...so I think different translations used by clients might be related not just En_US

@Discontinuum I will try with a fresh userdata client (no addons) and post the logs and such here

**Comment by knyghtmare** [comment] 2022-06-14 17:50
> If my assumptions are correct, you should see OOS on SeeOOS in English GB and on DoNotSeeOOS in English US, and vice versa

Results: 
I did see OOS on SeeOOS in EN_GB
I did see OOS on DoNotSeeOSS in EN_US
[wesnoth-20220614-234502-14264.log](https://github.com/wesnoth/wesnoth/files/8902236/wesnoth-20220614-234502-14264.log)

This time I got these on a vanilla client (no addons)

**Comment by Discontinuum** [comment] 2022-06-14 18:35
The second log without oos to compare would be handy (in the vanilla case)

**Comment by Wedge009** [comment] 2022-06-15 05:06
I don't think I'm able to replicate this, but I'm also not sure what I'm supposed to be looking for. I tested master at 557738dd495 on Linux and Windows without anything obviously showing wrong in the logs. Different locales between the clients, undead units as specified.

**Comment by Discontinuum** [comment] 2022-06-25 15:28
So, I found that I started to have this bug when I have "War of Legends" addon installed. When I have it installed, all units start to have addon-specific resistances. Probably it causes the checksum mismatch, as the host doesn't have them most likely. So I see

![изображение](https://user-images.githubusercontent.com/68666085/175780208-96fe2991-36a7-4421-8947-58bfa7f116d2.png)

When I delete this code from the War of Legends _main.cfg, I stop getting OOS
```
[units]
    #this is working as intended
    [resistance_defaults]
        id="electric"
        default="100"
        undeadfly=130
        undeadfoot=130
        undeadspirit=110
        gruefoot=110
    [/resistance_defaults]

    [resistance_defaults]
        id="energy"
        default="120"
    [/resistance_defaults]

    [resistance_defaults]
        id="arcane_focus"
        # please do not ask me why I did
        # this but this works so, yeah...
        default="( 200 - (resistance.arcane) )"
    [/resistance_defaults]
[/units]
```

So addon isolation seems not working good in this case.

What is mystery though is why I have OOS only on undead, but not on other units

**Comment by knyghtmare** [comment] 2022-06-25 15:30
@Discontinuum 
Transfer the issue to WoL's repo. Since I think I have to fix this on my end.

**Comment by Pentarctagon** [comment] 2022-06-25 20:09
Is it definitely confirmed that WoL is causing the issues? If yes then that's a good step forward, but it still doesn't seem to explain why it only affects certain units or why the selected language would matter.

**Comment by Discontinuum** [comment] 2022-06-25 22:40
WoL causes the issue, but seems not only WoL. I witnessed another player having the issue but he said he doesn't have WoL installed. Maybe some other of his addons, dunno. He had a custom build.
At least WoL is one of the triggers, but possibly there are more

**Comment by knyghtmare** [comment] 2022-06-28 02:09
I am unable to produce this bug with WoL as I do not know the other conditions here. I tried networked 1v1 matches with Default Era while having the addon installed and it never happens. Thus, I request more information. Wesnoth version, list of addons installed, list of addons of both host and client, etc.

**Comment by Discontinuum** [comment] 2022-06-28 08:53
WoL, the server version of it; one player doesn't have WoL, another does have; one of the players play undead

**Comment by CelticMinstrel** [comment] 2022-06-28 12:39
Sounds like this has nothing to do with undead and everything to do with movetype patching. I guess the units have different resistances on the two machines? So the question would be, why is the movetype patching of an inactive addon being applied?

**Comment by Discontinuum** [comment] 2022-06-28 13:26
Well, still there is an additional question, as OOS appears only on undead units. And the resist of all units are changed, so it's kinda strange

**Comment by Discontinuum** [comment] 2022-06-30 01:46
Strange, I've installed WoL again and can't reproduce either now. But I know longer see those resists in not WoL games. Super strange, seems like addon isolation in this aspect not entirely broken, it works or doesn't work with some other condition.

About those lines: I tested before when I had that OOS - no, those alone doesn't help. When I had oos, I had to remove all those lines
```
[units]
    #this is working as intended
    [resistance_defaults]
        id="electric"
        default="100"
        undeadfly=130
        undeadfoot=130
        undeadspirit=110
        gruefoot=110
    [/resistance_defaults]

    [resistance_defaults]
        id="energy"
        default="120"
    [/resistance_defaults]

    [resistance_defaults]
        id="arcane_focus"
        # please do not ask me why I did
        # this but this works so, yeah...
        default="( 200 - (resistance.arcane) )"
    [/resistance_defaults]
[/units]
```
so all resistance_defaults

**Comment by knyghtmare** [comment] 2022-07-02 10:26
did the recent WoL update solve the issue? I am not getting it myself so need a second or third opinion.

**Comment by Discontinuum** [comment] 2022-07-08 22:04
No, it doesn't. But I got some more strange things to tell.

This week I had old WoL installed and, as I said, no bug was observed. And no extra resist types appeared. And then suddenly this night it started again, after I updated some other addons. And extra resist types are here again. So it seems that
1. it's a floating bug, unfortunately,
2. it may have something to do with addon sequence or whatnot

**Comment by knyghtmare** [comment] 2022-07-08 22:11
> after I updated some other addons

Full list?

> it's a floating bug, unfortunately,

A heisenbug? No wonder it appears and disappears at will.

**Comment by Discontinuum** [comment] 2022-07-20 01:12
> @Discontinuum what is your list of add-ons?

My list of addons in a Wesnoth instance I got the bug is excruciatingly long, with many addons not on the addon server (tests or addons I develop). I think it contains a lot of not related stuff. When I have spare time I'll try to experiment in a cleaner environment

**Comment by knyghtmare** [comment] 2022-07-20 20:54
How is a **"World Conquest"-only** modification interfering with non-WC games?
That's my primary inquiry.
It's also switched off by default unless the player switches ON it for WC-games.

also, `[modification]` doesn't exactly have a `allow_campaign=` attr for me to use. Only `allow_scenario=' but that hardly works for a MP campaign.

**Comment by Pentarctagon** [comment] 2022-07-20 21:58
My guess is that it's not the modification that's causing the problem, rather it's that the host is correctly not enabling WoL whereas the other clients are enabling it. The host enabling Legends Conquest results in there being no OOS since enabling that modification means both the host and the other clients end up with WoL being enabled.

So I think the question is: why do the host vs non-host clients have different add-ons enabled?

It also seems somewhat similar to #6285, except in reverse - in #6285 the host was loading the correct WML while the other clients were incorrectly disabling add-ons, whereas here the host is loading the correct WML while other clients are incorrectly enabling add-ons.

**Comment by Pentarctagon** [comment] 2022-07-21 21:58
A minimal test add-on that allows reproducing the OOS: [test_resistance_defaults.zip](https://github.com/wesnoth/wesnoth/files/9163026/test_resistance_defaults.zip)

**Comment by knyghtmare** [comment] 2022-07-21 23:12
> did the recent WoL update solve the issue? I am not getting it myself so need a second or third opinion.

Fixed on my end with the latest update which was uploaded a minute ago. Both servers. I think.

**Comment by Discontinuum** [comment] 2022-07-22 12:13
In which version #6285 was fixed? What if the fix is responsible for the appeared bug?

**Comment by Pentarctagon** [comment] 2022-07-25 19:14
a4e8ac339eabcd94f337ad809d10de2a70272ba7 is the commit that is causing this issue, which unfortunately I can't just revert since it fixed a different issue that players were having.

**Closed** 2022-07-26 15:22 UTC
Labels: Bug, Confirmed, MP
