### ISSUE TITLE
[unit] should update fog (GNA #20656)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1333] opened 2017-05-08 07:30 UTC
**[Original submission](https://gna.org/bugs/index.php?20656)** by anonymissimus on 2013-03-26

In the attached save ("Flaming Sword" from Dead Water), move Gwabbo (9, 23) to the village at 14, 18. After the dialog and unit placement, it is clearly visible that Dorcyn (20, 18) can move farther to the east and northeast, but those areas are still covered by fog. It doesn't matter whether DSU is on or off, and even "update shroud now" doesn't lift the fog. (This I consider the real bug apart minor problems, such that units speak under fog.) Moving Dorcyn a hex does, as does "updating shroud now" after such move, in case DSU is enabled.

Thus, some functionality is missing from the [unit] tag implementation, and possible sighted events would be fired too late, if at all.

(Reproduced on win xp)
Release: 1.11.2+svn@r56594
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:30
**Modified on 2013-03-26**

**anonymissimus added attachment:** [SW-Das_Flammenschwert_Runde_2.gz](http://gna.org/bugs/download.php?file_id=17552)

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:30
**Modified on 2013-03-26**

**anonymissimus changed severity:** 3 - Normal -> 2 - Minor

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:30
**Modified on 2013-03-26**

**anonymissimus changed priority:** 5 - Normal -> 3 - Low

**Comment by Wedge009** [comment] 2017-05-09 21:57
Marking as confirmed, as I recall testing this some time ago.

**Comment by stevecotton** [comment] 2021-09-15 15:54
Clearing the assignment, as it was assigned 4 years ago.

@Wedge009 - I've just put a suggestion in #1964 to close one of these two as a duplicate of the other.

**Comment by Wedge009** [comment] 2021-09-15 16:03
Sounds good.

**Closed by Wedge009** 2021-09-15 16:03 UTC
Labels: Bug, Confirmed, WML, Good first issue
