### ISSUE TITLE
Missing codepoints 

### ISSUE THREAD

**Issue by galegosimpatico** [wesnoth/wesnoth#2627] opened 2018-03-10 21:27 UTC
Missing codepoints for some characters (https://en.wikipedia.org/wiki/Shavian_alphabet ¿?).

![https://frupic.frubar.net/shots/36543.png](https://frupic.frubar.net/shots/36543.png)
[https://frupic.frubar.net/36543](https://frupic.frubar.net/36543)

TBfW `1.13.11` for macOS, official binaries `Wesnoth_1.13.11.dmg` (size 424.149.414b sha256 `aa5cea07f6465bf5fa41736f22f3141ea7db3c88fd3c3b08bdc3aff0c9a0cff1`). Using macOS High Sierra.

**Comment by CelticMinstrel** [comment] 2018-03-10 22:03
That translation will probably be hidden from the Steam release though, since it's not really a _useful_ translation. If it happens for _other_ translations though, that could be a problem.

**Comment by gfgtdf** [comment] 2018-03-10 22:13
see also https://github.com/wesnoth/wesnoth/issues/1549

**Comment by Vultraz** [comment] 2018-03-11 03:16
Yeah, it's a duplicate of #1549.

**Closed by Vultraz** 2018-03-11 03:16 UTC
Labels: Bug, Duplicate, UI
