### ISSUE TITLE
Hide "Registered Users Only" checkbox if server only accepts guests or only accepts registered users

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2939] opened 2018-04-21 18:55 UTC
Said checkbox can be seen at game creation dialog (along with "Shuffle sides" checkbox and others).

However, this option does not make sense, if we're joining a server that forbids any kind of un-registered users. Also it doesn't make sense if we're joining a server that does not have any registered usernames at all.
It could make sense to hide or remove said checkbox when joining such server.

**Comment by vgaming** [comment] 2018-04-21 19:01
Possible implementations:
* remove the option altogether, because there's only a very narrow situation where such checkbox would be needed (considering our current 1.14 server).
* make wesnothd server advertise it's "registeration" capabilities, and only show the checkbox if we're joining a "reg"-capable server.

**Comment by soliton-** [comment] 2018-04-22 09:34
The question mark in the title sure makes it look like a question to start a discussion.

**Comment by vgaming** [comment] 2018-04-22 09:42
@soliton- indeed.
I'm used to place a question mark for requests (personal or IT). Like a question to do something rather than a demand. But I should probably change that habit as it seems to be very non-common (maybe incorrect at all, not sure).

**Comment by Wedge009** [comment] 2019-09-04 12:00
I suppose it's a valid idea, but any reason why it should be specific to 1.14? Just from reading this I'm not seeing any.

**Comment by vgaming** [comment] 2019-09-04 12:32
@Wedge009 I've added this checkbox because 1.14 was the version starting from which registered only users were allowed into main official server. It's as much applicable to e.g. 1.15 as well I think. I removed the label.

**Comment by soliton-** [comment] 2019-09-04 12:58
The client doesn't know the configuration of the server. There would have to be some messages on connect that inform the client of relevant server settings. And then the settings can change at run-time...

**Comment by vgaming** [comment] 2019-09-05 09:07
Interesting, I didn't know the setting can change at run-time (without restarts). I'm OK with closing the issue as I see no solution that would not increase complexity of the server and client.

**Comment by vgaming** [comment] 2019-09-05 09:15
EDIT ^

**Comment by jostephd** [comment] 2019-09-14 11:27
How about:

- When using `Join Official Server`, have the checkbox ticked and disabled.
- When using `Connect to Server`, have the checkbox unticked and enabled.

Layering violation, I know, but it removes a pointless decision from players who create games on the official servers.

**Comment by vgaming** [comment] 2019-09-24 11:44
I'd be in favor of that, considering that it indeed removes a pointless decision for players on official server (and doesn't change anything for the rest).

**Comment by Wedge009** [comment] 2019-09-24 15:09
What would be the best way to determine the server is official? Or just go with hard-coded check against wesnoth.org?

**Comment by vgaming** [comment] 2019-09-24 17:32
@Wedge009 the intention I think was to make this choice based on the button used in the main menu. So if e.g. you join to the same official server by manually typing in the correct address and port, you'll have it differently.

I'm not sure how many changes are needed code-wise though, but I presume it should be quite straightforward actually.

**Comment by gfgtdf** [comment] 2019-09-24 18:38
> I see no solution that would not increase complexity of the server and client

I don't see a problem with that, that is adding a message send by the server that basically says 'disable registered user only checkbox'. It's likeley that it can be done in a backwards compatible way that is just ignored by older clients.

**Comment by Wedge009** [comment] 2019-10-22 23:04
It's not as straight-forward as I thought, to communicate the MP selection to the MP lobby. The MP selection is in the helpfully-named `mp_method_selection`:
https://github.com/wesnoth/wesnoth/blob/d52783a7eaf9e254b7f552c54228d007c7f5af8f/src/gui/dialogs/multiplayer/mp_method_selection.cpp#L78

And that gets used in the title-screen call-back:
https://github.com/wesnoth/wesnoth/blob/d52783a7eaf9e254b7f552c54228d007c7f5af8f/src/gui/dialogs/title_screen.cpp#L505-L529

**Comment by jostephd** [comment] 2019-10-24 06:04
@Wedge009 And what's the problem? That `MP_CONNECT` is used here:

https://github.com/wesnoth/wesnoth/blob/f2de9621fab6185b3752d5068179df03d5152c02/src/wesnoth.cpp#L927-L932

**Comment by Wedge009** [comment] 2019-10-24 13:00
The problem is that I'm slow to understand complex pre-existing code that's not my own. I'm sorry.

But I followed `play_multiplayer()` -> `start_client()` which then seems to go into the display loop for the MP lobby. I'm not sure of the connection between this and `mp_create_game::pre_show()` which does the set-up of the MP create game screen (where the 'registered users only' option is present).

I understand you're busy, there's no need to respond if you don't have time.

**Comment by jostephd** [comment] 2019-10-25 01:47
Don't apologize! I'm glad you're looking into these issues. I was just trying to point out that you didn't actually say _what_ you didn't understand, which made it hard to illuminate the next step for you.

The sequence is:

do_gameloop -> play_multiplayer -> start_client -> enter_lobby_mode -> enter_create_mode -> mp_create_game

mp_create_game::pre_show will be called by these two lines:

https://github.com/wesnoth/wesnoth/blob/cd7ed4c0899fe3075b7a80c25e38947a228bc666/src/game_initialization/multiplayer.cpp#L522-L523

Now, what we need is for mp_create_game to know whether it's creating a game on the official server, or on something else (non-official server or local MP). I'm not sure what's the best way to do this, whether we should pass the info down the call chain from where it's available to where it's needed, or whether there's some place to put a piece of global state in, have do_gameloop or play_multiplayer set this global state and mp_create_game check it.

**Comment by Wedge009** [comment] 2019-10-25 09:07
I missed the link into `enter_lobby_mode()`, thank you. I'm also not sure where is the best place to make the server address available. The code drops any information about the address once it has opened the connection (which is in `start_client()`) - I suppose that makes sense because you don't necessarily need to know what specific wesnothd instance you're talking to once the connection is made.

Anyway, I decided to pass that official server information from `start_client()` to `mp_create_game()`. It feels a bit redundant though because `local_mode` and `official_server` are mutually exclusive, though they are derived by different means. I suppose it's up to reviewers to decide if it's worth doing it my way or not.

Also, I just realised an issue with master: at the moment unregistered users are permitted on development (1.15) server while the stable (1.14) server does not (the latter being the reason for this change). If this change is applied to master that means users cannot use unregistered accounts on 1.15 'official' server any more. Would this make sense?

Another thing I noticed: I think `host_info_->registered` in `mp_create_game` is always going to be false on an unofficial server so that also triggers the disablement of the 'registered users only' option. The only thing that changes with my PR is that the official server's 'registered users only' option is now always checked and made disabled. So in effect this makes that option completely redundant, which I think is the reasoning for @vgaming's original request to hide this option altogether.

**Comment by Wedge009** [comment] 2019-10-27 11:36
See #4517 talking about a 'disallow unregistered log-in' flag within the server. I'm not working any further on this.

**Comment by Vultraz** [comment] 2020-12-26 01:34
Closing as moot since the Registered Users Only checkbox was removed in 9376cf42af5c1f82bc048228c1a25ed0edf5f606 (see #5196

**Closed by Vultraz** 2020-12-26 01:34 UTC
Labels: Enhancement, MP Lobby, Network

**Comment by vgaming** [comment] 2020-12-26 09:41
@Vultraz thanks for noticing and clearing the issue (I didn't know) :+1:
