### ISSUE TITLE
Wesnoth could not start from windows command line.

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#1929] opened 2017-09-01 19:15 UTC
Windows 7 Pro x64
Wesnoth 1.12.6

Just tried to add Wesnoth install path (I've installed it with option "all data would be saved in Wesnoth directory") to Windows PATH variable. And wanted to start Wesnoth by just writing "wesnoth" in command line. But there is the error and Wesnoth didn't start.

![cmd_wesnoth_error](https://user-images.githubusercontent.com/10855248/29984408-05b341f2-8f63-11e7-89dc-191a4ff94535.png)

**stderr.txt**
20170901 22:05:19 error filesystem: Could not open 'C:/Users/amok\userdata/preferences' for reading.

Data directory: 
User configuration directory: C:/Users/amok\userdata
User data directory: C:/Users/amok\userdata
Cache directory: C:/Users/amok\userdata\cache

**Comment by gfgtdf** [comment] 2017-09-01 20:09
does it work when you move to the wesnoth1.12.6 folder where wesnoth is installed and start it there?


Also iirc the "all data would be saved in Wesnoth directory" option was removed recently so ths bug probably doesn't apply to wesnoth 1.13.8

**Comment by Wedge009** [comment] 2017-09-02 07:36
May be a stupid question, but does the game work through GUI means at all? eg double-click on file name in explorer. Title implies it's an issue with the command-line but could just be a configuration issue. I wonder if use of the ! in the program path is a problem.

**Comment by amokmen** [comment] 2017-09-02 19:09
@gfgtdf: Yes, trying to start from game directory works as a charm:
>D:\!user\progs\Wesnoth1.12.6>wesnoth

@Wedge009: I doubt that "!" in path to wesnoth.exe is problem.

**Comment by Wedge009** [comment] 2017-09-04 05:53
Oh I see what you're trying to do now. Well, I just did the same thing - confirmed for 1.12, but not for master/1.13.

**Comment by Wedge009** [comment] 2017-09-04 07:34
The [if-block within int main() of game.cpp](https://github.com/wesnoth/wesnoth/blob/1.12/src/game.cpp#L793) tries to detect the path on the basis of where it can find data files relative to get_exe_dir(). However, the implementation of the get_exe_dir() function in Win32 builds is just the [current working directory](https://github.com/wesnoth/wesnoth/blob/1.12/src/filesystem_boost.cpp#L649), so this obviously fails.

In master, @jyrkive fixed this to at least attempt to find the [path where the executable is being called from](https://github.com/wesnoth/wesnoth/blob/master/src/filesystem_boost.cpp#L674), so the rest of the path manipulation code works as expected.

I back-ported this change in get_exe_dir() from master to 1.12 branch (702be574 - originally from #571), and tested that this resolves the issue. At this point I don't think it's worth bringing in the rest of the commits from that PR as well.

**Comment by soliton-** [comment] 2018-03-26 00:04
So this is fixed then?

**Comment by Wedge009** [comment] 2018-03-26 02:16
My recollection was that it was, but I never got a response from @amokmen, plus we haven't had any further releases on 1.12 since then (that I'm aware of). But you're right, this can probably be closed. I'd just prefer to have someone else confirm the resolution.

**Comment by gfgtdf** [comment] 2018-03-26 02:22
iirc the plan was to close all bugs marked as backport/Stable 1.12 when 1.14 comes out.

**Comment by Wedge009** [comment] 2018-03-26 02:31
Sounds fair to me - on the assumption that 1.14 becomes the supported stable release and 1.12.x is declared obsolete. I haven't been around during a major stable release before so I don't know how smooth the transition is.

**Comment by Wedge009** [comment] 2018-05-02 16:08
Closing upon 1.14 release.

**Closed by Wedge009** 2018-05-02 16:08 UTC
Labels: Backport, Bug, Confirmed, Stable 1.12
