### ISSUE TITLE
Time for an SDL Upgrade to Support Metal? 

### ISSUE THREAD

**Issue by anakayub** [wesnoth/wesnoth#5737] opened 2021-04-25 03:17 UTC
### Game and System Information
 - What version of the game are you running? 1.15.12
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.) From source
 - If you're using a custom build, what compiler did you use, and what commit did you build at? XCode, -Ofast, monolithic link time optimization, unroll loops
 - What OS are you running? MacOS Big Sur
 
### Describe the desired feature
I wonder if it's time to increase the SDL that is included with the Mac version. Apparently I found performance issues when playing on my 16 inch MacBook Pro with a core i9 and discrete graphics on full screen, especially when the map is full of animation. Please see my point here: https://forums.wesnoth.org/viewtopic.php?p=664523#p664523. The performance was much better when I used SDL 2.0.12 (I couldn't get 2.0.14 to compile), but at the cost of a bug of a red line on the bottom and right edges of the screen. I'm not sure if this is due to me using all available optimization options, especially -Ofast even with SDL. 

This performance gain is probably due to the available Metal support when looking through the source (SDL_config_macosx.h). But the big problem is that at least in SDL 2.0.12 the Metal support is only available when targeting for MacOS 10.11 onwards.  I'm not sure of the minimum version of SDL that supports Metal and adequate backwards compatibility. For personal use (and a non-programmer even during my ancient days helping do the Mac Packaging) I can live with the bug if it means drastically better performance, but maybe a project-level discussion may be needed as regards to the minimum SDL used, especially if Metal support is available for older versions of MacOS.

![Screenshot 2021-04-24 at 5 51 29 AM](https://user-images.githubusercontent.com/42091252/115978927-4e85fe80-a5b5-11eb-8a41-adc1466207c7.png)
<img width="850" alt="Screenshot 2021-04-24 at 5 52 11 AM" src="https://user-images.githubusercontent.com/42091252/115978930-52b21c00-a5b5-11eb-8fa4-b2c3333a0387.png">

Comparison of Dark Forecast and Isle of Mists "without Metal"
<img width="917" alt="Screenshot 2021-04-25 at 10 54 21 AM" src="https://user-images.githubusercontent.com/42091252/115978916-4332d300-a5b5-11eb-9d7b-21b23534396f.png">

Metal support with SDL 2.0.12
<img width="1792" alt="Screenshot 2021-04-25 at 10 13 51 AM" src="https://user-images.githubusercontent.com/42091252/115978908-3a420180-a5b5-11eb-9aad-1c87677cb4de.png">

Better performance with SDL 2.0.12. Notice the red lines.
<img width="1792" alt="Screenshot 2021-04-25 at 11 03 41 AM" src="https://user-images.githubusercontent.com/42091252/115979020-06b3a700-a5b6-11eb-8a7a-0b863dc6997a.png">

Even better performance on Dark Forecast with Metal. Notice the red lines.

### Screenshots
If applicable, add screenshots or mockups to help explain your request.

**Comment by Pentarctagon** [comment] 2021-04-25 03:50
@hrubymar10 what version of SDL is macOS packaged with currently?

**Comment by anakayub** [comment] 2021-04-25 05:46
By the way, this may be related with issue #5735

**Comment by Pentarctagon** [comment] 2021-04-25 06:42
Increasing the minimum to 2.0.12 for the whole project wouldn't be possible due to Linux distributions still needing older versions.

**Comment by hrubymar10** [comment] 2021-04-25 07:28
Wesnoth 1.15.12 uses SDL 2.0.12 . macOS packages use SDL 2.0.12 for long time already.

**Comment by anakayub** [comment] 2021-04-25 11:09
<img width="1792" alt="Screenshot 2021-04-25 at 7 03 03 PM" src="https://user-images.githubusercontent.com/42091252/115991031-f8d34580-a5f8-11eb-9758-987348cfccbd.png">
I downloaded the binary and tested; performance is affected.

Would Metal support only be available if we target >= 10.11 (El Capitan) when compiling SDL? Our BfW Xcode project itself targets 10.11 already.

**Comment by Pentarctagon** [comment] 2021-04-25 16:41
I'm confused now how any performance difference could be attributed to using SDL 2.0.12+ and targeting macOS 10.11+ if Wesnoth's projectfiles are already doing that.  What are the full set of steps you did to build Wesnoth, particularly anything done differently than is mentioned [here](https://github.com/wesnoth/wesnoth/blob/master/projectfiles/Xcode/README.md)?

I'm also not sure if the specific performance improvements in the screenshots can be considered entirely valid given the use of `-Ofast` as well as loop unrolling to a lesser extent.  "monolithic link time optimization" I assume means LTO?

Additionally, your screenshots showing the FPS performance difference don't seem to be taken in identical circumstances - the ones showing low FPS have much more water than the ones showing high FPS, and animated water is known to decrease FPS.

**Comment by anakayub** [comment] 2021-04-25 20:44
Sorry if I wasn't clear. I've provided now 3 water heavy screenshots, all directly after loading a save, full screen. In order of when I attached them so far:

1) Built with the project file entirely and thus the libs compiled by hrubymar10. 6 FPS

2) Same Xcode project file, but with SDL self-compiled as a framework. The Xcode project of SDL 2.0.12 by default targets MacOS 10.6. Self-compiled, I targeted 11.3, turned on yes LTO, loop unrolling and -Ofast (which skews the results somewhat, but the change in frame rate is just too big). Then the Wesnoth Xcode project uses that SDL instead. 57 FPS

3) The Mac binary from Sourceforge. 7 FPS

4) Just to be sure, here is a screenshot with LTO and loop unrolling off and -Os for SDL, targeting 11.3. 56 FPS and no more "red line window edges"
<img width="1792" alt="Screenshot 2021-04-26 at 3 56 12 AM" src="https://user-images.githubusercontent.com/42091252/116007647-6c01a980-a643-11eb-85a1-28fbf779a469.png">

There has to be some difference somewhere to account for the difference in performance other than simple just compiling optimizations, and I wonder if SDL not using Metal somehow some way is the source of it. I wish I know how to interpret Xcode's Instruments, but I hope someone of expertise can interpret it and find the solution to potentially better performance. The top is the run with scenario 4, the bottom scenario 3 (open app, load save, open fps counter, quit to main menu, quit app).
<img width="1280" alt="Screenshot 2021-04-26 at 4 37 30 AM" src="https://user-images.githubusercontent.com/42091252/116008955-732bb600-a649-11eb-8d6c-45d81de0170e.png">


Thanks for your time.

**Comment by Pentarctagon** [comment] 2021-04-25 21:48
Well, if you want to know if it's just caused by making SDL target 10.11 instead of 10.6 and nothing else, make only that change, recompile, and see if the FPS increase is still there.

**Comment by anakayub** [comment] 2021-04-25 22:23
Just did as suggested

Opened a new project, changed SDL target to 10.11, linked to the Wesnoth project (also new) --> 57 fps
Deleted the references to self-compiled SDL, relinked to use the currently used SDL dylib --> 6 fps

**Comment by Pentarctagon** [comment] 2021-04-25 22:59
@hrubymar10 is changing the SDL target something that would be able to be done, or are there reasons to leave it as it is currently? If there's no downside to changing the SDL target, could you check and confirm whether the FPS improvement happens for you as well?  If it's possible to improve the FPS by ~10x just by updating the SDL library target macOS version, then that sounds pretty amazing.
@anakayub can you upload a save of the scenario you used for testing the FPS so that hrubymar can test using the same game conditions?

**Comment by anakayub** [comment] 2021-04-26 00:17
Sorry I’ll be away for at least half a day, but I originally played this on the MP server alone with the Isle of Mists scenario:
https://replays.wesnoth.org/1.15/2021/04/21/

**Comment by Pentarctagon** [comment] 2021-05-06 17:58
Also, out of curiosity, what exactly did you change to tell SDL to target 10.11+?  Was it something in Wesnoth's xcode setup or somewhere else?

**Comment by anakayub** [comment] 2021-05-06 22:55
What I'll explain here discounts the tribulations and real world time lost before lol

To be consistent, I initially tried to compile SDL 2.0.14 as a dylib via the command line to be consistent with hrubymar10's Wesnoth libraries. However, it seems I need libxext when running `./configure,` which I somehow could never get it right as I could not install libxext manually and the ones previously installed via MacPorts were somehow not found when configuring...But as I type this, both 2.0.12 and 2.0.14 are compiling at last (I've no idea what made it successful as I've stopped any compiling experimentation before this reply).

Anyways, the change in mention is in SDL's included Xcode project (SDL2-2.0.12/Xcode/SDL) involving the deployment target:
<img width="868" alt="Screenshot 2021-05-07 at 5 57 53 AM" src="https://user-images.githubusercontent.com/42091252/117370664-50c35380-aef9-11eb-9575-568872029d90.png">
The Xcode project however only compiles SDL as a .framework instead of a .dylib.
For the purpose of this "issue" I've left other settings as is except for the deployment target targeting 10.11 instead, but for my personal use I've subsequently targeted 11.3 and turned on LTO and `-O3`. For reference, SDL's default target is the MacOS released in 2009 (from the project of a freshly unzipped source):
<img width="863" alt="Screenshot 2021-05-07 at 6 18 30 AM" src="https://user-images.githubusercontent.com/42091252/117372465-26bf6080-aefc-11eb-8473-37e1b35990ea.png">


This framework was subsequently used in Wesnoth's Xcode project: 
<img width="792" alt="Screenshot 2021-05-07 at 6 08 29 AM" src="https://user-images.githubusercontent.com/42091252/117371557-ab10e400-aefa-11eb-99e0-673f5d614b40.png">
For the purpose of this issue changing SDL was all I did.
For personal use I've also subsequently used self-compiled libs for many others libs, but not all due to unexplained (to me) linker errors during runtime. For personal use (and not for this issue) I also subsequently turn on similar optimizations as SDL and also unrolled loops + profile guided optimization. Another thing to note is that due to wasted time trying to deal with code signing with my self-compiled libs I turned off Library Validation.

Now that SDL actually compiled as a dylib via command line I might try recompiling using that instead. But I might need to play around with flags (e.g. `-mmacosx-version-min=10.11` etc). 

However, as I'm typing this, it seems that running `otool -l` on our default SDL dylib (compiled by hrubymar10) shows that it's already targeting 10.11 minimum! So I'm now at a loss why are there performance differences. I'll have to check out if there are differences when self-compiling dylibs via command line and xcode for both 2.0.14 and 2.0.12 targeting 10.11 myself compared to our default SDL dylib used. But this will take real world time I need to take back at the moment.

As a reference, my current personal build runs at 84 fps the reference save:
<img width="1792" alt="Screenshot 2021-05-07 at 6 52 07 AM" src="https://user-images.githubusercontent.com/42091252/117375141-034ae480-af01-11eb-8e89-61615eb48212.png">

I hope excessively explaining things help.

**Comment by Pentarctagon** [comment] 2021-05-06 23:29
Huh, alright.  The scripts that are used currently to build all the macOS dependencies can also be found at https://github.com/hrubymar10/MacCompileStuff by the way.

**Comment by anakayub** [comment] 2021-05-09 06:09
I've tried out my command line build of SDL I mentioned earlier and was getting an increase. I've been going through the scripts, trying to experiment where the differences are, but nothing helped so far.

**Comment by CelticMinstrel** [comment] 2021-05-11 01:22
I'm a little confused at how metal support is helpful. Aren't we using software rendering? Metal is hardware rendering, right? I can see that something you're doing does help performance, but I question if it has anything to do with Metal…

**Comment by anakayub** [comment] 2021-05-13 19:46
Time to go to bed after much experimenting, but before that...

No changes in modifying the SDL2_build script made any difference. However, when going through the env file, it seems that the script already targets 10.11 which in theory should work with metal. I've spent time doing changing the variables to see any changes:

Change them all to 10.12, 10.13 and 11.0 --> No changes
Comment out lines 29-33 altogether --> Interesting
<img width="1792" alt="Screenshot 2021-05-14 at 2 56 47 AM" src="https://user-images.githubusercontent.com/42091252/118175509-c59b0e00-b462-11eb-8089-6b506fde706d.png">

Why would there be a difference beats me. Does the `-stdlib=libc++` flag make any  difference? It's almost 4 here hahaha. I think others need to help confirm my findings.

**Comment by Pentarctagon** [comment] 2021-05-13 20:25
I'd suggest removing things one line/flag at a time to see exactly when it changes.

**Comment by anakayub** [comment] 2021-05-14 02:43
That last point is interesting as the whole point of me targeting 11.0 is to target my own computer.

**Comment by anakayub** [comment] 2021-05-14 14:30
Great news. Commenting out lines 30-33 (related to LD, C and CXXFLAGS) and leaving behind the MACOSX_DEPLOYMENT_TARGET (on line 29) variable set to 10.11 seems to do the trick:
<img width="1792" alt="Screenshot 2021-05-14 at 8 14 26 PM" src="https://user-images.githubusercontent.com/42091252/118283359-dd759f00-b501-11eb-8940-3c1d1018750c.png">

Why this is so is beyond me. Earlier tried to do a build where all of the libraries are built with this env set, but I met a familiar stumbling block related to vorbis, which I've met before when self-compiling [https://gitlab.xiph.org/xiph/ogg/-/commit/c8fca6b4a02d695b1ceea39b330d4406001c03ed](url). When I'm free I'll try to get 1.15 sorted out to see the full extent of the performance uplift. Another thing is that I think this should be able to be applied to 1.14 as well.

**Comment by Pentarctagon** [comment] 2021-05-14 14:33
1.14 targets an earlier macOS version, so that likely wouldn't be possible.

**Comment by Pentarctagon** [comment] 2021-05-17 15:36
Also, as of #5746 using the `:fps` command will write out the FPS values to a spreadsheet on disk, so that would be a more accurate way to be able to measure FPS variations.

**Comment by cooljeanius** [comment] 2021-05-30 03:53
> Great news. Commenting out lines 30-33 (related to LD, C and CXXFLAGS) and leaving behind the MACOSX_DEPLOYMENT_TARGET (on line 29) variable set to 10.11 seems to do the trick:
> <img alt="Screenshot 2021-05-14 at 8 14 26 PM" width="1792" src="https://user-images.githubusercontent.com/42091252/118283359-dd759f00-b501-11eb-8940-3c1d1018750c.png">
> 
> Why this is so is beyond me. Earlier tried to do a build where all of the libraries are built with this env set, but I met a familiar stumbling block related to vorbis, which I've met before when self-compiling [https://gitlab.xiph.org/xiph/ogg/-/commit/c8fca6b4a02d695b1ceea39b330d4406001c03ed](url). When I'm free I'll try to get 1.15 sorted out to see the full extent of the performance uplift. Another thing is that I think this should be able to be applied to 1.14 as well.

Could you clarify which source file you're modifying here? I'm having a rather difficult time following this thread...

**Comment by Pentarctagon** [comment] 2021-05-30 04:31
That would be https://github.com/hrubymar10/MacCompileStuff/blob/7b13f99f35f99089b874d3b2bdb4731dde2d379c/SourcesAndScripts/Scripts/env#L30-L33

**Comment by Wedge009** [comment] 2022-04-26 23:57
Is this still an issue for macOS? I just note that the current (1.16.2) Linux release on Steam is compiled with SDL 2.0.16 and runs with 2.0.20. Windows release on Steam is compiled and run with 2.0.12.

**Comment by Pentarctagon** [comment] 2022-05-14 01:38
Closing, since as of cdfadff142b706a8bb177ec1ca8ea088bcec9dc8 accelerated rendering has been explicitly enabled.

**Closed by Pentarctagon** 2022-05-14 01:38 UTC
Labels: Enhancement, macOS, Engine
