### ISSUE TITLE
Preferences window has scrollbars in some translations (independent from resolution) (GNA #25665)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1665] opened 2017-05-08 13:45 UTC
**[Original submission](https://gna.org/bugs/index.php?25665)** by shiki on 2017-04-17

(Reproduced on All)
Release: 1.13.7+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 13:45
**Modified on 2017-04-17**

**shiki added attachment:** [high_res.jpg](http://gna.org/bugs/download.php?file_id=29937)

**Comment by wesnoth-bugs** [comment] 2017-05-08 13:45
**Modified on 2017-04-18**

**wedge009 wrote:**

> I used to see something similar in the version/build information dialogue, when using French. In your case, it looks like German for Advanced is much longer than English, widening the dialogue beyond what it was designed for and thus causing the scroll bars.

**wedge009 changed status:** None -> Confirmed

**Comment by wesnoth-bugs** [comment] 2017-05-08 13:45
**Modified on 2017-04-18**

**wedge009 changed OS:** Archlinux -> All

**Comment by Wedge009** [comment] 2017-06-16 12:01
I think #1167 describes this issue more generally, as it happens for multiple languages in different locations.

**Comment by gfgtdf** [comment] 2017-06-16 12:21
I think #1167 is not about gui2 and probably needs a complteley different fix.

**Comment by gfgtdf** [comment] 2017-06-16 12:23
Also since https://github.com/wesnoth/wesnoth/commit/08a8e7a58523e900d084f51aca53a1db40d74c4d this can be marked as ready for test

**Comment by Wedge009** [comment] 2017-06-16 12:35
I can see scroll bars in German Preferences under Windows but not Linux. Currently at 19170789. OS font scaling doesn't impact Wesnoth, does it?

**Comment by gfgtdf** [comment] 2017-06-16 14:31
> OS font scaling doesn't impact Wesnoth, does it?

Don't know

**Comment by Wedge009** [comment] 2018-01-17 06:21
#2363 notes the same issue as this one, but for Russian.

**Comment by sevu** [comment] 2018-12-26 17:40
Noting that the German translation is no longer affected, as the label was changed from "Erweiterte Einstellungen" to "Erweitert"

**Comment by Wedge009** [comment] 2019-08-24 05:30
Still an issue for French: 'Options avancées' for 'Advanced'.

**Comment by jostephd** [comment] 2019-09-09 09:53
I can reproduce this by doing this:

```
$ mkdir /tmp/foo
$ for i in `seq 1 100`; do cat <<'EOF' >> /tmp/foo/preferences
[hotkey]
        alt=no
        cmd=no
        command="screenshot"
        ctrl=no
        disabled=no
        shift=no
[/hotkey]
EOF
done
$ ./wesnoth --userconfig-dir=/tmp/foo 
```

![2019-09-09-095028_804x605_scrot](https://user-images.githubusercontent.com/24784687/64521332-55c89d80-d2e7-11e9-8a3f-1da74e10452a.png)

And here's the cause:

![2019-09-09-095234_1359x606_scrot](https://user-images.githubusercontent.com/24784687/64521479-96c0b200-d2e7-11e9-92ae-aa818eb7f798.png)

**Comment by Wedge009** [comment] 2021-09-13 13:04
The preferences window in 1.15.17+dev appears to stretch as needed now. I haven't done any extreme testing like jostephd did, but I haven't found any translations that produces scroll bars yet.

**Closed** 2021-09-13 13:08 UTC
Labels: Bug, Confirmed, Translations, UI
