### ISSUE TITLE
":refresh" command no longer does anything

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#6782] opened 2022-06-20 21:04 UTC
### Game and System Information

- **Version:** 1.17.5+dev

- **Downloaded from:**  here

- **Build info:** c3c47f8

- **OS:**  Linux

### Description of the bug

The command ":refresh" used to update the images displayed, if they had been changed since loading, it was very handy for terrain and sprite work.  Currently, it does not seem to do anything.  It did work earlier in 1.17, I'm not sure when it stopped.

### Steps to reproduce the behavior

1. Start Wesnoth, load some save.
2. Edit one of the images being used and overwrite it.
3. Type ":refresh"

### Expected behavior

":refresh" should update the image.

**Comment by Descacharrado** [comment] 2022-06-20 22:29
:refresh works for me building the same commit in W10 with MSYS.

**Comment by doofus-01** [comment] 2022-06-21 02:32
Groovy.  

If it helps, here is the full info

General
==========

The Battle for Wesnoth version 1.17.5+dev (c3c47f828da-Modified) x86_64
Running on openSUSE Leap 15.4 x86_64
Distribution channel: Default

Game paths
==========

Data dir:        /home/USER/git_wesnoth/wesnoth
User config dir: /home/USER/.wesnoth1_17
User data dir:   /home/USER/.wesnoth1_17
Saves dir:       /home/USER/.wesnoth1_17/saves
Add-ons dir:     /home/USER/.wesnoth1_17/data/add-ons
Cache dir:       /home/USER/.wesnoth1_17/cache

Libraries
=========

Boost:             1.66
Lua:               5.4.4
OpenSSL/libcrypto: 1.1.1l (runtime 1.1.1l)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.50.4 (runtime 1.50.4)
SDL:               2.0.22 (runtime 2.0.22)
SDL_image:         2.0.5 (runtime 2.0.5)
SDL_mixer:         2.0.4 (runtime 2.0.4)

Features
========

Lua console completion:       yes
D-Bus notifications back end: yes

Current video settings
======================

SDL video drivers:        [x11] wayland KMSDRM dummy
Window size:              1600x900
Game canvas size:         1600x900
Final render target size: 1600x900
Screen refresh rate:      60

Current audio settings
======================

Audio not initialized.

Installed add-ons
=================

No add-ons installed.

**Comment by mesilliac** [comment] 2022-06-21 07:41
Can you check if https://github.com/wesnoth/wesnoth/pull/6784 fixes it? It looks like texture caches weren't being flushed properly

**Comment by mesilliac** [comment] 2022-06-21 12:33
never mind about the PR i just merged it, but do let me know if this fixes it in master

**Comment by doofus-01** [comment] 2022-06-26 02:46
Thanks, @mesilliac, I'm checking now.  I'll close this issue if it is fixed.

**Comment by doofus-01** [comment] 2022-06-26 04:32
No change, ":refesh" still does nothing.  Using 9301e93c262

**Comment by mesilliac** [comment] 2022-06-26 06:10
Hmm. I'll see if i can reproduce it when i have time. So you have to be in a game? And then change one of the images on disk that's being used somewhere, like a terrain image or unit sprite, and type in ":refresh"?

**Comment by doofus-01** [comment] 2022-06-26 12:07
Right, I started a new local MP game (in case loading an old save somehow was affecting this), modified the sprite of my leader, typed ":refresh", and nothing happens.  Going to main menu and pressing F5 does not seem to work either.  Closing and restarting Wesnoth shows the sprite modification.

Probably unrelated, but Wesnoth has recently started using a lot of CPU, my computer can barely handle it.  It's most noticeable when scrolling around the map.

**Comment by mesilliac** [comment] 2022-06-27 04:13
Well it turns out i fixed it... and then 3 days later i broke it again ><

It should be fixed now in master for me. At least i confirm that with 12c4e5d7d6a37149ea01a4a371c492880e9c4bc9 unit images do update when i do `:refresh`.

On the CPU issue yeah, hardware acceleration support still isn't there yet. It's using some compatibility systems that will be very slow, most noticably with scrolling, animations and halos. It will get better as things get moved over, but might take a few months for everything.

**Comment by mesilliac** [comment] 2022-07-07 07:50
I think this should be working and fixed now. Reopen if it's still having issues, or crops up again.

**Closed by mesilliac** 2022-07-07 07:50 UTC
Labels: Bug, Graphics
