### ISSUE TITLE
Editor graphically a mess at 800x600

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5193] opened 2020-10-06 01:45 UTC
### Game and System Information
Local Linux builds of 1.15.4 and current master

### Describe the bug
The editor does not display correctly at 800x600 (aka the smallest resolution selectable in the preferences). The map overlaps with the editor's sidebar palette, and what is visible changes in response to mouseovers.

The bug isn't present in 1.14 - while that has #2618, it's a lesser bug than the 1.15 situation. The two versions in the screenshots have the same bugs, they look different because I scrolled the map in only one of them.

![wesnoth_editor_800x600](https://user-images.githubusercontent.com/101462/95149461-4d5ec280-0786-11eb-827e-64820cd79f7f.png)

**Comment by Pentarctagon** [comment] 2020-10-06 03:16
Is it just 800x600, or if not, then at which resolution does it start rendering properly?

**Comment by stevecotton** [comment] 2020-10-06 08:12
It works okay at 1024x768.

On my PC the settings dialog also has an option for 832x624, which is broken similarly to 800x600 - I guess the list of resolutions is generated from the screen sizes reported by the OS. I'm going to leave fixing this to someone who already understands the resolution-handling architecture; it's something that I haven't looked at before, and several currently-active developers have already worked on it.

**Comment by Pentarctagon** [comment] 2020-10-10 07:20
It looks like the height is irrelevant, but the issue happens when going to a width of 1023 or below.

**Comment by Pentarctagon** [comment] 2020-10-10 08:41
I also kind of wonder how useful it still is to support resolutions smaller than that.  Changing the resolution only actually resizes the window rather than doing any kind of scaling, and on the Steam Hardware Survey the smallest resolution it even measures (1024 x 768) is at 0.33% of the playerbase.

**Comment by stevecotton** [comment] 2020-10-10 09:01
Closing as "won't fix" sounds reasonable to me.

**Comment by Pentarctagon** [comment] 2020-10-10 20:33
From Discord:
* @Vultraz said he supports dropping those resolutions.
* @shikadiqueen said she strongly opposes it, though not why, which I'd be interested to know.  My assumption was that the number of screens still being used for things like Wesnoth that can't reach 1024x768 would be close non-existent at this point, and my understanding as well is that since there are specific GUI2 WML implementations for smaller resolutions, then increasing the minimum supported resolution would mean we'd no longer need those rarely used special cases.  The MP lobby for example has one [resolution] for widths of 800-999, and then another for 1000+.

**Comment by shikadiqueen** [comment] 2020-10-10 20:39
> My assumption was that the number of screens still being used for things like Wesnoth that can't reach 1024x768 would be close non-existent at this point

You seem to be making the same assumption that @Vultraz himself once made in conversations with me, where people who play (or work on developing) Wesnoth windowed always have large enough a screen to fit a 1024x768 window. I can most definitely tell you this is not the case on my laptop, which has a 1366x768 screen and runs Windows, which limits the real estate available depending on the size of the task bar and window decorations **with a maximized window**, let alone an unmaximized one. Not everyone has a second screen to help with the issue either.

I feel like we're also forgetting that @singalen wanted at some point to have support for smaller screens merged into mainline to make maintenance of the iOS port (and potentially Android as well) easier.

**Comment by Pentarctagon** [comment] 2020-10-10 21:45
Given that the problem in this bug report is solely related to the width (ie: 1024x600 works fine), would it make any sense to have just the minimum width be changed to 1024 and leave the minimum height at 600, or is that entirely absurd?

As far as singalen's case, my impression was that he essentially created an entirely separate implementation of the UI configuration to support iPhone resolutions, in which case the resolutions that mainline currently supports wouldn't be relevant.

**Comment by shikadiqueen** [comment] 2020-10-10 21:53
> Given that the problem in this bug report is solely related to the width (ie: 1024x600 works fine), would it make any sense to have just the minimum width be changed to 1024 and leave the minimum height at 600, or is that entirely absurd?

I'd say only if there's a very good reason to decide "we'll fix this issue we don't want to fix by deciding it doesn't need to be fixed".

**Comment by Pentarctagon** [comment] 2020-10-10 22:09
Alright, at the least then I'll bisect this later today/tonight.

**Comment by Pentarctagon** [comment] 2020-10-11 02:22
It looks like it's originally caused by @gwhitney 's commits 43de778c6aad8710707680a6b59ba0adbabbe565 ~ f3a472ab963a5ff04b738ccb90de1c151039c1b6.

**Comment by gwhitney** [comment] 2020-10-11 02:44
Oh dear. More negative unintended consequences from my effort to make Wesnoth readable on my displays. I am really sorry - I have never used the editor so it wasn't on my radar to check. I will see if I can get the editor running and track down what's going on.

**Comment by Vultraz** [comment] 2020-10-11 02:55
It's ok, these things happen :) The editor doesn't use GUI2, it uses ThemeWML, so problems would probably be in stuff that touches that.

**Closed** 2020-10-11 03:57 UTC
Labels: Bug, Editor, UI

**Comment by gwhitney** [comment] 2020-10-11 04:02
Whew, turned out not to be so bad (fortunate, since I can barely remember things I did 6 months ago ;-). Just an issue of the scaling changes now trying to cram an 843-pixel-wide window into an 800-pixel-wide screen, once the editor got below the "standard" 1024-pixel width. So just specified a reasonable width for the main map in an 800-pixel-wide layout, and voila. Hope this seems to do the trick for others as well. Again, my apologies for the oversight -- maybe there should be a UI pre-PR checklist? (Very sorry I can't volunteer to create one, I am now working as a finance director for a museum and sadly can't spare the time; in fact I haven't played Wesnoth in several months.)
