### ISSUE TITLE
Legend of Wesmere multiplayer "The selected game has no sides"

### ISSUE THREAD

**Issue by ArcDeSeel** [wesnoth/wesnoth#2246] opened 2017-11-26 22:10 UTC
This is in Wesnoth 1.13.10b. I've produced the same problem in compiled-from-source on Ubuntu 14 and in the Windows binary.

In the multiplayer game creation lobby, selecting the campaign "Legend of Wesmere", after clicking "Create Game" a dialog will say "The selected game has no sides!". Click closes the dialog, and game continues running as usual.

**Comment by GregoryLundberg** [comment] 2017-11-26 22:20
Cannot reproduce against current master (at ba6b6a1f53a897cf64115b82cc60261cc9228236)

**Comment by Vultraz** [comment] 2017-11-26 22:20
Already fixed in master (3b9e73f7d2f47a2d3a1599f147b7f098b3bd85a7). Will be in 1.13.11.

**Closed** 2017-11-26 22:20 UTC
Labels: bug, Campaign

**Comment by ArcDeSeel** [comment] 2017-11-26 22:22
Cool. Nice work.
