### ISSUE TITLE
Unreadable menu on MacOS Catalina

### ISSUE THREAD

**Issue by 10vorne** [wesnoth/wesnoth#5809] opened 2021-05-26 08:42 UTC
Menu unreadable on MacOS Catalina (10.15.7)

<img width="222" alt="Bildschirmfoto 2021-05-21 um 09 38 20" src="https://user-images.githubusercontent.com/84840244/119629840-b165f200-be0e-11eb-968d-81c4b75983d8.png">

The Battle for Wesnoth version 1.14.16
Running on Apple macOS 10.15.7 (19H1030)
Distribution channel: Steam

Game paths
==========

Data dir:        /Users/USER/Library/Application Support/Steam/steamapps/common/wesnoth/The Battle for Wesnoth.app/Contents/Resources
User config dir: /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14
User data dir:   /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14
Saves dir:       /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14/saves
Add-ons dir:     /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14/data/add-ons
Cache dir:       /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14/cache

Libraries
=========

Boost:     1.74
Cairo:     1.16.0 (runtime 1.16.0)
Pango:     1.46.1 (runtime 1.46.1)
SDL:       2.0.12 (runtime 2.0.12)
SDL_image: 2.0.5  (runtime 2.0.5)
SDL_mixer: 2.0.4  (runtime 2.0.4)
SDL_ttf:   2.0.15 (runtime 2.0.15)

Features
========

JPEG screenshots:               yes
Lua console completion:         yes
Legacy bidirectional rendering: no
Cocoa notifications back end:   yes

Current video settings
======================

Current pixel resolution: 2560x1329
Refresh rate: 60
SDL reports: 186x186 dots per inch.

Installed add-ons
=================

No add-ons installed.

**Comment by Pentarctagon** [comment] 2021-05-27 04:36
@hrubymar10 was #5099 ever backported to 1.14?

**Comment by Wedge009** [comment] 2021-06-02 06:57
Could ask @10vorne if those 'hairline' fonts are present in the distribution?

**Comment by 10vorne** [comment] 2021-06-02 12:35
I now installed the client-version 1.14.16 from the website and it's the same problem, fullscreen and window-mode.

**Comment by mattsc** [comment] 2021-06-02 20:40
I just installed the full DMG downloaded from the Wesnoth website and it does not include the hairline fonts, so I don't know where this comes from.

@10vorne: Could you open the "data dir" shown when you start Wesnoth.  In the information you gave above that would be
`/Users/USER/Library/Application Support/Steam/steamapps/common/wesnoth/The Battle for Wesnoth.app/Contents/Resources`
but it might be different now that you have downloaded other versions.  Easiest way to do this is by clicking the 'i' button in the bottom left of the main screen and open "game data".

Inside that should be a `fonts/` directory.  If you look into that, are there two files for the hairline fonts in there, `Lato-Hairline.ttf` and `Lato-HairlineItalic.ttf`?  If so, you can delete those (or move them to some other folder) and that should (hopefully) be a temporary fix for the problem.

But the underlying question is why you are still seeing those fonts when they are not shipped with 1.14.16 any more.  I'm not using Wesnoth through Steam, does it not update the resources when updating to the latest version, or at least not delete removed resources?

**Comment by 10vorne** [comment] 2021-06-07 09:32
Only thin fonts in sight, nor hairline...that makes it even weird?

![Bildschirmfoto 2021-06-07 um 11 31 18](https://user-images.githubusercontent.com/84840244/120993565-efa2d000-c783-11eb-9124-67dfdef61ced.png)

**Comment by mattsc** [comment] 2021-06-07 16:24
Hmm, yes, very strange.  I don't know then, and the problem doesn't happen for me,using Big Sur, so I can't troubleshoot it.

What would be helpful is if you could figure out which of those fonts creates the problem.  I'd start by removing the entire fonts directory, just to make sure that that is indeed where the fonts are taken from (well, don't actually remove it; drag it to the desktop, or rename it, or something).  It probably is, but I think at this point we have to check all the basics.  After you do that, Wesnoth should not find any fonts, which will results in either an error message, or all characters being displayed as rectangles, or something like that.  If that's the case, put the fonts directory back in place.

Then I'd remove all Lato fonts and see what changes.  If something changes, add them back in one at a time, or in groups, until the problem reappears.  Or you can start with the fonts called "light" or "thin", as it is unlikely that the heavy fonts are creating the problem.

Sorry that I can't be more specific.  This will require some experimenting to figure out what's going on, and since I can't reproduce the problem, unfortunately you'll have to do it.

**Comment by 10vorne** [comment] 2021-06-08 06:52
I removed all the fonts, nothing changes, no error messages, no rectangles. So it seems Wesnoth does not take the fonts it should take from the given folder?

**Comment by soliton-** [comment] 2021-06-08 13:51
What output do you get if you start wesnoth with the `--log-debug=font` option?

**Comment by 10vorne** [comment] 2021-06-08 14:02
`Data directory:               /Applications/The Battle for Wesnoth.app/Contents/Resources
User configuration directory: /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14
User data directory:          /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14
Cache directory:              /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14/cache

20210608 16:00:56 info font: Font map size before compression: 4537 ranges
20210608 16:00:56 info font: Font map size after compression: 140 ranges
20210608 16:00:56 debug font: Set the font list. The styled font families are:
20210608 16:00:56 debug font: [0]:		base:	'Lato-Regular.ttf'	bold:	'Lato-Bold.ttf'	italic:	'Lato-Italic.ttf'
20210608 16:00:56 debug font: [1]:		base:	'DejaVuSans.ttf'	bold:	'DejaVuSans-Bold.ttf'	italic:	'DejaVuSans-Oblique.ttf'
20210608 16:00:56 debug font: [2]:		base:	'Andagii.ttf'	bold:	''	italic:	''
20210608 16:00:56 debug font: [3]:		base:	'DroidSansJapanese.ttf'bold:	''	italic:	''
20210608 16:00:56 debug font: [4]:		base:	'DroidSansFallbackFull.ttf'	bold:	''	italic:	''
Setting mode to 1554x600
20210608 16:00:57 info font: Font map size before compression: 4537 ranges
20210608 16:00:57 info font: Font map size after compression: 140 ranges
20210608 16:00:57 debug font: Set the font list. The styled font families are:
20210608 16:00:57 debug font: [0]:		base:	'Lato-Regular.ttf'	bold:	'Lato-Bold.ttf'	italic:	'Lato-Italic.ttf'
20210608 16:00:57 debug font: [1]:		base:	'DejaVuSans.ttf'	bold:	'DejaVuSans-Bold.ttf'	italic:	'DejaVuSans-Oblique.ttf'
20210608 16:00:57 debug font: [2]:		base:	'Andagii.ttf'	bold:	''	italic:	''
20210608 16:00:57 debug font: [3]:		base:	'DroidSansJapanese.ttf'bold:	''	italic:	''
20210608 16:00:57 debug font: [4]:		base:	'DroidSansFallbackFull.ttf'	bold:	''	italic:	''
Checking lua scripts... ok`

**Comment by mattsc** [comment] 2021-06-09 22:17
I ran Wesnoth with the `--log-debug=font` option also and my output looks identical to yours.  However, it turns out that those are not actually the fonts used by Wesnoth.  [If I understand correctly, they are some sort of fall-back fonts left over from previous versions and, in fact, just got removed in the development version (but not in 1.14).]

I've been experimenting with this a bit and it turns out that Wesnoth does not just use the fonts available in its fonts/ folder, but apparently also those provided by the system.  I've been able to use all kinds of fonts that definitely are not part of the Wesnoth distribution:

<img width="728" alt="fonts" src="https://user-images.githubusercontent.com/2106424/121435168-4c90b880-c933-11eb-8837-afa584b4609f.png">

I think what is happening for you is that you have the Lato fonts (incl. Hairline) available elsewhere on your system.  To check that, open the "Font Book" app and see if it lists Lato (it does not for me, which is apparently why I don't have the problem).

Either way, a workaround for you should be to change the default font to another one that is available on your system, such as Arial.  To do so, open the "game data" folder again and find file `data/hardwired/fonts.cfg`.  Open it in a text editor and change `family_order` in l.28 to a font that is available on your system.  For example:
`    family_order= _ "Arial"`
You don't need to change the other lines, this one should be good enough (it's how I got all the different fonts in the image above).  It's a temporary hack, but hopefully it will make Wesnoth usable again for you until we find a better general solution.

[ Of course, you could also delete the Lato font, or at least its Hairline version, from your system, but I assume that it is there for a reason, so that might not be a good idea. ]

I should also note that this problem only occurs with Pango 1.46.1 (as noted in #5099), which is what Wesnoth 1.14.16 ships with.  So the simplest fix for Wesnoth may be to use a different Pango version.  I do not know what other implications that has though.

**Comment by Wedge009** [comment] 2021-06-09 23:28
For whatever it's worth, the current Steam release for 1.14.16 reports using pango 1.44.7 (although compiles under 1.30.0... but after checking 1.44.7 may be more to do with my own distribution set-up vs whatever Wesnoth distributes) while Windows build is still using pango 1.30.1.

There are some subtle changes with new pango releases, such as a change in the definition of 'green' (#4348) and strange tinting on Windows (#1921).

**Comment by mattsc** [comment] 2021-06-10 00:09
Yeah, I should have specified that this is for the Mac build.  If you check the very first post in this issue, you can see that the Pango version is 1.46.1.  The same is true for my own download of 1.14.16 as well.

**Comment by Wedge009** [comment] 2021-06-10 00:21
I'm aware it's for Mac (I added the tag (: ), I was just pointing out what was being used in other OSs, since I recall some subtle differences with pango versions, a couple of examples of which I referred to. In response to your 'I do not know what other implications [of using different pango versions] has though'.

**Comment by mattsc** [comment] 2021-06-10 00:27
Good.  :)  And thanks.

My comment was motivated by what @hrubymar10 said in #5099: "... because it is now impossible to build new libraries with old version of Pango and because of new Apple Silicon support ..."  Now, that comment is specifically about going back to older version, but some restrictions may also apply when upgrading to newer versions.  Or maybe not.  I just don't know.

**Comment by 10vorne** [comment] 2021-06-10 09:18
For me I found a solution / workaround in deactivating the hairline Lato font in the Font book. Now there is another font used in the menu, I'll see if there are other font-problems while e.g. starting a game, etc. Thanks so far, I'll follow this Pango-discussion to see when there is a final fix for the problem. If I can help with e.g. logs from my system, drop me a line. Thank you so far!

**Comment by mattsc** [comment] 2021-07-09 13:55
10vorne: Would it be possible for you to install the [latest development version (1.15.14)](https://forums.wesnoth.org/viewtopic.php?p=665872#p665872) and see if the bug still exists?  If you don't want to change your Steam version, you can download the Mac package directly from the link in the first post.  That uses a newer version of Pango which might have the bug fixed.

**Comment by mattsc** [comment] 2021-07-09 14:12
@10vorne I didn't ping you correctly in my previous comment.

**Comment by 10vorne** [comment] 2021-07-12 08:12
Just to be sure, before I test this with the Dev-Version, I have to reactivate the Lato-Hairline-Font, right?

**Comment by mattsc** [comment] 2021-07-12 13:14
Yes.  The font is not part of the release, so it would only present/used is it is activated in the system.

**Comment by 10vorne** [comment] 2021-07-12 13:32
I reactivated the lato hairline font to see if the problem reappeared with "the old" version. That was the case. Then I started the dev version and <drum roll> unfortunately the problem still exists here too...

**Comment by mattsc** [comment] 2021-07-12 13:37
Hmm, that's too bad.  So it does not appear to be the Pango version after all.  Could you confirm quickly that it does say 1.48.0 for Pango when you click on the "i" symbol in the bottom left of the title screen and then 'Libraries'?

Thank you for testing this!

**Comment by 10vorne** [comment] 2021-07-12 13:46
<img width="642" alt="Bildschirmfoto 2021-07-12 um 15 44 51" src="https://user-images.githubusercontent.com/84840244/125298078-22faf080-e328-11eb-8ee6-9ab6ecc7f304.png">

I deactivated the hairline font and the menu also worked flawless in the dev-version.

**Comment by mattsc** [comment] 2021-07-12 13:51
Looks like it's not just a bug in a specific Pango version and we need to find a different solution ...  Thanks again.

**Comment by 10vorne** [comment] 2021-07-12 13:52
Ping me if I can assist...

**Comment by 10vorne** [comment] 2021-07-16 07:01
I noticed another bug concerning fonts. I've played the tutorial and various keywords are illegible here, probably due to the combination of color and font. The Lato Hairline font is still deactivated.

<img width="1125" alt="Bildschirmfoto 2021-07-16 um 08 58 07" src="https://user-images.githubusercontent.com/84840244/125905942-60a88987-4e87-4230-8813-c25169583ccd.png">

**Comment by mattsc** [comment] 2021-07-18 00:18
Thanks for reporting this also.  Unfortunately, I/we do not know what to do about this at this time.  I've talked about it with @hrubymar10, but neither of us can reproduce the problem, so it's really hard to investigate.  That doesn't mean that we'll give up, just that I have no idea when (or even if) we'll figure out how to fix this.

**Comment by soliton-** [comment] 2022-04-22 14:37
@10vorne What translation are you using? I noticed that a couple of translations have translated
https://github.com/wesnoth/wesnoth/blob/034453d6977962b58c9e8d9d6c3a204679f0f48c/data/hardwired/fonts.cfg#L30
(not to a different font name but literally translated the font name)

I'm guessing the light variant is used in your screenshot which might be broken because of the translation.

**Comment by soliton-** [comment] 2022-04-22 15:06
Well, silly me. Obviously you're using german there... Looks like german left the font names as is so I guess that shouldn't be it. Might still be worth checking what happens if you use different font names there. (remove the translation mark `_` if you try.)

**Comment by Pentarctagon** [comment] 2022-04-23 15:37
Either way having that be translatable is incorrect though, right?

**Comment by 10vorne** [comment] 2022-04-25 10:19
So, I started Wesnoth again today to check the problem. As you can see from the screenshots, the problem with the fonts in the menu no longer exists in the current version. However, the problem with the keywords in the tutorial still seems to be there. If I can be of any help, let me know.

<img width="2554" alt="Bildschirmfoto 2022-04-25 um 12 14 00" src="https://user-images.githubusercontent.com/84840244/165070328-87b70173-a37e-4c7c-95f5-b0fcaa0e4274.png">
<img width="1281" alt="Bildschirmfoto 2022-04-25 um 12 15 35" src="https://user-images.githubusercontent.com/84840244/165070337-62d54f40-9c1c-44f1-8621-a5025aafb2c8.png">

**Comment by soliton-** [comment] 2022-04-26 08:26
> Either way having that be translatable is incorrect though, right?

It's so translations can choose a more appropriate (list of) font for their language. Several languages do that correctly but there are several fishy translations as well. Russian for example uses a font name that does not come with wesnoth so may or may not be on the system. That's for family_order_script though which seems to be only used in the credits. And then the mentioned literal translations of the font name in several languages. Not sure what happens there. Perhaps fallback to a default font.

**Comment by Wedge009** [comment] 2024-05-01 04:26
Are the links still faint for 1.18?

#7939 may not be related but that one was just marked as resolved.

**Comment by Wedge009** [comment] 2024-11-22 21:42
Closing due to lack of activity. Re-open if still an issue.

**Closed by Wedge009** 2024-11-22 21:42 UTC
Labels: Bug, macOS, UI
