### ISSUE TITLE
Find a way to prevent Lua animator objects from leaking unit references

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3534] opened 2018-09-08 22:49 UTC
I've spotted several commits recently that fix bugs by just adding an `anim:clear()` call, and it's made me think, couldn't there be a way to negate the need for this? The `anim:clear()` call is intended to allow reusing the animator for another animation, it's not meant to be something you need to call to clean up.

**Comment by gfgtdf** [comment] 2018-09-08 23:32
iirc lua used garbage collection, which means unlike in c++, objects (here: the animator) will not be destroyed immidiately when they go out of scope. in particular these unit referrerences are not really leaked but destroyed later at some later unknown time, but at last when the lua kernel is destroyed.

**Comment by CelticMinstrel** [comment] 2018-09-09 01:29
I understand what you mean, but it doesn't change the basic problem here.

Maybe the animator could store the unit as a `weak_ptr` instead of a `shared_ptr`? I think that would solve the problem, wouldn't it?

**Comment by jyrkive** [comment] 2018-09-09 07:27
The problem is that weak pointers to units aren't possible. Under the hood, `unit_ptr` is an intrusive pointer: the reference count is stored in the unit itself. Thus, when the last reference to the unit is destroyed, the reference count goes with it, and if a weak pointer attempts to read the reference count later, it gets undefined behavior.

**Comment by newfrenchy83** [comment] 2018-09-09 11:40
and put anim_comp.clear_haloes in run() function in game_lua_kernel is mor possible for don't use clear() in lua? i will tested this idea.

**Comment by newfrenchy83** [comment] 2018-09-09 13:47
i find a way to negate the need of clear() to put directly in run().

**Comment by CelticMinstrel** [comment] 2018-09-09 14:54
Oh, we didn't switch units to shared pointers? I do understand that weak pointers aren't possible in the intrusive model, but I thought I remembered unit pointers being changed to shared. Maybe I misremembered.

**Comment by jyrkive** [comment] 2018-09-09 15:03
IIRC, Vultraz attempted the switch but gave up.

**Closed** 2018-09-09 15:47 UTC
Labels: Bug, Low-priority, Lua API
