### ISSUE TITLE
TBfW 1.14 stable can crash when launched using KDE on Debian 9 _Stretch_.

### ISSUE THREAD

**Issue by ghost** [wesnoth/wesnoth#2690] opened 2018-03-18 21:02 UTC
This is TBfW at rev https://github.com/wesnoth/wesnoth/commit/0ab238ab76b84712566e415551c2999acf2a4c1e (branch `1.14`) built from sources on GNU/Linux.

The used Boost is not [the distro default](https://packages.debian.org/stretch/libboost-all-dev). I can try to repeat using distro default Boost but I haven't tried yet because I don't expect any change from that.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch
$ uname -a
Linux udvd9 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
$ ls /usr/local/lib/
libboost_chrono.a                    libboost_random.a
libboost_chrono.so                   libboost_random.so
libboost_chrono.so.1.56.0            libboost_random.so.1.56.0
libboost_filesystem.a                libboost_regex.a
libboost_filesystem.so               libboost_regex.so
libboost_filesystem.so.1.56.0        libboost_regex.so.1.56.0
libboost_iostreams.a                 libboost_system.a
libboost_iostreams.so                libboost_system.so
libboost_iostreams.so.1.56.0         libboost_system.so.1.56.0
libboost_locale.a                    libboost_test_exec_monitor.a
libboost_locale.so                   libboost_thread.a
libboost_locale.so.1.56.0            libboost_thread.so
libboost_prg_exec_monitor.a          libboost_thread.so.1.56.0
libboost_prg_exec_monitor.so         libboost_unit_test_framework.a
libboost_prg_exec_monitor.so.1.56.0  libboost_unit_test_framework.so
libboost_program_options.a           libboost_unit_test_framework.so.1.56.0
libboost_program_options.so          python2.7
libboost_program_options.so.1.56.0   python3.5
$ ldd wesnoth | sed s/0x.*//
        linux-vdso.so.1 (
        libSDL2-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (
        libboost_iostreams.so.1.56.0 => /usr/local/lib/libboost_iostreams.so.1.56.0 (
        libboost_regex.so.1.56.0 => /usr/local/lib/libboost_regex.so.1.56.0 (
        libboost_program_options.so.1.56.0 => /usr/local/lib/libboost_program_op
tions.so.1.56.0 (
        libboost_filesystem.so.1.56.0 => /usr/local/lib/libboost_filesystem.so.1.56.0 (
        libboost_locale.so.1.56.0 => /usr/local/lib/libboost_locale.so.1.56.0 (
        libicudata.so.57 => /usr/lib/x86_64-linux-gnu/libicudata.so.57 (
        libicui18n.so.57 => /usr/lib/x86_64-linux-gnu/libicui18n.so.57 (
        libicuuc.so.57 => /usr/lib/x86_64-linux-gnu/libicuuc.so.57 (
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (
        libboost_system.so.1.56.0 => /usr/local/lib/libboost_system.so.1.56.0 (
        libboost_random.so.1.56.0 => /usr/local/lib/libboost_random.so.1.56.0 (
        libboost_thread.so.1.56.0 => /usr/local/lib/libboost_thread.so.1.56.0 (
        libSDL2_image-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0 (
        libSDL2_mixer-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2_mixer-2.0.so.0 (
        libSDL2_ttf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0 (
        libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (
        libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (
        libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (
        libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (
        libvorbisfile.so.3 => /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 (
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (
        libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (
        libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (
        libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (
        libpulse-simple.so.0 => /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0 (
        libpulse.so.0 => /usr/lib/x86_64-linux-gnu/libpulse.so.0 (
        libsndio.so.6.1 => /usr/lib/x86_64-linux-gnu/libsndio.so.6.1 (
        libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (
        libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (
        libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (
        libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (
        libXss.so.1 => /usr/lib/x86_64-linux-gnu/libXss.so.1 (
        libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (
        libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (
        libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (
        libwayland-cursor.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (
        libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (
        /lib64/ld-linux-x86-64.so.2 (
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (
        libboost_chrono.so.1.56.0 => /usr/local/lib/libboost_chrono.so.1.56.0 (
        libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (
        libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (
        libwebp.so.6 => /usr/lib/x86_64-linux-gnu/libwebp.so.6 (
        libmodplug.so.1 => /usr/lib/x86_64-linux-gnu/libmodplug.so.1 (
        libfluidsynth.so.1 => /usr/lib/x86_64-linux-gnu/libfluidsynth.so.1 (
        libFLAC.so.8 => /usr/lib/x86_64-linux-gnu/libFLAC.so.8 (
        libmad.so.0 => /usr/lib/x86_64-linux-gnu/libmad.so.0 (
        libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (
        libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (
        libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (
        libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (
        libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (
        libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (
        libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (
        libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (
        libpulsecommon-10.0.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsec
ommon-10.0.so (
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (
        libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (
        libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (
        libjack.so.0 => /usr/lib/x86_64-linux-gnu/libjack.so.0 (
        libsndfile.so.1 => /usr/lib/x86_64-linux-gnu/libsndfile.so.1 (
        libreadline.so.7 => /lib/x86_64-linux-gnu/libreadline.so.7 (
        libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (
        libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (
        liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (
        libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (
        libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (
        libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (
        libasyncns.so.0 => /usr/lib/x86_64-linux-gnu/libasyncns.so.0 (
        libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (
        libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (
        libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (
        libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (
$ _
```

Using [KDE Plasma selected from the official packaging](https://packages.debian.org/stretch/kde-plasma-desktop) because using [dwm](http://dwm.suckless.org/) (from the official Debian Stretch packaging too) `wesnoth` was not working OK.

Step 0: Make sure `wesnoth` will start full screen. Right after building from sources on a clean host it would first boot full screen. If started windowed, click `Preferences`, click `Display`, click `Full screen` and close the game by clicking `Close` then `Quit`.

Step 1: Start `wesnoth` using the full screen mode, this weird something ~~happens~~ can happen:

![screenshot_20180318_200250](https://user-images.githubusercontent.com/3533348/37570663-69974a88-2aea-11e8-8c99-b0436e16327c.png)
_See how it is supposed to be full screen, but somehow it is not really full screen._ **This step randomly won't happen.**

Step 2: Activate the windowed mode: click `Preferences`, click `Display`, click `Full screen`.

The program is windowed now. No matter if you close the `Preferences` panel or not, if the program entered the state were you could see something like the picture in step 2, then if you click the _unmaximize_ KDE control, at my host it is crashing with this message:

```
[...]
WML exception:
User message: Failed to show a dialog, which doesn't fit on the screen.
Dev message: /PATH/TO/WESNOTH/src/gui/widgets/window.cpp:958 in function 'layout
' found the following problem: Failed to size window; wanted size 841,495 availa
ble size 845,476 screen size 845,476.
$ _
```

Step 3: Boot `wesnoth` again. The program is very stable, allowing to go full screen and windowed back and forth, and when windowed it is allowing to go maximized and unmaximized back and forth.

If windowed, closes and boots without issues as long as it doesn't get booted using the full screen mode. If booting using the full screen mode, it is getting back to step 2.

<hr />

I've experienced other weird issues on KDE Plasma for Debian Stretch using other hosts before. There are random weird issues with Chromium and also with Anura games, but in none of those similar cases have I ever seen any crash behavior like this.

I think something is very wrong with KDE for Debian Stretch. The issue reminds me of the classic [SimCity on Microsoft 4](https://news.ycombinator.com/item?id=2281932) story, just the other way around.

**Comment by galegosimpatico** [comment] 2018-03-19 18:11
I have two hosts with KDE for Debian Stretch, but this one seems to be free from the issue:

```
$ xrandr 
Screen 0: minimum 8 x 8, current 4320 x 1920, maximum 16384 x 16384
VGA-0 connected 1920x1080+0+420 (normal left inverted right x axis y axis) 531mm
 x 299mm
   1920x1080     60.00*+
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00                                                 
   800x600       75.00    60.32                                                 
   640x480       75.00    59.94                                                 
DVI-D-0 connected primary 1200x1920+1920+0 left (normal left inverted right x ax
is y axis) 518mm x 324mm                                                        
   1920x1200     59.95*+  59.88                                                 
   1920x1080     60.00    59.94    50.00    29.97    25.00    23.97    60.05
60.00    50.04                                                                  
   1600x1200     60.00                                                          
   1280x1024     75.02    60.02                                                 
   1280x720      60.00    59.94    50.00                                        
   1152x864      75.00                                                          
   1024x768      75.03    60.00                                                 
   800x600       75.00    60.32                                                 
   720x576       50.00                                                          
   720x480       59.94                                                          
   640x480       75.00    59.94    59.93  
HDMI-0 connected 1200x1920+3120+0 right (normal left inverted right x axis y axi
s) 518mm x 324mm
   1920x1200     59.95*+  59.88  
   1920x1080     60.00    59.94    50.00    29.97    25.00    23.97    60.05
60.00    50.04  
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
$ _
```

**Comment by Wedge009** [comment] 2018-03-20 04:31
Perhaps the older Plasma Debian (5.8?) is using is a factor - the full screen issue looks very much like something I _used_ to get as mentioned in #1569, but seemed to go away with Plasma 5.10.

It's also not clear what SDL version is available. In that report, there seems to be some combination of Plasma and/or SDL that produced this problem.

**Comment by galegosimpatico** [comment] 2018-03-20 07:53
Both hosts are using official packaging SDL.

In the case of the crashing host, these are the used SDL versions:

```
$ ldd wesnoth | grep -i sdl
        libSDL2-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007f
eed42fa000)
        libSDL2_image-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so
.0 (0x00007feed04c2000)
        libSDL2_mixer-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2_mixer-2.0.so
.0 (0x00007feed026e000)
        libSDL2_ttf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0 (
0x00007feed0066000)
$ find /usr/lib/x86_64-linux-gnu/ -name '*libSDL*'
/usr/lib/x86_64-linux-gnu/libSDL2_ttf.a                                         
/usr/lib/x86_64-linux-gnu/libSDL2.a                                             
/usr/lib/x86_64-linux-gnu/libSDL_image-1.2.so.0                                 
/usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0.11.4                                  
/usr/lib/x86_64-linux-gnu/libSDL2_mixer-2.0.so.0.0.1                            
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so                                        
/usr/lib/x86_64-linux-gnu/libSDL2_mixer.so                                      
/usr/lib/x86_64-linux-gnu/libSDL2_ttf.so                                        
/usr/lib/x86_64-linux-gnu/libSDL2_mixer-2.0.so.0
/usr/lib/x86_64-linux-gnu/libSDL2.so
/usr/lib/x86_64-linux-gnu/libSDL2_image.so
/usr/lib/x86_64-linux-gnu/libSDL_image-1.2.so.0.8.4
/usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0
/usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0.0.1
/usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0.14.0
/usr/lib/x86_64-linux-gnu/libSDL2main.a
/usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.4.1
/usr/lib/x86_64-linux-gnu/libSDL2_image.a
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
/usr/lib/x86_64-linux-gnu/libSDL2_mixer.a
/usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so
/usr/lib/x86_64-linux-gnu/libSDL2_mixer-2.0.so
/usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so
/usr/lib/x86_64-linux-gnu/libSDL2_test.a
/usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0
$ _
```

In the unlikely case the image went away before ceasing usefulness, also the `xrandr` output for the crashing host:

```
$ xrandr
Screen 0: minimum 320 x 200, current 1280 x 800, maximum 8192 x 8192
LVDS-1 connected primary 1280x800+0+0 (normal left inverted right x axis y axis)
 290mm x 180mm
   1280x800      60.00*+
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   960x600       60.00  
   960x540       59.99  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   800x512       60.17  
   700x525       59.98  
   640x512       60.02  
   720x450       59.89  
   640x480       60.00    59.94  
   680x384       59.80    59.96  
   576x432       60.06  
   512x384       60.00  
   400x300       60.32    56.34  
   320x240       60.05  
VGA-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
$ _
```

There is an _About System_ utility, it is telling _KDE Plasma Version: 5.8.6_ among other lines.

**Comment by Wedge009** [comment] 2018-03-20 09:04
> I've experienced other weird issues on KDE Plasma for Debian Stretch using other hosts before. There are random weird issues with Chromium and also with Anura games, but in none of those similar cases have I ever seen any crash behavior like this.

Debian Stretch seems to be using Plasma 5.8 and SDL 2.0.5. I remember a time not so long ago when my own KDE set-up seemed quite unstable in terms of graphical artefacts and Wesnoth also had troubles like this. As mentioned in the previous bug report, things seemed to be much more stable from Plasma 5.11 and SDL 2.0.6 onwards. I realise it isn't ideal to wait for a more recent Plasma release but unless someone else here can replicate your situation exactly I'm not sure what we can do to help.

**Comment by galegosimpatico** [comment] 2018-03-20 12:40
At the host where it isn't crashing (so far) I suppose SDL is exactly the same so far.

> [...] unless someone else here can replicate your situation exactly I'm not sure what we can do to help.

I can try to help that...

* I don't know Debian distro management. If Debian Stretch upgrades to KDE 5.10 at some point, then it would seem to me a clear [Won't fix](https://github.com/wesnoth/wesnoth/labels/Won%27t%20fix), because time would fix.

* Actually I don't really think Debian Stretch is going to upgrade to KDE 5.10 or more recent, at any moment.

  * Debian Stretch ships `wesnoth` `1.12`. Will we ever see `1.14` on Stretch? I'm sure I remember at least one old Ubuntu or Debian distro holding two stable `wesnoth` versions at the same time in their official packaging. However, I'm aware there have been notable environmental changes ever since, that make past experience not valid for future expectations.

  * If `1.14` is not coming to Debian Stretch, I don't care what you do. To my opinion, labeling [Won't fix](https://github.com/wesnoth/wesnoth/labels/Won%27t%20fix) would be appropriate.

  * If `1.14` is ever coming to Debian Stretch. I can try to debug and propose a solution to the issue, if my affected laptop lives that long.

    * Maybe the issue involves code changeable without affecting the other TBfW deployments. I can try to find a solution and open PR.

    * Maybe there is no reasonable fix at all. I would be upgrading the host to Debian 10 as soon as possible.

    * Maybe there can be a fix making an exceptional flow for this deployment, not really wanted for everyone but reasonably acceptable for this deployment.

       * I can try to debug and propose a solution to the issue, provided that detection of KDE 5.8 by `wesnoth` is feasible, and desirable, and (if it isn't already implemented) I succeed in its implementation.

       * If development lead discourage detection of the desktop environment and version, I can try to check if that same strategy can be safely _upgraded_ to be in effect for every GNU/Linux deployment.

**Comment by galegosimpatico** [comment] 2018-03-20 20:29
If it is of any use I can identify affected and unaffected SDL2 versions [without much effort](https://github.com/galegosimpatico/anura/blob/my-trunk/INSTALL#L99-L123). Fortunately it seems nothing like this happens to [1.12](https://packages.debian.org/stretch/wesnoth-1.12-core)! Well done! I wasn't aware 1.12 is SDL1 :sweat_smile:.

**Comment by shikadiqueen** [comment] 2018-03-23 08:57
There's no such a thing as KDE 5.10, but there is Plasma 5.10.

I don't remember experiencing any issues with Wesnoth on stretch (despite having the worst hardware setup for Plasma, NVIDIA with the proprietary drivers), and haven't seen anything unusual on buster/sid either (Plasma 5.12), so I'm not sure what to recommend in terms of debugging right now.

I have two 1080p screens instead of a laptop panel, though. I also recently started using latte-dock on top of Plasma.

**Comment by shikadiqueen** [comment] 2018-03-26 06:52
Also, to clarify, Debian stable only receives bug fixes. Updating any package to a whole new upstream version has too great a potential for introducing regressions or compatibility-breaking behaviour, so it is usually not done except in **extreme** cases (Chromium is one such by default because of the lack of a long-term support branch upstream), and certainly not for as large and complicated software as KDE Frameworks, Plasma, KDE Applications, or Qt are.

Sometimes said software may be added to backports, and I do think the Qt/KDE maintainers' considered pushing a newer Plasma 5.8 LTS version to backports at some point but I don't know if that will ever come to fruition. It's still a lot of work for them.

If you need a moving target while still running Debian (whilst embracing all the associated risks that come with this), you should be using testing, or (only if you're *very* intimately familiarized with Debian's development process and can fix the occasional breakage that can happen) sid.

**Comment by galegosimpatico** [comment] 2018-03-26 11:31
Clarified! I actually partly knew about the Debian flow... well, only high level. Your response helps me understand a little more the hands on stuff they and packagers do.

So what about me remembering a distro holding two TBfW stable releases? If that couldn't have been Debian, can be something I saw when I was an Ubuntu LTS user? Or is that a made up remembrance?

I'm sure Ubuntu 8 LTS shipped TBfW 1.6, I would also guess that Ubuntu 10 LTS shipped TBfW 1.8 and Ubuntu 12 LTS shipped 1.10, I just can't remember those so clearly... was any of Ubuntu 10 or Ubuntu 12 shipping two TBfW stable releases at the same time?

I tried to check my memories against old package lists, but I can't find them. Isn't there any record trail of that?

**Comment by galegosimpatico** [comment] 2018-03-26 13:31
Found at last, blessed be archive.org WBM...

Here is Ubuntu 10 LTS _Lucid Lynx_ providing both TBfW 1.6 and 1.8: https://web.archive.org/web/20120201223757/http://packages.ubuntu.com/search?suite=lucid&searchon=names&keywords=wesnoth

Here is Ubuntu 12 LTS _Precise Pangolin_ providing both TBfW 1.8 and 1.10: https://web.archive.org/web/20120202142318/http://packages.ubuntu.com/search?suite=precise&searchon=names&keywords=wesnoth

I've no idea how or why those Ubuntu versions got to provide two stable `wesnoth` versions.

Regardless whether TBfW `1.14` is ever making it to any Ubuntu distro already providing TBfW `1.12` or not, I find no Ubuntu version currently providing Plasma 5.8 (no point in investigating SDL then?)...

I suppose every Debian stable is safe and every non EOL-ed Ubuntu is safe. I yield the issue from here.

**Comment by stevecotton** [comment] 2018-03-26 20:39
For Debian, the old packages are still tracked, see the 'versions' box, second down on the left.
https://tracker.debian.org/pkg/wesnoth-1.8
https://tracker.debian.org/pkg/wesnoth-1.10
https://tracker.debian.org/pkg/wesnoth-1.12

1.8 was in o-o-stable (old-old-stable, Wheezy)
1.10.3 was also in Wheezy
1.10.7 was in Wheezy-backports and Jessie
1.12.6 is in Wheezy-backports-sloppy, Jessie-backports and Stretch
1.13.8 is in Experimental

**Comment by galegosimpatico** [comment] 2018-03-26 22:25
Thank you, I didn't knew of those pages.

Just a little unimportant comment: I read there TBfW 1.8 was in Squeeze, not Wheezy..?

**Comment by Wedge009** [comment] 2019-10-16 00:07
I notice ghost appears to be a deleted user. Without any further updates I don't think it's worth keeping this given it appears to be user/system-specific - I don't think we were able to replicate this.

Should ghost return and this still be an issue we can re-open it.

**Closed by Wedge009** 2019-10-16 00:07 UTC
Labels: Bug, Engine, Linux
