### ISSUE TITLE
Graphical glitches in message dialog

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#8061] opened 2023-11-22 00:46 UTC
### Game and System Information

The Battle for Wesnoth version 1.17.23+dev (9559b072-Clean) x86_64
Running on Freedesktop.org SDK 22.08 (Flatpak runtime) x86_64

Boost:             1.67
Lua:               5.4.6
OpenSSL/libcrypto: 3.0.0k-dev (runtime 3.0.0k-dev)
libcurl:           7.86.0 (runtime 7.86.0-DEV)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.51.0 (runtime 1.51.0)
SDL:               2.24.0 (runtime 2.24.0)
SDL_image:         2.6.3 (runtime 2.6.3)
SDL_mixer:         2.6.3 (runtime 2.6.3)

SDL video drivers:        [x11] wayland dummy evdev
Window size:              1920x1008
Game canvas size:         1920x1008
Final render target size: 1920x1008
Screen refresh rate:      60
Screen dpi:               101.60x101.60
Renderer:                 opengl (hw)
Maximum texture size:     16384x16384
VSync:                    off

### Description of the bug

![Screenshot_20231121_214443](https://github.com/wesnoth/wesnoth/assets/3605541/ea0559dc-368e-4bbd-9ffd-c09d65279255)

### Steps to reproduce the behavior

1. I noticed this bug after killing Fal Kgag in first scenario of Liberty  campaign.

**Comment by grz0** [comment] 2023-11-22 01:35
I just compiled wesnoth from master and I see the same issues,  also on Wayland. I tested `SDL_RENDER_BATCHING=0 ` and the issue still can be reproduced.
Mesa:
```
OpenGL renderer string: Mesa Intel(R) Xe Graphics (TGL GT2)
OpenGL version string: 4.6 (Core Profile) Mesa 23.2.1
Mesa version: 23.2.1
```

The issue is not limited to dialogs in Liberty, I see it also in other scenarios, for example first scenario in  A tale of Two Brothers:

![image](https://github.com/wesnoth/wesnoth/assets/3605541/78ce2a15-e398-48b9-8686-4c684811dc84)

**Comment by Wedge009** [comment] 2023-11-22 01:36
So this might be specific to Intel GPUs, then? Can anyone else replicate this, regardless of GPU or OS?

**Comment by Pentarctagon** [comment] 2023-11-22 01:51
I also can't reproduce on Linux/X11, AMD.

**Comment by mesilliac** [comment] 2023-11-22 07:30
It's probably related to my recent offscreen rendering changes for windows. It looks like corruption in the background texture of the message window (which technically is a transparent window covering the whole map area).

Possibly `fill(0,0,0,0)` isn't doing what i expected it to...

**Comment by mesilliac** [comment] 2023-11-22 08:39
It definitely wasn't doing what i expected it to.

So this might be fixed by #8062

**Comment by grz0** [comment] 2023-11-22 09:04
First bad commit: 0eada04f55016a1849c3bf2b5fff5365909b96f6

```
git bisect start
# status: waiting for both good and bad commits
# good: [8a4ff229855458ad8b57053acec9950b84690f53] 1.17.7
git bisect good 8a4ff229855458ad8b57053acec9950b84690f53
# status: waiting for bad commit, 1 good commit known
# bad: [c7eac0126be66b1a390f287ab6e758546df5a6a3] Clip rerender requests to the window area.
git bisect bad c7eac0126be66b1a390f287ab6e758546df5a6a3
# good: [8e6df8cd1fc755b45f29cca46fc80a3ddda9835a] Fix incorrect query for selecting new clients by download source.
git bisect good 8e6df8cd1fc755b45f29cca46fc80a3ddda9835a
# good: [1af69b22365db90b40195bc575b114aa20ac6452] fix git checkout failing for vcpkg
git bisect good 1af69b22365db90b40195bc575b114aa20ac6452
# good: [ed3ef8c84441de6222819456b7236b807722ea81] EI: translation hints for Mage
git bisect good ed3ef8c84441de6222819456b7236b807722ea81
# good: [2fd85fc556d0e0022ea31fb9b73288b8e8dc09a1] Fix attribute presence check
git bisect good 2fd85fc556d0e0022ea31fb9b73288b8e8dc09a1
# bad: [a8dc847d35e4ea11eb70bb26660a42e5e19e9311] Warn when forcing a bad zoom level
git bisect bad a8dc847d35e4ea11eb70bb26660a42e5e19e9311
# bad: [ca5edd5336bbe491b34b62c5fb895e13bd96c077] Regenerate story screen message panel blur when background changes.
git bisect bad ca5edd5336bbe491b34b62c5fb895e13bd96c077
# bad: [766cfe82018349221618a2b9596d194304f40cfd] Implement deferred rendering for blurrables.
git bisect bad 766cfe82018349221618a2b9596d194304f40cfd
# good: [eda389b28d6fb00cc0e6f1dfc36fff84275e28da] Fix include_file= not being able to handle cfg files generated by the editor
git bisect good eda389b28d6fb00cc0e6f1dfc36fff84275e28da
# good: [18c2ad3bf8584a0c8ca4d3c80e02904fbac52b1b] Add a negation operator for sdl::point.
git bisect good 18c2ad3bf8584a0c8ca4d3c80e02904fbac52b1b
# bad: [08144affdf685160248c7fb474014c36112d9a22] Allow draw::set_render_target to switch to the main render buffer.
git bisect bad 08144affdf685160248c7fb474014c36112d9a22
# bad: [0eada04f55016a1849c3bf2b5fff5365909b96f6] Offscreen rendering for windows.
git bisect bad 0eada04f55016a1849c3bf2b5fff5365909b96f6
# first bad commit: [0eada04f55016a1849c3bf2b5fff5365909b96f6] Offscreen rendering for windows.
```

**Comment by Wedge009** [comment] 2023-11-22 09:08
Thanks, at least that confirms mesilliac's intuition.

**Comment by grz0** [comment] 2023-11-22 09:17
@mesilliac I just compiled master with https://github.com/wesnoth/wesnoth/pull/8062 and I can't reproduce this problem.

**Closed** 2023-11-22 23:30 UTC
Labels: Bug, Unconfirmed, Graphics

**Comment by mesilliac** [comment] 2023-11-22 23:33
FTR this was the same problem as #6836 - i also changed the code for the minimap to use the new `clear` function. It was setting the blend mode manually before filling.
