### ISSUE TITLE
Scorpion resistance

### ISSUE THREAD

**Issue by rmj555** [wesnoth/wesnoth#5731] opened 2021-04-23 15:52 UTC
I brought this up before and it still persists on version 1.15.12.  Melee weapons are better at killing scorpions than swords.

Windows 10pro from sourceforge.

![TRoWscorpion](https://user-images.githubusercontent.com/76490126/115897242-104fda00-a411-11eb-88cf-1aeb728d572e.png)

[TRoW-The Swamp of Esten Turn 2.gz](https://github.com/wesnoth/wesnoth/files/6366588/TRoW-The.Swamp.of.Esten.Turn.2.gz)
![TRoWscorpion](https://user-images.githubusercontent.com/76490126/115897353-2d84a880-a411-11eb-922f-09859d4dae4d.png)

**Comment by Pentarctagon** [comment] 2021-04-23 15:58
Swords are melee weapons though?

**Comment by rmj555** [comment] 2021-04-23 16:04
Sorry, I meant blunt.

I have no idea why the .gz file I loaded is identical to the png.

**Comment by soliton-** [comment] 2021-04-23 16:04
What exactly is the issue being reported?

**Comment by knyghtmare** [comment] 2021-04-23 16:09
Feb 2020: Giant Scorpion Resistances were altered but no changelog entry given. The missing changelog entry is probably the issue here.

**Comment by Pentarctagon** [comment] 2021-04-23 16:47
Why is it an issue that the resistances were changed?

**Comment by knyghtmare** [comment] 2021-04-23 17:00
> Why is it an issue that the resistances were changed?

b9e67f459840a01a3d453570cd6ceec31ef10ac6

I like the new resistances though. They fit to the unit more, while the previous ones were rather..."extreme".
Also, I don't really thing is a bug. It's just a lack of communication that the resistances were altered to be more approriate.

**Comment by Pentarctagon** [comment] 2021-04-24 16:32
I'll be closing this soon unless an explanation of why this is a bug can be provided.  Just the fact that it wasn't mentioned in the changelog doesn't make the new resistances wrong.

**Comment by rmj555** [comment] 2021-04-25 16:17
The opening dialog of the scenario says that swords and fire are best for killing scorpions.

**Comment by knyghtmare** [comment] 2021-04-25 16:18
> The opening dialog of the scenario says that swords and fire are best for killing scorpions.

Which scenario? Link or quote?

**Comment by Hejnewar** [comment] 2021-04-25 16:54
Purpose of leaving variation of scorpion was to have this scenario be as it previously was, but it seems that its using new scorpion instead. I think it was TRoW - Swamp of Esten. I cant find the dialogue.

**Comment by knyghtmare** [comment] 2021-04-25 16:56
> Purpose of leaving variation of scorpion was to have this scenario be as it previously was, but it seems that its using new scorpion instead. I think it was TRoW - Swamp of Esten. I cant find the dialogue.

Wouldn't the simple fix be to just edit that dialogue to state that Scorpions can be "bludgeoned" instead of swords? That seems to be it.

**Comment by rmj555** [comment] 2021-04-26 14:58
It was SotBE, Desert of Death.

**Comment by knyghtmare** [comment] 2021-04-26 15:13
Oh, I see.
@Pentarctagon 
This is a duplicate of #5419
Same conclusion again.

**Closed** 2021-04-26 16:29 UTC
Labels: Units
