### ISSUE TITLE
Game chatroom names are untranslatable

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2862] opened 2018-04-10 22:29 UTC
![random-map-teams](https://user-images.githubusercontent.com/705211/38586726-3b36ea08-3d1f-11e8-9781-929bd0305e70.png)

**Comment by shikadiqueen** [comment] 2018-04-10 22:32
Duplicate of #2709.

**Closed by shikadiqueen** 2018-04-10 22:32 UTC
Labels: Bug, Duplicate, MP Lobby, Translations, UI
