### ISSUE TITLE
Wrong sprite in sidebar

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3627] opened 2018-10-17 21:30 UTC
In 1.14.5, in the last scenario of AToTB, I moved a unit to attack a Goblin Impaler, and while I was mouseovering the Goblin Impaler the sidebar showed the wrong sprite:

![sidebar-sprite](https://user-images.githubusercontent.com/24784687/47117230-57aeeb80-d253-11e8-8edd-e16e0193f83c.png)

There happened to be another Goblin Impaler next to the first one and it, too, displayed the same wrong sprite.

**Comment by Wedge009** [comment] 2018-10-26 10:09
Have a save file handy? I tried to replicate this in 1.14.5 release but without success. I wonder if it's a one-off timing oddity between having your archer selected and then hovering over the goblin.

**Comment by jostephd** [comment] 2018-10-26 18:32
When this happened, I saved my state and opened that save in a new instance of wesnoth, and the second wesnoth didn't have the bug. I didn't save it, but I still have the replay.

As I mentioned, this is AToTB. The sprite is TC'd green so it's probably Reeve Hoban... but when I mouseover Reeve Hoban, his sprite has the sword point down, along the thigh, not point up as in this sidebar capture. Could this be one of the attack sprites?

I saw this on side 1 turn 6; side 3's Longbowman was killed on side 2 turn 5.

**Comment by GregoryLundberg** [comment] 2018-10-26 19:28
I think I've had something similar happen. I think it was pre-tag for 1.14 but since I could never reproduce it, I decided it would have to wait. Most recently, I've had issues with frozen bits but only when I'm using X server on Windows 10 for Wesnoth running on Linux but that's probably unrelated.

**Comment by jostephd** [comment] 2018-11-11 01:02
I have another instance of this in DiD. Two Swordsmen use the Spearman's static sprite on map and in the sidebar, but a Swordsman sprite in the Attack Enemy dialog. While attacking they use the Swordsman animations. They also use the Swordsman idle animation (face south and twiddle the sword every so often), not the spearman's idle animation (continuously incline the spear to and fro).

That instance of wesnoth is currently open, can I run some lua command or something to debug it? It doesn't reproduce if I save and load.

**Comment by jostephd** [comment] 2018-11-11 01:12
The Swordsmen are on team purple but their Spearman sprites are TC'd green. There were green Spearmen in this scenario but they had been killed.

**Comment by Wedge009** [comment] 2023-03-06 04:06
Given the age and lack of a reliable means to replicate this, I'm closing this.

**Closed by Wedge009** 2023-03-06 04:06 UTC
Labels: Bug, Needs more info, Graphics, UI
