### ISSUE TITLE
Wrong plural forms in src/formula/string_utils.cpp

### ISSUE THREAD

**Issue by gunchleoc** [wesnoth/wesnoth#4702] opened 2020-01-13 11:37 UTC
### Game and System Information
Upcoming 1.14 (I am translating)

### Describe the bug
```
#: src/formula/string_utils.cpp:291
msgid "timespan^$num year"
msgstr ""

#: src/formula/string_utils.cpp:291
msgid "timespan^$num years"
msgstr ""
```

This is wrong and needs to be ngettext format. Same for months etc.

### To Reproduce

Get the string on screen with a locale like `gd` and have it fetch a plural number. I don't know where it is used exactly.

### Expected behavior

#: src/formula/string_utils.cpp:291
```
msgid "timespan^$num year"
msgid_plural "timespan^$num years"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""

```

**Comment by CelticMinstrel** [comment] 2020-01-14 02:04
If I recall correctly, this is used to inform users who were banned from the MP server when their ban expires.

**Comment by shikadiqueen** [comment] 2020-01-25 18:26
Oh yeah, I remember now. I added that code.

I couldn't figure out a way to use proper plural forms without writing the code as a massive `if` chain. `dsngettext()` is a runtime function and the strings in question are part of a table. It's impossible to use it without evaluating the numeric value on the spot.

**Comment by shikadiqueen** [comment] 2020-01-25 18:29
Also, speaking as a former translator myself, in no way does this impede your work, so it's not so much a bug as it is something that could use some improvements that may or may not be feasible.

**Comment by Wedge009** [comment] 2021-09-15 10:26
There are quite a few issue reports that discuss plurals in translation - would #1259 have any bearing on this one?

**Comment by stevecotton** [comment] 2021-09-15 11:19
#6036 is a duplicate of this (which I logged, oops). Might keep that one and close this one, as #6036 has more discussion about fixing it.

@irydacea, which of us should work on fixing it? I stopped because I thought you wanted to take it, but now think that was just a misunderstanding.

**Comment by Wedge009** [comment] 2021-09-15 11:23
Definitely better to consolidate further discussion in #6036 then...

**Closed by Wedge009** 2021-09-15 11:23 UTC
Labels: Enhancement, Translations
