### ISSUE TITLE
Cumulative leadership doesn't work

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#6466] opened 2022-01-27 19:33 UTC
### Game and System Information
 - What version of the game are you running? 1/16.1
 - Where did you download it from? flatpak

### Describe the bug
Cumulative leadership doesn't stack with other leaderships it should stack with (with different ids)

### To Reproduce
One of the easiest ways: get War Banner in World Conquest and place a unit near any leader and the banner-bearer. The banner provides cumulative leadership but it doesn't work

### Expected behavior
Units get increased leadership bonus

### Savefiles
[WC2-WC II 2 - Start Turn 1Cumulative.gz](https://github.com/wesnoth/wesnoth/files/7953278/WC2-WC.II.2.-.Start.Turn.1Cumulative.gz) A save of WC with War Banner and Elvish Marshal to play with

### Additional context
In 1.14 it worked

**Comment by newfrenchy83** [comment] 2022-01-28 12:23
In 1.16, cumulative mustn't be used in [leadership], instead you must replace value by 'add' or sub' for cumule value. i will try to renabled that without remove 'add' or 'sub' but i don't think what it was accepted in 1.16 or master.

**Comment by Discontinuum** [comment] 2022-01-28 18:08
Should we mention it in the docs, or has it been already mentioned?

**Comment by newfrenchy83** [comment] 2022-01-28 18:51
> Should we mention it in the docs, or has it been already mentioned?

it hasn't already mentionned, but i pull 2 PR for fix this issue, and it must wait what this was merged or not inmaster and 1.16 branch.

**Comment by Discontinuum** [comment] 2022-01-28 18:54
I mentioned it
> and it must wait what this was merged or not inmaster and 1.16 branch
In Discord @Pentarctagon said to merge the API fix only in 1.17, if I'm not mistaken

**Comment by newfrenchy83** [comment] 2022-01-28 19:02
Then mention in docs for 1.16 branch, what value and cumulative=yes must be replaced by add or sub and cumulative=no

**Comment by Pentarctagon** [comment] 2022-01-28 19:04
A change to the API can't be implemented in 1.16 since it would break compatibility with previous 1.16 releases in MP as well as replays.

**Comment by Discontinuum** [comment] 2022-01-28 19:08
>  by add or sub and cumulative=no
why cumulative=no should be in place?

**Comment by newfrenchy83** [comment] 2022-01-28 19:14
> > by add or sub and cumulative=no
> 
> why cumulative=no should be in place? I don't get it

if cumulative=yes with 'value' and value is negative, then final value will be 0. Keep cumulative=no for don't make error. No problem with add or sub but prudence

**Comment by Discontinuum** [comment] 2022-01-28 19:33
Hm, and if we have two units with the same ability with "add=" instead of cumulative=yes and value=, they will stack or not?

**Comment by newfrenchy83** [comment] 2022-01-28 19:37
if same ability, then add added one time. the stack is with abilities with diffrent id

**Comment by stevecotton** [comment] 2022-04-20 20:14
I'm puzzled by the specification (which is unchanged in the last 10 or so years, other than adding a link to this bug report):

> * cumulative: if set to 'yes', this ability will be cumulative with the base value for this ability.
> * id: this ability will not be cumulative with other abilities using this id. Must be present if cumulative is anything other than 'yes'.

Given that spec, I'd expect a combination of `[leadership]id=X, cumulative=no` and `[leadership]id=Y, cumulative=no` to have the cumulative effects of X + Y. That doesn't sound logical, but it's the only meaning I can see for `id`'s documentation - if it did something else then one or other of the two sentences for `id` could be omitted.

Please can someone give a spec for the edge-cases that it's expected to handle?

I'm looking at unit-testing it, and wondering if new unit tests should become the specification for what it should do. At the moment I'm still trying to understand what the edge cases should be, particularly as the changes in #6468 will change a common path that affects other abilities too.

**Comment by newfrenchy83** [comment] 2022-04-20 21:46
> I'm puzzled by the specification (which is unchanged in the last 10 or so years, other than adding a link to this bug report):
> 
> > * cumulative: if set to 'yes', this ability will be cumulative with the base value for this ability.
> > * id: this ability will not be cumulative with other abilities using this id. Must be present if cumulative is anything other than 'yes'.
> 
> Given that spec, I'd expect a combination of `[leadership]id=X, cumulative=no` and `[leadership]id=Y, cumulative=no` to have the cumulative effects of X + Y. That doesn't sound logical, but it's the only meaning I can see for `id`'s documentation - if it did something else then one or other of the two sentences for `id` could be omitted.
> 
> Please can someone give a spec for the edge-cases that it's expected to handle?
> 
> I'm looking at unit-testing it, and wondering if new unit tests should become the specification for what it should do. At the moment I'm still trying to understand what the edge cases should be, particularly as the changes in #6468 will change a common path that affects other abilities too.

I tested the appearance of two leadership with two different IDs, and it is always in the case of positive values the strongest valuer that is taken into account when cumulative = no, and this observation remains valid when I uses the old code with 'highest ("value")' instead of leader_effect.get_composite_value (), the only difference is that cumulative = yes no longer works with leader_effect.get_composite_value () unless you apply the repair I'm propose.

So when 'value' do not add up with two leadership with different 'ID' and with cumulative = no for both is perfectly normal, it is for that the cumulative option = yes existed for leadership.

**Comment by Pentarctagon** [comment] 2022-04-20 23:33
My interpretation from reading the wiki text is just that the `id` field is required for non-cumulative leadership abilities. What exactly happens if both `id` is set and `cumulative=yes` is undefined.

So just based on the wiki text, I'd say that I'd expect the result of having multiple leadership abilities applied to the same unit effectively be:
```
max(any individual positive non-cumulative leadership, sum of positive cumulative leaderships)
+
min(any individual negative non-cumulative leadership, sum of negative cumulative leaderships)
```

**Comment by Discontinuum** [comment] 2022-04-20 23:58
My interpretation would be that `id` makes sense only for cumulative abilities. For non-cumulative abilities it has no effect. If there are two cumulative abilities with the same `id`, only the greatest one applies (and cumulates). So according to me, the formula is

`max (all non-cumulative) + sum over all ids (max of all cumulative with ID)`

For example, we have 25 non cumulative, two cumulatives with id =X, values 25 and -25 and another two cumulatives with id = Y, values -10 and -15. The result would be

25+ max(25,-25) + max (-10,-15) = 25 +25 + (-10) = 40

**Comment by newfrenchy83** [comment] 2022-04-21 09:50
We must have that:
if same id and cumulative=no, value applied one time, and some the first leadeship in list used.
if same id and cumulative=yes , value of cumulative can be added to value of leadership with other id, but one time only.
if diffrent id and cumulative=no, highest(pos_value) + lowest(neg_value)
if diffrent id and cumulative=yes, sum of pos_value) + sum of neg_value)

**Comment by newfrenchy83** [comment] 2022-04-21 13:26
We must have that:
if same id and cumulative=no, highest(pos_value)+lowest(neg_value)
if same id and cumulative=yes ,highest(pos_value)+lowest(neg_value)
if diffrent id and cumulative=no, highest(pos_value) + lowest(neg_value)
if diffrent id and cumulative=yes, sum of pos_value) + sum of neg_value)
but we have that:
if same id and cumulative=no, highest(pos_value)+lowest(neg_value)
if same id and cumulative=yes ,highest value
if diffrent id and cumulative=no, highest(pos_value) + lowest(neg_value)
if diffrent id and cumulative=yes, sum of pos_value) + sum of neg_value)

**Comment by newfrenchy83** [comment] 2022-04-22 13:02
@stevecotton for https://github.com/stevecotton/wesnoth/commit/6cc39b55f2229f07fc0249fa02e2acda765a8ea9 , if you rebase commit for integrate https://github.com/wesnoth/wesnoth/pull/6468/commits/bc74b41094e2986b840edf3b671c866b58b503a4 you must expect that now:
with same id and cumulative=yes, if pos_value, the highest value is used, if neg_value, the loewest value is used, and if(very few probable) both pos_value and neg_value,then pos_value +neg_value(but i tested what 1 pos_value and 1 neg_value in same time, i don't recommand to test that with same id).
the goal to that, like for add,sub,multiply or divide, is to added one value by id (the extremum) like in regular leadership or if value is identical for two leaders(same level) and one student, value used one time, and if value different, the highest(or lowest for neg_values). If you want what two values was both used, you must use two id different, like in utbs "formation" abilities(many abilities in one)

**Comment by newfrenchy83** [comment] 2022-04-22 14:01
Oh, i tested the same id and cumulative=yes case with highest("value").first, and this the sum of value who is added, and i think what it is the cause to why cumulative=yes is alos few used in leadership, if student adjacent to 5 leader with leadeship with cumulative=yes, then damgage increased to(value* 5)%, for one attack who inflict 5 point of damage and leadership to 25%, the result is:(5+ 5*(5*0.25))=11 or 12 damages. For me the playability was not balanced and the useof cumulative=yes abandonned because of this.
with my PR a leadership with cumulative=yes can be added with leadership to same id and cumulative=no.

I would have interpretation of other participant to this issue for know if i must fixed that or this my PR must remain like now.

**Comment by newfrenchy83** [comment] 2022-04-22 14:28
I fixed this in my local fork, and i now 4 possible cases:
two leadership with diffrente 'value' and cumulative=no, highest pos_value + lowest neg_value
3 leadership, one with 'value' and 2 with same id adn 'add' or 'sub' instead of value: value + add or value- sub each 'add' or 'sub' added on e time, andi if value of add or sub diffrente, highesdt 'add' or lowest 'sub' used
3 leadership, one with 'value' and 2 with differente id and 'add' or 'sub' instead of value: leadership1value (+ leadership2'add'+ leadership3'add') or (-leadership2'sub' - leadership3'sub')
2 or more leadership with sameid or not, and cumulative=yes for 'value': value1+value2+..+value5.

If you think what these cases are valid, let me know and i push fixing in my PR for what @stevecotton  could retest his commit

**Comment by newfrenchy83** [comment] 2022-04-23 16:22
Finally, i fixed the bug in @stevecotton  in hard source code

**Closed** 2022-05-19 23:13 UTC
Labels: Bug, Campaign, MP, Units, Regression
