### ISSUE TITLE
Error message (possibly invalid WML) while updating Add-ons

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3059] opened 2018-05-09 07:38 UTC
While updating my Add-ons, this happened:
![wml](https://user-images.githubusercontent.com/39015360/39801718-6f6ca0c0-536c-11e8-89ee-2fd52648da2d.png)
Wesnoth did not crash afterwards, I was just returned to the main screen.
I had an Add-on description open, when I used the 'Update all' button. (It's reproducible this way.)
And it apparently finished updating.

**Comment by Konrad22** [comment] 2018-05-09 13:44
(My case is the small(er) window.)

**Comment by jyrkive** [comment] 2018-08-11 16:46
@Konrad22 mentioned in Discord that it also occurs if he presses a key while having addon description open.

My first guess would be that the search field attempts to do something while the addon list is hidden.

**Comment by Konrad22** [comment] 2018-08-11 16:53
Small update: Enter or Esc do not trigger this. But things like alt gr + q for special symbols do trigger it.

**Comment by CelticMinstrel** [comment] 2018-08-11 19:59
Based on the error message, I think that @jyrkive is almost certainly correct in his assessment of the cause.

Possible fixes:

* Treat it as optional; if it's found to be hidden (`find_widget` returns null), don't update anything, just note that it needs to be updated when it's shown later.
* Ensure that the list is visible before working with it; then if it was originally hidden, hide it again when done.

**Comment by Konrad22** [comment] 2020-12-09 17:31
Why you this needs to be fixed beofre 1.16:
This error message will appear (and close the add-on manager) every single time the user tries to select an older version of an add-on in the add-on description.
(Why selecting an older version is possible: https://github.com/wesnoth/wesnoth/pull/5038)

**Comment by CelticMinstrel** [comment] 2021-02-13 22:08
Huh, is this still not fixed? I don't think it would be all that hard… might even be a good first issue for someone…

**Comment by stevecotton** [comment] 2021-05-26 14:17
There are multiple paths that result in the same error message. I've just posted a fix to one specific path in #5810, but I'm wondering if calling stacked_widget::set_find_in_all_layers(true) would be a more general solution.

**Comment by stevecotton** [comment] 2021-05-30 13:13
As pointed out on IRC, this is going to be much easier to trigger in 1.16, and IMO it's something that should be a blocker.

**Comment by stevecotton** [comment] 2021-06-20 19:06
Two separate causes of this were fixed in #5820, I think it makes sense to close this issue (and open a new one if there's another way to cause the issue).

**Closed by stevecotton** 2021-06-20 19:06 UTC
Labels: Blocker: New Stable, Bug, Good first issue, UI
