### ISSUE TITLE
game map unresponsive (GNA #25467)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1622] opened 2017-05-08 12:55 UTC
**[Original submission](https://gna.org/bugs/index.php?25467)** by sapient on 2017-01-25

I downloaded the latest dev release available on Sourceforge (1.13.6) Win32 (didn't see a Win64 available).

I am able to start a campaign or tutorial, but only the menu at the top responds to clicks.

If I do Actions->Next Unit, it will jump to Kaleh or whoever. But pressing "n" has no effect, nor clicking the unit.

I also noticed that pressing ctrl-alt-m does not turn off the music, but I was able to turn off the music through the preferences menu.

I am able to scroll around the map when my mouse pointer is at the edge of the map, but using the keyboard arrows does not scroll the map.

Logs:

I am not attaching my log file because there were no UI related messages in there.

System Details:

I am using a laptop with a Japaneses keyboard layout.

I am using the trackstick and trackpad buttons, not an external mouse.

Installed Physical Memory (RAM)	16.0 GB

OS Name	Microsoft Windows 7 Professional

Version	6.1.7601 Service Pack 1 Build 7601

System Model	Latitude E5530 non-vPro

System Type	x64-based PC

Processor	Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz, 2901 Mhz, 2 Core(s), 4 Logical Processor(s)

(Reproduced on Windows7Pro64)
Release: 1.13.6
Priority: 5 - Normal
Severity: 5 - Blocker

**Comment by wesnoth-bugs** [comment] 2017-05-08 12:55
**Modified on 2017-01-27**

**unwiseowl wrote:**

> I've had this occur a couple of times also on 1.13.6. I haven't been able to reproduce, but I am pretty confident that it occurred on tabbing in/out of the game.

**Comment by wesnoth-bugs** [comment] 2017-05-08 12:55
**Modified on 2017-01-30**

**wedge009 wrote:**

> There is no Win64 build as far as I know - there isn't really any benefit to making one at the moment.
> 
> 
> 
> This sounds more like a keyboard mapping issue rather than UI responsiveness since you say things are still working with, so I've changed the title to reflect this. Please let me know if I have it incorrect.
> 
> 
> 
> Are you familiar with the QWERTY keyboard? Can you confirm if you're still having these non-working hot-keys if you select a US keyboard layout (for example)?

**Comment by wesnoth-bugs** [comment] 2017-05-08 12:55
**Modified on 2017-02-28**

**gfgtdf wrote:**

> I had a similar issue when i resized the window during the loadingscreen dialog. Are you didn't do a similar thing before?

**Comment by wesnoth-bugs** [comment] 2017-05-08 12:55
**Modified on 2017-03-20**

**gfgtdf wrote:**

> please test whetehr this stil occurs in 1.13.7

**gfgtdf changed status:** None -> Ready For Test

**Comment by wesnoth-bugs** [comment] 2017-05-08 12:55
**Modified on 2017-03-23**

**sapient changed status:** Ready For Test -> Fixed

**sapient wrote:**

> With 1.13.6 it was happening every launch.
> 
> I haven't yet been able to reproduce the bug with 1.13.7.
> 
> I'm assuming it has been fixed.

**Comment by wesnoth-bugs** [comment] 2017-05-08 12:55
**Modified on 2017-03-23**

**gfgtdf wrote:**

> hmm it may not be fixed yet, a similar bug was reported in the forums, see https://forums.wesnoth.org/viewtopic.php?f#5&t45175#p609811.

**Comment by wesnoth-bugs** [comment] 2017-05-08 12:55
**Modified on 2017-03-23**

**gfgtdf wrote:**

> this commit https://github.com/wesnoth/wesnoth/commit/d22a4ca6962d1ac0ef0ad63d9f0e9a8a002a2128 from vultraz could also fix it.

**Comment by wesnoth-bugs** [comment] 2017-05-08 12:55
**Modified on 2017-04-15**

**gfgtdf wrote:**

> i got this one quite often when testing 1.13.7 specially when observing mp games, so this is not foixed on 1.13.7 . Still vultraz commit below which wasn't in 1.13.7 could have fixed it.

**gfgtdf changed status:** Fixed -> Confirmed

**Comment by CelticMinstrel** [comment] 2017-05-15 04:46
@gfgtdf So did the linked commit fix it or not? Is this still an issue?

**Comment by gfgtdf** [comment] 2017-05-15 10:06
> @gfgtdf So did the linked commit fix it or not? Is this still an issue?

we don't know since this bug appeary a little randomly so we cannot easiyl test whether its fixed, the current plan i to see whether someone reports it on 1.13.8 release.

**Comment by gfgtdf** [comment] 2017-07-17 21:42
Ok this just happend to me on 1.13.8, so it's not fixed yet.

**Comment by gfgtdf** [comment] 2017-08-02 13:12
Ok i thought about this some more, and i think its casued by: https://github.com/wesnoth/wesnoth/commit/c3eb503c6ec4b4b8aa96d41fda012590fb8260b1 . The problem is that open_window_stack.pop_back(); is not called when window->show exited with an exeption so that is_in_dialogs will always return true form that point on until wesnoth is restarted.

**Comment by CelticMinstrel** [comment] 2017-08-03 00:06
I can reproduce this with the steps you describe. If you're correct about the cause, I'll have it fixed in a couple of minutes (plus compile time).

**Closed** 2017-08-03 00:41 UTC
Labels: blocker, bug, confirmed, UI
