### ISSUE TITLE
Wrong Numbering of Scenario Count

### ISSUE THREAD

**Issue by Gweddeoran** [wesnoth/wesnoth#4059] opened 2019-05-01 02:34 UTC
In TRoW, it should be 20 scenarios and for SotA it should be 18. Also, there seems to be a bug where difficulties for AToTB and UtBS do not show up at certain resolutions.

**Comment by slavrenyuk** [comment] 2019-05-04 05:03
More details in this post https://forums.wesnoth.org/viewtopic.php?f=38&t=4439&p=641380#p641379

**Comment by jostephd** [comment] 2019-05-06 21:44
Triaged this as the scenario numbering issue. Let's discuss the other bug on the forums.

**Comment by sigurdfdragon** [comment] 2019-05-13 03:00
The TRoW & SotA scenario counts have been corrected

**Comment by nemaara** [comment] 2019-05-13 03:25
We can use this to track the other issue, which is no longer a campaign nor a prose issue.

**Comment by nemaara** [comment] 2019-05-13 15:02
Actually this does seem to be a duplicate of #3443, so we can put any more information regarding this issue there.

**Closed by nemaara** 2019-05-13 15:02 UTC
Labels: Engine, UI
