### ISSUE TITLE
Multiplayer local game lobby ui issues

### ISSUE THREAD

**Issue by wang1986one** [wesnoth/wesnoth#2828] opened 2018-04-03 17:22 UTC
Multiplayer ---- local game ---- select random map ---- set player num 9 ---- create game ---- 1 local player + 8 computer players

When move the list, the lobby ui is error

And , you can't select the team leader in the last ,such as Loyalists -- White Mage

IOS ver 1.13.13

**Comment by soliton-** [comment] 2018-04-08 18:14
Selecting the team leader works for me.

**Comment by hrubymar10** [comment] 2018-04-19 17:49
Lobby UI error is reproducible only with American English for me. I can't reproduce it with Czech. (I only tested these 2 languages).

I can't reproduce your 'White Mage' bug.

**Comment by Wedge009** [comment] 2018-05-03 02:29
Not really sure what the error here is supposed to be. Understand the reporter's native language is likely not English.

**Comment by Wedge009** [comment] 2019-10-16 01:29
I tried again at 1.14.9 release, still don't know what 'lobby ui is error' is supposed to mean.

@hrubymar10 Do you remember what the error was from your statement 'with American English'?

**Comment by Wedge009** [comment] 2019-10-16 01:50
Okay, #2897 does indeed seem the same as this one. And it does look like it might be macOS/iOS-specific as well. Closing this one in favour of #2897.

**Closed by Wedge009** 2019-10-16 01:50 UTC
Labels: Bug, MP Lobby, Needs more info
