### ISSUE TITLE
WC: transation problems

### ISSUE THREAD

**Issue by hexagonrecursion** [wesnoth/wesnoth#5526] opened 2021-02-08 10:23 UTC
`data/campaigns/World_Conquest/resources/data/artifacts.cfg` uses string concatenation to build user-visible strings eg:
https://github.com/wesnoth/wesnoth/blob/4d4e8e617e229a4dc16a4e7aa69ab166f2c036a0/data/campaigns/World_Conquest/resources/data/artifacts.cfg#L8
Usually using string concatenation to build sentences is a bad idea for internationalization reasons: different languages have different syntax. I think that In this case string concatenation is fine because it is not building an English sentence, but @soliton- disagrees:
> https://github.com/wesnoth/wesnoth/pull/5483#issuecomment-765624614
> For translations I'm pretty sure best would be for example simply: description="17-2 ranged-fire magical"
> 
> What WC assumes is that you can just translate each word in isolation. That might work for some languages that are similar enough to english but it doesn't work well in general.
> 
> I don't know the number of strings in WC and what a change would exactly mean. But WC is new and not sure if it's already gotten any translations so far.

I am opening this issue because of a suggestion by @Pentarctagon:
> 
> https://github.com/wesnoth/wesnoth/pull/5483#issuecomment-770451015
> Should this PR be closed and a general issue opened for translation problems in WC?

**Comment by soliton-** [comment] 2021-02-09 07:45
You're right that it's not about complete sentences so it's certainly less of an issue. Would be good to hear opinions of translators.

**Comment by CelticMinstrel** [comment] 2021-02-11 15:00
See also #5114, this might be a duplicate of that.

There are definitely issues with that specific example. It may not be a complete sentence, but it _is_ building natural language phrases such as "up to 10% resistances". The commas could _possibly_ be better handled by `format_conjunct_list`, although that adds "and" before the last item so maybe it's not necessary, but even if it's not they should probably at least use `stringx.join`.

I did sort of start trying to break all this up but it didn't get very far. Probably it could be broken into a list of "effects" somehow, and there would be a single Lua function which parses those "effects" into a proper description string.

**Comment by shikadiqueen** [comment] 2021-03-12 23:00
Please add any new information to #5114.

**Closed by shikadiqueen** 2021-03-12 23:00 UTC
Labels: Bug, Campaign, Duplicate, MP, Translations
