### ISSUE TITLE
SotBE S14, Lua error after winning the scenario

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4556] opened 2019-11-08 13:16 UTC
### Game and System Information
 - What version of the game are you running?
1.15.2

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Sourceforge

 - What OS are you running?
Windows 10

### Describe the bug
I defeated the last enemy leader (scenario objectives are to defeat all enemy leaders) and then the lua error appeared.

### To Reproduce

1. Start the scenario 'Back Home'.
2. Wait for Grüü to appear (turn 7).
3. Defeat all enemy leaders, e.g. by using debug mode.

### Expected behavior
No Lua error appears. Just the normal grey out because the scenario is over.

### Screenshots
![grafik](https://user-images.githubusercontent.com/39015360/68479199-13153a00-0232-11ea-9bd0-b9e73f2e487c.png)

### Savefiles
[SotBE-Back Home-Auto-Save7.gz](https://github.com/wesnoth/wesnoth/files/3824705/SotBE-Back.Home-Auto-Save7.gz)

**Comment by gfgtdf** [comment] 2019-11-08 19:13
This is probably caused by my recent midufy_unit rrfactir, but I won't be at home until Saturday in 8 days

**Comment by CelticMinstrel** [comment] 2019-11-16 03:44
Does that fix it?

**Comment by Konrad22** [comment] 2019-11-18 20:06
I have no idea, since I don't know how to build wesnoth. I can check at earliest when 1.15.3 is out.
But I'm sure there are other people who can test this.

**Comment by gfgtdf** [comment] 2019-11-18 20:14
> I have no idea, since I don't know how to build wesnoth

this is a change to the lua files, you onyl need to replace those lua files. no building involved

**Comment by Konrad22** [comment] 2019-11-18 22:00
FTR, the content of those lua files was different from the content of 'my' lua files ever before the (so far untested) fix.

**Comment by Konrad22** [comment] 2019-11-18 22:05
I'm getting this instead.
![grafik](https://user-images.githubusercontent.com/39015360/69097920-db8b6680-0a57-11ea-8d82-24f62033d2b8.png)

Did you do the refactor before 1.15.2 was released?

**Comment by gfgtdf** [comment] 2019-11-18 22:09
> I'm getting this instead.

oh yes this is another error, this one  does require rebuilding

**Comment by soliton-** [comment] 2019-11-20 13:16
@Konrad22 can you try with http://files.wesnoth.org/mingwbuild.zip?

**Comment by Konrad22** [comment] 2019-11-21 11:21
To be honest I have no idea what I'm supposed to do with that. Downloading this and the starting that wesnoth.exe throws an assertion error, so I guess that's not what I'm expected to do.

**Comment by soliton-** [comment] 2019-11-21 20:20
Put the files from the zip into a git checkout of wesnoth or wherever you tested the updated lua files earlier.

**Comment by Konrad22** [comment] 2019-11-21 21:40
I just replaced the relevant lua file. I'm not sure if this would work with this stuff as well.

**Comment by gfgtdf** [comment] 2019-11-22 00:05
Honestly I think we know well where this bug came from and I for my part am fine with closing this one without further testing assuming it's fixed.

**Comment by Pentarctagon** [comment] 2020-06-27 16:53
Closing then.

**Closed by Pentarctagon** 2020-06-27 16:53 UTC
Labels: Bug, Campaign, Lua API

**Comment by Konrad22** [comment] 2020-06-27 18:14
FTR, I tested it just now on 1.15.3 and the bug is indeed fixed.
