### ISSUE TITLE
Canceling addon upload doesn't actually cancel the transfer

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2591] opened 2018-03-04 17:11 UTC
Canceling an upload in the addon manager apparently doesn't actually cancel the background operation. If you do so, wait a bit in the manager, exit, and come back, you'll notice your addon marked as published. I've inadvertently published my addon twice this way....

And note it's not just a client-side issue. A user on the forums reported my addon on the server the first time. In all, it has had 21 downloads over the two spurious publications, so it was indeed published.

**Comment by jyrkive** [comment] 2018-03-04 18:06
Quick experiments show that this is difficult to fix.

Before commit c9ec111cf1150d80af844c8d9d33146f9e4556e0, the code attempted to cancel the upload by calling `boost::asio::ip::tcp::socket::cancel()`. The new code attempts to do it by calling the destructor of the socket instead. My tests show that neither operation helps: in fact, this result suggests that this bug also exists in 1.12.

If Boost.Asio refuses to honor when our code orders it to cancel the upload, there isn't much we can do. We could theoretically kill the Asio thread, but it's an extremely dangerous approach.

**Comment by Vultraz** [comment] 2018-03-05 00:49
It was probably mitigated somehow in 1.12 by the manager closing and re-opening... ugh. What to do :(

**Comment by doofus-01** [comment] 2018-03-05 03:55
Speaking purely as a possible end user of this broken cancel feature, not a coder, I wonder if causing all of Wesnoth to shut down would cancel the upload?  I know if I were uploading an add-on, then decided I had to cancel, I would not care much if Wesnoth quit-to-desktop.  It's not optimal, but if this is the brick wall jyrkive seems to suggest, it could be an option.

**Comment by Vultraz** [comment] 2018-03-05 04:01
No. That is not an acceptable solution.

**Comment by CelticMinstrel** [comment] 2018-03-05 18:33
Killing the asio thread would be preferable to quitting the program. What makes that dangerous?

**Comment by GregoryLundberg** [comment] 2018-03-05 20:41
The problem is that the receiving end has no way to know if the end of the TCP stream is a cancelled upload or the normal end of the upload.

Terminating the program, cancelling the thread, disallowing the cancel function or throwing a random exception from elsewhere in the program are functionally identical to the receiver.

I would suggest uploading to a temporary file and adding a command which says, "That file I just uploaded? I'm done, please rename it to <this> and keep it for me, if you would."

The cancel button would try (possibly with an undetectable failure) to stop sending the file, then follow with a different command which says, "Oops, sorry. Forget that, please."

And, to handle all other cases such as network failures, hardware failures, program crashes or Blue Screens of Death, the server should eventually time-out waiting for one of the two above commands and behave as if a cancel command has been received.

**Comment by AI0867** [comment] 2018-03-05 21:02
All gzipped WML documents are prefixed by their length, so it should be perfectly possible to distinguish between an interrupted transfer and a completed one.

**Comment by GregoryLundberg** [comment] 2018-03-05 21:05
Nope.

What you're doing is making it a race condition: did you click cancel before or after the server saw the length was equal and committed your change, before or after you got the positive reply about the upload and updated the UI.

Unless you want the Issue "I clicked Cancel and it uploaded anyway!"

**Comment by AI0867** [comment] 2018-03-05 21:08
Sure, it doesn't fix *all* of the cases (similar to an HTTP POST to a forum, for example), but if you can stop the transfer before all the bytes leave your output buffer, the server should be able to notice that.

**Comment by GregoryLundberg** [comment] 2018-03-05 21:09
So there are times when it won't have to wait for a time-out. Same thing as if it gets a Connection Reset error waiting to read more.

**Comment by jyrkive** [comment] 2018-03-05 21:15
@CelticMinstrel If the thread happens to be in the middle of memory allocation, killing the thread means that the heap lock will never be released. As a result, the game freezes as soon as it attempts to allocate memory next time.

It would be a rare situation, but extremely annoying when it occurs.

**Comment by jyrkive** [comment] 2018-03-06 18:53
Fixed in commit 67e292704400901e66720b269d45094a7351251c.

**Closed by jyrkive** 2018-03-06 18:53 UTC
Labels: Addons Server, Blocker, Bug, Urgent
