### ISSUE TITLE
Title screen GUI design

### ISSUE THREAD

**Issue by nemaara** [wesnoth/wesnoth#4531] opened 2019-10-31 22:33 UTC
Making an issue for this finally, since I've been talking about it for a while: here would be some general things about improving the title screen and in game GUIs (which it really would be nice to improve). I'll split the in game GUI discussion into a separate issue.

One fundamental thing in GUI design is using layout, sizing, and coloring to draw attention to elements with different importance. The (functionally) most important elements also need to be the largest and stand out the most in the design. Another important thing is how much information you have in the GUI: every extra piece added dilutes all the other information contained in the display. In general, in the base display, only the most important things need to be there, and extra information can be shoved into side menus to avoid cluttering the base display. **_The primary goal is ease of use and understanding (not how much information you can cram into one space)._** With this in mind, let's look at our title screen.

![image](https://user-images.githubusercontent.com/13598479/67983640-7f24ec00-fbfb-11e9-9546-5ad9b0f0bf06.png)

As can be seen from the part circled in red, we have 10 (!) buttons on the right all with the same size and coloring with absolutely nothing to differentiate them. Supposing that I were a new player opening up the game for the first time, there is nothing visually to direct me to what I want to do, which is just to play something. The first thing I'm going to think about when opening the game isn't to fix my preferences nor is it to open the help menu. I just want to play the game first, then see if I need help or to fix some options (say, playing without music if it bothers me). 

Next, circled in blue, we have the "tips of the day" section, which is basically the same size as the 10 buttons menu, meaning that the GUI gives it more or less has the same importance as the 10 buttons on the right combined. Obviously, however, tips of the day are not nearly as important as most of the single buttons on the right, let alone all of them combined.

Therefore, when considering the functionality of every section and button on the title screen, we should think about emphasizing only the most important 4-5 buttons, and leave the others to small icons off to the side. "Language", for example, is just a part of preferences and can be merged into that. "Tutorial" can be merged into "Campaigns" in some form. "Add-ons" and "Map Editor" are part of content creation and can be merged into a category as well. "Credits" is definitely not as important to players as any of the above, and probably should be a small button or icon off to the side. Under this design, we'd have "Singleplayer", "Multiplayer", "Content Creation", "Preferences", and optionally a quit button. Note that "Preferences" in many games is also provided as a small icon rather than a separate button.

For tips of the day, a smaller, less centered box with smaller buttons would place less emphasis on it, making it more of a nice detail rather than something that takes up a quarter of the whole screen (and thus has great importance in the GUI). This way, we can visually emphasize the most important elements to the player, namely in order:
1. Playing the actual game (single/multiplayer/load)
2. Content Creation (addons/map editor) - note that this can be minor for other games, but is a big one for wesnoth
3. Quit button
4. Preferences (options and language, possibly an icon)
5. Other things (credits - probably an icon, tips of the day - probably a small box).

An example of a GUI design that we could emulate would be Stardew Valley's titlescreen:

![Capture](https://user-images.githubusercontent.com/13598479/67990337-fbbfc680-fc0b-11e9-9d12-4a2607a76df4.JPG)

In this case, there are only 4 big buttons, 3 of which are related to playing the game. I know immediately where to click if I want to play or exit, which is probably what I really care about doing as a player. Adapting something like this to Wesnoth could be as simple as replacing each of the 4 big buttons with one of our own (SP, MP, Load, Content Creation), then add small icons for everything else.

Tagging @soliton- and @stevecotton since we chatted on some other issues and IRC/Discord about this. I'll put part 2 on the in game GUI up sometime.

**Comment by stevecotton** [comment] 2019-11-01 14:12
In games that just have a "new" button, then I'd expect that to start with tutorial-ish scenarios. Putting the button for new players on the first screen, I imagine something like this as the first screen:
![wesnoth_start_with_campaigns](https://user-images.githubusercontent.com/101462/68030369-9cb88b00-fcb9-11e9-834d-846d02d3f6e7.png)

I think add-ons shouldn't be part of "content creation", there will hopefully be many more players installing UMC than authors creating UMC.

For tip-of-the-day, instead of next/previous let's just have a "more" button that opens a help page with all of the tips in it.

**Comment by CelticMinstrel** [comment] 2019-11-02 00:38
I can see the reasoning for mixing the tutorial into the main campaign menu, but I'm not sure I like the idea for some reason...

**Comment by nemaara** [comment] 2019-11-02 00:49
> In games that just have a "new" button, then I'd expect that to start with tutorial-ish scenarios. Putting the button for new players on the first screen, I imagine something like this as the first screen:

So for a lot of games I've played, the tutorial is actually merged into the first campaign, or is a very small thing off to the side (like in a side menu). I'm not sure I like it at the very top of the campaign list either, but I don't think it needs a separate button on the main screen either. Maybe in an ideal case, we'd merge it into AToTB or TSG. For now, the easiest patch solution might be what you have there?

You have a point about addons, so maybe we'd leave that as its own button, and move the map editor to a smaller icon somewhere else?

Tips of the day, I was more thinking the box is way too large, but the buttons are a bit irksome too. I originally thought about having them be arrows instead, but it could be easy enough to just put all the tips in the help menu. Biggest issue for me is that it just takes too much space and importance away from the actual "buttons that do something" in the other menu.

Of course all of this depends on how easy it is to work with the GUI code, which as I understand it, is pretty difficult to manage right now.

**Comment by CelticMinstrel** [comment] 2019-11-03 00:26
What about giving the tutorial a separate button in the campaign window rather than including it in the campaign list? Not sure that's a good idea either, but I feel that it'd be a little better than showing it in the campaign list…

I'm not sure if merging it into AToTB or TSG or even AOI is a good idea? First of all, that means anyone playing those campaigns (at least on easy) are forced to interact with the tutorial (though I suppose there could be a skip option…). Also, there's no way the current tutorial could be shoehorned into any existing campaign, and by trying to do so, I think the lessons would be harder to cover in a logical manner without detracting from the campaign. Maybe you could come up with a totally new tutorial as part of an existing campaign; I'm not sure how that would compare to the existing one…

For tips of the day, I think I like the idea of making it smaller and changing the buttons to arrows, like you often see on the front page of websites to scroll between several banners.

**Comment by nemaara** [comment] 2019-11-03 00:32
> What about giving the tutorial a separate button in the campaign window rather than including it in the campaign list? Not sure that's a good idea either, but I feel that it'd be a little better than showing it in the campaign list…
> 
> I'm not sure if merging it into AToTB or TSG or even AOI is a good idea? First of all, that means anyone playing those campaigns (at least on easy) are forced to interact with the tutorial (though I suppose there could be a skip option…). Also, there's no way the current tutorial could be shoehorned into any existing campaign, and by trying to do so, I think the lessons would be harder to cover in a logical manner without detracting from the campaign. Maybe you could come up with a totally new tutorial as part of an existing campaign; I'm not sure how that would compare to the existing one…

Yea I'm with you on both of these. I'd rather have a small button in the campaign window than have it appear in the campaign list, but not sure how hard that is. Merging it into TSG or AToTB would be not that trivial, and I've never been a fan of forced tutorials personally (though there's a lot of them that I can think of...). The most elegant solution (ideal case) might be finding a way to merge the tutorial into a novice campaign, but that's probably not practical for now.

**Comment by CelticMinstrel** [comment] 2019-11-03 00:36
Well, moving it to a small button in the campaign screen would I think be a pretty easy change, if we want to do that. At least, the implementation of the UI change in the UI would be fairly simple; some of the C++ logic for the titlescreen and main game loop would probably have to be tweaked to support it, though, and I'm not quite sure how hard _that_ would be.

**Comment by stevecotton** [comment] 2019-11-03 00:50
Please would you make a mock-up of this? I think the tutorial is essential for first-time players, so I'm not following how making it a small button helps.

**Comment by nemaara** [comment] 2019-11-03 16:02
Hmm, I have to admit I'm pretty biased against tutorials, but I think you have a point that the tutorial is something players should be able to find easily. I think a small button is still okay as long as the placement is good. Maybe a button in the red circled area (same size as or slightly wider than "OK and "Cancel")? It could also be further to the left, i.e. left aligned with the campaign text as well (blue circled area). 

![image](https://user-images.githubusercontent.com/13598479/68088057-3d798880-fe29-11e9-8137-33a0f46aee6a.png)

P.S. The reason I don't personally like the tutorial in the campaign list is that it's not a campaign. It doesn't fit in the same category as literally the other 18 things on that list.

**Comment by stevecotton** [comment] 2019-11-03 16:33
I think you're underestimating the importance of the tutorial. Try playing the first scenario of AToTB, on easy, as if it's your very first go of Wesnoth and no-one has told you:
* that you can recruit
* the day/night cycle and its effects
* anything about villages
* what any of the numbers in that sidebar mean

I think you'd probably get to the second scenario, assuming your leader didn't die, but with a lot less troops than a rookie would need to win the second scenario. However, considering @CelticMinstrel 's feedback about watching rookies die on Tutorial S02, I'm probably being overly optimistic.

Conclusion: if your UI guidelines would make new players more likely to play AToTB than the tutorial, then your UI guidelines aren't right for this situation.

**Comment by nemaara** [comment] 2019-11-03 16:39
That's true, in which case couldn't we have a popup that says something like "You have not yet played the tutorial. Are you sure you want to proceed onto the first campaign?" (a lot like the "do you want to delete this save pop up"). Then the player can disable that message if they want, or it can be autodisabled upon completing the tutorial.

**Comment by sigurdfdragon** [comment] 2019-11-06 19:16
What about putting the tutorial at the top of the campaign list, but spicing up its title & description a bit?

Call it "Combat Training" or "Battle School" or something
The battle dummy icon seems good for that.
Some sort of catchy portrait/scene for the description section.

A description like:
Learn the basics of fighting and then foil an orc attack.
(Tutorial, 2 scenarios.)




Maybe also have a lock on the rest of the campaign menu until the tutorial is completed?

**Comment by AI0867** [comment] 2019-11-06 19:57
> Maybe also have a lock on the rest of the campaign menu until the tutorial is completed?

That's a good way to annoy people who have played the game before, but are using a fresh install.

**Comment by nemaara** [comment] 2019-11-06 20:05
> What about putting the tutorial at the top of the campaign list, but spicing up its title & description a bit?
> 
> Call it "Combat Training" or "Battle School" or something
> The battle dummy icon seems good for that.
> Some sort of catchy portrait/scene for the description section.
> 
> A description like:
> Learn the basics of fighting and then foil an orc attack.
> (Tutorial, 2 scenarios.)
> 
> Maybe also have a lock on the rest of the campaign menu until the tutorial is completed?

I like the first idea! Gives the game and the tutorial some personality/style. Having it be pseudo-canonical would also make me feel a bit better about having it be in the campaign screen.

Locking the rest of campaign menu until the tutorial is completed is counterproductive, especially for people like me who usually skip tutorials. Having it be at the top is probably good enough.

**Comment by nemaara** [comment] 2019-11-15 03:06
Okay hi everyone, I've been working on the titlescreen a little bit and have somewhat of a prototype. I'm putting this here now for comments.

![image](https://user-images.githubusercontent.com/13598479/68913776-77506600-072a-11ea-98e8-ca047e615db7.png)

There's still a couple things to do like:

Remove the right side panel and make the buttons text-only (but much larger and maybe with a different font).
Make some of the buttons (preferences, quit, editor) into large, translucent icons in the top right.
Move around/improve some smaller elements like the info button in the lower left and version string.
Find a new home for tips of the day.

**Comment by CelticMinstrel** [comment] 2019-11-15 03:13
What about moving the tips of the day to a separate modeless dialog that appears centred on top of the title screen when you first launch the game? The debug clock could perhaps be used as a reference for how to do a modeless dialog.

* Add a small "tips" button somewhere in the bottom row (along with the info and language buttons) which toggles the tips on and off.
* Have a "don't show again" checkbox in the tips, if checked the tips will never show on startup.
* If that checkbox isn't checked, tips show every time you start the game, but not when you return to the titlescreen (probably some flag is needed to track this).
* Tips dialog still has a next button in it, but help button is moved somewhere else (perhaps a ? button somewhere near the screen's edge).

Which reminds me, you forgot to include the help button in your screenshot!

**Comment by stevecotton** [comment] 2021-01-29 11:46
The language icon (or its placement) seems to be causing problems, I've seen three or four people commenting about it. I recall one on IRC, and there's another today in the 1.15.9 release topic, <https://r.wesnoth.org/p662289>.

**Comment by stevecotton** [comment] 2021-05-17 14:16
Given that 1.16 enters string freeze in a month, what's planned to be done with the title screen before then?

If we're not going to reach a new design then I'm planning to move the language button back to a more obvious location.

**Comment by nemaara** [comment] 2021-05-17 16:17
That would need @shikadiqueen and @Vultraz to comment, especially Vultraz since he's the UI maintainer.

**Comment by shikadiqueen** [comment] 2021-05-17 21:49
You've probably seen that I intended to give it a proper label and move it somewhere else (I posted the screenshots back in February) but that plan doesn't make any sense without a wholesale titlescreen redesign.

I will say "three or four people" by itself is not a good argument to change or revert anything.

**Comment by stevecotton** [comment] 2021-05-18 03:34
Could you add a link to February's screenshots please?

For an argument about why the button needs to move, note that it moves further from the center of the screen as the screen size increases, and it doesn't scale with screen size. On an 800x600 window it's easily noticeable, but on 2560x1440 it's less obvious than either Dan Tonk or Weldyn.

Contrast that with the Stardew Valley image that's been posted as a design aim, where the only button that's as discrete is the music button.

**Comment by shikadiqueen** [comment] 2021-05-18 03:48
Sorry, it was March rather than February. I don't want to post the screenshots without the context because people already have a bad habit of taking everything I do out of context as it is, so I'm just going to link to the Discord conversations instead:

* https://discord.com/channels/231976805987385345/259976436490829825/824527114748297256
* https://discord.com/channels/231976805987385345/259976436490829825/824716737638432778
* https://discord.com/channels/231976805987385345/259976436490829825/824846648273797171
* https://discord.com/channels/231976805987385345/259976436490829825/824869993304031263

**Comment by shikadiqueen** [comment] 2021-05-18 03:50
> For an argument about why the button needs to move, note that it moves further from the center of the screen as the screen size increases, and it doesn't scale with screen size. On an 800x600 window it's easily noticeable, but on 2560x1440 it's less obvious than either Dan Tonk or Weldyn.

If anything this only further supports the notion that we need to stop using that stupid map (as beautiful as it is) as a titlescreen background. It's always been fighting with the actual UI elements over attention regardless of your game window size, but obviously it becomes an even bigger issue at larger sizes.

**Comment by Wedge009** [comment] 2021-09-15 09:29
I realise this is an ongoing work - so far the changes I notice from 1.14 to 1.16 will be:
* Tutorial moved into the Campaign menu
* Slight campaign menu redesign and use of background images (makes use of story images that might otherwise only be used once or twice)
  * I assume it's deliberate, but portraits are removed from some campaign descriptions, perhaps to avoid clashing with the new backgrounds? I see this for:
    * Two Brothers
    * Liberty
    * Descent into Darkness
    * The Rise of Wesnoth
    * Northern Rebirth
* The Language menu is moved to a sort of globe icon in the bottom-right corner.
* Everything else is much the same as 1.14.

I don't mind the move of the Language option, however I definitely agree the size of the button is a problem. The 'i' icon on the bottom-left makes sense to remain small and unobtrusive, but the Language option - if newcomers even recognise it as such upon first glance - really should be a little more prominent (perhaps double the size it is currently in 1.15.17+dev?)

So that makes a good point for changing the main menu background from the traditional map as well - it is indeed pretty but it's only really going to make sense to people familiar with the story, perhaps a bit overwhelming to newcomers. I've been playing since 1.4.x and I can only recall a map of some sort being used for the main menu screen, but I think the choice of The Rise of Wesnoth's Harrowing Escape story image is probably the best and most representative out of all the story screens we currently have available (Fall of Eldaric is already used for the banner image in the Steam library).

I suppose one issue I have with the WIP image from 2019-11-15 is that it drops the 'tip of the day' from the main screen. While I understand the aim of that is to simplify the appearance of the main menu, I can't really think of an alternative place to put it. While I don't really pay it much attention now, it does offer a lot of handy advice to newer players as well as a bit of story flavouring by presenting many tips as quotes from in-universe characters. It could be moved to Help... but I don't think that gives it enough visibility.

It would likely be a challenge to accommodate all the different window sizes out there, but I wonder if there's room to squeeze the 'tip of the day' between the logo and the foreground humans, including Haldric, on the left. Or perhaps a shorter but wider window underneath those same humans.

I read celmin's suggestions on the 'tip of the day' section after writing the above - those sound like good options too. At the very least the Help button needs to stay somewhere.

---

As an aside, I think a tutorial definitely has its place in Wesnoth. I don't think I would have been so keen to get into it all those years ago if I was dumped straight into a campaign, however easy/novice Two Brothers or An Orcish Incursion might be. To attract as many players as possible and lower the bar to entry (and thus increase potential for sales), most contemporary games have some sort of introductory tutorial even with game mechanics much more straightforward than Wesnoth's. Contrast with traditional, physically boxed games where part of the fun/immersion was reading the paper manuals and instruction guides... but that limits it to a rather niche audience. And Wesnoth is distributed on-line so it would have that same opportunity to present instructions in paper form beforehand.

**Comment by stevecotton** [comment] 2021-09-16 13:07
> I don't mind the move of the Language option, however I definitely agree the size of the button is a problem.

Who will be the target audience of that button? I closed #5959 unmerged because there didn't seem to be an audience, as it will auto-detect the system language on end-users' systems.

I'm now wondering if users will want to switch back to en_US if their own language has an incomplete translation.

**Comment by Wedge009** [comment] 2021-09-16 13:15
Is #5959 the right PR? I don't see the connection.

I don't find the system language works well in Wesnoth for me - it seems to go to `en_US`. But even if detection was working well, I think it should be quite clear that different languages are available. It's a good feature and advertising point for Wesnoth to have translation support, isn't it?

**Comment by stevecotton** [comment] 2021-09-16 13:30
Sorry, #5969.

**Comment by Wedge009** [comment] 2021-09-16 13:35
I'm neutral on the idea, but I think the intention is to reduce the number of buttons in the main menu. So I suppose I sound like I'm conflicted - do we hide away the Language menu option or do we make it obvious that it's actually there? I suppose people will disagree with me, but I think it's okay for it to be in the corner with the icon vs the English 'Language' text, but I do think it's too small as-is on high resolution screens.

**Comment by babaissarkar** [comment] 2024-04-10 03:47
We can make the Tips of the Day an animated scroll, that (1) unfurls when the game's titlescreen (this screen under discussion) first loads, then closes to a closed scroll after a while, (2) If the user hover on it, it opens once again, showing it's content

We also definitely need to have more decorated and specialized versions of button (a `[button_definition]`) for the title screen, which may or may not be animated. (by decorated, I'm referring to filigree borders, sometimes seen in other fantasy games, but there may be other viable options)

**Comment by Dalas121** [comment] 2024-05-27 18:34
Some title screen mockups I put together a while ago. I'd been thinking of:
 - When first opened by a new player, always default to the farmland background. But every other time pick a random background and use that one. Add an option to preferences to use a fixed background instead of a random one.
 - News button is highlighted green if there's new news that you haven't yet viewed. Clicking on it opens your browser to somewhere on wesnoth.org.
 - "Add-ons" renamed to "Mods & Add-ons", since Mods is a more currently-used term for UMC.

![main-menu1](https://github.com/wesnoth/wesnoth/assets/33790750/0121ae21-ff23-4e49-8e5c-e1959a475902)
![main-menu2](https://github.com/wesnoth/wesnoth/assets/33790750/5c0f0c1d-5a03-4761-be28-dac68213dbbf)
![main-menu3](https://github.com/wesnoth/wesnoth/assets/33790750/5d3a7f16-f2b6-4980-bd61-03b359fa4923)
![main-menu4](https://github.com/wesnoth/wesnoth/assets/33790750/1c932b9e-6eb4-4341-9a30-ea907e11fd89)
![main-menu5](https://github.com/wesnoth/wesnoth/assets/33790750/4b2e6f33-491f-4ce7-aafe-f1cad1eb4a65)
![main-menu6](https://github.com/wesnoth/wesnoth/assets/33790750/4c929cc5-685b-45e8-8367-ce9da5c18b09)

**Comment by Dalas121** [comment] 2024-06-03 19:00
As this topic seems to be getting some traction, I put together some additional mockups.

![main-menu1](https://github.com/wesnoth/wesnoth/assets/33790750/3840ca2b-d9c9-4b36-8586-9f364c4b0520)

![main-menu1](https://github.com/wesnoth/wesnoth/assets/33790750/4d7e66d4-9394-43cd-b0d1-bf78fb3f677e)
![main-menu2](https://github.com/wesnoth/wesnoth/assets/33790750/8752071a-abfe-4f11-81ec-09ad21d49ec8)
![main-menu4](https://github.com/wesnoth/wesnoth/assets/33790750/6a04cfc2-5b2c-48c6-9a66-e27c0a0a948b)

**Comment by stevecotton** [comment] 2024-06-04 08:02
I think just "Campaigns" is better than "New Campaign". But why is "Tutorial" still a separate item?

If there are already savefiles, it would be good to have "load game" at least as prominent as "new campaign". I think it's still useful to have "load game" even when there are no savefiles, as it communicates to a first time player that yes, they'll be able to load later.

When there was a separate tutorial, I was wondering about a button which showed "tutorial" if there were no save files, and "load game" otherwise.

**Comment by babaissarkar** [comment] 2024-06-04 08:46
@stevecotton  please see the screenshot in #8953 . I think your concerns have already been addressed.

**Comment by CelticMinstrel** [comment] 2024-06-04 13:01
> A left-panel main menu would allow us to show "New Campaign", "Load Game", etc in the central area, instead of using popups like we currently do. IMO popups are quite outdated at this point.

…how can something as trivial as a popup be outdated? Also, if you add it to the middle on top of the title screen you've mocked up, isn't that still a popup?

**Comment by Dalas121** [comment] 2024-06-04 13:12
I haven't seen many (any?) recent games that use pop-ups as major components of their main menu.  Rather, I see games either modify their main menu (e.g. Northguard), or switch screens entirely (e.g. Civ 6).

Maybe "window" is a better term than "pop-up"?

**Comment by CelticMinstrel** [comment] 2024-06-04 13:33
That would make the campaign menu a non-modal window like the debug clock, then.

**Comment by CelticMinstrel** [comment] 2024-06-04 17:35
There is an event dispatching issue with modeless dialogs on the map, yes. As far as I know, that's only on the map.

**Comment by Dalas121** [comment] 2024-06-19 13:27
From the other thread:

> I'd add lack of dedicated smartphone versions (Android and iOS) to the list. The number of people who only play on a phone are fairly large.

This is a great point; I 100% agree with you and ForestDragon.

> Thanks. Having the option to toggle between the two modes makes this a lot more better.

Agreed. I absolutely believe that with how moddable Wesnoth's UI is, any change should include a toggle button for an old UI style, which I expect many veterans will prefer to continue using.

> To be blunt, this UI idea looks nothing like wesnoth anymore, and looks more like some kind of sci-fi RPG

It's not intended to look sci-fi, but it's also not intended to look like Wesnoth.

When I first installed Wesnoth and loaded up the in-game UI, I still remember my initial thought: _"wow, nobody's updated this game in 20 years."_  I was tempted to quit then and there.  And that was **8 years ago**, and coming from someone who still played the occasional brood war (1998).

I've tried to model the UI styling loosely after Fire Emblem Engage, Northguard, and Civ 6 - the 3 newest major fantasy games I could find.  My mockup definitely suffers from a lack of detail compared to those 3, but that's an issue with my skill rather than the intended style.  It's certainly not perfect though, and I'm happy to provide the base .svg file if you can make improvements:

![ingame-ui](https://github.com/wesnoth/wesnoth/assets/33790750/7ff409dc-a97f-4135-a41d-89c02e3c39a6)

> Versions before 1.18 were generally a lot more moderate with what got changed each update, and most of the time the new versions truly felt like an net improvement.

On the flip side, before I got involved in the community I genuinely didn't realize Wesnoth was still being updated. Changes were small and unannounced (in-game at least) to the point of being irrelevant. By this point I'd played through every mainline campaign (except NR) multiple times.

> And the idea of attracting new players seems to have become misused as a mantra to justify any and all changes that old players dislike, whether a significant enough amount of new players actually like the changes or not.

I think that both sides need to be factored in.  If we're changing a long-standing Wesnoth element that barely affects new players, e.g. EI, we need to be primarily considering veteran players.  By the time a new player gets to a campaign like EI, they're not a new player anymore, and our main job needs to be enhancing the experience for our existing playerbase.

But at the same time, if we're changing a "curb appeal" element such as the intro campaigns or the UI (especially with an old-style toggle), then we need to be primarily considering new players. How many veteran players go back and re-play the tutorial, or replay TSG instead of downloading a new add-on?  But every single new player will go through those scenarios.

**Comment by Pentarctagon** [comment] 2024-06-19 14:28
> And the idea of attracting new players seems to have become misused as a mantra to justify any and all changes that old players dislike, whether a significant enough amount of new players actually like the changes or not.

Personally speaking, part of the problem is that it seems like basically any non-trivial, player-visible change to things like the UI, campaign design, unit art, etc result in people complaining about it and wanting it changed back. So not making changes that long time players dislike essentially becomes synonymous with not making any such changes at all ever.

**Comment by Pentarctagon** [comment] 2024-06-19 17:17
...which probably came across as a lot more dismissive than I meant it to be. It's just that having been involved in Wesnoth for as long as I have, it's happened over and over again where something existing is significantly changed and that alone is enough to make a bunch of people unhappy. That doesn't mean that all changes are automatically good either, it just means that people being unhappy with those types of changes is the default and expected rather than a situation that's unusual and can be used as an warning that there's some deeper problem with the change.

**Comment by Dalas121** [comment] 2024-06-19 19:12
> it just means that people being unhappy with those types of changes is the default and expected rather than a situation that's unusual and by itself

Generally, my rule of thumb is that if I hear a few complaints (e.g. EI), I can take it or leave it - use my own judgement on the specific points.

If I hear a LOT of complaints (e.g. TDG, TSG), then that's a sign that we've done something seriously wrong, and regardless of my opinion revisions need to be made before any change goes mainline.

**Comment by Pentarctagon** [comment] 2024-06-19 20:02
Sure, you need to read and consider the feedback being given. But we also shouldn't avoid making changes just because it's going to make something be significantly different than it was before.

**Comment by Pentarctagon** [comment] 2024-06-19 20:54
Anyway, I think I'm distracting from the actual issue at this point so I'll stop commenting after this, but the point I've been doing very badly at trying to make is that it often feels like there are a lot of objections that essentially boil down to the fact that something was changed at all, which I really don't like. Wesnoth isn't a museum piece where the goal is to preserve existing content as it is - it's *supposed* to be actively developed and continue to have changes made to it.

**Comment by babaissarkar** [comment] 2024-06-24 15:28
@Dalas121 I think you'd need to design the various UI controls (button, textbox, menu button, dialog etc.) next, since these are the basic building blocks. Then you can probably specialize on particular dialogs.

**Closed** 2024-07-16 07:37 UTC
Labels: Enhancement, UI

**Comment by Wedge009** [comment] 2024-07-16 08:52
I thought I had missed something, until I noticed:

> To use the new theme, you'll need to switch to the `modern` theme using **Preferences -> Display -> UI Theme** and restart Wesnoth.

Is there something wrong with the new design such that it's not being used by default (yet)? I understand there may be further refinements forthcoming, but I also imagine that for the eventual 1.20 release any redesign would be opt-out rather than opt-in.

**Comment by babaissarkar** [comment] 2024-07-16 09:04
> Is there something wrong with the new design such that it's not being used by default (yet)?

Just wanted to discuss a couple of things with the dev team, give me a couple of days. Hopefully this will be default before the next release date.

**Comment by babaissarkar** [comment] 2024-07-17 03:56
@Wedge009 "Modern" is being made default/initial theme in #9104.

**Comment by CelticMinstrel** [comment] 2024-07-17 12:58
> and is exactly the same except for the drop caps in tips.

I assume what you mean is that the only change made to the classic title screen is adding the drop caps?

**Comment by babaissarkar** [comment] 2024-07-17 13:00
> > and is exactly the same except for the drop caps in tips.
> 
> I assume what you mean is that the only change made to the classic title screen is adding the drop caps?

Yes.
