### ISSUE TITLE
[1.16] The unit panel tooltip is not shown on names and descriptions

### ISSUE THREAD

**Issue by kabachuha** [wesnoth/wesnoth#6007] opened 2021-08-04 17:31 UTC
### Game and System Information
 - What version of the game are you running?
 - 1.15.15
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 - The official site/SourceForge
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - Not a custom build
 - What OS are you running?
 - Windows 10

### Describe the bug
A tooltip doesn't show up when mouse hovers over a long unit name on the right in-scenario panel. It makes long names impossible to read unless they show up in a dialog which doesn't bound to happen.

### To Reproduce

1. First, load a scenario.
2. Then, find or spawn a unit with a long name that doesn't fit the right panel.
3. Lastly, hover a mouse over the top entry that is the name in bold white characters.
4. Observe that there is no tooltip.

### Expected behavior
A full-name tooltip used to be shown in 1.14.

### Screenshots
The localized fort guard name is cropped by the right edge and a tooptip with the full information is not available although there is the cursor over it.

![no_tooltip](https://user-images.githubusercontent.com/14872007/128226481-102270a5-a615-4edc-a7ac-7412d2a6c487.png)

### Additional context
The fix will probably bear some regression as the behaviour was correct in 1.14.

**Comment by kabachuha** [comment] 2021-08-06 13:00
**UPDATE**
I played around with the issue and found out that it sometimes doesn't display a tooltip for unit description instead whereas the name tooltip is shown even for shorter names. I think this may indicate an id conflict somewhere or the config element selection failure for the first needed entry.

**Comment by kabachuha** [comment] 2021-08-06 20:25
My guess is that some logic chain is broken in [display::refresh_report](https://github.com/wesnoth/wesnoth/blob/4fed1670324a73c784250437ce6fcb88235fb3dc/src/display.cpp#L2806) function of report.cpp leading to dropout of tooltips from boundary config entries. The function itself seemingly deserves a rewrite, it even uses the much deprecated `goto` operator.

**Comment by CelticMinstrel** [comment] 2021-08-07 16:58
`goto` isn't deprecated, merely discouraged (because there's almost always a better way). In this case it's used like an enhanced `continue`, so it's not too terrible. Maybe there's still a better way tho, not sure.

**Comment by Wedge009** [comment] 2021-09-15 16:18
I just did a quick check between 1.14.17 and 1.15.17 (1.16 beta) and seems like a lot of tool-tips have been dropped:
* Unit name
* Unit type
* Side flag
* Side number
* Unit race

Don't know if this could possibly be intentional, however, as some the tool-tips for the race and name were rather unnecessary, except for the cases where the text is too big for the side-bar. Perhaps not intentional as the Unit type tool-tip provided the Help summary in 1.14.

**Comment by stevecotton** [comment] 2021-09-15 16:54
They're haven't been dropped, it's that this is an intermittent bug where sometimes they appear and sometimes they don't.

I've found that switching focus away from the window and them back to it (or maybe hiding the window and then showing it) can reset whatever has gone wrong.

**Comment by Wedge009** [comment] 2021-09-16 00:18
I wondered about that too. Is the 'intermittent display' something that happens in 1.14 as well? I can't remember if I've observed it there or not.

**Comment by stevecotton** [comment] 2021-09-16 01:33
I'm not sure - I noticed it on 1.15 because I was testing something that needed me to look at the tooltips a lot. The thing I was testing was the special notes handling, but that isn't going to be the root cause of this, as that was just a different way to generate the content for the tooltip.

**Comment by Wedge009** [comment] 2021-11-03 00:17
From #6096, looks like there may be a relation between the tool-tips working (or not) and window resolution.

**Comment by stevecotton** [comment] 2021-11-06 06:34
Mostly fixed in #6256 for 1.16 and #6261 for master; I've created a new issue, #6264, for the remaining part of the bug.

**Closed** 2021-11-06 06:34 UTC
Labels: Bug, Confirmed, UI, Regression, Medium Priority

**Comment by kabachuha** [comment] 2021-11-06 08:26
@stevecotton thaaanks!
