### ISSUE TITLE
Lua console + Alt Tab

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#2166] opened 2017-11-03 12:46 UTC
Wesnoth UI gets buggy if you open Lua console and use `Alt Tab`

Steps to reproduce:
* start wesnoth, open Lua console (enable :debug and press \`)
* switch to a different window and switch back ("Alt Tab")

You'll see this: 
![wesnoth-lua-alt-tab](https://user-images.githubusercontent.com/1547617/32374232-dd3250ac-c0ad-11e7-9d1c-115c60883756.png)

You can't really click anywhere. This is what you'll see if you use scroll up-down on the center:
![wesnoth-lua-alt-tab2](https://user-images.githubusercontent.com/1547617/32374260-eeac0bca-c0ad-11e7-8031-c4aa1b58f05f.png)
On the last screenshot, the Lua console list is the real foreground thing. This is why _it_ gets scrolled and redrawn.

**Comment by GregoryLundberg** [comment] 2017-11-03 13:33
duplicate of #2159

**Closed by GregoryLundberg** 2017-11-03 13:33 UTC

**Comment by vn971** [comment] 2017-11-03 13:46
@GregoryLundberg sorry, thx.
