### ISSUE TITLE
WC: Promote  to commander borken

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#7823] opened 2023-08-01 22:53 UTC
As reported today on discord, the cause seems to be that changing a units id like this 

https://github.com/wesnoth/wesnoth/blob/df9bbd5b25f04b5e48e665fe91c424ce02c5aaa0/data/campaigns/World_Conquest/resources/resources.cfg#L64

Gives an error.

Reported on 1.16.9 but probably also effects 1.17

**Comment by stevecotton** [comment] 2023-08-02 12:30
Seems a duplicate of #7264, which was fixed for master in #7284. Please check if this is reproducible on 1.17.

**Comment by stevecotton** [comment] 2023-08-07 07:12
@gfgtdf is this fixed by what you've merged? Was it already fixed beforehand?

**Comment by gfgtdf** [comment] 2023-08-07 13:09
> @gfgtdf is this fixed by what you've merged?

Yes 

> Was it already fixed beforehand?

No it was wrongly Backported (by me), this is 1.16 only.

**Closed** 2023-08-07 13:10 UTC
Labels: Bug, Campaign
