### ISSUE TITLE
preferences screen looks broken (Russian)

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2363] opened 2018-01-11 22:51 UTC
Steps to reproduce:
1. Set Russian locale:
```
export LC_ALL=ru_RU.UTF-8
```
2. Launch `wesnoth` v1.13.10+dev (7cdec04c-Clean)
3. Click "Настройки" (=Preferences)

You'll see the following picture:
![preferences_ru](https://user-images.githubusercontent.com/33452702/34851416-ef6ddade-f73a-11e7-93b9-f93e8b9460ef.png)

It seems broken on the right. Can we maybe increase Preferences window size a bit so that it won't break with a little longer texts and/or wider fonts?

**Comment by CelticMinstrel** [comment] 2018-01-12 04:10
This seems similar to the issues (possibly slider-related) in MP create.

**Comment by Wedge009** [comment] 2018-01-15 10:20
I'm pretty sure this is a duplicate of #1665 (and possibly others).

**Comment by vgaming** [comment] 2018-01-16 18:14
@Wedge009 seems so. Should I close in favor of the linked one? (Sorry for not searching existing issues beforehand..)

**Comment by Wedge009** [comment] 2018-01-17 06:20
No worries, it can be hard to read through old reports. Since you seem comfortable with the old report, I'll close this one.

**Closed by Wedge009** 2018-01-17 06:20 UTC
Labels: Bug, Duplicate
