### ISSUE TITLE
Movement animations jerky under fog (GNA #23020)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1432] opened 2017-05-08 09:21 UTC
**[Original submission](https://gna.org/bugs/index.php?23020)** by bob_the_mighty on 2014-12-03

I noticed the new cavalryman had a very jerky animation moving on a map with fog when accelerated speed is turned on. It's not just jerky, it seems to dart back and forth between each hex as it passes. Several other mounted units do it too, I think possibly all units with a movement anim (same thing happens with bats and drakes).

It occurs when accelerated speed is on any setting above normal.

(Reproduced on Windows 7)
Release: 1.12
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment] 2017-05-08 09:21
**Modified on 2014-12-05**

**coffee wrote:**

> Is this a large map? Some work was done to alleviate this type of problem before the 1.12.0 release, but with a lot of processing going on it can still happen.

**Comment by wesnoth-bugs** [comment] 2017-05-08 09:21
**Modified on 2014-12-05**

**bob_the_mighty wrote:**

> Well, after I noticed it I tested it again on the small 2p hamlets map and it was still happening.

**Comment by wesnoth-bugs** [comment] 2017-05-08 09:21
**Modified on 2014-12-05**

**coffee wrote:**

> Ok. Don't mind if I ask some more questions?
> 
> 
> 
> Does the motion look the same as for this previously fixed bug https://gna.org/bugs/?21883 (for Macintosh though)? The initial video and attachment file #20525 are the interesting ones here.
> 
> 
> 
> Also, what graphics card do you have, as well as does this happens with a lower resolution or if it happens less?

**Comment by Vultraz** [comment] 2017-06-27 10:36
Was this also fixed by the fix got #1565?

**Comment by Coffee--** [comment] 2017-06-28 22:14
Sadly I think this has in it yet a different bug that needs to be fixed, but may be partly related to #1565. In that other bug if you make the animation speed lower and the unit has a movement animation you will see that it isn't right. The fix for this may speed up the rendering and assist this with this bug at higher speeds, but from my testing won't be enough on it's own to truly fix this issue at high speeds.

I'm happy to assign myself this bug and look at it over the weekend as I've already done some preliminary tests some time back relating to this with an earlier dev version in the 1.13.x series. I believe it may be related to "cycling" in the animation drawing code for units where the unit may be rendered backwards in the wrong hex. Something similar happened for 1.11.x if I recall correctly and maybe it was never really fixed properly.

**Comment by Coffee--** [comment] 2017-07-01 07:26
After some more testing I think I'm close to finding a culprit for this.

In the units/drawer.cpp redraw_unit function I printed out the adjusted_params.offset, loc, and dst values whilst moving a single unit only up and down on the map. What I find different in 1.13.x is that the offset cycles back towards 0 without updating to the next loc and dst values regularly when acceleration is turned on. This does not happen in 1.12 from my testing.

Now the trick is to see if the problem is with not updating the loc/dst values or the hex movement offset.

**Comment by Vultraz** [comment] 2017-07-01 07:31
Hmm... I was going to ask if this was fixed on my accelerated rendering branch but if offsets are involved potentially not.

**Comment by Coffee--** [comment] 2017-07-01 09:41
I would like to test whether this commit 8562421434843a7c0e931b5f76c48e9ea9f72c00 introduced this problem. It is really hard though because of a boost error on build. I can compile later and earlier, but not around the time this problem first appeared.

**Comment by Coffee--** [comment] 2017-07-08 03:52
After some more testing I've found that this bug dates back some time (to at least the 1.12 series) and is more obvious when the game is set on accelerated mode and the computer is otherwise slowed down (say by running debug code). The changes to the new SDL and the above commit probably just make it more obvious.

The issue appears to me to be caused by the way movements are shown. Internally a "0~1:200" offset is given to movements by default (in animation.cpp) and if the internal timer in frame_private.hpp goes over a multiple of 200 it can pick up the next 0~1:200 offset from the same single hex movement. This causes the unit to jump around the hex.

I'll have a look if maintaining a separate timer that is limited to the current multiple of 200 for each hex-hex movement might fix this problem. Just thought I'd share my progress here so far.

**Comment by Vultraz** [comment] 2017-07-08 04:57
Given that movement seems very smooth on my accelerated_rendering branch (even more so with some local changes I have pending), including with fog, I think it might be worth abandoning this on master.

**Comment by Coffee--** [comment] 2017-07-09 03:14
Thanks for letting me know of your work Vultraz. IMO if it is smooth we should be looking to merge this into master as we can't really put out 1.14.0 in the state that it is with animations being so jumpy and unprofessional as they are now.

**Comment by CelticMinstrel** [comment] 2017-07-09 15:01
>  I think it might be worth abandoning this on master.

It's really not worth abandoning this on master until you've determined that the performance issues _cannot_ be resolved on master... which is something you haven't even investigated in the slightest.

If your fix for this on accelerated_rendering can be merged into master, it should be.

**Comment by jyrkive** [comment] 2017-08-05 14:03
Does commit ecb51029d75153eab311513e91c95246c59c9787 fix this?

**Comment by Wedge009** [comment] 2019-09-06 09:48
I don't think I was ever able to recreate this in the past, so I don't know what to compare with, but looking at 1.14.7 it seems fine to me. Tested Cavalryman moving through fog.

**Comment by jostephd** [comment] 2019-09-15 08:47
I've tested this in 1.10 and I see the problem there, the Cavalryman's sprite appeared instantaneously on the hex it had left, while moving SE in the test scenario with fog enabled and shroud disabled. That doesn't happen in master.

@jyrkive, I tried reverting your commit on top of master and that didn't reintroduce the bug.

**Closed by jostephd** 2019-09-15 08:47 UTC
Labels: Bug, Graphics
