### ISSUE TITLE
Terrain rendered on top of unit

### ISSUE THREAD

**Issue by GregoryLundberg** [wesnoth/wesnoth#3600] opened 2018-10-04 22:08 UTC
From https://forums.wesnoth.org/viewtopic.php?f=4&t=48903

The wooded terrain to the SE overlays the unit. Example from OP:
![alt text](https://forums.wesnoth.org/download/file.php?id=82001 "Terrain overlays unit")
Note how the green pine tree from the SE tile overlays the wolf's head.

**Comment by doofus-01** [comment] 2021-08-29 01:46
I think this is fixed, but someone else should confirm (1.16, not master)

**Comment by doofus-01** [comment] 2021-08-30 01:55
If this is duplicate of #1153, it is fixed in 1.16 (still needs to be ported to master)

**Closed by doofus-01** 2021-08-30 01:55 UTC
Labels: Bug, Graphics, Low Priority
