### ISSUE TITLE
UtBS - Segfault in The Morning After (in vicinity of recent abilities code)

### ISSUE THREAD

**Issue by gwhitney** [wesnoth/wesnoth#4862] opened 2020-04-20 16:17 UTC
### Game and System Information
 - What version of the game are you running?
git master
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
built from source
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
g++ 3a62c923f4-Clean
 - What OS are you running?
OpenSUSE Tumbleweed Linux

### Describe the bug

Wesnoth segfaults.

### To Reproduce

1. Load the attached savefile.
2. Hit "End Turn".
3. Voila, wesnoth segfaults.

### Expected behavior

Expected enemy to take its turn and game to continue.

### Screenshots

n/a

### Savefiles
If applicable, attach savefiles to help explain your problem. (To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.)

Attached.
[UtBS-The Morning After Turn 4c.gz](https://github.com/wesnoth/wesnoth/files/4504689/UtBS-The.Morning.After.Turn.4c.gz)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.

I ran under the debugger, and below is the full backtrace (and below that the uninformative console output). The problematic frame appears to be #1. At this point, the code is in a section in abilities.cpp inside an `if (other_)...` condition, and indeed other_ is non-null and points to the teacher Garak, but other_attack_ which is used to call `special_activate()`
is a null pointer. This is in code or closely in vicinity of code recently modified by commit https://github.com/wesnoth/wesnoth/commit/d9b4ae1ecadc04039430da90970c5c448e5ab944
If I can figure out a patch that seems correct I will post a pull request, but it occurs to me that the author of that commit, maybe @gfgtdf, might see the problem right off the bat.

Thanks for any help fixing this up, like the scenario would like to continue past turn 4 ;-)

```
(gdb) where
#0  0x0000555555e690a8 in attack_type::special_active(config const&, attack_type::AFFECTS, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=0x0, special=..., whom=attack_type::AFFECT_OTHER, tag_name="chance_to_hit", include_backstab=true, filter_self="filter_student") at src/units/abilities.cpp:1170
#1  0x0000555555e68d3f in attack_type::list_ability(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=0x7fffda7fb080, ability="chance_to_hit") at src/units/abilities.cpp:1115
#2  0x0000555555e68eb3 in attack_type::get_special_ability(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=0x7fffda7fb080, ability="chance_to_hit") at src/units/abilities.cpp:1128
#3  0x0000555555fdbaf0 in battle_context_unit_stats::battle_context_unit_stats(unit const&, map_location const&, int, bool, unit const&, map_location const&, std::shared_ptr<attack_type const>, unit_map const&) (this=0x55555e4f0f80, u=..., u_loc=..., u_attack_num=1, attacking=true, opp=..., opp_loc=..., opp_weapon=std::shared_ptr<const attack_type> (empty) = {...}, units=...) at src/actions/attack.cpp:179
#4  0x0000555555fddc7d in battle_context::battle_context(unit const&, map_location const&, int, unit const&, map_location const&, int, unit_map const&) (this=0x7fffffffb0d0, attacker=..., a_loc=..., a_wep_index=1, defender=..., d_loc=..., d_wep_index=-1, units=...) at src/actions/attack.cpp:385
#5  0x0000555555fded8e in battle_context::<lambda()>::operator()(void) const (__closure=0x7fffffffaf60) at src/actions/attack.cpp:597
#6  0x0000555555fdf16a in battle_context::choose_defender_weapon(unit const&, unit const&, unsigned int, unit_map const&, map_location const&, map_location const&, combatant const*) (attacker=..., defender=..., attacker_weapon=1, units=..., attacker_loc=..., defender_loc=..., prev_def=0x0) at src/actions/attack.cpp:620
#7  0x0000555555fdea46 in battle_context::choose_attacker_weapon(unit const&, unit const&, unit_map const&, map_location const&, map_location const&, double, combatant const*) (attacker=..., defender=..., units=..., attacker_loc=..., defender_loc=..., harm_weight=0, prev_def=0x0) at src/actions/attack.cpp:549
#8  0x0000555555fde20a in battle_context::battle_context(unit_map const&, map_location const&, map_location const&, int, int, double, combatant const*, unit const*, unit const*) (this=0x55555cb9ed10, units=..., attacker_loc=..., defender_loc=..., attacker_weapon=-1, defender_weapon=-1, aggression=1, prev_def=0x0, attacker_ptr=0x0, defender_ptr=0x0) at src/actions/attack.cpp:422
#9  0x000055555640e3a1 in ai::attack_analysis::analyze(gamemap const&, unit_map&, ai::readonly_context const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, double) (this=0x7fffffffb900, map=..., units=..., ai_obj=..., dstsrc=std::multimap with 61 elements = {...}, srcdst=std::multimap with 61 elements = {...}, enemy_dstsrc=std::multimap with 328 elements = {...}, aggression=1) at src/ai/default/attack.cpp:139
#10 0x0000555556409156 in ai::ai_default_rca::aspect_attacks_base::do_attack_analysis(map_location const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::array<map_location, 6ul> const&, bool*, std::vector<map_location, std::allocator<map_location> >&, std::vector<ai::attack_analysis, std::allocator<ai::attack_analysis> >&, ai::attack_analysis&, team const&) const (this=0x555557d2c010, loc=..., srcdst=std::multimap with 61 elements = {...}, dstsrc=std::multimap with 61 elements = {...}, fullmove_srcdst=std::multimap with 61 elements = {...}, fullmove_dstsrc=std::multimap with 61 elements = {...}, enemy_srcdst=std::multimap with 328 elements = {...}, enemy_dstsrc=std::multimap with 328 elements = {...}, tiles=..., used_locations=0x7fffffffb9ca, units=std::vector of length 3, capacity 4 = {...}, result=std::vector of length 28, capacity 32 = {...}, cur_analysis=..., current_team=...) at src/ai/default/aspect_attacks.cpp:330
#11 0x0000555556407c2a in ai::ai_default_rca::aspect_attacks_base::analyze_targets() const (this=0x555557d2c010) at src/ai/default/aspect_attacks.cpp:118
#12 0x000055555640729a in ai::ai_default_rca::aspect_attacks_base::recalculate() const (this=0x555557d2c010) at src/ai/default/aspect_attacks.cpp:69
#13 0x0000555556081a13 in ai::typesafe_aspect<std::vector<ai::attack_analysis, std::allocator<ai::attack_analysis> > >::get_ptr() const (this=0x555557d2c010) at src/ai/composite/aspect.hpp:172
#14 0x00005555560f7d2f in ai::composite_aspect<std::vector<ai::attack_analysis, std::allocator<ai::attack_analysis> > >::recalculate() const (this=0x55555d26cdf0) at src/ai/composite/aspect.hpp:319
#15 0x0000555556081a13 in ai::typesafe_aspect<std::vector<ai::attack_analysis, std::allocator<ai::attack_analysis> > >::get_ptr() const (this=0x55555d26cdf0) at src/ai/composite/aspect.hpp:172
#16 0x0000555556081900 in ai::typesafe_aspect<std::vector<ai::attack_analysis, std::allocator<ai::attack_analysis> > >::get() const (this=0x55555d26cdf0) at src/ai/composite/aspect.hpp:128
#17 0x00005555563eb9a8 in ai::readonly_context_impl::get_attacks() const (this=0x55555f177190) at src/ai/contexts.cpp:555
#18 0x00005555560117ca in ai::readonly_context_proxy::get_attacks() const (this=0x55555cbe5008) at src/ai/contexts.hpp:665
#19 0x0000555556417039 in ai::ai_default_rca::combat_phase::evaluate() (this=0x55555cbe4e10) at src/ai/default/ca.cpp:174
#20 0x000055555646dd33 in ai::ai_default_rca::candidate_action_evaluation_loop::do_play_stage() (this=0x555557e3ca70) at src/ai/default/stage_rca.cpp:112
#21 0x000055555602e899 in ai::stage::play_stage() (this=0x555557e3ca98) at src/ai/composite/stage.cpp:58
#22 0x000055555600faa2 in ai::ai_composite::play_turn() (this=0x555557d8d480) at src/ai/composite/ai.cpp:150
#23 0x000055555605f5f9 in ai::manager::play_turn(int) (this=0x7fffd9f82888, side=2) at src/ai/manager.cpp:748
#24 0x0000555556358b12 in playsingle_controller::play_ai_turn() (this=0x7fffffffc5b0) at src/playsingle_controller.cpp:560
#25 0x0000555556357b0c in playsingle_controller::play_side_impl() (this=0x7fffffffc5b0) at src/playsingle_controller.cpp:404
#26 0x000055555634ae2d in play_controller::play_side() (this=0x7fffffffc5b0) at src/play_controller.cpp:1181
#27 0x000055555634b191 in play_controller::play_turn() (this=0x7fffffffc5b0) at src/play_controller.cpp:1222
#28 0x000055555635609e in playsingle_controller::play_scenario_main_loop() (this=0x7fffffffc5b0) at src/playsingle_controller.cpp:174
#29 0x0000555556356967 in playsingle_controller::play_scenario(config const&) (this=0x7fffffffc5b0, level=...) at src/playsingle_controller.cpp:271
#30 0x00005555561f39a4 in campaign_controller::playsingle_scenario(end_level_data&) (this=0x7fffffffcc80, end_level=...) at src/game_initialization/playcampaign.cpp:197
#31 0x00005555561f3ecb in campaign_controller::play_game() (this=0x7fffffffcc80) at src/game_initialization/playcampaign.cpp:284
#32 0x0000555555af4e6c in game_launcher::launch_game(game_launcher::RELOAD_GAME_DATA) (this=0x5555574a2810, reload=game_launcher::RELOAD_DATA) at src/game_launcher.cpp:1025
#33 0x000055555597ae32 in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (args=std::vector of length 1, capacity 1 = {...}) at src/wesnoth.cpp:939
#34 0x000055555597b67a in main(int, char**) (argc=1, argv=0x7fffffffdd58) at src/wesnoth.cpp:1137
```

For what it is worth, the entire console output:
```
Battle for Wesnoth v1.15.3+dev (3a62c923f4-Clean)
Started on Mon Apr 20 08:58:03 2020

Automatically found a possible data directory at /home/USER/source/wesnoth

Data directory:               /home/USER/source/wesnoth
User configuration directory: /home/USER/.config/wesnoth
User data directory:          /home/USER/.local/share/wesnoth/1.15
Cache directory:              /home/USER/.cache/wesnoth

Setting mode to 2746x1957
Checking lua scripts... ok
Segmentation fault (core dumped)
```

**Comment by gfgtdf** [comment] 2020-04-20 20:31
> This is in code or closely in vicinity of code recently modified by commit d9b4ae1

its much more likely that this was broken in the also recent commit https://github.com/wesnoth/wesnoth/commit/6ff4a892e5692a36040f46795f3681f0aba44d3e, since the first one only adds the student_variable and renames some other variables.



Thx for the detailed report though we work on fixing this.

**Comment by newfrenchy83** [comment] 2020-04-20 22:32
@gwhitney have you play without https://github.com/wesnoth/wesnoth/commit/d9b4ae1ecadc04039430da90970c5c448e5ab944 for verify what it is the cause of bug?

**Comment by gwhitney** [comment] 2020-04-20 22:36
I think you are asking me to roll back to https://github.com/wesnoth/wesnoth/commit/2ea9433415da0df65af62023e0323c72ac20a57f (the commit before d9b4ae1) and see if the "End Turn" no longer segfaults? OK, I will try to go to that point in the code and recompile and run. Will report back when I manage to do that.

**Comment by newfrenchy83** [comment] 2020-04-20 22:42
alsa i confirm crash before https://github.com/wesnoth/wesnoth/commit/d9b4ae1ecadc04039430da90970c5c448e5ab944

**Comment by gwhitney** [comment] 2020-04-20 22:46
Right, I just experienced the crash at 2ea9433. Checking 0a007aa

**Comment by gwhitney** [comment] 2020-04-20 22:51
At 0a007aa, hitting End Turn showed an enemy turn and then made it to turn 5, no segfault. So that localizes it fairly well, I guess. Let me know if there's anything else you need me to do.

**Comment by newfrenchy83** [comment] 2020-04-20 23:38
@gwhitney retry https://github.com/wesnoth/wesnoth/commit/2ea9433415da0df65af62023e0323c72ac20a57f but with fix in https://github.com/wesnoth/wesnoth/pull/4864, please.

**Comment by gwhitney** [comment] 2020-04-21 00:05
OK, I compiled and ran from the head of newfrenchy83:patch-7 and I was able to see the enemy turn and make it to turn 5 without a segfault.

**Comment by newfrenchy83** [comment] 2020-04-21 09:12
@gwhitney try with https://github.com/wesnoth/wesnoth/pull/4863 instead, https://github.com/wesnoth/wesnoth/pull/4864 create another bug, and i prefer revert simplification of cpp code i abilities.cpp

**Comment by gwhitney** [comment] 2020-04-21 16:54
Yes, also if I check out the head of newfrenchy:patch-6, I can make it through the enemy turn and on to turn 5 without a segfault.

**Comment by Wedge009** [comment] 2021-09-15 12:10
What's the status here? Looks like a few PRs were made but never merged so I assume the issue is still present...

**Comment by stevecotton** [comment] 2021-09-15 12:24
There were other PRs by @newfrenchy83, which I guess fixed this. I've tested and neither 1.15.17+dev nor master crash.

**Closed by stevecotton** 2021-09-15 12:24 UTC
Labels: Bug, High Priority, Engine

**Comment by Wedge009** [comment] 2021-09-15 12:35
Great, thanks!
