### ISSUE TITLE
[1.16] [BUG] Loading save file of MP campaign caused save file corruption

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7739] opened 2023-06-28 06:52 UTC
### Game and System Information

- **Version:** 1.16.9
- **Downloaded from:** Sourceforge
- **Build info:** DMG Client Download
- **OS:** MacOS v12.6.5 Macbook Pro 2015

### Description of the bug

I load save file to resume my playthrough but on loading I receive a weird message and the save files no longer work.

### Steps to reproduce the behavior

1. Download my Save file (attached)
2. Load the save file (from MP Lobby Load Game, NOT main menu load game)
3. See the weird message

### Expected behavior

I can play and resume my playthrough

### Additional context

Addon:
1. UWS/Ultimate Wesnoth Survival (latest version)
[uwsc-UWS Campaign Turn 29.gz](https://github.com/wesnoth/wesnoth/files/11891087/uwsc-UWS.Campaign.Turn.29.gz)
2. War of Legends (I always play with my era)
3. Unit Marker (I like to mark my favourite units)
4. Faction Flags (cause I like aesthetics)

As you can see this message doesn't even tell what's wrong. Just said untested for and "please report" so here I am
<img width="613" alt="Screenshot 2023-06-28 at 12 40 03 PM" src="https://github.com/wesnoth/wesnoth/assets/5283677/e6750280-7669-443b-b381-400ed2ab48d2">

**Comment by knyghtmare** [comment] 2023-06-28 06:58
FYI, loading from main menu causes it load, but I lose all of my units

**Comment by ProditorMagnus** [comment] 2023-06-28 07:36
era_id="war_of_legends"
active_mods="plan_unit_advance,knyght_wol_faction_flags,unitmarker"

There are more addons involved.

**Comment by Toranks** [comment] 2023-06-28 09:13
Different error,  maybe it is more specific to find the cause:
![imagen](https://github.com/wesnoth/wesnoth/assets/40789364/72c48734-8ca5-4447-bff4-eca4c3f73e47)

**Comment by Pentarctagon** [comment] 2023-06-28 18:41
@gfgtdf this sort of error is what the optional_child/mandatory_child change addressed, right?

**Comment by gfgtdf** [comment] 2023-07-01 23:44
> @gfgtdf this sort of error is what the optional_child/mandatory_child change addressed, right?

Well, in theory the "new" method of using optional_child can still throw an error just as bad (mandatory_child throws a more descriptive error though), but i looked though all cases when doing the conversion so that that commit should have fixed this issue if it was present at that time.

**Comment by Wedge009** [comment] 2024-03-22 22:11
> 1.17 removed this error.

Closing with release of 1.18.0.

**Closed by Wedge009** 2024-03-22 22:11 UTC
Labels: Bug, MP, Stable 1.16
