### ISSUE TITLE
Lua console output text is not visible

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#7655] opened 2023-05-23 15:28 UTC
### Game and System Information

- **Version:** 1.17.17
- **Downloaded from:** itch
- **OS:** windows 10

### Description of the bug

When trying to scroll down Lua console, everything except first few ticks of scrollbar is empty. When new output should become visible, scroll position is reset to top.

Real output can be observed with copy button.

https://i.vgy.me/HCdnJ6.png initial view
https://i.vgy.me/NJx3VJ.png furthest down it is possible to scroll without losing all text
https://i.vgy.me/dwPfQG.png more scrolled down

### Steps to reproduce the behavior

1. enable debug
2. open lua console
3. enter something that should generate text response, for example wesnoth

### Expected behavior

Output of Lua statement is visible on screen, without having to scroll down or use copy button.

### Additional context

Noticed during testing of #7653

**Comment by knyghtmare** [comment] 2023-05-23 15:33
Same as #7565

**Comment by Toranks** [comment] 2023-05-23 17:13
Same causes as #7093 and #6879

**Comment by CelticMinstrel** [comment] 2023-05-23 17:52
> redundant

No, they're not in the least bit redundant. Redundant means that something else provides all of the same functionality, which is definitely not the case.

**Comment by Wedge009** [comment] 2023-05-23 21:58
I would say it's the same as those other linked issues. Can we consolidate these reports instead of having them replicated everywhere? This is now at least four reports for the seemingly same issue albeit with different symptom details.

**Comment by ProditorMagnus** [comment] 2023-05-23 22:09
There could be index issue referencing all of them as list what to test after solution.

**Comment by Pentarctagon** [comment] 2023-11-18 04:32
Is this a separate issue or a duplicate of #7093?

**Comment by CelticMinstrel** [comment] 2023-11-18 22:12
It's likely that they have the same root cause. This is describing the Lua console however, while that one is describing the gamestate inspector.

**Comment by gfgtdf** [comment] 2023-12-17 22:28
I just tested and it doesn't happen for me the only thing that happens for me is the text disappearing with `error SDL: When creating texture from surface: Texture dimensions are limited to 16384x16384` when the text gets too long (independent on scrolling position)

**Comment by ProditorMagnus** [comment] 2023-12-17 23:50
I confirm that with sourceforge release of 1.17.23 this does not happen.

Play page links to sourceforge, main page links to itch.

**Closed** 2023-12-18 23:15 UTC
Labels: Bug, Confirmed, Blocker: New Stable, UI, Regression

**Comment by CelticMinstrel** [comment] 2023-12-19 00:03
Didn't @gfgtdf just say it _does_ happen? Or is there a separate bug tracking that?

**Comment by mesilliac** [comment] 2023-12-19 05:14
That was the same as the credit screen issue no? It was worked around for credits, but the base problem remains for long text in scroll boxes in general.

IIRC there were two cases, one where the text generated but the resulting texture was too big, and one where the text refused to generate because the resulting texture would be too big.

**Comment by CelticMinstrel** [comment] 2023-12-19 05:21
Yes, the issues in the Lua console, the gamestate inspector, and the credits were all basically the same thing as far as I know.

**Comment by mesilliac** [comment] 2023-12-19 05:44
I mean it probably never got a separate issue because of that. Now that the credit screen issue has been closed it probably needs a new one opened for the problem in general, unless there was one opened i'm not aware of.

Funnily enough, while searching for that, i found #3265 and the fix #5682 ... not sure why it never came up that this problem existed, and was fixed, previously.

**Comment by CelticMinstrel** [comment] 2023-12-19 06:17
Did it never come up? I thought it came up a couple times… I think I remember mentioning it myself…

**Comment by mesilliac** [comment] 2023-12-19 06:41
Not anywhere i was copied in on. It could have been mentioned on IRC? Moot anyway as that fix isn't appropriate now. I didn't find an open issue for it so i think it needs a new one.

**Comment by gfgtdf** [comment] 2023-12-19 17:40
> Didn't @gfgtdf just say it does happen? Or is there a separate issue tracking what he described?

This issue seems to be about even shorter texts not being rendered as soon as the user scrolls (but still being visible when the dialog initially shows up). The issue i mentioned is about the text not showing at all if its too big. I thought there was an open issue for it because its clearly not the first time it happend but maybe not.

**Comment by CelticMinstrel** [comment] 2023-12-19 19:00
If there is one, it's likely it explicitly mentions either the Lua console or the gamestate inspector. If not, it's likely that the assumption was for the now-closed credits one to cover it, but the credits fix was a workaround specifically for the credits so in that case we'll need a new issue.

**Comment by ProditorMagnus** [comment] 2023-12-19 19:32
Steps reproduce issue with 1.17.17. Steps do not reproduce issue with 1.17.23. Therefore this issue is solved.

If you have other issues even if with console then register as new task.
