### ISSUE TITLE
Unable to load a savefile wesnoth just made

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2375] opened 2018-01-16 17:27 UTC
Steps to reproduce:

* open the save file at the end of the issue.

Alternative outdated old steps:
<strike>1. start wesnoth v1.13.10+dev (bbdb5ad8-Clean)  (though it reproduces even on 1.12)
2. download "Creep Wars Dev" add-on version 0.11.2 (latest)
3. start a local (offline) game with scenario "Creep Wars narrow 0.11.2"
4. when the game starts (on turn 1), save it.
5. try to open the produced save file</strike>
**UPD:** does not work anymore because I've fixed a relevant bug in the add-on code. There are still some issues left that might need solving, see discussion below.

I get this in console when I try to load the file:
```
20180116 19:58:59 error general: The file you have tried to load is corrupt: '
```
(that's all, nothing down below)

Additional note that may be useful: when I select the file in "load game" dialog, wesnoth already says "(Invalid)".

Save file (it can be opened even if you don't have the add-on installed):
[Creep_Wars_narrow_0.11.2-3_Turn_1.gz](https://github.com/wesnoth/wesnoth/files/1636144/Creep_Wars_narrow_0.11.2-3_Turn_1.gz)

**Comment by GregoryLundberg** [comment] 2018-01-16 20:50
I'm marking as a bug and confirmed because I can reproduce using your save file.

The bug is that the game is throwing game::error with no indication of the failure type or location. This could be as intended, and not a bug.

The actual error is "Invalid tag" in your save file. I've not yet determined where. You should be able to see this message by re-testing, enabling --log-info engine

```
Checking lua scripts... ok
20180116 14:49:35 info engine: Invalid tag name
at <unknown>:367820180116 14:49:35 error general: The file you have tried to load is corrupt
```

**Comment by GregoryLundberg** [comment] 2018-01-16 21:35
Specifically, the invalid tag is `[_]`, for example, in the following block for the second [side]:

```
			[modifications]
				[object]
					duration="turn"
					[effect]
						apply_to="new_ability"
						[abilities]
							[_]
								description="+2 movement"
								name="first turn advantage"
							[/_]
						[/abilities]
					[/effect]
				[/object]
				[object]
					[effect]
						apply_to="movement"
						increase=2
					[/effect]
				[/object]
			[/modifications]
			[abilities]
				[_]
					description="+2 movement"
					name="first turn advantage"
				[/_]
			[/abilities]
```

**Comment by vgaming** [comment] 2018-01-16 21:38
@GregoryLundberg thanks a lot! I didn't know about the `--log-info engine` key.

The problem being solved now locally, can we make any conclusions globally? For example, should wesnoth ignore an ability that it won't be able to save/load in the first place? So that you'd get an error at object/effect/abilities creation time?

**Comment by vgaming** [comment] 2018-01-16 21:39
UPD: wording

**Comment by GregoryLundberg** [comment] 2018-01-16 21:45
`s/[_]/[tad]/` `s\[/_]\[/tad]\` six occurrences each and your load-game screen looks good, the game loads and runs. dunno if it does what you want but it's up.

**Comment by GregoryLundberg** [comment] 2018-01-16 21:47
As I said, I marked it as an error because it just threw an exception with no clue where it was or what was wrong; the caught that exception and threw another which it caught, displayed, and ignored.

I leave it to the UI people if this is actually a bug or if they're intentionally obfuscating errors.

**Comment by GregoryLundberg** [comment] 2018-01-16 21:52
It occurs to me, as well, that to a Lua programmer (among many other dialects) `_` is a perfectly good `name` and it's surprising that it won't work for a `tag name` so maybe that's a bug, too.

**Comment by vgaming** [comment] 2018-01-16 21:59
@GregoryLundberg while your points are correct, I was trying to address a specific issue in the last comment: why should wesnoth accept an [object] that it cannot save and load?

Error reporting, and maybe the `_` tag name could be issues, too, I agree.

**Comment by GregoryLundberg** [comment] 2018-01-16 22:02
OK. I see. I'd say, no, it's a bug to write a save file you cannot read.

Or, in this case, to refuse to accept a tag from a save file that you could (1) create with [insert_tag] or (2) load from a campaign, scenario or addon. To my mind, that's another way of stating the `_` is not a valid `tag name` issue.

**Comment by Pentarctagon** [comment] 2018-01-17 07:53
FWIW, it doesn't look like the UMC developer is the one adding the `[_]` tag.  The code that adds the ability in question, from `maps/first_turn_advantage.lua` in Creep Wars:
```
local wesnoth = wesnoth
local creepwars = creepwars
local assert = assert
local ipairs = ipairs
local print = print
local T = wesnoth.require("lua/helper.lua").set_wml_tag_metatable {}


local function first_turn_advantage_register(side, value)
	assert(wesnoth.current.turn == 1)
	for _, unit in ipairs(wesnoth.get_units { side = side }) do
		local ability = T.dummy { name = "first turn advantage", description = "+2 movement" }
		wesnoth.add_modification(unit, "object", {
			T.effect { apply_to = "new_ability", T.abilities { ability } },
			duration = "turn",
		})
		wesnoth.add_modification(unit, "object", {
			T.effect { apply_to = "movement", increase = value },
		})
	end

	wesnoth.wml_actions.event {
		name = "side " .. side .. " turn 1",
		T.lua { code = "creepwars.first_turn_advantage_fix_moves()" }
	}
	wesnoth.wml_actions.event {
		name = "side " .. side .. " turn 1 end",
		T.lua { code = "creepwars.first_turn_advantage_remove_object()" }
	}
end
```

Given that `[_]` is certainly not a valid subtag of `[abilities]`, this seems like it might be a bug with `wesnoth.add_modification()`?

**Comment by vgaming** [comment] 2018-01-17 08:35
@Pentarctagon sorry, I've just published an update as soon we understood and confirmed the error. Where you now see `T.dummy`, I had `T._` before. Published in version 0.11.3. Sorry for the confusion.

**Comment by vgaming** [comment] 2018-01-17 08:36
Sorry because I should've update the issue description or say something here. Will do now.

**Closed** 2018-01-17 21:52 UTC
Labels: Bug, Confirmed

**Comment by vgaming** [comment] 2018-01-17 21:57
@jyrkive do you think it would make sense to disallow the tag from existing in the first place? Like, when first time somebody tries to add this tag anywhere, wesnoth raises an error?

**Comment by GregoryLundberg** [comment] 2018-01-17 22:12
Fail early and fail loudly

**Comment by CelticMinstrel** [comment] 2018-01-18 03:20
Huh, I actually thought `[_]` _was_ a valid tag name.

**Comment by jyrkive** [comment] 2018-01-18 07:59
@vgaming That's exactly what commit 52e3772 does. Giving WML that contains invalid tags to any function such as `wesnoth.add_modification()` is now a hard error.

See also the new unit tests in commit 1386e3945c4c8ddc4c74e87e586f93f642b9b2a6. (`pcall()` returns true if the code runs successfully, and false if it generates an error.)

**Comment by vgaming** [comment] 2018-01-18 11:21
@jyrkive I indeed missed the second commit. I see now. Thanks for explaining and for the fix itself!

**Comment by CelticMinstrel** [comment] 2018-01-19 05:30
...this is slightly off-topic, but I just noticed that there are two slightly different functions in `config` to check if a tag name is valid - `valid_id` and the one Jyrki used. The former doesn't test for beginning with an underscore.

I'm pretty sure tags or attributes beginning with an underscore are used internally, for example in the diff format. Might be only attributes though, not tags...

**Comment by jyrkive** [comment] 2018-01-19 09:31
@CelticMinstrel Oh, whoops. I didn't notice that `config::valid_id()` existed. I added the duplicate function.

I'll remove my duplicate and fix `valid_id()` to check for beginning underscores as well.

**Comment by CelticMinstrel** [comment] 2018-01-19 13:58
As long as that doesn't break valid WML that uses attributes such as `__remove` (an example of where this is allowed is in `[set_variables]mode=merge`).

Reference: https://wiki.wesnoth.org/InternalActionsWML#.5Bset_variables.5D

(Another underscore attribute used internally is `__diff_track` according to config.cpp; I didn't take the time to check where it's used though.)

**Comment by jyrkive** [comment] 2018-01-19 14:01
Oh. In that case my duplicate function actually needs to stay.

**Comment by soliton-** [comment] 2018-01-19 15:14
Not that I've checked but I'd guess underscores are allowed just not if they make up the complete name.

**Comment by sapientN3T** [comment] 2018-05-11 20:01
I’m a bit late to the party, but I think this should have been treated as a bug in the parser. It was never intended to be illegal for an attribute or tag to start with underscore. And the parser should have enough contextual clues to be aware that it is reading a tag name or an attribute name, places where translation marks are not usable.

**Comment by CelticMinstrel** [comment] 2018-05-12 03:25
I would definitely support restoring the ability for tag names to begin with an underscore (and revert the ability for them to contain dollar signs).

**Comment by vgaming** [comment] 2018-05-12 09:56
Plz be careful with documentation, some add-on writers may depend or start depending on the documented behaviour. (For example, I already depend on the format partly, though the exact proposal of allowing first `_` and disallowing `$` won't affect me.)

**Comment by CelticMinstrel** [comment] 2018-05-12 15:53
We're not going to document the allowing of dollar signs, because it was only an unintended side-effect of a bugfix. If people start depending on undocumented behaviour it's their own fault if things break when we change that behaviour.

**Comment by jyrkive** [comment] 2018-05-14 06:29
Note that we can't allow leading underscores in the 1.14 branch at this point, it would be an API change. Such a change can only be made in 1.15 at the earliest.
