### ISSUE TITLE
Horizontal scroll direction is reversed

### ISSUE THREAD

**Issue by dhardy** [wesnoth/wesnoth#2218] opened 2017-11-19 00:07 UTC
Before the last system update, touchpad scrolling of the map worked perfectly. After the update (Wesnoth 1.13.10), horizontal scrolling works in the wrong direction (vertical scrolling is still correct). It's weird having only one axis reversed. I don't see any config for this.

**Comment by sevu** [comment] 2017-11-19 00:56
I recall this happening to me too.

**Comment by Vultraz** [comment] 2017-11-19 23:43
When I swipe left, the map goes to the right. Is that not the previous behavior?

**Comment by dhardy** [comment] 2017-11-20 08:17
It's not the previous behaviour I had. Now the map moves down when I swipe down (same direction) but left when I swipe right. It's pretty odd. (I never did get why we needed to reverse touchpad scrolling directions just because touchscreens work differently; one is a "scrolling" method the other is "drag a point".)

**Comment by Vultraz** [comment] 2017-11-20 08:21
That’s a good analogy, I guess. Now we just neee to decide which scrolling method to commit to.

**Comment by dhardy** [comment] 2017-11-20 08:25
Well, either stick to the old standard (and tweak your touchpad if you want different in all your apps) or add an option. Because all my other apps scroll in the same direction as I swipe.

**Comment by AI0867** [comment] 2017-11-22 10:20
Apple decided to make touchpads on macOS work the same as touchscreens on iOS at some point, and microsoft followed suit in windows 8 (even with scrollwheels I believe). Some linux software also does this, KDE (at least the versions I've run) does not.

It's all rather annoying.

**Comment by dhardy** [comment] 2017-11-22 11:55
I know, I just assumed the only sane way to implement the switch would be by swapping touchpad scroll output. (Although even that is not sane — queue *scroll down to zoom in* on maps interpreting wheel events the usual way.) Ugh, what a can of worms.

**Comment by vgaming** [comment] 2017-11-23 21:08
// Linux XFCE environment defines scrolling as "scroll down = text goes down", but there is an option to reverse scrolling behavior, called "Reverse scroll direction". This option is the approach that seems sane. It's not app-level, it's system-level.

I would be very happy if wesnoth would behave same as all others programs on my OS/environment. So that I could also reverse the behavior on all apps simultaneously by a single click (if I'd want to).

**Comment by GregoryLundberg** [comment] 2017-11-23 21:44
I don't know if it's such a good idea querying the DM for options unless it's explicitly an option supported by all DMs on Windows, macOS and every flavor of Linux out there.

**Comment by vgaming** [comment] 2017-11-23 22:01
@GregoryLundberg agree. So, I'd make it OS-specific. It seems that Windows has a single dominating DE/whatever, same goes for Mac. Linux has all kinds of DE-s, but the majority of them uses traditional scrolling, not "touch-style".

**Comment by dhardy** [comment] 2017-11-24 07:30
You would have thought there'd be a [freedesktop standard](https://www.freedesktop.org/wiki/Specifications/) for this kind of thing, but I can't find one.

**Comment by dhardy** [comment] 2017-11-24 07:32
Actually, [there's a section in the X protocol](https://www.x.org/releases/X11R7.7/doc/inputproto/XI2proto.txt) (search "scrolling"). Presumably there's some equivalent [for Wayland](https://wayland.freedesktop.org/) too, but can't find it.

**Comment by jyrkive** [comment] 2017-11-26 20:45
Looks like this was caused by commit cfa2df194ec148ab521407dbba6df1dff193f528.

**Comment by vgaming** [comment] 2017-11-27 11:39
@dhardy well, the point is to _ignore_ the setting, even if it can be found on Xorg configuration files etc. We want wesnoth to behave _like all other apps_, we don't want hardcode that "scorll down" = "map goes down".
So, if we just use the standard Linux scroll direction, we will always scroll in the same direction as the user would inside e.g. a browser. Even if the user inverts his Xorg configuration. (Basically inverting what "scoll up" means, on his system.)

**Comment by Vultraz** [comment] 2017-11-27 15:22
What is this "standard Linux scroll direction" you speak of?

**Comment by GregoryLundberg** [comment] 2017-11-27 15:39
I read it as "what my system does" and "the same as Windows" since I don't see any difference.

When I roll the mouse wheel to scroll down a web page the line I'm reading moves up my screen.

When I roll the mouse wheel the same direction on Wesnoth, the unit moves up my screen.

My touch system is restricted to mouse emulation since I'm using Windows Remote Desktop.

Connected to my Linux system, when I touch the bottom of the window and move down a bit, the unit on my screen moves up. Same as when I move the mouse a bit off the bottom edge.

My Windows 7, 8.1 and 10 systems don't seem to understand touch. Maybe something with my setup but I don't care to look right now.

I would expect, if I an click-dragging the map, or touch-dragging, that the map follows the mouse pointer or my finger.

When it comes to the arrow keys, however, I would expect the system scroll to be honored. That is, if I have it set to move the line on my web page down when I press the down arrow, I would expect the unit on my screen to move down. Similarly, if I have it set (as "normal") to move the line on my web page up when I press the down arrow, I would expect the unit on my screen to move up as well.

**Comment by vgaming** [comment] 2017-11-27 15:42
@Vultraz yes, I mean the "scoll down = text goes up" thing.

**Comment by vgaming** [comment] 2017-11-27 16:02
BTW, note on Xorg settings. I did some tests now.

It seems that, when you enable this setting, applications actually receive an inverted scroll action itself. So if you scroll down your mouse wheel, applications get "scoll up" event. If you scroll up your wheel, applications get "scoll down" event. Also, this is input-specific. So you can invert your mouse, but leave touchpad as is, for example. Etc.

Note on tests:
* I was lazy to properly hack into Xorg settings, so I used my XFCE settings to "invert scroll direction".
* I observed the events using `xev` command.

**Comment by dhardy** [comment] 2017-11-27 17:31
FYI Windows 8 and recent versions of GNOME both switch scrolling direction (scroll UP to make text go up). Not 100% sure how this happens but I would guess by remapping events (both Xorg conf and `xinput` allow "mouse button" scroll events to be remapped). IIUC older versions of Windows didn't have uniform support for side-scrolling so that may be why the patch @jyrkive mentioned switched only the `x` direction? Seems a special case though; I imagine most platforms will not want this.

I strongly suspect that regardless of which behaviour you want (objects on map follow fingers when scrolling or move away), on most platforms [with horiz and vert scrolling] the current code will be wrong (inconsistent between x and y directions). But maybe more testers are needed...

**Comment by sevu** [comment] 2018-01-29 02:41
The game is unplayable with a touchpad, I mark this as a blocker.
Some information:
- I use libinput as touchpad driver. Not evdev or synaptic.
- Scrolling up scolls up.
- Scrolling left scrolls right.

Does anybody on Linux _not_ have a different behavior for horizontal and vertical with the touchpad?

**Comment by ancestral** [comment] 2018-02-06 14:27
The game is honoring the scrolling setting in System Preferences. If you have the check box “content tracks finger movement” the game follows that. How do you scroll a page in Safari? It’s the same behavior.

If we undo this, then this breaks for people who have the natural scrolling turned off, which will be even more frustrating for the other half of people who turned the setting off.

So the only fix for this is overriding this preference… which I think we can do. I’ll see if I can find make a patch to check the systemwide scroll setting.

**Comment by ancestral** [comment] 2018-02-06 14:37
BTW, I’m pretty sure the change in the behavior happened with a move to SDL2.

**Comment by soliton-** [comment] 2018-02-07 21:22
Perhaps it would be easiest to just add settings to invert scrolling directions. Options are bad but this is going to be simpler than figuring out what the right thing to do is for each OS/device (and then still have people that don't like the default and want to change it just for wesnoth).

**Comment by ancestral** [comment] 2018-02-08 04:38
`defaults read -g com.apple.swipescrolldirection` is the command for macOS that reads whether natural scrolling is on or not. If it returns `0` it’s off, which means drag down scrolls down, drag left scrolls left, etc. If it returns `1`, it’s on, which means it’s the reverse.

**Comment by vgaming** [comment] 2018-02-08 09:22
@ancestral I think the current issue is about Linux mostly. Not sure though. But at least on Linux, the current behavior is definitely broken. We should 100% stick to the old behavior _on Linux_.

**Comment by ancestral** [comment] 2018-02-08 20:45
So just to clarify:

* The patch several years ago I made was in an `#ifdef` for Mac. I didn’t change anything outside that. I did not break anything for other platforms. Likely, SDL started honoring system-level scrolling options. (But I don’t know for sure.)
* If all Linux users are reporting this is reversed, then either an `#ifdef` for Linux is a good idea, or change the default and then I can *reverse* the Mac `#ifdef` setting.
* I would argue that people probably expect the game to work where swipe to left is left and swipe to right is right (at least on the game map). I think it is unintuitive to expect the opposite on the game map regardless of the system setting.

**Comment by GregoryLundberg** [comment] 2018-02-08 21:29
Your third point is why I gave up on panning and disabled it, long ago.

Panning at the edge may be the way it is and y'all can say it is therefore it shall always be; but, to me, it's stupid and I'm very glad I can turn it off. The game is far more enjoyable when your cat walking across the desk, jiggling the mouse, doesn't cause your map to go zooming off this way or that.

**Comment by vgaming** [comment] 2018-02-08 21:47
@ancestral didn't totally get the "edge" part. For me, it's as simple as "just do what a browser does". Scrolling is not something you think about, your hands do that themselves. Since it's automatic, all apps within an OS/device should behave identically.

**Comment by ancestral** [comment] 2018-02-08 23:16
@vgaming So when you move your cursor to the edge of the map, you expect the game should move in that direction. This doesn’t apply to web browsers. You don’t scroll by moving the cursor to the edge of the window.

**Comment by vgaming** [comment] 2018-02-08 23:36
@ancestral this part I do understand. What I cannot understand, is how it relates to scroll events. These are different types of movement on my touchpad, the cursor doesn't even change position while scrolling, it stays in the center.

**Comment by ancestral** [comment] 2018-02-09 01:43
My question is, for Linux users, is there actually a system setting for scrolling direction?

**Comment by vgaming** [comment] 2018-02-09 09:39
@ancestral yes. But the trick is -- it doesn't really change scrolling direction for e.g. "scroll down" event. Instead, it makes your physical mouse scrolling generate inverted scroll event.

In other words, if you re-configure this setting, you will make the same physical gesture, but get an inverted scrolling event. Apps do not know about it (normally).

**Comment by ancestral** [comment] 2018-02-09 20:47
My apologies. After looking at [cfa2df](https://github.com/wesnoth/wesnoth/commit/cfa2df194ec148ab521407dbba6df1dff193f528)… maybe I was wrong. I could have sworn it was in an `#ifdef`. My mistake, I was thinking of another report.

So Linux *is* different?

https://github.com/wesnoth/wesnoth/issues/1754

**Comment by vgaming** [comment] 2018-02-09 21:19
@ancestral I don't know if Linux is different because I do use any other OS. On Linux, when you scoll up, viewport goes up. That is expected behavior. Now, when you scoll left, viewport goes _right_. This is broken.

**Comment by ancestral** [comment] 2018-02-09 21:20
Okay, so is it easier to `#ifdef` for Linux, or `#ifdef` for Mac and Windows?

**Comment by jyrkive** [comment] 2018-02-10 05:40
IIRC, last time I tested this on Windows, panning direction was correct (meaning that the X axis reversal is Linux specific).

**Comment by sevu** [comment] 2018-02-10 10:23
Wesnoth also runs on a variety of other unix systems.

**Comment by vgaming** [comment] 2018-02-10 11:11
If there are 2 systems that are known to behave in one way, and an unknown number of other systems that probably behave differently, I'd chose `ifdef`-ing the two known systems.

**Comment by ancestral** [comment] 2018-02-11 04:28
I had one person with a Linux machine confirm this works. That being said, if you notice the issue persists, please re-open the issue. Thanks.

**Closed by ancestral** 2018-02-11 04:28 UTC
Labels: Blocker, Bug, Confirmed, Regression, UI

**Comment by vgaming** [comment] 2018-02-11 10:41
@ancestral confirming that fix works. Thanks!
