### ISSUE TITLE
Load game UI: window too narrow for Japanese filenames

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7290] opened 2023-01-19 13:38 UTC
### Game and System Information

- **Version:** 1.16.7 (exactly the tagged version)
- **Downloaded from:** built from source
- **Build info:** GCC 12, Boost 1.81
- **OS:** Linux with X11 (Debian Unstable)

### Description of the bug

With an 1920x1080 window on an HDPI screen (that triggers the bigger fonts), the load game dialog is so narrow that it requires a horizontal scrollbar, even though there's enough space for it to be wider. The problem persists at higher resolutions, with the unused space growing rather than becoming part of the dialog.

![image](https://user-images.githubusercontent.com/101462/213456348-81c8bd57-919e-4965-906a-8600cf11c624.png)

### Steps to reproduce the behavior

1. Start Wesnoth
2. Change window size if needed
3. Click the title screen's Load button

### Expected behavior

Show the full dialog without a horizontal scrollbar.

### Additional context

This is separate to 1.17's #7087 - the UI around this dialog has been changed between the stable and dev branches.

**Comment by stevecotton** [comment] 2023-01-19 14:06
Alternatively, there's enough unused space in the filename area for the contents to be narrower.

**Comment by Wedge009** [comment] 2023-01-19 17:10
Presumably not an issue on master?

**Comment by stevecotton** [comment] 2023-01-19 17:17
Looking again on master, it's an issue there too, the cancel button is cut in half both with big and small fonts. I just noticed #7087's problems and didn't notice the cancel button.

**Comment by Wedge009** [comment] 2023-01-20 08:42
Is the title really meant to say 1920x1800?

I can't remember what's the threshold for triggering high DPI rendering, but clearly my displays don't meet the requirement as I can't replicate it, either this or #7087.

**Comment by stevecotton** [comment] 2023-01-20 11:18
Corrected the title, thanks.

I'm wondering what's going on here, because I'm sure we wouldn't have released 1.16.0 looking as it does on my display. Knowing that it doesn't do this for you is useful to narrow it down. The obvious commit to cause this would be acd08fd0c51f9f5e71ac8d0c5d1679d1c8a4876e, however that was already in 1.15.4.

I've just realised that it looks worse for me with low DPI fonts at 1920x1080 - that makes the dialog much narrower. 
![image](https://user-images.githubusercontent.com/101462/213682887-caacace2-3a06-4987-8c45-28ea786c3ac4.png)

**Comment by stevecotton** [comment] 2023-01-20 11:54
Ah, the filename section gets its width from the widest filename, but the filename appears to truncate based on character count (just a guess from the UI's behavior, haven't searched for the code that does it) :

![image](https://user-images.githubusercontent.com/101462/213689231-40a1736f-2010-4250-8acd-cc7e9d48baac.png)

**Comment by stevecotton** [comment] 2023-01-20 12:37
Two sets of steps, depending on the resolution the longer set is more reliable than the short set, because the long set makes the date/time column wider too.

Steps to reproduce:
1. Change the language to Japanese (Nihongo)
2. Start the tutorial, thus creating an autosave
3. Return to the main menu
4. Open the Load Game dialog

Alternative steps to reproduce:
1. Change the language to Japanese (Nihongo)
2. Start the tutorial, thus creating an autosave
3. Return to the main menu
4. Change to a different language (the game only expires autosaves in current language)
5. Play the game on Thursday (Wednesday or Saturday would probably work too)
6. Play the game on a different day (but within a week of step 5)
7. Ensure the language is set to en_US
8. Open the Load Game dialog

**Comment by Toranks** [comment] 2023-01-20 13:19
Related, I've always been annoyed by truncating filenames on load game dialog. I would like to be able to see the end of the filename, because I can't see with the naked eye what turn, or extension, it is, if the name is long. Would it be possible to make a scroll bar just for the file window, without affecting the buttons?

**Comment by Zireael07** [comment] 2023-01-20 14:12
+1 to ellipsis in the middle

**Comment by Wedge009** [comment] 2023-01-20 20:56
I don't necessarily think that it's _only_ Japanese file names, but certainly for the Japanese tutorial I can confirm this in (I believe) non-high DPI monitor (27-inch 2560x1440).

I recall issues with certain days of the week too (since closed), but I'm not sure that's necessarily relevant here.

**Comment by CelticMinstrel** [comment] 2023-02-04 21:46
I guess it's because most of the Japanese characters are double-width. The correct solution would be to truncate based on the physical size of the string rather than the character count.

**Comment by Wedge009** [comment] 2024-05-25 06:51
Seems to be resolved in master (1.19) after 5e3a86f7abbfcb48d4c55f4e275fe81fc4a0372a.

**Closed by Wedge009** 2024-05-25 06:51 UTC
Labels: Bug, Confirmed, UI
