### ISSUE TITLE
Assertion failure when unit without attacks tries to open attack dialog

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3535] opened 2018-09-09 07:36 UTC
Report for https://forums.wesnoth.org/viewtopic.php?f=4&t=48700

wesnoth: src/gui/widgets/generator_private.hpp:610: void gui2::generator<minimum_selection, maximum_selection, my_placement, select_action>::select_item(unsigned int, bool) [with minimum_selection = gui2::policy::minimum_selection::one_item; maximum_selection = gui2::policy::maximum_selection::one_item; my_placement = gui2::policy::placement::vertical_list; select_action = gui2::policy::select_action::selection]: Assertion `index < items_.size()' failed.

Involved unit code https://github.com/ProditorMagnus/Ageless-for-1-14/blob/01c56beb988faad9b0c340d9aefd1e6945994ca1/units/EoMa_units/Destroyers/Dark_Portal.cfg#L270-L306

**Comment by jyrkive** [comment] 2018-09-09 07:44
Duplicate of #3424.

**Closed by jyrkive** 2018-09-09 07:44 UTC
