### ISSUE TITLE
Editor backward compatibility

### ISSUE THREAD

**Issue by iddq-tea** [wesnoth/wesnoth#6384] opened 2021-12-15 15:24 UTC
### Game and System Information
 - Version: 1.16.1
 - Downloaded from the website
 - Windows 10, 64-bit, latest version

### Describe the desired feature
Instead of showing the usual "Unknown tile" error message, the editor should replace any unknown tiles with default ones, as it does with deprecated tiles. It would speed up the conversion process.

**Comment by knyghtmare** [comment] 2021-12-15 16:03
Defaulting the unknown terrains to Gg would be nice instead of an error and crash.

**Comment by soliton-** [comment] 2021-12-15 17:02
This is unrelated to deprecated terrain. Unknown terrain can only be replaced/represented with a single placeholder terrain or maybe one for a base terrain and one for an overlay.

I would definitely not choose Gg but a special terrain that makes it obvious that this is not a known terrain and also display a message about unknown terrain being in the map so the editor knows they probably need to replace that terrain if they want a usable map.

Really I wouldn't replace the terrain automatically at all unless explicitely requested by the user. In the case that the terrain is custom and the terrain definitions are simply not loaded we don't want to alter the map and in the case that an old map is updated the editor will need to choose appropriate terrain to replace each unknown terrain with.

**Comment by iddq-tea** [comment] 2021-12-15 17:46
I thought about this after making the post, here are my ideas:

The editor prompts the user beforehand, and if yes is selected, the file is not overwritten. If the user realizes they messed up, they don't lose any progress. By "as it does with deprecated tiles", I meant it has a specific graphical overlay - the letter D written over the default terrain (mushrooms). If D is for Deprecated, U could be for Unknown - and the terrain it defaults to could be mushrooms as well.

**Comment by CelticMinstrel** [comment] 2021-12-15 18:37
The reason that doesn't work is that if it's an unknown tile, there's no base to overlay the D on in the first place.

I think the correct approach is for the map editor to load maps with a special flag that alters the behaviour when encountering an unknown tile. Instead of giving an error message, it should automatically insert a default, hidden definition for that tile, so that the map can be viewed and even altered and resaved without affecting the unknown tile.

I'm not sure exactly how the unknown tile would be displayed though.

**Comment by doofus-01** [comment] 2021-12-25 20:16
If a hidden, default code is to be inserted, then the display should be pretty easy.  It could be color-hex.png, or a question mark similar to fake-shroud-editor.png.  There should still be some sort of error message.  Basically what soliton- said.

I wouldn't have thought anything needed to be written to the map data for that, but I don't know.

**Comment by stevecotton** [comment] 2023-02-17 13:12
Issue #7389 is almost a duplicate of this. I'm closing this one because the other seems clearer about what's requested.

**Closed by stevecotton** 2023-02-17 13:12 UTC
Labels: Enhancement, Editor, Terrain
