### ISSUE TITLE
Music and animations skip/lag on some tracks it seems (GNA #24623)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1550] opened 2017-05-08 11:30 UTC
**[Original submission](https://gna.org/bugs/index.php?24623)** by johncarthill on 2016-04-29

I've noticed this on the main screen, as well as at points during the Heir to the Throne campaign (it probably occurs in other campaigns, I just haven't played them yet). Eventually, the music starts skipping like crazy, and the sound effects/graphics begin to skip as well. The reason why I put this under "Sound and Music" is because the skipping goes away at least on the main screen once it loops back to the beginning of the music, so I feel like it's related to the music playing itself somehow?

Version: 12.5

Built from Sources: No, used the Windows installer

OS: Windows 10 Build 10586

Reproduce: Wait on the main screen for the music/mouse movement to begin skipping/lagging. Alternately, start the Heir to the Throne campaign, and wait for the skipping/lagging to happen there. In both these cases, you can then wait long enough for the problem to go away, and then return.

(Reproduced on Windows 10)
Release: 1.12.5
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:30
**Modified on 2016-04-29**

**shadowmaster changed release:** 12.5 -> 1.12.5

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:30
**Modified on 2016-04-29**

**johncarthill wrote:**

> As a followup note, I've found stopping the music when it encounters this problem and then restarting it (from the settings menu) fixes the problem temporarily.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:30
**Modified on 2016-04-30**

**wedge009 wrote:**

> Unfortunately, I can't find this issue with either of the scenarios described. I wonder if there's anything specific to your Windows 10 drivers. How long does it take before the music starts skipping? If it doesn't take more than a few minutes I suspect the issue might be specific to your sound set-up as surely other people would have encountered the issue as well if it was a common problem.
> 
> 
> 
> In the preferences menu, under sounds, what is the buffer size set to?

**Comment by Wedge009** [comment] 2017-05-09 11:38
Candidate for closing?

**Comment by Wedge009** [comment] 2018-05-02 14:37
Closing due to lack of further information and a way to reproduce this reliably.

**Closed by Wedge009** 2018-05-02 14:37 UTC
Labels: Audio, Bug, Windows
