### ISSUE TITLE
MP Lobby Create Game: Map previews do not always display

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6844] opened 2022-07-06 04:03 UTC
### Game and System Information

- **Version:** master at be1a347618f
- **Downloaded from:** self-compiled
- **Build info:** SCons on Linux/X11 with SDL 2.0.16, MSVC/CMake on Windows with SDL 2.0.22
- **OS:** Linux/X11 and Windows

### Description of the bug

This came out of investigating #6836. While I did not encounter the same image corruption reported in that issue I did notice that map previews did not always display. I found these scenarios exhibited behaviour where they would just show the same preview that the previously selected scenario had. Switching windows and then returning to Wesnoth forces a redraw and the map preview displays.

The problem scenarios I found in Linux:
* 2p Elensefar Courtyard
* 2p Fallenstar Lake
* 2p Howling Ghost Badlands
* 2p Rufus Isle
* 2p Sablestone Delta
* 2p Silverhead Crossing
* 2p Thousand Stings Garrison
* 2p Weldyn Channel
* 3p Alirok Marsh
* 4p A New Land
* 4p Castle Hopping Isle
* 4p Clash
* 4p Morituri
* 4p Underworld
* 4p Xanthe Chaos
* 5p Forest of Fear
* 6p Hexcake
* 6p Team Survival
* 6p Volcano

The list for Windows is much shorter, but the issue is the same (which only puzzles me more now, why should some scenarios display properly in Windows but not Linux...?):
* 2p Thousand Stings Garrison
* 2p Weldyn Channel
* 4p A New Land
* 4p Clash
* 4p Xanthe Chaos
* 5p Forest of Fear
* 6p Hexcake
* 6p Team Survival

### Steps to reproduce the behavior

1. Start Wesnoth
2. Select MP -> Local Game
3. Select through individual scenarios and note some of them do not properly update the map previews

### Expected behavior

To match behaviour in 1.16, where every scenario updates the map preview.

### Additional context

Both machines are using AMD GPUs. Open-source amdgpu for Linux.

**Comment by Wedge009** [comment] 2022-07-06 04:06
@Descacharrado Does my list above correspond to your observations in your Windows build?

**Comment by Descacharrado** [comment] 2022-07-06 17:19
For me (W10 MSYS) it is:
- 2p Thousand Stings Garrison
- 2p Weldyn Channel
- 2p Alirok Marsh
- 4p A New Land
- 4p Castle Hopping Isle
- 4p Clash
- 4p Morituri
- 4p Underworld
- 4p Xanthe Chaos
- 5p Forest of Fear
- 6p Hexcake
- 6p Team Survival
- 6p Volcano

Which is very weird because I distinctly remember that the other day I tested the same thing and only 2 maps were not updating the map preview... I have not rebuilt or changed branch since then.

**Comment by Descacharrado** [comment] 2022-07-06 17:44
As it is very hard to explain what is happening, I thought that some videos may help:

Video 1:
https://youtu.be/k2fZgAXnCno

In this video it can be seen that on a very small resolution, very few maps are being updated. Also, at the end, it can be seen that scrolling down just a little bit forces the map to load.

Video 2:
https://youtu.be/l5f_54gY6_U

This proof of what I said in the comment above about my 1366x705 resolution solving most maps. Also, it can be seen that no matter what map is bugged, if you preview "2p - dark forecast survival" first, the next map will always update correctly, and that only happens with dark forecast.

**Comment by Wedge009** [comment] 2022-07-06 22:11
Interesting... there does appear to be some correlation with window resolution. On my Linux machine I was in a 1920x1200 window. Maximising it to 2560x1371, I now find 2p Caves of the Basilisk not showing the map preview. I haven't gone through the rest of the list to see what else may be broken.

**Comment by mesilliac** [comment] 2022-07-07 02:01
Oh weird. It indeed seems related to screen resolution. I managed to reproduce in master it but it's not happening in new_rendering nor in my local with another overhaul i've been working on. So i think this will be fixed by pending changes, once those are merged.

**Comment by mesilliac** [comment] 2022-07-07 04:15
might be fixed by #6848...

**Comment by mesilliac** [comment] 2022-07-07 04:29
and i figured out what the critical factor was... it was the length of the description.

When they had smaller descriptions, or the window size was larger, it was less likely that changing the description would trigger a relayout. Smallest descriptions: Thousand strings and hexcake.

**Comment by Wedge009** [comment] 2022-07-07 06:46
#6848 resolves it for me, thanks. As I said earlier, it did look like a simple refresh/redraw issue. And that is weird indeed, how it was previously dependent on the description triggering a layout refresh.

**Comment by mesilliac** [comment] 2022-07-07 07:49
Great. Thanks for all the testing :)

**Closed** 2022-07-07 07:48 UTC
Labels: Bug, Graphics, MP Lobby
