### ISSUE TITLE
With touchpad horizontal scrolling is inverted

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#7404] opened 2023-02-21 14:48 UTC
When I use the touchpad, scrolling upwards scrolls upward, downward scrolls downwards. But scrolling right scrolls to left.

1.16 and c9eae7c affected.
When using the OS' settings to activate `natural scrolling`, all four directions are inverted, so the bug remains.

Using Linux with KDE on top of X11 with libinput.
Other programs are not affected by this problem.
Scrolling by moving the mouse pointer via the touchpad to a side or corner of the screen works correct as well.

**Comment by Pentarctagon** [comment] 2023-02-21 18:58
Does Wesnoth have any touch-specific handling? I thought it didn't but maybe I'm wrong.

**Comment by Wedge009** [comment] 2023-02-21 22:05
Pretty sure this is a duplicate of #3362. I don't have access to touchpad-scrolling any more, but I remember encountering the issue on Linux.

**Comment by Wedge009** [comment] 2023-02-21 23:10
#3362 looks like it's about horizontal scrolling via touch-pad (edge) to me, same as this one, not using scrollbar with a touch-pad as though using a mouse.

Regardless, wouldn't it be fair to consolidate similar issues?

**Comment by beetlenaut** [comment] 2023-04-21 17:11
I have this same issue using a mouse with a tilt-wheel. Vertical and horizontal scrolling work the opposite ways. I reversed the code changes made in #2218 on my own system because scrolling was too frustrating otherwise.

It's been suggested before, but I think we should just add options for this because the various desktop environments are such moving targets. (I am also using Linux with KDE.)

**Comment by pehjota** [comment] 2023-12-20 17:32
The old issue #2218 was considered to be a GNU/Linux issue, which is only partly true.  It was actually a bug in SDL, fixed on X11 in pull libsdl-org/SDL#4700 committed as libsdl-org/SDL@515b7e9 (released in version 2.0.18) and on Wayland in commit libsdl-org/SDL@3e1b3bc (2.0.20).  Pull #2481 worked around the SDL bug, but since SDL fixed it, this hardcoded workaround is now causing a regression.  Pull widelands/widelands#5394 committed as widelands/widelands@67db32a implemented a proper (though in my opinion a little overengineered) workaround using `SDL_GetVersion()` and `SDL_GetCurrentVideoDriver()`, and Wesnoth should do something similar to fix this regression (see pull #8137).

I observe this regression in Wesnoth master with SDL with 2.28.5 but not with SDL 2.0.14 (where the #2481 workaround worked).

**Closed** 2023-12-26 04:52 UTC
Labels: Bug, Duplicate, Input

**Comment by pehjota** [comment] 2023-12-27 09:58
Backported fix to 1.16 in PR #8158.
