### ISSUE TITLE
Planning Mode deadlocks game, when others players unit advances

### ISSUE THREAD

**Issue by Chenjox** [wesnoth/wesnoth#7058] opened 2022-10-20 22:35 UTC
### Game and System Information

- **Version: 1.16.6**
- **Downloaded from: Steam**
- **Build info:**
- **OS: Windows 10**

### Description of the bug

My friend and I love the whiteboard tool, as it makes managing units alot more simple.

The situation we accounted multiple times was the following: When a unit of another player A advances as a result of the execution of a planned move, the other player B's game just deadlocks. I can interact with the UI, even leave the game but cannot advance the game any further.
 

### Steps to reproduce the behavior

1. Have two players A and B
2. Have either player plan a move in which a unit advances
3. check the state of player B
4. Profit

### Expected behavior

Well, we don't expect the game to hang

**Comment by gfgtdf** [comment] 2023-03-19 03:22
I was not able to reproduce this, does this always happen to you or only in very specific cases ?

**Comment by gfgtdf** [comment] 2023-03-23 15:40
So this is probably a dublicate of this one #5302 and maybe unrelated to unit advancing.

**Comment by gfgtdf** [comment] 2023-04-04 00:35
#5302 was Fixed in 1.16.9

**Closed** 2023-04-13 16:53 UTC
Labels: Bug, Duplicate, MP, Whiteboard

**Comment by demario-w** [comment] 2023-04-13 22:31
I experienced the issue (as player B) and it seems different from #5302.
This issue is about MP game (only?) and not SP as the other issue. Hard to know the version used by other player of course.

The original description is pretty clear, but my experience is a bit different, I hit it about three times, until I start quitting/joining the game when the similar circumstances occur : two players (World Conquest), one has planning mode activated. When a planned move lead to a kill (hence on turn of player using planning mode), the game for the other player stops working: the killed unit doesn't fully disappear, the planning objects (arrows, filter on units' sprite) stay, and further moves by the other player are not showing on the board. Possibly the chat between players is not even working (he didn't answer to my chat).
The only thing to do is to quit and go back to the lobby (I am not DCed) and rejoin the game where control can be passed back to me. The player with planning mode can either host or be the guest. Nothing seems strange to the player with planning mode active.

From the 3 occurrences I hit, the planned move needs to lead to a kill (not necessarily advance) and the problem occur if the kill happen on the first attack (strike) of planned move (ie. it is not the first planned move). Maybe it happens intermittently but regularly enough (I changed my habit by quitting pretty fast). It doesn't happen on AI move killing units on the turn of the player using planning mode AFAIK.

**Comment by gfgtdf** [comment] 2023-04-14 21:40
The fix for #5302 is rather board i think, so even if it doesn't match this description exactly it's somewhat likely that it fixes it, I'd really like you to try with 1.16 head or once 1.16.8 come out to see if this still persists.

Feel free to file a new report or to reopen this one if it still happens in 1.16.8

**Comment by gfgtdf** [comment] 2023-04-30 00:41
> Hard to know the version used by other player of course.


Ftr, you can type '/q version <Playername>` in the command window (or was it the chat window? Not sure) to get the wesnothd client version used by other players
