### ISSUE TITLE
Fix the AI "cheating" on fog/shroud maps (GNA #3379)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1035] opened 2017-05-08 00:14 UTC
**[Original submission](https://gna.org/bugs/index.php?3379)** by anonymous on 2004-05-13

Making the AI understand fog is probably not that hard. The trick is to let it "remember" unit positions for at least one turn.

Shroud on the other hand, might prove difficult, because the AI won't know not to "explore" terrains that greatly slow its movement. At the least, we would need a significant new exploration AI.

(Reproduced on GNU Linux)
Release: 0.7.7-CVS
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment] 2017-05-08 00:14
**Modified on 2005-09-21**

**ott wrote:**

> See https://savannah.nongnu.org/bugs/index.php?func=detailitem&amp;item_id=8941 for Savannah history.

**Comment by CelticMinstrel** [comment] 2017-05-08 00:16
If I recall correctly, @mattsc partially addressed this?

**Comment by CelticMinstrel** [comment] 2017-05-11 02:13
@sigurdfdragon and @mattsc believe this should be closed, but I disagree. While it's not something that's likely to be done anytime soon (as it would require the AI to have some dedicated exploration AI, if I understand correctly, or alternately some way of "guessing" at what lies under shroud), I do think it would be a very nice thing to have.

**Comment by mattsc** [comment] 2017-05-11 02:25
Let me clarify.  The issue with the AI cheating under fog is, as far as I know, fixed.  That is the only part that I would consider an actual bug.

The AI remembering units it has seen is not necessary for the AI to work "correctly".  It is therefore an enhancement in my opinion, not a bug.

The same goes for the AI ignoring shroud.  That is how it works, a feature, not a bug.  Adding an explorer candidate action would be nice, but I would deal with that by creating a Micro AI which can then be added to the default AI, rather than by changing the default AI.  In fact, writing such an AI is on my task list, although with low priority.

Thus, I would close this as a bug report.  Doing so by labeling it an enhancement that can then be kept around indefinitely is fine by me.  However, since these are really three separate albeit related issues, I would close this and add separate feature requests for the second and third instead.

**Comment by CelticMinstrel** [comment] 2017-05-11 02:30
Ah, okay. If you want to close this but also open those feature requests, that would be fine with me. I do remember you addressing the first part you mentioned.

**Comment by mattsc** [comment] 2017-05-13 02:24
> If you want to close this but also open those feature requests, that would be fine with me.

Done in #1692.
Closing this one.

**Closed by mattsc** 2017-05-13 02:24 UTC
Labels: AI, bug
