### ISSUE TITLE
variable 'wc2_artifacts' must be assigned before being used

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#5228] opened 2020-10-24 11:59 UTC
### Game and System Information
The Battle for Wesnoth version 1.15.6+dev (9e91ddb1fee-Modified)
Distribution channel: Default

### Describe the bug
Started a local MP game, chose World Conquest for the era.  Recruited a couple times, right-clicked on one of the units, got a Lua error:
``
error scripting/lua: campaigns/World_Conquest/lua/era/era.lua:357: variable 'wc2_artifacts' must be assigned before being used
stack traceback:
        [C]: in function '.error'
        lua/ilua.lua:136: in metamethod '__index'
        campaigns/World_Conquest/lua/era/era.lua:357: in function <campaigns/World_Conquest/lua/era/era.lua:349>
``

**Comment by Pentarctagon** [comment] 2021-06-24 00:18
@doofus-01 does this error still appear?

**Comment by knyghtmare** [comment] 2021-06-25 20:50
Confirmed on: Battle for Wesnoth v1.15.14+dev (8679f0573f8-Modified) x86_64

20210626 02:48:57 error scripting/lua: campaigns/World_Conquest/lua/era/era.lua:360: variable 'wc2_artifacts' must be assigned before being used
stack traceback:
	[C]: in function '.error'
	lua/ilua.lua:136: in metamethod 'index'
	campaigns/World_Conquest/lua/era/era.lua:360: in function <campaigns/World_Conquest/lua/era/era.lua:352>

**Comment by CelticMinstrel** [comment] 2021-06-25 23:59
Hmm… it's assigned in game_mechanics/_load.lua, so there are four possible problems that I can think of:

1. An error occurs in shared_utils/wml_converter.lua, game_mechanics/ability_events.lua, or game_mechanics/artifacts.lua
2. game_mechanics/artifacts.lua returns nil
3. Something later assigns nil to the variable
4. game_mechanics/_load.lua is never called

The second or third seem the most likely…

**Comment by Pentarctagon** [comment] 2021-08-05 03:38
It looks like `#4` is the cause?  Adding just something like `wesnoth.log("error", "hi")` to the top of `_load.lua` results in "hi" being logged when starting a WC scenario but not when starting a regular scenario with the WC era.

`_load.lua` is called from:
```
lua/main.lua:4:wesnoth.dofile("./game_mechanics/_load.lua")
lua/campaign_main.lua:7:wesnoth.dofile("./game_mechanics/_load.lua")
```
`main.lua` is then only ever called from the WC scenario file:
```
scenarios/WC_II_scenario.cfg:199:                    wesnoth.dofile('campaigns/World_Conquest//lua/map/main.lua')
scenarios/WC_II_scenario.cfg:215:                    wesnoth.dofile('campaigns/World_Conquest//lua/map/main.lua');
resources/resources.cfg:10:            code = " wesnoth.dofile('campaigns/World_Conquest//lua/campaign_main.lua') "
era/era.cfg:36:            code = " wesnoth.dofile('campaigns/World_Conquest//lua/era_main.lua') "
```

**Comment by Pentarctagon** [comment] 2021-08-06 22:44
Apparently this has been a bug since even before WC was merged into master, since it also exists in the 1.15 add-ons server version.

Anyway, apparently the solution is to have the era load the resources wc2_artifact_data, wc2_trait_data, and wc2_trainer_data as well as loading everything in _load.lua except for the three invest files (since they require wc2_scenario) stops any errors when the game starts or you right click a unit.

**Comment by Pentarctagon** [comment] 2021-08-07 20:29
In summary:

Currently, when you right click on a unit on a regular scenario with the World Conquest era:
```
error scripting/lua: campaigns/World_Conquest/lua/era/era.lua:360: variable 'wc2_artifacts' must be assigned before being used
stack traceback:
        [C]: in function '.error'
        lua/ilua.lua:136: in metamethod 'index'
        campaigns/World_Conquest/lua/era/era.lua:360: in function <campaigns/World_Conquest/lua/era/era.lua:352>
```

After having it load the `wc2_artifact_data` resource, `game_mechanics/artifacts.lua`, and `shared_utils/wml_converter.lua`, right clicking works but selecting "Tell me how my recruit works" gives:
```
error scripting/lua: campaigns/World_Conquest/lua/era/era.lua:336: variable 'wc2_color' must be assigned before being used
stack traceback:
        [C]: in function '.error'
        lua/ilua.lua:136: in metamethod 'index'
        campaigns/World_Conquest/lua/era/era.lua:336: in field 'wc2_recruit_info'
        campaigns/World_Conquest/lua/era/era.lua:366: in field 'h'
        lua/on_event.lua:19: in function <lua/on_event.lua:12>
```

After having it also load `game_mechanics/color.lua`, selecting "Tell me how my recruit works" also now works, however now when a unit dies it gives:
```
error scripting/lua: campaigns/World_Conquest/lua/game_mechanics/artifacts.lua:182: variable 'wc2_scenario' must be assigned before being used
stack traceback:
        [C]: in function '.error'
        lua/ilua.lua:136: in metamethod 'index'
        campaigns/World_Conquest/lua/game_mechanics/artifacts.lua:182: in field 'h'
        lua/on_event.lua:19: in function <lua/on_event.lua:12>
```

After having it now also load `campaign/scenario.lua`, on loading it gives:
```
error scripting/lua: campaigns/World_Conquest/lua/campaign/scenario.lua:68: bad 'for' limit (number expected, got nil)
stack traceback:
        campaigns/World_Conquest/lua/campaign/scenario.lua:68: in field 'h'
        lua/on_event.lua:19: in function <lua/on_event.lua:12>
        [C]: in field 'fire_event'
        campaigns/World_Conquest/lua/campaign/scenario.lua:62: in field 'h'
        lua/on_event.lua:19: in function <lua/on_event.lua:12>

error scripting/lua: campaigns/World_Conquest/lua/campaign/scenario.lua:114: attempt to call a nil value (field 'wc2_objectives')
stack traceback:
        campaigns/World_Conquest/lua/campaign/scenario.lua:114: in field 'h'
        lua/on_event.lua:19: in function <lua/on_event.lua:12>
```

After having it also load `campaign/objectives.lua`, on load it gives:
```
error scripting/lua: campaigns/World_Conquest/lua/campaign/scenario.lua:68: bad 'for' limit (number expected, got nil)
stack traceback:
        campaigns/World_Conquest/lua/campaign/scenario.lua:68: in field 'h'
        lua/on_event.lua:19: in function <lua/on_event.lua:12>
        [C]: in field 'fire_event'
        campaigns/World_Conquest/lua/campaign/scenario.lua:62: in field 'h'
        lua/on_event.lua:19: in function <lua/on_event.lua:12>

error scripting/lua: campaigns/World_Conquest/lua/campaign/objectives.lua:28: attempt to concatenate a nil value (field 'wc2_difficulty.name')
stack traceback:
        campaigns/World_Conquest/lua/campaign/objectives.lua:28: in field 'wc2_objectives'
        campaigns/World_Conquest/lua/campaign/scenario.lua:114: in field 'h'
        lua/on_event.lua:19: in function <lua/on_event.lua:12>
```
However, `wc2_difficulty` is only ever assigned in `WC_II_scenario.cfg`.

So it seems that whatever gfgtdf changed between 1.14 and 1.15, the WC era isn't actually designed to be used independently from the WC scenario anymore.

**Comment by knyghtmare** [comment] 2021-08-07 21:01
> So it seems that whatever gfgtdf changed between 1.14 and 1.15, the WC era isn't actually designed to be used independently from the WC scenario anymore.

Would adding the `allow_scenario=` key inside the `[era]` suppress this bug?

```
[era]
    allow_scenario=WC_II_1p,WC_II_2p,WC_II_3p
[/era]
```

In my test version, I have observed that the era isn't displayed at all anymore if done like this, but well...the bug 5228 doesn't happen either? I am just suggesting this as a possible quick solution until a proper one for 1.17.x can be added in. Wesnoth does have 4 other eras in the core package to play World Conquest with and I do think those 4 are sufficient.

**Comment by Pentarctagon** [comment] 2021-08-07 21:36
That sounds reasonable, I'd say.

**Comment by CelticMinstrel** [comment] 2021-08-08 16:17
If the era isn't designed to be used on arbitrary scenarios, then that seems like a good solution; and if the situation later changes so that it does work, we can always remove it again.

**Comment by Pentarctagon** [comment] 2021-08-17 04:08
Closing in favor of #6032

**Closed by Pentarctagon** 2021-08-17 04:08 UTC
Labels: Bug, Campaign, MP, Lua API
