### ISSUE TITLE
Multiplayer Modification Checklist Bug

### ISSUE THREAD

**Issue by uluo-wes** [wesnoth/wesnoth#6780] opened 2022-06-20 20:02 UTC
### Game and System Information

- **Version:** 1.14.17 & 1.16.3
- **Downloaded from:** Steam
- **Build info:** No custom build. Downloaded through Steam, swapped between beta 1.14.x (stable) and current 1.16.3 in Steam Betas option in game properties. Since info and log files are long I uploaded both below.
- **OS:** Windows 10 21H2
[1.14.17 Build Info.txt](https://github.com/wesnoth/wesnoth/files/8943258/1.14.17.Build.Info.txt)
[1.14.17 Log.txt](https://github.com/wesnoth/wesnoth/files/8943259/1.14.17.Log.txt)
[1.16.3 Build Info.txt](https://github.com/wesnoth/wesnoth/files/8943260/1.16.3.Build.Info.txt)
[1.16.3 Log.txt](https://github.com/wesnoth/wesnoth/files/8943263/1.16.3.Log.txt)

### Description of the bug

When checking or unchecking mods in the multiplayer window the game freezes or hangs for a second and does one of the following:
1. Checks/Unchecks the selected mod only. (On rare occasion it's smooth with no hanging).
2. Checks/Unchecks up to 5+ other mods randomly, does nothing to the mod selected for some reason.
3. Checks/Unchecks the mod selected and another two spaces up or down.
4. When "3." occurs and I try to checking the selected mod again after unchecking both, the same mod two spaces up checks first, when clicking again the selected mod checks. Seems to happen in a weird sequence.

### Steps to reproduce the behavior

1. Download addons for 1.14.17 and 1.16.3, ideally the same addons updated for both versions.
2. Open multiplayer, select any map.
3. Check/Uncheck mods.

### Expected behavior

Checking and unchecking mods only does so for the selected mod and doesn't automatically do so for random mods in the list.

### Additional context

It's possible I messed something up having multiple installs of different versions of Wesnoth on Steam and two installed locally on two different drives causing unexpected bugs.

**Comment by knyghtmare** [comment] 2022-06-20 20:08
```js
20220620 14:39:53 error config: found modification with id=Dead_Bodies twice
20220620 14:39:53 error config: found modification with id=lay_ambushes twice
20220620 14:39:53 error config: found modification with id=wind_modification twice
20220620 14:39:55 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:39:56 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:39:57 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:39:57 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:39:58 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:01 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:01 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:01 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:02 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:02 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:04 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:04 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:05 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:08 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:08 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:09 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:09 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:12 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:12 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:13 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:14 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:14 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:16 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:16 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:16 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:17 error mp/create: ignoring on_mod_toggle that is already set
20220620 14:40:17 error mp/create: ignoring on_mod_toggle that is already set
```

At a glance I think the mods _Dead Bodies_ and _Wind Mod_ are firing most of the error messages for 1.16.3
Rest of it is deprecation and a lot of warnings from Warning Strings from AWW.

May I suggest you to uninstall _Dead Bodies_, _Wind Mod_ and _Ambush Rework_ (all mods by Pipapopinguin) and see if the problem persists?
Context: this author has been known to make very buggy mods (seeing the forum reports) and you are using 2 of them.

**Comment by uluo-wes** [comment] 2022-06-20 20:34
Uninstalling all of Pipapopinguin's mods fixed the issues for not only my two Steam installs but the two local versions as well.

**Comment by knyghtmare** [comment] 2022-06-20 20:36
Closing this since the uninstallation of _Dead Bodies_, _Wind Mod_ and _Ambush Rework_ solved the issue.
For future reference:
this is the third time modifications by Pipapopinguin have caused "bugs" or issues like this.

**Comment by soliton-** [comment] 2022-06-21 08:41
It would be still good to know what exactly the issue is. It sounds like a bug that an addon can cause this.

**Comment by soliton-** [comment] 2022-06-21 08:50
> Closing this since the uninstallation of _Dead Bodies_, _Wind Mod_ and _Ambush Rework_ solved the issue. For future reference: this is the third time modifications by Pipapopinguin have caused "bugs" or issues like this.

Do you know which one is the cause? Or each one does it? Does the author know?

**Comment by knyghtmare** [comment] 2022-06-23 11:20
> > Closing this since the uninstallation of _Dead Bodies_, _Wind Mod_ and _Ambush Rework_ solved the issue. For future reference: this is the third time modifications by Pipapopinguin have caused "bugs" or issues like this.
> 
> Do you know which one is the cause? Or each one does it? Does the author know?

I suspect all three. Installed only _Corpse Mod_ and the bug was caused instantly. 

The author was notified of the previous 2 cases of their addons causing bugs. I suppose to have to be notified for the third time.

**Comment by soliton-** [comment] 2022-06-23 11:28
The ones that I looked at all include the same files multiple times (for example corpse.cfg in that addon). I suspect that's the issue. Still sounds like a bug in wesnoth to cause such weird effects.

**Comment by knyghtmare** [comment] 2022-06-23 11:33
> Still sounds like a bug in wesnoth to cause such weird effects.

Perhaps not. I have installed mods by Mattss, Vasya N, Ravana, ForestD and myself and none of them have caused this kind of issue.

**Comment by soliton-** [comment] 2022-06-23 13:01
Some other addons not causing issues means this issue is not a bug in wesnoth? What's the relation even?

If there is a way to mess up the UI with one addon so that clicking on modifications of completely unrelated addons is messed up then that's clearly a bug in wesnoth. So far that's how it sounds like it to me.

**Comment by Pentarctagon** [comment] 2022-06-23 16:27
So the fix would be that when populating that list for the UI:
* Ignore modifications with duplicate IDs.
* Print an error to the log/stderr saying it ignored a duplicate for the modification ID each time it encounters a duplicate
?

**Comment by soliton-** [comment] 2022-06-23 16:30
Yes, I think that would be the simplest fix. Not sure something more sensible could be done really.

**Comment by Pentarctagon** [comment] 2022-06-23 19:17
Would that potentially break other things? I guess if it's done immediately on loading the modification then it's probably fine internally, but what about `allow_modification`/`disallow_modification`/`ignore_incompatible_modification`/`require_modification`?

**Comment by soliton-** [comment] 2022-06-24 17:58
I would accept either ID (with addon prefix or not) in those places so that it works the same as now but in the future UMC authors could gradually switch to the safer addon prefixed IDs.

**Comment by Discontinuum** [comment] 2022-06-24 18:54
I have a feeling most of ID duplication is when the addon coded a bit improperly like Dead Bodies. Maybe ignore the second one? Or can it be done so the behaviour is as now, but UI isn't broken? Dead Bodies doesn't produce 2 mods in the mod list, but it breaks the selection

**Comment by soliton-** [comment] 2022-06-24 19:29
For the case of duplicate IDs in the same addon there is no betterer way than to ignore I'd say. And ideally complain a bit more visibly so the author notices it easier.

**Comment by ProditorMagnus** [comment] 2023-08-02 07:17
If the addons are not fixed in reasonable time they need to be deleted.

> All add-ons uploaded must actually be functional. This does not mean add-ons must be bug free or that they must be complete, but they cannot:
Cause errors elsewhere, when not playing the add-on's content.

**Comment by soliton-** [comment] 2023-08-02 08:44
If there are broken addons feel free to report them but let's not clutter up this issue with that.

**Comment by Discontinuum** [comment] 2023-08-02 08:52
Why can't the game just ignore the second addon with the same id?

**Comment by soliton-** [comment] 2023-08-02 09:07
Because nobody has implemented that so far.

**Comment by gfgtdf** [comment] 2023-12-08 17:09
In case someone wants to work on it:
The problem is probably that when populating the modlist in 
https://github.com/wesnoth/wesnoth/blob/8977c1e60d09a9e852753bbf471d76be0cac62cf/src/game_initialization/create_engine.cpp#L783
The code removes dunblicates
 But when the other list of populated in 
https://github.com/wesnoth/wesnoth/blob/8977c1e60d09a9e852753bbf471d76be0cac62cf/src/game_initialization/depcheck.cpp#L76
The code doesn't remove dublicates so the two lists are out of sync.

**Comment by gfgtdf** [comment] 2023-12-08 17:12
Of course this is not an ideal solution, one could ask why do we need 2 lists (that can be out of sync) in the first place, and if we have two lists, why don't we at least populate the one list from the other list to make sure they are equal, one could try to refactor the code so that there are no longer two list etc.

**Comment by gfgtdf** [comment] 2023-12-08 17:20
After seeing the actual usecases, (which is an addon that includes the same file multiple times via macro inclusion ) i think it would maybe be better if we just showed none of the addons in that case, to make them aware that something is broken.

**Closed** 2024-02-11 20:38 UTC
Labels: Bug, MP Lobby, Add-ons
