### ISSUE TITLE
Parts of mini-map are visible on story text screen of a campaign

### ISSUE THREAD

**Issue by Earth-Cake** [wesnoth/wesnoth#4534] opened 2019-11-01 17:10 UTC
Version 1.15.2,
Steam version of the game,
on Linux Ubuntu.

On storytext screen you can see parts of the mini-map. I encountered this bug in Liberty as well.

1. Start Dead Water or Liberty campaign
2. Proceed to the first storytext screen

![map_bug](https://user-images.githubusercontent.com/52823609/68042140-73f0bf80-fcd2-11e9-980a-5d30bb13959f.png)

**Comment by Pentarctagon** [comment] 2019-11-01 17:14
Looks like it's the same as #4237, though the fix for that issue should be in 1.15.2.

**Comment by Earth-Cake** [comment] 2019-11-01 17:16
Yeah, looks like it.

**Comment by Pentarctagon** [comment] 2019-11-01 18:37
Is anyone able to confirm if this happens with the Steam release for macOS or Windows?  I can confirm it happens as well on Steam on Mint.

**Comment by Pentarctagon** [comment] 2019-11-02 03:42
From Discord:
```
<begui> using sdl 2.10 i cannot reproduce with version 1.14.9
<begui> linux
```

@Konrad22 do you see this behavior anymore?

**Comment by Konrad22** [comment] 2019-11-03 09:47
I don't, not on 1.15.2 SF or steam and not on 1.14.9 steam.

**Comment by Wedge009** [comment] 2019-11-03 20:00
Last time I checked Steam on Linux (which was very recently), albeit stable 1.14.9 release, it was still using SDL 2.0.9 which has batched renders disabled by default. Is the 1.15.2 Steam release on Linux really using SDL 2.0.10?

**Comment by Wedge009** [comment] 2019-11-03 20:21
> Looks like it's the same as #4237, though the fix for that issue should be in 1.15.2.

6436f902 and d4b3c9b4 added to master on 24th September while 1.15.2 was tagged on 20th October... :/

**Comment by Pentarctagon** [comment] 2019-11-04 03:44
It's a bit of an oddity, actually.  Both 1.14.9 and 1.15.2 for me report SDL 2.0.9 as the build version, but 2.0.10 as the runtime version.  So perhaps the problem is that it was built against a version of SDL that doesn't know about the batch rendering hint?

```
The Battle for Wesnoth version 1.15.2
Running on Linux Mint 19.2 Tina

Game paths
==========

Data dir:        /home/USER/.steam/steam/steamapps/common/wesnoth
User config dir: /home/USER/.config/wesnoth
User data dir:   /home/USER/.local/share/wesnoth/1.15
Saves dir:       /home/USER/.local/share/wesnoth/1.15/saves
Add-ons dir:     /home/USER/.local/share/wesnoth/1.15/data/add-ons
Cache dir:       /home/USER/.cache/wesnoth

Libraries
=========

Boost:             1.66
OpenSSL/libcrypto: 1.0.1  (runtime 1.0.2n)
Cairo:             1.10.2 (runtime 1.15.10)
Pango:             1.30.0 (runtime 1.40.14)
SDL:               2.0.9  (runtime 2.0.10)
SDL_image:         2.0.4  (runtime 2.0.5)
SDL_mixer:         2.0.4  (runtime 2.0.4)
SDL_ttf:           2.0.14 (runtime 2.0.15)

Features
========

JPG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: no
D-Bus notifications back end:   yes
```
and
```
The Battle for Wesnoth version 1.14.9 (9eba78f-Modified)
Running on Linux Mint 19.2 Tina

Game paths
==========

Data dir:        /home/USER/.steam/steam/steamapps/common/wesnoth
User config dir: /home/USER/.config/wesnoth
User data dir:   /home/USER/.local/share/wesnoth/1.14
Saves dir:       /home/USER/.local/share/wesnoth/1.14/saves
Add-ons dir:     /home/USER/.local/share/wesnoth/1.14/data/add-ons
Cache dir:       /home/USER/.cache/wesnoth

Libraries
=========

Boost:             1.66
OpenSSL/libcrypto: 1.0.1  (runtime 1.0.2n)
Cairo:             1.10.2 (runtime 1.15.10)
Pango:             1.30.0 (runtime 1.40.14)
SDL:               2.0.9  (runtime 2.0.10)
SDL_image:         2.0.4  (runtime 2.0.5)
SDL_mixer:         2.0.4  (runtime 2.0.4)
SDL_ttf:           2.0.14 (runtime 2.0.15)

Features
========

JPG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: no
D-Bus notifications back end:   yes
```

**Comment by Wedge009** [comment] 2019-11-04 04:54
I think that's the key. If I understand correctly, your builds are against SDL 2.0.9 headers - therefore the work-around to disable batched renders doesn't trigger (it only compiles when SDL version >= 2.0.10). And then you are running against SDL 2.0.10 library, which has rendering in batches as default, triggering this issue. I wonder if @Earth-Cake has a similar situation.

For what it's worth I re-ran 1.14.9+dev and 1.15.2+dev in Windows and Linux, all with SDL 2.0.10 for build and run-time, and I don't have the issue.

**Comment by Wedge009** [comment] 2019-11-04 04:54
Duplicate of #4237.

**Comment by Pentarctagon** [comment] 2019-11-05 00:37
@loonycyborg Can this be fixed for 1.15.3/1.14.10?

**Comment by Wedge009** [comment] 2019-11-05 00:42
What's to fix? I think the main question is why the build and run-time versions are different for your Steam installation. For mine, it's SDL 2.0.9, so why is your system running SDL 2.0.10? :S

**Comment by Pentarctagon** [comment] 2019-11-05 04:07
@Wedge009 I don't know - my system SDL version is neither of those (2.0.8) - but he's the one who creates the Steam package, so he'd be the most likely person I can think of who could provide an answer.

**Comment by Wedge009** [comment] 2019-11-05 04:14
As I said, my Linux Steam installation is using SDL 2.0.9, while my Windows Steam installation is using SDL 2.0.8, so this is really puzzling.

**Comment by AI0867** [comment] 2019-11-05 10:12
> What's to fix? I think the main question is why the build and run-time versions are different for your Steam installation. For mine, it's SDL 2.0.9, so why is your system running SDL 2.0.10? :S

The possible 'fix' would be to always build with SDL 2.0.10, which might eliminate the remaining instances of the issue.

As for why systems are running different versions, there are different versions of steam, and steam can use either the included libs or the libs of the operating system.

Can someone test a SDL 2.0.10-built version on a < 2.0.10 runtime to see if that works properly too?

**Comment by Wedge009** [comment] 2019-11-05 10:32
In my recent investigations relating to SDL I've used 2.0.10 headers with 2.0.8/9 DLLs (on Windows) just fine - that's how I established my case for submitting #4508 and #4510.

**Comment by Wedge009** [comment] 2020-01-14 20:42
Returned to this as a result of the Duplicate label. Remind me what's outstanding here, if anything. The underlying issue should have been resolved - are we just looking at build changes relating to SDL here? Just wondering if this should be closed (from the Duplicate).

**Comment by Pentarctagon** [comment] 2020-01-15 00:09
Just in general, wouldn't anything that's a duplicate be closable?

**Comment by Wedge009** [comment] 2020-01-15 03:22
Earlier today I closed the other Duplicate that was still active. Sounds like there's no objections to closing this one too.

**Closed by Wedge009** 2020-01-15 03:22 UTC
Labels: Confirmed, Duplicate, Graphics, Linux, Steam
