### ISSUE TITLE
Hovering with the cursor over certain unit attributes does not display explanation box when window is maximized or in fullscreen

### ISSUE THREAD

**Issue by IceTyp** [wesnoth/wesnoth#6096] opened 2021-09-17 10:21 UTC
### Game and System Information

 - Wesnoth 1.15.17
 - Steam
 - Ubuntu 20.04

### Describe the bug

When hovering with the cursor over certain unit attributes, the explanation box does not appear. This seems to happen only if the window is **maximized** or in **fullscreen**.
Note that the cursor is not displayed in the screenshots.

The following window is **not maximized**. When hovering over _nightstalk_ the explanation box appears (as it should):

![Hovering over ability not maximized window](https://user-images.githubusercontent.com/90767623/133762992-0e65103f-b7c9-4790-a49e-92bec5d8cfb8.png)

In contrary, the next window is **maximized**. The explanation box does not appear when hovering over _nightstalk_:

![Hovering over ability maximized window](https://user-images.githubusercontent.com/90767623/133762648-0362333c-017a-4b38-b168-48c470cb72b4.png)

Here, the window is in **fullscreen**. The explanation box does not appear when hovering over _nightstalk_:

![Hovering over ability fullscreen](https://user-images.githubusercontent.com/90767623/133765299-c618d43a-2c16-4701-8f5e-060368ab45a3.png)

### Other unit attributes

The explanation box of the following elements in the above picture is not displayed when hovering over them (when the window is maximized or in fullscreen):
- _Shadow_
- _nightstalk_
- _skirmisher_
- _Undead_ (Race)

In the above picture, the following elements are not affected by this bug:
- _chaotic (+0%)_
- _undead_ (Trait)
- _8x3 claws_
- _backstab_

Note that there is a similar behavior with other units.

### Further explanations

I have also installed Wesnoth 1.14.14 on the same system (with flatpak). There, this bug does not occur, that is, the explanation box is displayed when hovering over any of the listed attributes (even when the window is maximized or in fullscreen).

**Comment by Wedge009** [comment] 2021-09-17 10:52
@stevecotton and I noticed something similar while discussing #6007. Are you sure you only observe this with a maximised window?

**Comment by IceTyp** [comment] 2021-09-17 10:56
For me it only happens when the window is maximized or in fullscreen.
It does not happen when it is left aligned, right aligned or something else.

**Comment by Pentarctagon** [comment] 2021-11-02 23:40
It's definitely related to the window size somehow. I started a Sulla's Ruins game with a Lieutenant:
* 1280x720 - both Lawful and Leadership tooltips appear on hover.
* 1280x800 and above - the Lawful tooltip appears, but the Leadership tooltip does not.

**Comment by Wedge009** [comment] 2021-11-03 00:16
This is odd - it also looks to me like 1280x720 and 1280x800 is a threshold for working vs non-working tool-tips. It looks like everything is working in the former but some drop out in the latter. IceTyp's window appears to be 1920x1080, though it could be that there are missing tool-tips at that resolution too.

**Comment by MXB2001** [comment] 2021-11-03 15:39
I've also seen this but only in fullscreen not in maximized. My res is 1366x768. I will also try this hooked up to my 1280x1024 external monitor and report the results.

Missing boxes are for abilties, race, name, unit type only.

More interesting is that units with many abilties (which causes the display to show a ... for the ones that don't fit) the ones that are shown don't have a popup but the popup for the ... to show all the rest does work!

1.16.0 Debian Linux from flatpak on a Thinkpad laptop T430s

**Comment by IceTyp** [comment] 2021-11-03 17:45
I can also reproduce it on 1.16.0.
After some investigation, I think it depends on the **font size**. If for instance the window is right aligned, then the font size is smaller (on my laptop). But in full screen and maximized windows it is bigger. I also tried different resolutions and the issue seems to occur if and only if the bigger font size is in use.

**Comment by Pentarctagon** [comment] 2021-11-03 18:08
Wesnoth has different UI configurations defined based on the resolution being used.  So I would guess that the font size changes because it switches to a different configuration of the right sidebar's UI.  The simplest cause then would be that perhaps somehow the tooltip was removed from the configuration used for larger resolutions, though I'm having some trouble figuring out where the right sidebar's configuration is defined.

**Comment by MXB2001** [comment] 2021-11-03 18:58
I did some testing and here are the results. If EITHER the X res exceeds 1023 or the Y exceeds 767 the bug occurs.

I also ran into a CRASH when changing resolutions. I presume I should open a new bug report for that so I'll do that next.

**Comment by Pentarctagon** [comment] 2021-11-03 22:09
It looks like this happens more specifically when the vertical height of the window is larger than 767 pixels.  If I choose the resolution 1024x768, then the tooltip does not display.  If I manually resize it down one pixel to 1024x767, then the tooltip shows up.

**Comment by Wedge009** [comment] 2021-11-03 22:31
As discussed in #wesnoth-dev, 1024x768 is the base in https://github.com/wesnoth/wesnoth/blob/master/data/themes/default.cfg - lower resolutions have slightly different configuration as defined in that file.

**Comment by Pentarctagon** [comment] 2021-11-04 05:00
@stevecotton A bisect points to f282eb79483db8f463e5e87eca47e5334afa4e93 as the commit causing this issue.  The previous commit of b740153d9261ec02702ea219dcddf6fc5183dfe3 does not have this issue.

**Comment by stevecotton** [comment] 2021-11-04 18:03
> @stevecotton A bisect points to [f282eb7](https://github.com/wesnoth/wesnoth/commit/f282eb79483db8f463e5e87eca47e5334afa4e93) as the commit causing this issue. The previous commit of [b740153](https://github.com/wesnoth/wesnoth/commit/b740153d9261ec02702ea219dcddf6fc5183dfe3) does not have this issue.

I confirm that, but I can't explain it. The PR that's just auto-linked has a bit more detail, but I'd welcome guesses about how these were connected. I intend to have that PR ready for merging in time for 1.16.1, but it's time to stop today.

**Comment by stevecotton** [comment] 2021-11-04 22:42
Somewhere in f282eb7, the height of the lines of text is increasing by 1 pixel. The change isn't visible (all the drawn pixels seem the same, but that's just a comparison by eye when switching between windows), but the `rect`s that control the tooltips are one pixel taller.

It might affect width too, but as that varies depending on the text, it's harder to check. Will look further tomorrow.

**Comment by stevecotton** [comment] 2021-11-05 07:13
Apologies, in f282eb7 I noticed that `pango_text::set_maximum_height` already uses PangoLayout's `pango_layout_set_height`, and removed the apparently unnecessary enforcement of the maximum height from our wrapper code without testing the result. That's the root cause of this bug.

**Comment by stevecotton** [comment] 2021-11-06 06:33
Fixed in #6256 for 1.16 and #6261 for master.

**Closed by stevecotton** 2021-11-06 06:33 UTC
Labels: Bug, UI, Regression

**Comment by Wedge009** [comment] 2021-11-06 14:04
I gave this a try in 1.16 and it seems a lot better now. Thanks.
