### ISSUE TITLE
Multiplayer Local Game Lobby Issues

### ISSUE THREAD

**Issue by Mothy11** [wesnoth/wesnoth#3772] opened 2018-12-10 22:06 UTC
Multiplayer Local Game Lobby Issues 
Kind of tough to explain so added a gif if this doesn't make any sense:
The boxes for "Computer player" and AI type are not properly anchored to the page. When I scroll up the page, the boxes come too. When I scroll down the page, the boxes come too. 
Changing the AI type has no effect on this. 
Changing the player type back to local player will stop the boxes from incorrectly moving.
Independent of what map I choose, as long as I can scroll in the lobby.
Generally not a big issue, but the boxes are still interactive when moving and can sometimes get in the way when trying to set other players settings.

Additional info: 
Running Wesnoth version 1.14.5
Operating system is Linux Mint 19 Tara
Downloaded game from steam
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45773323/49765148-72bf4880-fd36-11e8-8326-9c358803b742.gif)

**Comment by gfgtdf** [comment] 2018-12-10 23:10
https://github.com/wesnoth/wesnoth/issues/3429

**Comment by Wedge009** [comment] 2018-12-13 09:12
Agree this is a duplicate of #3429. Thanks for reporting this.

**Closed** 2018-12-13 09:13 UTC
Labels: Duplicate, MP Lobby, UI
