### ISSUE TITLE
Weird graphical flickering around units that are on water castles when animate water is enabled at the maximum zoom

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6892] opened 2022-07-20 18:39 UTC
### Game and System Information

- **Version:** 1.17.6
- **Downloaded from:** Steam
- **OS:** Windows 10
- **Resolution:** 1920x1080

### Description of the bug

Let me show the gif first:
![flicker bug2](https://user-images.githubusercontent.com/41433185/180056763-702650ac-292b-457e-8dfc-d2fdfcf75edf.gif)
If you look around the cuttlefish and around the merking unit there is some weird flickering going on. This is at maximum zoom and when animate water is activated. There is also something weird going on with the colors of the hp bars and even some flickering on those bars. 
I also didn't show it here, but if you mouse over the units the shade of green of the hp bars changes slightly to a brighter green and back to a less bright green when moving the mouse away.
This recording was taken in the Scenario called Bilheld of the Dead Water campaign.

### Steps to reproduce the behavior

Go to the scenario Bilheld of Dead Water
Go to maximum zoom
Make sure animate water is active
Try moving the mouse back and forth over the units if you want to see the slight color change in the hp bars

### Expected behavior

No weird flickering artifacts when you are zoomed in and when animate water is active.

**Comment by mesilliac** [comment] 2022-07-21 00:17
I think this might be fixed by https://github.com/wesnoth/wesnoth/pull/6887 . Can you check and see if it still occurs in current master?

**Comment by mesilliac** [comment] 2022-07-21 00:19
Also worth checking: does it still happen in 1.17.6 after you've selected the unit? A texture property previously wasn't getting set correctly until the unit was highlighted.

**Comment by mesilliac** [comment] 2022-07-21 03:50
I couldn't reproduce the HP bar flickering, but i did reprdoce the cuttlefish tail flicker. That one seems to be fixed by #6893.

**Comment by max-torch** [comment] 2022-07-21 06:04
In 1.17.6, the problem still occurs even when the units are selected. The gif only shows the merking but it's the same situation with the cuttlefish.
![flickerbug3](https://user-images.githubusercontent.com/41433185/180140771-c9b2aa8a-29c0-456b-8dc8-f7df13cd1c3e.gif)
This is unlike what happened in #6891, where the problem does not occur if the unit is selected.

With regards to doing testing on the head commit of the master branch, I can't do it now, but I can do it in 3-4 days as I am planning to do a rebuild of Wesnoth on Ubuntu.

**Comment by max-torch** [comment] 2022-07-21 06:27
> I couldn't reproduce the HP bar flickering, but i did reproduce the cuttlefish tail flicker. That one seems to be fixed by #6893.

Still in 1.17.6 when loading, the scenario, the HP bar flicker doesn't happen sometimes. But as you can see, it did happen to me in 1.17.6 and I was even able to record it. But now I can't get it to happen anymore again. So I don't know what exactly it was that triggered the HP bar flicker, but at least I was able to document it when it happened :)

**Comment by mesilliac** [comment] 2022-07-21 07:30
There's no rush on testing, i'll be pulling in a lot of fixes and tidyups over the next few days. The relevant ones should be in tomorrow, so testing master any time after then should see if these issues are fixed or not.

The brighter HP bars when hovered is apparently intended, it explicitly changes the alpha on the bar.

I was getting flickering in the HP/XP bars at one point so it's not impossible there's something wrong there. But it should be fixed up in #6893.

From what i can see i think all the other issues are related to animation frames extending outside hexes, which i think should be all fixed up there as well. Verifying in the weekend after all the various tidyups are merged to master would be great.

**Comment by max-torch** [comment] 2022-07-24 19:10
Just Tested on The HEAD of current master.:
The Battle for Wesnoth version 1.17.6+dev (d1833b5cf73-Clean) x86_64
Running on Ubuntu 22.04 LTS x86_64
Distribution channel: Default

![image](https://user-images.githubusercontent.com/41433185/180662244-837d0e64-6a50-4a2e-89f8-4cb9aeb1c7f1.png)

The issue does not exist. There are no weird flickers. I don't know if it's because im on Linux or because im on the master.

**Comment by max-torch** [comment] 2022-07-24 19:12
In the OP i said:
> EDIT: The merking is not submerged in water like the other units around him. I do not know if this is intended.

I know now that it is intended since the central hex is not underwater.

**Comment by mesilliac** [comment] 2022-07-25 02:23
Alright looks good, this should be fixed then. Thanks for testing :). There were several fixes since 1.17.6 but i wasn't sure if it got all of the cases here.

**Closed by mesilliac** 2022-07-25 02:23 UTC
Labels: Bug, Graphics
