### ISSUE TITLE
Minimap issue in replay

### ISSUE THREAD

**Issue by ElderoZ** [wesnoth/wesnoth#2734] opened 2018-03-24 19:05 UTC
Wesnoth 1.13.12

When switching to full map view in the replay it does not show the visibility to be full map on the minimap, just the unit markers.
![obraz](https://user-images.githubusercontent.com/37750423/37867846-88fbbc5c-2f9e-11e8-97d2-d502fba5d098.png)

**Comment by soliton-** [comment] 2018-03-24 20:00
Duplicate of #2738.

**Closed by soliton-** 2018-03-24 20:00 UTC
Labels: Duplicate
