### ISSUE TITLE
[1.16.3] Check for missing credits in about.cfg

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#6475] opened 2022-01-30 20:37 UTC
A reminder task to check that new contributors have been credited. Definitely missing are:
* Bruno Macabeus (Trickster)
* Luis Miguel Iglesias (Descacharrado)

**Comment by Wedge009** [comment] 2022-01-31 00:17
Just wondering how far back we go? I notice not all of the top 100 committers (according to https://github.com/wesnoth/wesnoth/graphs/contributors) are included in `about.cfg`.

On top of @macabeus and @Descacharrado, there's also @max-torch, @knyghtmare, @czyzby, @severin, @Discontinuum, @evanmiller, @larb0b, @ddiefenthaler who seem to be absent (unless they're not credited by their GitHub alias). I only reviewed commits back as far as 2021-06-21 when 1.16 branch started. Is there a 'minimum threshold' of commits required for inclusion?

Also, not sure if he's only worked on master so far, but there's @Jonathan-Kelly for the WoF campaign too. Also, I don't see @nemaara or yumi in the credits...

**Comment by max-torch** [comment] 2022-01-31 04:12
I would be happy to be added to `about.cfg`
#6480

**Comment by czyzby** [comment] 2022-01-31 07:35
Can confirm that I didn't update the `about.cfg` in my pull request. If I also qualify, I wouldn't mind an entry in the `"Artwork and Graphics"` section along the lines of:

```ini
    [entry]
        name = "MJ (czyzby)"
        comment = "fixes and palette adjustments of the saurian sprites"
    [/entry]
```

**Comment by Descacharrado** [comment] 2022-01-31 09:14
I'd be happy to add myself in the next PR I open so you do not have to keep track of me, unless the "collecting everyone in one go" is what we are aiming to do. I also agree with Celtic:

> being added to the credits should be opt-out, not opt-in. Add everyone unless they request otherwise.

I'd say that adding the Github nickname should be the norm and then, if the contributor wants to opt out or modify their entry, they can do so similarly to what @max-torch did, opening a PR.

**Comment by nemaara** [comment] 2022-01-31 17:30
You can leave me off for now, thanks!

**Comment by knyghtmare** [comment] 2022-01-31 18:29
I got my forum name on the world conquest credits so not sure if I should added in about.cfg or not.

**Comment by severin** [comment] 2022-01-31 21:24
I'm fine either way 🙂

**Comment by ddiefenthaler** [comment] 2022-01-31 22:32
Hey, you can leave me out too.
I only made a very small contribution and not even to the game itself.
Thanks anyway!

**Comment by stevecotton** [comment] 2022-01-31 22:47
I'll gladly merge PRs for this, but it's easy to add names in a batch too.

**Comment by Jonathan-Kelly** [comment] 2022-02-01 00:26
Thanks for the consideration, but I did not get anything completed in time for 1.16, so I do not belong in its credits.

**Comment by Wedge009** [comment] 2022-02-01 00:42
> I got my forum name on the world conquest credits so not sure if I should added in about.cfg or not.

I'm not sure how the credits are collated internally but while there is an overall campaign section in the core `about.cfg`, it does appear that there are `[about]` sections pulled from the individual campaign files too. If your contributions have solely been in a specific campaign then maybe it's sufficient to just leave it that for now.

> Thanks for the consideration, but I did not get anything completed in time for 1.16, so I do not belong in its credits.

I thought you should be included in master at least, but then I suppose your contribution may also be campaign-specific and you've already (as I recall) credited yourself there.

So to my understanding (mainly for stevecotton's benefit):

**Confirmed to be added**
czyzby
Descacharrado
severin

**Assumed to be added (unless opt-out)**
macabeus
Discontinuum
evanmiller
larb0b

**Added**
max-torch

**Prefer to be left off**
nemaara
knyghtmare
ddiefenthaler
Jonathan-Kelly

I haven't looked at what sections various people should be included either, so that would be the responsibility of either the contributor, or whoever ultimately adds them to the credits.

**Comment by Jonathan-Kelly** [comment] 2022-02-01 18:24
> I'm not sure how the credits are collated internally but while there is an overall campaign section in the core `about.cfg`, it does appear that there are `[about]` sections pulled from the individual campaign files too.

It looks like everyone listed in `about.cfg` will show up anytime credits roll, whereas those listed in a campaign specific `[about]` will appear only when the player completes that campaign in particular. Though `about` credits have a much larger and fancier font. :)

I suppose about.cfg is also a helpful tool for associating names and aliases in one place. It was only after several months I realized @stevecotton and octalot are actually the same person, because I had somehow not checked this one file.

> I thought you should be included in master at least,

I guess I have no preference for master. (Sounded like maybe @knyghtmare is also in the no preference category?) I recently discovered the [add yourself to the game credits](https://wiki.wesnoth.org/PatchSubmissionGuidelines#Add_yourself_to_the_game_credits) rule, so I was going to figure something out as part of an upcoming WoF patch.

By the way, @stevecotton, you should consider upgrading your own place in the credits [to reflect your promotion](https://forums.wesnoth.org/viewtopic.php?t=52693)? And @Wedge009, it looks like you are only listed under `"Miscellaneous Contributors"` after having made hundreds of commits?

**Comment by Wedge009** [comment] 2022-02-01 21:59
> Wedge009, it looks like you are only listed under `"Miscellaneous Contributors"` after having made hundreds of commits?

One of the devs added me years ago when I first started. 'Miscellaneous' is probably still accurate now, I've mainly focused on relatively minor bug and string fixes, and not really done anything major in a specific domain, that I can recall.

**Comment by cooljeanius** [comment] 2022-03-01 04:09
oh hey I've had some PRs merged within the last year or so; I should add myself: https://github.com/wesnoth/wesnoth/commits?author=cooljeanius

**Comment by Wedge009** [comment] 2022-03-01 04:20
Oh, if you're not in there already, by all means go ahead. I only reviewed back to June 2021, looks like your most recent contribution was April 2021, so I missed you in my list.

**Comment by CelticMinstrel** [comment] 2022-03-01 07:30
> I haven't looked at what sections various people should be included either, so that would be the responsibility of either the contributor, or whoever ultimately adds them to the credits.

As far as I know, the general rule is that if you've committed code, you can be added to Miscellaneous Contributors. (I think we count WML as code for this purpose, though that would only apply if it was general WML and not specific to a single campaign.)

I don't know what the rule is for people who contribute things that aren't code (art, etc).

**Comment by Pentarctagon** [comment] 2024-01-18 17:23
It looks like some have been added in the mean time, so remaining is:
* Descacharrado
* macabeus
* Discontinuum
* evanmiller

**Closed** 2024-01-19 22:16 UTC
Labels: Blocker: New Stable, Prose, Help, Fwdport
