### ISSUE TITLE
THoT - S5 "Fear"- orc spawn error. 

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#4631] opened 2019-12-10 20:10 UTC
### Game and System Information
 - 1.15.2
 - Steam
 - Windows 10

### Describe the bug
Orcs `spawn` but they vanish immediately after appearing. Only orc leader is spawning properly. 

### Screenshots
![Bug](https://user-images.githubusercontent.com/41817546/70561760-55ac9800-1b8b-11ea-93ac-8ff5f9684bcd.JPG)

### Savefiles
[Bug.gz](https://github.com/wesnoth/wesnoth/files/3946752/Bug.gz)

**Comment by GregoryLundberg** [comment] 2019-12-10 20:49
Sounds like a duplicate of #4621

**Comment by Wedge009** [comment] 2019-12-22 09:15
I note #4621 is already closed, and I was not able to replicate this THoT S5 in master (but that save game does have the issue as reported). Is this issue specific to the 1.15.2 release? If it's really a duplicate, it should be closed, I think.

**Comment by Wedge009** [comment] 2020-01-14 20:39
Closing as duplicate. Re-open if desired.

**Closed by Wedge009** 2020-01-14 20:39 UTC
Labels: Bug, Duplicate
