### ISSUE TITLE
Torches turn green on zoom

### ISSUE THREAD

**Issue by beetlenaut** [wesnoth/wesnoth#3937] opened 2019-02-24 00:38 UTC
The sconce terrain (*^Efs) looks fine on the default zoom, but parts of it turn green on any other zoom level. This is often not that noticeable, but with an orange-tinted time area around the sconce, it's obvious. The wall-mounted torch variant does the same thing, but only during a few frames of its animation cycle. (The attached image is a scene from the second scenario of the add-on WML_Guide if you don't want to build a test case.)
![green_torch](https://user-images.githubusercontent.com/4147859/53293477-1f7f6280-3789-11e9-938f-0054f16411a4.png)

**Comment by cooljeanius** [comment] 2021-08-17 23:38
Related to point 1 in #5420 ("Lit cave becomes cyan") perhaps?

**Comment by mesilliac** [comment] 2022-06-15 08:58
does this still happen? I couldn't reproduce either in master or in 1.16.

**Comment by Wedge009** [comment] 2022-07-13 21:56
I also couldn't replicate in 1.16.5 release, using WML Guide S2. The #5420 mention is worthwhile investigating as a possible link otherwise I'd be inclined to close this. Marking as Works for Me since mesilliac also cannot replicate.

**Comment by mesilliac** [comment] 2022-07-14 00:45
I also couldn't replicate that other issue, i think both should be closed.

The other mentioned this was potentially related to xBRZ which is no longer used for scaling the game display.

If you look closely you can see the same hex outline artifacts in this screenshot, so i think it is likely that it was indeed related to the scaling algorithm and both issues are now doubly fixed.

**Comment by mesilliac** [comment] 2022-07-14 00:59
Closing both for now. If it reoccurs with the new rendering system, it's a new bug as scaling is now done in hardware.

**Closed by mesilliac** 2022-07-14 00:59 UTC
Labels: Bug, Works for me, Graphics

**Comment by max-torch** [comment] 2022-07-20 06:15
does this mean that possibly the xBRZ or whatever scaling feature was used can be tested again and returned, because we know that it possibly wasn't the actual main culprit for bugs like this? It looked really pretty with that feature.

**Comment by mesilliac** [comment] 2022-07-20 07:10
As far as i can tell this bug was definitely caused by the scaling system used. I'm not so sure it was xBRZ.

The other part of the bug linked above with seam lines appearing between hexes is probably also still a problem.
