### ISSUE TITLE
SotA S8-10: Recruit menu shows walking corpse variants in main recruit list (should only be in 'All Corpses' sub-list)

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6128] opened 2021-09-28 09:40 UTC
### Game and System Information
 - 1.15.18
 - Steam
 - Windows 10

### Describe the bug
In the scenarios where you control only Ras-Tabahn's army, his main recruit list contains the walking corpse variants. The official term is 'walking corpse' but I will make use of the term 'zombie' as well.

### To Reproduce

1. Kill any unit with a non-zombie unit in S8, S9, or S10
2. You will see the zombie variant of the killed unit be added to the main recruit list.

### Expected behavior
You should not see any zombie or zombie variant in the main recruit list. They are supposed to be present only when you enter the "All Corpses" Sub-list. This is the behavior for all other scenarios throughout the entire campaign.

### Screenshots
The main recruit list:
![image](https://user-images.githubusercontent.com/41433185/135062456-94157240-4bfa-4ea3-aba5-9299e5d273b1.png)
The 'All Corpses' Sub-list. This is the only place where the zombies should be listed:
![image](https://user-images.githubusercontent.com/41433185/135062813-a2eaf5db-386f-4711-b32c-1124826560bc.png)
The proper behavior (screenshot from S11):
![image](https://user-images.githubusercontent.com/41433185/135063323-fca7d642-60f7-4013-9796-bdddfcc224d3.png)

### Savefiles
Here's a savefile that already has the zombie variants in the recruit list.
[SotA-Merfolk Revenge.gz](https://github.com/wesnoth/wesnoth/files/7242813/SotA-Merfolk.Revenge.gz)
The savefile is from 1.15.17

**Comment by stevecotton** [comment] 2021-09-28 09:49
> In the scenarios where you control only Ras-Tabahn's army

Oooooh, that's the detail that we missed earlier; that the bug must be in the code that splits the two characters. This issue is a duplicate of #5237, so I'll close this as a duplicate but many thanks for debugging the root cause.

**Closed by stevecotton** 2021-09-28 09:49 UTC
