### ISSUE TITLE
When a player disconnects from the game during the important action, extra init_side's might corrupt the replay and lead to OOSes

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#6072] opened 2021-09-11 02:42 UTC
If a player suddenly disconnects, extra init_side commands sent when another player takes control might corrupt the game and lead to numerous ooses.

Examples:
1. https://replays.wesnoth.org/1.14/2021/09/06/4p__Isars_Cross_Turn_20_(92398).bz2 This Isar. On Turn 14 after Troll Whelp kills the archer, it should level, but the player dcs in this very moment, and init_side was sent. As a result the game lasted 6 more turns but was aborted by players due to ooses, and if you watch the replay in the game, it shows OOS here that init_side sent when user choice expected, then after skipping all ooses you get the window of choosing the troll advancement (in replay watching!) and after that the game crashes (on 1.14.9)

2. A game with the addon "The Great Steppe Era", the latest version 0.4.1beta. On turn 2 IPS who is in command of side 3, disconnects right before his turn. In chat we see "Removing illegal command 'init_side". But the result is the following: the host has two init_side's in his replays, other players have only one, as supposed. But init_side causes "side turn" event to be executed, so the host has side turn executed twice which caused the birthing timer of thee witch on 13,22 to tick two times instead of one. And the host had the witch spawned a unit one turn before the others which led to an obvious oos. Side turn events are considered multiplayer-safe in the docs, but this init_side problem when dc undermines this guarantee
[GSEGameHostVersion.gz](https://github.com/wesnoth/wesnoth/files/7147081/GSEGameHostVersion.gz)
[GSEGameNonHostVersion.gz](https://github.com/wesnoth/wesnoth/files/7147082/GSEGameNonHostVersion.gz)

In the host version: 
[host.txt](https://github.com/wesnoth/wesnoth/files/7147086/host.txt)

In the non-host version:
[nonhost.txt](https://github.com/wesnoth/wesnoth/files/7147088/nonhost.txt)

**Comment by gfgtdf** [comment] 2023-03-16 23:20
hmm do you still remember this? In particular which option the hosts picked after the player has  dropped (set idle/replacewith other player etc)?

**Comment by gfgtdf** [comment] 2023-03-17 02:37
More importantly: These replays are from wesnoth 1.14, do you know whether it still happens in 1.16 ?

**Comment by gfgtdf** [comment] 2023-04-27 03:35
Looks like a duplicate of #3685

**Closed by gfgtdf** 2023-04-27 03:35 UTC
Labels: Bug, MP
