### ISSUE TITLE
Add-on version check prevents joining game 

### ISSUE THREAD

**Issue by Zweitaktmotor** [wesnoth/wesnoth#8805] opened 2024-04-25 14:09 UTC
### Game and System Information

version 1.18
OS Linux Mint Debian 5

### Description of the bug

"Something is wrong with the add-on version. check database supporting the multiplayer lobby."

### Steps to reproduce the behavior

1. Try to enter a multiplayer game with a red exclamation mark.
2. Click to download the required add-on.
3. After the download, Wesnothwill restart, but trying to join the game again now produces the above error message.

### Expected behavior

I should be able to join the game after the download.

### Additional context

I did find a workaraound: 

1. Try and remember the name of the add-on
2. Log out
3. From the Home Screen, enter the add on server and install the required one.
4. Enter Multiplayer mode again and the game should work now.

But I would still prefer the context download from within multiplayer download.

**Comment by soliton-** [comment] 2024-04-25 14:20
What exactly were the involved addons? What game was it (game title or when did it start) or what exactly were the host settings?

The title is a bit confusing. The download was successful, yes? Wesnoth did not restart but reloaded its config?

**Comment by Zweitaktmotor** [comment] 2024-04-25 14:44
I can recall XPMod, Bonus Spam and Age of Heroes, but there may have been others.

At the moment, I can see "Utimate Survival" where this still happens.

The download itself seems to be successful, but afterwards it is not recognised, only displaying the above error message.

**Comment by soliton-** [comment] 2024-04-25 15:17
See also #8710 and #4055.

**Comment by gfgtdf** [comment] 2024-04-25 15:40
maybe you could try to enable the (clientside) netowrk log, relogin to thte server, and post the entry of that game here if you see such a game? It could be useful (at least it was last time).

**Comment by gfgtdf** [comment] 2024-04-25 19:12
Ok i think the problem is that in https://github.com/wesnoth/wesnoth/pull/8135/files i forgot up update https://github.com/wesnoth/wesnoth/blob/71a6e465e05095b06ee2fa52f36e22cb1a8b8249/src/server/wesnothd/server.cpp#L1576

**Comment by gfgtdf** [comment] 2024-04-25 19:26
the good thing is that we can probably fix this without waiting for the next release

**Comment by soliton-** [comment] 2024-04-25 19:43
I’ll have to check what you pointed at but it seems to me it can’t be all. The fact that the client says an addon is missing but then doesn’t prompt to install anything shows an inconsistency in the check itself.

**Comment by gfgtdf** [comment] 2024-04-25 19:52
> I’ll have to check what you pointed at but it seems to me it can’t be all. The fact that the client says an addon is missing but then doesn’t prompt to install anything shows an inconsistency in the check itself.

The client received nonsensial data, as shown in the log you showed above:
the `[addon]` part about XP_Bank says `require=no`, but the [modification] part below has `require_modification` empty which defaults to true here https://github.com/wesnoth/wesnoth/blob/71a6e465e05095b06ee2fa52f36e22cb1a8b8249/src/game_initialization/lobby_data.cpp#L206

**Comment by gfgtdf** [comment] 2024-04-25 19:56
i actually don't know why we send/use the redundant data (the [modification] when we have [addon] already) in the first place tho.

**Comment by soliton-** [comment] 2024-04-27 12:10
If there are multiple checks based on redundant data then that certainly makes little sense. Regarding `require_modification` it sounds like client and server disagree on the default.

Anyway either the check(s) need to validate the redundant data is consistent or better remove the redundancy.

**Comment by ProditorMagnus** [comment] 2024-05-06 18:34
Should we ask @ForestDragon-wesnoth adjust xp bank?

**Comment by gfgtdf** [comment] 2024-05-07 00:13
I mean you can, but mostly this is really a bug in wesnoth, the server actively removes `require_modification=no` so whether its unset or not set doesnt matter, only require_modification=yes works currently if i understood the code correctly.

**Comment by soliton-** [comment] 2024-05-07 07:53
It was originally implemented that way in https://github.com/wesnoth/wesnoth/commit/bcaa7f4f2c7b0e4f15eb231d75db010c5d5f6577

The client was changed in 05d1e4b9ba2beaf72663c3c72c71775afe6b4081

**Comment by Pentarctagon** [comment] 2024-06-24 01:00
Any chance of this getting fixed in the next month or so?

**Comment by gfgtdf** [comment] 2024-06-24 01:25
hmm for some reason i interpretet solitions last comment that we wanted to investigate this more, the fix is mostlikely easy, (and server sided, so independed of the release scedule)

**Comment by gfgtdf** [comment] 2024-06-24 01:29
opened a pr for it

**Comment by Pentarctagon** [comment] 2024-06-24 01:32
Nice, thanks.

**Comment by soliton-** [comment] 2024-06-24 08:44
> hmm for some reason i interpreted solitions last comment so that he wanted to investigate this more first. The fix is mostlikely easy, (and server sided, so independed of the release scedule)

There was nothing more to investigate the client side default was changed in the mentioned commit which broke the logic. We can certainly fix it on the server side.

**Closed** 2024-06-27 08:25 UTC
Labels: Bug, MP, MP Lobby
