### ISSUE TITLE
Language change doesn't affect unit alignment

### ISSUE THREAD

**Issue by WhiskeyjackBfW** [wesnoth/wesnoth#8393] opened 2024-02-12 23:01 UTC
### Game and System Information

- **1.17.25:**
- **both Steam and Wesnoth downloads page versions:**
- **Build info:**
- **Windows:**

### Description of the bug

Changing the game language does not affect the ingame alignment language until the game is restarted. Tested to affect both saved and new games (only tested with campaigns). Tested both German -> English and English -> German extensively.

Restarting the game seems to change the alignment language as well, but does not fix the issue (changing the language again reproduces the bug).

### Steps to reproduce the behavior

1. Change the language of the game.
2. Start any match or load a save file
3. Look at any units alignment (including tooltip)

### Additional context

![grafik](https://github.com/wesnoth/wesnoth/assets/159852416/2da01603-88ed-4138-a3ef-cad2b5b690ab)

**Comment by gfgtdf** [comment] 2024-02-13 02:52
I can reproduce this one on linx aswell

**Comment by Wedge009** [comment] 2024-02-13 06:16
I couldn't replicate this in 1.16.11 release, but I haven't checked master yet. At first I thought this might have been related to my #4505 report, but that appeared to be resolved in 1.16.x. Maybe something changed again in 1.17.x?

**Comment by Wedge009** [comment] 2024-02-13 08:03
On a quick test between English and French with master @ 144daf8825b, I get a recurrence of #4505 (objectives not in current language selection), but I can't replicate this particular issue (side bar not in current language selection).

**Comment by gfgtdf** [comment] 2024-02-13 12:25
> but I can't replicate this particular issue (side bar not in current language selection).

Its not about sidebar, its only  about alignment strings

**Comment by Wedge009** [comment] 2024-02-13 12:30
Okay, the image in the original confused me - I thought it was from a German language selection and thus having most things in English threw me. I can confirm this also, and it's specific to 1.17.

**Comment by Wedge009** [comment] 2024-02-13 13:13
It looks like this was introduced in c4c292fa3bc01e0a39ae9fa73ae1b88c60e758d5 by @Pentarctagon since 1.17.2. Is it related to the unit alignments being defined as `const`s? There are many such definitions, but it looks like only the unit alignments are visible to the user.

One of those obscure bugs that's only exposed by someone regularly changing the language selection.

**Comment by Pentarctagon** [comment] 2024-02-13 16:17
Just making something const wouldn't cause the issue by itself - if it was trying to change the value of a const variable, that'd be a compiler error.

**Closed** 2024-03-01 11:41 UTC
Labels: Bug, Confirmed, Translations, Regression

**Comment by gfgtdf** [comment] 2024-03-05 00:57
Does anyone  know what the issue was? Language changing during the lifetime of a t_string object is something that t_string _should_ be able to handle, that's why it has the translation timestamps and the t_string::reset_translations() function, so imo having these as static variables  should be fine if t_string::reset_translations() works as expected.
