### ISSUE TITLE
Mix_CloseAudio() hangs when closing Wesnoth

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3588] opened 2018-09-30 22:43 UTC
From the title screen, open the add-on manager, and when the list of add-ons is shown press Alt+F4. Wesnoth freezes and needs to be killed.

**Comment by gfgtdf** [comment] 2018-09-30 22:46
canot reproduce this one, here it closes as it shoudl tested on official 1.14.5 windows release.

**Comment by Pentarctagon** [comment] 2018-10-01 00:05
Also can't reproduce on Mint 19, Wesnoth 1.14.5+dev.

**Comment by jostephd** [comment] 2018-10-01 19:56
Thank you. I now looked into it more and I think I found the problem.

One, this has nothing to do with the add-on manager. It also happens if I try to quit from the title screen. Two, it hangs on this line:
https://github.com/wesnoth/wesnoth/blob/7d37175292386dcd4abdcc9a037263f4ae6e9f54/src/sound.cpp#L476
Mix_CloseAudio() returns only when VLC running under another user stops playing music.

I think that Mix_QuerySpec/Mix_CloseAudio pattern is correct so I'll try upgrading libsdl2-mixer.

**Comment by Pentarctagon** [comment] 2018-10-03 00:19
`dpkg` reports my version as being "2.0.2+dfsg1-2".

**Comment by jostephd** [comment] 2018-10-03 19:41
libsdl-mixer1.2:amd64 1.2.12-11+b3
libsdl2-mixer-2.0-0:amd64 2.0.1+dfsg1-1

**Comment by Wedge009** [comment] 2018-10-17 03:32
Do we have any more info on how to replicate this? I haven't seen this one on either master (new and old) or 1.14, Windows or Linux.

SDL mixer is 2.0.2 for both Windows and Linux.

**Comment by Pentarctagon** [comment] 2018-10-17 07:07
So far, it looks like it might be an issue with SDL Mixer 2.0.1.

**Comment by jostephd** [comment] 2018-10-17 17:09
> Do we have any more info on how to replicate this? I haven't seen this one on either master (new and old) or 1.14, Windows or Linux.

Ctrl+Alt+F6, have vlc play something, Ctrl+Alt+F7 (vlc keeps playing!), open wesnoth (I tested 1.14), close wesnoth. Wesnoth will only close after vlc is closed on the Ctrl+Alt+F6 login. (Ctrl+Alt+Fn switches to another tty)

I can reproduce that with the following toy program too (extracted from src/sound.cpp):

```
// Compile with: -lSDL2 -lSDL2_mixer
#include <limits.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_mixer.h>
#include <SDL2/SDL_rwops.h>

const char SOUND_FILE[] = "/usr/share/games/wesnoth/1.14/sounds/chat-highlight.ogg";

static bool init_sound()
{
	if(SDL_WasInit(SDL_INIT_AUDIO) == 0) {
		if(SDL_InitSubSystem(SDL_INIT_AUDIO) == -1) {
			fprintf(stderr, "Could not initialize audio: %s\n", Mix_GetError());
			return false;
		}
	}

	if(Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 1024) == -1) {
		fprintf(stderr, "Could not initialize audio: %s\n", Mix_GetError());
		return false;
	}

	Mix_AllocateChannels(32 /* n_of_channels */);
	Mix_ReserveChannels(12 /* n_reserved_channels */);

	Mix_Music *mus = Mix_LoadMUS(SOUND_FILE);
	Mix_PlayMusic(mus, INT_MAX);

	return true;
}

void close_sound()
{
		int frequency;
		uint16_t format;
		int channels;
		int numtimesopened = Mix_QuerySpec(&frequency, &format, &channels);
		if(numtimesopened == 0) {
			fprintf(stderr, "Error closing audio device: %s\n", Mix_GetError());
		}

		while(numtimesopened) {
			Mix_CloseAudio();
			--numtimesopened;
		}
}

int main(void)
{
	init_sound();
	sleep(1);
	close_sound();
	return EXIT_SUCCESS;
}
```

Change the hardcoded path, compile and run it. If vlc is not playing, the toy program exits cleanly. If vlc is playing, the toy program will only exit a few seconds after vlc stops playing (e.g. by pressing "pause" in vlc).

**Comment by GregoryLundberg** [comment] 2018-10-17 19:19
The question, then, is: is this sample program hanging in the init_sound or in the close_sound function? Do you hear the chat-highlight OGG before VLC plays something, after VLC finished, or not at all?

It would make sense to me that it's hanging in the init_sound, blocked awaiting VLC to release the sound device. In which case, this is a case of not looking before leaping (specifically, not checking that the sound device is available before assuming it is blocking because the music cannot be started). In this case, if there is no way to check, that's an upstream issue.

If it's blocking in the close_sound, it sounds like an upstream issue but we might be able to work around it by adding a time-out (say, give it 1 second to stop playing and close down).

**Comment by jostephd** [comment] 2018-10-17 19:39
> The question, then, is: is this sample program hanging in the init_sound or in the close_sound function?

In Mix_CloseAudio(), like I said.

> Do you hear the chat-highlight OGG before VLC plays something, after VLC finished, or not at all?
> 

I don't hear the ogg at all.

If vlc stops playing while tty7 is focused, wesnoth (that's already running in the background) starts playing its background music.

If vlc is launched on tty6 with `sleep 2 && vlc foo.mp3` while tty7 is focused, then wesnoth's background music continues to play and vlc doesn't start playing until tty6 gets focus.

> If it's blocking in the close_sound, it sounds like an upstream issue but we might be able to work around it by adding a time-out (say, give it 1 second to stop playing and close down).

Sounds good, though I'm not sure how to implement that.

**Comment by GregoryLundberg** [comment] 2018-10-17 19:49
In the sample, you opened it once but are looping to close it a number of times. If one of those times is because VLC has it open, and you can't close VLC's use of it, there you go.

So, first pass, add your own counter for how many times you opened the device and see if closing it that many times fixes it. Quick test for this: in the sample program, check that `numtimesopened == 1`

Also, try a much longer sleep (like 10 or 15 seconds) so you can see if you hear the OGG sound before you fire up VLC.

Another test, have two copies of the sample playing different sounds/tracks, and displaying progress info and see if one hangs for the other. It's possible the bug is in VLC, not SDL_mixer.

**Comment by jostephd** [comment] 2018-10-17 21:36
Thanks for the guidance. IIRC the bug happens when I substitute mplayer for vlc. Beyond that, I "solved" the bug for myself by not leaving vlc open in tty6 while I'm trying to play in tty7, so this isn't particularly urgent for me. Perchance does someone else want to pick this up from here?

**Comment by Wedge009** [comment] 2018-10-17 23:13
How difficult is it for you to test SDL mixer 2.0.2? If the issue still occurs then, I'd be inclined to say it's a problem between how external audio players and SDL interact. If not, then we have our solution.

**Comment by jostephd** [comment] 2018-10-18 18:16
Not easily, I'm afraid. I tried to backport it (to Debian stable) but ran into dependency problem.

**Comment by jostephd** [comment] 2018-10-19 19:18
> So, first pass, add your own counter for how many times you opened the device and see if closing it that many times fixes it. Quick test for this: in the sample program, check that `numtimesopened == 1`

Yes, it is equal to `1`. The very first call to Mix_CloseAudio() hangs.

**Comment by Vultraz** [comment] 2019-01-23 10:48
Is this resolved now that we have Mixer 2.0.4?

**Comment by jostephd** [comment] 2019-01-27 19:51
I'll test when I have time.

**Comment by sevu** [comment] 2019-03-23 15:06
Didn't test, just adding the label

**Comment by truesoundlord** [comment] 2019-04-07 20:04
Same issue with SDL2_mixer (2.0.2) in LEAP 15.
When using netbeans with gdb as debugger when stepping at Mix_closeaudio it hangs.
Running never triggers any issue it happens only when debugging using gdb.

There is the -g flag used at the compile line. I'll try with -ggdb flag.

**Comment by Pentarctagon** [comment] 2023-10-18 19:12
Closing given the Unconfirmed label and lack of recent comments.

**Closed by Pentarctagon** 2023-10-18 19:12 UTC
Labels: Bug, Upstream issue, Unconfirmed, Audio
