### ISSUE TITLE
Planning mode: crash to desktop when cancelling >2 moves while holding unit with 0MP

### ISSUE THREAD

**Issue by Maegil** [wesnoth/wesnoth#1842] opened 2017-07-18 23:34 UTC
Battle for Wesnoth 1.12.6 pt-br from the wesnoth.org link
Windows 7 ultimate SP1

To reproduce:
-set to planning mode
-select any unit with 0 MP left (if the selected unit has moves left, expend the remaining MP first)
-plan a first move, then a second; you can add more moves but less than two does not trigger the bug
-select the unit once again and press "h" (regardless of whether the cursor is still over the unit or elsewhere); cancelling the moves without selecting the unit does not trigger the bug
-the game CtDs; a Windows error message has appeared on the third (see screenshot) and fourth tests but not on the other attempts. 

[HdT-Inverno_Nórdico-Salvo-automaticamente5.gz](https://github.com/wesnoth/wesnoth/files/1157458/HdT-Inverno_Nordico-Salvo-automaticamente5.gz)
[stderr.txt](https://github.com/wesnoth/wesnoth/files/1157452/stderr.txt)
![westnoth crash](https://user-images.githubusercontent.com/30274230/28342385-575b4876-6bee-11e7-908e-00d7a8054be3.jpg)

**Comment by Coffee--** [comment] 2017-07-20 09:58
I can reproduce this error for 1.13.x. Happy to assign this to myself and look to see if it can be fixed for 1.13.9.

**Comment by gfgtdf** [comment] 2017-07-20 10:38
@Coffee-- bug #1841 is also easy to reproduce and faisl with the same assertion error message so they could be related.

**Comment by Coffee--** [comment] 2017-07-20 11:05
Thanks gfgtdf.

BTW I'm not claiming exclusive rights to this bug, so by all means feel free to fix it first :P I can take a look over the weekend at this and maybe some other planning mode issues with attacks in multiplayer.

**Comment by Wedge009** [comment] 2017-07-21 03:15
Appreciate your willingness to look at this. It looks like this could be another symptom of the same problem as in #1595 and #1324.

**Comment by Coffee--** [comment] 2017-07-23 03:39
Looks like this issue can only be triggered by the keyboard command 'h' to delete a planned action. The other issues may be different things and this issue might simply be worked around by deselecting the current unit before a deletion. I will see if this is easy to implement.

**Comment by Coffee--** [comment] 2017-07-23 10:11
Seems like this can be solved by changing the src/whiteboard/manager.cpp manager::contextual_delete as per the todos already mentioned in the comments. That is, changing to use the find_last_action_of instead of find_first_action_of.

Will probably require a bit more testing. I can look at this next weekend further.

**Comment by Coffee--** [comment] 2017-07-25 11:14
Should now be fixed for 1.13.9 release in commit b5641d8e3ccc1c4e88f32e97939e461a80ff95bf

**Comment by Wedge009** [comment] 2017-07-25 12:14
Wow, that 'to do' comment was added by someone called Tommy Schmitz back in July 2011. I don't there's anyone active left who knows the planning-mode code really well any more. If following the suggestion in the comment resolved the issue then great. Let's see if any regressions come of it.

**Comment by Coffee--** [comment] 2017-07-29 22:22
Seems all good to me. There is a minor graphical result where we should also deselect the unit after deleting candidate moves, but this is in the TODOs listed fo someone in the future. Closing this issue.

**Closed by Coffee--** 2017-07-29 22:22 UTC
Labels: bug, Units, Whiteboard
