### ISSUE TITLE
Problems with loading/deleting file names with both spaces and underscores (GNA #24937)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1567] opened 2017-05-08 11:49 UTC
**[Original submission](https://gna.org/bugs/index.php?24937)** by wedge009 on 2016-08-07

Perhaps an extension of bug #21926 - something has changed since my last test then.

Taking an otherwise valid save file and renaming or making a copy of it with spaces in the file name, attempting to load the file results in a 'corrupted save' message. Additionally, attempting delete the file from the Load Game dialogue results in the entry being deleted in the GUI, but the actual file remains in the file system, on disk. For the latter, no record of this problem is in the logs.

This only seems to be an issue in Windows, in current master. 1.12 in Windows is fine, Linux is also okay, with regards to both loading and deleting.

(Reproduced on Windows,OSX)
Release: 1.13.5+dev
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:49
**Modified on 2016-08-07**

**wedge009 wrote:**

> Considering this minor because Wesnoth doesn't generate file names with spaces - underscores are used instead. This situation arises when I make copies of files - Windows appends things like ' - Copy' or ' (2)' to the file name.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:49
**Modified on 2016-08-07**

**gfgtdf wrote:**

> The is most likeley caused by out use of std::strftime whihc is local dependent and iirc windows has no utf locales.
> 
> 
> 
> This most likeley doenst effect linux.
> 
> 
> 
> The proper ifix is most likeley not to use std::strftime and instead eigher use boost locale/icu or some other library.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:49
**Modified on 2016-08-08**

**wedge009 wrote:**

> Thanks for the information.
> 
> 
> 
> That's right, as I mentioned, Linux seems to be okay.
> 
> 
> 
> The interesting thing to note is that 1.12 also seems to be okay. I see that std::strftime() is wrapped with util::strftime(), the latter being used throughout the rest of the code. This util::strftime() wrapper has remained unchanged since at least 1.12 so I'm wondering if the breakage has happened elsewhere. Too, the save_info::format_time_local() which uses util::strftime() also seems very similar.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:49
**Modified on 2016-08-11**

**the_squished_elf wrote:**

> Noting that this is present in Mac OS X as well, exactly as you described it.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:49
**Modified on 2016-10-04**

**beetlenaut wrote:**

> I am using Linux, and I am seeing the same problem.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:49
**Modified on 2016-10-20**

**gfgtdf wrote:**

> As i said in some other thea my earler post here about "The is most likeley caused by out use of std::strftime" went accidnetly here and belonged to another issue.
> 
> 
> 
> 
> 
> The problem here is that our ui code translated spaces to underscores, so that when you type 'a b' in the savegame dialog the generated filename is actually 'a_b', a similar code is also in the loadgame dialog.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:49
**Modified on 2016-10-21**

**wedge009 changed OS:** Windows -> Windows,OSX

**wedge009 wrote:**

> I just tested this again and confirm Linux is okay (although it does drop error messages to stderr).
> 
> 
> 
> In Windows, selecting the offending save file results in an 'invalid' message in the preview section on the left, plus attempting to load it results in a 'file is corrupted' message.
> 
> 
> 
> Looking at the logs, I can see Wesnoth is attempting to try a variety of combinations of underscores and spaces, though:
> 
> 
> 
> ```
> 
> 20161022 12:26:00 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les_Elfes_assi�g�s-test_with_spaces.gz' for reading.
> 
> 20161022 12:26:00 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les Elfes assi�g�s-test with spaces.gz' for reading.
> 
> 20161022 12:26:00 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les_Elfes_assi�g�s-test_with_spaces.gz.gz' for reading.
> 
> 20161022 12:26:00 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les Elfes assi�g�s-test with spaces.gz.gz' for reading.
> 
> 20161022 12:26:00 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les_Elfes_assi�g�s-test_with_spaces.gz.bz2' for reading.
> 
> 20161022 12:26:00 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les Elfes assi�g�s-test with spaces.gz.bz2' for reading.
> 
> 20161022 12:26:04 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les_Elfes_assi�g�s-test_with_spaces.gz' for reading.
> 
> 20161022 12:26:04 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les Elfes assi�g�s-test with spaces.gz' for reading.
> 
> 20161022 12:26:04 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les_Elfes_assi�g�s-test_with_spaces.gz.gz' for reading.
> 
> 20161022 12:26:04 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les Elfes assi�g�s-test with spaces.gz.gz' for reading.
> 
> 20161022 12:26:04 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les_Elfes_assi�g�s-test_with_spaces.gz.bz2' for reading.
> 
> 20161022 12:26:04 error filesystem: Could not open '...\Wesnoth1.13/saves/HdT-Les Elfes assi�g�s-test with spaces.gz.bz2' for reading.
> 
> ```
> 
> 
> 
> Can beetlenaut and squished elf do a similar check? I know beetlenaut was having several other issues in Linux - not sure why Linux is okay for me but not him.

**Comment by Wedge009** [comment] 2017-05-11 04:19
@gfgtdf I reported this as Windows-only, then the_squished_elf reported it was happening in OSX. Only @beetlenaut reported this as an issue for Linux, but I can't be sure it really is across all platforms.

**Comment by gfgtdf** [comment] 2017-05-11 09:47
it just seemed od to me that this hada  the mscos label but not the windows label when the comment are mainly about osx. so i removed that label.


But also i'd be surprised it it was system dependent, this code here https://github.com/wesnoth/wesnoth/blob/1.13.7/src/save_index.cpp#L247 looks like it'd system independntly replace all spaces which underscore before attempting to read a file savefile.

**Comment by Wedge009** [comment] 2017-05-11 14:05
That might be part of the problem. For whatever reason Windows fails to pick up a file name with spaces but Linux doesn't seem to have an issue. I can't comment either way for OSX.

**Comment by CelticMinstrel** [comment] 2017-05-11 14:28
I haven't tested myself, but I would expect OSX to lean more towards Linux in general, since it's BSD-derived.

**Comment by gfgtdf** [comment] 2017-05-11 14:51
ohh i just noticed that the line i meantione daove still used the original as a fallback in case that it didn't find the file with the modified name.


@Wedge009  maybe you could give the same output that you gave for the linux build for the windows build too? just to see which names it actually tries to open.

**Comment by gfgtdf** [comment] 2017-05-11 14:58
ok i just tested this on windows and i could only reproduce this with files that contain both spaces and underscores in a single filenames, files that use onyl spaces or only underscores seem to be ok.

could you please check whethe the bahviour is the same on linux?

**Comment by Wedge009** [comment] 2017-05-12 13:18
I think you found it. On both Windows and Linux, I can load/delete save games with file names of only spaces, and only underscores. But for both OSs, I run into trouble when a file name has of both underscores and spaces. When I previously tested Linux, I must have had a file name with spaces but no underscores.

So yes, this issue does not appear to be OS-specific.

**Comment by gfgtdf** [comment] 2017-10-07 12:26
marked as  'regression' since te first comment said

> This only seems to be an issue in Windows, in current master. 1.12 in Windows is fine, Linux is also okay, with regards to both loading and deleting.

**Comment by CelticMinstrel** [comment] 2017-10-07 21:15
Why not just revert that code to translate between spaces and underscores? There's really no point in doing such a thing anyway.

**Comment by Arcanister** [comment] 2017-10-08 03:05
I think space should be translated to underscores in save dialog only. Reverse translation could be used to display saves, but when trying to access file functions should rely on untranslated version of name, so both should be kept. Trying to access various versions of name is not a good idea. What if somebody has both "DMsc1_replay.gz" and "DMsc1 replay.gz" ?
Also if underscores are translated to spaces in load dialog, perhaps spaces should be translated into something else, such as middle dot?

**Comment by CelticMinstrel** [comment] 2017-10-08 05:54
Absolutely. I don't think it's a good idea to translate underscores in filenames to spaces for display, but even if you do, you should definitely not assume all spaces in the result were underscores in the original.

**Comment by jyrkive** [comment] 2018-02-07 06:14
Vultraz says that this is more important than #2422, which has been marked as a blocker. Hence, this bug is also a blocker.

**Comment by Wedge009** [comment] 2018-02-07 09:27
Retesting at 057a5305, I find nothing has changed for my previous comments on this. For Windows, that is. For Linux, however, I am now getting the same result as in Windows. Bizarre.

As I did mention before, I considered this minor because Wesnoth does not create files with spaces in them. This situation only arises if the user names the save files with spaces. But I'll concede that Wesnoth should be able to handle this case more gracefully.

**Closed** 2018-02-07 19:36 UTC
Labels: Blocker, Bug, Regression, UI

**Comment by Wedge009** [comment] 2018-02-08 00:02
@jyrkive Thank you for this. I didn't see the display vs actual file name system was such a mess. At least this is working for me now - loading, load preview, and delete from load dialogue.
