### ISSUE TITLE
Scenario music does not play when loading saves

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2602] opened 2018-03-06 09:42 UTC
There's an issue in the sound code that prevents scenario music from playing when a game is loaded. Loading a start-of-scenario save works correctly, though.I think this has something to do with `sound::commit_music_changes`. `playsingle_controller::play_scenario` properly parses scenario music, but when `commit_music_changes` is called, it exists early at `sound.cpp:790` and the main menu music continues to play. ~~It's also reported that the scenario playlist does **not** begin playing after the currently playing track ends (though I did not confirm this first hand).~~

This issue also affects the MP Lobby. Despite `game_config::lobby_music` being set to `silence.ogg`, the main menu music never stops playing.

**Comment by jyrkive** [comment] 2018-03-06 09:45
The early exit in `sound.cpp:790` means that the main menu track is present in the current playlist. Obviously, it shouldn't be: there aren't exactly many scenarios which have the main menu music in their playlist.

It's expected behavior that the track doesn't change until the current track ends. That's how Wesnoth 1.13 has worked as long as I can remember (starting from summer 2016, if not earlier).

**Comment by Vultraz** [comment] 2018-03-06 10:09
No, I think it just means the track is marked as "play once". The "track is in list" exit is L796.

Perhaps we need an explicit fadeout call?

**Comment by jyrkive** [comment] 2018-03-06 10:17
Oh, right. I see.

An explicit fadeout call shouldn't be necessary: https://github.com/wesnoth/wesnoth/blob/master/src/sound.cpp#L723-L725

**Comment by Vultraz** [comment] 2018-03-06 10:32
Hmmmmm....I wonder if the problem is that there is no `immediate=yes` in any of the scenario tracks...

**Comment by jyrkive** [comment] 2018-03-06 10:33
Changing the music when loading a save has worked for a long time, though. This must be a recent regression, and I think it points towards some kind of saving bug - an extremely severe problem.

**Comment by Vultraz** [comment] 2018-03-09 14:13
I've determined that the playlists are at least properly constructed. The issue has something to do with what's being played.

**Comment by Vultraz** [comment] 2018-03-09 15:17
The bit about the scenario playlist not starting after the main menu track finishes appears to be false. Waiting for the main menu theme to finish in a DiD save then gives me the last track in the scenario playlist (`battle.ogg`).

**Comment by Vultraz** [comment] 2018-03-09 15:22
Also, this bug appears to function both ways. Scenario music doesn't stop when returning to titlescreen IF you loaded a scenario save. Starting the save normally, such as through the campaign menu, does result in scenario music correctly playing, AND the main menu music correctly starting again when quitting the game.

**Comment by jyrkive** [comment] 2018-03-09 18:38
> The bit about the scenario playlist not starting after the main menu track finishes appears to be false. Waiting for the main menu theme to finish in a DiD save then gives me the last track in the scenario playlist (battle.ogg).

In that case this isn't a bug. That's how Wesnoth 1.13 has worked since forever.

**Comment by Vultraz** [comment] 2018-03-10 02:49
Somehow that doesn't feel right...Are we sure it isn't a long-standing regression in 1.13?

**Comment by CelticMinstrel** [comment] 2018-03-10 02:59
The music system is certainly working the way it's designed to - if you set a new playlist without `immedate=yes`, the currently-playing track will continue to play to the end, and then the game will move onto the new playlist.

You could however make an argument that, when loading a saved game, the currently-playing track should be stopped to allow the scenario music to take over. Which would be what this issue is about. So... I'd argue that it's not invalid, but it certainly isn't a blocker either. I'm not even sure it would be a bug rather than an enhancement.

**Comment by gfgtdf** [comment] 2018-03-10 11:48
when loading a save the current track should be stopped and somethgin from the new list shodul be played instead. _Unless_ the currently playing track is also on the new playlist in which case it shodul finish the current track as if nothgin happened. The later is specialy important when loading a game from inside a game from the same scenario, you don't want an interrupotion of the music in that case.

**Comment by shikadiqueen** [comment] 2018-03-21 08:31
This is not how music used to work when loading saves in 1.12.x, therefore it *is* a regression.

1.12.x would instantly switch to the scenario's playlist (probably selecting a random track from the playlist if it had more than one entry, haven't checked that) upon loading a save. I do believe this behaviour did not always exist and may have been introduced during 1.9.x, but it doesn't change the fact that some of us do rely on it and don't want the title screen music or whatever else was playing before to keep playing over what we chose for our scenarios.

**Comment by Vultraz** [comment] 2018-03-21 09:41
7dea2b92abad957004e57030963dcb0f458286ac appears to be the cause.

**Comment by CelticMinstrel** [comment] 2018-03-21 16:08
What is GNA23065 that the commit claims to fix?

**Comment by sevu** [comment] 2018-03-25 00:46
Who has a local backup of gna :tada:

**Comment by Vultraz** [comment] 2018-03-25 00:48
There’s a copy on archive.org.

**Comment by sapientN3T** [comment] 2018-03-25 03:20
[music] unable to replace playlist without interrupting current track

"It should be possible to change the playlist without interrupting the current track by using immediate,append=no,no. Currently, doing so does cause an immediate switch to the new playlist. "

https://web.archive.org/web/20170204102655/https://gna.org/bugs/index.php?23065

**Comment by CelticMinstrel** [comment] 2018-03-25 05:12
At the moment I'm thinking the best fix is likely just to call `sound::stop_music()` as soon as you're committed to loading a game (so when you click the load button). That _would_ mean there's no music for the loading screen, but I can't think of a way around this.

**Comment by Vultraz** [comment] 2018-03-25 05:13
I have a local change that adds a `force` parameter to `commit_music_changes` that skips the `play_once` check. It seems to work as expected, though music doesn't stop until you enter the game itself.

**Comment by Wedge009** [comment] 2018-05-02 23:33
Personally, I like that there's no forced change on loading/exiting a saved game, I think I noticed this change some time ago. But I agree it is a regression and starting a new campaign does force a reset of the music to whatever the scenario specifies.

**Comment by shikadiqueen** [comment] 2018-05-21 00:46
Any progress?

**Comment by jyrkive** [comment] 2018-06-05 04:41
I'm taking this one.

**Closed** 2018-06-05 05:40 UTC
Labels: Audio, Bug, Confirmed, Regression

**Comment by Wedge009** [comment] 2018-06-05 07:59
Aside from the unwanted music change-on-**re**load that @shikadiqueen mentioned in #wesnoth-dev, I'm not sure if @Vultraz still wants the MP Lobby to have the MP Lobby music restored to silence.
