### ISSUE TITLE
[1.14] Mainline campaign "The Rise of wesnoth" error

### ISSUE THREAD

**Issue by FractalWire** [wesnoth/wesnoth#3022] opened 2018-05-04 22:33 UTC
Hi,

At the beginning of the scenario "Return to Oldwood" in the mainline campaign "The rise of Wesnoth", I've got the following error : 

![image](https://user-images.githubusercontent.com/16882885/39655773-c246de60-4ffb-11e8-9a29-f67696c29856.png)

**Comment by sevu** [comment] 2018-05-04 23:43
Can you tell us your screen resolution, this seems to be one factor.

**Comment by FractalWire** [comment] 2018-05-04 23:48
Ah, indeed. It only happens when I'm in windowed mode at 1280x737.
No problem when I'm fullscreen at 1280x800.

**Comment by dmontgrmry** [comment] 2018-05-05 23:15
I have been able to reproduce this bug with the resolutions that are in the table. Interestingly, however, the bug does not appear to be in the scenario `05_The_Oldwood`, even when `portraits/rithrandil.png` is replaced with `portraits/rithrandil-winter.png` in the .cfg file (under `side`). Furthermore, when replacing `portraits/rithrandil-winter.png` with `portraits/rithrandil.png` in `07_Return_to_Oldwood.cfg`, the bug occurs. If, instead however, `portraits/rithrandil-winter.png` is cropped to 500x669, the bug does not appear.

- 1280x737: reproduced, y=-20
- 1280x743: reproduced, y=-14
- 1280x755: reproduced, y=-2
-1280x757: unreproducible.

(pattern...)

This indicates, at least to myself, that there must be a bug in the WML for `07_Return_to_Oldwood.cfg` and scaling for the portraits.

**Comment by Wedge009** [comment] 2018-05-06 12:01
Just noting this is a duplicate of #2912. It certainly seems related to the unusually tall profile image for Rithrandil and certain resolution ratios/heights.

**Comment by sevu** [comment] 2018-05-21 13:43
Closing because of duplicate

**Closed** 2018-05-22 01:27 UTC
Labels: Bug, Campaign, Duplicate, Graphics, Stable 1.14, UI
