### ISSUE TITLE
All default campaigns have a difficulty listed, except for "Descent into Darkness"

### ISSUE THREAD

**Issue by Taschi120** [wesnoth/wesnoth#5902] opened 2021-06-27 16:55 UTC
### Game and System Information
Windows 10 x64, Battle for Wesnoth 1.14.17 downloaded via Steam.

### Describe the bug
All campaigns shipped with the game have a difficulty level and length listed in their description (e. g. "Novice level, 16 scenarios" for "Eastern Invasion"), except for Descent into Darkness

### To Reproduce
Click "Campaigns" in the main menu, then check the descriptions for the individual campaigns.

### Expected behavior
All campaigns should have difficulty level and length listed.

I am not 100% sure if this bug report is appropriate here because it is *technically* a problem with a piece of content rather than the core game.

**Comment by knyghtmare** [comment] 2021-06-27 17:00
![image](https://user-images.githubusercontent.com/5283677/123553150-62a7d100-d79b-11eb-9cc6-6aa480d83cdf.png)
Seems fine to me (1.15.14+dev)

**Comment by Taschi120** [comment] 2021-06-27 17:02
This is how it looks in 1.14.17:

![grafik](https://user-images.githubusercontent.com/5377412/123553207-1f893600-d77a-11eb-829d-36bbc75f9dc5.png)

Well, if it's already fixed on master, that's fine by me :)

**Comment by knyghtmare** [comment] 2021-06-27 17:04
https://github.com/wesnoth/wesnoth/blob/2bf650b571d4536930ee1420d4106d8030f12f11/data/campaigns/Descent_Into_Darkness/_main.cfg#L23-L25

The code seems fine for it (in 1.14 branch)
Maybe some newline thing?

**Comment by Taschi120** [comment] 2021-06-27 17:06
It's possible but several other campaigns have descriptions that take up significantly more than four lines, and all of them render fine.

**Comment by Taschi120** [comment] 2021-06-27 17:15
If the campaign selection window is getting overhauled in 1.15 anyway, it's fine by me if you just close this isse.

**Comment by stevecotton** [comment] 2021-06-27 17:30
Probably caused by #3443 (the last line of text isn't being displayed).

**Comment by Pentarctagon** [comment] 2021-06-27 18:52
1.14 also isn't planned to get another release at this point, so yeah, I'll go ahead and close this.

**Closed by Pentarctagon** 2021-06-27 18:52 UTC
