### ISSUE TITLE
movement_used does not work as expected

### ISSUE THREAD

**Issue by spixi** [wesnoth/wesnoth#4057] opened 2019-04-29 18:17 UTC
Modification of `movement_used` does not work as expected.

I created a modification, with the intention that units can move after their attack. However, setting movement_used to 0 does not have the expected effect.

Expected result
-----------
After an attack, there are still movepoints left and the unit’s orb is yellow.

Actual result
-----------
The unit’s orb is red. You can try to move the unit, but it will first move at the start of your next turn.

Testcase
-----------
```ini
#textdomain wesnoth-move_after_attack
[modification]
   id=move_after_attack
   name=_"Move After Attack"
   type=hybrid

   [event]
      name=recruit,recall,post advance,unit placed
      first_time_only=no
      [modify_unit]
         [filter]
            x,y=$x1,$y1
         [/filter]
         [object] 
               duration=forever
            [effect]
               apply_to=attack
               set_movement_used=0
            [/effect]
         [/object]
      [/modify_unit]
   [/event]

   [event]
      name=move_to
      first_time_only=no
	  [lua]
          code = <<
              local unit = wesnoth.get_variable("unit")
              wesnoth.fire("message",{message=unit.moves})
              wesnoth.fire("message",{message=unit.max_moves})
          >>
      [/lua]
   [/event]
   [event]
      name=attack
      first_time_only=no
	  [lua]
          code = <<
              local unit = wesnoth.get_variable("unit")
              wesnoth.fire("message",{message=unit.moves})
              wesnoth.fire("message",{message=unit.max_moves})
          >>
      [/lua]
   [/event]
[/modification]
```

**Comment by gfgtdf** [comment] 2019-04-30 00:42
Did you move the unit before attaing? Movement_used only effects the movement used by the attack itself and not prevent movement reset due to zoc which is part after of the movement to the enemy unit and not of the attack.

**Comment by spixi** [comment] 2019-04-30 06:38
So, is the movement also set to zero because of ZOC? That is not, what I expected. I have to test this with level 0 units like bats.

**Comment by spixi** [comment] 2019-04-30 06:43
By the way. The `attack` event happens after recalculating the number of attacks and the movement of the unit. Maybe a new `pre attack` event would be useful for modifications, which affect these values.

**Comment by gfgtdf** [comment] 2019-04-30 18:11
> So, is the movement also set to zero because of ZOC

yes, always keep in mind that from the engine pov "moving the unit near the victim" and "combat"  are two separate and not directly related actions even when the user issues them both together with just one click.

**Comment by spixi** [comment] 2019-04-30 20:11
Ok, that is strange. I did not know that a unit loses movement in the ZOC of another unit. I thought, this

**Comment by spixi** [comment] 2019-04-30 20:15
Is there a reason for that? I mean, you either move around that unit or if there is shroud, you are interrupted by the “press t to continue” message.

**Comment by soliton-** [comment] 2019-04-30 20:40
A reason for ZoC causing you to lose movement? That is basically how ZoC works, the unit should not be able to go further.

**Comment by jostephd** [comment] 2019-05-07 16:06
Closing since everything works as intended. @spixi, if you need help implementing that behavior you can ask on the [WML Workshop forum](http://forums.wesnoth.org/viewforum.php?f=21). And feel free to open a new issue requesting a `pre attack` event.

**Closed by jostephd** 2019-05-07 16:06 UTC
