### ISSUE TITLE
Pressing up or down while in an intro text for a scenario makes most of the 'text part' transparent (confirmed for windows 7 and 10)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3068] opened 2018-05-09 23:33 UTC
I'm talking about this:
![transparent](https://user-images.githubusercontent.com/39015360/39844802-4b48e27c-53f2-11e8-9185-71efa014eef5.png)

EDIT: Tabbing out and back in to wesnoth or just going forward or backwards in the text returns it to normal.

**Comment by ProditorMagnus** [comment] 2018-05-09 23:48
Looks like #2988.

**Comment by Wedge009** [comment] 2018-05-10 04:34
I notice that even using the left and right arrow keys to navigate the story text results in a momentary flash of maximum transparency through to the background. Using the mouse to click the arrow keys does not have this, so it may be a case of the text box reading the key input as a cursor movement or something like that.

**Comment by Vultraz** [comment] 2018-05-13 13:16
I can't reproduce this.

**Comment by Wedge009** [comment] 2018-05-13 13:44
I can confirm it happens on both Windows 7 and 10, 1.14.1 release.

**Comment by Vultraz** [comment] 2018-05-31 08:47
Still cannot confirm.

**Comment by Konrad22** [comment] 2018-05-31 09:17
I'm unable to confirm it for 1.14.2.

**Comment by Wedge009** [comment] 2018-05-31 10:39
It's still there in 1.14 branch as of ee638bc8 (1.14.2+dev).

1. Start a campaign (I just went with A Tale of Two Brothers).
2. Click the story text area (I don't remember having to do this previously but maybe I just missed that last time).
3. Press up/down to produce the transparency. Left/right flickers.

Repeating the above while skipping step 2 does not produce the issue. I confirm the above for Windows 7 and Linux.

**Comment by Vultraz** [comment] 2018-05-31 10:41
Ok, NOW I can repro it with step 2. This is... *weird*.

**Comment by Konrad22** [comment] 2018-05-31 10:56
@Wedge009 
Thanks for providing that missing step.
I can confirm it now once more for Windows 10.

**Comment by Vultraz** [comment] 2018-06-16 05:18
This is not an issue on master, so I might just leave it unfixed in 1.14.

**Comment by Wedge009** [comment] 2018-06-16 05:29
Is it because master is using a different rendering now?

I suppose that's fair - it's a fairly contrived situation to use both mouse and keys on the story screen.

**Comment by Vultraz** [comment] 2018-06-16 05:42
Yes, master's UI rendering has been quite changed. This kind of issue is a symptom of the "dirty widget" drawing paradigm, while master uses a "always redraw everything" method that does away with stuff like this.

So... yeah, actually, I'm closing this. Fixed on master.

**Closed by Vultraz** 2018-06-16 05:42 UTC
Labels: Bug, Confirmed, Stable 1.14, UI
