### ISSUE TITLE
Depcheck prompts for era selection when selecting mods in SP

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2229] opened 2017-11-22 05:19 UTC
See title. When you toggle a mod (both select and deselect are affected) in the SP campaign selection dialog, a prompt appears telling you you need to choose a compatible era and offers the Default era as the only choice.

**Comment by gfgtdf** [comment] 2017-11-24 01:22
hmm yes this sounds like a problem. Disabling the depcheck for sp would probably be rather easy, but i think that depcheck might be useful in sp soo for example if a mod i known not to work with a certain campaign the author of the mod coudl specifically disallow the mod for that one...   then again prroperly enabling depcheck for sp woudl requite fixing the select campaign gui code aswell whihc i'm currently not moptivated to so, i'm probably just going for disable it for sp.


also i removed the regression label since it's not a regression compares to 1.12 (since that one didnt't support mods for sp)

**Comment by Vultraz** [comment] 2017-11-24 02:01
What UI changes need to be made?

**Comment by gfgtdf** [comment] 2017-11-24 02:26
what i meant was just that the code in gui/dialogs/campaign_selection.hpp neds to be changed to change ui buttons/listsbox state accoridingly if the depcheck reverted a human made decision, (instead of just changing depcheck/create_engine whihc might be enough to fix this partcular issue but wouldn't make depcgheck work properly in sp)

**Comment by jyrkive** [comment] 2018-02-25 05:44
With dependency check disabled in SP, this is no longer a blocker.

**Comment by CelticMinstrel** [comment] 2018-02-25 16:56
I noticed recently that the default era has `type=hybrid`. That might explain why the depcheck is offering only that era. Of course, that doesn't really help the situation, as you're not supposed to be picking an era here _anyway_.

**Comment by gfgtdf** [comment] 2018-02-25 16:59
> With dependency check disabled in SP, this is no longer a blocker.

Ye, my actual plan was to close this one and open a  new issue for the current state

> I noticed recently that the default era has type=hybrid. That might explain why the depcheck is offering only that era. Of course, that doesn't really help the situation, as you're not supposed to be picking an era here anyway.

yes the the problem is not the only one selection is offered, it's that that dialog is shoiwn in the first place. The default era shoudl already be selected be default (since it is the only era) iirc.

**Closed** 2018-02-26 02:47 UTC
Labels: Bug, UI
