### ISSUE TITLE
playing death fadeout on scenario defeat

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2059] opened 2017-09-30 18:02 UTC
In the 2nd tutorial Scenario, when Galdrad, your Elvish Advisor, dies, his fadeout isn't played when he dies.
In case you changed Galdrad to belonging to side 1, it is played.

The WML looks like this:
https://github.com/wesnoth/wesnoth/blob/3df86a0f6cae6a924c148cc2179a320b6d5c6868/data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg#L1060-L1081

I thought it's maybe related to that the side 3 is defeated afterwards, but the results were the same with `victory_when_enemies_defeated=no` or `defeat_condition=never/always` for side 3.

Tested with real battle, not shift+k at 3df86a0
Edit: wanted to test with an older version, but since I have sdl2.0.6 I can't launch older versions anymore.

**Comment by gfgtdf** [comment] 2017-09-30 21:30
mabye you ahve show ai moves disabled in your preferences?

**Comment by sevu** [comment] 2017-09-30 21:38
I don't find the setting now, but I'm sure that's not the case. I see the enemy moving and the animations during the fight.

**Comment by gfgtdf** [comment] 2017-09-30 21:51
ok i tested this n i cannot confirm the "In case you changed Galdrad to belonging to side 1, it is played" part, ot me it it was never shown, unrelated to whihc side he belonged

**Comment by Wedge009** [comment] 2019-10-09 05:51
I wonder if it's because the failure scenario plays immediately on the loss of the critical unit and that overrides any unit death fading. I assume use of the Tutorial is just for your testing and this happens on any scenario/campaign.

**Comment by jostephd** [comment] 2019-10-09 22:01
I can't reproduce this in master. When Galdrad is killed by enemy units, his last breath line is spoken.

@Wedge009 Have you reproduced this? How? Note I edited the link in the OP.

**Comment by Wedge009** [comment] 2019-10-10 01:28
The 'last breath' dialogue plays, it's the fact that the unit disappears practically instantaneously rather than fading out as per normal. I check using the debug tools to switch sides and reduce HP to 1 and then attack (rather than using shift+k to debug kill).

**Comment by jostephd** [comment] 2019-10-10 01:49
Ah! Yeah, I can see that.

**Comment by Wedge009** [comment] 2022-07-13 21:14
Confirmed still present in 1.16.3 release, but resolved with 1.17.5+dev, possibly due to #6855.

**Closed by Wedge009** 2022-07-13 21:14 UTC
Labels: Bug, Confirmed, Graphics
