### ISSUE TITLE
Leadership in 1.16 has a bug

### ISSUE THREAD

**Issue by MXB2001** [wesnoth/wesnoth#6269] opened 2021-11-07 04:11 UTC
### Game and System Information
 - What version of the game are you running?
1.16.0

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 flathub

 - What OS are you running?
Linux Debian 9

### Describe the bug
When the leadership tag is used with a value set to something negative and cumulative is set to yes the value used is not the negative value but 0.

### To Reproduce

1. First..
```
#define ABILITY_NOCTURNAL
    [leadership]
        id=nocturnal
        name=_ "nocturnal"
        cumulative=yes
        value=25
        affect_self=yes
        [filter]
            [filter_location]
                time_of_day=chaotic
            [/filter_location]
        [/filter]
    [/leadership]
    [leadership]
        id=nocturnal
        cumulative=yes
        value=-25
        affect_self=yes
        [filter]
            [filter_location]
                time_of_day=lawful
            [/filter_location]
        [/filter]
    [/leadership]
#enddef
```

2. Then...
Run a test game with a unit that has this ability.

3. Lastly...
Observe that the damage during night gets the leadership bonus while during the day the -25% is not applied

### Expected behavior
For negative leadership values to work when cumulative=yes (it works when set to no - I have tested)

**Comment by Wedge009** [comment] 2021-11-07 07:34
I'm asking, not telling: is that how leadership is intended to work? This looks like a non-standard way to try to use it - I'm just wondering if negative values were necessarily considered in the design because there are often other issues with negative values (I'm thinking of #4232) as an example.

**Comment by newfrenchy83** [comment] 2021-11-07 11:39
I'm asking if this ability tested in 1.14 version?

**Comment by newfrenchy83** [comment] 2021-11-07 11:47
Why using cumulative=yes in leadership, when it is used in marksman specials, thhe highest value of cth is used(if base_value is greater_ than vlue of special, then base value applied), i think what it is the same here,  during the day, this is the time_of_day bonus who is applied when cumulative=yes because this is the bonus base value. For cumulative=no ,the this is final_value= tod_bonus + leadership_bonus but for cumulative=yes this is : if tod_bonus>leadership bonus then value=tod_bonus.

**Comment by newfrenchy83** [comment] 2021-11-07 12:40
like said in https://forums.wesnoth.org/viewtopic.php?t=55092 the bugs was fixed in 1.14 but be back in 1.16.

**Comment by newfrenchy83** [comment] 2021-11-07 13:00
i pull a PR for fix that.

**Comment by newfrenchy83** [comment] 2021-11-07 13:12
cumulative=yes is used for choice in default value or value of abilitie/special, but in leadership, default value is 0, this option is no suse in this case(in chance_to_hit the default value is the value of cth without special, before https://github.com/wesnoth/wesnoth/commit/7114174789e850bbd7829a353e7d885791c0a664#diff-eb9c8f8b8122951ad515f39be0e4d8550c4f22421024154f55bdef508de85897 cumulative tags don't usable in leadership, but now, it must be cumulative=no, or reverse partially this commit

**Comment by MXB2001** [comment] 2021-11-07 14:57
I believe someone was wondering why use cumulative? It is essential to work with regular mainline leaders. When it was set to no this custom ability and standard leadership did not stack as intended. Turning it on solved the problem which is why cumulative=yes is critical in this case. To answer some other queries Yes this is pretty much the only way to alter damage output via an ability instead of a weapon special and yes this always worked in 1.14. Also the Era of Magic uses negative leadership abilities extensively (just with cumulative=no)

**Comment by newfrenchy83** [comment] 2021-11-07 15:40
> 
> 
> I believe someone was wondering why use cumulative? It is essential to work with regular mainline leaders. When it was set to no this custom ability and standard leadership did not stack as intended. Turning it on solved the problem which is why cumulative=yes is critical in this case. To answer some other queries Yes this is pretty much the only way to alter damage output via an ability instead of a weapon special and yes this always worked in 1.14. Also the Era of Magic uses negative leadership abilities extensively (just with cumulative=no)

cumulative=yes work? In 1.16, 1.14 or both?

**Comment by newfrenchy83** [comment] 2021-11-07 16:17
i have another solution for don't have to use cumulative=yes.

`
#define ABILITY_NOCTURNAL
    [leadership]
        id=nocturnal
        name=_ "nocturnal"
        cumulative=no
        add=25
        affect_self=yes
        [filter]
            [filter_location]
                time_of_day=chaotic
            [/filter_location]
        [/filter]
    [/leadership]
    [leadership]
        id=nocturnal
        cumulative=no
        sub=25
        affect_self=yes
        [filter]
            [filter_location]
                time_of_day=lawful
            [/filter_location]
        [/filter]
    [/leadership]
`
NOw add and 'sub' can be used for what valeue was added or subbed to regular leadership.

**Comment by stevecotton** [comment] 2021-11-08 00:34
@MXB2001 do you still want this change after Ravana's suggestion in the forum thread?

While I'm glad that @newfrenchy83 has already made a PR, if we don't need to make a change then I think it's better not to.

**Comment by Pentarctagon** [comment] 2021-11-10 15:05
Also, looking at the https://wiki.wesnoth.org/AbilitiesWML documentation, it says:
> id: **this ability will not be cumulative with other abilities using this id**. Must be present if cumulative is anything other than 'yes'.

Given both abilities in the provided example have `id=nocturnal`, this sounds like it's actually the intended behavior?

**Comment by newfrenchy83** [comment] 2021-11-10 16:35
speaking of the documentation, I would like to point out some changes that should be made to the page https://wiki.wesnoth.org/AbilitiesWML


in the section Extra keys and tags used by the [resistance] / [leadership] ability, [filter_student] should not be mentioned, only [filter_weapon] and [filter_second_weapon] can be used.

In the section Extra tags and keys used by weapon special abilities: [filter_weapon] and [filter_second_weapon] do not exist independently, [filter_weapon] must be implemented in [filter_student], [filter_opponent], [filter_attacker] and [filter_defender] of the same way as in special weapons, [filter_student] replacing [filter_self]
For weapon special abilities with values, there is an overwrite_specials = one_side / both_sides which cancels all other abilities and weapons of the same type, one_side only cancels abilities / weapons on combatants, both_side also cancels weapons / abilities of the opponent that apply to the fighter affected by the ability with the overwrite_special key.

and finally in the section The [abilities] tag ,: plagues, heal_on_hit, and swarm are supported now (since 1.15.3), but when a unit with the special weapon [plague] is affected by an ability [plague] it is the weapon that is taken into account (unless overwrite_specials keys is used)

I don't know who administers this page, could you forward it?

**Comment by Pentarctagon** [comment] 2021-11-10 16:39
No one really administers this particular page specifically.  If you want an account to make the updates, the procedure for requesting one is at https://forums.wesnoth.org/viewtopic.php?t=43815

**Comment by Pentarctagon** [comment] 2021-11-16 19:15
Barring further comments, I am leaning towards closing this issue, given it does follow the documented functionality and there are other ways to achieve the same thing.

**Comment by Wedge009** [comment] 2021-11-16 21:50
I don't really have a strong opinion on that either way, but I note #6270/#6281 are still open. If this is closed that should probably mean they close too.

**Comment by vgaming** [comment] 2021-12-04 22:08
The two referenced issues are now closed. This described scenario also seems to be working as intended (as documented). I'd agree on closing.

**Closed** 2021-12-04 22:24 UTC
Labels: Bug, WML, Units
