### ISSUE TITLE
some minor graphic bugs

### ISSUE THREAD

**Issue by dust5114** [wesnoth/wesnoth#2596] opened 2018-03-05 07:07 UTC
~~1. Label of button "back to list/add-on details"  doesn't change to "add-on details" after mod installation from "+shield" button, it remains "back to list" .~~
2. Pop up label on slider "maximum auto saves " in general menu overlays shown number of that value.
~~3. Touchpad scrolling is laggy in help, thou mouse wheel is not. In 12.6 there is no problem. Using Synaptics touchpad.~~
4. After alt+tab from fullscreen, application disappears from taskbar after reloading save file.
5. May be it's not a bug, but save reloading times are a lot longer vs 12.6, where they were almost instant.
Version  1.13.11, win 8.1, prebuild installer.

**Comment by jyrkive** [comment] 2018-03-05 07:29
Please don't report multiple bugs in one bug report.

**Comment by dust5114** [comment] 2018-03-05 16:53
Version  1.13.11

**Comment by dust5114** [comment] 2018-03-05 18:37
@jyrkive  Should i leave it like this, or break  to 5 issues?

**Comment by AI0867** [comment] 2018-03-05 21:10
#3 is probably "smooth scroll" causing far too many scroll events. You might file a bug as scrolling not being performant enough, but the root cause is your touchpad driver.

**Comment by jyrkive** [comment] 2018-03-05 21:16
You can leave this issue. Just don't do it again in the future.

**Comment by AI0867** [comment] 2018-03-06 08:38
I don't really know. I simply have plenty of issues in other programs from my own touchpad's "smooth scroll".

**Comment by jostephd** [comment] 2019-10-11 01:01
>  2. Pop up label on slider "maximum auto saves " in general menu overlays shown number of that value.

I don't think this is a problem.

> 3. Touchpad scrolling is laggy in help, thou mouse wheel is not. In 12.6 there is no problem. Using Synaptics touchpad.

I take it you do have smooth scroll enabled, so I'll mark this as resolved.

> 4. After alt+tab from fullscreen, application disappears from taskbar after reloading save file.

I don't understand the instructions. What exactly do you do, and in what order?

> 5. May be it's not a bug, but save reloading times are a lot longer vs 12.6, where they were almost instant.

Just to be sure, did you compare apples to apples here? I.e., did you compare 1.12 and 1.14 on the same computer, on savefiles of the same campaign and scenario? (Not same playthrough, just same scenario)

**Comment by Wedge009** [comment] 2019-10-14 04:17
I'm not sure what 2 is about - is there an expectation that the value of the slider should also be shown in the pop-up/tool-tip? If so, I also agree it's not an issue.

Agree 4 is not that clear.

I wonder what is meant by 'a lot longer' in 5. Agree would need more information/testing there to get some objective comparisons.

**Comment by jostephd** [comment] 2019-10-14 04:31
> I'm not sure what 2 is about - is there an expectation that the value of the slider should also be shown in the pop-up/tool-tip? If so, I also agree it's not an issue.

I don't think there's such an expectation, but that's not what 2 is saying. The dialog shows the value of the slider above the slider. When the tooltip is shown, it is drawn over the value of the slider, hiding it. That's what 2 is saying.

> Agree 4 is not that clear.

> I wonder what is meant by 'a lot longer' in 5. Agree would need more information/testing there to get some objective comparisons.

@dust5114 Could you provide additional info on 4 and 5 please?

**Comment by Wedge009** [comment] 2019-10-14 08:07
If that's what 2 is about, I can't confirm it on 1.14.9, it may be resolved.

**Comment by jostephd** [comment] 2019-10-14 22:47
I can reproduce it, but I think it's a won't fix. The "Maximum auto-saves: " text and the slider are two separate widgets, and the label can be placed at any location with relation to the slider (above / below / to the side).

Let's wait for clarification on 4 and 5.

**Comment by Wedge009** [comment] 2019-10-21 10:55
It doesn't look like we're going to get any further information from @dust5114. Do we need to keep this open?

**Comment by soliton-** [comment] 2019-10-21 12:13
I don't think so. It can always be re-opened once further information comes in.

**Comment by Wedge009** [comment] 2019-10-21 12:25
Agreed, thanks.

**Closed by Wedge009** 2019-10-21 12:25 UTC
Labels: Bug, Needs more info, Regression, UI

**Comment by dust5114** [comment] 2019-10-21 15:14
About 4: just tested 14.9 and the issue is gone.  
About 5: yes, i'm testing the same map, same scenario. it's not a big deal, but  on my old laptop 1.12 loading savefile took smth like less then 1 second. Newer versions take 2-4 seconds to load. Just tested it running simultaneous on that machine.

**Comment by Wedge009** [comment] 2019-10-21 22:23
Thanks for responding. Good to know 4 is okay. About 5: I assume you're manually timing with a stopwatch or something like that? I know the studies that talk about web pages taking longer than a second to load are an issue (gee, we're collectively so impatient) - is 5 seconds that difficult for you? You mention old laptop so it could just be an increase in CPU and/or IO load.

**Comment by soliton-** [comment] 2019-10-22 07:22
I think more important would be the difference between 1.12 and 1.14 since in principle not that much should have changed for loading a game. Ideally that should be tested by timing and averaging multiple runs of as similar saves as possible. Not simultaneously where we have no idea how the OS schedules the processes.

**Comment by jostephd** [comment] 2019-10-22 08:07
> Ideally that should be tested by timing and averaging multiple runs of as similar saves as possible

Rather than saves, I'd suggest to time starting a particular campaign. Too bad --campaign-skip-story isn't in 1.12...

**Comment by dust5114** [comment] 2019-10-22 09:19
On the topic of loading times:
As i said, it's not a big deal. Laptop is smth from 2008-2009 intel M i3 2 cores. It was just a hint on may be some lost optimisation. May be new graphic engine loads a little slower, idk. Again, the difference is only seconds, not a big deal. But the difference is consistent, it is not some fluke due OS handling processes. 1.12-almost instant 1.14- takes a little bit of time(2-3 seconds). Saves, states of map were identical in testing (2 turns at the start of campaing), no antivirus and spyware running, clean booted system.

P.S. Thank you guys for working on this game, you are doing really good work.
