### ISSUE TITLE
Crash when loading save file after defeat in local multiplayer game

### ISSUE THREAD

**Issue by IceTyp** [wesnoth/wesnoth#5097] opened 2020-08-23 17:08 UTC
### Game and System Information
-1.15.4
-Steam
-Ubuntu 20.04

### Describe the bug
When I tried to load a save file after my leader is defeated in a local multiplayer game, BfW crashes.

### To Reproduce
1. Start a local multiplayer game. (I tried it with World Conquest 1p and also with a Random map against the AI.)
2. Let your leader be defeated.
3. After the Defeat message appears, press space
4. Press Ctrl + o to load a game.
5. Choose any save file and press Enter to load it.

The game will crash.

### Savefiles
Alternatively to step 1, you could also open this save file, end your turn, and proceed with step 2.
[Random map-Auto-Save6.gz](https://github.com/wesnoth/wesnoth/files/5114398/Random.map-Auto-Save6.gz)

### Additional context
I have not tried this for non-random maps. 
I could not reproduce this bug in the campaign DiD.

**Comment by Pentarctagon** [comment] 2020-08-23 18:39
Ouch.  An even simpler way to reproduce:
* Load the save game
* Quit to the main menu
* Load the same save game
* Wesnoth crashes

The crash is caused by the assert [here](https://github.com/wesnoth/wesnoth/blob/5e5df83db6937f7e140003104c66a3020e4934e1/src/saved_game.cpp#L658) being triggered.

A bisect points to commit 5759404121215730cbd4ec899061317923e0ec6e being the cause.

The backtrace is [here](https://pastebin.com/wUtpjbdE).

**Comment by Pentarctagon** [comment] 2020-08-23 19:29
As another note, loading a save from within an ongoing game (aka not after being defeated or after going back to the main menu) does not trigger the crash.

**Comment by Pentarctagon** [comment] 2020-08-26 14:31
Fixed in 5b5a60d0c4969260bdd0bfea59a5e12f074e13d6.

**Comment by stevecotton** [comment] 2020-08-27 02:23
Reopening - 5b5a60d makes the WML unit tests assert.

The Travis build of 5b5a60d itself failed before that point, due to the utf-8 check on the missing `RELEASE_NOTES`. The crash in the unit tests is visible in https://travis-ci.com/github/wesnoth/wesnoth/jobs/378132819

```
Thread 1 "wesnoth" received signal SIGABRT, Aborted.
#3  0x00007ffff709ef36 in __GI___assert_fail (assertion=0x555556072c68 "!\"cannot figure out scenario_id\"", file=0x55555604094e "src/saved_game.cpp", line=658, function=0x555556072c38 "std::string saved_game::get_scenario_id()") at assert.c:101
#4  0x0000555555dc1343 in saved_game::get_scenario_id[abi:cxx11]() ()
#5  0x0000555555f2ce87 in game_launcher::load_game() ()
#6  0x0000555555fbf2b9 in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#7  0x00005555557fae58 in main ()
```

**Comment by gfgtdf** [comment] 2020-08-28 09:48
try this https://github.com/wesnoth/wesnoth/commit/d1f56287bdb60bbe4e4c09840b7844dad27c688b

**Comment by Pentarctagon** [comment] 2020-08-28 14:10
It looks like that worked and it's just travis doing its thing where it hangs trying to make the cache (all four that errored did so for the same reason - no output displayed for 10 minutes - at the same point in the job). I've restarted the errored jobs and hopefully they should pass now.

**Closed** 2020-08-28 18:05 UTC
Labels: Blocker: Point, Bug, Engine

**Comment by stevecotton** [comment] 2020-08-28 19:10
Looks good, thanks.
