### ISSUE TITLE
Feature request: in-game message log for reviewing past dialogue

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#6579] opened 2022-03-24 23:04 UTC
### Describe the desired feature

Many text-heavy games these days (Ace Attorney, Dragalia Lost, Fire Emblem: Three Houses) come with message log features that allow a player to review past pieces of dialogue, in case they clicked through a message too fast. I can add screenshots showing what they look like later. This would be helpful for players who get stuck because they missed reading something. On Discord @nemaara said this would be a nice feature to have, so I'm opening an issue to track it.

**Comment by Wedge009** [comment] 2022-03-24 23:12
I know what you're referring to - I thought this has been requested/recorded before, though.

**Comment by CelticMinstrel** [comment] 2022-03-24 23:48
I also thought this had been requested.

**Comment by cooljeanius** [comment] 2022-03-24 23:48
> I know what you're referring to - I thought this has been requested/recorded before, though.

yeah I tried searching "message log" but that turned up so many results that I wasn't able to tell which were relevant; if you can find an existing bug to close this as a duplicate of, please do

**Comment by Wedge009** [comment] 2022-03-24 23:50
Closing as duplicate of #1835. But thanks for recording this.

**Closed by Wedge009** 2022-03-24 23:50 UTC
Labels: Enhancement, UI
