### ISSUE TITLE
GameCrashed during credits after liberty campaign (game still understood I finished the campaign)

### ISSUE THREAD

**Issue by TheFlamelet** [wesnoth/wesnoth#8218] opened 2024-01-06 08:07 UTC
### Game and System Information

- **1.1724** 
- **Not steam**
- **Build info:**
- **Windows 10**

### Description of the bug

Just a game crash

### Expected behavior

No need to crash. Send me to main menu.

### Additional context

[wesnoth-20240106-101350-2947182250.log](https://github.com/wesnoth/wesnoth/files/13848826/wesnoth-20240106-101350-2947182250.log)
[wesnoth-20240106-084619-2064746378.log](https://github.com/wesnoth/wesnoth/files/13848827/wesnoth-20240106-084619-2064746378.log)

**Comment by Pentarctagon** [comment] 2024-01-06 16:36
Sounds like #7395?

**Comment by TheFlamelet** [comment] 2024-01-06 18:53
is it possible the reason is that my game directory is uncompressed unto desktop instead of C:\programs?
might that be a reason for the crashes and underwhelming performance?

**Comment by Wedge009** [comment] 2024-01-09 23:24
I don't think the file location should make a difference. 'Underwhelming performance' is subjective and can't be diagnosed without more details/information - keep in mind GPU is a factor for 1.17 releases.

Closing as duplicate of #7395. If someone determines this is a separate issue, then this can be re-opened.

**Closed by Wedge009** 2024-01-09 23:24 UTC
Labels: Bug, Duplicate, Engine
