### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by Phosphoraptor97** [wesnoth/wesnoth#6333] opened 2021-11-25 04:20 UTC
### Game and System Information
 - What version of the game are you running?
 1.16.1 from forum pin
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 Sourceforge
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - What OS are you running?
 Windows 10

### Describe the bug

Game does not start, nothing happened when i click run even as administrator

### To Reproduce

I uninstalled an older 1.14 version then reinstalled this version.

### Savefiles
If applicable, attach savefiles to help explain your problem. (To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.
These did not produce any logs in C:\Users\[Username]\Documents\My Games\Wesnoth1.14\logs

**Comment by Pentarctagon** [comment] 2021-11-25 04:32
>  These did not produce any logs in C:\Users\[Username]\Documents\My Games\Wesnoth1.14\logs

You'd need to be looking in the `Wesnoth1.16` folder.

**Comment by Phosphoraptor97** [comment] 2021-11-25 04:52
i didnt have that folder show up

**Comment by Pentarctagon** [comment] 2021-11-25 05:26
Did 1.16 install?

**Comment by Phosphoraptor97** [comment] 2021-11-25 05:43
yes

**Comment by Pentarctagon** [comment] 2021-11-25 05:44
Where?

**Comment by Phosphoraptor97** [comment] 2021-11-25 05:44
Is it the game folder or the documents folder?

**Comment by Phosphoraptor97** [comment] 2021-11-25 05:45
I have the game folder but not the documents one

**Comment by Pentarctagon** [comment] 2021-11-25 05:45
What do you mean by the game folder?

**Comment by Wedge009** [comment] 2021-11-25 05:45
I just double-checked - that indeed should be the default directory for Windows: `C:\Users\<user>\Documents\My Games\Wesnoth1.16\`.

A reminder that this isn't a support forum - and if you don't provide the information we need, we can't help you. If you can, I suggest running from the command-line, see if any messages show up in standard output.

**Comment by Phosphoraptor97** [comment] 2021-11-25 05:45
One with the game files in it

**Comment by Phosphoraptor97** [comment] 2021-11-25 05:46
documents has the saves etc

**Comment by Pentarctagon** [comment] 2021-11-25 05:46
Where is the game folder, and what are you trying to run?

**Comment by Phosphoraptor97** [comment] 2021-11-25 05:47
C:\Program Files\Battle for Wesnoth 1.16.1
wesnoth.exe

**Comment by Phosphoraptor97** [comment] 2021-11-25 05:48
> I just double-checked - that indeed should be the default directory for Windows: `C:\Users\<user>\Documents\My Games\Wesnoth1.16\`. (Edit: This is for user files - save games, logs, etc.)
> 
This folder didnt show up when i installed, it still has the 1.14 one

**Comment by Pentarctagon** [comment] 2021-11-25 05:49
* Open the start menu and type `cmd`.
* Start `cmd.exe`.
* Type `cd "C:\Program Files\Battle for Wesnoth 1.16.1"` and hit enter.
* Type `wesnoth.exe` and hit enter.

What shows up after doing so?

**Comment by Phosphoraptor97** [comment] 2021-11-25 05:51
nothing

**Comment by Pentarctagon** [comment] 2021-11-25 05:52
Please post a screenshot of cmd.exe after having done the above steps.

**Comment by Phosphoraptor97** [comment] 2021-11-25 05:52
![image](https://user-images.githubusercontent.com/65775637/143387189-5fe90a18-8d5c-409d-a1ac-e449686d643b.png)

**Comment by Pentarctagon** [comment] 2021-11-25 05:54
What does running `wesnoth.exe --report` display on cmd.exe?

**Comment by Phosphoraptor97** [comment] 2021-11-25 05:56
========= BUILD INFORMATION =========

The Battle for Wesnoth version 1.16.1 x86_64
Running on Microsoft Windows 10 20H2 (10.0.19042) x86_64
Distribution channel: SourceForge

Game paths
==========

Data dir:        C:\Program Files\Battle for Wesnoth 1.16.1
User config dir: C:\Users\USER\Documents\My Games\Wesnoth1.16
User data dir:   C:\Users\USER\Documents\My Games\Wesnoth1.16
Saves dir:       C:\Users\USER\Documents\My Games\Wesnoth1.16\saves
Add-ons dir:     C:\Users\USER\Documents\My Games\Wesnoth1.16\data\add-ons
Cache dir:       C:\Users\USER\Documents\My Games\Wesnoth1.16\cache

Libraries
=========

Boost:             1.74
Lua:               5.4.2
OpenSSL/libcrypto: 1.1.1i (runtime 1.1.1i)
Cairo:             1.17.4 (runtime 1.17.4)
Pango:             1.48.0 (runtime 1.48.0)
SDL:               2.0.12 (runtime 2.0.12)
SDL_image:         2.0.5 (runtime 2.0.5)
SDL_mixer:         2.0.4 (runtime 2.0.4)

Features
========

Lua console completion:       yes
Win32 notifications back end: yes

Current video settings
======================

Graphics not initialized.

Current audio settings
======================

Audio not initialized.

Installed add-ons
=================

No add-ons installed.

**Comment by Pentarctagon** [comment] 2021-11-25 05:59
And `C:\Users\USER\Documents\My Games\Wesnoth1.16` still doesn't exist?

**Comment by Phosphoraptor97** [comment] 2021-11-25 06:01
Ok its there now

**Comment by Phosphoraptor97** [comment] 2021-11-25 06:02
game still doesnt start

**Comment by Pentarctagon** [comment] 2021-11-25 06:03
What does `wesnoth.exe --log-debug=all` output?

**Comment by Wedge009** [comment] 2021-11-25 06:04
Was going to suggest checking if maybe directory permissions is an issue or not. But since the directories are there now - do you still have nothing recorded in the logs?

Also, it may be worth double-checking the integrity of installer you have downloaded: check-sums are listed at https://wiki.wesnoth.org/Download#Stable_.281.16_branch.29

**Comment by CelticMinstrel** [comment] 2021-11-25 06:11
> * Open the start menu and type `cmd`.
> 
> * Start `cmd.exe`.
> 
> * Type `cd "C:\Program Files\Battle for Wesnoth 1.16.1"` and hit enter.
> 
> * Type `wesnoth.exe` and hit enter.

This, but replace the last step by `wesnoth.exe --wconsole`.

**Comment by Phosphoraptor97** [comment] 2021-11-25 06:15
No logs still

C:\Program Files\Battle for Wesnoth 1.16.1>wesnoth.exe --wconsole

C:\Program Files\Battle for Wesnoth 1.16.1>Battle for Wesnoth v1.16.1 x86_64
Started on Thu Nov 25 14:14:43 2021

Automatically found a possible data directory at C:\Program Files\Battle for Wesnoth 1.16.1
20211125 14:14:43 error display: Could not initialize SDL_video: directx not available
Could not initialize video.

Video initialization failed

Exiting.

C:\Program Files\Battle for Wesnoth 1.16.1>

**Comment by Wedge009** [comment] 2021-11-25 06:16
Well, that explains a lot. I don't suppose you can confirm if other DirectX and/or SDL-based applications work or fail on your PC? Sounds like this may not be related to Wesnoth.

**Comment by Phosphoraptor97** [comment] 2021-11-25 06:22
I could run Civ 5 from DX9 to DX 10/11

**Comment by Phosphoraptor97** [comment] 2021-11-25 06:23
Also tried installing latest DirectX, didnt change anything

**Comment by Pentarctagon** [comment] 2021-11-25 06:26
What happens if you run `set SDL_VIDEODRIVER=windows` before doing `wesnoth.exe --wconsole`?

**Comment by Phosphoraptor97** [comment] 2021-11-25 06:30
the game can be run from the command, but running wesnoth.exe alone still does nothing

**Comment by Pentarctagon** [comment] 2021-11-25 06:32
So did it work when first running `set SDL_VIDEODRIVER=windows`?

**Comment by Phosphoraptor97** [comment] 2021-11-25 06:32
yes

**Comment by Wedge009** [comment] 2021-11-25 06:42
https://wiki.libsdl.org/FAQUsingSDL states that `SDL_VIDEODRIVER` should only be `windows` for SDL2 on Windows OS. So it sounds like there may be some other SDL-based application you're using that might be setting it to something else. It might be worth trying to run Wesnoth after a complete reboot and seeing if there are still problems.

BTW, it's worth noting that Wesnoth 1.14 also uses SDL2, so the older version should have had the same issue.

Either way, it seems you have your solution and we've determined the problem isn't specifically with Wesnoth itself, so closing.

**Closed by Wedge009** 2021-11-25 06:42 UTC
Labels: Bug, Needs more info, Engine

**Comment by Pentarctagon** [comment] 2021-11-25 06:44
For simplicity I'd suggest creating a .bat file containing just:
```
set SDL_VIDEODRIVER=windows
wesnoth.exe
```
and run that instead of wesnoth.exe directly.
