### ISSUE TITLE
Crash when toggling Windows desktop view

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7438] opened 2023-03-06 16:39 UTC
### Game and System Information

The Battle for Wesnoth version 1.17.13 x86_64
Running on Microsoft Windows 7 Service Pack 1 (6.1.7601) x86_64
Distribution channel: Steam

Libraries
=========

Boost:             1.80
Lua:               5.4.4
OpenSSL/libcrypto: 1.1.1s (runtime 1.1.1s)
Cairo:             1.17.6 (runtime 1.17.6)
Pango:             1.50.11 (runtime 1.50.11)
SDL:               2.24.1 (runtime 2.24.1)
SDL_image:         2.6.2 (runtime 2.6.2)
SDL_mixer:         2.6.2 (runtime 2.6.2)

Features
========

Lua console completion:       yes
Win32 notifications back end: yes

Current video settings
======================

SDL video drivers:        [windows] dummy
Window size:              1920x1080
Game canvas size:         1920x1080
Final render target size: 1920x1080
Screen refresh rate:      60
Screen dpi:               96.00x96.00
Renderer:                 direct3d (hw)
Maximum texture size:     16384x16384
VSync:                    on

Current audio settings
======================

SDL audio drivers:  [wasapi] directsound
Number of channels: 2
Output rate:        48000 Hz
Sample format:      signed 16 bit little-endian
Sample size:        4096 bytes

### Description of the bug

When you do alt+tab to desktop on any moment, the game crashes. This only happens with the game configured to fullscreen and when changes to desktop, not to any other window or program.
![imagen](https://user-images.githubusercontent.com/40789364/223174348-25cd11e7-18b9-47d0-be13-0e9aceffea88.png)

### Steps to reproduce the behavior

- Enter the game on fullscreen
- Do alt+tab and consecutive tab until you select dektop
- APPCRASH

### Additional context
Reported first on the forum:
https://forums.wesnoth.org/viewtopic.php?p=680202#p680202

**Comment by Wedge009** [comment] 2023-03-07 22:38
Marking as confirmed only because this is from a separate report on the forums and Toranks is able to replicate it.

I have tested both the 1.17.13 release (downloaded from sourceforge.net) and my MSVC/cmake-compiled builds from 1.17.13+dev @ 1bbce8a610f72f98e2cac22c564a697e689b1d21. Tested both Windows 7 and 10, and also made sure the program _started_ in full-screen mode, not just switching to full-screen after starting in windowed mode. I cannot replicate this anywhere. Just for the sake of it, I also checked on Linux - nothing.

Is it possible it's specific to a Steam launch? As far as I know, 'full-screen' in Wesnoth is just a borderless window set to display at the full resolution of a given monitor, so as @Pentarctagon said in the forum thread, there really isn't anything different that Wesnoth is doing outside of making the relevant call to SDL. On the other hand, if this only happens when launched from Steam, maybe the Steam overlay is doing something weird?

**Comment by Wedge009** [comment] 2023-03-08 00:04
Okay, I completely missed the part about specifically selecting the Windows 7 desktop 'window'. I don't see any 'desktop' option in Windows 10, so this looks specific to Windows 7.

**Comment by Toranks** [comment] 2023-03-08 00:13
Just in case, this problem occurs without steam started. Although I have downloaded it from steam, I don't have steam started (not even in background), I start the executable of wesnoth.exe directly.

**Comment by Wedge009** [comment] 2023-03-08 00:17
Yeah, it's clearly not Steam-related now that I can see how to replicate it. It may not be an issue in Wesnoth as 1.16.8 release says the 'fault' is in SDL2.dll (although I don't know why it thinks the application version is 1.16.3...)
![image](https://user-images.githubusercontent.com/13679322/223586011-5000e940-05d4-4c1e-bcfb-0ec1f3289e0f.png)

**Comment by Wedge009** [comment] 2023-03-08 01:20
While Windows 10 doesn't have a desktop view option in the Alt-Tab window switching functionality, the issue can be replicated there by using the Windows+D short-cut. There's no crash dialogue, however, Wesnoth simply disappears.

**Comment by Wedge009** [comment] 2023-03-08 01:36
The problem is a divide-by-zero exception occurring in `video::update_framebuffer()`:
https://github.com/wesnoth/wesnoth/blob/bf5befcd5e8cb97fbbd35bbf598358b8a8816b47/src/video.cpp#L229-L234
`osize` (I'm guessing it's meant to represent output size) is (0,0) when Windows desktop view is toggled. Thus, even if I clamp `max_scale` to `preferences::min_pixel_scale` after this code snippet, there is just another divide-by-zero issue somewhere else further down the code, because it's trying to render to a zero-sized frame.

But this code is for 1.17.x, so why is the issue also happening for 1.16.x? `sdl::window::get_output_size()` is the same for both 1.17 and 1.16, so it may be for the same reason that a (0,0) is being returned. (I can't debug 1.16 Windows builds due to #7217 so I can't check right now.)
https://github.com/wesnoth/wesnoth/blob/bf5befcd5e8cb97fbbd35bbf598358b8a8816b47/src/sdl/window.cpp#L107-L113

It turns out that `SDL_GetRendererOutputSize()` only starts returning (0,0) when in Windows desktop view (as opposed to the application window just being minimised) only from SDL 2.24.0 onwards. I was prompted to investigate this when I noticed that release 1.17.7, which is packaged with SDL 2.0.22, did _not_ exhibit the crash, yet it does include the pixel scaling code in `update_framebuffer()`. Similarly, I noticed 1.16.8 release, like 1.17.13 release, is packaged with SDL 2.24.1.

https://wiki.libsdl.org/SDL2/SDL_GetRendererOutputSize does not show any indication of when/how a (0,0) result might be given. But given that a non-zero result seems to be returned for SDL 2.0.22 and (0,0) is returned from 2.24.0 onwards, I wonder if it's an issue - intentional or otherwise - with `SDL_GetRendererOutputSize()`.

**Comment by Wedge009** [comment] 2023-03-08 01:47
I just made a quick check: when SDL_GetRendererOutputSize returns (0,0) for the width/height, it's also returning 0 indicating no error conditions.

**Comment by Wedge009** [comment] 2023-03-08 01:56
Marking as upstream for now, since simply switching to SDL 2.0.22 removes the issue. Of course, using older SDL will re-introduce #4508 - it seems like there's been some internal overhaul of Windows window handling starting with SDL 2.24.0.

**Comment by Pentarctagon** [comment] 2023-03-08 03:05
Has the issue been reported upstream?

**Comment by Wedge009** [comment] 2023-03-09 22:54
@Pentarctagon SDL team has put in place a work-around to return the last known dimensions when a Windows application is in this situation (Windows desktop view active), to be included in 2.26.5 release scheduled around 1st April. I grant this isn't a crippling bug (unless one happens to be fond of using Windows desktop view), but what's involved with bumping Windows builds to a newer SDL? Is it waiting for `vcpkg` to pick up SDL 2.26.5 and then updating our 'baseline' accordingly? Is it acceptable to leave other platforms alone with respect to their SDL dependency?

**Comment by Pentarctagon** [comment] 2023-03-10 00:15
It pulls in whatever is available in the msys2 release that's used for the docker image.

**Comment by Wedge009** [comment] 2023-03-10 00:50
So it may be a while before it becomes available, then.

**Comment by Pentarctagon** [comment] 2023-03-10 02:15
Updating it isn't hard and it seems like they keep pretty up to date with the SDL2 versions if they've already gotten to 2.24, so I assume it won't be more than a month or two after the fix gets to SDL2.

**Comment by Wedge009** [comment] 2023-04-10 05:23
It looks like the recently released SDL 2.26.5 doesn't have this issue. I compiled master @ 39deda9a0402483c287818b3150aae4969eaa114 and just dropped their binary to the working directory and I wasn't able to replicate the crash. I re-confirmed the crash with their SDL 2.26.4 DLL.

**Comment by Pentarctagon** [comment] 2023-10-19 00:36
Can this be closed then?

**Comment by Wedge009** [comment] 2023-10-19 01:04
Wesnoth is still packaging SDL 2.26.3 - at least last time I checked a few days ago.

**Comment by Pentarctagon** [comment] 2023-10-19 01:11
Ah, alright. It should be fixed as part of #7925 then, since the msys2 image needs to be updated for that anyway (whenever a new version of msys2-installer is released).

**Closed** 2024-02-23 12:34 UTC
Labels: Bug, Confirmed, Upstream issue, Windows, Engine
