### ISSUE TITLE
map editor: broken Undo for "items"

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2306] opened 2017-12-20 19:11 UTC
Steps to reproduce:
* start wesnoth v1.13.10+dev (19c08e77-Clean)
* open map editor, create new scenario
* choose "items" editor (icon that looks like a box on the right middle)
* place any items

Expected at this point: <strike>you can save your scenario</strike> you can undo placing items
Actually: you can't, wesnoth does not recognize that you changed anything (therefore saving doesn't make sens, according to wesnoth)

Steps (continued):
* select label editor, click to place a label and then cancel. You'll see the "undo" action appearing.. But it won't work

Steps (alternative):
* select label editor, click to place a label and then cancel. Click "partial undo". Map editor will say "Fatal Error" and close itself.

EDIT: fixed typo, see the <strike>strike-through</strike> text.

**Comment by Wedge009** [comment] 2017-12-21 05:50
Which branch is that? master looks a bit different, looks like it diverges from your 19c08e7 branch at b7881a0e.

Anyway, running current master, fd656b61, I was able to save my scenario after placing items (I checked the file on disk as well) and had no trouble with placing labels or undoing label placement.

**Comment by vgaming** [comment] 2017-12-23 19:56
@Wedge009 I've re-run this on v1.13.10+dev (393ac9bd-Clean).

The results are the same, except that I've spot a typo in the original description. See the update to it please. The second and third cases show the same error still (it's especially easy to reproduce 3. and see how unwanted that is).

**Comment by Wedge009** [comment] 2017-12-23 23:35
All right, I can confirm the inability to undo placement of items, but I didn't get any crash on undo (normal or partial) of labels.

**Comment by vgaming** [comment] 2017-12-24 09:31
I'm not sure I've described the 3-rd case clearly enough. Here are the steps:

* start wesnoth v1.13.10+dev (19c08e77-Clean)
* open map editor, create new scenario
* choose "items" editor (icon that looks like a box on the right middle)
* place any items
* select label editor, click to place a label and then cancel.
* click "partial undo".

Map editor will say "Fatal Error" and close itself.

**Comment by Wedge009** [comment] 2017-12-24 11:52
Okay, I can confirm the Fatal Error as well now, but only on partial undo, not normal undo. The 19c08e7 commit is irrelevant and it's not part of master anyway. Just looking at the behaviour, I'd guess that the undo handling for placing items and labels are not consistent or broken somewhere.

**Comment by vgaming** [comment] 2017-12-24 16:00
@Wedge009 it certainly is. IDK how to undo item placement at all.

**Comment by jyrkive** [comment] 2018-01-09 18:28
Commit a65596e5b54174c949d8a0d830234d49447b1bab improves the behavior somewhat. Clicking the map with the label tool active no longer activates the undo buttons.

**Comment by Wedge009** [comment] 2018-01-11 00:22
That certainly helps. I note that the undo only becomes available if the label is actually placed, but not if it's cancelled. So the label issue is resolved, in my opinion.

So that leaves items, which cannot be undone after placement.

**Comment by Vultraz** [comment] 2018-02-12 02:46
The item tool needs more work than just fixing Undo. Added an entry for it in #1702, and closing this.

**Closed by Vultraz** 2018-02-12 02:46 UTC
Labels: Bug, Confirmed, Editor
