### ISSUE TITLE
scenario end buttons turns to end turn button after pressing it

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3238] opened 2018-06-11 17:53 UTC
When you lost am game, you end up in linger mode, and in the corner is a scenario end button.
When you press it, you return to the MP Lobby, but for a moment the button turns into the turn end button again.

**Comment by Wedge009** [comment] 2019-10-22 00:05
Just wondering: does this happen in SP? I don't expect it to be MP-specific, but I imagine the button is _normally_ 'End Turn' and gets updated to 'End Scenario' on victory/loss. If there's a delay or some other processing, perhaps after the 'End Scenario' label is removed the 'End Turn' button stays visible.

**Comment by mesilliac** [comment] 2022-07-14 01:49
I can't reproduce this, so it was likely fixed in #6855. Reopen if it is still an issue.

**Closed by mesilliac** 2022-07-14 01:49 UTC
Labels: Bug, UI, Low Priority
