### ISSUE TITLE
Terrain with a string with more than 4 characters

### ISSUE THREAD

**Issue by benjaminbarrett1** [wesnoth/wesnoth#4995] opened 2020-07-16 21:14 UTC
### Game and System Information
 - What version of the game are you running? 1.14.12
 - Where did you download it from? Arch community repository
 - If you're using a custom build, what compiler did you use, and what commit did you build at? N/A (installed with Pacman
 - What OS are you running? Linux (Arch)

### Describe the bug
At the end of a scenario (heir to the throne, a hasty alliance) [edit: it's actually at the start of the next scenario] I got an error message:

> An error due to possibly invalid WML occurred
> The error message is :
> A terrain with a string with more than 4 characters has been found, the affected terrain is :2 Kud
> 
> When reporting the bug please include the following error message 
> Condition 'size <= 4' failed at /build/wesnoth/src/wesnoth/src/terrain/translation.cpp:710 in function 'string_to_layer_'.

### To Reproduce
Going back and finishing the scenario again did not reproduce the error.

**Comment by gfgtdf** [comment] 2020-07-16 21:40
am i the only only one  who things the space between the colon in the error message is strange?

**Comment by gfgtdf** [comment] 2020-07-16 21:45
Do you have any mods installed that could cause this?

**Comment by benjaminbarrett1** [comment] 2020-07-16 21:46
No, I haven't installed any mods

**Comment by gfgtdf** [comment] 2020-07-16 21:52
i just  tested said scenario and could not reproduce the issue.

**Comment by benjaminbarrett1** [comment] 2020-07-16 21:54
I have a savefile from the final turn, but reloading from that point doesn't seem to reproduce the error. Do you want it anyway?

**Comment by gfgtdf** [comment] 2020-07-16 21:59
> I have a savefile from the final turn, but reloading from that point doesn't seem to reproduce the error. Do you want it anyway?

Yes i'll take a quick look maybe there is sometihng obvious

**Comment by benjaminbarrett1** [comment] 2020-07-16 22:04
Here's the save file

[HttT-Hasty Alliance-Auto-Save17.gz](https://github.com/wesnoth/wesnoth/files/4934458/HttT-Hasty.Alliance-Auto-Save17.gz)

**Comment by gfgtdf** [comment] 2020-07-16 22:32
okay thanks unfortunately i cannot see anything that could  have caused this.

Do you remember anything else you did when this issue appeared?

**Comment by benjaminbarrett1** [comment] 2020-07-16 22:35
Unfortunately not - I just killed the leader, clicked through to end the scenario, and got the error message, which took me back to the main menu screen. Sorry not to be of more help, and thanks for looking into it!

**Comment by gfgtdf** [comment] 2020-07-16 22:35
more important question: Did the erro message happen at the end of that scenario (while you could see all the unit from the odl scenario etc) or while the next scenario was already loading?

**Comment by benjaminbarrett1** [comment] 2020-07-16 22:36
I'm fairly sure it was while the next scenario was loading

**Comment by gfgtdf** [comment] 2020-07-16 22:37
okay so the next scenario is a randomly generated map, there is probably somethign wrong with the random map generator that well happens onyl in some maps because it is, well, random.

**Comment by benjaminbarrett1** [comment] 2020-07-16 22:38
I see, that makes sense

**Comment by gfgtdf** [comment] 2020-07-16 22:45
My first guess would be that the  map generator tried to place two keeps in the same tile and that this somehow made it crash.

**Comment by benjaminbarrett1** [comment] 2020-07-16 23:02
I just managed to reproduce the error by regenerating the level about 50 times. No more information though

**Comment by CelticMinstrel** [comment] 2020-07-17 03:15
> My first guess would be that the map generator tried to place two keeps in the same tile and that this somehow made it crash.

If that results in a tile "2 2 KuD" then perhaps that would make sense…? Or would it? I'm not sure…

**Comment by gfgtdf** [comment] 2020-07-17 11:22
> If that results in a tile "2 2 KuD" then perhaps that would make sense…? Or would it? I'm not sure…

I think we _should_ allow that but i'm not sure whether the üart that reads the mapdata actualyl does.

**Comment by CelticMinstrel** [comment] 2020-07-17 12:20
I do vaguely recall a bug where multiple named locations on the same tile would not work…

**Comment by Wedge009** [comment] 2020-07-29 00:40
Pretty hard to diagnose something that only happened just the once. I wondered about the 'translation.cpp' but then I realised that one is about terrain mapping rather than language translation.

**Comment by benjaminbarrett1** [comment] 2020-07-29 11:38
I was able to reproduce it by reloading the scenario about 50-100 times, until it happened to occur again. This doesn't give any new information though.

**Comment by gfgtdf** [comment] 2020-07-29 15:30
> Pretty hard to diagnose something that only happened just the once. I wondered about the 'translation.cpp' but then I realised that one is about terrain mapping rather than language translation.

No, we are pretty sure what happens, mostlikeley there is a bug in the la cave  generator so that it places two starting location on the same tile.

**Comment by CelticMinstrel** [comment] 2020-08-01 20:44
That's a bug in the map parser, not the Lua cave generator.

Or wait… I guess it's a bug in both. Still, the map parser should be able to handle multiple locations on the same tile.

**Comment by gfgtdf** [comment] 2020-08-01 21:17
> Still, the map parser should be able to handle multiple locations on the same tile.

I fixed that in 1.15 already, but i don't think i'll backport this.

**Comment by CelticMinstrel** [comment] 2020-08-01 22:15
Okay, perfect. Then the Lua cave generator should also be fixed to not place two sides on the same location.

**Comment by Wedge009** [comment] 2021-09-15 13:57
So is this resolved in 1.15.x or does the Lua generator still need updating?

**Comment by Wedge009** [comment] 2023-03-06 04:27
Please re-open if it's still an issue.

**Closed by Wedge009** 2023-03-06 04:27 UTC
Labels: Bug, Terrain
