### ISSUE TITLE
Lua console: unclear "events"

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2282] opened 2017-12-08 21:01 UTC
Steps:
* start wesnoth 1.13 e4b61eab
* open any game, enable debug mode, enter Lua console
* type in `"<!--"`

Expected: lua console prints '<!--'

Actually: lua console shows error `!-: event not found`  Is it some unknown to me Lua hack that I encountered? My OS Lua definitely doesn't have this.

**Comment by CelticMinstrel** [comment] 2017-12-09 07:17
This is a "feature" of readline. Your OS Lua would likely have it if it were built against readline (which is possible, if I recall correctly). Personally I think it should be disabled if possible (assuming we're even keeping readline rather than rolling our own history implementation).

**Comment by gfgtdf** [comment] 2017-12-09 12:01
I reported this already in https://github.com/wesnoth/wesnoth/issues/1708 . that discussion also suggests a possible fix for it althoug i'd still lime making out ouw history implementation  more.

**Comment by GregoryLundberg** [comment] 2017-12-09 14:50
Yep. Closing this as duplicate of Issue #1708.

**Closed by GregoryLundberg** 2017-12-09 14:50 UTC
Labels: Bug, Confirmed, Lua API
