### ISSUE TITLE
1.13.13 no feedback for droid / undroid

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#2819] opened 2018-04-02 18:49 UTC
In 1.12.6 multiplayer, when a side is droided or undroided there is a server message to all players (and observers). On 1.13.13 that doesn't happen.

This message is a useful feature in SXC, and probably other co-op games with 3 or more players. If someone leaves the the host can choose to play that side, to control it while asking who wants it, or to droid it; whichever the hosts chooses, the first message in the chat log makes the host's decision obvious to players. Without that message, someone will have to ask, or the host will get in the habit of typing what the message would have said.

**Comment by sapientN3T** [comment] 2018-04-03 00:56
I had this discussion before when the message was added and I was of the opinion that how you play your side should be private. One potential use of the command is to assist you on performing some inconsequential moves very quickly, or to temporarily relinquish control in the event of an urgent matter in real life. However, if there is a server announcement, this might cause some embarrassment to the one who used it and some offense to the other players. On the other hand, one might argue that it is unfair for someone who believes they are playing a human to be faced with an AI. To counter that argument, I would say: If the command is used in an improper situation, then it should be evident regardless.

**Comment by stevecotton** [comment] 2018-04-03 08:05
What about making it an allies-only message? For 2v2 matches, it would be useful to know that your partner is a machine that doesn't understand chat messages; and it would give the 1.12.6 behaviour for SXC-like fully co-op games.

**Comment by vgaming** [comment] 2018-04-03 13:51
I think that using "droid" to signal AFK in its current form should not be encouraged. Currently, people do not droid when they are just AFK.

I think it may be better to introduce an AFK status properly, or not do half-implementation at all. A proper AFK status should tell other players that a side is AFK, yet signal that player is willing to return later. In some cases, players may decide to wait instead of dealing with AI side.

All-in-all, this needs to be carefully thought out instead of throwing out a solution altering one edge case only. Especially if that case is doubtful for reasons discussed in first message. I personally would prefer the old solution until we implement proper AFK.

**Comment by shikadiqueen** [comment] 2018-04-04 05:15
Marking as a regression since odds that the announcement was not dropped on purpose, and the priority here is informing other players what's going on anyway.

**Comment by Konrad22** [comment] 2018-07-27 10:00
I'd very much like to get at least private feedback on droid/undroid, when I'm the one doing the droiding. It's quite confusing when you want to droid a side and you have no idea if you have succeeded.

**Comment by jostephd** [comment] 2018-07-31 19:01
#3419

**Comment by CelticMinstrel** [comment] 2018-08-11 23:10
...why is this still open when it has been done?

**Closed by CelticMinstrel** 2018-08-11 23:10 UTC
Labels: Bug, MP, Regression

**Comment by stevecotton** [comment] 2018-08-12 11:06
The merged PR only gives private feedback, I guess this was still open for discussing whether to add public feedback. Still, it seems that there are divided opinions on whether there should be public feedback, so I guess it makes sense to leave it closed.

**Comment by CelticMinstrel** [comment] 2018-08-12 15:45
What exactly do you mean by private vs public feedback? Is it a question of whether other players learn that a player has (un)droided?

**Comment by vgaming** [comment] 2018-08-12 15:47
@CelticMinstrel I think so. I like exactly the old behaviour pretty much as well (it's transparent, you see _exactly_ what's going on).

**Comment by CelticMinstrel** [comment] 2018-08-12 15:49
Old behaviour?

**Comment by Konrad22** [comment] 2018-08-12 15:50
( @CelticMinstrel See first post in this issue.)
