### ISSUE TITLE
[effect] [filter] ability_type_active causes crashes when loading a savegame

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7238] opened 2022-12-28 11:37 UTC
### Game and System Information

The Battle for Wesnoth version 1.17.11 x86_64
Running on Microsoft Windows 7 Service Pack 1 (6.1.7601) x86_64
Distribution channel: Steam

Installed add-ons
=================

A_New_Order:                  1.4.1
Advance_Wesnoth_Wars_fork:    1.17.11
Akladian_Music:               1.0.1
An_Orcish_Incursion:          1.0.3
Eastern_Invasion_Dalas:       2.0.1
Era_of_Magic:                 3.9.5
Era_of_Magic_Resources:       1.8.0
Gui_Debug_Tools:              0.10.2
Non_Fatal_Wounds_Extended:    2.1
Reflection:                   1.0.0
To_Lands_Unknown:             3.6.0
To_Lands_Unknown_Resources_1: 2.0.0
To_Lands_Unknown_Resources_2: 1.7.1
Unitmarker:                   1.0.4

### Description of the bug

![imagen](https://user-images.githubusercontent.com/40789364/209805663-5c04020b-b9b8-4a4f-9080-7826024e0511.png)

### Steps to reproduce the behavior

1 Give an unit (whit any _hides_ ability) this object via any method:
```
                            [object]
                                id=aww_preambush_icon
                                [effect]
                                    [filter]
                                        ability_type_active=hides
                                    [/filter]
                                    apply_to=overlay
                                    add="misc/aww-ambush-attack.png" ## use an existent image for testing purposes, not this custom image
                                [/effect]
                            [/object]
```
2 Skip to next turn and save
3 Load savegame
4 APPCRASH

### Expected behavior

NOTE: The filter works as expected on normal play, only crashes when loads a savegame. Giving this object to a unit without hides ability, doesn't causes crashes. ability_type=hides doesn't cause crashes. On 1.16 crashes too.

### Additional context

Deleting the filter stop the crashes, so the cause is specifically this filter:

```
                                    [filter]
                                        ability_type_active=hides
                                    [/filter]
```

EDIT: This filter crashes too. Same with time_of_day_id=
```
						[filter]
							[filter_location]
								time_of_day="chaotic"
							[/filter_location]
						[/filter]
```

SAVEGAME WITH CRASH (zipped file):
[UCsDH-Erradicando a un mago-Guardado automático4.zip](https://github.com/wesnoth/wesnoth/files/10317129/UCsDH-Erradicando.a.un.mago-Guardado.automatico4.zip)

**Comment by Pentarctagon** [comment] 2022-12-28 19:43
@newfrenchy83 FYI

**Comment by newfrenchy83** [comment] 2022-12-28 19:44
Hé could you more precide

**Comment by newfrenchy83** [comment] 2022-12-28 19:50
ability_type_active présent before 2017 and i just extension logic to ability_id_active,i don't know cause of crash but i don't think ability_id_active implémentation was responsable.

**Comment by Pentarctagon** [comment] 2022-12-28 20:20
Ah, right, my bad then.

**Comment by Toranks** [comment] 2022-12-28 21:05
But, ability_type=hides doesn't crashes the game. Only ability_type_active. I've tested it many times on many combinations, and clearly is this filter.
This is the referenced line, on `bool unit::ability_active`

[bool unit::ability_active](https://github.com/wesnoth/wesnoth/blob/master/src/units/abilities.cpp#L361)

**Comment by Toranks** [comment] 2022-12-29 23:13
Something surprising, I didn't expect it, but if the effect does NOTHING, but contains the filter, it still crashes.
It does not depend on the map, nor on the installed addons, nor on any other cause. Put this object (insert it into a savegame on a unit with hide ability), and you can recreate the crash at any time.

```
                            [object]
                                [effect]
                                    [filter]
                                        ability_type_active=hides
                                    [/filter]
                                [/effect]
                            [/object]
```

**Comment by stevecotton** [comment] 2022-12-30 07:58
@Vultraz looks like an issue from 6a21fdc6750a8342846ef18248517808316c4118, probably a duplicate of #5643. Should we just revert that commit?

Explanation for everyone else: there's a bunch of global things that can be accessed either via global pointers in the `resource` namespace, or via `display::get_singleton()`. The singleton and these global pointers get set up in `play_controller::init`; so it would eventually be nice to have all of them go through a `get_singleton()` method (although preferably not a singleton of a GUI class).

If you see a callstack that's in `play_controller::init` and crashes on an `assert(display::get_singleton())` line, then it's probably code that's been changed to use `get_singleton()`, but that needs to access one of the global resources when the resource has already been created, but before the display has been created.

**Comment by Vultraz** [comment] 2022-12-30 09:35
The display class should already exist at that point, though...

**Comment by stevecotton** [comment] 2022-12-30 12:03
Exactly that. The crash happens with `game_state::init` in the callstack, called from play_controller.cpp:225 (frame 22). The `game_display` instance isn't created until play_controller.cpp:243.

```
#20 team_builder::build_team_stage_two() (this=0x55555938f3b0) at src/teambuilder.cpp:80
#21 game_state::init(config const&, play_controller&) (this=0x55555a4256d0, level=..., pc=...) at src/game_state.cpp:234
#22 operator()() const (__closure=0x7fffffff9d20) at src/play_controller.cpp:225
#23 std::__invoke_impl<void, play_controller::init(const config&)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/12/bits/invoke.h:61
#24 std::__invoke_r<void, play_controller::init(const config&)::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/12/bits/invoke.h:111
#25 std::_Function_handler<void(), play_controller::init(const config&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/12/bits/std_function.h:290
#26 std::function<void ()>::operator()() const (this=0x7fffffff9d20) at /usr/include/c++/12/bits/std_function.h:591
#27 gui2::dialogs::loading_screen::process(events::pump_info&) (this=0x7fffffffa770) at src/gui/dialogs/loading_screen.cpp:171
#28 events::pump() () at src/events.cpp:739
#29 gui2::window::show(unsigned int) (this=0x7fffffffa770, auto_close_timeout=0) at src/gui/widgets/window.cpp:572
#30 gui2::dialogs::modal_dialog::show(unsigned int) (this=0x7fffffffa770, auto_close_time=0) at src/gui/dialogs/modal_dialog.cpp:92
#31 gui2::dialogs::loading_screen::display(std::function<void ()>) (f=...) at src/gui/dialogs/loading_screen.cpp:226
#32 play_controller::init(config const&) (this=0x7fffffffb8e0, level=...) at src/play_controller.cpp:210
```

**Closed** 2022-12-30 21:08 UTC
Labels: Bug, WML
