### ISSUE TITLE
Incomplete handling of case sensitive filenames

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3135] opened 2018-05-18 20:04 UTC
#3129 shows image of attack using attacks/trident.png. Addon has file attacks/Trident.png. Neither image is displayed.

**Comment by gfgtdf** [comment] 2018-05-19 20:01
wesnoth does not claim to fully support file sensitive filenames (in particular on windows), what wesnoth has are just some hooks to make umc code fail eariler (to detect bugs eariler) to make sure no broken addons are uploaded to the server. If your addon relies on filesystem beeing case sensitive this is a bug in your adon just like relying on filesystem beeing case insensitive is.

**Comment by Vultraz** [comment] 2018-05-19 23:27
How about just... NOT naming the file `attacks/Trident.png' in AE? -_-

**Comment by ProditorMagnus** [comment] 2018-05-19 23:35
I will consider that. Should be good to lowercase all internal binary paths.

**Comment by ProditorMagnus** [comment] 2018-05-19 23:51
Lowercasing not doable, such images are used by active eras.

Trident is used by 3 different eras, all of them basically inactive, so can change that one.

**Comment by Vultraz** [comment] 2018-05-19 23:52
You have the addon sources rolled into one... you can change whatever you want.

**Comment by ProditorMagnus** [comment] 2018-05-20 00:02
Yes, but I will not make any unneeded changes to EoMa or BMR, I regularly need to import those again.

**Comment by Wedge009** [comment] 2018-05-20 13:55
Is #2046 relevant?

**Comment by jostephd** [comment] 2019-05-07 15:42
Indeed, this issue doesn't describe any bug or feature request not covered by #2046. Any objections to closing this issue as a duplicate of that one?

**Comment by Wedge009** [comment] 2019-05-08 09:01
Go ahead and close, can always re-open if good reason given. I've tried to quash duplicates in the past, but haven't done an all-open-issues review in a while (this was something I found easier to do in Gna than here, and that's not necessarily to do with having more open issues here than back then).

**Comment by jostephd** [comment] 2019-05-08 09:40
Closing, then. (And I'm curious about how Gna made that easier, but that's OT here...)

**Closed by jostephd** 2019-05-08 09:40 UTC
Labels: Bug, Engine, Low-priority
