### ISSUE TITLE
Parts of Drake Flameheart getting clipped or changing z-level at max zoom when moving the cursor back and forth

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6891] opened 2022-07-20 18:29 UTC
### Game and System Information

- **Version:** 1.17.6
- **Downloaded from:** steam
- **OS:** Windows 10
- **Resolution:** 1920x1080

### Description of the bug

Let me show the gif first:
![drakebug2](https://user-images.githubusercontent.com/41433185/180054750-09cfb394-782a-4a06-b9e3-d088163df586.gif)

As you can see, at maximum zoom, I am moving the cursor back and forth from a Drake Flameheart to other hexes around it. Sometimes parts of the unit are clipped and sometimes the parts of the castle terrain are drawn over on top of its wings.
This recording was taken in the Scenario Bilheld from the campaign Dead Water.

### Steps to reproduce the behavior

1. Have a Drake Flameheart in the middle of castle tiles.
2. Go to the maximum zoom.
3. Move the mouse cursor back and forth from the Drake to two hexes away and then back. Try different angles.

### Expected behavior

No clipping or changing of z-levels of painted graphics.

**Comment by Wedge009** [comment] 2022-07-21 00:27
You reported something similar in #6118. Do you think this could be the same issue or something else entirely? Granted, this one is after the hardware acceleration was implemented.

**Comment by mesilliac** [comment] 2022-07-21 00:54
I can't reproduce this in my current working branch, so i think one of the changes i have on my local may have fixed it.

I'll be cleaning those up and posting them probably in the next few days.

I also have a fix relating to https://github.com/wesnoth/wesnoth/issues/6589 which solves out-of-hex leftovers during animation at zoom. I'll probably try putting that up today. It might be related.

**Comment by max-torch** [comment] 2022-07-21 05:36
> You reported something similar in #6118. Do you think this could be the same issue or something else entirely? Granted, this one is after the hardware acceleration was implemented.

I have no idea if it's related. All I know is that I decided to report this, because although it has some similarity to #6118, this is happening with the new hardware acceleration.

**Comment by max-torch** [comment] 2022-07-21 05:48
In 1.17.6,
I tried doing this again, but this time selecting the drake first, which @mesilliac said to try doing. See gif:
![drakebug3](https://user-images.githubusercontent.com/41433185/180138686-432b88ed-63d6-4ee7-baac-c8a0706c0e32.gif)
Everything behaves the way it is expected to behave when the unit is selected.

Now with regards to testing this on the head commit of the latest master, I can't do it right away, but I can do it 3-4 days from now, because i am planning to do a fresh build of wesnoth on ubuntu.

**Comment by Wedge009** [comment] 2022-07-21 06:47
Aside: Is it that much trouble to build? I generally try to rebuild the current state of the code when I'm testing.

**Comment by max-torch** [comment] 2022-07-21 20:51
Let's just say that it took me an entire 3 whole days of researching and not giving up to get my first build of wesnoth working on windows. Then another two whole days of not giving up to get my second build of wesnoth working on linux. I know I won't have that much trouble again when i do my 3rd build now, but who knows?

**Comment by Wedge009** [comment] 2022-07-21 21:05
Okay. I just find SCons build on Linux super-easy, once all the dependencies are satisfied. Incremental build works well for me too.

**Comment by max-torch** [comment] 2022-07-24 19:14
Just Tested on The HEAD of current master.:
The Battle for Wesnoth version 1.17.6+dev (https://github.com/wesnoth/wesnoth/commit/d1833b5cf73bc2a642c106d6fec7d37e267fdfc4-Clean) x86_64
Running on Ubuntu 22.04 LTS x86_64
Distribution channel: Default

![image](https://user-images.githubusercontent.com/41433185/180662395-9a8beed6-0b8f-4273-944c-9ce37cde1a72.png)

Again at maximum zoom. The issue does not exist. I do not know if it is because i am on linux or because this is master.

**Comment by Wedge009** [comment] 2022-07-24 23:04
I don't expect there to be a difference between OS in this case, but if you want you can confirm on Windows too and then this can be closed.

**Comment by mesilliac** [comment] 2022-07-25 02:30
If it's fixed on Linux it'll be fixed on Windows also. There are (or were, i guess) a lot of similar-looking bugs caused by different things, so sometimes my testing missed cases. Looks like this one's good tho, thanks for verifying :).

**Closed by mesilliac** 2022-07-25 02:30 UTC
Labels: Bug, Graphics
