### ISSUE TITLE
Some content of the [ai] tag is duplicated in savegames

### ISSUE THREAD

**Issue by Elvish-Hunter** [wesnoth/wesnoth#3338] opened 2018-07-13 13:52 UTC
While updating A Rough Life for 1.14 (which is already uploaded on the server), I converted the old AI code used in the first scenario to use [candidate_action]; after doing this, the stderr log gets spammed with error messages like the following one on each turn.

`error ai/actions: Error #2001 (move_result::E_EMPTY_MOVE) in full move by side 3 from location 14,11 to location 18,13`

At first, of course, I thought that it was a mistake in my code, so I started a long debug session; long short story, no matter what I did, the result never changed. It's important to note, however, that except for this message the code seems to behave just like I want it to.
Trying to get rid of this error, I decided to add some wesnoth.message() calls for debug purpose, and you can use them by uncommenting lines 27, 28, 29 and 52 in the file add-ons/A_Rough_Life/lua/jabb.lua. Surprise: the wesnoth.message() outputs are printed twice for each turn! In fact, on turn 1 I get these messages:
![ai debug messages](https://user-images.githubusercontent.com/4049668/42694890-1805898e-86b4-11e8-97cb-6f481583592e.png)
plus two more that I wasn't quick enough to screenshot.

Trying to understand the issue some more, I opened the autosave of the first turn, and found out that there are some duplicated tags inside the savegame: at least the [candidate_action] and [goal] are involved. This is what I found at line 2781:

			[goal]
				name="target"
				value=3
				[criteria]
					id="Jacques"
				[/criteria]
			[/goal]
			[modify_ai]
				action="add"
				path="stage[main_loop].candidate_action"
				side=3
				[candidate_action]
					engine="lua"
					id="jabb_moves"
					location="~add-ons/A_Rough_Life/lua/jabb.lua"
					max_score=100100
					name="jabb_moves"
					[args]
					[/args]
				[/candidate_action]
			[/modify_ai]
			[goal]
				name="target"
				value=3
				[criteria]
					id="Jacques"
				[/criteria]
			[/goal]
			[modify_ai]
				action="add"
				path="stage[main_loop].candidate_action"
				side=3
				[candidate_action]
					engine="lua"
					id="jabb_moves"
					location="~add-ons/A_Rough_Life/lua/jabb.lua"
					max_score=100100
					name="jabb_moves"
					[args]
					[/args]
				[/candidate_action]
			[/modify_ai]

This explains why the Lua code gets executed twice.
I then tried playing a mainline campaign (Eastern Invasion) and got the same result: the [goal] tag gets duplicated in the savegame, but here isn't noticeable because it doesn't cause an AI action to be attempted  twice.

At this point, I suspect that it might be a C++ issue. I noticed this behavior on version 1.14.3 running on Xubuntu 16.04 LTS. I didn't test if it happens on the 1.15 series yet.

**Comment by CelticMinstrel** [comment] 2018-07-15 13:41
Not really sure, but if it's about stuff being duplicated in the savegame, I guess the first place I'd look is the "write full AI to config" function?

**Comment by mattsc** [comment] 2018-08-06 13:36
I poked around this a little.  The AI non-default aspects settings are also added twice (which has no effect, of course), and this appears not only in the save, but right away in the AI config setup when a scenario is started.  However, it only happens for AI components that are modified in a `[side]` tag.  If you put the code into `[modify_side]` or `[modify_ai]` tags in a prestart event, the duplication does not happen.  So it seems to have something to do with the AI definition at the very beginning of the scenario when the sides are set up.

@Elvish-Hunter This at least gives you a work-around until this is fixed.

@CelticMinstrel @gfgtdf @Vultraz   This appears to be caused by code that I don't really know anything about.  I think one of you would be better suited to follow up on it?

**Comment by mattsc** [comment] 2018-08-06 15:45
For reference, to reproduce this:
- Start the first scenario of Eastern Invasion as pointed out by @Elvish-Hunter and dismiss the story and opening dialog
- Open gamestate inspector with `:inspect`
- Click on: team 3 -> ai -> goals

**Comment by mattsc** [comment] 2018-11-09 05:06
I looked into this some more and, unless I did something wrong, it seems that the `[goal]` tag in my test case above is already duplicated in the `level` config passed to `play_controller`.  In other words, it seems to happen right around the parsing of the `[scenario]` tag.  But then I got lost and just cannot figure out what is going on there.  Any help would be appreciated.

**Comment by mattsc** [comment] 2018-11-09 19:19
Okay, after a lot of inexpert digging around, I finally figured out what is going on.  But I have no idea how to fix it.  @gfgtdf calling on you, since I think you have worked the most on this part of the code.

The whole thing starts [here](https://github.com/wesnoth/wesnoth/blob/master/src/game_initialization/connect_engine.cpp#L1069) in connect_engine.cpp.  This adds an `[ai]` tag with only an empty `ai_algorithm=` key.  At this point the side config looks like this:
```
[ai]
	ai_algorithm =
[/ai]
[ai]
	aggression = 0.6
	grouping = no
	passive_leader = yes
	[goal]
		name = target
		value = 2
		[criteria]
			id = Dacyn
		[/criteria]
	[/goal]
[/ai]
```
Then in [l.1178](https://github.com/wesnoth/wesnoth/blob/master/src/game_initialization/connect_engine.cpp#L1178) and following, a `trimmed` config is created, which removes the first of those `[ai]` tags, since it does not contain anything.
Finally, at the end of that block, when `trimmed` and the original `res` are merged, we get this:
```
[ai]
	aggression = 0.6
	ai_algorithm =
	grouping = no
	passive_leader = yes
	[goal]
		name = target
		value = 2
		[criteria]
			id = Dacyn
		[/criteria]
	[/goal]
[/ai]
[ai]
	aggression = 0.6
	grouping = no
	passive_leader = yes
	[goal]
		name = target
		value = 2
		[criteria]
			id = Dacyn
		[/criteria]
	[/goal]
[/ai]
```
Note that these two are identical, except for the `ai_algorithm=` in the former.

So this causes the duplication of the `[goal]` tags in my test case and of the CAs in @Elvish-Hunter's original problem.

I have no idea what to do about this as I do not know what this code is supposed to do exactly, but hopefully this is enough for somebody else to fix the problem?

**Comment by gfgtdf** [comment] 2018-11-09 19:56
Unfortunteley i don't know much about this, also the last commit that touched that particular line is actualyl this one: https://github.com/wesnoth/wesnoth/commit/56a99175dad6ff0c17a94d7b0054602a4ede05fd

From what you said, it should not be too hard to fix, probably just add a clear_children("ai") to either `trimmed` or `res` before the merge.

The best fix can only be figured out be someone what actualyl understands the ai and in particular knows that the 'ai algorithm' ui options actualyl behaves and how it interacts with the given [ai] blocks in side.

**Comment by gfgtdf** [comment] 2018-11-09 19:59
wait, actually the second codereference form your commit is in a 'if not is_reloaded_game then' check, and the first post uses, [modify_ai] which is done after initial setup so that code shoudl not have an effect on it

**Comment by CelticMinstrel** [comment] 2018-11-10 02:15
My reaction to that code is that it doesn't make any sense whatsoever. It removes a few attributes from the "trimmed" config and then merges the result back into the main config? What on earth is the point of that?

Anyway, my thought on fixing it is, try adding that extra `[ai]` _after_ this trimming. Either that, or remove the trimming altogether since it appears to do nothing. (Well, maybe it might restore some attributes that were removed/altered earlier in the function? I'm not sure.)

**Comment by mattsc** [comment] 2018-11-10 06:01
The idea of moving the `ai_algorithm` bit after the trimming has occurred to me also, but I *really* don't understand WTH this code is doing.  I'm not going to touch it and change something just to solve this specific problem, because it probably has repercussions that I have no understanding of whatsoever.  So as far as I am concerned, I have done what I can about this.  If somebody understands what's going on here and wants to fix it, that's great.  If not, well, c'est la vie.

**Comment by gfgtdf** [comment] 2018-11-10 11:09
This seems to be the commit that adds the 'trimmed' stuff https://github.com/wesnoth/wesnoth/commit/6b42279b65e02bb94b8ace3e41f26f4ad78b0061

the refernced issues are

1:

>    Multiplayer scenario leaders aren't used, races don't work, other settings not used
> 
> Multiplayer scenario WML settings don't work properly.  Leader (&amp;quot;type&amp;quot;) along with race settings (&amp;quot;recruit&amp;quot;) and other settings such as gold and income are overwritten when starting the game.
This bug is about making existing WML work it does in other scenarios, and is a smaller part of the feature request bug #3332.  This bug is not about updating the gui or adding new WML tags to help create multiplayer scenarios (such as race or allow_race_change).</original_submission>

2:

> allow_player=no sides assigned random factions overriding [side] settings
> 
> In MP scenarios, it is currently impossible to specify the faction and recruit lists in the [side] tag. Any setting here is overridden by a random faction choice, even if the side has been flagged as &amp;quot;allow_player=no&amp;quot; and doesn't even appear on the game setup dialogue (where factions, teams and gold can be set).
> 
> This effectively screws MP scenario designers.
> 
> Make it so that &amp;quot;allow_player=no&amp;quot; sides are NOT assigned a faction randomly, but will accept settings from the [side] tag.

3:

> AI doesn't recruit
> 
> Despite favourable conditions (gold, decent recruit list etc.) AI's quite frequently fail to recruit (this is in MP scenarios). When they recruit, it's usually a full castle full.
> 
> Here's one AI that is liable to do this:
   recruit=&amp;quot;Troll Whelp,Orcish Archer,Orcish Assassin,Orcish Grunt,Wolf Rider&amp;quot;
   [ai]
     aggression=1.3
     caution=0.1
     village_value=2.0
     leader_value=4.0
     protect_leader=1
     protect_leader_radius=35
     villages_per_scout=20
     passive_leader=yes
     recruitment_ignore_bad_combat=yes
     recruitment_ignore_bad_movement=yes
    recruitment_pattern=&amp;quot;fighter,fighter,archer,fighter,scout,fighter,archer&amp;quot;
   [/ai]
> 
> Since in MP, I have to set the recruit list with [set_recruit] (see the other bug today), there might also be an issue with that process.
>
> Needless to say, this completely makes some scenarios unplayable.


So if you can test that these do no reoccur when you remove that copde you can remove it.

**Comment by gfgtdf** [comment] 2018-11-10 11:17
hmm no wait, actually i think it realyl makes no sense at all, basicially _all_ of the attributes that are set in new_config except "name" are added to the attributes_to_trim. so ye should be removed, will do it.

**Comment by mattsc** [comment] 2018-11-10 15:47
@gfgtdf Thanks for those comments.  I did not see your question since it was added in an edit (as was this last one, which I only saw by chance), sorry.  No, the code does not get executed when reloading.  However, that `[modify_ai]` tag in 'A Rough Life' is inside a [side] tag, not an event (don't know what that means for when it is executed).  Nevertheless, I tried removing the "trimmed block" and started that scenario and it does not fix @Elvish-Hunter's problem, so there's still something else going on.  I'll get back on that sometime.

On the other hand, I confirmed that removing the `trimmed` merge fixes the `[goal]` tag duplication and does not have any immediately obvious other effects.

**Comment by mattsc** [comment] 2018-11-10 15:54
I checked one more thing: removing that code does not fix the ARL problem in that the error message remains.  The duplication of the `[candidate_action]` tag in the save is gone.

**Comment by mattsc** [comment] 2018-11-10 16:07
I'll keep double posting here so that this does not get lost ...

@Elvish-Hunter : so I looked at the jabb_moves Lua code and the problem causing your error message is in there, not in the engine.  The evaluation function has no check for whether the next move is actually possible, so the engine tries to execute the CA until it runs into an error (in this case, an empty move), which results in the CA being black-listed.  You could either make the return of the CA score conditional on `res` showing an executable move, or the simplest way is probably to change l.24 to

`    if jabb and (jabb.moves > 0) then`

Nevertheless, this was useful as we would have never found the tag duplication otherwise.  :)

**Comment by CelticMinstrel** [comment] 2018-11-11 02:02
I guess that commit fixes this then.

**Closed by CelticMinstrel** 2018-11-11 02:02 UTC
Labels: AI, Bug, Stable 1.14

**Comment by mattsc** [comment] 2018-11-11 14:09
Any reason not to cherry-pick this to 1.14?

**Comment by CelticMinstrel** [comment] 2018-11-11 17:58
I'm not sure if it's MP-safe, but I think we probably should anyway.

**Comment by gfgtdf** [comment] 2018-11-12 03:04
this does not cause oos if that's what you mean.

**Comment by CelticMinstrel** [comment] 2018-11-12 05:44
That's what I mean, yes.
