### ISSUE TITLE
Spacebar regesters two presses

### ISSUE THREAD

**Issue by Samonella7** [wesnoth/wesnoth#2586] opened 2018-03-04 03:46 UTC
Here is a refresher on how the spacebar works (or how it worked in 1.12):
First, it marks the selected unit has having exhausted it's moves, so its status orb turns red and it's ignored by the next-unit function (useful for making sure you moved all the units you meant to). Then it immediately does the same thing as next-unit, ie, select another unit that hasn't exhausted it's moves or been marked.
Using the spacebar on a unit that was already marked un-marks it, so it's noticed by next-unit again, and its status orb goes back to green/yellow.
Holding down the spacebar for a second or so makes it starts marking all your units very quickly, ie, mark one, immediately find the next and mark it too, etc (though I have no idea when this would be useful).

The problem in 1.13 is that it quickly marks two units, as though I had held the spacebar for a second, even if I tap it and let go as quickly as possible.

This leads to some other strange things: trying to un-mark a unit doesn't work, because, in the same way, the game seems to register the action twice, so it immediately marks the unit after un-marking it. Also, when there is only one unmoved/unmarked unit left, it is impossible to mark because the game marks it and immediately unmarks it again.

I tested this using a windows 10 computer and found the problem in both 13.11 and 13.10.

**Comment by Vultraz** [comment] 2018-03-04 16:48
I cannot reproduce this on current master. Possibly the recent hotkey-related changes by @jyrkive fixed this. Though it's worth noting you can no longer hold down the spacebar for continuous function, but I don't think that's too much of a problem.

**Comment by jyrkive** [comment] 2018-03-04 18:10
"Holding down spacebar marks all units very quickly" was likely caused by holding it down generating keypress events continuously, which I fixed in commit ecc0dca665737bcb411fbd355edd37df8a9038b8. It wasn't intentional behavior.

**Comment by Vultraz** [comment] 2018-03-04 23:46
Makes sense, actually. Since I can't repro the original bug, I'm closing this.

**Closed by Vultraz** 2018-03-04 23:46 UTC
