### ISSUE TITLE
Quick replay getting stuck in unit_animator::wait_for_end

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#3084] opened 2018-05-11 00:16 UTC
On the 1.14 MP servers, enable quick replays and try to observe a game in progress. For some games Wesnoth will get stuck, with the unit_animator::wait_for_end never finishing. I could reproduce by joining as an observer while the game was in progress on the MP server with 1.14.0, 1.14.1 and 3723c4edfabf6dfd35c226c2ff1e59912dcaae47 (all built locally). Note: I only checked the stack trace with the 3723c build, I'm assuming it was the same for the 1.14.0 and 1.14.1.

I've seen this with two games today, both SXC with Ageless Era:
 * https://replays.wesnoth.org/1.14/20180510/SXC_Mountains_of_Doom_0.2.119_Turn_54_(5105).bz2
 * the (being played at the time of writing) SXC_Curve with Gundorf as the first player

Gundorf's game does not get stuck if I enable "normal replays". For the Mountains of Doom game, it plays successfully when watched as an end-of-game replay (I haven't seen an option to play and already-finished game as a quick-replay). 

Stack trace for thread 1 from 3723c4edfabf6dfd35c226c2ff1e59912dcaae47:

```
#0  0x0000555555b00496 in unit_animator::wait_for_end() const (this=0x55555831cf48) at build_dir/main/src/units/animation.cpp:1452
#1  0x0000555555a15672 in impl_run_animation(lua_State*) (L=0x7fffacfb8408) at build_dir/main/src/scripting/game_lua_kernel.cpp:445
#2  0x000055555627e285 in luaD_precall(lua_State*, lua_TValue*, int) (L=0x7fffacfb8408, func=0x7fffae9b7090, nresults=0) at build_dir/main/src/lua/ldo.cpp:434
#3  0x000055555629a663 in luaV_execute(lua_State*) (L=0x7fffacfb8408) at build_dir/main/src/lua/lvm.cpp:1134
#4  0x000055555627e62f in luaD_call(lua_State*, lua_TValue*, int) (L=0x7fffacfb8408, func=0x7fffae9b6da0, nResults=0) at build_dir/main/src/lua/ldo.cpp:499
#5  0x000055555627e68d in luaD_callnoyield(lua_State*, lua_TValue*, int) (L=0x7fffacfb8408, func=0x7fffae9b6da0, nResults=0) at build_dir/main/src/lua/ldo.cpp:509
#6  0x00005555562751ac in f_call(lua_State*, void*) (L=0x7fffacfb8408, ud=0x7fffffff7380) at build_dir/main/src/lua/lapi.cpp:942
#7  0x000055555627d522 in luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*) (L=0x7fffacfb8408, f=0x555556275177 <f_call(lua_State*, void*)>, ud=0x7fffffff7380)
    at build_dir/main/src/lua/ldo.cpp:142
#8  0x000055555627ee6a in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) (L=0x7fffacfb8408, func=0x555556275177 <f_call(lua_State*, void*)>, u=0x7fffffff7380, old_top=32, ef=16)
    at build_dir/main/src/lua/ldo.cpp:729
#9  0x000055555627527d in lua_pcallk(lua_State*, int, int, int, long, int (*)(lua_State*, int, long)) (L=0x7fffacfb8408, nargs=1, nresults=0, errfunc=-3, ctx=0, k=0x0)
    at build_dir/main/src/lua/lapi.cpp:968
#10 0x0000555555a4fc3d in luaW_pcall_internal(lua_State*, int, int) (L=0x7fffacfb8408, nArgs=1, nRets=0) at build_dir/main/src/scripting/lua_common.cpp:956
#11 0x0000555555a4fcb5 in luaW_pcall(lua_State*, int, int, bool) (L=0x7fffacfb8408, nArgs=1, nRets=0, allow_wml_error=true) at build_dir/main/src/scripting/lua_common.cpp:972
#12 0x0000555555a2c977 in game_lua_kernel::run_wml_action(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, vconfig const&, game_events::queued_event const&) (this=0x7fff9f374180, cmd="command", cfg=..., ev=...) at build_dir/main/src/scripting/game_lua_kernel.cpp:4579
#13 0x000055555616487d in game_events::event_handler::handle_event(game_events::queued_event const&, game_lua_kernel&) (this=0x7fffb14cd1b0, event_info=..., lk=...)
    at build_dir/main/src/game_events/handlers.cpp:73
#14 0x0000555555e40e86 in game_events::wml_event_pump::process_event(std::shared_ptr<game_events::event_handler>&, game_events::queued_event const&) (this=0x7fffad536590, handler_p=std::shared_ptr<game_events::event_handler> (use count 2, weak count 2) = {...}, ev=...) at build_dir/main/src/game_events/pump.cpp:304
#15 0x0000555555e42101 in game_events::wml_event_pump::<lambda(game_events::manager&, game_events::handler_ptr&)>::operator()(game_events::manager &, game_events::handler_ptr &) const (__closure=0x55555dbffe70, ptr=std::shared_ptr<game_events::event_handler> (use count 2, weak count 2) = {...}) at build_dir/main/src/game_events/pump.cpp:596
#16 0x0000555555e42e32 in std::_Function_handler<void(game_events::manager&, std::shared_ptr<game_events::event_handler>&), game_events::wml_event_pump::operator()()::<lambda(game_events::manager&, game_events::handler_ptr&)> >::_M_invoke(const std::_Any_data &, game_events::manager &, std::shared_ptr<game_events::event_handler> &) (__functor=..., __args#0=..., __args#1=std::shared_ptr<game_events::event_handler> (use count 2, weak count 2) = {...}) at /usr/include/c++/7/bits/std_function.h:316
#17 0x0000555555e3288b in std::function<void (game_events::manager&, std::shared_ptr<game_events::event_handler>&)>::operator()(game_events::manager&, std::shared_ptr<game_events::event_handler>&) const (this=0x7fffffff7fe0, __args#0=..., __args#1=std::shared_ptr<game_events::event_handler> (use count 2, weak count 2) = {...}) at /usr/include/c++/7/bits/std_function.h:706
#18 0x0000555555e31d12 in game_events::manager::execute_on_events(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (game_events::manager&, std::shared_ptr<game_events::event_handler>&)>) (this=0x7fffadef1c00, event_id="die", func=...) at build_dir/main/src/game_events/manager.cpp:210
#19 0x0000555555e428c5 in game_events::wml_event_pump::operator()() (this=0x7fffad536590) at build_dir/main/src/game_events/pump.cpp:592
#20 0x0000555555e41eca in game_events::wml_event_pump::fire(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, game_events::entity_location const&, game_events::entity_location const&, config const&) (this=0x7fffad536590, event="die", loc1=..., loc2=..., data=...) at build_dir/main/src/game_events/pump.cpp:495
#21 0x0000555555c108dd in (anonymous namespace)::attack::unit_killed((anonymous namespace)::attack::unit_info&, (anonymous namespace)::attack::unit_info&, battle_context_unit_stats const*&, battle_context_unit_stats const*&, bool) (this=0x7fffffff90b0, attacker=..., defender=..., attacker_stats=@0x7fffffff90c0: 0x55555f8d2360, defender_stats=@0x7fffffff90b8: 0x55555fabb440, drain_killed=false)
    at build_dir/main/src/actions/attack.cpp:1340
#22 0x0000555555c0fc09 in (anonymous namespace)::attack::perform_hit(bool, statistics::attack_context&) (this=0x7fffffff90b0, attacker_turn=false, stats=...)
    at build_dir/main/src/actions/attack.cpp:1229
#23 0x0000555555c11d8e in (anonymous namespace)::attack::perform() (this=0x7fffffff90b0) at build_dir/main/src/actions/attack.cpp:1483
#24 0x0000555555c12a36 in attack_unit(map_location const&, map_location const&, int, int, bool) (attacker=..., defender=..., attack_with=0, defend_with=0, update_display=false)
    at build_dir/main/src/actions/attack.cpp:1605
#25 0x0000555555c12ad0 in attack_unit_and_advance(map_location const&, map_location const&, int, int, bool, ai::unit_advancements_aspect const&) (attacker=..., defender=..., attack_with=0, defend_with=0, update_display=false, ai_advancement=...) at build_dir/main/src/actions/attack.cpp:1615
#26 0x0000555555a9ae16 in synced_command_func_attack(config const&, bool, bool, synced_command::error_handler_function) (child=..., show=false, error_handler=...)
    at build_dir/main/src/synced_commands.cpp:227
#27 0x0000555555aa1c97 in synced_context::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, config const&, bool, bool, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)>) (commandname="attack", data=..., use_undo=true, show=false, error_handler=...)
    at build_dir/main/src/synced_context.cpp:72
#28 0x0000555556027986 in do_replay_handle(bool) (one_move=false) at build_dir/main/src/replay.cpp:877
#29 0x0000555556026380 in do_replay(bool) (one_move=false) at build_dir/main/src/replay.cpp:684
#30 0x0000555556016e4c in turn_info::handle_turn(config const&, bool) (this=0x7fffffffbb30, t=..., chat_only=false) at build_dir/main/src/playturn.cpp:102
#31 0x00005555560177b9 in turn_info::process_network_data(config const&, bool) (this=0x7fffffffbb30, cfg=..., chat_only=false) at build_dir/main/src/playturn.cpp:163
#32 0x000055555600d45d in playmp_controller::process_network_data(bool) (this=0x7fffffffb6f0, chat_only=false) at build_dir/main/src/playmp_controller.cpp:470
#33 0x000055555600c89a in playmp_controller::play_network_turn() (this=0x7fffffffb6f0) at build_dir/main/src/playmp_controller.cpp:332
#34 0x0000555556011d24 in playsingle_controller::play_side_impl() (this=0x7fffffffb6f0) at build_dir/main/src/playsingle_controller.cpp:389
#35 0x0000555556005ccd in play_controller::play_side() (this=0x7fffffffb6f0) at build_dir/main/src/play_controller.cpp:1151
#36 0x0000555556006006 in play_controller::play_turn() (this=0x7fffffffb6f0) at build_dir/main/src/play_controller.cpp:1193
#37 0x000055555601035c in playsingle_controller::play_scenario_main_loop() (this=0x7fffffffb6f0) at build_dir/main/src/playsingle_controller.cpp:175
#38 0x0000555556010c0c in playsingle_controller::play_scenario(config const&) (this=0x7fffffffb6f0, level=...) at build_dir/main/src/playsingle_controller.cpp:263
#39 0x0000555555e5aba4 in campaign_controller::playmp_scenario(end_level_data&) (this=0x7fffffffc080, end_level=...)
    at build_dir/main/src/game_initialization/playcampaign.cpp:225
#40 0x0000555555e5ae93 in campaign_controller::play_game() (this=0x7fffffffc080) at build_dir/main/src/game_initialization/playcampaign.cpp:288
#41 0x0000555555e4e8ed in (anonymous namespace)::enter_wait_mode((anonymous namespace)::mp_workflow_helper_ptr, int, bool) (helper=std::shared_ptr<(anonymous namespace)::mp_workflow_helper> (use count 3, weak count 0) = {...}, game_id=5512, observe=true) at build_dir/main/src/game_initialization/multiplayer.cpp:441
#42 0x0000555555e4f674 in (anonymous namespace)::enter_lobby_mode((anonymous namespace)::mp_workflow_helper_ptr, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, config const&) (helper=std::shared_ptr<(anonymous namespace)::mp_workflow_helper> (use count 3, weak count 0) = {...}, installed_addons=std::vector of length 17, capacity 32 = {...}, initial_lobby_config=...) at build_dir/main/src/game_initialization/multiplayer.cpp:558
#43 0x0000555555e4fd25 in mp::start_client(config const&, saved_game&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (game_config=..., state=..., host="server.wesnoth.org:15000") at build_dir/main/src/game_initialization/multiplayer.cpp:620
#44 0x00005555558d603b in game_launcher::play_multiplayer(game_launcher::mp_selection) (this=0x5555573a0cf0, res=game_launcher::MP_CONNECT)
    at build_dir/main/src/game_launcher.cpp:852
#45 0x00005555558497bf in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (args=std::vector of length 7, capacity 8 = {...}) at build_dir/main/src/wesnoth.cpp:869
#46 0x000055555584a164 in main(int, char**) (argc=7, argv=0x7fffffffe068) at build_dir/main/src/wesnoth.cpp:1143
```

**Comment by gfgtdf** [comment] 2018-05-11 00:32
probably the same cause as https://github.com/wesnoth/wesnoth/issues/2970

**Comment by CelticMinstrel** [comment] 2018-05-11 03:58
If it's confirmed to be the same, this should be marked as duplicate.

**Comment by gfgtdf** [comment] 2018-05-13 15:39
hmm ye it's not 100% sure yet, also note that one is really more drastic, while in the other one looks like a problem that could be solved by 'fixing' your wml code this one is really a blocker that effects many people that try to observe mp games


ftr, if someone wants to investigate, the way skip_replay works is probably just this line https://github.com/wesnoth/wesnoth/blob/1.14/src/replay.cpp#L683

**Closed** 2018-05-31 08:17 UTC
Labels: Blocker, Bug, Regression, UI, Units
