### ISSUE TITLE
(Re)move gzip/bzip2 command line compresion code from wesnoth.cpp 

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#8065] opened 2023-11-23 10:20 UTC
### Describe the desired feature

I was recently analysing Wesnoth initialisation code and stumbled upon command line (de)compression code. IMO, providing a compression tool in the game is out of scope and should be removed or moved to some other file than wesnoth.cpp.

**Comment by knyghtmare** [comment] 2023-11-23 12:38
I think the decompression is necessary for cache, save files, addons downloaded from the server so asking for it's removal sounds unnecessary.

**Comment by Pentarctagon** [comment] 2023-11-23 15:40
It's not really hurting anything, but yeah I've also wondered why someone bothered exposing this as command line options for wesnoth.

**Comment by Pentarctagon** [comment] 2023-12-07 20:35
Remove the gunzip/gzip and bunzip2/bzip2 code from wesnoth.cpp and commandline_options.cpp. Also remove any associated header includes.

**Comment by Pentarctagon** [comment] 2023-12-08 00:17
If you feel strongly about it then feel free to close the issue. Though I can't imagine anyone would actually need to use this functionality rather than just... using bzip2 or gzip.

**Comment by soliton-** [comment] 2023-12-08 10:04
While it is very common to have bzip2 or gzip installed on a UNIX-like OS that is not a requirement for running wesnoth and I doubt you can decompress either on windows for example without installing a thirdparty tool.

**Comment by grz0** [comment] 2023-12-08 11:36
@soliton-  How many players on Windows would come up with an idea to check command line arguments and use Wesnoth binary to decompress files instead of just installing 7-zip or other third-party tools?

**Comment by soliton-** [comment] 2023-12-08 12:09
No clue.

**Comment by AnkushSingh0710** [comment] 2023-12-09 05:26
I removed the code which is mentioned above and removed the header which is related to compression so should I go for pull request now

**Comment by ProditorMagnus** [comment] 2023-12-09 12:12
Is any of data/tools relying on this?

**Comment by CelticMinstrel** [comment] 2023-12-09 16:51
I did a quick search and didn't find anything in data/tools or utils that relies on this.

**Comment by AnkushSingh0710** [comment] 2023-12-10 05:43
the issue is solved or not?

**Comment by Pentarctagon** [comment] 2023-12-10 06:14
I think it depends on Soliton - I consider it to essentially be dead code, but it's definitely not something I feel strongly enough about that I'd want to force the issue.

**Comment by CelticMinstrel** [comment] 2023-12-10 18:14
Even if this is removed, is it not still possible to effectively decompress a saved game by disabling compression in Wesnoth preferences, opening the game, and resaving it? Although I'm not sure if that works for replays or start-of-scenario saves.

And I would expect that most people running Windows already have a way to open gzip or bzip files, whether it be in the native filesystem zip browser (no idea if that supports formats other than zip) or popular 3rd-party software like 7-zip. Any other OS ships with the tools to decompress these files.

In short, I agree with @grz0.

**Comment by soliton-** [comment] 2023-12-14 15:03
I disagree that exposing (de-)compression functionality that can be used to process wesnoth generated files is out of scope.

I guess the other implied argument is that no one uses this functionality because everyone will rather install a thirdparty tool that does this. I have no clue how to judge that for all platforms wesnoth runs on now and in the future.

Anyway if people think it's worthwhile to remove trivial code that has worked fine for years and this somehow makes wesnoth better then go ahead.

**Comment by CelticMinstrel** [comment] 2023-12-15 19:01
I don't feel that there's a reason to have it, but it's not something that I'd consider important to remove either.

**Comment by stevecotton** [comment] 2024-04-09 09:54
While not important to remove, I feel that it's good to make the `process_command_args` function simpler. I'm mildly in favor of this change.

**Closed** 2024-04-10 13:45 UTC
Labels: Enhancement, Good first issue, Engine
