### ISSUE TITLE
Memory corruption with damage-changing attacks (growing fury, concentrated)

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#2615] opened 2018-03-08 22:05 UTC
There are some units in Ageless Era whose damage changes during combat, and there's an easily reproducible memory corruption bug with both of these. Just use debug mode to summon a couple of units, and the crash generally happens before the end of the first combat.

* the Cyclops, with its "growing fury" melee attack
* the Rune Purist, with its "concentrated" ranged attack

Wesnoth: built on Linux from 13f9a9b18e2ed94609d2e6eae2336b39355a9f45
Ageless Era: 4.17.0

WML for those two attacks:
https://github.com/ProditorMagnus/Ageless-for-1-11/blob/4.17/data/ME_data/weapon_specials/concentrated.cfg
https://github.com/ProditorMagnus/Ageless-for-1-11/blob/4.17/data/EoMa_data/weapon_specials/growing_fury_new.cfg

**Comment by gfgtdf** [comment] 2018-03-09 22:49
this is likeley casued by #2526 We _could_ fix this by adding a unit_ptr for that unit somehere also changing the unit attack structure back to use unit_ptr s woudl be an option.


But note that we if we for exampel have two of the same attack related event, and the first one changes (by store/unstore) the unit and the second filters based on the units attack specials or similar (this is probably what happens is probably happeening in this report). Even if we fix the memeory corruption by adding unit_ptrs we changed behviour compared to 1.12 since in the second event will still filter based on the 'outdated' unit.

**Comment by stevecotton** [comment] 2018-03-10 00:31
This might be an edge case where UMC authors already expect trouble, and are even already looking forward to changes.

WhiteWolf's How to make one unit stop striking during an attack: https://forums.wesnoth.org/viewtopic.php?f=21&t=47711#p622216

@ProditorMagnus please would you comment w.r.t. "growing fury / concentrated"?

**Comment by CelticMinstrel** [comment] 2018-03-10 00:35
If it's memory corruption, would it be possible to get a stack trace for the out-of-bounds write(s)?

**Comment by ProditorMagnus** [comment] 2018-03-10 00:53
With growing fury I forward to @inferno8 and @ForestDragon-wesnoth

I expect it is possible to rewrite such ability to directly modify health, instead of changing damage, but that would cause much more work. Another workaround would be [damage] filter_self with events counting hits, which is not better either.

**Comment by CelticMinstrel** [comment] 2018-03-10 01:47
Okay, I see what the problem is here (the unit object that initiated the attack no longer exists). One possibility I can think of is to change how `[unstore_unit]` works  when _replacing_ a unit that's already on the map - instead of removing the old one and adding the new one, it could destroy the old one in-place and construct the new one at the same location.

There's still some potential issues with that, though. In particular, the reference to the weapon will still be invalid if you simply destroy and reconstruct; if you want to keep the weapons valid too you'd have to use the same strategy on each weapon individually (but of course removing any that have actually been removed from the unit).

---

I'd also note that these abilities are likely better implemented via effects rather than a store-unstore action, similar to how the ghoul's special ability is done. I think it's still a good idea to fix the issue anyway, though.

**Comment by CelticMinstrel** [comment] 2018-03-10 02:16
@gfgtdf - Does something like that commit look like it could work?

**Comment by jyrkive** [comment] 2018-03-10 07:56
IMO, instead of attempting to support the current implementation of growing fury and concentrated, it would be better to just throw a WML error (but make sure that equivalent abilities can be implemented with effects).

**Comment by ProditorMagnus** [comment] 2018-03-10 10:32
Consider that ghoul effect is permanent. Is there good way to remove effects now?

**Comment by CelticMinstrel** [comment] 2018-03-10 15:16
It's possible to remove them, yes. In WML, there's the `[remove_object]` tag, which only allows removing `[object]` modifications. Lua has `wesnoth.remove_modification` which can even remove traits and advancements.

Certainly a WML error is better than memory corruption. I generally prefer to preserve compatibility when possible, though. Still, if the consensus is _not_ to do so in this case, I guess I can just raise an error instead.

**Comment by gfgtdf** [comment] 2018-03-10 15:18
about your commit:
i also had a simlar idea, but i don't think it coompleteley fixes this problem, for example if for some reason the umc code [store_unit]s the unit with kill=yes and then unstores it, the changes won't apply.


what i currently think woudl be best, in particular considering 1.14 is coming soon is to
1) prefer referencing the unit by it's location like it also happend in 1.12, that is use the unit* in the attack struct only when the unit is not on the map.
2) change it back to using unit_ptr, i am also going to createa pr soon that makes sure all units are always owned by unit_ptrs

**Comment by gfgtdf** [comment] 2018-03-10 17:24
oh and another imporant thing: specials_context_t can crash in it's dtor if the attack it references was removed (whihc can even happen if the unit is not reset at all), luckily attack_type is already memepory managed so changing `const attack_type& parent;` to `shared_ptr<attack_type>` codul fix that part.

**Comment by CelticMinstrel** [comment] 2018-03-10 18:01
While I doubt this would be an issue in practice (the attack is probably held by another pointer somewhere else when the `specials_context_t` is destroyed), it certainly wouldn't hurt to play it safe and do as you suggest.

**Comment by jyrkive** [comment] 2018-03-10 18:12
@gfgtdf is working on fixes. Unassigning this from myself. (@Vultraz should never have assigned this one to me in the first place.)

**Closed** 2018-03-11 06:36 UTC
Labels: Bug
