### ISSUE TITLE
[1.17][help] long loading time to display license

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#7850] opened 2023-08-15 21:00 UTC
The help in 1.17 as of ac16fb150b3 is very buggy.
A place where on notices this in particular: Viewing the license in the help takes several seconds.

**Comment by knyghtmare** [comment] 2023-08-15 21:37
Confirmed. Took 61 secs. I thought my client froze.

**Comment by stevecotton** [comment] 2023-08-16 11:32
Likely a duplicate of #6845, which has an (old) bit of code that take O(n^2) time to line-break the text.

**Comment by Wedge009** [comment] 2023-08-17 01:58
It looks to me like the same report. I request this is closed in favour of #6845.

**Closed** 2023-08-17 02:07 UTC
Labels: Duplicate, Enhancement, Confirmed, Help
