### ISSUE TITLE
SotB Sc.7 Scorpions

### ISSUE THREAD

**Issue by rmj555** [wesnoth/wesnoth#5419] opened 2021-01-12 17:08 UTC
The opening dialog says that blunt weapons are worthless, but in fact they are best at killing scorpions.

**Comment by knyghtmare** [comment] 2021-01-12 17:11
Actually, the Giant Scorpions in S7 of SotBE are of the Sand Scuttler variation and these have a 70% impact resistance.
The default Giant Scorpion has -10% impact resistance. So, the dialogue is correct.

**Comment by rmj555** [comment] 2021-01-14 16:25
I disagree. Impact has a -10% resistance. Your photo is not what I see.

**Comment by doofus-01** [comment] 2021-01-17 02:53
I see what knyghtmare sees, really no room for confusion, even on "unit description".  You didn't say what version you were using, anything recent?

**Comment by Konrad22** [comment] 2021-01-17 10:15
I went and checked 1.14.15 and 1.15.9, and in both of them the Scorpions have 70% impact resistance.

**Comment by rmj555** [comment] 2021-01-17 16:42
1.15.8 on Windows 10 from Sourceforge.

**Comment by doofus-01** [comment] 2021-01-18 04:08
Thanks.  I don't think this is OS-dependent, and three people have been unable to reproduce the error, so there must be some sort of misunderstanding.  Please post any further info that might help, otherwise this issue should be closed.

**Comment by Konrad22** [comment] 2021-01-18 07:28
@rmj555 Would you mind posting a screenshot and a savefile? That might clear up things.

**Comment by sevu** [comment] 2021-01-18 21:55
I want to point out that changes in the scenario code from newer version will only come into effect when staring fromt he start-of-scenario save. Mid-turn saves, including the turn-1 save, will still have the old code. Maybe that's it?
At an earlier point - or in case you use a save from 1.14 - normal scorpions were used in that scenario.

**Comment by doofus-01** [comment] 2021-01-19 02:31
Looking at the history of scorpions, old scorpions (when the campaign strings were likely written) had the 70% impact resistance, it was changed "recently" and then the Sand Scuttler variation was added to keep old resistances. https://github.com/wesnoth/wesnoth/commit/b8fecb7994af9063d1d736bab781196aea3dbd04#diff-13de0f79a41e719fbd53937639295bb3ff3fa478134895f52be9ef513978de1d

Granted, the variation is a recolor so it may look similar, but in the context of that scenario everything seems fine, and old saves shouldn't be an issue.  As far as I can tell, the variation mechanic is working just fine (debug create a unit to test).  I'm pretty sure we can close this.

**Closed** 2021-01-25 02:22 UTC
Labels: Prose, Works for me
