### ISSUE TITLE
ci report cannot distinguish between failed and canceled builds

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2581] opened 2018-03-03 17:18 UTC
This is probably an upsteam issue, but i'll post it anways since our ci maintainer (iirc that is @Pentarctagon ?) might know better. 

next to the commits you curently eigher see a red cross or a green hook that indicates whether the ci build passed or not. It also alsows the red cross if a build was calceled, iirc not too long ago it would instead show a septerate symbol (somethign grey, but i don't rmember what exactly) in case that a build was calceled, it's quite annoying that this was lost, in particular since we calcel ci builds quite often which results in many red crosses in our commit list. This not only makes it harder find the real problameic commit in case that something really broke, it also makes the people unsensible against failing ci reports since they are quite likely just false-positive reports nowdays.

This effects both the appveyor reports and the traivs reports.

**Comment by Pentarctagon** [comment] 2018-03-03 17:45
It looks like this is a github limitation, in that it only has [statuses](https://help.github.com/articles/about-statuses/) for pending, passing, or failing, while github's [API documentation](https://developer.github.com/v3/repos/statuses/) also lists "errored" as a status.  The AppVeyor and Travis build history does show the difference between canceled and failed, though.

**Comment by soliton-** [comment] 2018-03-04 19:35
Why/How is this a regression?

**Comment by gfgtdf** [comment] 2018-03-04 20:14
i thought it did have grey symbol on github not too long ago but i might be wrong.

**Comment by Pentarctagon** [comment] 2018-03-16 19:54
Closing since there's nothing anyone here can do about this right now, and if/when this does get implemented there would also be nothing we'd have to do on our end.

**Closed by Pentarctagon** 2018-03-16 19:54 UTC
Labels: Services, Upstream issue
