### ISSUE TITLE
SotA - Lua error for zombie_recruit_dialog

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#5160] opened 2020-09-21 04:00 UTC
### Game and System Information
 - What version of the game are you running?
1.15.5+dev
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
source 
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
98d4411fe23
 - What OS are you running?
Linux
### Describe the bug
Got to little castle in first scenario, tried to recruit a zombie, got a Lua error:

 `stack traceback:
        [C]: in field 'find'
        .../Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua:79: in upvalue 'preshow'
        lua/backwards-compatibility.lua:89: in function <lua/backwards-compatibility.lua:86>
        [C]: in upvalue 'old_show_dialog'
        lua/backwards-compatibility.lua:84: in field 'show_dialog'
        .../Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua:148: in main chunk
        [C]: in field 'dofile'
        [string "wesnoth.dofile 'campaigns/Secrets_of_the_Anci..."]:1: in local 'bytecode'
        lua/wml-tags.lua:266: in local 'cmd'
        lua/wml-utils.lua:144: in field 'handle_event_commands'
        lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
`

### To Reproduce

Try to recruit in the first scenario

### Savefiles
If applicable, attach savefiles to help explain your problem. (To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.

**Comment by stevecotton** [comment] 2020-09-21 09:25
I can reproduce this. Here's the first line of that Lua error, along with newlines in the stack trace:
```
error scripting/lua: .../Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua:79: bad argument #1 to 'find' (widget expected, got no value)
stack traceback:
	[C]: in field 'find'
	.../Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua:79: in upvalue 'preshow'
	lua/backwards-compatibility.lua:89: in function <lua/backwards-compatibility.lua:86>
	[C]: in upvalue 'old_show_dialog'
	lua/backwards-compatibility.lua:84: in field 'show_dialog'
	.../Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua:148: in main chunk
	[C]: in field 'dofile'
	[string "wesnoth.dofile 'campaigns/Secrets_of_the_Anci..."]:1: in local 'bytecode'
	lua/wml-tags.lua:266: in local 'cmd'
	lua/wml-utils.lua:144: in field 'handle_event_commands'
	lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
```

**Comment by Pentarctagon** [comment] 2020-09-21 14:01
I'd guess it's most likely due to 7b2ede62432485791580033cdf2e013fe8f2269f

**Comment by stevecotton** [comment] 2020-09-21 14:23
The commit after that, 661fc1d8efb8c8ff89d9a771c2a68812c19499a4, "makes the widget parameter of widget.find manditory". So I guess it was okay when 7b2ede6 was committed (haven't tested that), but broken afterwards.

As @CelticMinstrel said on IRC, please would @gfgtdf add documentation for the new GUI2 widgets API, preferably on https://wiki.wesnoth.org/LuaAPI/wesnoth/gui/widget

**Comment by CelticMinstrel** [comment] 2020-09-24 02:41
I think the correct fix for this issue is to merge all of backwards-compatibility.lua into core.lua. It may also require some C++ changes to ensure that the new GUI2 API is actually available in the mapgen kernel.

**Comment by gfgtdf** [comment] 2020-09-24 23:03
> I think the correct fix for this issue is to merge all of backwards-compatibility.lua into core.lua. It may also require some C++ changes to ensure that the new GUI2 API is actually available in the mapgen kernel.

I think this is unrelated to the lua maqpgen kernel, i probably just messed something up while  rebasing the pr.

**Comment by CelticMinstrel** [comment] 2020-09-25 04:41
Hmm. You might be right, actually. Never mind then! (Although what I said is still a good idea.)

**Comment by Pentarctagon** [comment] 2020-09-25 14:05
This has been fixed with 21a1220273858d53a92aabe963b0b5a35360fc1a I assume?

**Comment by stevecotton** [comment] 2020-09-25 20:48
It now works if you can only recruit one or two types of zombies. Once you can recruit 3 variations, the Lua error below occurs (to test this, on the first scenario kill a rat, a wolf and one of your own bats).

```error scripting/lua: .../Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua:115: bad argument #2 to '__index' (invalid propertly of widget)
stack traceback:
	[C]: in metamethod '__index'
	.../Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua:115: in upvalue 'preshow'
	lua/backwards-compatibility.lua:89: in function <lua/backwards-compatibility.lua:86>
	[C]: in upvalue 'old_show_dialog'
	lua/backwards-compatibility.lua:84: in field 'show_dialog'
	.../Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua:147: in main chunk
	[C]: in field 'dofile'
	[string "wesnoth.dofile 'campaigns/Secrets_of_the_Anci..."]:1: in local 'bytecode'
	lua/wml-tags.lua:266: in local 'cmd'
	lua/wml-utils.lua:144: in field 'handle_event_commands'
	lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
```

**Comment by gfgtdf** [comment] 2020-09-25 21:32
> It now works if you can only recruit one or two types of zombies

This is actually really strange since i the 'size' attribute of widgets should be undefined (at least i didn't see it in the implementation) even if you can only recruit 2 types of zombies.

**Comment by gfgtdf** [comment] 2020-09-25 22:30
nevermind i forgot that the dialog is only active when there are Y2 types of zombies

**Comment by gfgtdf** [comment] 2020-09-26 19:29
fixed in https://github.com/wesnoth/wesnoth/commit/e313334e62564dd3b1b97c90d70db3864fc2487c

**Comment by Pentarctagon** [comment] 2020-09-26 19:42
Closing then.

**Closed by Pentarctagon** 2020-09-26 19:42 UTC
Labels: Blocker: Point, Bug, Campaign
