### ISSUE TITLE
Multiplayer Desync if slot 1 is idle/empty

### ISSUE THREAD

**Issue by TheFlamelet** [wesnoth/wesnoth#8221] opened 2024-01-07 18:34 UTC
### Game and System Information

- **1.16:**
- **Not steam**
- **NA**
- **OS:**

### Description of the bug

Hello, 
people joined my game and we left slot 1 empty, and choose other slots. However, when turn is ended, the next player never recieves notification.

Desync messages appear for every recruit even before ending the turn.

### Steps to reproduce the behavior

1. Choose a map from your editor
2. host the map on wesnoth server
3. leave slot 1 empty.
4. you will have desync with other players.

### Expected behavior

Empty slots should not cause any desync, including 1st slot.

**Comment by gfgtdf** [comment] 2024-01-07 18:45
Seems to be the same as #3899 thx for bringing it back to our attention.

**Comment by Wedge009** [comment] 2024-01-09 23:25
Closing as duplicate of #3899.

**Closed by Wedge009** 2024-01-09 23:25 UTC
Labels: Bug, Duplicate, MP
