### ISSUE TITLE
SEGFAULT on trying to add third player to the first team for user map (local multiplayer mode)

### ISSUE THREAD

**Issue by kostgr** [wesnoth/wesnoth#5718] opened 2021-04-18 15:29 UTC
Battle for Wesnoth v1.15.11 x86_64 (packaged for openSuse 15.2)

Some last month we experience segmentation fault on trying to setup local multiplayer game for own map.
It comes each time we try to make one team of at least three players. Adding third one leads constantly to segfault.

Output of gdb:

Thread 1 "wesnoth" received signal SIGSEGV, Segmentation fault.
0x00005555559265f7 in gui2::find_widget<gui2::drawing> (widget=widget@entry=0x5555573492c0, id="leader_image", must_be_active=must_be_active@entry=false, must_exist=must_exist@entry=true)
    at /usr/src/debug/wesnoth-1.15.11-lp152.54.1.x86_64/src/gui/auxiliary/find_widget.hpp:73
73              T* result = dynamic_cast<T*>(widget->find(id, must_be_active));
Missing separate debuginfos, use: zypper install Mesa-dri-nouveau-debuginfo-19.3.4-lp152.27.1.x86_64 Mesa-libGL1-debuginfo-19.3.4-lp152.27.1.x86_64 ...

**Comment by knyghtmare** [comment] 2021-04-18 15:30
Duplicate of #5648

**Closed** 2021-04-18 16:07 UTC
Labels: Duplicate
