### ISSUE TITLE
Game crash when opening preferences dialog.

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#7482] opened 2023-03-24 22:14 UTC
### Game and System Information

- **Version:** 1.16.8
- **Downloaded from:** GitHub
- **Build info:** built with scons
- **OS:** Ubuntu 22.04

### Description of the bug

When opening the preferences dialog, the game sometimes crashes with:
```
X Error of failed request:  BadRROutput (invalid Output parameter)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  9 (RRGetOutputInfo)
  Serial number of failed request:  1065147
  Current serial number in output stream:  1065147
Segmentation fault (core dumped)
```
It doesn't always happen and so far it only happend when i opened the preferences dialog from playing a game.

**Comment by Pentarctagon** [comment] 2023-03-24 22:20
It mentions the "X Error", so this sounds like it's a problem with the desktop environment perhaps? Wesnoth itself certainly doesn't attempt to interact with X directly.

**Comment by gfgtdf** [comment] 2023-03-24 22:23
But indirectly, and i forgot the last line, the segfault _could_ be on our end. maybe we don't check for an SDL function returning NULL or simething like that.

That said, i have no idea how to debug the destktop environment.

**Comment by Wedge009** [comment] 2023-03-24 23:38
Can't say I've encountered this. 1.16 or master, Linux or Windows.

Ever happen with a fresh preferences file?

**Comment by gfgtdf** [comment] 2023-03-24 23:59
Stacktrace :

```
....
#10 0x00007fed6a464495 in __run_exit_handlers
    (status=1, listp=0x7fed6a638838 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:113
#11 0x00007fed6a464610 in __GI_exit (status=<optimized out>)
    at ./stdlib/exit.c:143
#12 0x00007fed69b527cb in  () at /lib/x86_64-linux-gnu/libX11.so.6
#13 0x00007fed69b528f4 in _XError () at /lib/x86_64-linux-gnu/libX11.so.6
#14 0x00007fed69b529f7 in  () at /lib/x86_64-linux-gnu/libX11.so.6
#15 0x00007fed69b544d5 in _XReply () at /lib/x86_64-linux-gnu/libX11.so.6

#16 0x00007fed69ac2fa2 in XRRGetOutputInfo ()
    at /lib/x86_64-linux-gnu/libXrandr.so.2
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x00007fed6ad5afe3 in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#18 0x00007fed6ad32f0e in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#19 0x000055ca792816f5 in CVideo::get_available_resolutions(bool)
    (this=0x55ca7a5d7ae0, include_current=include_current@entry=true)
    at src/video.cpp:436
...

```
Seems to happen rather consistantly now

**Comment by Wedge009** [comment] 2023-03-25 01:07
Steps to replicate? I still cannot confirm, and don't see anyone else confirming, so not sure it's not unconfirmed.

**Comment by gfgtdf** [comment] 2023-03-25 01:19
I mean, i can reproduce it and i'm a developer of wesnoth which should be enough. But of course it depends what the intention behind the "unconfirmed" label is.

This bug is by nature platform-specific and also not that easy to reproduce, it now happend 3 times, so far always during longer games. I didn't manage to reproduce it in a quick way yet.

**Comment by Pentarctagon** [comment] 2023-03-25 01:46
It's fairly bizarre that getting a list of available resolutions would succeed or fail based on how long a game has been going - the list of available resolutions is constant per screen. How long of a game does it take for you to be able to reproduce the issue?

**Comment by Zireael07** [comment] 2023-03-25 10:39
Hmm, I know some other SDL projects have problems when left running for very long (like a couple days long) and most issues pointing to that are closed as driver issues - maybe it's again a driver problem?

**Comment by gfgtdf** [comment] 2023-03-26 02:10
> . How long of a game does it take for you to be able to reproduce the issue?

Idk it doesn't always happen and so far it always happens when i didn't expect it. Often (but i don't think always) i have the game open for quite some time, so something else and then come back to wesnoth.

> maybe it's again a driver problem?

Maybe,  not sure, but i have every little knowledge in that area to say something here.

**Comment by gfgtdf** [comment] 2023-06-03 19:40
Just happend again, i started wesnoth (current master), then went outside to go biking, and when i went home an opened the preferences dialog  i got this error :/

**Comment by Wedge009** [comment] 2024-03-27 02:51
Do you still get this with 1.18?

**Comment by gfgtdf** [comment] 2024-03-28 01:53
I didn't  play that much recently, so i cannot really tell for now.

**Comment by Wedge009** [comment] 2024-05-02 22:39
I'm not sure if this should remain open since it looks like no-one besides gfgtdf has encountered the issue, and not for quite some time, it seems.

**Closed** 2024-07-09 04:14 UTC
Labels: Bug, Needs more info, Engine
