### ISSUE TITLE
Crashes at various spots when sound is enabled (GNA #23026)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1434] opened 2017-05-08 09:24 UTC
**[Original submission](https://gna.org/bugs/index.php?23026)** by anonymous on 2014-12-05

These spots include :

1) The game can crash when music is enabled and a track ends, both in menu and ingame.

2) When sound is enabled, it crashes as soon as the game gives you ability to control your units.

3) When joining the official server, the game crashes upon being whispered. Once again, only when sound is enabled.

The see more info on "is not responding" window blames libvorbis-0.dll

For now, as a workaround disabling all the sound options stops the game from crashing.

(Reproduced on Windows XP SP3)
Release: 1.12.0
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 09:24
**Modified on 2014-12-22**

**shadowmaster wrote:**

> Can't reproduce on Windows 8.1. I haven't tested XP, but I suspect this is an extremely uncommon issue since nobody else has posted about it here or in the forums.
> 
> 
> 
> I assume you made sure that your sound drivers are correctly installed and up to date, right? Is there anything unique about your system that might be relevant for this bug?

**Comment by wesnoth-bugs** [comment] 2017-05-08 09:24
**Modified on 2015-05-06**

**anonymous wrote:**

> Reported solved here:
> 
> 
> 
> http://forums.wesnoth.org/viewtopic.php?f#4&t42429

**Comment by wesnoth-bugs** [comment] 2017-05-08 09:24
**Modified on 2015-05-06**

**shadowmaster wrote:**

> It's not really solved until our packaging on Windows is changed accordingly or someone figures out why this is happening with newer libraries in the first place.
> 
> 
> 
> I'd also like to note that I've been experiencing a variation of this issue on Debian 8 (i.e. not Windows) when returning to the MP lobby (which has no music) from a game with music enabled. I haven't decided yet whether to file a separate bug report or not, but for the time being I'd say this bug is not fixed.

**Comment by wesnoth-bugs** [comment] 2017-05-08 09:24
**Modified on 2015-07-01**

**loonycyborg wrote:**

> Just replacing vorbis dll with one suggested in forum triggered another bug so 1.12.4a contains libvorbis 1.3.5, the latest version I compiled from source. Please test if this issue still happens with 1.12.4a

**Comment by Vultraz** [comment] 2018-02-07 23:12
Since there's been no evidence this issue or #1446 affected any Windows version other than XP, I'm closing this and #1446. We indeed don't officially support XP anymore in 1.13.

**Closed by Vultraz** 2018-02-07 23:12 UTC
Labels: Audio, Bug, Windows, Won't fix

**Comment by Vultraz** [comment] 2018-02-07 23:15
As for the lobby music issue, @shikadilord confirmed it was an upstream packaging issue with `libvorbisfile` on Debian and Ubuntu that has since been fixed.
