### ISSUE TITLE
Rectangles are not drawn correctly

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#6799] opened 2022-06-25 00:34 UTC
### Game and System Information

The Battle for Wesnoth version 1.17.5+dev (666571ca-Clean) x86_64
Running on Freedesktop.org 21.08.14 (Flatpak runtime) x86_64
Distribution channel: Default

#### Libraries

Boost:             1.66
Lua:               5.4.4
OpenSSL/libcrypto: 1.1.1m (runtime 1.1.1o)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.48.10 (runtime 1.48.11)
SDL:               2.0.16 (runtime 2.0.16)
SDL_image:         2.0.5 (runtime 2.0.5)
SDL_mixer:         2.0.4 (runtime 2.0.4)

#### Current video settings

SDL video drivers:        [x11] wayland dummy
Window size:              1920x1015
Game canvas size:         1920x1015
Final render target size: 1920x1015
Screen refresh rate:      60

### Description of the bug

Screenshots:
![image](https://user-images.githubusercontent.com/3605541/175750841-731cf75d-82c5-4e87-afe6-0ce8eb610cb5.png)
![image](https://user-images.githubusercontent.com/3605541/175750850-2cd8d04d-0c57-44f1-a00b-5944baf85817.png)
![image](https://user-images.githubusercontent.com/3605541/175750857-5599f67a-c653-473a-bf69-4a115fcae7f8.png)

### Steps to reproduce the behavior

1. Start wesntho

**Comment by mesilliac** [comment] 2022-06-25 00:52
After some discussion on discord it looks like this is caused by an SDL bug: https://github.com/libsdl-org/SDL/issues/4001

It seems to have been introduced sometime around SDL 2.0.15 and fixed sometime around 2.0.18, and only affects some systems.

I'll look into putting an override in to draw rectangles a different way for bad SDL versions.

**Comment by Wedge009** [comment] 2022-06-25 09:57
I noticed this a while back too. Windows build via vcpkg is using SDL 2.0.22 and I don't observe the issue, but I do in Ubuntu 20.04.4, which uses 2.0.16.

Is it known what is the differentiator in only affecting 'some' systems?

**Comment by mesilliac** [comment] 2022-06-25 11:01
The upstream issue mentioned the openGL renderer specificaly having the issue, but it seemed like something they had trouble with in various forms at different times. It must be a bit of a nightmare keeping everything pixel-perfect on all the different systems.

**Comment by mesilliac** [comment] 2022-06-26 09:27
This should now be fixed in master. I assume the next nightly flatpak will pick it up.

**Closed by mesilliac** 2022-06-26 09:27 UTC
Labels: Bug, Confirmed, Upstream issue, Graphics

**Comment by Wedge009** [comment] 2022-06-26 10:44
Looks good to me in the final version too. Thanks.

**Comment by grz0** [comment] 2022-06-26 14:06
I  tested the latest flatpak build (76422acb), the issue has been fixed. Thanks.
