### ISSUE TITLE
Downloading or deleting an add-on resets certain hotkeys

### ISSUE THREAD

**Issue by inky17** [wesnoth/wesnoth#2532] opened 2018-02-21 02:32 UTC
I added a hotkey for recruit ('r', which was previously assigned to redo) and then downloaded an add-on (removing an add-on has the same effect).
After exiting the add-on server, the 'r' hotkey went back to being assigned to redo instead of recruit.

(Wesnoth 1.13.11, Windows 10)

**Comment by GregoryLundberg** [comment] 2018-02-21 02:46
Removed Redo(r)
Reassigned Redraw as (r)
Installed a random add-on
Checked
Redo is once-again (r)
Redraw is once-again (ctrl-d)

Wesnoth 1.13.11+dev / Arch

**Comment by jyrkive** [comment] 2018-02-21 04:35
Likely caused by Wesnoth not saving preferences until exit. Installing an add-on causes the entire game state to be reloaded, apparently including preferences.

The best way to fix would be to save preferences earlier (e.g. when the preferences window is closed). It would be useful also for development: I often change a preference, then do something that makes the game crash or kill it in a debugger. On the next start, the preference will have changed back because it was never saved to disk.

**Comment by Vultraz** [comment] 2018-02-21 06:07
The save-to-disk fix doesn't work.

**Closed** 2018-02-21 06:49 UTC
Labels: Blocker, Bug, Confirmed
