### ISSUE TITLE
Weird RtL language indentations at the `Help` menu.

### ISSUE THREAD

**Issue by ghost** [wesnoth/wesnoth#2633] opened 2018-03-11 17:09 UTC
![https://frupic.frubar.net/shots/36546.png](https://frupic.frubar.net/shots/36546.png)
[https://frupic.frubar.net/36546](https://frupic.frubar.net/36546)

How to get a screen like that:

* Choose a right-to-left language (Arab works better if you don't understand none, because the translation is a lot less complete than Hebrew).

* Select `مساعدة` (`Help`).

* Click `Encyclopedia`.

* Click `Geography`. the _Geography_ line borns under indented instead of extra indented. That is wrong but in some way under control.

* Click any _Geography_ e.g. `Great Ocean`. The _Geography_ subs lines born under indented one level respect to _Geography_, two levels respect to _Encyclopedia_.
  * On my macOS host and configuration, keeps usable with all texts in the screen. Some text parts are outside the black panel though, text written out of the black panel aren't cleared before each rewrite:
![https://frupic.frubar.net/shots/36548.png](https://frupic.frubar.net/shots/36548.png).
  * On my iOS device and version and configuration, chunks of text go out of the screen. I think it's behaving similar to macOS but just feels worse because there only the black panel is shown.

Versions information:

* TBfW `1.13.11` for macOS, official binaries `Wesnoth_1.13.11.dmg` (size 424.149.414b sha256 `aa5cea07f6465bf5fa41736f22f3141ea7db3c88fd3c3b08bdc3aff0c9a0cff1`). Using macOS High Sierra.

* TBfW `RC_VERSION_MAJOR.RC_VERSION_MINOR.RC_VERSION_REVISION` for iOS, (I think it's TestFlight `1.13.11 (32)`. Using iOS `10.3.3 (14G60)` on a `MD523TY/A` device.

**Comment by jyrkive** [comment] 2018-03-11 17:27
This isn't too surprising. The help browser has poor RTL support because it uses GUI1.

**Comment by CelticMinstrel** [comment] 2018-03-11 18:06
This may be low priority if the Arabic and Hebrew translations aren't complete enough to ship, though.

**Comment by Wedge009** [comment] 2018-03-18 11:17
I can reproduce this one too. Maybe not too many people using these languages or aren't looking at the Help too much.

I understand Help conversion to gui2 is still in progress.

**Comment by Wedge009** [comment] 2019-10-15 23:27
I note with the minimum translation threshold there doesn't appear to be any RtL languages available for 1.14.9 any more.

**Comment by Wedge009** [comment] 2021-09-14 08:29
Only closing this one in favour of #5600 because that one has already been assigned.

**Closed by Wedge009** 2021-09-14 08:29 UTC
Labels: Bug, UI, Low Priority, Help
