### ISSUE TITLE
add support for key "mode=insert" to [object] (GNA #23779)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1500] opened 2017-05-08 10:35 UTC
**[Original submission](https://gna.org/bugs/index.php?23779)** by tekelili on 2015-08-12

Currently [object] resembeles only "mode=append" behavior

(Reproduced on any)
Release: 1.13
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment] 2017-05-08 10:35
**Modified on 2015-08-12**

**tekelili wrote:**

> I guess [object] mode=insert would be irrelevant (or not possible to behave correctly when applied), but it would be still usefull decide order of objects for the moment unit levels up.

**Comment by Pentarctagon** [comment] 2021-08-22 07:46
Closing due to a lack of any provided use case for this.  Also this feels like it would be prone to behaving in unexpected ways compared to what was intended.

**Closed by Pentarctagon** 2021-08-22 07:46 UTC
Labels: Enhancement, WML
