### ISSUE TITLE
Chat text lines overlap

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#7184] opened 2022-12-01 14:10 UTC
When there are multiple lines of text in the top left corner of the screen, the black background of each line partially obscures the line above it.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/578731/205074210-82e7e1d6-f3d1-41c3-b3a0-e5d43c388561.png">

**Comment by knyghtmare** [comment] 2022-12-01 14:13
Duplicate of #7100

**Closed** 2022-12-01 15:14 UTC
Labels: Bug, Duplicate, UI
