### ISSUE TITLE
Deprecate [advancefrom]

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3955] opened 2019-02-28 16:17 UTC
It is common cause of OOS issues

It uses old name format https://forums.wesnoth.org/viewtopic.php?p=484571#p484571

It is the only way to modify units types after they have already been created (+tag may only affect last one, so does not count as completely created)

**Comment by ProditorMagnus** [comment] 2019-02-28 16:18
It might be useful to create new issue to define [advance_from] in a way that does not cause OOS so easily.

**Comment by gfgtdf** [comment] 2019-02-28 16:51
related issue https://github.com/wesnoth/wesnoth/issues/1451, basically the idea is to have a new tag that goes into [scenario], [era] etc and only changes the advancements for the game that uses it.

**Comment by ProditorMagnus** [comment] 2019-02-28 21:37
I checked that the first link did not in fact have advancefrom, so I removed the reference.

**Comment by CelticMinstrel** [comment] 2019-03-01 02:05
Surely the OOS issues caused by `[advancefrom]` are solvable by somehow ensuring both clients have precisely the same environment - for example, sending a list of enabled addons and a list of preprocessor defines over the network. Without that, could there even _be_ a way to define `[advancefrom]` that doesn't risk OOS issues?

**Comment by gfgtdf** [comment] 2019-03-01 03:30
> I checked that the first link did not in fact have advancefrom, so I removed the reference.

Yes the OOS from that one are probably casued by global traits, (which we shodul also fix but thats a differnt issue)

> Surely the OOS issues caused by [advancefrom] are solvable by somehow ensuring both clients have precisely the same environment 

Yes but that's not really practical, in particular since config reloads are a major annoyances in the current design,. The best one can currently do in 1.14 is to change the advancement of each unti individually via lua/wml code (see https://forums.wesnoth.org/viewtopic.php?f=21&t=49257&p=637311#p637202 for a sample code)

> Without that, could there even be a way to define [advancefrom] that doesn't risk OOS issues?

Well you coudl for example add some contional to when they are used like [advancefrom] era=my_era_id will onyl enable that advancemefrom when the era that defined that unti is actualyl used, i still think having the [fix_advancemnt] tag in [era] as suggested in #1451 is the better plan though.

**Comment by CelticMinstrel** [comment] 2019-03-01 04:36
> (which we shodul also fix but thats a differnt issue)

I'm pretty sure it would become the same issue if you were to approach it in the way I just suggested. I understand why you say it's not practical, but I really think we should find a way to _make_ it practical.

> era=my_era_id will onyl enable that advancemefrom when the era that defined that unti is actualyl used

Well, this idea doesn't require deprecating or really even fundamentally changing `[advancefrom]` though.

**Comment by sevu** [comment] 2019-03-02 21:13
The spot [advancefrom] is supposed to fill, is that the information for advancements in the help is the same like the on map unit. And that generally works bad.
1) It works only fine for single player, and only if the author did guard it with a define. Not usable for Eras - which are the big field where people _would_ want to use it. (People made many sprites for advancements of core units)
2) the other way around, having a custom unitadvancing to a core unit, looks bad in the help. You'll see that multiple units with the same name advance to some unit. These are dummy units, which are exactly the same, except that the lvl 3 one adds a lvl 4 advancement. To solve the help issue, one adds even more dummy units.

While people generally like to copy-paste things and change a single line, because it works without knowledge, it doesn't go well, the next time somebody adjusts the description in mainline the translation is lost.
Thing is, people developing for Wesnoth have no experience. Even if they have, it's a custom language. They won't have everything on the scope. OOS, translations, help system... some point will go wrong.

/rant

I think a proper solution requires that MP add-ons are seperated from each other, like SP campaigns are.  @shikadiqueen made some draft of such an add-on system years ago IIRC. Not sure if it's opening a new can of worms for add-ons which should modify other add-ons.

The other area where I can imagine a solution. Changes to the help system (which was intended to rewritten for GUI2, if thing's didn't go as they did).

**Comment by sevu** [comment] 2019-03-02 21:15
The places in mainline which use [advancefrom] have generally no need for it.

**Comment by CelticMinstrel** [comment] 2019-03-02 23:44
I wouldn't've expected the help rewrite to address any of that, since it's just about the visual display of the help and not its content.

**Comment by ProditorMagnus** [comment] 2019-03-20 21:01
Adding reference to e4c4ca7572b2986790f40ee20b1ccb2e6e85252a in case it will not be added to wiki by the time this issue is closed.

**Comment by gfgtdf** [comment] 2019-04-01 20:37
now with [unit_type_fix] we coudl also implement [advancefrom] in a not-oos-casusing way:

We remove the old [advancefrom] and instead in the config loading code (fore the addons config is merged into the game_config) do something like (pseuidocode)
```
for u in addon_cfg.child("units").child_range("unit") do
  for adavnefrom in u.child_range("advancefrom") do
    for child in addon_cfg.all_child_range() do
      if child.key == "era" or child.key == "modification"
        child.content,add_child("fix_unit_type", { type = u["type"], add_advancement = adavnefrom ["type"]})
      end
    end
  end
end
```

That way the advancefrom woudl also be effective when one of the parts of the addons is actualyl used.

**Comment by CelticMinstrel** [comment] 2019-04-02 03:37
@gfgtdf - My suggestion is to go ahead and commit that implementation, but also add a deprecated message.

Why won't it work in mainline `advancefrom`? Mainline uses of it certainly shouldn't be removed as long as it's still supported, so if your idea really won't work with it, then maybe we need a better idea.

Unless by mainline uses of it you mean uses in specific campaigns, which certainly should be replaced with the new tag. (In fact, I'd suggest defining a macro for each optional advancement that currently exists in mainline, so that the old `extra_defines` method can be easily migrated to the new method. This should also be added to wmllint, both at the definition point and at the usage point.)

**Comment by gfgtdf** [comment] 2019-04-02 13:26
> but also add a deprecated message.

i have no problem with that.

> Why won't it work in mainline advancefrom? 

The idea was to put the cod ementioned above in the addon config loading code before the addon config is appended to the main game config, so that the [advancefrom] from that addon are only effective when one of the [era], [modification], [campaign] tags etc are actually used in the current game.

> Mainline uses of it certainly shouldn't be removed 

Why that? for uses inside mainline campaigns we can easily replace them with [unit_type_fix] and for uses in the game core we can just add the types to the previous units advancementlist. Removing cases of deprecated features in mainline is actually a normal thing.

**Comment by CelticMinstrel** [comment] 2019-04-03 00:05
Did you even read my second paragraph?

When I said they shouldn't be removed, I was referring to uses in the game core, which need to at least go through a deprecation phase before being removed. Furthermore, when deprecating something you should add a new way of getting the same result, so I suggested defining a macro for each optional advancement that contains a unit type fix tag.

**Comment by gfgtdf** [comment] 2019-04-03 01:45
> Did you even read my second paragraph?

yes I did but it didn't really make sense so I assumed there was a misunderstanding so I just clearified my ponit. Changing how those unit anvances are set internally whether via advancefrom or by changing the advance= attribute has zero impact for umc authors. For core we can change all `id=Id1 ... [advancefrom] type=Id2` to directly adding Id1 to the advance= attribute of the unittype with id2. This it unrelated to whether we want to keep extra_defines: If we want, we remove all [advancefrom] can still keep the extra_defineds= by using `#ifdef ... \n advance=... \n #else ...` in the other unit type.

**Comment by CelticMinstrel** [comment] 2019-04-04 04:01
Uhh, no, changing the `advance=` attribute means that the unit will now always be able to take that advancement. We can't do that. An `#ifdef ... #else ... #endif` approach to defining the `advance=` key (and `experience` too) is feasible, true, and should probably be done at some point to maintain backwards compatibility, but for future code, wouldn't it be better to define macros that use the new method?

**Comment by gfgtdf** [comment] 2019-04-04 10:32
> but for future code, wouldn't it be better to define macros that use the new method?

Yes it would, my main point here was really just to show that the inability to use [advancefrom] in mainline with the new implementation, is not really a problem.

**Comment by spixi** [comment] 2019-05-31 11:09
[advancefrom] can be replaced by a [modification] with [unit_type_fix].

There is no real need of [advancefrom] and extra_defines anymore.

**Comment by CelticMinstrel** [comment] 2019-06-08 03:46
`[advancefrom]` yes, but there could be other conceivable uses for `extra_defines` - for example, to specify configuration options for a resource addon, perhaps? Of course you'd want to use this only in single-player campaigns though.

**Comment by sevu** [comment] 2019-06-08 11:02
For these one uses #ifhave instead of checking for a macro. Or could swap to this if one doesn't.

**Comment by CelticMinstrel** [comment] 2019-06-15 17:27
I don't think `#ifhave` supports my example use-case. That tests if a specific file exists, right? I was envisioning a resource (or maybe even a modification) add-on that wants to offer some options to campaign designers that make use of it - perhaps dividing itself into several "submodules" (though that could be done by just defining multiple `[resource]` tags), or tweaking parameters somehow - for example, if it's a resource add-on containing new units (actually, can that even be done?), it could offer multiple ways of splicing those units into the core unit trees.

**Comment by sevu** [comment] 2019-06-15 19:10
True, doing Preprocessor-logic things based on WML-logic would otherwise not be possible.
For normal resource loading, this is what the Trader add-on (an open world RPG uses):
```
#ifhave ~add-ons/Trader_Sounds/_main.cfg
#define SOUNDS
#enddef
#endif
```

**Comment by gfgtdf** [comment] 2020-03-12 18:15
done

**Closed by gfgtdf** 2020-03-12 18:15 UTC
Labels: Enhancement, MP, WML
