### ISSUE TITLE
add a /clear command to mp lobby chat

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3202] opened 2018-06-02 18:18 UTC
as said in the title. It'd be nice to have a /clear command in the chat window in the mp lobby to get rid of older chats and messages in that window

**Comment by sevu** [comment] 2019-04-28 15:38
Chat can be cleared with `ctrl+x` (pressed outside the chat window). But it's nowhere mentioned that this exists.

**Comment by ProditorMagnus** [comment] 2019-04-28 16:04
Issue is about lobby chat.

**Comment by sevu** [comment] 2019-04-28 16:11
Then this does make sense...

**Comment by macabeus** [comment] 2022-01-23 17:08
@sevu the `ctrl+x` command is mentioned here: https://wiki.wesnoth.org/HotKeysSystem#Multiplayer_.28chat.29

Anyway, it looks like a quick win. I can add this command

**Comment by stevecotton** [comment] 2022-01-24 03:11
At least two people have been confused, so I'm adding a picture for clarity. The issue is to add a `/clear` command to this chatbox:
![mp_lobby](https://user-images.githubusercontent.com/101462/150715826-fa63f3d7-6e04-4543-ab6c-852ea208c8f2.png)

**Comment by stevecotton** [comment] 2022-02-19 19:41
Resolved in #6457 and #6476.

**Closed** 2022-02-21 01:31 UTC
Labels: Enhancement, MP Lobby, Good first issue
