### ISSUE TITLE
Buttons on start screen are not working / Mac / 1.17.4

### ISSUE THREAD

**Issue by daMark-de** [wesnoth/wesnoth#6741] opened 2022-06-02 16:12 UTC
### Game and System Information

- **Version: 1.17.4**
- **Downloaded from: wiki.wesnoth.org**
- **Build info: -**
- **OS: Intel Mac 10.14.6**

### Description of the bug

Not playable.
No Button of at start screen is working (Campaigns, ..., Quit, i / Version, Help, Previous, Next, "Language")

### Steps to reproduce the behavior

Download *.dmg file and open it.
Copy the content (game) to your local Applications-folder.
Start the game (allow it to executed). It starts in full screen mode (for me).
Try to click a button or another ...
Find a way to quit the game ...

**Comment by knyghtmare** [comment] 2022-06-02 16:14
Duplicate of #6715 
Should be fixed for 1.17.5

**Comment by daMark-de** [comment] 2022-06-02 17:22
I checked `is:open` and [#6715](https://github.com/wesnoth/wesnoth/issues/6715) already closed. :-(
Maybe you keep this issue open until 1.17.5 is released?

**Comment by Wedge009** [comment] 2022-06-02 22:00
Resolved duplicates are normally closed, even if unreleased, plus this is from the development version. But if you can remember to close this, I suppose that's fine.

**Comment by daMark-de** [comment] 2022-06-03 11:03
Hmm, I do not know much about the github-labels and how the projekt groups organize their work. So this idea might be stupid ...

What's about labels like "To be resolved with VERSION" (short "tbrw_1.17.5" for example")
Such a label would mark a (technically) resolved issue when the solution will be published with a release not yet available.
The issue can easily be found and closed when the new release is published and the issue is really solved with that release. Otherwise one can change the label to "tbrw_1.17.6" for example.
Doing so I would have seen the issue #6715 and that it was (internally) resolved. This reduces the number of duplicate issues.

But: 
Is it possible to delete unused labels from the system? Otherwise the list of labels will grow and grow and ...
Is there somebody who monitors all the "tbrw_*" labels and takes care of them? (Delete and change them if necessary?)

**Comment by CelticMinstrel** [comment] 2022-06-03 12:22
I think what you describe is the purpose of the "Milestone" field actually.

**Comment by knyghtmare** [comment] 2022-06-20 18:51
Closing since 1.17.5 is now available for download

**Closed by knyghtmare** 2022-06-20 18:51 UTC
Labels: Bug, Duplicate, macOS

**Comment by hermestrismi** [comment] 2022-06-24 12:21
Hi,
This is an update for TB (Tale of two Brothers) and it's complete now.
So, this week: "tb" and "anl" are finished and ready to test and upload.
Have a nice weekend
