### ISSUE TITLE
image_pos="right" does not display correctly (GNA #24930)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1566] opened 2017-05-08 11:48 UTC
**[Original submission](https://gna.org/bugs/index.php?24930)** by pentarctag0n on 2016-08-06

While using the new image_pos="right" attribute for [message] does cause the image to display on the right, it also shoves everything else over to the left.  This behavior is somewhat unexpected, as I would expect that the image is simply displayed to the right of the message text/options, rather than the current behavior of also pushing the message text/options over to the left third of the [message] and leaving the middle third of the [message] as empty space.

Correcting this would also make it useful with the ~FL() image function, since it would allow for the portrait to switch sides and still look correct[1].

[1] http://i.cubeupload.com/0ZWOrz.png

(Reproduced on Linux Mint)
Release: 1.13.5+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:48
**Modified on 2016-08-29**

**celticminstrel wrote:**

> The image_pos=right behaviour should be exactly the same as appending ~RIGHT() to the image path though, so I don't think this is new with the image_pos key.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:48
**Modified on 2016-09-02**

**pentarctag0n wrote:**

> Either way, it doesn't seem correct.  Though if the second_portrait key gets added to [message], this key becomes rather irrelevant.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:48
**Modified on 2016-09-04**

**celticminstrel wrote:**

> I disagree about second_portrait making it irrelevant - it's only irrelevant when second_portrait is actually specified.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:48
**Modified on 2016-09-05**

**pentarctag0n wrote:**

> How would:
> 
> 
> 
> image="x.png"
> 
> image_pos="left|right"
> 
> 
> 
> in [message] be different from:
> 
> 
> 
> portrait|second_portrait="x.png"
> 
> 
> 
> in wesnoth.show_message_dialog()?

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:48
**Modified on 2016-09-05**

**pentarctag0n wrote:**

> I mean, unless there's some other use for image_pos, if image_pos="right" (and ~RIGHT()) get fixed, then they do the same thing as portrait|second_portrait when there's only one portrait being displayed.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:48
**Modified on 2016-09-09**

**celticminstrel wrote:**

> Well, "portrait" doesn't specifically mean the portrait on the left in wesnoth.show_message_dialog (though I suppose that could be changed). And similarly in [message], "image" does not specifically mean the image on the left, and I don't think that could be easily changed (for compatibility).
> 
> 
> 
> Anyway, this bug (if it even is a bug) is independent of the method by which the portrait gets shifted to the right.

**Comment by wesnoth-bugs** [comment] 2017-05-08 11:48
**Modified on 2016-09-10**

**pentarctag0n wrote:**

> Yes, my point was just that if the portrait and second_portrait keys were added to [message], it would effectively resolve this issue since the strange ~RIGHT() behavior could be worked around.
> 
> 
> 
> I would call this a bug though, since at least to me, the fact that the [message] text/options/etc also get moved to the left is unexpected, and I can't imagine a situation where someone would want the [message] to be displayed as: text|blank|image, rather than: blank|text|image

**Comment by Pentarctagon** [comment] 2021-08-22 22:03
Confirmed as still happening on 1.15.16.

**Comment by Wedge009** [comment] 2023-03-06 01:11
Only marking as confirmed because of Pent's remark, I'm not sure where to check for this. I assume the remark on 2016-09-10 is supposed to say 'also get moved to the _right_'. If so, I'd agree.

**Comment by Wedge009** [comment] 2024-04-23 00:02
@Pentarctagon I didn't see the symptom back in 1.15, but looking at 1.19 - if I understand the issue correctly - I think this can be closed now?

Before:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/1423709c-ec3d-44f7-a27a-b7e940292eb7)

After `image_pos="right"`:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/362f684d-c53d-4624-bf38-5890ac2b57e9)

The inconsistent image positioning is reported in #3300. I understand this issue is specifically about the text changing position unexpectedly.

CC: @CelticMinstrel from GNA conversation.

**Comment by Pentarctagon** [comment] 2024-04-23 00:08
Yep.

**Closed by Pentarctagon** 2024-04-23 00:08 UTC
Labels: Bug, Confirmed, WML
