### ISSUE TITLE
1.17 font is extremely dyslexia unfriendly

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#6908] opened 2022-07-25 13:33 UTC
### Describe the desired feature

So I have dyslexia and when I tried out 1.17.6 I could barely read without focussing, meanwhile with non-bold font I can read pretty much fine only occasionally making mistakes. This creates for me an extremely unfriendly first experience of the game (or in this case version) and if I was new I would probably just drop the game right there because not being able to read smoothly is a big deal. That is why I would rather see a rollback to the 1.16 version of the font. 

I think that the issue is caused primarily by the fact that simply bolding letters in this case does not increase spacing between them and simply makes them bigger which in turn triggers my dislexion a lot and with font like that I need way more focus than I would usually need to even read. 

But it gave me a new experience, for the first time I felt like I was looking at gibberish instead of actual words. I was pretty surprised that this could even happen, usually I just replace some words with whatever I think they should be.

**Comment by mesilliac** [comment] 2022-07-26 05:12
Did this change between 1.17.5 and 1.17.6? Or between 1.16 and 1.17?

**Comment by Hejnewar** [comment] 2022-07-26 08:22
I checked and this happened somewhere between 1.17.0 and 1.17.5, I had pretty long break from 1.17 series so I can't pinpoint exactly when.

**Comment by Wedge009** [comment] 2022-07-27 14:33
Can you show some screenshots comparing what you find easy to read and what isn't? I noticed some changes with the new rendering applied in 1.17.6 but I thought mesilliac managed to resolve most of those issues.

**Comment by Hejnewar** [comment] 2022-07-27 22:14
Sure. 
1.16 - this is as easy to read for me as any normal text
![Example1](https://user-images.githubusercontent.com/41817546/181379179-f50c8da5-e5e5-4a98-bd85-f733a3bfa96c.PNG)
![Example3](https://user-images.githubusercontent.com/41817546/181379202-e5cd9b7a-6d3b-48fd-a3bd-f83c8e29cc9d.PNG)
1.17 - this is quiet hard to read and I have to focus to not make too many subsitutions or even read at all especially in case of menu buttons
![Example2](https://user-images.githubusercontent.com/41817546/181379221-115e57da-8c95-432b-9c72-bab5bc5e9d3c.PNG)
![Example4](https://user-images.githubusercontent.com/41817546/181379225-3ff5c84c-1f34-4057-85ae-388edd7a4507.PNG)

**Comment by Wedge009** [comment] 2022-07-27 23:54
Interesting. I find the difference quite subtle, but I can see that your 1.17 example is 'bolder'. On Linux, I see no difference between 1.16.5 release and 1.17.6+dev (1be1ba42825). Windows builds aren't working for me at the moment so I can't check right now, but it does look like your 1.17 images are anomalous. Is that from your own build?

**Comment by mesilliac** [comment] 2022-07-28 05:26
I don't have dyslexia, and that second example also gives me a headache...

It seems to not be a difference in font, but rather in weight. I wonder if perhaps it is being rendered twice for some reason. This is the same word from each example:
![move](https://user-images.githubusercontent.com/243646/181426680-cee94dcd-0162-4748-a06e-02f9478f23e9.gif)

**Comment by mesilliac** [comment] 2022-07-28 06:38
On linux i also seem to have the correct font weight in current master, so i can't reproduce the issue but it seems that the text itself isn't blitting twice. The font here appears identical the the 1.16 version above.
![move_linux](https://user-images.githubusercontent.com/243646/181437191-e8232787-e3f2-466f-90dc-825111cefb0e.png)

**Comment by Wedge009** [comment] 2022-07-28 12:33
That was my point - it's identical in Linux but I observe the issue under Windows. Windows text rendering has produced different results compared with Linux in the past - sounds like you don't think it's related to any of the changes you've done recently.

**Comment by mesilliac** [comment] 2022-07-28 13:26
I'm not sure if it's related or not, that's the thing. There have been various changes and it's possible something like changing the windows executable to be marked as "high DPI aware" somehow changed how it wants to render fonts. Well, it shouldn't be the case, but i can't say for certain it isn't.

It's also possibly a bug or a change in SDL, or in Pango, in which case it would only show up with certain versions.

It also could have been some other change to Wesnoth since 1.16 that i'm not aware of. Maybe font weights were changed. That isn't something i did, but i can't say it didn't happen.

**Comment by Wedge009** [comment] 2022-07-28 15:22
Sounds like we need Windows users to confirm when this started. I can confirm the issue does not show in Windows build of current 1.16 branch.

Not sure if 'high DPI aware' works in Windows 7 but the issue is present there as well as Windows 10.

**Comment by Wedge009** [comment] 2022-07-28 15:53
Using the official Windows release builds from sourceforge.net, I confirm the issue was introduced in between 1.17.4 and 1.17.5. If/when I resolve the vcpkg issue with sdl2-mixer, I can try to narrow down the commit/s which caused this.

**Comment by Wedge009** [comment] 2022-07-29 03:46
I gave up on trying to fix CMake builds on MSVC and reverted to the traditional VS project build if only to get some sort of compilation working on Windows for now. I can replicate the issue even without the 'high DPI aware' manifest packaging so it doesn't appear associated with that.

The commit responsible appears to be 06b02471e49e4db616ec55c2c02ef66349e0bc53 which was merged as part of #6685. And since then, the 'win32 fontmap backend' was removed in c69d2a91a61d32b4a37c6a28a506696c6080c9a8 - not sure if that means font handling is supposed to be consistent across OSs now. My initial thought was to try reverting 06b02471e49e4db616ec55c2c02ef66349e0bc53 in current master to see what happens but this results in conflicts.

I understand the intention of #6685 was to resolve #1549, and I can see characters being rendered properly with Windows with this change. I am not sure what to do about the change in text rendering for Windows, as a side-effect.

CC: @loonycyborg, @Pentarctagon

**Comment by loonycyborg** [comment] 2022-07-29 12:16
This double blitting causes deja vu for me, iirc there were some windows specific issues related to alpha value handling.

**Comment by Pentarctagon** [comment] 2022-07-29 14:14
Do you mean #5618?

**Comment by loonycyborg** [comment] 2022-07-29 17:13
Yes.

**Comment by Pentarctagon** [comment] 2022-07-29 17:16
@Wedge009 if you revert the change made to that PR, does that fix the issue?

**Comment by Wedge009** [comment] 2022-07-30 00:41
I was not able to revert because of the later change, c69d2a9 that removed the win32 fontmap back-end altogether. But I can try to revert that too.

**Comment by Wedge009** [comment] 2022-07-30 01:03
Against current master (6701542f633990ec14f9302d9e998062ad13d749) I was able to compile cleanly by reverting both 06b02471e49e4db616ec55c2c02ef66349e0bc53 and c69d2a91a61d32b4a37c6a28a506696c6080c9a8.

This results in fonts being rendered the same as for 1.16 Windows and for 1.16/1.17 Linux, _this_ issue, but unfortunately **re-opens** #1549.

**Comment by Pentarctagon** [comment] 2022-07-30 01:11
> I was not able to revert because of the later change, https://github.com/wesnoth/wesnoth/commit/c69d2a91a61d32b4a37c6a28a506696c6080c9a8 that removed the win32 fontmap back-end altogether. But I can try to revert that too.

I don't follow. The code from #5618 is clearly still present: https://github.com/wesnoth/wesnoth/blob/6701542f633990ec14f9302d9e998062ad13d749/src/font/text.cpp#L724-L733

**Comment by Wedge009** [comment] 2022-07-30 01:14
Are you asking me or loony? I'm just reporting what I found.

**Comment by Pentarctagon** [comment] 2022-07-30 01:18
@Wedge009 I'm asking if you can revert a56497a561b0f491d686fb396029f98fe94fac72 and retest.

**Comment by Wedge009** [comment] 2022-07-30 01:52
Yep, that seems to resolve it. I'll open a PR, if only for the CI checks, shortly.

**Closed** 2022-07-30 04:25 UTC
Labels: Enhancement, Confirmed, Windows, UI
