### ISSUE TITLE
NR S2: rails displayed on castle (discussion/not a bug).

### ISSUE THREAD

**Issue by IskarJarak** [wesnoth/wesnoth#5317] opened 2020-11-26 20:26 UTC
@doofus-01 

Not sure if this applies to other cave scenarios as well, but the display of rails through a castle looks weird to me. Here is a screenshot from the scenario:

![rails_on_keep](https://user-images.githubusercontent.com/44609951/100388918-4177da00-302c-11eb-8ea4-5f8b4ae0dde3.PNG)

Here is a contrasting screenshot from SoF, where rails don't get placed on the same tile as castle/keep:

![keep_on_rails](https://user-images.githubusercontent.com/44609951/100388922-42a90700-302c-11eb-98a2-4b02f6679c2c.PNG)

In the case of the first screenshot you _could_ argue that the castle is just walls around a dirt field and then it kind of makes sense, but having the palisades on top of the tracks looks a) strange, b) impractical, and c) unstable to me. The patches of light dirt to contrast the surrounding dark dirt from the castle dirt also don't help.

Thinking about it again, I am a little torn if hiding the rails below the castle would make for better visuals though.

**Comment by knyghtmare** [comment] 2020-11-26 20:35
I do not think this is not a bug. You can get rails over the encampment hex in the map editor by placing the rails overlay over the encampment hex. I speculate that the map designer originally intended for the the rail path to be shown like this.

**Comment by Pentarctagon** [comment] 2020-11-26 20:38
IMO it doesn't make a whole lot of sense to put rails that look like they're phasing through a wall.  Either the rails shouldn't go through the encampment, or there's need to be a transition added for walls <-> rails to have a gate sort of structure be there.  Otherwise it does look a bit weird.

**Comment by doofus-01** [comment] 2020-11-26 20:52
Ah, I see now, I somehow went to the cut-scene earlier, and the rails look OK there.  Yes, I agree rails going through the castle/camp walls looks very odd, should be fixed.  A new transition for it sounds like a big headache for little gain, I'd be inclined just not to have such a combo in mainline.  Is there some non-decorative reason to have the rails terrain there?

Fortunately, in this case the map is drawn, not generated, so it should be simple to fix.

**Comment by IskarJarak** [comment] 2020-11-26 20:55
I'm pretty sure the rails are purely decorative in this case.

**Comment by IskarJarak** [comment] 2020-11-27 11:10
Does this work better? I'm still not quite sure how to interpret the encampment castle type... There were a few other cases where I just removed rails from keeps on the map, but here I see no alternative to cutting the whole rail or impacting the map gameplay-wise (the castle-village-wall hexes at the northern end are strategically important).

![keep_on_rails2](https://user-images.githubusercontent.com/44609951/100442842-036ccb80-30a9-11eb-88cb-acf2b0d6ed8e.PNG)

**Comment by doofus-01** [comment] 2020-11-27 12:44
That looks right to me.

**Comment by IskarJarak** [comment] 2020-11-27 12:47
alright, then I'll commit that change.

**Closed** 2020-11-27 19:37 UTC

**Comment by Konrad22** [comment] 2020-11-30 12:21
I have no idea if this was 'fixed' as well, but the blue troll leader also has rails on his castle in 1.15.7.

**Comment by IskarJarak** [comment] 2020-11-30 14:43
I'm pretty sure I caught them all - they were at least 2 other castles with rails on them.
