### ISSUE TITLE
UNICODE encoding error in non-Latin1 characters in Credits (v 1.14.17)

### ISSUE THREAD

**Issue by dway123** [wesnoth/wesnoth#5977] opened 2021-07-24 01:49 UTC
When reading credits for Wesnoth, I noticed that some characters, mostly for Asian languages, weren't displaying properly. I noticed this when finishing Heir to the Throne, and also when just clicking the "credits" button on the launch page.

# Steps to Reproduce
1. Launch Wesnoth.
2. Click the "Credits" button.
3. Scroll to the "Translation" sections.

# Expected Behavior:
Examples of proper Latin1 and character display:
![image](https://user-images.githubusercontent.com/10102114/126853793-baea1b4c-0081-437e-a9ad-1301efd6baf1.png)

# Actual Behavior:
Examples of improper character display:
![image](https://user-images.githubusercontent.com/10102114/126853812-c3284c2b-d4c0-4fb6-a2dd-d758e683b2f8.png)
![image](https://user-images.githubusercontent.com/10102114/126853773-75b7c8c6-a5a7-49c2-a3f8-17fd4e38b5d3.png)

# More Info
For more information, I'm playing via Steam on Microsoft Windows 10 Home, Version 10.0.19043, Build 19043, and haven't seen any recent "UNICODE" or "Asian" language mentions in the [changelog](https://github.com/wesnoth/wesnoth/blob/master/changelog.md), since v1.14.17.

I did notice some i18n changes in the [1.15.6 changelog](https://github.com/wesnoth/wesnoth/blob/master/changelog.md#version-1156) that might be relevant though, but don't understand fonts deeply enough to know here, and haven't tried building the new release to test this.

**Comment by Wedge009** [comment] 2021-07-24 02:23
Thanks for reporting, but pretty sure this is a duplicate of #1549 - I note that you're playing on Windows where this issue occurs.

**Comment by dway123** [comment] 2021-07-24 05:02
Thanks. It's possible this is a duplicate of #1549, but I think it could maybe be a follow-up instead. 

I did notice this [comment](https://github.com/wesnoth/wesnoth/issues/1549#issuecomment-479268197) that suggests a minor issue after the fix (Steam release 1.14.6) for #1549, 

> when using a latin-based language and looking in the Language dialogue, the Chinese and Japanese languages listed in their native characters aren't rendered (but they are when Japanese language is selected).

The following comment mentions 

> Iirc another dialog where this showed up was the credits screen.

I think this bug might be that minor issue :P

I don't mind leaving the bug as a duplicate if it's unlikely to be prioritized, but I believe it does have a different root cause than #1549, which seemed to be a larger-scope issue that's now resolved.

**Comment by Wedge009** [comment] 2021-07-24 05:32
I invite you to make your contributions in #1549 directly so it doesn't get lost in this separate report - it's still open for comments. ~It's been a while since I've looked at these issues~, but just retesting in 1.14.17 Linux there is no such issue because of how fonts are supplied and handled there. Retesting in Windows I can reconfirm the issue. If there happens to be anything genuinely new that you find that can't be directly tied to #1549 feel free to re-open this or submit a new issue.

All right - I re-read #1549 and I think this is still the same issue. If you switch your current language to Chinese or Japanese, this issue doesn't occur any more - the hack/work-around from #1549 seems to cover that. It only remains an issue (and only for Windows) if the current language is Latin-based (or Cyrillic). So I encourage you to give further feedback in #1549 to keep the discussion in one place.

**Closed by Wedge009** 2021-07-24 05:32 UTC
Labels: Bug, Duplicate, UI, Windows
