### ISSUE TITLE
Gweddry character not showing

### ISSUE THREAD

**Issue by GwD2018** [wesnoth/wesnoth#2630] opened 2018-03-10 22:20 UTC
in the- The Escape Tunnel -the Gweddry character not showing despite i can recruit&recall but he can't move.........
![untitled](https://user-images.githubusercontent.com/37253319/37247308-34764b40-24b1-11e8-8a36-d93d4569bb96.png)

**Comment by hrubymar10** [comment] 2018-03-10 22:55
Please upload here save. I'll try reproduce it

**Comment by Vultraz** [comment] 2018-03-11 02:26
He was probably hidden by a previous scenario (with `[hide_unit]`) and that carried over due to my recent change to write the hidden= key to unit configs. I added a commit (fef068034f7b06fb6b2365eede82dd253c25ba3e) that resets units' hidden status between scenarios, so assuming this is that issue, it will be fixed in 1.13.12.

**Comment by Vultraz** [comment] 2018-03-11 03:14
Yeah, I just checked, and there is indeed a `[hide_unit]` tag in EI S1. So this is almost certainly fixed.

**Closed by Vultraz** 2018-03-11 03:14 UTC
