### ISSUE TITLE
Directly droiding players as host is no longer possible

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3374] opened 2018-07-26 23:34 UTC
You can't droid other players as host directly, you first have to take their side and then you can droid that side. You could do so in the earlier versions of Wesnoth. I'm not sure as to why this was changed.
~Also, if I manage to droid someone, there is no feedback from the system anymore like 'Droided side x'. Which is making me at least very unsure if it actually worked.
I'd really like to have that feedback from the system, if possible.~

**Comment by stevecotton** [comment] 2018-07-27 09:53
The lack of feedback is a duplicate of issue #2819, which has developers arguing both for and against it.

**Comment by Konrad22** [comment] 2018-07-27 09:54
Thanks. Edit incoming.

**Comment by Wedge009** [comment] 2019-10-22 02:11
#2819 is now closed so where does that leave this issue? Are you still finding this is a problem, @Konrad22?

**Comment by Konrad22** [comment] 2019-10-22 09:05
I can now droid fine on 1.14.9, but for some reason I will still see that sides turn from their point of view.

**Comment by Wedge009** [comment] 2019-10-22 11:03
> ...for some reason I will still see that sides turn from their point of view.

As in, the camera shifts around as though you are still the controlling player? Sounds like this needs to be kept open then, but please update the title with something that more accurately describes your current issue.

**Comment by stevecotton** [comment] 2019-10-22 11:29
That's #3665

**Comment by Wedge009** [comment] 2019-10-22 11:37
So... that one isn't really closed then?

**Comment by Konrad22** [comment] 2019-10-22 19:32
Maybe..? To be honest I'm not really clear what their fix was in the end. Anyway, for me just using 'droid' works, but I see the game from the side of the droided side.

**Comment by stevecotton** [comment] 2019-10-22 21:28
For 1.15.2, `:droid 2 on` will retain vision, `:droid 2 full` won't.

**Comment by Wedge009** [comment] 2019-10-22 22:15
@stevecotton Should we re-open #3665 and continue there or keep going on this one?

**Comment by Wedge009** [comment] 2019-10-22 23:33
Closing this as the actual 'droid' command issue has been resolved.

**Closed by Wedge009** 2019-10-22 23:33 UTC
Labels: MP, Regression
