### ISSUE TITLE
Version 1.16.9 and GCC 13.1.0 building problem

### ISSUE THREAD

**Issue by muashieWuphu** [wesnoth/wesnoth#7740] opened 2023-06-28 12:15 UTC
### Game and System Information

- 1.16.9
- http://downloads.sourceforge.net/wesnoth/%{name}-%{version}.tar.bz2
- N/A
- PLD Linux, gcc (PLD-Linux) 13.1.0 20230627 (release)

I can't build the 1.16.9 version of Wesnoth due to the following error.

Does anyone know how to solve this?

### Description of the bug

`In file included from /home/users/builder/rpm/BUILD/wesnoth-1.16.9/src/deprecation.cpp:15:                                                                                                             
/home/users/builder/rpm/BUILD/wesnoth-1.16.9/src/deprecation.hpp:20:6: warning: elaborated-type-specifier for a scoped enum must not use the 'class' keyword                                           
   20 | enum class DEP_LEVEL : uint8_t { INDEFINITE = 1, PREEMPTIVE, FOR_REMOVAL, REMOVED };                                                                                                           
      | ~~~~ ^~~~~                                                                                 
      |      -----                                                                                 
/home/users/builder/rpm/BUILD/wesnoth-1.16.9/src/deprecation.hpp:20:22: error: found ':' in nested-name-specifier, expected '::'                                                                       
   20 | enum class DEP_LEVEL : uint8_t { INDEFINITE = 1, PREEMPTIVE, FOR_REMOVAL, REMOVED };                                                                                                           
      |                      ^                   
      |                      ::                                                                    
/home/users/builder/rpm/BUILD/wesnoth-1.16.9/src/deprecation.hpp:20:12: error: 'DEP_LEVEL' has not been declared                                                                                       
   20 | enum class DEP_LEVEL : uint8_t { INDEFINITE = 1, PREEMPTIVE, FOR_REMOVAL, REMOVED };                                                                                                           
      |            ^~~~~~~~~                     
/home/users/builder/rpm/BUILD/wesnoth-1.16.9/src/deprecation.hpp:20:32: error: expected unqualified-id before '{' token                                                                                
   20 | enum class DEP_LEVEL : uint8_t { INDEFINITE = 1, PREEMPTIVE, FOR_REMOVAL, REMOVED };                                                                                                           
      |                                ^                                                           
/home/users/builder/rpm/BUILD/wesnoth-1.16.9/src/deprecation.hpp:43:17: error: 'DEP_LEVEL' has not been declared                                                                                       
   43 |                 DEP_LEVEL level,                                                           
      |                 ^~~~~~~~~                
/home/users/builder/rpm/BUILD/wesnoth-1.16.9/src/deprecation.cpp: In function 'std::string deprecated_message(const std::string&, DEP_LEVEL, const version_info&, const std::string&)':
/home/users/builder/rpm/BUILD/wesnoth-1.16.9/src/deprecation.cpp:38:25: error: 'INDEFINITE' is not a member of 'DEP_LEVEL'                                                                             
   38 |         case DEP_LEVEL::INDEFINITE:                                                        
      |                         ^~~~~~~~~~                                                         
/home/users/builder/rpm/BUILD/wesnoth-1.16.9/src/deprecation.cpp:43:25: error: 'PREEMPTIVE' is not a member of 'DEP_LEVEL'                                                                             
   43 |         case DEP_LEVEL::PREEMPTIVE:                                                        
      |                         ^~~~~~~~~~                                                         
/home/users/builder/rpm/BUILD/wesnoth-1.16.9/src/deprecation.cpp:53:25: error: 'FOR_REMOVAL' is not a member of 'DEP_LEVEL'                                                                            
   53 |         case DEP_LEVEL::FOR_REMOVAL:                                                       
      |                         ^~~~~~~~~~~                                                        
/home/users/builder/rpm/BUILD/wesnoth-1.16.9/src/deprecation.cpp:59:25: error: 'REMOVED' is not a member of 'DEP_LEVEL'                                                                                
   59 |         case DEP_LEVEL::REMOVED:                                                           
      |                         ^~~~~~~                                                            
make[2]: *** [src/CMakeFiles/wesnoth-client.dir/build.make:6116: src/CMakeFiles/wesnoth-client.dir/deprecation.cpp.o] Error 1                                                                          
make[2]: *** Waiting for unfinished jobs....                                                       
make[2]: Leaving directory '/home/users/builder/rpm/BUILD/wesnoth-1.16.9/build'
make[1]: *** [CMakeFiles/Makefile2:277: src/CMakeFiles/wesnoth-client.dir/all] Error 2                                                                                                                 
make[1]: Leaving directory '/home/users/builder/rpm/BUILD/wesnoth-1.16.9/build'                                                                                                                        
make: *** [Makefile:159: all] Error 2 `

**Comment by Pentarctagon** [comment] 2023-06-28 14:11
As [discussed](https://forums.wesnoth.org/viewtopic.php?p=682399#p682399) on the forums, this has already been fixed in 11e0e2767081e675ed71191e9463ac578305dff5. The issue is only that 1.16.10 hasn't been released yet.

**Closed by Pentarctagon** 2023-06-28 14:11 UTC
Labels: Bug
