### ISSUE TITLE
Don't re-upload unchanged files when updating an add-on (GNA #19972)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1313] opened 2017-05-08 07:08 UTC
**[Original submission](https://gna.org/bugs/index.php?19972)** by anonymous on 2012-07-22

When uploading a new version of an add-on to addons.wesnoth.org (through the in-game upload client) all the files have to be sent every time, even if most of them haven't changed.  A one-line fix to some WML can force you to re-upload megabytes of oggs.

The uploader should take a hash of each file, compare them to hashes of the old versions of the files (which hashes the server should compute and supply), and only upload those files for which the hash has changed.

This would of course require changes to both the client and the server.  It might also create incompatible changes to the protocol, which I gather is not extensible.

Since this would mean old clients couldn't use the new server, one possibility would be to rewrite the addon server protocol entirely, to use HTTP with GET, PUT, and some custom headers.  That would allow future extensions to be implemented without a flag day.  Also I gather the addon server needs a rewrite as it is.

(Reproduced on Linux)
Release: 1.10
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:08
**Modified on 2012-07-23**

**anonymissimus wrote:**

> That's what version control systems and the wesnoth UMC repository are for, where you only need to send a small text file per one line fix.

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:08
**Modified on 2012-07-23**

**anonymous wrote:**

> Ah, I didn't realise there was a repository for UMC; it doesn't seem to be mentioned anywhere on wiki.wesnoth.org.
> 
> 
> 
> Do commits to the UMC repo get automagically applied to the addon server?

**Comment by jostephd** [comment] 2019-09-11 10:23
Duplicate of #1458? This is asking for rsync functionality, using git would provide that and more.

**Comment by kabachuha** [comment] 2020-10-16 19:51
Implemented in #5038.

**Closed by kabachuha** 2020-10-16 19:51 UTC
Labels: Add-ons, Enhancement
