### ISSUE TITLE
Unable to re-join game after DC

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#3579] opened 2018-09-26 06:26 UTC
Steps:
* start a multiplayer game with a pass, observers disabled
* join the game with another client, start game
* exit the other client and exit MP lobby (simulate network disconnection)
* attempt to re-join the game

Normally expected by people at this point: you can re-join since you were one of the players, and you know the password.

Actually: you cannot neither observe nor join as player.

P.S. Now, I know this is how wesnoth used to function for a long time. I also know that many people would like an alternative way of how password works. This specific issue is not broad, however. It touches one specific aspect of the situation: being able to re-join if you know the password. If someone is <strike>brave</strike> determined enough to change the overall situation, I'd appreciate that. Otherwise let's focus on the specific situation.

**Comment by Wedge009** [comment] 2019-10-22 05:55
It's not clear in your instructions above but the third point 'other client' appears to mean the host. If the host gets disconnected, then yes, the Join button is disabled, because the client thinks the room is now full (assuming 2-player game).

**Comment by soliton-** [comment] 2019-10-27 10:58
The problem is that you aren‘t allowed to join a game as a player once it started and also that there won’t be a free side to take to begin with. So for games with disallowed observers there is no way to get a disconnected player back in but to abort and reload.

I think an ideal solution would be to add a new controller state that marks the side as free to be taken by a joining player but prevents the game from continuing if that "empty" side‘s turn comes before it’s reassigned to a joining player or the host changes control.

That would be good not only for observerless games but also avoids issues with automatically giving a possibly opposing side to the host.

There is a bit of an issue when it’s the free side‘s turn and someone joins that shouldn’t get the side and makes moves before the host can remove them. I think that is not going to be a big deal in practice though and preferable to adding more complexity by having the host confirm the new player or so. (Setting a password on the game also prevents it.)

**Comment by Wedge009** [comment] 2019-10-27 11:31
> The problem is that you aren‘t allowed to join a game as a player once it started...

What I tested above, the game was not 'started'. It was still in MP Staging screen. When the host disconnects, the game doesn't appear to recognise this, so the room is still deemed 2/2 instead of 1/2.

**Comment by soliton-** [comment] 2019-10-27 12:46
That sounds like a bug. The game should end if it wasn’t started and the host leaves. Was the disconnect perhaps not noticed yet?

**Comment by vgaming** [comment] 2019-11-06 13:50
Sorry for the late reply.

> It's not clear in your instructions above but the third point 'other client' appears to mean the host.

It doesn't matter actually, but for maximum reproducibility, it is just another wesnoth client. No, it's not the host, as the host is sayed to be hosting the game at first step.

> The problem is that you aren‘t allowed to join a game as a player once it started and also that there won’t be a free side to take to begin with. So for games with disallowed observers there is no way to get a disconnected player back in but to abort and reload.

Yes, exactly. You start a game, a player DC-es, and there's no way to continue except aborting the game at all. If the game had 6 people, then, as you might imagine, aborting the game and starting it from a savegame is quite tiresome.

> I think an ideal solution would be to add a new controller state that marks the side as free to be taken by a joining player but prevents the game from continuing if that "empty" side‘s turn comes before it’s reassigned to a joining player or the host changes control.

That's one possibility. I would completely abolish the current design of "no-observer" and "password" fields though. By password I would mean that anybody can join the game at any time, provided they know the password. By "no-observer" I would mean that observing players are auto-kicked at start of the game, after which only players who were in the original list can ever join. That includes DC and reconnection.

**Comment by vgaming** [comment] 2019-11-06 13:51
> When the host disconnects, the game doesn't appear to recognise this, so the room is still deemed 2/2 instead of 1/2.

That must be a separate bug then. Can we raise it separately for better visibility?

**Comment by Wedge009** [comment] 2019-11-06 20:07
I encountered it while testing this issue according to the instructions you gave. Seems to me this is directly related to your issue.

**Comment by vgaming** [comment] 2019-11-06 21:36
@Wedge009 I understood that my instruction might not be precise enough. It said:

> start a multiplayer game with a pass, observers disabled

By "starting a game" I meant going past room creation and actually start playing. I'll specify it more strictly now.

**Comment by vgaming** [comment] 2019-11-06 21:38
@Wedge009 the second step in my instruction says (and said):

> join the game with another client, start game

The last "start game" means to advance the team/faction choosing screen into the actual game. That differs from your repro steps, does it?

**Comment by Pentarctagon** [comment] 2021-08-11 23:55
It allows it to be worked around by setting a password rather than disallowing observers, but for games with observers disabled I don't think it changes anything.  Fixing this would require keeping track of the original set of the username of anyone who has controlled a side and then allowing them to bypass the "no observers" setting so they can rejoin and be re-assigned a side, I think.

**Comment by vgaming** [comment] 2021-08-15 18:52
@Pentarctagon my original issue is fixed though, I think. I really saw this huge probleem (that https://github.com/wesnoth/wesnoth/pull/4138 fixes), so I wanted to raise a bug on that. Now that the PR is merged, we can close this issue and optionally create another one for even-nicer passwords/observers check (differentiate between reconnections and new joins as @Pentarctagon wrote).

I'm aligning to close this issue to not confuse new readers with outdated irrelevant posts on top of the thread

**Closed** 2021-08-15 18:52 UTC
Labels: Bug, Confirmed, MP Lobby
