### ISSUE TITLE
A New Land bug

### ISSUE THREAD

**Issue by Lordlewis6** [wesnoth/wesnoth#4973] opened 2020-06-28 01:37 UTC
### Game and System Information
 - What version of the game are you running?
This bug runs on any version that has A New Land, I have known about this bug for several years.
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Website version, but will most likely works on everything else.
 - What OS are you running?
Windows 10

### Describe the bug
This video sums it up.
https://www.youtube.com/watch?v=KTRaFxnP3tI&feature=youtu.be
Pretty much what a player can do is use a peasant to cut a forest down, nothing new. If the player pulls up the right click menu before actually cutting the tree down the tile that the cursor was clicking on will turn into a grass tile. This can be used to do a few things, including getting extra money because cutting down forests grants 1 gold, it can destroy any tile including unwalkable/impossible ones and destroy keeps. If a unit does this glitch in single player the game will not break in any ways, but if played in multiplayer the game can break. If any unit walks onto where an impassable tile is the game will report a out of sync issue for every player but the one who performed the glitch, this can crash the game on occasion. If a keep is destroyed and someone (like an enemy leader) attempts to recruit on it, the game will crash for anyone who didn't perform the glitch. All of this works with the A New Land era.

### To Reproduce

1. Prompt a peasant to chop down a forest tile
2. Pull up the right click menu on any tile you want to turn to grass while the peasant chops the forest tile
3. Move a unit onto the tile that just turn to grass or build something on that tile

### Expected behavior
The game can crash depending on what happens, but there will always be an out of sync issue.

### Savefiles
The replays will not work with this bug.

### Additional context
A bug that might be worth fixing, but is not easy to find but easy to pull off.

**Comment by gfgtdf** [comment] 2020-06-28 01:40
a duplicate of https://github.com/wesnoth/wesnoth/issues/4946 and will be fixed in the next 1.14 release

**Comment by gfgtdf** [comment] 2020-06-28 01:43
> If a keep is destroyed and someone (like an enemy leader) attempts to recruit on it, the game will crash for anyone who didn't perform the glitch

This part is new though, coudl you specify what you mean by crash here? how does the crash look like ?

**Comment by Lordlewis6** [comment] 2020-06-28 10:27
Well it might have necessarily been that, but I assumed it was. The game crashed for P2 at the end of their turn so it might not have been the leader recruiting. Also the version I was using was 1.15 when I retested it and recorded the video.

**Comment by gfgtdf** [comment] 2020-06-28 18:24
my question was more how exactly it crashed, does it give an error message? Or does the game just quit without any information?

**Comment by Lordlewis6** [comment] 2020-06-28 21:54
It just quit without a message, apparently P2 had two Wesnoths open and isn't too powerful so that might be why.

**Comment by sevu** [comment] 2020-07-02 02:52
It might have been that the experimental AI was used, it does cache castle hexes and that does not work well with ANL.
Thought, I switched it back to normal AI after 1.15.0, so maybe not the issue here.

**Comment by stevecotton** [comment] 2021-08-18 10:52
Is there a reason to keep this open? The part that wasn't fixed by #4946 is a wouldn't-know-if-we-fixed-it crash.

**Comment by sevu** [comment] 2021-08-21 19:53
I don't think so.

**Closed by sevu** 2021-08-21 19:53 UTC
Labels: Bug, MP
