### ISSUE TITLE
SoF: lua error

### ISSUE THREAD

**Issue by arosella** [wesnoth/wesnoth#5879] opened 2021-06-20 16:00 UTC
Battle for Wesnoth v1.15.13+dev x86_64, 
compiled from git source (cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ )
on an MxLinux (Linux htpc 5.10.0-5mx-amd64 #1 SMP Debian 5.10.26-1~mx19+1 (2021-04-01) x86_64 GNU/Linux )

Scenario [scenario]: id=2t_In_the_Dwarven_City

After Durston phrase "Good one, let them try to take it! Ha!", the scenario ended suddenly with a <Lua error> both on the screen and on the console

$ wesnoth
Battle for Wesnoth v1.15.13+dev x86_64
Started on Sun Jun 20 17:48:10 2021

Data directory:               /usr/local/share/wesnoth
User configuration directory: /home/USER/.config/wesnoth
User data directory:          /home/USER/.local/share/wesnoth/1.15
Cache directory:              /home/USER/.cache/wesnoth

Setting mode to 1920x1172
20210620 17:48:13 error config: Multiple [unit_type]s with id=Giant Stoat encountered. **<== This happens as soon as I start the game**
Checking lua scripts... ok 
20210620 17:49:18 error config: Multiple [unit_type]s with id=Giant Stoat encountered. **<== This happens at loading scenario**
20210620 17:50:10 error scripting/lua: lua/wml/move_unit.lua:88: attempt to call a nil value (field 'find_vacant_hex')
stack traceback:
	lua/wml/move_unit.lua:88: in local 'cmd'
	lua/wml-utils.lua:144: in field 'handle_event_commands'
	lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
**And this finally showed up at the end on the dialogue**

[SdF-Nella città dei nani.gz](https://github.com/wesnoth/wesnoth/files/6682648/SdF-Nella.citta.dei.nani.gz)

**Comment by CelticMinstrel** [comment] 2021-06-20 16:17
The second part looks like #5877 which was already fixed. Just to make sure though, does line 88 of data/lua/move_unit.lua say `wesnoth.paths.find_vacant_hex` or `wesnoth.find_vacant_hex`?

The first part is weird, because there's clearly only one giant stoat… is it somehow transcluded twice or something?

**Comment by arosella** [comment] 2021-06-20 18:35
line 88 of data/lua/wml/move_unit.lua

if not (x == prevX and y == prevY) then x, y = wesnoth.find_vacant_hex(x, y, pass_check) end

**Comment by doofus-01** [comment] 2021-06-20 20:25
The Giant Stoat should have been removed, but I forgot about it, unfortunately.  Still, there's only one.  Maybe it's coming from data in your save-file, and campaigns started in the current version won't have that data?  It's also possible there's a badly configured add-on.

**Comment by arosella** [comment] 2021-06-20 20:35
No add-on, installed; I'm  quite confident that I'm not using old savefile, but I'll check. However, the first warning pop-up at the splash screen, no savefile loaded...

$ wesnoth
Battle for Wesnoth v1.15.13+dev x86_64
Started on Sun Jun 20 22:29:40 2021


Data directory:               /usr/local/share/wesnoth
User configuration directory: /home/USER/.config/wesnoth
User data directory:          /home/USER/.local/share/wesnoth/1.15
Cache directory:              /home/USER/.cache/wesnoth

Setting mode to 1489x797
20210620 22:29:42 error config: Multiple [unit_type]s with id=Giant Stoat encountered.
Checking lua scripts... ok


I'll clean all the cache, just in case...

**Comment by CelticMinstrel** [comment] 2021-06-21 02:15
Okay, sounds like this should be closed as a duplicate of #5877?

**Comment by Wedge009** [comment] 2021-09-15 16:00
No response since June - I haven't seen any other reports on this either...

**Closed by Wedge009** 2021-09-15 16:00 UTC
Labels: Bug, Campaign, Lua API
