### ISSUE TITLE
Game config incorrectly parses numbers using decimal comma based on locale

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#3945] opened 2019-02-24 15:35 UTC
This was originally reported [here](https://forums.wesnoth.org/viewtopic.php?f=4&t=48080#p634466).

The short version is apparently Wesnoth (sometimes?) takes locale into account when parsing decimal values from game configs, which then causes problems in cases where the separators are different - 1.000,00 vs 1,000.00 as an example.

The reporter's location is Slovenia and OS is Windows 7.  This issue has also been reported to be working as expected on Windows 10 and Linux.

**Comment by Wedge009** [comment] 2019-02-25 12:30
I'm intrigued, but I'm wondering if there's an easy way to test/replicate this. Looks like @jostephd is assisting.

**Comment by soliton-** [comment] 2019-09-13 17:28
[strtod](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strtod.html) is specified to take locale into account so it doesn't seem like the right thing to use here. It does not seem like it should cause visible issues though since it should just mean attribute values are saved as strings and not numbers because of the `from_string_verify` safe guard.

So the `strtod` call looks like something to fix but I can't see how it'd cause this bug.

**Comment by gfgtdf** [comment] 2019-09-13 19:17
C++ 17 will have STD::from_chars which should do exactly what we want, but it's not 
Supported by most compilers yet.

**Comment by Wedge009** [comment] 2019-09-13 23:27
If `strtod` takes locale into account, why is it _not_ the right thing to use?

**Comment by gfgtdf** [comment] 2019-09-13 23:31
> If strtod takes locale into account, why is it not the right thing to use?

beasue this exactly means it takes the locale into account, this means using commans in one pc and points on another. what we want is a function that behaves the same way on all machines.

**Comment by Wedge009** [comment] 2019-09-13 23:37
Oh right, got it. I forgot that the configuration/WML is static. So it's a potential issue - wonder why @soliton- doesn't think it's the cause, then. Still, need someone who can actually replicate and verify this for us to check.

**Comment by Pentarctagon** [comment] 2019-09-14 00:29
> C++ 17 will have std::from_chars which should do exactly what we want, but it's not
> Supported by most compilers yet.

Additionally, 1.15 has C++14 as the minimum required C++ standard, and 1.14 has only C++11.

**Comment by soliton-** [comment] 2019-09-15 13:15
@Wedge009 Because as I mentioned there is a safe guard which tries to convert the number back to a string and checks if it’s the same as the initial string. Something like 0.5 would be converted to 0 or perhaps 5 and should not convert back to 0.5 so would fall back to a string.

**Comment by Wedge009** [comment] 2019-09-16 07:04
That's a good idea, but what happens in cases where the string is something like 0.500? Is that still accepted?

**Comment by soliton-** [comment] 2019-09-16 14:44
Not really sure what you're asking. If the string is 0.500 then it would convert to 0 or 500 or so but it will almost certainly not convert back to 0.500.

The point of the safe guard is to prevent storing e.g. a password that happens to look like a number as a number unless it perfectly converts back to the original string. That's because `config_attribute_value` is used to store arbitrary config values. It has no idea what type a specific value is supposed to be.

**Comment by Wedge009** [comment] 2019-09-16 15:08
I thought we're dealing with doubles, not integers. So if something was given as 0.500 then it should parse to 0.5. But then converting back to a string would be just 0.5 as well, wouldn't it? And that wouldn't match to the original 0.500.

It was just a side question anyway - the real issue is how this affects the processing of the cfg files, and how to reproduce the original report of the missing XP bars, etc.

**Comment by soliton-** [comment] 2019-09-16 16:44
Well, as I've been trying to say it should not affect the processing of cfg files since the safe guard makes sure anything that cannot be accurately converted back is saved as a string. So if `strtod` parses "wrong" (based on the locale or for any other reason) its result is not used because it shouldn't convert back accurately. So it would seem to me the actual issue must be somewhere else.

As you hinted at with your side question it seems quite rare that converting to double would convert back accurately and so maybe that's not very useful but that is indeed a side question. :)

**Comment by Wedge009** [comment] 2021-09-15 04:03
Still no information on this and 1.16 release is imminent. Have there been any more forum conversations about this problem? Then again, I suppose we should keep this open because of the use of `strtod`, which is still used in current master:
https://github.com/wesnoth/wesnoth/blob/e235d9a64e50a1af0a228292849d9a054dae76e5/src/config_attribute_value.cpp#L189

**Comment by Pentarctagon** [comment] 2022-10-25 21:45
Another instance of this has been reported on steam: https://steamcommunity.com/app/599390/discussions/0/3487500856977097528/

**Comment by CelticMinstrel** [comment] 2022-10-27 01:53
Perhaps the best approach is to use a string stream rather than `strtod`, as that lets you explicitly choose the locale.

**Comment by Pentarctagon** [comment] 2022-10-27 02:29
Above gfgtdf also previously mentioned
> C++ 17 will have std::from_chars which should do exactly what we want, but it's not
Supported by most compilers yet.

and we can use C++17 now.

**Comment by Pentarctagon** [comment] 2022-10-28 02:52
Is there any information I should as for from the person on the Steam forums? I can't seem to reproduce this myself on Linux.

**Comment by Wedge009** [comment] 2022-10-28 05:52
I don't think I was ever able to replicate the problem either, regardless of the platform. Those closest to this discussion seem to have gone, too.

**Comment by gfgtdf** [comment] 2024-04-19 16:56
Since an issue that could be related it was recently brought up again. i want to put forcus on this bug again.

I still think that using from/to_chars here is the best solution.

If we cannot use std::from/to_chars, then boost since version 1.85 also has its own implementation of from/to_chars which we can use, at least on synstems that down support from/to_chars in the theirs stadard library.

**Comment by CelticMinstrel** [comment] 2024-04-19 17:55
Using boost::from_chars sounds good to me.

**Comment by gfgtdf** [comment] 2024-04-19 18:47
> Looks like we're already using from_chars though 

Yes but only for ints.

> The next Ubuntu LTS release (24.04) only has boost 1.83 

Maybe, but we might not need it there since it it supports std::from_chars already

**Comment by Pentarctagon** [comment] 2024-04-19 19:12
It looks like (?) GCC 11 is required for float support, so for 1.19 it's no problem to bump the minimum compiler version to that.

**Comment by gfgtdf** [comment] 2024-04-19 19:39
Yes, so the requirement will me `">=gcc11" OR ">=boost 1.85" OR ">=msvc2019"`. The question is: can the steam, mingw, and macos jobs use boost 1.85.

For steam it looks like we do already pull boost in by ourselves https://github.com/wesnoth/wesnoth/blob/master/utils/dockerbuilds/CI/Dockerfile-base-steamrt#L9 and we can probably just change it to 1.85

For macos jobs it's already pretty up to date https://github.com/hrubymar10/MacCompileStuff/blob/1.18/SourcesAndScripts/Scripts/boost_build

For mingw i actually have no idea.

**Comment by Pentarctagon** [comment] 2024-04-19 21:20
I think macOS might work with the std version if the minimum version is 10.15+? Honestly it's really hard to find C++ feature support for macOS in general.

**Comment by gfgtdf** [comment] 2024-04-19 22:10
afaik clang libcxx doesnt support charconv for floating points yet even the latest version, but using boost 1.85 shouldnt be a problem on macos.

**Comment by Pentarctagon** [comment] 2024-04-19 23:25
https://libcxx.llvm.org/Status/Cxx17.html#note-p0067 says it's been available since version 14, so it might be available on Apple platforms now? Probably only really recent releases though.

**Comment by gfgtdf** [comment] 2024-04-19 23:36
it only meantioned to_chars for doubles, not from_chars,

**Comment by CelticMinstrel** [comment] 2024-04-20 00:10
I think we'd have to arrange for the Mac build to use Boost for this.

**Comment by Pentarctagon** [comment] 2024-04-20 03:42
Looks like the mingw build uses boost 1.83 currently.

**Comment by gfgtdf** [comment] 2024-04-20 14:54
> Looks like the mingw build uses boost 1.83 currently.

This seems pretty up to date, and likeley that will be updates to >=1.85, at leasrt before wesnoth 1.20 . But i wonder, is it our control or are we using a "package" prepared by soemoen else ?

**Comment by Pentarctagon** [comment] 2024-04-20 15:58
The msys2 stuff comes from https://github.com/wesnoth/wesnoth/blob/d112ca233959e25dbcf5ed0a0f48070e8132185e/utils/dockerbuilds/msys2/Dockerfile#L14

Boost is installed with pacman (https://github.com/wesnoth/wesnoth/blob/master/utils/dockerbuilds/msys2/bin/pacman-cross) at https://github.com/wesnoth/wesnoth/blob/d112ca233959e25dbcf5ed0a0f48070e8132185e/utils/dockerbuilds/CI/Dockerfile-base-mingw#L6

**Comment by Jonathan-Kelly** [comment] 2024-04-25 15:53
> The reporter's location is Slovenia and OS is Windows 7. This issue has also been reported to be working as expected on Windows 10

I can reproduce this problem on Windows 10.

If I switch the region to `English (Slovenia)` on Windows 10 the health and experience bars become one pixel tall and a number of other errors occur related to Wesnoth interpreting its data with decimal commas.

**Comment by gfgtdf** [comment] 2024-12-29 01:45
This should be fixed by #8790, woudl be nice if someone who could reprpoduzce this bug could test it

**Comment by Jonathan-Kelly** [comment] 2024-12-29 13:54
Looks like it is now fixed - I set my windows 10 machine's region to `English (Slovenia)` and reproduced the issue on Wesnoth 1.18.3 (health and experience bars appear one pixel tall) then tested it on 1.19.7 and they render normally.

Well done @gfgtdf !

**Closed** 2024-12-29 21:48 UTC
Labels: Bug, Confirmed, Ready for testing, Windows, Translations, Engine
