### ISSUE TITLE
Handling AI Detection in 1.15

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4996] opened 2020-07-16 21:50 UTC
I looked into how to handle AI-detection in 1.15.
It seems there's not good solution anymore.

Since https://github.com/wesnoth/wesnoth/pull/4147 the controller attribute is not anymore OOS-safe.
What are the Alternatives? Seem to be only possible from Lua by using `wesnoth.synchronize_choice`.

Option A: Using the controller attribute from one client
```
    [lua]
        code = <<
                return wesnoth.synchronize_choice(
                    function()

                        local side_number = wml.variables['side_number']

                        -- catch the case that side_number is nil in the game setup phase
                        if side_number == nil then return {value = false} end

                        local side = wesnoth.sides[side_number]
                        if side.controller == 'ai' then
                            return {value = true}
                        else
                            return {value = false}
                        end
                    end
                ).value
        >>
    [/lua]
```
This avoids OOS. However, depending on whose turn the above code is checked, the result will change.
Think of the option in ANL, to help another player with research.
If side 1 is played by client 1,
while side 2's player left, and the :droid 2 full command was used,
and side 3 has another human player.

This will mean during side 1's turn side 2 will be treated as AI, while in side 3's turn it's considered as a player.
Let's think about the Diplomacy Menu in ANL. If the above code is used there to disable menu options making no sense towards AI players, like helping side 2 with farming research, then side 1 and side 3 have not the same options offered.

Option B:
```
    [lua]
        code = <<
                return wesnoth.synchronize_choice(
                    function()
                        return { value = false}
                      end,
                      function()
                        return {value = true}
                      end
                ).value
        >>
    [/lua]
```
Not sure if the code for this case will work, I made a mistake when trying it out.
The idea is that the 1st function is executed by human players, while the 2nd for AI players.
The problem: One can only check against the current active side.
I.e. it would be no help for the ANL menu example, where you want to know if another side is ai-controlled.

So, I think we need a better solution for 1.16.

Besides, both approaches are rather complicated. Making differences between AI and player sides is a common thing, just normally it's indirectly checked by checking against the side number. Just, this doesn't work if you write a [modification] or [era] instead of a [scenario]. It would be good to offer an easier way. In fact it halfway exists, by checking controller in a SSF in SP.

If I didn't miss anything, in 1.14 controller= is OOS safe in Lua, and in WML it would be too if one doesn't differentiate between controller=networked and controller=human.
If that's the case, 1.16 could allow checking for it in a SSF in MP as well, if controller returns always human like it does in Lua

(However, this issue is about that it's not anymore OOS-safe in 1.15)

**Comment by gfgtdf** [comment] 2020-07-16 21:58
> depending on whose turn the above code is checked, the result will change.

I don't see why this is a problem checking directly  for controller == ai like you would do before had exactly the same problem

> Option B:

Iiirc this is effectively  the same as option A, since checking for controller=='ai' is exactly what teh engine does when choosing whetehr to call the second function or not

**Comment by Pentarctagon** [comment] 2020-07-16 22:01
#4147 did not cause this to not be MP safe - it was already noted as not being MP safe prior to that PR both in the [[side]](https://wiki.wesnoth.org/SideWML) documentation as well as being disabled entirely in [SSFs](https://wiki.wesnoth.org/StandardSideFilter).

**Comment by gfgtdf** [comment] 2020-07-16 22:20
okay a third option is to use the last parameter of wesnoth.synchronize_choice, as you probably know wesnoth.synchronize_choice
 evaluates the passed function on one client and sends the result to the other clients, usually it is evaulated on the current playing client but if you you the last parmeter you can force it to be evaluates on the client that you actualyl want to know about 

```
local side_num = wml.variables['side_number']
local is_ai = wesnoth.synchronize_choice(
  function()
    local side = wesnoth.sides[side_num]
    return { is_ai = side.controller == 'ai'}
  end, side_num ).is_ai
```

While this would always give you the correct return values is has a big disadvantage: it need to wait for side side_num to evaluate the function, for example if side_num is controlled by a client that is currently reading the help, this will wait until that client has finished doing so, furthermore  it will disallow undoing.

**Comment by Pentarctagon** [comment] 2020-07-16 22:25
From Ravana's comment in the thread linked in the [side] wiki page:

> 1.14 decided that it is private information whether side is played by AI or something else.

So it sounds like prior to 1.14 the controller value was synchronized among clients?  If it was, does anyone know the reason it became no longer synchronized during 1.13?

**Comment by gfgtdf** [comment] 2020-07-16 22:30
> 1.14 decided that it is private information whether side is played by AI or something else.

No this sound just wrong, the situation before 1.14 was basicially the same we have currently in 1.15

**Comment by Pentarctagon** [comment] 2020-07-17 02:37
Should this issue be an enhancement rather than a regression, in that case?

**Comment by sevu** [comment] 2020-07-17 03:56
> If I didn't miss anything, in 1.14 controller= is OOS safe in Lua, and in WML it would be too if one doesn't differentiate between controller=networked and controller=human.

I'd gladly like to know more on that part. I don't know where I picked up controller=networked, it's wasn't mentioned in the wiki pages. 
Of the [Lua page](https://wiki.wesnoth.org/index.php?title=LuaWML/Sides&diff=59799&oldid=59796), the last edit is quite interesting. The attribute has the same value on all clients, values like network_ai are gone. The note about OOS was probably just left there in case, but seems not based on something.

The [SSF](https://wiki.wesnoth.org/index.php?title=StandardSideFilter&diff=59801&oldid=57790) page has a similar change in the log.

That controller being blocked for filtering in MP can be bypassed by storing the side in a variable first. It's just unpractical, because you cannot use [store_side] in the context of a filter, so it must be done before … I started replacing these instances with [lua] tags to check the controller.

The part left where I can imagine OOS is, what happens if one side changes from human to ai, will it be synced?
Thinking it through, I came to a sad conclusion.
First, I don't know it.
Secondly, that case never happens. Normal droiding doesn't change the controller to ai (anymore).

And that's the sad part. My next issue or forum post would have been about the problem which you tried to solve with that PR.
I don't know if we can have both, changing controller and syncing these changes to all clients.
On the other hand, _what is the technical problem?_ Is there a reason it cannot be synced like everything else?

==========================================

As for that [forum thread](https://r.wesnoth.org/p643343) … I think there's much confusion about it. I didn't understand it last year. If I now look over it:

> 1.14 decided that it is private information whether side is played by AI or something else.

Maybe he reffered to droiding the side by that. At least it makes sense then. I don't know a way to detect droided sides.
Or, maybe option B above does so.

For the warning on the SideWML page, it [also originates](https://r.wesnoth.org/p643408) from this thread is there only because the SSF page warned about it.

**Comment by ProditorMagnus** [comment] 2020-07-17 09:47
I think that comment was because of droid yes.

**Comment by gfgtdf** [comment] 2020-07-17 11:33
> Of the Lua page, the last edit is quite interesting. The attribute has the same value on all clients, values like network_ai are gone. The note about OOS was probably just left there in case, but seems not based on something.

This is mostly true, indeed it was mostly left just in case. One way i could think of of change the controller attribute in 1.14 that would cause errors in replays would be to change it via the mp connect dialog when loading a save.

>  The part left where I can imagine OOS is, what happens if one side changes from human to ai, will it be synced?

:droid full (or :driod in 1.12) is not synced, [modify_side]controller= however is synced.

> On the other hand, what is the technical problem? Is there a reason it cannot be synced like everything else?

The technical problem is that :droid (full) can also happen on sides that are not currently playing, think for example of the case where the playing side (side 1) is currently executing a [event] that check controller= of another side (side 2), then the other side (side 2) does `:droid full` after the client of side 1 executed its event, but before it was sended to client 2. That way, even if we would notify he other clients of controller changes. The would get different values during the execution of that [event]

> Maybe he reffered to droiding the side by that. At least it makes sense then. I don't know a way to detect droided sides.
Or, maybe option B above does so.

yes makes sense

**Comment by Pentarctagon** [comment] 2020-07-17 19:12
Would it make sense to have :droid (full) be synchronized but only able to be done for sides owned by the person currently taking their turn?

**Comment by gfgtdf** [comment] 2020-07-17 19:18
> Would it make sense to have :droid (full) be synchronized but only able to be done for sides owned by the person currently taking their turn?

Not really, what we could easily do it to make it fully synconized when we allow :droid full only to be used by the currently playing side. 

Alternatively we could make the players send the 'droid' message to other clients, this would leave it 'unsynchronized'. maning you would need to use it together with wesnoth.sync_choice but it could fix the issue in the first post.

**Comment by gfgtdf** [comment] 2020-07-17 19:59
One of my main problem with controller= was always that is used in different ways:

a) some people use it to determine which side is controlled by an ai, as mentione din the example above to disabel certain features that the ai wouldn't know how to use.

b) but its also sometimes used to determine who is the 'enemy' and who the 'protagonist' in a campaign, this for example of a mod that wants to make a scenario harder by giving 'enemies' buffs,  they will probably also check for the controller attribute.

And we basicially couldn't come up with a really good solution for this problem yet.

**Comment by Pentarctagon** [comment] 2020-07-17 23:32
Wouldn't (b) be covered by checking `team_name`?

**Comment by gfgtdf** [comment] 2020-07-17 23:38
> Wouldn't (b) be covered by checking team_name?

No you can figue out which sides are allied, but not which ones are the 'protagonitst' imageine you are writign a [modification] then you have no idea which team_name specifies the side that the player controls (the protagonist) and which ones ar the enmies, you have to use the controller= attribute

**Comment by Pentarctagon** [comment] 2020-07-18 00:06
There are scenarios/campaigns that have AI as allied sides though, so while checking whether the controller is an AI is probably correct in the majority of cases, it wouldn't be able to cover all cases.  Actually without help from the add-ons the modification is used with, there probably isn't any way to know 100% of the time.

**Comment by gfgtdf** [comment] 2020-07-18 00:39
> There are scenarios/campaigns that have AI as allied sides though, so while checking whether the controller is an AI is probably correct in the majority of cases, it wouldn't be able to cover all cases. Actually without help from the add-ons the modification is used with, there probably isn't any way to know 100% of the time.

In your specific example one could instead of of just checking controller, just say something like 'is allies with a side with controller=human'

Well yes exactly, that's why we it would maybe better come up with a better solutio,  but we didn't yet. I also explained with because this was one of the reasons for the :droid change in 1.14: before 1.14 :droid would break such addons that try to check which one is the 'players side' by checking controller.

**Comment by Pentarctagon** [comment] 2020-07-21 22:04
Barring a more complete/correct solution then, it sounds like `:droid full` should be made synchronized as well?

**Comment by gfgtdf** [comment] 2020-07-21 22:50
> Barring a more complete/correct solution then, it sounds like :droid full should be made synchronized as well?


What do you mean by 'synchronized' here?

**Comment by Pentarctagon** [comment] 2020-07-22 00:11
Restricting `:droid full` to the currently playing side, and sent the controller update to other clients.

**Comment by Pentarctagon** [comment] 2020-07-22 00:31
Otherwise if it's just not possible to have the controller be updated on other clients safely, then it sounds like `:droid full` is fundamentally flawed.

**Comment by Pentarctagon** [comment] 2020-12-05 07:11
@gfgtdf if you're around, does

> Not really, what we could easily do it to make it fully synconized when we allow :droid full only to be used by the currently playing side.

mean that this issue can be fixed by only changing `:droid full` to be able to be used on the current side's turn?  Or does it additionally need to send the controller update to the other clients?

I'm going to work on fixing this, but I just want to confirm I'm understanding correctly.

**Closed** 2020-12-30 15:09 UTC
Labels: Blocker: New Stable, Lua API, MP, Regression, WML
