### ISSUE TITLE
Map size restrictions broken in wesnoth-1.13

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#1962] opened 2017-09-09 11:09 UTC
Steps to reproduce:
* start wesnoth-1.13
* click Multiplayer
* click Local game
* choose Random Map
* click settings
* set width to 20
* set number of players=9 (map width should increase to 34 at this point)
* close the generation settings window and open it again.

Expected at this point:
* number of players = 9, minimum map width=34

Actually:
* number of players = 9, width=34, but width can be minimized to 20

Note that a "smart" solution would be to check generation capabilities rather than forcing big "quadratic" minimums.
For example, generation of a 20x100 map is entirely possible for 9 players. And it makes sense -- you get a normal size front line, **you can really have a ZoC**. Map of size 20x100 is entirely playable. It would be good to support _generatable_ map sizes (the current generation mechanism requires about 120 hexes for each player, which could either be vertical, horisontal, or square).

**Comment by Vultraz** [comment] 2017-09-10 04:45
Turns out I can't reproduce this :( Min width is still 34 with 9 players after closing the dialog and reopening it.

**Comment by vn971** [comment] 2017-09-10 09:07
@Vultraz did you use the development version wesnoth-1.13* ? I've compiled mine just yesterday, but it was there for some months already. Strange.

**Comment by Vultraz** [comment] 2017-09-10 09:32
Yes, I used master.

**Comment by Wedge009** [comment] 2017-09-10 12:49
I can confirm this one. :/ I used local MP game as opposed to one on a server.

**Comment by Vultraz** [comment] 2017-09-10 13:24
As did I.

**Comment by Wedge009** [comment] 2017-09-10 13:43
Retesting against b260cdc3 I get slightly different behaviour. While minimum width remains at 34, after setting the width to 34 in the previous settings dialogue, the new dialogue shows width is set to 48.

**Comment by Vultraz** [comment] 2017-09-10 13:44
Expected I think.

**Comment by vn971** [comment] 2017-09-10 20:19
@Vultraz note that the width is really only 34 after re-opening settings. But the _minimum_ width is 20. In other words, _you can_ set width to 20 after re-opening.

**Comment by vn971** [comment] 2017-09-10 20:22
I've updated "steps to reproduce" to make it more strict.

**Comment by CelticMinstrel** [comment] 2017-09-10 20:46
Oh yeah, isn't the minimum size set based on the number of players? I should probably also implement that kind of restriction for the cave map in #993. How does it work exactly?

**Comment by Vultraz** [comment] 2017-09-10 20:48
Check the code for that dialog.

**Comment by vn971** [comment] 2017-09-10 20:57
@CelticMinstrel wesnoth-1.12 calculated minimum width and height so that map could be generated for sure even when both values are minimal (I think it's about 120 hexes per player).

Wesnoth-1.13 currently has the restriction broken when you re-open the dialog.

What I ask to consider is allowing those sizes for which the generator can generate a map. So that I could set 20x100, and clicking "close" would either generate a new map or increase the width. Smth like that. I would want this because I think a "thin-high" map is more playable in some cases.

**Comment by Vultraz** [comment] 2017-09-10 21:12
I swear I can't repro this. When I reopen the dialog I get players = 9 and width = 48 with reduction down to 34. :/

**Comment by Wedge009** [comment] 2017-09-11 05:29
I think I was at 3e9515c1 when I got the behaviour vn971 describes. When I compiled at b260cdc3 I get the behaviour Vultraz describes. Is there anything between those commits that could have affected this?

**Comment by Vultraz** [comment] 2017-09-11 05:41
The infamous acea15c312 probably.

**Comment by Wedge009** [comment] 2017-09-11 05:51
Can @vn971 confirm building on the most recent commits no longer produces this issue, please?

**Comment by vn971** [comment] 2017-09-11 07:32
Confirming the bug of width assingable to 20 is no longer present.

Feel free to close the bug if the additional proposal doesn't seem fit at the moment (of allowing any sizes, but checking on generation ability instead). With the last commit, wesnoth actually _fails_ sometimes to create a map if you specify minimum width and height. (Try a few times to see.) Which might be another sign that hard-coding stuff leads to errors, and checking map generator might provide additional advantages.

**Comment by Vultraz** [comment] 2017-09-13 14:30
Ok, I've re-confirmed that this now happens again. This was likely caused by 2b3d09c177d3 which reverted part of acea15c312.

**Closed** 2017-09-13 14:38 UTC
Labels: bug, confirmed, MP Lobby, UI
