### ISSUE TITLE
Crash when changing screen res in 1.16.0

### ISSUE THREAD

**Issue by MXB2001** [wesnoth/wesnoth#6253] opened 2021-11-03 19:04 UTC
### Game and System Information
 - What version of the game are you running?
1.16.0 

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
flathub

 - What OS are you running?
Linux Debian 9

### Describe the bug
The program exited with no further ado when I tried changing res.

### To Reproduce

1. First..
Switch to a low res. like 800x600 

2. Then...
Switch to 1280x1024 (the max size of my external monitor)

### Expected behavior
The res to change and the program to continue running.

### Additional context
error log

Battle for Wesnoth v1.16.0 x86_64
Started on Wed Nov  3 14:44:16 2021

Data directory:               /app/share/wesnoth
User configuration directory: /home/USER/.var/app/org.wesnoth.Wesnoth/config/wesnoth
User data directory:          /home/USER/.var/app/org.wesnoth.Wesnoth/data/wesnoth/1.16
Cache directory:              /home/USER/.var/app/org.wesnoth.Wesnoth/cache/wesnoth

Setting mode to 1366x768
Checking lua scripts... ok
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x4f8
  Serial number of failed request:  119506
  Current serial number in output stream:  119507

**Comment by Wedge009** [comment] 2021-11-03 22:04
Appears to be duplicate of #5518.

**Closed by Wedge009** 2021-11-03 22:04 UTC
Labels: Bug, Duplicate, Linux
