### ISSUE TITLE
Minimap viewport not clipped in fullscreen mode after changing desktop

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3255] opened 2018-06-15 17:41 UTC
1. Start DiD
2. Switch to 100% zoom
3. Switch to fullscreen mode (for me that's 1920x1080)
4. Press `-` twice to zoom out
5. At this point, the viewport annotation on the minimap (the white rectangle) is clipped to the minimap box:
![0-clipped](https://user-images.githubusercontent.com/24784687/41481600-29875406-70c2-11e8-9323-299f6c26b272.png)
6. Switch to another virtual desktop and back: press C-A-Right then C-A-Left.
7. Now the viewport annotation is not clipped to the minimap box: 
![1-viewport-not-clipped](https://user-images.githubusercontent.com/24784687/41481605-2cdd1276-70c2-11e8-8030-5a54671f2e96.png)
8. Press `0` to go back to 100% zoom. Some horizontal elements from the zoomed out viewport annotation remain:
![2-horizontal-lines-remain](https://user-images.githubusercontent.com/24784687/41481608-30e6d032-70c2-11e8-97d7-e3e3561d5f62.png)
9. If you move the viewport along the east and west edges of the map, white lines will remain along the west and east edges of the minimap:
![4-vertical-lines](https://user-images.githubusercontent.com/24784687/41481715-84d84b62-70c2-11e8-9aa4-4962ed2291d3.png)
10. At any point, toggling fullscreen mode off and back on resets the display.

This is 1.14 on Linux.

**Comment by Wedge009** [comment] 2018-06-16 06:17
I'm sure I've seen something similar - if not the same - before. I tried to find if it was reported before (I think it might have been) but perhaps it hasn't.

**Comment by jostephd** [comment] 2018-10-16 19:52
Do you mean #2742? The screenshot is at https://github.com/wesnoth/wesnoth/issues/1563#issuecomment-312409287

**Comment by Wedge009** [comment] 2018-10-17 02:17
Quite possibly. I couldn't replicate this in Windows and my Linux resolution is too low, so contrary to my previous remark maybe it's something specific to the window redraw when switching virtual desktops in Linux. I'm just guessing here.

**Comment by Wedge009** [comment] 2019-10-22 00:25
With respect to this and #2742, I only get it with SDL 2.0.10. Either way, remind me what's different between this and #2742, please? Is it just the virtual desktop aspect? I assume you still have this issue today, with 1.14.9 release or 1.14 branch.

**Comment by jostephd** [comment] 2019-10-22 00:40
I have the issue today in master. I'm not sure whether it's a duplicate of #2742 or not. It could be a duplicate, or maybe it's two different ways to get the same bug. @stevecotton, what do you think? And @shikadiqueen, you've seen this too, haven't you?

**Comment by Wedge009** [comment] 2019-10-22 00:47
Just wondering what SDL you're using with master.

**Comment by jostephd** [comment] 2019-10-22 02:21
SDL:               2.0.8  (runtime 2.0.8)
SDL_image:         2.0.1  (runtime 2.0.1)
SDL_mixer:         2.0.1  (runtime 2.0.1)
SDL_ttf:           2.0.14 (runtime 2.0.14)

**Comment by Wedge009** [comment] 2019-10-22 02:27
So looks separate to my issue then. Might be specific to virtual desktops.

**Comment by jostephd** [comment] 2019-10-22 02:32
I'm not sure how to even begin debugging this issue. I guess I should do something to log the events SDL generates when switching virtual desktop, and the events it generates when enabling fullscreen with the hotkey in-game, and diff them? Anyone knows how to do that?

**Comment by mesilliac** [comment] 2022-07-14 01:52
This should be fixed by the move to accelerated rendering, as the renderer used is now different. I tested and was unable to reproduce any similar issue. Closing for now, but please do reopen if it turns out this is still a problem.

**Closed by mesilliac** 2022-07-14 01:52 UTC
Labels: Bug, UI
