### ISSUE TITLE
A possibility of sending suspended server messages (GNA #21669)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1366] opened 2017-05-08 08:07 UTC
**[Original submission](https://gna.org/bugs/index.php?21669)** by mythological on 2014-02-17

This feature request of mine is about including an option for users logged in on a multiplayer server to send a message to another user who is offline and the message would be displayed the next time the user whom the message is sent to logs in on the same server.

(Reproduced on Any/All)
Release: 1.11.9+svn
Priority: 3 - Low
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment] 2017-05-08 08:07
**Modified on 2014-02-17**

**mythological changed item group:** None of the others -> Multiplayer Lobby

**Comment by wesnoth-bugs** [comment] 2017-05-08 08:07
**Modified on 2014-02-17**

**mythological changed severity:** 3 - Normal -> 1 - Wish

**Comment by wesnoth-bugs** [comment] 2017-05-08 08:07
**Modified on 2014-02-20**

**involution wrote:**

> This issue was touched on here:
> 
> 
> 
> http://forums.wesnoth.org/viewtopic.php?f#12&t39734&p=563929
> 
> 
> 
> I guess maybe its not clear from the discussion there, but what I'm trying to suggest is a bot that sits in channel, and is more of a "mailman" than just a logger. If Alice wants to message Bob when he gets back, she tells the bot "send this Bob when he logs on", and the bot stores it and delivers it when it sees Bob log on. I think this is a much easier solution than a source patch to wesnoth.

**Comment by Pentarctagon** [comment] 2021-08-21 20:35
Essentially a duplicate of #2473 - closing this one since more meaningful discussion has happened there even though this is the earlier issue.

**Closed by Pentarctagon** 2021-08-21 20:35 UTC
Labels: Enhancement, MP Lobby, Network
