### ISSUE TITLE
[unlock_view] in add-on scenario doesn't unlock view

### ISSUE THREAD

**Issue by singalen** [wesnoth/wesnoth#2145] opened 2017-10-29 23:10 UTC
I installed a ["Flight to liberty"](https://forums.wesnoth.org/viewtopic.php?f=31&t=40195) campaign.
Its first scenario has tags like: 

        [lock_view]
        [/lock_view]
        {HIGHLIGHT_IMAGE 12 30 items/gohere.png ()}
        [unlock_view]
        [/unlock_view]

The view locks and doesn't unlock.

(Discord channel)

> Pentarctagon: so if [unlock_view] isn't actually unlocking the view, that might be a wesnoth bug.

> Vultraz: yeah, if it doesn't work, file a bug report and assign to celmin

**Comment by CelticMinstrel** [comment] 2017-10-30 05:05
Why is this assigned to me, exactly?

**Comment by Vultraz** [comment] 2017-10-30 22:46
I cannot reproduce this. I think it must be an issue with the addon.

**Comment by GregoryLundberg** [comment] 2017-12-12 23:15
Closing this as invalid report.

The HIGHTLIGHT_IMAGE macro includes a scroll_to which occurs even when the view is locked.

Testing mainline such as in NR where [lock_view] properly prevents scrolling during start-event dicusssions (as an example) shows view locks and unlocks.

**Closed by GregoryLundberg** 2017-12-12 23:15 UTC
Labels: Bug, Needs more info, WML
