### ISSUE TITLE
UI Event Handling Overhaul

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#3538] opened 2018-09-09 21:28 UTC
From Vultraz on Discord recently, after I asked about the current state of/plans for master:

> I said months ago I didn’t know how to proceed. The problem is too complex for me.
> If I could figure out how to implement virtual mouse Raytracing or whatever the proper solution is to ensure clicks on the UI are processed by the UI and not the map, I could implement the new game UI in short order and we could proceed to the more complex stuff like OGL, texture caches, spritesheets, etc.
> But I don’t know how to properly unify the event handling systems without doing a complete rewrite
> So we’re stuck.
> I had hoped 1.16 would be a 1 year target, but at this rate it’s a 5 year target. Or possibly an impossible target.
> Too much refactoring and too many improvements have already been made on master to roll them back (and without them we’d just be left with 1.14), so basically further development is completely stalled until someone can figure out this giant mess.

Ideally then, I would like this issue to be where a more technical summary of this problem is documented as well as where anyone(new or existing) who might want to attempt to fix this problem could look to for where they should start investigating.  A previously discussed mockup of what the new UI might look like can be found [here](https://cdn.discordapp.com/attachments/231976805987385345/446323300885594152/wesnoth_new_UI_mockup_V2.JPG)(which then it looks to me like the GUI2 equivalent of a Java GlassPane is what's needed, but I could be entirely off base on that).

Therefore, @Vultraz , I'd appreciate it if you could provide those details in a comment below.

More fundamentally though, I think that not having a working master/development branch for this long is not good, and the idea that it could remain not working indefinitely is even worse, and would signal to me that the project is as good as dead.  So either this problem needs to be fixed or the commits in master that are breaking it need to be removed.  Then at the very least other progress can continue to be made and the other already existing master-only commits that have been made aren't wasted effort, as well as so other contributors such as @GregoryLundberg would be willing to work on the master branch again, even if it contains neither the existing improvements already made as a part of this nor the future improvements mentioned above such as OpenGL.

I'm also not trying to say that something needs to be done _right this minute_ or anything like that(especially given how long it's already been), but a decision on how to proceed does need to be made eventually, even if it ends up being a painful one.

**Comment by CelticMinstrel** [comment] 2018-09-09 22:14
I just want to note that current master-only commits are probably not wasted effort even if we do roll back the breakages, as long as they don't touch the broken areas (mainly UI and the help dialog). For example, any added keys in the filter APIs could easily be cherry-picked to another branch if the current master is abandoned.

**Comment by Pentarctagon** [comment] 2018-09-09 22:37
I mean they'd be wasted effort if nothing changes, since they can't go into 1.14 and if master is broken forever then there won't be a 1.15.0 either.

**Comment by CelticMinstrel** [comment] 2018-09-09 23:46
Ahh, okay. That's true, yes.

**Comment by jyrkive** [comment] 2018-09-10 02:33
**Technical summary**

In short, the problem is that the event system has no idea whether an input event is supposed to go to GUI2 or ingame. It applies not only to mouse clicks but also to keyboard input.

"Virtual mouse raytracing" is what the Unity game engine does. Whenever the player taps the screen, Unity casts a ray. UI has the first chance to capture it: if any UI element is at the tap position, it captures the ray and receives a tap event. Otherwise, the event goes to the world space, and world space elements can then capture the tap event in the same way.

Of course, a solution is needed for keyboard input as well, but it can be something similar.

In Wesnoth's case, it would mean that GUI2 needs to report back whether any GUI2 element received the input event. The rest would be trivial to implement.

**Personal anecdote**

It was extremely irresponsible of Vultraz to throw away the GUI1 sidebar and topbar implementations without having any idea how to get the GUI2 versions to work. You should never remove a feature you are not capable of reimplementing.

**State of master branch**

I fully agree with Pentarctagon. The idea that we'd forever stop development in the master branch only in order not to revert Vultraz's commits is ridiculous. There isn't even any point in having those commits there if we won't ever make a release that contains them anyway!

If Vultraz continues to hold the master branch hostage like this, he is very clearly completely unsuitable to be project leader and needs to step down.

**Comment by Vultraz** [comment] 2018-09-10 14:29
No, that sin only halfway correct. Due to the nature of the old game UI, there’s no way to implement it efrciently Ipswich accelerated rendering without significant refactoring, nor is it possible to have it work while properly implementing accelerated rendering. Most of the UI was disabled during my early work on the a_r branch anyway, so if you want a functional old UI you’d need to basically revert everything.

It is true, though, that the game UI is not essential for accelerated rendering. The UI is currently disabled, and progress could be made on the rendering underpinnings right now without worrying about the UI.

**Comment by jyrkive** [comment] 2018-09-10 14:32
@gfgtdf Correct. What we need is a way to determine if the input event is going to GUI2 or ingame. It doesn't matter how it's done: raycasting is what Unity does, but there are other possibilities.

For example, we could constrain the ingame view so that ingame is only shown within a rectangle and HUD is only shown outside said rectangle. After that dispatching mouse events is simple:

```
if (coordinates inside rectangle) {
    send event to ingame
} else {
    send event to GUI2
}
```

For keyboard events we could take the same approach as 1.14 (only ingame processes them, HUD doesn't).

**Comment by jyrkive** [comment] 2018-09-10 14:34
> Due to the nature of the old game UI, there’s no way to implement it efrciently Ipswich accelerated rendering without significant refactoring, nor is it possible to have it work while properly implementing accelerated rendering.

Actually I don't believe either of those claims.

**Comment by Vultraz** [comment] 2018-09-10 14:38
Perhaps the latter could be done, but definitely not the former. But if we decide to proceed with the deeper accelerated rendering and OGL stuff without a UI, isn't the issue of the UI moot for the moment?

**Comment by gfgtdf** [comment] 2018-09-10 16:09
> Perhaps the latter could be done, but definitely not the former

He said if we 'constrain the ingame view so that ingame is only shown within a rectangle ' which is basicially what the old ui did, its clear that this does not work for the new design.

> But if we decide to proceed with the deeper accelerated rendering and OGL stuff without a UI, isn't the issue of the UI moot for the moment?

I think having the game ui in a broken state could demotivate everyonw from working on stuff that is related to that (accelerated rendering), in particular because its unclear whether this will be fixed at all and its possible that new work on that will be reverted and work was done for nothing.

> What we need is a way to determine if the input event is going to GUI2 or ingame

This actuall doesn't sound too hard, iirc gui2::dispatcher::fire (which is called by gui2::event::sdl_event_handler::handle_event()) does already return a boolean whether it was handled, so we just need to pass that somehow along or am i missing something

**Closed** 2018-10-14 16:12 UTC
Labels: Blocker, UI, Urgent

**Comment by CelticMinstrel** [comment] 2018-10-14 18:09
I think this is something that will still be needed on the development branch eventually, though the details may differ a little. Should we reopen this, or create a new one?
