### ISSUE TITLE
UtBS, dehydration icon from S2 is not removed at the end of the scenario

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#6045] opened 2021-08-24 11:35 UTC
### Game and System Information
 - What version of the game are you running? 1.15.15
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.) Steam
 - What OS are you running? Windows 10

### Describe the bug
Units that were dehydrated at the end of S2, still have the dehydration icon.

### To Reproduce

1. First have a unit dehydrated at the end of S2.
2. Then recall it in one of the next scenarios.

### Expected behavior
The icon is removed at the end of the scenario.

### Screenshots
https://cdn.discordapp.com/attachments/259976436490829825/879442006617759765/unknown.png

### Savefiles
[UtBS-A Stirring in the Night-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/7038808/UtBS-A.Stirring.in.the.Night-Auto-Save1.gz)
Sun Sylph called Jotender that's on the map.

### Additional context
The dehydration status itself seems to have been removed.

**Comment by stevecotton** [comment] 2021-08-24 11:59
Duplicate of #5687, although with a clearer title about it affecting later scenarios.

**Comment by Pentarctagon** [comment] 2021-08-24 17:41
Closing since it's a duplicate.

**Closed by Pentarctagon** 2021-08-24 17:41 UTC
Labels: Bug, Duplicate, Campaign
