### ISSUE TITLE
Units blink when attacking while standing on animated terrain

### ISSUE THREAD

**Issue by AnekronCZ** [wesnoth/wesnoth#8364] opened 2024-02-06 21:59 UTC
### Game and System Information

- **Version:** 1.17.25
- **Downloaded from:** AUR
- **Build info:** a481923
- **OS:** Manjaro Linux (X11)

### Description of the bug

Units blink when selected to move and attack other units. h/t to sevu for suggesting it might be due to the terrain being animated; after some testing it appears to be the case. Described in detail in steps to reproduce the behaviour.

How the units blink:

https://github.com/wesnoth/wesnoth/assets/149104469/094c39cd-e36f-4572-aeb0-0698032ea234

Reproduced with two Peasants: (sprite invisible since it was captured mid blink)

![Screenshot_20240206_224731](https://github.com/wesnoth/wesnoth/assets/149104469/1bddee3a-ec9f-47cc-b31a-f74afeba5fa8)

### Steps to reproduce the behavior

1. Launch any scenario
2) Place a unit ("first unit") on animated terrain (e.g. water hex, a village with light burning inside)
3) Place enemy unit ("second unit") on animated terrain
4) Move the first unit to attack the second one so it ends it's turn on another animated hex
5) Enter the attack choice box while not covering the path the first unit has to take to attack
6) The first unit now blinks

### Expected behavior

6) First unit does not blink

**Comment by Pentarctagon** [comment] 2024-02-06 22:04
Should already be fixed with the next release as of dcde7c541ef37278043e6da953716f4888ea156b

**Comment by Wedge009** [comment] 2024-02-07 01:05
I couldn't replicate the blinking at 1.17.25 tag (only had symptom from #6960), I wonder if it's more than just a water hex necessary, maybe something to do with the transition to surrounding hexes. But definitely current master (I tested at e644613caee) looks good to me so I think it is as Pent said. If/when 1.17.26 is available please retest and close as appropriate, or build from source if you can.

**Comment by gfgtdf** [comment] 2024-02-07 01:28
I  definitely had it  blinking sometimes when i tried to reproduce https://github.com/wesnoth/wesnoth/issues/6960

**Comment by Wedge009** [comment] 2024-02-07 01:48
Can you confirm that master doesn't have the blinking then?

**Comment by AnekronCZ** [comment] 2024-02-07 06:55
Replicated the issue under Windows through Steam version 1.17.25. At this time I can't compile the current build, but if can check later if needed.

https://github.com/wesnoth/wesnoth/assets/149104469/a42bbfb0-9f3a-4ef2-bcaa-49e0d1ec121f

**Comment by Pentarctagon** [comment] 2024-02-07 06:56
I can confirm it doesn't happen for in when replicating the situation on current master.

**Comment by Pentarctagon** [comment] 2024-02-12 02:19
Closing since I can't reproduce the issue with the above fix present. Feel free to reopen if it still happens for you after the next release.

**Closed by Pentarctagon** 2024-02-12 02:19 UTC
Labels: Bug, Graphics
