### ISSUE TITLE
Wesnoth fails to remember multiple account passwords

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#6288] opened 2021-11-12 07:51 UTC
### Game and System Information
wesnoth-1.16.1 running on ArchLinux, installed from ArchLinux repository

### Describe the bug
Wesnoth seems to have bugs with remembering online account passwords. Passwords are prompted for accounts that already were submitted password for memoization, and the size of the `credentials` files grows unpredictably

### Steps to reproduce, Scenario 1
I've migrated from wesnoth-1.14 to wesnoth-1.16. Each time I start wesnoth and try to log in as "vasili", wesnoth prompts me for the password, even though I have the option to remember the password checked. Each time I close back wesnoth, `credentials` file grows by about 50 bytes.

1. Use my already existing `credentials` file... (I know it's only reproducible by me, but it's reproducible. See Scenario2 below for Steps that can be done by anybody.)
2. Start wesnoth, try to log in
3. Be prompted for the password. Enter it in, log in to main wesnoth online server
4. Close wesnoth. Observe that the `credentials` file grew by ~50 bytes
5. Start wesnoth again, try to log in, observe that password need to be entered again

### Steps to reproduce, Scenario 2
1. Remove `credentials` file (or temporarily rename it)
2. Start wesnoth, log in as "vasili" (I'm not sure if names matter, I guess you can replace with your own, except if alphabetical order or some hashing matters). Observed at this point: you are asked for the pass as expected, and the `credentials` file is around 50 bytes after closing wesnoth.
3. Start wesnoth, log in as "vasya2". Observed at this point: again you are asked for the pass as expected, and the `credentials` file grows by another 50 bytes to a total of ~100 bytes.
4. Start wesnoth, log in as "vasya2" (again). This time, you would expect wesnoth to already remember your password. It doesn't happen, however. Observed behavior is: you are asked for the pass again, and the `credentials` file grows to around 150 bytes (should've stayed at ~100 bytes at this point).
5. Start wesnoth, log in as "vasya2" (again). This time, with the `credentials` file being ~150 bytes in size, wesnoth will let you through without password prompt, as would be expected. The `credentials` file does not grow in size when closing wesnoth. This behavior should've been on previous step, but is only observed now.

### Screenshots
![2021 11 12_08:48:07](https://user-images.githubusercontent.com/33452702/141429871-58c03f4c-aaba-48ee-b307-185e01feb9eb.png)

### Additional context
There are no relevant logs being made in the console when I log in.

**Comment by Wedge009** [comment] 2021-11-12 08:50
I only have one account so I can't test scenario 2. But it sounds like there might be an issue when trying to save more than one password/account - or saving a password when there already exists a `credentials` file.

**Comment by Wedge009** [comment] 2021-11-12 08:58
Seems like scenario 2 requires two different accounts. As an experiment I manually set `remember_password=no` in the `preferences` file, but without deleting the `credentials` file. Logging in and saving the password is not an issue there, and the credentials file produced is the same as before.

**Comment by Wedge009** [comment] 2021-11-12 09:48
It looks like @CelticMinstrel introduced encrypted credentials in 1.13.9. So this is the first time the `credentials` file could have been used across major stable versions.

As best as I can tell, these are the (non-trivial) commits for `src/preferences/credentials.cpp` introduced from 1.15.0 onwards:
* 45f871067f76cad96f39acb5e37e236d30e9a3d7: replace `size_t` with `std::size_t`
* dfce371287c336e03ac85733420b22bbf283ad6b: convert `utf8::string` to `std::string`
* cdef87e87522d46dfe644231d1f682f5cbe88340: fix for #2745
* e7c0a69420f59abbaf914db2a06b610b55726d4b: fix for prior commit
* d9fb6c0bf572e204a3949b6ac904cc0516d3fc85: just adds `const` declaration
* eb9a219c5fc38c55ef3f509343a431747f67cc96: just replaces `[]` indexing with `front()` and `back()`
* 8716b8f9d01dfb94754e05eb0c4bc07b447e5df8: Apple-specific changes
* 9bc6161c3c5baf6d06f7cd4d78797ed760dcfa2c: Avoid trailing white-space

I have no idea if any of these could break credentials handling, across major versions but I can imagine even tinkering with data types could potentially change things at a raw byte level.

**Comment by Wedge009** [comment] 2021-11-12 10:27
I installed 1.14.9 from distro repository and logged in on my single account, saving the password. The credentials file produced by this version is 36 bytes while the one produced by 1.16.1 is 47 bytes - so something must have changed?

Anyway, I saved my account in 1.16.1 and there doesn't appear to be any problem reading the credentials again with subsequent opening of 1.16.1. The file size remains constant at 82 bytes, which seems to indicate that both the saved account from 1.14.9 and 1.16.1 are present (36 bytes + 47 bytes = 83 bytes - I'm assuming there's a shared byte somewhere).

**Comment by vgaming** [comment] 2021-11-12 10:57
Hey @Wedge009 , you placed a "Works for me" label on the issue. Can you please elaborate, did you test Scenario 1 or Scenario 2? Because if it's none of the scenarios, then the issue you tested is also different, and thus the  label shouldn't be applied?

**Comment by vgaming** [comment] 2021-11-12 10:59
UPDATE --^

**Comment by Wedge009** [comment] 2021-11-12 10:59
Thought it's pretty clear from what I said above, tested scenario 1.

**Comment by vgaming** [comment] 2021-11-12 10:59
@Wedge009 sorry, I've updated my comment now. Can you please read the last (updated) paragraph?

**Comment by Hejnewar** [comment] 2021-11-12 18:06
I know this issue, it actually is pretty annoying to be honest. Scenario 1 confirmed (on windows 10).

**Comment by Wedge009** [comment] 2021-11-12 22:19
Can you describe to me what you did? Migrate 1.14 `credentials` file to 1.16 and it stops working?

If you've confirmed the issue, then great, I suppose. Confirming an issue is the first part of resolving it.

**Comment by Wedge009** [comment] 2021-11-12 22:22
Oh, PR already, that's great. Maybe @Hejnewar can advise if it resolves scenario 1 as well?

**Closed** 2021-11-13 17:14 UTC
Labels: Bug, Confirmed, Engine
