### ISSUE TITLE
Text has green tint when building with MSVC

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#1921] opened 2017-08-26 21:55 UTC
See title. The text is tinted green as hell when building with MSVC and the aquelia/external toolchain. This did not happen when building with GCC and an older version of pangocairo.

It seems to go away if this line in `font/text.cpp:`

```cairo_font_options_set_antialias(fo, CAIRO_ANTIALIAS_DEFAULT);```

is changed to

```cairo_font_options_set_antialias(fo, CAIRO_ANTIALIAS_GRAY);```

But that causes other rendering issues with text. I know @shikadilord mentioned this had something to do with AA handling of pixels over semi-transparent surfaces on Windows, but why it wouldn't happen with an older pangocairo version and GCC I don't know.

**Comment by gfgtdf** [comment] 2017-08-26 22:33
maybe you could add a screenshot to compare?

**Comment by GregoryLundberg** [comment] 2017-08-26 22:34
Dunno about "green" but on Linux and Windows, both, I don't like the anti-aliasing for character/glyph. And it looks worse to me on Windows.

**Comment by Vultraz** [comment] 2017-08-26 22:43
Greeeeen:
![greeeen](https://user-images.githubusercontent.com/3558659/29745641-33824534-8b0c-11e7-9339-66737971d4dc.PNG)

**Comment by beetlenaut** [comment] 2017-08-26 23:19
The anti-aliasing is working on my system, and looks great. Here's the same text (on OpenSUSE Leap 42.3.)
![white](https://user-images.githubusercontent.com/4147859/29745787-b43de306-8a79-11e7-810c-ba7e3d9aacb1.png)

**Comment by Vultraz** [comment] 2017-08-26 23:21
I think this is a Windows problem, but certainly not exclusively a Windows problem, since it was fine with TDM GCC on Windows.

**Comment by shikadilord** [comment] 2017-08-27 01:22
Could you test this patch with the affected build configuration?

<https://gist.github.com/shikadilord/5730f0c57c861406d31f869f53e6f6d0>

**Comment by Vultraz** [comment] 2017-08-27 01:28
I don't have fontconfig, will need to find it.

```Cannot open include file: 'fontconfig/fontconfig.h': No such file or directory	wesnoth	C:\Users\\Documents\wesnoth\src\font\font_config.cpp	46	
```

**Comment by Vultraz** [comment] 2017-08-27 02:58
That doesn't seem to change anything ;_;

**Comment by shikadilord** [comment] 2017-08-27 03:19
Well, I wasn't expecting a miracle, it was really just out of curiosity.

The cause of the text being tinted green is simply that RGB subpixel hinting is unsuitable for our use case, so you absolutely need to force Cairo to use grayscale AA and deal with any issues arising from it (which, by the way, you have yet to provide a screenshot of).

**Comment by jyrkive** [comment] 2017-08-27 03:25
I'd like to also retain support for aliased rendering if the player has disabled antialiasing in Windows settings. But I can deal with that part myself.

**Comment by Vultraz** [comment] 2017-08-27 03:25
Grayscale AA, no fontconfig patch:
![gsaa](https://user-images.githubusercontent.com/3558659/29746861-64c329c0-8b33-11e7-8848-9a4bc1e77041.PNG)

**Comment by Wedge009** [comment] 2017-09-01 10:39
Took me a while to find it, but I remember #1568 being a conversation I had with @Vultraz on Windows/Linux text rendering comparison. I'm sure some of those images are still valid comparisons even now. I vaguely recall Vultraz complaining about the green tint even then (maybe on IRC).

Also, is #1744 related to this as well?

**Comment by Wedge009** [comment] 2017-09-01 10:40
Also, my personal builds use fairly recent Pango and Cairo libraries on Windows - how old are we talking about with regards to 'green tint not happening'?

**Comment by Vultraz** [comment] 2017-09-01 10:44
Cairo 1.10 and Pango 1.28 is what a binary I have sitting around from July that I built with TDM GCC gives (Disclaimer: might not be 100% accurate since I'm running it with the DLLs from the aquelia/external repo, but versions don't come from DLLs (I think?) so the result shouldn't be affected).

**Comment by gfgtdf** [comment] 2017-09-25 22:36
sry but i don't see how this is a blocker  this bug is a visual issue that a lot of people wont even notice and it only effects devs versions (the releases don'tuse msvc). Sepcailly if you compare it to many other bugs here that break mainline campaigns and that are not marked as 'blocker'

**Comment by Wedge009** [comment] 2017-09-26 07:06
I think that's a good point. Personally I don't really notice the tinting unless I really focus on the text and I'm not bothered by it.

**Comment by jyrkive** [comment] 2017-09-26 10:00
Agreed. I removed the blocker status.

**Comment by Wedge009** [comment] 2018-02-08 09:02
Is this something we want to keep for 1.14 release?

**Comment by Vultraz** [comment] 2018-02-08 09:03
Probably not. It's unfixable anyway.

**Comment by Wedge009** [comment] 2018-02-08 09:04
I'm not bothered by it, personally.

**Comment by jyrkive** [comment] 2018-02-08 09:07
Neither am I. I don't really even notice it.

**Comment by Vultraz** [comment] 2018-02-15 07:35
Interesting thing to note: rendering the text at 4K gets rid of the green tint:
![nogreen](https://user-images.githubusercontent.com/3558659/36245395-ff04fb76-127e-11e8-911c-6d6031f4d632.JPG)

**Comment by Wedge009** [comment] 2018-05-22 11:00
Revisited this since Vultraz closed the related #1568 and #1744. Directly comparing my own build (with MSVC) with the Steam release (on Windows), I can notice the text still has the slight tint, but without the direct comparison I probably wouldn't have noticed it.

**Comment by Wedge009** [comment] 2019-09-06 06:27
Since I started building for 64-bit Windows (August 2019), which includes using vcpkg, I noticed this issue now. But maybe because I had my own build plus an official build open simultaneously and suddenly noticed how poorer the fonts in my own build looked. I note official 1.14.7 build (32-bit) is using pango 1.30.1 while I'm using 1.41.0 at the moment.

**Comment by Wedge009** [comment] 2021-06-09 23:43
Does @Vultraz or anyone else still observe this? I just did a quick check on Wesnoth 1.14.16 on Windows (with pango 1.30.1) vs my own build with pango 1.48.0, and don't observe any obvious differences in text rendering.

**Comment by irydacea** [comment] 2021-06-10 13:57
This was fixed in #5618 already.

**Closed by irydacea** 2021-06-10 13:57 UTC
Labels: Bug, Graphics

**Comment by Wedge009** [comment] 2021-06-10 22:32
Didn't know they were the same issue. Thanks.
