### ISSUE TITLE
Weekdays are not localized

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2864] opened 2018-04-10 22:37 UTC
![screenshot_20180411_003506](https://user-images.githubusercontent.com/705211/38587029-51c9085e-3d20-11e8-9d45-b25d3137cf2b.png)

I am not sure if they could be translated automatically using something like ICU, if they would have to be translated manually as any other Wesnoth string, or if I would have to work around this by choosing a date formatting that does not include non-numbers.

**Comment by shikadiqueen** [comment] 2018-04-10 22:41
Duplicate of #1709.

**Closed by shikadiqueen** 2018-04-10 22:41 UTC
Labels: Bug, Duplicate, Regression, Translations
