### ISSUE TITLE
Random glitches in map preview

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#6836] opened 2022-07-03 22:41 UTC
### Game and System Information

The Battle for Wesnoth version 1.17.5+dev (635bdd8c-Clean) x86_64
Running on Freedesktop.org 21.08.14 (Flatpak runtime) x86_64
Distribution channel: Default

Boost:             1.66
Lua:               5.4.4
OpenSSL/libcrypto: 1.1.1m (runtime 1.1.1o)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.48.10 (runtime 1.48.11)
SDL:               2.0.16 (runtime 2.0.16)
SDL_image:         2.0.5 (runtime 2.0.5)
SDL_mixer:         2.0.4 (runtime 2.0.4)

SDL video drivers:        [x11] wayland dummy
Window size:              1920x1015
Game canvas size:         1920x1015
Final render target size: 1920x1015
Screen refresh rate:      60

### Description of the bug

![image](https://user-images.githubusercontent.com/3605541/177059477-4edc221a-d4fd-4259-af1c-3bc4cf26c691.png)
![image](https://user-images.githubusercontent.com/3605541/177059527-18aa5a41-5713-4e50-8121-533fbe6c38a6.png)

### Steps to reproduce the behavior

1. Open 'Create Game' dialogue 
2. Select few maps on the list

**Comment by Wedge009** [comment] 2022-07-03 22:48
I'm not able to replicate the kind of artefacts seen above, with 159d5286bd2 on Linux/X11, but what I did notice is that the map preview doesn't always refresh. eg When using the arrow keys to select the maps before/after 'A New Land', the map preview window just shows whatever the previously selected map was. Only when I switch windows via Alt-Tab and back again does the map preview draw properly - maybe something to do with bad refresh?

**Comment by knyghtmare** [comment] 2022-07-04 01:13
>  but what I did notice is that the map preview doesn't always refresh. eg When using the arrow keys to select the maps before/after 'A New Land', the map preview window just shows whatever the previously selected map was. Only when I switch windows via Alt-Tab and back again does the map preview draw properly - maybe something to do with bad refresh?

Same issue here. Map preview refresh doesn't seem to work. Might be related to this issue.

**Comment by mesilliac** [comment] 2022-07-05 06:56
Can you check if #6842 fixes it? It looks like the memory isn't being initialized before rendering the minimap. That PR should fix the problem, if that is the problem.

I'm not sure if the failure to refresh / load the correct minimap is related. If the linked PR doesn't fix it, it'll probably have to wait for Vultraz to come back as this is the implementation he pulled in.

I don't actually see either of the mentioned issues on my end. But i'm pretty sure the linked fix should at least cover the graphics corruption shown above.

**Comment by Wedge009** [comment] 2022-07-05 09:20
I'd be interested to know if it makes a difference for grz0's original issue because I was not able to replicate the corrupted screens that are in the original report. Unfortunately the PR didn't appear to make any difference for me in terms of proper map preview updates.

These are the scenarios whose map previews I've found which no longer update properly in master:
* 2p Elensefar Courtyard
* 2p Fallenstar Lake
* 2p Howling Ghost Badlands
* 2p Rufus Isle
* 2p Sablestone Delta
* 2p Silverhead Crossing
* 2p Thousand Stings Garrison
* 2p Weldyn Channel
* 3p Alirok Marsh
* 4p A New Land
* 4p Castle Hopping Isle
* 4p Clash
* 4p Morituri
* 4p Underworld
* 4p Xanthe Chaos
* 5p Forest of Fear
* 6p Hexcake
* 6p Team Survival
* 6p Volcano

I don't know if there's anything common among them or if this observation should perhaps be broken into a separate report.

**Comment by mesilliac** [comment] 2022-07-05 10:31
I merged the PR as it shouldn't cause any problems even if it doesn't fix anything. It should show up in the next nightly.

I'm not sure what could be common to those scenarios. They all seem to be rendering correctly for me. If the PR fixes the glitching then the non-rendering might be a different bug. We'll see

**Comment by Descacharrado** [comment] 2022-07-05 16:07
> Can you check if https://github.com/wesnoth/wesnoth/pull/6842 fixes it?

It seems to solve it for me (I was able to reproduce it before a503850c, W10 MSYS).

There is something definitely wrong with (at least) 2p - Thousand Stings Garrison. Sometimes the map preview updates, sometimes it does not. So creating a different report for what Wedge said seems like a good option:
> I don't know if there's anything common among them or if this observation should perhaps be broken into a separate report.

**Comment by Wedge009** [comment] 2022-07-06 04:04
It does indeed sound like a separate issue. My previous observation was on Linux/X11 with SDL 2.0.16. I just checked Windows MSVC/CMake with SDL 2.0.22 (after PR merged) and see slightly different behaviour. AMD GPUs in both cases.

If grz0 confirms the corrupted previews are resolved, this issue can be closed. I opened #6844 for the non-display that I observed.

**Comment by grz0** [comment] 2022-07-06 12:23
@mesilliac, the issue has been fixed on the latest flatpack build. Thanks.
 
The Battle for Wesnoth version 1.17.5+dev (be1a3476-Clean) x86_64
Running on Freedesktop.org 21.08.14 (Flatpak runtime) x86_64

**Closed** 2022-07-06 12:23 UTC
Labels: Bug, Confirmed, Graphics
