### ISSUE TITLE
wmlint issues

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3080] opened 2018-05-10 17:09 UTC
i just ran wmlint over worldconquest2, (mostly for the dunefolk renaming) and it made some bad changes:

* `message= "&$wct.era[$era_i].image=$temp.units=$temp.replaces"` to `message=_  "&$wct.era[$era_i].image=_ $temp.units=_ $temp.replaces"`, obviously `image` is part of a string so wmlint should not try to change it.
* `[terrain]
	terrain=Hh^Uf
	find_in=terrain_to_change
[/terrain]
` to `[terrain_type]
	terrain=Hh^Uf
	find_in=terrain_to_change
[/terrain_type]` i have no idea why it does that but it is obviously wrong.
 * `<span font-family='Lucida Sans Unicode'>` to `<span font-family=Lucida Sans Unicode>` it removes these apostrophe, no idea why, i didn't test whether actually breaks anything but especially with those whitepaces in the name i'd not be surprised if it did.
* seems like the wmlint entry for the unti id `Qatif_al_nar` is missing, (at least wmlint failed to convert that one here)
* by default it changes the core data directory aswell, (which somehow seems to break the core data directory even though it should be up to data)

**Comment by Elvish-Hunter** [comment] 2018-10-01 12:04
> `message= "&$wct.era[$era_i].image=$temp.units=$temp.replaces"` to `message=_ "&$wct.era[$era_i].image=_ $temp.units=_ $temp.replaces"`, obviously `image` is part of a string so wmlint should not try to change it.

This has been fixed by 20be511 (master) and 8e8acc9 (1.14).

> `[terrain] terrain=Hh^Uf find_in=terrain_to_change [/terrain]` to `[terrain_type] terrain=Hh^Uf find_in=terrain_to_change [/terrain_type]` i have no idea why it does that but it is obviously wrong.

This happens because, in past, `[terrain]` was used *to define terrains as well*. Of course, wmllint has no way to understand which one was the intended purpose, so it has to rely on indentation to guess it.
Explanation: if [terrain] has no indentation (no spaces or tabs before it), it's assumed to be a top level tag and define a terrain; in a comment, it is said that, for this case, wmllint relies on wmlindent being run before it.

> `<span font-family='Lucida Sans Unicode'>` to `<span font-family=Lucida Sans Unicode>` it removes these apostrophe, no idea why, i didn't test whether actually breaks anything but especially with those whitepaces in the name i'd not be surprised if it did.

I haven't been able to reproduce this behavior, sorry.

Because all the points have been addresses, I'm closing this issue.

**Closed by Elvish-Hunter** 2018-10-01 12:04 UTC
Labels: Bug, WML Tools
