### ISSUE TITLE
Map size displayed as 0x0.

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#4519] opened 2019-10-25 18:11 UTC
### Game and System Information
 - 1.15.2
 -Steam
 - Windows 10

### Describe the bug
Map size is displayed as 0x0.

### To Reproduce
Try to create game on Steam version of wesnoth. 

### Screenshots
![bug](https://user-images.githubusercontent.com/41817546/67593816-4d2b0a00-f763-11e9-896a-a7568f5a0eec.PNG)

@sevu

**Comment by ProditorMagnus** [comment] 2019-10-25 18:32
Scope not limited to steam.

**Comment by Pentarctagon** [comment] 2019-10-25 21:53
I can confirm that this happens to me for Steam and non-Steam on linux.

**Comment by jostephd** [comment] 2019-10-26 00:53
Why is @Vultraz assigned? I suspect this was caused by the combination of #4407 and e29287eeee2f5a306f09d3712efcb31b4504d7ed, but haven't confirmed.

**Comment by Vultraz** [comment] 2019-10-26 01:08
Yeah, looks like #4407 just sets the map data directly, but this requires some deeper tinkering besides just reverting. So I'll look into it since that code is my area.

**Comment by jostephd** [comment] 2019-10-26 01:11
Thanks.

**Comment by Pentarctagon** [comment] 2019-10-26 04:03
@jostephd vultraz also asked to be assigned this on Discord, which is why I went ahead and did that.

**Comment by Wedge009** [comment] 2019-10-26 08:14
Yes, issue in master, but not in 1.14.

**Comment by jostephd** [comment] 2019-10-26 08:41
Set milestone, feel free to change it though.

**Comment by Pentarctagon** [comment] 2019-11-30 19:54
Adding the Blocker label if for no other reason than this would be an absurd thing *not* to fix by 1.16.

**Comment by Pentarctagon** [comment] 2020-01-10 20:43
Fixed in #4652

**Closed by Pentarctagon** 2020-01-10 20:43 UTC
Labels: Blocker, Bug, Confirmed, Regression, UI
