### ISSUE TITLE
Campaign menu: Home/End does not change selected item (GNA #14375)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1172] opened 2017-05-08 04:26 UTC
**[Original submission](https://gna.org/bugs/index.php?14375)** by shadowmaster on 2009-09-26

Using the Home/End keys in the campaign menu's listbox changes the visible section, but it doesn't automatically select the first/last item, respectively.

(Reproduced on any)
Release: 1.7.5+svn
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment] 2017-05-08 04:26
**Modified on 2009-10-23**

**mordante wrote:**

> This is by design, same for page up and page down. After looking at it for a while I agree changing the selection in all these cases feels more natural.

**mordante changed category:** Bug -> Feature Request

**Comment by Wedge009** [comment] 2019-08-23 14:38
@CelticMinstrel This is very similar to #2631, isn't it?

**Comment by CelticMinstrel** [comment] 2019-08-24 05:15
It does look pretty similar, yeah... are you thinking of closing it as a duplicate of that?

**Comment by Wedge009** [comment] 2019-08-24 05:23
Yes, do you disagree?

**Comment by CelticMinstrel** [comment] 2019-08-24 14:57
Well, currently this one only mentions home/end while that one only mentions page up/down, and they're referring to different menus, but... they _are_ more or less the same sort of problem as far as I can see. With an edit to the title of one, I suppose the other could be closed as duplicate.

**Comment by Wedge009** [comment] 2019-08-24 16:59
#2631 only mentions Page Up/Down in the title, but @sevu also mentions pos1/end in the description (which I take to mean Home/End, but maybe it means something else). That one also seems to be more of a general description whereas this one is specifically on the Campaign menu.

**Closed** 2019-08-24 17:00 UTC
Labels: Enhancement, UI
