### ISSUE TITLE
Submerge triggers on bridges over deep water

### ISSUE THREAD

**Issue by OrangePumpking** [wesnoth/wesnoth#8705] opened 2024-04-07 08:52 UTC
### Describe the desired feature

This might actually be a bug, but I'd be surprised if nobody noticed this before so I figured it might be intentional.

Skeleton units with the submerge ability can hide on hexes with deep water. The logic is that they don't need to breath so they can just walk over the sea-floor Pirates of the Caribbean style. The trade-off is that they have tremendously low terrain disadvantage because it's hard to move in deep water like that. However, this ability also triggers on bridges. This doesn't make sense to me because they have the 40% defense for standing on the flat bridge but the submerge ability also triggers? Logically, they're in the water or they're not, so they either get the ability and poor defense or the are standing on the bridge and should get decent defense but not the ability. I'd be interested to find out if this is a bug or an intentional choice.

(I first noticed this in 1.17.21 DID S04, but I tested it in 1.18 and it works there too)

**Comment by Wedge009** [comment] 2024-04-07 20:59
Closing as duplicate of #3605. Please feel free to add your comments there.

**Closed by Wedge009** 2024-04-07 20:59 UTC
Labels: Duplicate, Enhancement
