### ISSUE TITLE
Having x/y offset applied to the frame is causing them to not render properly while zoomed in or out

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#6589] opened 2022-03-27 18:50 UTC
### Game and System Information

- **Version: 1.16.2**
- **Downloaded from: Steam**
- **OS: Windows 10**

### Description of the bug

Having x/y offset applied to the frame is causing them to not render properly while zoomed in or out. See additional context.

### Steps to reproduce the behavior

1. Launch To Land Unknown
2. Zoom in or out

### Additional context

https://user-images.githubusercontent.com/41817546/160295739-4c710e00-96de-44f6-848b-fd14dee8bf52.mp4

**Comment by doofus-01** [comment] 2022-03-27 19:52
I can't see the video, what's not rendering properly?  Mainline units with y= (Sky Hunter, for example) seem to be OK, at least in 1.17.  There was an issue with x,y= keys in animations a while back, and it was fixed in #5548, but there could be other, related cases.

**Comment by Hejnewar** [comment] 2022-03-27 20:04
Its really hard for me to describe it but after graphic moves to another location it still remains where it was, unless overwritten by something (another animation, mousing over it, etc). 

![like this](https://user-images.githubusercontent.com/41817546/160298665-7242c6d1-4764-4b2a-946c-7f5851dc62f3.JPG)

**Comment by doofus-01** [comment] 2022-03-27 21:23
I've seen something like that, I think it had to do with x/y or an out-of-hex frame in the standing frame or default image, and then no explicitly specified movement animation.  In other words, the auto-generated movement animation behaves strangely.  Does the TLU unit use a custom movement animation, or the auto/default?

**Comment by Hejnewar** [comment] 2022-03-27 23:03
TLU is using that. I actually found this bug out by trying to do similar thing and TLU is just way better example of the same thing happening. 
```
        [standing_anim]
            alpha=0
            [anim_frame]
                duration=3200
                image=units/summoners-humans/carpetrider1.png
                image_mod=~SCALE(36,36)~TC(1,magenta)
                alpha=0.8
                offset=-7.0~11.0
                y=54
                auto_vflip=false
            [/anim_frame]
        [standing_anim]
```

**Comment by doofus-01** [comment] 2022-03-28 03:37
[standing_anim] without [movement_anim] sounds like the issue, in that case.  Possibly it is an engine bug, but I think an argument could be made that the engine can't know what is wanted for units with complicated standing animations.  In any case, if you explicitly write out the [movement_anim], does the issue persist?

**Comment by Hejnewar** [comment] 2022-03-28 08:34
```
    [movement_anim]
        direction=s,se,sw
        start_time=0
        [frame]
            image="units/monsters/falcon/falcon.png"
        [/frame]
    [/movement_anim]
    [movement_anim]
        direction=n,ne,nw
        start_time=0
        [frame]
            image="units/monsters/falcon/falcon-ne.png"
        [/frame]
    [/movement_anim]

    [standing_anim]
        alpha = 0
        [bird_frame]
            duration = 10500
            image = "units/monsters/falcon/falcon-soar[1~5,4~2,1~5,4~2].png:[200*5,300,400,500,300*5,400*2,300]"
            image_mod = ~TC(4,magenta)
            alpha = 0.9
            offset = -10.0~36.0
            x = -400
            y = -800
            layer = 200
            auto_vflip = false
        [/bird_frame]
    [/standing_anim]
```

I added the [movement_anim] but the issue is unfortunatley still there. Also with this code it should be easier to replicate the issue without TLU.

**Comment by doofus-01** [comment] 2022-04-02 17:57
I tested the falcon animation, and see I did not understand the issue.  There is no unit moving anywhere, it is the image sliding around as part of the standing animation `offset = -10.0~36.0`, is that right?

I did not see any graphics glitches though.  I tried on a couple different MP maps, including the sky version of Isar's Cross, and saw nothing like the image posted above.  A difference I can think of is that I'm using source tarball on openSUSE, not Steam on Windows.  Can you post the data from the preferences info screen, that shows the SDL_image etc. versions?

**Comment by mesilliac** [comment] 2022-07-10 01:40
Can you add a minimal test case to the test scenario? (`data/scenario-test.cfg`) I'm not sure how to reproduce.

It seems like possibly the same bug as https://github.com/wesnoth/wesnoth/issues/3996 . I noticed some other bugs with animation frames not clearing properly. There's probably a really simple fix.

**Comment by doofus-01** [comment] 2022-07-11 03:38
Sure, I can do that next weekend.

It looks like almost any out-of-hex animation frame leaves similar trails, for example the Loyalist sprites I just updated.  It doesn't happen at default zoom, but there are lots of glitches when zoomed in.  However, it's not as obvious in 1.16, if it's happening at all, so maybe there is more than one thing going on.  I guess we need the test in both branches?

**Comment by mesilliac** [comment] 2022-07-11 14:00
I'm not sure yet how easy it will be to backport, but i expect the fix will be portable. So yep it would be helpful to have it in both, if it can be reproduced there.

**Comment by doofus-01** [comment] 2022-07-16 12:39
I almost thought this was fixed in 8238a1d8d55, and was about to post that I couldn't reproduce it, but it turns out the x,y keys are needed.  It looks fine without those, and it looks fine at default zoom with them.

The out-of-hex animation glitches I noted in my previous comment seem to be fixed though.

**Comment by mesilliac** [comment] 2022-07-21 05:41
The linked PR fixes the issue for me. Specifically commit ab1cdec3bdb8db58c7838a289ff0635a1cb6941c .

I also tried backporting it to 1.16 and it also fixed related issues for me there. I think this should fix a lot of issues with animation frames not clearing, as it was in the core frame invalidation code.

**Comment by mesilliac** [comment] 2022-07-22 03:11
I just committed a fix to master: 49e75f0e899e4c06ec7f9b8387d4507364239a15

Can one or both of you confirm that this fixes the issue in master?

If it's confirmed fixed, i'll backport the fix to 1.16.

**Comment by doofus-01** [comment] 2022-07-23 17:58
The test in #6878 doesn't have the problem anymore, with d9663c6fe55

**Comment by mesilliac** [comment] 2022-07-25 02:34
Alright looks like it should be well fixed then. I'll backport to 1.16 as well. Thanks for the help testing and with the test case :).

**Closed by mesilliac** 2022-07-25 02:34 UTC
Labels: Bug, Confirmed, Graphics
