### ISSUE TITLE
An error due to possibly invalid WML occurred the error message is: Mandatory widget ‘filter’ hasn’t been defined

### ISSUE THREAD

**Issue by Celaborn** [wesnoth/wesnoth#4903] opened 2020-05-15 00:50 UTC
### Game and System Information
 - What version of the game are you running?
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - What OS are you running?
IOS 13.3.1
### Describe the bug
Won’t let me download add-ons

### To Reproduce

1. First..
Tap: “Add-ons” on the main screen on the IPad
2. Then..
Tap: “Connect”
3. Lastly...
Error occurs.

Condition ‘!must_exist || result’ failed at /Users/vic/src/wesnoth/wesnoth/src/gui/auxiliary/find_widget.hpp:74 in function ‘find_widget’.

### Expected behavior

I expected to be able to add or view add-ons to download.

### Savefiles
If applicable, attach savefiles to help explain your problem. (To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.

Condition ‘!must_exist || result’ failed at /Users/vic/src/wesnoth/wesnoth/src/gui/auxiliary/find_widget.hpp:74 in function ‘find_widget’.

**Comment by soliton-** [comment] 2020-05-18 06:46
Can’t reproduce on an iPad with a resolution of 2048x1536. What resolution does your device have?

Was this error there from install? Did you try reinstalling?

**Comment by timediv** [comment] 2020-07-12 17:33
I also have this issue. Yes the problem was there with a clean install. Before I played anything at all. My screen resolution is the one of the first gen iPad pro. I was able to play a campaign just fine.

**Comment by singalen** [comment] 2020-08-18 22:32
Resolved in the latest update.

**Comment by Pentarctagon** [comment] 2020-08-19 00:09
Closing then.

**Closed by Pentarctagon** 2020-08-19 00:09 UTC
Labels: Add-ons, Bug, Needs more info, iOS
