### ISSUE TITLE
GUI: Re-folding treeview node causes other node to disappear

### ISSUE THREAD

**Issue by white-haired-uncle** [wesnoth/wesnoth#8689] opened 2024-04-05 13:43 UTC
### Game and System Information

- **Version:** v1.19.0-dev (ebe84ce5e68-Modified) 
- **OS:** `Linux spartan 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

I don't know why it says "Modified", I didn't change anything (it usually says "dirty" if I had).

### Description of the bug

When I open and close a treeview node, a neighboring node disappears.  This is different from how it worked in 1.16, and I think it's broken in 1.19

1.16:
![tv_16_1](https://github.com/wesnoth/wesnoth/assets/135195815/b9604b05-a786-4642-9dd4-0d4580362240)
![tv_16_2](https://github.com/wesnoth/wesnoth/assets/135195815/60bc1994-3640-4b39-b874-5e29a29faa6b)
![tv_16_3](https://github.com/wesnoth/wesnoth/assets/135195815/159b4087-89f3-4b91-b537-afa627f9b536)

1.19:
![tv_19_1](https://github.com/wesnoth/wesnoth/assets/135195815/8dbcab2b-e7ad-4d58-adcc-243055e27654)
![tv_19_2](https://github.com/wesnoth/wesnoth/assets/135195815/eb2908b6-7450-4ec8-b24d-62bcd723f35f)
![tv_19_3](https://github.com/wesnoth/wesnoth/assets/135195815/bd70361e-5dc3-4bd3-9a3c-cd2febace59c)

### Steps to reproduce the behavior

1. Load the attached campaign in 1.16
2. Use the right click option "Our current test GUI"
3. Unfold treenode
4. Fold treenode
5. Repeat with 1.19

[GUI_Tutorial.tar.gz](https://github.com/wesnoth/wesnoth/files/14885550/GUI_Tutorial.tar.gz)

### Expected behavior

I expect 1.19 to look like 1.16.  Perhaps I'm doing something wrong that depends on a 1.16 bug fixed in 1.19, but if so I can't find my error.

**Comment by Wedge009** [comment] 2024-04-06 23:05
> I don't know why it says "Modified", I didn't change anything (it usually says "dirty" if I had).

It could be that the sub-modules are out-of-date.

**Comment by white-haired-uncle** [comment] 2024-04-07 00:26
> > I don't know why it says "Modified", I didn't change anything (it usually says "dirty" if I had).
> 
> It could be that the sub-modules are out-of-date.

I'm not sure what that means.

Is there something I should be doing to ensure I'm reporting on a valid configuration?  thanks

**Comment by Wedge009** [comment] 2024-04-07 05:03
I'm not sure of all the details either, but the Wesnoth git tree has sub-modules for lua and mariadbpp. If those are out-of-date, then the build version is marked as modified.

Try `git submodule update --init --recursive` - if the version still reports 'modified' after that, then there must be some sort of local change in your working copy.

**Comment by Wedge009** [comment] 2024-04-07 21:56
Since this appears to be a regression, given it was working as expected in 1.16, if you could find the point at which the problem started via `git bisect`, that might help too.

**Comment by white-haired-uncle** [comment] 2024-04-26 07:23
I read a bit on git bisect, something I'd never heard of, and it seems to make sense, or it would if I knew more about git.

It looks like I can mark the current commit as bad "git bisect bad", but then I need to mark 1.16 as good but I have no clue how to do that.  The 1.16 I have just says "Battle for Wesnoth v1.16.10 x86_64", and the build directory is long gone.  I guess I could try checking out 1.16 and building again?

It looks like I installed 1.16 on Dec 12, could I just pick a commit from like Dec 10 and if that's good use it as a start?

**Comment by white-haired-uncle** [comment] 2024-04-26 13:50
I assume you mean that I could install packages for 1.17.x and test them w/o having to recompile.  I'm unable to find a ppa for dev versions (or much of anything), and 1.17.10 doesn't look like it will run under wine.  Thoughts?

I'm rather surprised there's no official ppa for wesnoth, perhaps even a fedora dnf repo.  But I suspect that's been discussed to death somewhere and there's a good reason (resources, or perhaps resources).

**Comment by white-haired-uncle** [comment] 2024-04-26 14:15
```
$ git bisect good 1.16.10
Bisecting: a merge base must be tested
warning: unable to rmdir 'src/modules/lua': Directory not empty
[31fc41bd0603f2290b8273e4eab087d28e1ca796] ran woptipng

```

```
$ scons --config=force wesnoth nls=no prefix=/opt/wesnoth-bisect
scons: Reading SConscript files ...
Saved options: default_targets = 'wesnoth,wesnothd', nls = False, prefix = '/opt/wesnoth-bisect'
Building Wesnoth version 1.15.14+dev
```

1.15.14?  That doesn't sound right?  And it fails anyway, probably here

```
scons: Configure: Checking for Boost system library...
build/sconf_temp/conftest_42561beb037fef3ac1eb711ed3d0895a_0.cpp <-
  |
  |        #include <boost/system/error_code.hpp>
  |
  |
  |        // Workaround for sdl #defining main breaking non sdl programs
  |        #ifdef main
  |        #undef main
  |        #endif
  |        int main()
  |        {
  |            return 0;
  |        }
  |
  |
g++ -o build/sconf_temp/conftest_42561beb037fef3ac1eb711ed3d0895a_0.o -c -Werror=non-virtual-dtor -std=c++17 -Wall -Wextra build/sconf_temp/conftest_42561beb037fef3ac1eb711ed3d0895a_0.cpp
scons: Configure: no

```

which is odd as I have  libboost-all-dev installed and can build 1.17/1.19 here just fine.

**Comment by Wedge009** [comment] 2024-04-26 23:42
I have both Windows and Linux as an option so if I have no idea where a regression was introduced, I can use the Windows releases to help me set the initial boundaries. But if testing via official releases isn't an option for you what you can do is (for example) `git checkout 1.17.0` and compile there, that should be the tag for 1.17.0 release. Whatever version you find, the main point is that you must be sure you've set correct boundaries for the initial search. I'm not sure why you're originally put 'good' as 1.16.10.

If you've set the boundaries as 1.17.1 and 1.17.24, then a development build during 1.17.9+dev sounds right. Bisecting does a 'binary search' to find the commit that causes your bug. After building, if you indicate the commit is good, then the next test would be somewhere between 1.17.9 and 1.17.24. If you indicate the commit is bad, then the next test would be somewhere between 1.17.1 and 1.17.9. This process repeats until you find the commit that introduces the bug.

Of course, this assumes you've actually tested that 1.17.1 is really 'good'.

By default, I believe SCons builds both wesnoth and wesnothd, I can't remember what the command is to just build wesnoth. Anyway, that's why narrowing down the initial boundaries is important if you have a slow build.

**Comment by white-haired-uncle** [comment] 2024-04-27 00:40
Thanks, that's what I've been working on.  It was going well, then I must have marked a good one bad or a bad one good. At least I don't have to start completely over.  Wish I would have taken notes, though, or installed to a unique location for each build.

I picked 1.16.10 as good because I had a 1.16.10 install and I knew it worked.  But using bisect on that gave an error, so I just tried 1.17.1, and got lucky and my first build was good so I had a new lower bound.

I suppose I probably could have looked for a flatpack, except that would involve flatpack.

'scons wesnoth' will build only the client.  But then to install (why am I installing?) you can't just do 'sudo scons install' or it will then build wesnothd, you have to 'sudo scons install wesnoth'.  And don't try something crazy like 'scons wesnoth prefix=/opt' which will just silently ignore 'wesnoth', you must use 'scons prefix=/opt wesnoth'.

**Comment by Wedge009** [comment] 2024-04-27 01:11
It's a bit tricky because of the way Wesnoth structures its development. Stable branches such as 1.16 and 1.18 fork off from the master branch as appropriate. If the break happened sometime between 1.16 and 1.18, I'd suggest to look at the 1.17 development first - in other words, confirm that 1.17.0 (or later) is 'good' and current master as 'bad' (or the most recent 1.17.x tag possible).

I don't find it necessary to 'install' Wesnoth on Linux. I just run SCons and then `./wesnoth` to run the executable.

**Comment by CelticMinstrel** [comment] 2024-04-27 01:27
> I'm not sure why you're originally put 'good' as 1.16.10.

This presumably won't work either, since 1.17.x is not descended from 1.16.x.

> If it turns out that 1.17.0 is also 'bad', then we need to do more investigation.

Well, if 1.17.0 were bad then you'd have to reach back into the 1.15.x series.

**Comment by white-haired-uncle** [comment] 2024-04-27 05:00
```
hawkeye$ git bisect bad 06254e5581c
06254e5581cbb79b5eaf72bec0dbb3fc1566b7a4 is the first bad commit
```

**Comment by Wedge009** [comment] 2024-04-27 12:59
06254e5581cbb79b5eaf72bec0dbb3fc1566b7a4

Oh dear. So another one that would belong in #7657.

**Comment by white-haired-uncle** [comment] 2024-07-31 00:55
This could be linked with #9146, which seems to be caused when using recurse=false with tree_view_node::fold() and unfold().  

I'm not sure if the user can even specify whether to recurse when using the lua API, or if it's fixed (to false?) behind the scenes.  I can't find a way to test that.

@white-haired-uncle should see what the lua API uses once he learns more about widget internals.  Hoping this self ping causes this to show up on my notification (aka todo) list.

**Comment by Vultraz** [comment] 2024-08-12 03:45
This is a very very odd bug... It *will not* happen if you use the the "official" `tree_view_node_toggle` mechanism, but it will if you manually fold/unfold, despite these being practically identical codepaths...

**Closed** 2024-08-12 04:35 UTC
Labels: Bug, UI, Regression

**Comment by CelticMinstrel** [comment] 2024-08-16 12:46
> I'm not sure if the user can even specify whether to recurse when using the lua API, or if it's fixed (to false?) behind the scenes. I can't find a way to test that.

Yeah, it's forced to false in Lua. We should do something about this…
