### ISSUE TITLE
[Lua console] Using wrong paste buffer with middle mouse click

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3462] opened 2018-08-13 01:58 UTC
It's possible to past into the Lua console with ctrl + v, ctrl + shift + v (not sure if the shift is just not recognized) and with the middle mouse click.,

It always only pastes what I copied somewhere before with ctrl +c, it never pastes text which I marked somewhere, e.g. in my text editor.

So summing up, it ignores the Unix way of copying, but not the Unix way for pasting, except of using the wrong buffer.

There was some talk about sth. like that on the bug tracker in the last years, but I don't remember the details, or if it was about the chat or the Lua Console.

**Comment by CelticMinstrel** [comment] 2018-08-13 02:31
The Lua API tag is for stuff related to scripting. This isn't related to scripting.

**Comment by shikadiqueen** [comment] 2018-08-13 05:10
Duplicate of #2847.

**Closed by shikadiqueen** 2018-08-13 05:10 UTC
Labels: BSD, Bug, Duplicate, Linux, UI
