### ISSUE TITLE
Cross-platform addons: file names case-sensitivity

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#2046] opened 2017-09-26 17:44 UTC
The goal of this proposal is to make resource loading in wesnoth cross-platform, i.e. working identically on case-sensitive and case-insensitive filesystems. This tries to eliminate the current problem of some addons working on one OS and not working on the other. A particularly popular problem is addons tested on Windows (which is case-insensitive by default), yet not working on other OSes.

One proposal is to make resource loading case-sensitive (on all platforms). This will show mistakes immediately if the addon developer uses a wrong case.

Another proposal (made in comments below) is to make resource loading case-insensitive on all platforms, meaning that wesnoth will load resources that have a different case. (Even on case-sensitive filesystems.)

Thoughts?

**Comment by gfgtdf** [comment] 2017-09-29 21:11
> This tries to eliminate the current problem of Windows addon developers testing their addon on Windows and having no idea it won't work on other OSes.

Don't we also have this problem the other way around? If a linux umc developer puts 2 files in an addon that only differ by case but have othwewise the same name, it won't work on windows.

**Comment by vn971** [comment] 2017-09-29 21:22
@gfgtdf good point! I'd add it to the same issue if you don't mind. Technically different things, but one common goal (real cross-platformness).

**Comment by GregoryLundberg** [comment] 2017-09-29 23:04
Consider a folder with 10000 files. One of those files is `mYfile`. How do i match it to `MYFILE`? I can easily convert `MYFILE` to `myfile`but I need to enumerate the entire 10000 files to find and convert `mYfile` to`myfile`. And then I am left with what to do if `mYfILe` also appears.

**Comment by vn971** [comment] 2017-09-29 23:14
@GregoryLundberg the proposal for the server is to refuse all addons that have at least 2 files with the same case-ignore name.
Technically, that's trivial to do: project all names to their lowercase values and find if there are duplicates (two entries with the same lowercase name). Finding these duplicates is easily and effectively done with a HashSet.

**Comment by GregoryLundberg** [comment] 2017-09-30 00:18
What I am trying to point out is that, while the proposal is all well-and-good, it presumes a perfect gate-keeper and can fail is amazing and surprising ways if something happens inside the walled garden.

**Comment by Arcanister** [comment] 2017-09-30 01:52
The opposite issue is less severe, since it's harder to do by mistake and it will be noticeable immediately when Wesnoth unpacks the add-on.

**Comment by gfgtdf** [comment] 2017-09-30 12:19
i have already seen projects that ship with files with the same (case  insensitive) name, even though it was just the INSTALL file it was quit annyoing sinc my first unpack programm simply refused to unpack open it. I have to say though that i don't know exactly how windows filesystem behaves when it comes to non-ascii chracters. If we were currently initially creatign the adodn server i'd probably suggest to just only allow lowercase filenames but currently this might break too many addons.

**Comment by Arcanister** [comment] 2017-09-30 16:28
Installing such add-on on Windows doesn't spit out any errors. Files get overwritten silently.

**Comment by CelticMinstrel** [comment] 2017-10-01 15:57
Um, the title of this issue seems backwards to me. It should treat filenames as case-insensitive, not case-sensitive. (And if @gfgtdf is correct, also reject filenames ending in a period. More specifically, it should reject any filenames that would be illegal on Windows.)

**Comment by vn971** [comment] 2017-10-01 17:12
@CelticMinstrel well, it was meant from the following perspective: when you load any resource (or any file at all), you do it in a case-sensitive manner, even on Windows. So if you requested file "aBC.cfg", wesnoth won't load "abc.CFG" even on Windows.

The alternative you write about (making wesnoth working case-insensitively on all platforms) could work, too.

**Comment by Arcanister** [comment] 2017-10-01 17:38
I think, case sensitive is overall better. It should also be easier to implement:
When running on OS like Windows or MacOS X, first locate needed resource file, then if its case doesn't match, throw an error or at least clearly-visible warning like:
"units/Bowment.cfg" requested "Attacks/Bow.png", but found "image/attacks/bow.png". Either rename the resource file or correct WML code.

**Comment by CelticMinstrel** [comment] 2017-10-01 18:03
I guess there are two sides to this.

1. The WML preprocessor and resource resolver should give an error if it requests a file but then finds that the case does not match. Like @Arcanister said, if an addon requests "Attacks/Bow.png", but the canonical path is actually "attacks/bow.png", that should be an error. Similarly, if you include `{./units.cfg}` but the file is actually called "units.CFG", that should be an error.
2. The add-on uploader should reject any add-on containing two files that differ only by case. For example, if the add-on contains "attacks/bow.png" and also "attacks/bow.PNG", it should not allow you to upload it.

**Comment by Ja-MiT** [comment] 2017-10-01 18:20
@vn971 when you state a preference for case-sensitive or case-insensitive, you are going beyond stating the problem into the realm of proposing one solution over the other. If you want to give your issue a better shot at the best solution (however "best" should be determined), I would suggest a solution-neutral title for the issue, such as "case-sensitivity of file names". I would also suggest that the goal of this issue be "to eliminate the current problem of Windows addon developers testing their addon on Windows and having no idea it won't work on other OSes" rather than insisting on the specific proposal "to make resource loading in wesnoth case-sensitive (on all platforms)".

(This is intended as advice. I've seen things work out poorly sometimes when people start out focused on a particular solution rather than focused on the problem.)

**Comment by vn971** [comment] 2017-10-01 18:51
@CelticMinstrel of course I don't push one solution or the other. This is why I wrote earlier "could work, too". The proposal I posted is only a proposal (the one that came to my mind), I don't insist. After all, this is what comments are made for. I'll try to rename the issue better.

**Comment by vn971** [comment] 2017-10-01 19:00
*updated the title, the first comment and the last comment.

**Comment by AI0867** [comment] 2017-10-05 14:45
I'm happy to write case checks for windows. I can't test them locally, but I can push some code for other people to test.

The problem is what to do when a case mismatch is detected. I can write to the log, but windows people rarely read those.

As I don't want to add GUI calls into the filesystem code, that basically just leaves the option of refusing to read the file, and hoping the developer notices.

**Comment by AI0867** [comment] 2017-10-05 15:18
If anyone would like to test it, here's a branch implementing case sensitivity on windows: https://github.com/AI0867/wesnoth/tree/windows-case-check

This check is based on the WIN32 API, so it won't do the same for macOS, which by default, uses HFS+ in case-insensitive mode.

**Comment by CelticMinstrel** [comment] 2017-10-06 02:29
That check looks good, but obviously we'd need a MacOS version of it too before pushing it to master. I'm not sure how that would be done.

**Comment by Arcanister** [comment] 2017-10-06 07:49
In addition to that, resource loading and expanding file inclusion should threat '\' as escaping character instead of path separator, even on Windows

**Comment by vn971** [comment] 2017-10-06 08:48
@AI0867 I can't test personally because I don't have Windows.
IIRC windows GUI programs do not even have console logs (there are strange rules to declare yourself _either_ as GUI app or as console app, something like that).

**Comment by AI0867** [comment] 2017-10-06 11:31
@vn971 yes, we log to stdout.log and stderr.log on windows, if possible.

**Comment by CelticMinstrel** [comment] 2017-10-07 05:39
I don't think `\` should be treated as an escape character. It should be treated as a path separator. If you absolutely must have an escape character, I'd recommend using `%` followed by two hex digits, since that's an already-established format in paths (URLs to be more precise, but they're closely related). Still, I don't think it's necessary.

**Comment by Wedge009** [comment] 2019-10-09 05:42
I recognise I'm late to the discussion but thinking about my experience at work, aside from case-insensitivity on Windows there's also the consideration that a number of characters considered valid for file names in Linux are not allowed in Windows (there's already some discussion on the backslash). I think what we wound up doing was just restricting file names to alpha-numeric characters, plus underscores. It's a common problem and I think a lot of projects do this.

**Comment by Wedge009** [comment] 2019-10-09 05:53
There's also #2094.

**Comment by soliton-** [comment] 2019-10-10 08:57
With @AI0867 PR merged and https://github.com/wesnoth/wesnoth/commit/37225d2 this is already solved, no?

**Comment by Wedge009** [comment] 2019-10-10 09:06
I don't work with add-ons much. Is there an easy way to test for this?

**Comment by gfgtdf** [comment] 2019-10-10 12:08
>With @AI0867 PR merged and 37225d2 this is already solved, no?

well this seems to handle only one direction, It is still possibel to writre adodsn on linux that don't work on windows for that reason as a i mentioned  in my first comment.

**Comment by gfgtdf** [comment] 2019-10-10 23:49
Oh okay i read it wrongly and assumed that commit I'd was your opr so I only read that one. Nevermind then.

**Comment by CelticMinstrel** [comment] 2019-10-11 02:21
> I think what we wound up doing was just restricting file names to alpha-numeric characters, plus underscores.

Which is actually not a very logical choice. I doubt many people who aren't programmers use underscores in their filenames. Rather than going that far, I'd just suggest restricting it according to what Windows allows, since it's the lowest common denominator. But at the very least, you should allow hyphens. (And periods of course.)

**Comment by Wedge009** [comment] 2019-10-11 03:22
Sorry I didn't make myself clear. I meant that the file names were cleaned up so that any invalid characters were changed to underscores. There's no user-input in our case, just system-generated strings. So for our case, perfectly 'logical'.

**Comment by CelticMinstrel** [comment] 2019-10-12 15:46
Oh, right. Yeah, either deleting or substituting any invalid characters is fine.

**Closed** 2019-10-20 21:26 UTC
Labels: Enhancement, WML

**Comment by ProditorMagnus** [comment] 2019-10-20 21:34
It is not possible to silently rename files, it would break preprocessing and Lua file loading.

**Comment by CelticMinstrel** [comment] 2019-11-13 01:56
@soliton- Was this closed because it was implemented/fixed or because it was rejected? If the former, please link the commit that addressed it; and if the latter, please explain some reasoning?

**Comment by AI0867** [comment] 2019-11-13 10:18
There have been two changes:
37225d24eaa52183f897e223dc3847bf89c89282 makes checks filename case on windows, helping to ensure that windows authors won't upload add-ons that will break on case-sensitive filesystems.
PR #2071 adds case-conflict checks, helping to ensure that authors on case-sensitive filesystems won't upload add-ons including multiple files that map to the same filename on case-insensitive filesystems.

I believe that addresses both concerns raised in this issue.

Unfortunately, due to technical reasons, the case-conflict checking only checks ASCII, for reasons stated [in the PR](https://github.com/wesnoth/wesnoth/pull/2071#issuecomment-336661858).
