### ISSUE TITLE
Macros stripping out plus sign (GNA #23544)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1476] opened 2017-05-08 10:10 UTC
**[Original submission](https://gna.org/bugs/index.php?23544)** by pentarctag0n on 2015-04-27

When passing a string as a macro argument, it is stripping out the plus sign and replacing it with a space.  For example:

{VARIABLE var "elves/transparent/archer+female.png"}

is stored correctly.  However:

{VARIABLE var "elves/transparent/{IMG}"}

where {IMG} was passed in as "archer+female.png" is stored as "elves/transparent/archer female.png" which causes an error when trying to use it in a [message].

(Reproduced on Windows 7)
Release: 1.13+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 10:10
**Modified on 2015-04-27**

**shadowmaster wrote:**

> The immediate solution is simply to not nest quoted strings using the preprocessor, i.e. don't quote the parameter that gets passed as IMG.

**Comment by wesnoth-bugs** [comment] 2017-05-08 10:10
**Modified on 2015-04-27**

**anonymous wrote:**

> To me it seems like we shouldnt have + signs in mainline filenames if is casues problems with the wml proprocessor. (iirc that was also the reason why we disallowed spaces?)

**Comment by wesnoth-bugs** [comment] 2017-05-08 10:10
**Modified on 2015-04-27**

**shadowmaster wrote:**

> Resource (not WML) files with paths containing whitespace only cause problems with the preprocessor if you are crazy enough to attempt to substitute a PNG's contents into your WML.
> 
> 
> 
> We mostly disallowed spaces because some of our maintenance scripts don't quote arguments right and we are too lazy to fix them.

**Comment by stevecotton** [comment] 2020-11-03 15:19
I think the macros expand to a set_variable with `value="elves/transparent/"archer+female.png""`.

This looks like string-handling to me, and the result isn't a bug, even though it is a surprise. I think the best to do would be to make it generate a warning but still do what it currently does; and I that warning would probably trigger too often with false positives.

**Comment by Pentarctagon** [comment] 2020-11-03 16:04
So there should be a warning, but then there shouldn't be a warning because it'd be output too much?

**Comment by soliton-** [comment] 2020-11-03 20:49
I agree this is not a bug but simply how macro substitution and quoting interact.

I would suggest to not quote macro substitutions (so rather `"..."{MACRO}` or even `"..." + {MACRO}`) to not run into the surprising behavior.

Maybe a macro substitution in quotes could generate a warning. Would have to check how many false positives that produces.

**Comment by soliton-** [comment] 2020-11-03 21:11
So perhaps most prominently we do use macro substitution in quotes for `map_data="{path/to/map}"`. While in the dev version that was mostly replaced with map_file that will presumably not change so quickly for UMC and there are similar uses for terrain masks for example.

I'm afraid a warning for this is not going to be practical.

**Comment by Pentarctagon** [comment] 2020-11-03 21:20
I guess this should be closed as not a bug, in that case?

**Comment by soliton-** [comment] 2020-11-03 21:26
Yes, not much we can do here.

**Closed by soliton-** 2020-11-03 21:26 UTC
Labels: Bug, WML
