### ISSUE TITLE
dead player can prevent advancing to next round (GNA #18719)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1275] opened 2017-05-08 06:24 UTC
**[Original submission](https://gna.org/bugs/index.php?18719)** by anonymous on 2011-09-22

I was playing a multiplayer match. Some time after I was dead I went out of the room and right-clicked on the playing field so I could watch the moves of the other players later.

(If you have some menu open, the display of actions is delayed until you close it again.)

When I got back it turned out the other players were not able to continue but were displayed that it was my turn. Round 10 wouldn't start while I (as a dead player) had the context menu open. I successfully reproduced the bug at the end of round 10. I was the last player in the game (4/4).

I compiled wesnoth-1.8.6 myself.

replay here: http://replays.wesnoth.org/1.8/20110922/4p_-_Isar's_Cross_Turn_11_(447).gz

(Reproduced on 2.6.37.6)
Release: 1.8.6
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 06:24
**Modified on 2017-02-15**

**gfgtdf wrote:**

> Yes that's becasue the game doesnt know when a player is is dead, specially when you might play with addons that ca restore your unit later.
> 
> 
> 
> Usually the the hosts just droids those sides in suhc a case where a dead player went afk.
> 
> 
> 
> I don't think automatic removal of the defeated player woudl be good since it migth clash with soem addons, but it migth be useful to have an option to automatically do this.
> 
> 
> 
> Actuall i think this can be implemented in lua.

**Comment by gfgtdf** [comment] 2023-08-01 00:13
I'm not really sure why i'm assigned to this, usually the only case were you randomly assign bugs to other persons is when its clear that they broke it which is clearly not the case in this bug report which is from 2011.

I'd also argue that this issue is less important now than it was before since the main motivation seemed to be the desire to replay previous turn from an mp game which is now also possible via the "Replay Turn" button.

**Comment by soliton-** [comment] 2023-08-01 17:18
Yeah, this is not a bug and not really something that can be fixed.

**Closed by soliton-** 2023-08-01 17:18 UTC
Labels: Bug, MP
