### ISSUE TITLE
[SP Campaigns] Elvish Shyde, Enchantress, and Sylph are too deadly.

### ISSUE THREAD

**Issue by Dalas121** [wesnoth/wesnoth#8740] opened 2024-04-12 12:05 UTC
### Describe the desired feature

In 1.18, the Elvish Shyde, Enchantress, and Sylph had their damage increased by 75%/45%/60%, respectively. This is comparable to increasing the Royal Guard's damage from 11x4 to 17x4. Combined with the unit lines' already impressive stats, this raises several issues:

- these units are now too strong in comparison to other mage units. The Sylph now dramatically outclasses the Great Mage, and the Enchantress is generally superior to both the Arch Mage and Lich. Sure, these are different factions, but power levels should be at least in the same ballpark.

- these units compete with the also-buffed Elvish Sharpshooter for the "mage" role. The Enchantress's lower damage is more than compensated by its higher accuracy, slow attacks, magical retaliation, and L4 advancement.

- campaigns and add-ons balanced around earlier versions of the Shyde/Enchantress/Sylph are significantly less balanced. +75% damage is a massive buff.

I suggest reverting the Shyde to her old stats (which were already very powerful), and either reverting the Enchantress/Sylph too, or rebalancing the Enchantress/Sylph as lower-damage mixed support units while leaving the Elvish Sharpshooter as the Elves' mage-equivalent.

**Comment by Hejnewar** [comment] 2024-04-12 15:55
Honestly I will just leave that to Yumi as before and whatever she decides I will balance, but what I see here is total disregard of xp so perhaps I could suggest changing that first.

**Comment by Dalas121** [comment] 2024-04-12 16:34
ATM Sylph costs 42xp more than the Great Mage (and the first 32xp on the shaman are hard to get), so I think it's fine for the Sylph to be a **little** stronger overall. But I'd be against massively turning up the XP requirements as a way to nerf the Enchantress/Sylph, unless we're creating a new level 3 elf and pushing the Enchantress/Sylph up to level 4/5.

Note that unlike the other thread, I don't think there was an issue with the process of making these changes. IIRC they sat in that forum thread for several months for feedback, though admittedly they were kinda buried on the 3rd page. I just don't think they're good changes and would prefer them altered.

**Comment by Hejnewar** [comment] 2024-04-12 17:14
I would rather say that this is a problem with wesnoth as a whole, it is an environoment where you should only level and use the strongest unit you can get (unless it is horribly countered) because in the end that is what is the most efficient and really there is no point in using anything else. And I do recognise that as a problem. 

Also what I can do is literally just tune up gold and xp. I can cut stats but that with come with xp cut. Both were problemactic decision was made, high xp stays.

**Comment by nemaara** [comment] 2024-04-12 21:19
I'm having trouble agreeing that old shyde had superb stats, as 8-3 is barely stronger than the lvl 1 mage in neutral tod. 

I did mention to hej before that the new stats might be a bit high but I really think the higher exp for elves should stay and he suggested the payoff is only worth it if the stats are higher. What if we went with a middle ground where we lower the required exp a bit and also the stats?

**Comment by Hejnewar** [comment] 2024-04-12 21:50
Yeah whatever is fine with me. 

There are other ways to solve this tho. Im considering if I should push for them or not. The reall problem is that every unit is just worth 20g in campaigns which makes some units utterly useless and others crazy op just cuz.

**Comment by loonycyborg** [comment] 2024-04-12 21:56
Maybe also give some interesting secondary attack to the magi to counterbalance slow from elf line?

**Comment by nemaara** [comment] 2024-04-12 21:56
Personally I think a buff over the old stats is actually good esp for shaman lines, just how much of a buff is the question. I agree they are strong but as I'm aiming to slightly restrict shaman usage and exp you can get in future campaign designs, they may not actually be that strong. Plus I most likely will not really let you get sylphs much.

**Comment by Hejnewar** [comment] 2024-04-12 22:06
Kinda for fun I will also mention that we can for some time now set units recall_cost in stats. :sip:

**Comment by stevecotton** [comment] 2024-04-12 22:12
If we're talking about UMC SP campaigns, a possible answer would be an add-on with a custom era that has the old balance, which any campaign add-on could use instead of the default era. I'm not taking a side in the balance debate, just pointing out a way to avoid changes when porting UMC.

**Comment by Dalas121** [comment] 2024-04-12 23:44
> I'm having trouble agreeing that old shyde had superb stats, as 8-3 is barely stronger than the lvl 1 mage in neutral tod.

I think you're looking at the Shyde as artillery, while I feel it's more of a utility/support. If we compare the old Shyde to the MoL, the MoL has +50% damage and Illuminates. The Shyde has flight, +1 move, more defense/durability, and a slow.  I'd consider those fairly balanced - the MoL is a damage-dealing frontline healer, while the old Shyde was an agile, resilient, slowing healer.

Or if we compare the old Shyde to the Saurian Seer, the old Shyde has flight, more defense/durability, and a slow. The Seer has +1 move and +1 ranged damage. I'd consider the seer meaningfully inferior to the old Shyde, not to mention the new one.

I also feel that utility/support is a good role for the Shyde (and even Enchantress/Sylph) to fill. The level-1 Shaman is utility/support, and we already have the Sharpshooter to fill the role of artillery.

> I can cut stats but that with come with xp cut. Both were problemactic decision was made, high xp stays.

I don't think XP is a great balancing mechanic for high-level units. A unit's level is supposed to tell the player information about that unit's power - 2 units of the same level and a similar role should be similar in power, even if XP costs are different.

In addition, while many campaigns are being shortened, we shouldn't rely on that when balancing units. XP might make the difference between getting a Shyde in scenario 3 vs 4, but that doesn't really matter if you're playing an older (or UMC) campaign with 20 scenarios.

> Kinda for fun I will also mention that we can for some time now set units recall_cost in stats. :sip:

Variable recall costs - I'm not confident this would be a improvement over 20g, and I feel it's also a far more extreme change than damage/hp/xp. With that in mind, I don't feel it's something we should move towards.

**Comment by loonycyborg** [comment] 2024-04-12 23:56
Slow is still the most powerful debuff accessible to playable units I think.

**Comment by nemaara** [comment] 2024-04-13 00:13
I cannot agree that the shyde had more durability than MoL, at best they were similar. I think pierce is also generally worse of an attack type than arcane. So I think regardless of her use as utility/healer, 8-3 is too low. But 14-3 might be too high too (need hej to comment on pierce dmg type vs others)

Like I said I'd like to keep the exp similar to before but the damage is probably too high, so what do you think we should do? I'm actually okay with a straight nerf personally, but hej will want to lower exp then.

**Comment by Dalas121** [comment] 2024-04-13 00:34
> I cannot agree that the shyde had more durability than MoL, at best they were similar.

Some effective HP values broken down by terrain:

| Terrain | Shyde  | MoL | MoL vs Chaotic | MoL vs Lawful |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Flat  |  102  | 78  | 104  | 59 |
| Forest | 170 | 94 | 125 | 71 |
| Hill | 102 | 94 | 125 | 71 |
| Castle | 128 | 118 | 157 | 89 |
| Frozen | 85 | 59 | 79 | 44 |
| Shallow Water | 85 | 59 | 79 | 44 |
| Swamp | 85 | 59 |  79 | 44 |
| Cave | 73 | 78 | 104 | 59 |

Vs non-fearless chaotic creatures, when it's not daytime, the MoL beats the Shyde on 5/8 terrain types (just barely on flat). In all other situations, the Shyde is meaningfully more durable.

Not to mention the advantage of mobility - the Shyde can pick and choose good fights, and has a better chance of escaping from a bad one.

> I think pierce is also generally worse of an attack type than arcane.

If we can't agree on a stats analysis, perhaps we should poll the discord (the regular one, not UMC) and get player opinion on the Shyde's power? A lot of stuff comes down to feel.

**Comment by CelticMinstrel** [comment] 2024-04-13 00:43
> poll the discord

Like I said earlier, decisions of this kind shouldn't be based solely on things that go on behind closed doors. If we're doing a poll, it should go on the forum. (It can of course be _linked_ from the Discord to get people to actually vote tho.)

**Comment by nemaara** [comment] 2024-04-13 00:45
I thought you meant hp and resists by durability, as you also mentioned defense and agility which I took to mean chance to dodge. I agree that shyde has better overall surviving power but I meant that her hp and resists were not and still aren't really better.

I think illuminates is being underestimated in this comparison, which is part of the reason MoL feels so good imo. But hej has hard numbers on the damage types so I'd like to see his response on those.

**Comment by Dalas121** [comment] 2024-04-13 00:50
> Like I said earlier, decisions of this kind shouldn't be based solely on things that go on behind closed doors.

Absolutely, thanks for the reminder.

> I thought you meant hp and resists by durability, as you also mentioned defense and agility

Ah, yes I agree their raw HP/resists aren't meaningfully different. Sorry for the confusion.

I do consider Illuminates to be really, really good, and a big part of the reason the MoL is one of the best (IMO) level-3s in the game.  But I also think that mobility and a slowing attack are also really really good.

**Comment by babaissarkar** [comment] 2024-04-13 01:40
> Personally I think a buff over the old stats is actually good esp for shaman lines, just how much of a buff is the question. I agree they are strong but as I'm aiming to slightly restrict shaman usage and exp you can get in future campaign designs, they may not actually be that strong. Plus I most likely will not really let you get sylphs much.

That's not taking into account UMC content.

**Comment by babaissarkar** [comment] 2024-04-13 01:56
I think #8741 and this one seems like duplicate of each other.
Considering the discussion, we can't probably close either though.

**Comment by CelticMinstrel** [comment] 2024-04-13 03:13
> Also, sorry, I accidentally edited one of the earlier posts, but fixed it.

It's certainly helpful that we have (mostly) full edit history on GitHub!

**Comment by Discontinuum** [comment] 2024-04-13 04:19
>  I agree they are strong but as I'm aiming to slightly restrict shaman usage and exp you can get in future campaign designs, they may not actually be that strong. Plus I most likely will not really let you get sylphs much.

I think it makes more sense to do it in the reverse order: first a new campaign design appears with new stats and then if it's successful, the changes might go further.

**Comment by nemaara** [comment] 2024-04-13 06:01
> I think #8741 and this one seems like duplicates of each other.
> Considering the discussion, we can't probably close either though.

For now can we use the other issue? It covers this one as well as the other units that may need tweaking, while this one only talks about a subset of units.

**Comment by ForestDragon-wesnoth** [comment] 2024-04-13 06:04
> > I think #8741 and this one seems like duplicates of each other.
> > Considering the discussion, we can't probably close either though.
> 
> For now can we use the other issue? It covers this one as well as the other units that may need tweaking, while this one only talks about a subset of units.

As creator of #8741 I support switching to it

**Comment by Hejnewar** [comment] 2024-04-13 07:58
> I don't think XP is a great balancing mechanic for high-level units. A unit's level is supposed to tell the player information about that unit's power - 2 units of the same level and a similar role should be similar in power, even if XP costs are different.

I completely disagree. This makes so many things not fun, this leads to restrictions in design space and makes the game more boring. Cost is what should indicate power level. So thats off the table.  

> Variable recall costs - I'm not confident this would be a improvement over 20g, and I feel it's also a far more extreme change than damage/hp/xp. With that in mind, I don't feel it's something we should move towards.

Oh Im sure you already tested it but the feedback so far was really good. Thats also why I made UtBS like that, I have units that are by far stronger than what is standard and they dont break anything. Im sure that if I put Sylph there nothing would get broken AND if i changed the unit but adjust the cost also nothing will get broken **thats the perfect way of stopping balance changes from mattering in cmapaigns most fo the time.** So in the future I will be using it, in various variations. 

> About Shyde 

I wont be refering to everything, especially that the hp doesnt take into account how often the terrains actually occur so it would be pretty useless for mp anyway (and Im not going to balance units around single campaigns). 

And again you can just check gold cost to see who is stronger instead of trying to prove a point. I did that to let people know how strong unit is by just looking at the gold (but that aslo includes upkeep, so it is not raw strength but close enough except maybe for few places). Shyde is 10 gold stronger than MoL.

Survivability Shyde is 98, MoL is 90. Damage wise Shyde is 46, MoL is 43. This is some comparison but these values dont actually scale linearly so thats just like raw comparison. 

> As creator of https://github.com/wesnoth/wesnoth/issues/8741 I support switching to 8741

Nope, that issue is basically just arguing about visibility of changes and attacking eachother, so Im going to just comment on people behaviour there and actuall stats here because discussion here is just much more cultured and there instead we just have comments that the changes are mad comparing only damage which is not very smart.

**Comment by Dalas121** [comment] 2024-04-13 09:31
> I completely disagree. This makes so many things not fun, this leads to restrictions in design space and makes the game more boring. Cost is what should indicate power level. So thats off the table.

I'm going to have to vehemently disagree with you on this one. Cost only has 2 direct impacts on the gameplay - direct recruit cost and AI target priority.

Level, on the other hand, is a stat we continually shove at the player. It's used for experience, it's used for upkeep, it's used for experience. And level is what other games use to indicate power level. It's only natural that players expect level to be used for comparison. The tutorial, for example, mentions level over 20 times. Recruit cost isn't mentioned once.

In the help menu, a unit's level is the second thing we show the player, right after the unit's name. Cost is buried on the 5th row, 3 columns down, and we don't even bother showing it in the UI side panel.

Imagine if I proposed a new directly-recruitable level 4 unit that costs 5 gold and deals 10x2 damage - that might be balanceable (low cost, high upkeep, high experience feed), but it would never fit in with existing units.

> Oh Im sure you already tested it but the feedback so far was really good. Thats also why I made UtBS like that, I have units that are by far stronger than what is standard and they dont break anything. Im sure that if I put Sylph there nothing would get broken AND if i changed the unit but adjust the cost also nothing will get broken thats the perfect way of stopping balance changes from mattering in cmapaigns most fo the time. So in the future I will be using it, in various variations.

I used to be in favor of variable recall cost, but after playing UtBS and WoF I'm much less sure. From my experience with these campaigns I've found that it takes a lot of the joy out of progression. In many cases (UtBS mostly) I was actively trying to avoid leveling my fodder units, spreading XP around as widely as possible. Since progression is an absolutely core part of Wesnoth, I would be very hesitant to change this without overwhelming support from the playerbase.

But if we do have a poll or similar that shows the overwhelming support you suggest, then Yumi and I probably need to be changing all our rework campaigns to use variable recall costs. And we should make this the official recall mechanic, instead of a campaign-by-campaign exception that needs disclaimers before every campaign.

Also note that I personally dislike the "_my units are superheroes_" design philosophy used in UtBS, but that's just my personal opinion so I'm not going to try and pretend it holds much weight.

> (and Im not going to balance units around single campaigns).

To my understanding these units appear far more often in singleplayer than multiplayer, no?

> And again you can just check gold cost to see who is stronger instead of trying to prove a point.
> Survivability Shyde is 98, MoL is 90. Damage wise Shyde is 46, MoL is 43. This is some comparison but these values dont actually scale linearly so thats just like raw comparison.

You mean, check gold to see who Hejnewar thinks is stronger? I don't necessarily disagree with your cost/power numbers (including for the old Shyde), but unless the formula/process you use is public and universally-accepted let's not suggest that it's objective truth.

**Comment by Hejnewar** [comment] 2024-04-13 10:41
> Imagine if I proposed a new directly-recruitable level 4 unit that costs 5 gold and deals 10x2 damage - that might be balanceable (low cost, high upkeep, high experience feed), but it would never fit in with existing units.

It actually already did and provided quiet interesting change of gameplay pace so no, you are wrong and I will use that in the future for sure. 

> I used to be in favor of variable recall cost, but after playing UtBS and WoF I'm much less sure. From my experience with these campaigns I've found that it takes a lot of the power and joy out of progression. In many cases (UtBS mostly) I was actively trying to avoid leveling my fodder units, spreading XP around as widely as possible. Since progression is an absolutely core part of Wesnoth, I would be very hesitant to change this without overwhelming support from the playerbase.

Thats your playstyle, others play differently, I already talked with people who like similarily to you (I think) went mostly with low levels, people who wanted to mostly play with level 2 units, and people who recall Stalwart often. And I think thats beautiful that all units from level 1 to level 3 are used by different people and everyone can enjoy something else. 

> Also note that I personally dislike the "my units are superheroes" design philosophy used in UtBS, but that's just my personal opinion so I'm not going to try and pretend it holds much weight.

But they arent. Stalwart is the most noticable example. But thats like one unit. Others are close in power to the regular mainline counterparts. Maybe they feel like that because they cost a lot on nightmare, but on easy they usually cost like 20g or so. Because yes the recall costs scale with difficulty. And anyway, you dont have to use the "superheroes" I actually ned to make them more useful anyway because they no longer level and thus are not as useful...  

And if you think that makes the progression worse, just use 100% for lvl 1, 70% for lvl 2, 40% for lvl 3, and it still works, you keep close to the 20g you had per unit, but you deal with balance changes and stronger or weaker units anyway. There are ways you just have to be willing to try to figure out something better instead of being stuck with the same imperfect thing forever. 

> To my understanding these units appear far more often in singleplayer than multiplayer, no? Or do you mean specific single campaigns (which I agree with), not single player campaigns?

LoW is MP campaign, tons of single scenario survivals that are really improved by this, World Conquest, heck even AoH because leveling lvl 2 unit is not unheard of there.

> You mean, check gold cost to see who Hejnewar thinks is stronger? I don't necessarily disagree with your cost/power numbers (including for the old Shyde), but unless the formula/process you use is universally-agreed-upon we shouldn't suggest it's objective truth.

You just really opened a pandora box here. You dont disagree buty you dont trust me or from the sound of it you are greedy for the "formula" because it has to be public otherwise it cannot be accepted (if it even exists). No matter what you just say that I do a job that cannot be trusted! If you want one make one yourself. Maybe take over the balancing duties then, you will surely be better. Its not like I do a good job anyway. So yeah from today to do the balance have fun. I will review it with pleasure.

**Comment by Discontinuum** [comment] 2024-04-13 11:21
> You just really opened a pandora box here. You dont disagree buty you dont trust me or from the sound of it you are greedy for the "formula" because it has to be public otherwise it cannot be accepted (if it even exists). No matter what you just say that I do a job that cannot be trusted! 

It's because your formula or whatever you use produces so outlandish results and changes, so that many people disagree. 

> Maybe take over the balancing duties then, you will surely be better. Its not like I do a good job anyway.

I'm actually ready to do the balance. I've been doing balance for Afterlife Rated and got pretty good results. I have a lot of wesnoth friends of different playstyles to get the opinions. I would be happy to do it with Dalas as well cause I see his reasons and he does pretty good job with SP aspects

**Comment by Dalas121** [comment] 2024-04-13 11:39
> You dont disagree buty you dont trust me or from the sound of it you are greedy for the "formula" because it has to be public otherwise it cannot be accepted (if it even exists). No matter what you just say that I do a job that cannot be trusted! If you want one make one yourself. Maybe take over the balancing duties then, you will surely be better. 

And here we were talking about how we're trying to have a productive conversation! Resorting to hyperbole (somehow I doubt you actually want me to take over balance) is unlikely to be helpful for either of us, or the game as a whole.

I don't think that _"one person's balance numbers aren't guaranteed to be objective truth"_ should be a controversial statement, no? Mine certainly aren't objective truth.

> It actually already did and provided quiet interesting change of gameplay pace so no, you are wrong and I will use that in the future for sure.

We have a pouplar add-on with a 10x2 damage level 4 unit? (and no powerful abilities/specisl) I have a hard time seeing a unit like this being publically accepted, but if the community at large is fine with that then I'll eat my words.

> But they arent. Stalwart is the most noticable example. But thats like one unit. Others are close in power to the regular mainline counterparts.

I more mean the custom mechanics, rather than the raw power level. Multiple attacks per turn, ray/nova damage without retaliation, +12 healing, a bajillion AMLAs, etc. It's not my cup of tea, but that's just my preference and I don't want to pretend like I represent the community at large on this.

> And if you think that makes the progression worse, just use 100% for lvl 1, 70% for lvl 2, 40% for lvl 3, and it still works, you keep close to the 20g you had per unit, but you deal with balance changes and stronger or weaker units anyway.

I think this gets us the worst of both worlds, unfortunately. You still have the increased complexity of variable recall costs with a different ratio for each campaign, but it also doesn't fix the balance issue - if we use 30% for level 4 (for example), the difference in power between a 48 gold Sylph and a 33 gold Great Mage is way more than 15 gold.

This also runs into issues where higher-level units are actually *cheaper* than lower-levels. With the numbers you gave, for example, a Duelist would cost 20g to recall but a Master-at-arms only gosts 18g.

I'm also still not clear what's wrong with 20g recalls? IMO balancing units around a major change like this needs to be solving a massive issue, or else I don't feel it's worth breaking all our existing campaigns and UMC.

> LoW is MP campaign, tons of single scenario survivals that are really improved by this, World Conquest, heck even AoH because leveling lvl 2 unit is not unheard of there.

Ok, that's fair.

**Comment by Hejnewar** [comment] 2024-04-13 12:19
> I don't think that "one person's balance numbers aren't guaranteed to be objective truth" should be a controversial statement, no? Mine certainly aren't objective truth.

Yes yours. The point of balance is to be the objective truth for every player not just for a single one. 

> the difference in power between a 48g Sylph and a 33g Great Mage is way more than 15g.

Here you should use %. 

> This also runs into issues where higher-level units are actually cheaper than lower-levels. With the numbers you gave, for example, a Duelist would cost 20g to recall but a Master-at-arms only needs 18g.

And right now both cost 20 despite having such a massive difference in power, also doesnt seem fair. Not to mention level 1 unit that suddenly cost 20 gold as well. 

> I'm actually ready to do the balance. I've been doing balance for Afterlife Rated and got pretty good results. I have a lot of wesnoth friends of different playstyles to get the opinions. I would be happy to do it with Dalas as well cause I see his reasons and he does pretty good job with SP aspects

So first you slander me and then ask for something like that? Are you crazy? Your results are also bad for the amount of time and tools you had (and friends it seems). Its not like Im going to even hear sorry from you for all the shit you talked about me that is not even true. And it seems Dalas also likes your opinions. 

If you didnt try so hard to attack me presonally, then honestly I would just give you a test and see how you do with your friends but instead you chose that my person is more important to slander than just pushing changes you want. But well what can I expect if you cant agrue your changes you just have to attack the person. /shrug

**Comment by AnekronCZ** [comment] 2024-04-14 07:32
I agree with Dalas on almost all his points; thought I'll mention that so it doesn't look like he's the only one with such views.

> I used to be in favor of variable recall cost, but after playing UtBS and WoF I'm much less sure. From my experience with these campaigns I've found that it takes a lot of the power and joy out of progression.

This complaint is particularly close to my heart. I can totally see how variable recall costs can add to player's experience. Tbh, it's probably the only way to keep the really long campaigns interesting without resorting to recall list wipes. That being said, many people get really attached to their units, which is quite easy since in Wesnoth, almost every unit has a unique name, traits, can carry unique items and so on. Not being able to recall a unit you really enjoy using can detract from the enjoyment quite a bit.

> Are you crazy? Your results are also bad for the amount of time and tools you had (and friends it seems). Its not like Im going to even hear sorry from you for all the shit you talked about me that is not even true. And it seems Dalas also likes your opinions.

I regret that it comes to this _us versus them_ framing again. I don't think the balance changes from 1.16 were for the worse overall. The elvish buff was imo and I'd like to see it at least partly reverted, but I don't mean that as a slight against your work and definitely not against you personally. Can we (on both sides) just keep discussing the matter and hand and refrain from attacking people and dividing into feuding groups?

**Comment by Discontinuum** [comment] 2024-04-14 07:40
>  Your results are also bad for the amount of time and tools you had
Disagree, I believe my results are pretty good, at least I have clear metrics that go into a favourable direction after my Afterlife changes were introduced

>  you cant agrue your changes you just have to attack the person
The description of #8740, of #8741, comments https://github.com/wesnoth/wesnoth/issues/8741#issuecomment-2051748683 , my comment https://github.com/wesnoth/wesnoth/issues/8741#issuecomment-2051790816 , comments by Dalas here... You answered only my "public discussion" point (in exchanges with me), and I criticised the way you handle the feedback of other people, I see it as not really constructive, my opinion is such. 

> and then ask for something like that? Are you crazy? <...> If you didnt try so hard to attack me presonally, then honestly I would just give you a test and see how you do with your friends
To add to @AnekronCZ 's, that line really sounds as if you are the owner of this game's balance, and you alone will decide who can touch it and who cannot. I understand that you may be really heated after how this discussion was going, but this "proprietary" thinking is really unconstructive and goes against the community-spirit of the game. I was really sad to hear that

**Comment by Pentarctagon** [comment] 2024-04-14 13:57
> To add to @AnekronCZ 's, that line really sounds as if you are the owner of this game's balance, and you alone will decide who can touch it and who cannot. I understand that you may be really heated after how this discussion was going, but this "proprietary" thinking is really unconstructive and goes against the community-spirit of the game. I was really sad to hear that

As per https://forums.wesnoth.org/viewtopic.php?t=52693, he's the person responsible for multiplayer content, which of course includes multiplayer balance as well. That doesn't mean balance changes can *only* be done by him, but he needs to agree with them (ie: approving #8749).

**Comment by soliton-** [comment] 2024-04-14 14:33
I think the controversial changes that are currently being talked about are regarding high level units that are pretty far from the usual multiplayer balance. If this was really needed for some mp scenarios like world conquest then I'm very curious about an explanation. Perhaps there are other ways to reach the same goal.

While balancing decisions certainly shouldn't be a free-for-all the current situation of having a single person in charge of balance is not great. Previously the balancing team consisted of 3 people. If we could return to that I think that'd help a lot.

**Comment by Discontinuum** [comment] 2024-04-14 17:20
> As per https://forums.wesnoth.org/viewtopic.php?t=52693, he's the person responsible for multiplayer content, which of course includes multiplayer balance as well. That doesn't mean balance changes can only be done by him, but he needs to agree with them (ie: approving https://github.com/wesnoth/wesnoth/pull/8749).

I understand he's a multiplayer maintainer. But in my understanding, a maintainer is supposed to arrange tasks in a certain field of responsibility for the benefit of the community. If considerable part of active community members have strong objections to certain decisions or plans, the maintainer shouldn't be able just obstruct the concerns and continue to implement plans in concern no matter what. 

But another aspect of this wording that's worrying me is that it sounds like he kinda "excludes" me and others from any participation just because of our heated exchanges and opinions. "Then honestly I would just give you a test and see how you do with your friends" sounds like persons need special approval to touch anything balance related, "to be given a test". I understand that it was in the heat of the moment but that sounds really disturbing, especially considering strong community support of changes in question. This proprietary thinking in such controversial and hot questions should be avoided and discouraged.

I also agree with the entirety of the latest message of @soliton- and I also support that balance needs to be done by a team. I believe balance is extremely vast and multi-faceted, and we need people of different views, philosophies and playing experiences to do it better and more prudently

**Comment by ForestDragon-wesnoth** [comment] 2024-04-14 17:24
I agree with soliton, a 3-person balance team would be healthier for the game than the current system

**Comment by inferno8** [comment] 2024-04-14 18:34
I wholeheartedly agree with Solition's perspective and fully support Discontinuum's argumentation as well. As someone who has been actively developing his own MP era for over a decade, I can attest to the fact that striking the right balance between unit statistics is no easy feat, especially for one person, no matter how skilled that person is. 

Currently, there are three individuals responsible for unit balance within the EoMa add-on, and their collaborative approach has proven to be very effective. In my opinion, implementing a similar democratic 3-people control system for mainline balance would not only improve the overall balance of units but also help avoid potential miscommunications in the future. By involving multiple perspectives and expertise, I think it is possible to create a more comprehensive and fair balance for players.

I'd also like to highlight that despite recent events, Hejnewar's efforts in revising a vast number of unit statistics are still truly impressive. I have known him for a considerable amount of time now, and I can confidently say that he did put a lot of effort to improve the game. It's essential to recognize and respect his hard work amidst any current challenges or controversies.

**Comment by Dalas121** [comment] 2024-04-14 19:01
> I'd also like to highlight that despite recent events, Hejnewar's efforts in revising a vast number of unit statistics are still truly impressive. I have known him for a considerable amount of time now, and I can confidently say that he did put a lot of effort to improve the game. It's essential to recognize and respect his hard work amidst any current challenges or controversies.

I agree with this, and I wanted to thank you for bringing it up. Hejn catches a lot of flak for being difficult to work with, but if we look at the actual changes he's made, I feel that the vast majority have been positive and I agree that he's putting a lot of work into improving Wesnoth.

And while I may disagree with him on this particular issue, I think Hejn did a perfectly acceptable job with the process of presenting stats to the community. If I were in his place, I would be understandably upset with the sudden uproar about changes that were made available for public feedback nearly a year ago.

Could the balancing and feedback process have been handled better? Absolutely, in my opinion. But that certainly does not justify the personal attacks and insults that have been cropping up from both sides with regards to this issue.

> Previously the balancing team consisted of 3 people. If we could return to that I think that'd help a lot.

I would be generally in favor of a 3-person balance team. But I also fear such a team might be permanently tainted with memories of the high tempers that brought it about.

**Comment by ForestDragon-wesnoth** [comment] 2024-04-14 19:04
> I would be generally in favor of a 3-person balance team. But I also fear such a team might be permanently tainted with memories of the high tempers that brought it about.

Still better than the alternative of keeping a system where a single person has a complete monopoly over something as important to the game as balance

**Comment by Pentarctagon** [comment] 2024-04-14 21:28
Who would be the additional two people?

**Comment by igorbat** [comment] 2024-04-15 09:49
I'm prepearing a document for @Pentarctagon while I know about at least 2 independant discussions of candidacies, so, please, have at least a day for a final decision.

**Comment by knyghtmare** [comment] 2024-04-15 17:03
> Who would be the additional two people?

I suppose two can be picked from dwarftough, Dalas and IPS.

**Comment by ForestDragon-wesnoth** [comment] 2024-04-15 17:18
I believe dwarftough definitely should be one of the people in the balance team. The other suggested candidates are good too, but it depends on which of them would be willing and available to work on the game's balance.

**Comment by Hejnewar** [comment] 2024-04-15 19:12
It doesnt matter what you want. If you try to force me to work with someone with whom I wont want to work with I will just quit, but fortunatley it is not up to you. I would actually take IPS tho. I know the best person was contacted but he refused, a pity but I still got something else from that so its fine.

**Comment by Mirion147** [comment] 2024-04-15 19:50
Let's keep in mind that we are all looking to work towards what is best for the game. I think it's important enough that we can maybe tone down to a more constructive tone, eh? Obviously there's the people who are actively devs and the people who aren't, but at the end of the day we're all looking towards the same goal. (Or I guess that could just be an assumption of mine)

**Comment by Hejnewar** [comment] 2024-04-15 22:24
> tone down to a more constructive tone, eh?

If you said that before my message, maybe. But now. I dont have any reason to. I dont have any reason to accept anything in fact. Thats already my courtesy. I have nothing to care about. My dev status? Bitch please. The community? Im already not in the part that is so negative about me anyway so why should I? The game? I can work alone as well. So yeah, maybe you (as in the negative people) had a hand once, but thats beautiful display of fucking up. And before you (as in you) say anything. Dont. I dont care.

**Comment by Mirion147** [comment] 2024-04-15 22:31
> > tone down to a more constructive tone, eh?
> 
> If you said that before my message, maybe. But now. I dont have any reason to. I dont have any reason to accept anything in fact. Thats already my courtesy. I have nothing to care about. My dev status? Bitch please. The community? Im already not in the part that is so negative about me anyway so why should I? The game? I can work alone as well. So yeah, maybe you (as in the negative people) had a hand once, but thats beautiful display of fucking up. And before you (as in you) say anything. Dont. I dont care.

Well now that that's out of the way. Can we be constructive now?

**Comment by Pentarctagon** [comment] 2024-04-15 23:47
@Hejnewar You've clearly put a lot of effort into improving Wesnoth, but if you don't want to be constructive, don't care about being a developer, don't care about large parts of the community, and don't care about the game itself, then I'm confused. Why *are* you here if you don't care at all about any of those things?

Members of the Project Council are expected to be willing and able to explain why they made a particular change, not to derail an entire discussion over someone else's false statement (#8741). Developers in general are also expected to follow the Community Guidelines written over on the forums.

**Comment by CelticMinstrel** [comment] 2024-04-16 00:41
> If you try to force me to work with someone with whom I wont want to work with I will just quit

I just want to note that this is _not a problem_. No-one should be forced to work with someone that they don't want to work with.

**Comment by ForestDragon-wesnoth** [comment] 2024-04-16 05:47
> > If you try to force me to work with someone with whom I wont want to work with I will just quit
> 
> I just want to note that this is _not a problem_. No-one should be forced to work with someone that they don't want to work with.

Well, the community is also being forced to work with Hejne due to his changes affecting mainline, so in my opinion that it is not one-way.

**Comment by CelticMinstrel** [comment] 2024-04-16 13:12
I don't think that analogy really holds. The community was not _collaborating_ with Hejnewar. Hejnewar was doing the work more or less my himself, maybe with community feedback, but it wasn't a collaborative effort between him and anyone else.

**Closed** 2024-04-27 16:46 UTC
Labels: Enhancement, Units

**Comment by ProditorMagnus** [comment] 2024-04-27 16:48
Would make sense to backport the campaign stat changes.

**Comment by stevecotton** [comment] 2024-04-27 17:12
> Would make sense to backport the campaign stat changes.

Which ones are those? It all seems to be core units.

**Comment by CelticMinstrel** [comment] 2024-04-27 17:15
My interpretation of Ravana's words is to add minimal unit types using `[base_unit]` to modify these units to be like the 1.19 version in mainline campaigns that use them… but that's probably actually a _lot_ of work so I don't think it would be worth it.

**Comment by ProditorMagnus** [comment] 2024-04-27 17:17
I was thinking of event based adjustment for less effort, but base_unit would look nicer in help.

**Comment by CelticMinstrel** [comment] 2024-04-27 17:20
Either way, it's probably better to do it as a `[modification]` in my opinion, rather than copy-pasting all that code into every campaign that has elves. That also enables it to be used on non-mainline campaigns.

**Comment by ProditorMagnus** [comment] 2024-04-27 17:23
I would do it as mainline [resource] included in mainline campaigns, but addon [modification] which loads this resource may be provided in addition.

**Comment by CelticMinstrel** [comment] 2024-04-27 17:26
If the consensus is that that _should_ be done, I suggest using "future" as part of the resource's ID.
