### ISSUE TITLE
Server messages do not get rendered for passive side

### ISSUE THREAD

**Issue by kallaballa** [wesnoth/wesnoth#2235] opened 2017-11-23 09:45 UTC
In game, when the active (=having turn) side quits or surrenders the pertaining server message don't get rendered on the passive (=not having turn) side. Anyway, the server messages _do_ show up in the chat log.

Edit - System: OpenSuse 42.3 with Awesome WM

Reproduce:
A creates game. B joins. A quits. B doesn't see the server messages.

![screen](https://user-images.githubusercontent.com/287266/33166645-45868de8-d03b-11e7-9f40-46750bd7328d.jpg)

**Comment by GregoryLundberg** [comment] 2017-11-27 13:49
Cannot reproduce.
Tested **_without_** your Surrender PR installed.
Whichever side quits the other (1) gets a desktop notification (2) gets a popup (since it was a 2-player game) and (3) sees the messages on-screen once all popups are closed.

I am closing this. It may be reopened if someone actually can reproduce it

**Closed by GregoryLundberg** 2017-11-27 13:49 UTC
Labels: bug, invalid, MP

**Comment by GregoryLundberg** [comment] 2017-11-27 14:46
On further testing: the issue is that you have the Chat Log dialog open for the inactive player prior to the active player quitting. Close the dialog and the on-screen messages appear (and the control change dialog pops up) as normal.

The only issue I see is that the on-screen messages really should go on-screen immediately and not wait, or come and go depending upon whether a dialog is open.

**Comment by kallaballa** [comment] 2017-11-27 14:51
Nope. i opened the chat dialog after. the messages never appeared on-screen. gonna add an html5 video of what i did.

**Comment by kallaballa** [comment] 2017-11-27 14:58
here's the video: http://viel-zu.org/screen.webm

**Comment by GregoryLundberg** [comment] 2017-11-27 15:13
Watched the video as best I could. Tried having both windows on-screen at once. I don't have the space to tile them, for me, at 800x600 they overlap a bit but enough shows to see the on-screen messages. I can't get the messages to fail to appear.

I'm on Arch, just updated as part of my morning routine.

sdl2 2.0.7-1
boost 1.65.1-2
Battle for Wesnoth v1.13.10+dev (aceabbe018-Clean)

**Comment by kallaballa** [comment] 2017-11-27 15:22
I'm on OpenSuse 42.3 update-to-date with Awesome WM. I'm using the same BfW version.

wesnoth executable is linked against:
sdl2 2.0.7-1
boost 1.58.0-8.1

thx for your efforts!

**Comment by kallaballa** [comment] 2017-11-27 17:36
I'll try to track it down
