### ISSUE TITLE
Setting a unit's facing does not redraw the unit to be facing the new direction

### ISSUE THREAD

**Issue by nemaara** [wesnoth/wesnoth#4978] opened 2020-06-30 08:02 UTC
### Game and System Information
 - What version of the game are you running?
1.15.3

### Describe the bug
As the title says. The following block of code does nothing in 1.15.3, where as it works in 1.14.
`        [modify_unit]
            [filter]
                id=Yumi
            [/filter]
            facing=ne
        [/modify_unit]
`

Edit: turns out the unit's facing actually does change in WML (the gamestate inspector shows that this works) but the game doesn't draw it properly on the screen.

### Expected behavior
I expect my unit to turn when that block of code executes, but she doesn't. 

### Savefiles
The event at the end of the turn in the following save should make my unit (Yumi) turn several times during the cutscene, but she doesn't in 1.15, while she does in 1.14.

[Gns-1-Frozen Skies-Auto-Save3.gz](https://github.com/wesnoth/wesnoth/files/4850265/Gns-1-Frozen.Skies-Auto-Save3.gz)

**Comment by gfgtdf** [comment] 2020-06-30 10:28
You say that it doesn't work on 1.15.3, have you also tested master?

**Comment by nemaara** [comment] 2020-06-30 17:27
No because I can't test master (or maybe I can but I forgot how).

**Comment by Pentarctagon** [comment] 2020-06-30 18:31
You can download the latest executable from https://sourceforge.net/projects/bfw-travis-upload/files/

**Comment by nemaara** [comment] 2020-07-01 04:21
This bug appears to be in master as well.

**Comment by gfgtdf** [comment] 2020-07-01 14:43
Okay seems to be an Invalidate_hex call missing somewhere

**Comment by gfgtdf** [comment] 2020-09-06 10:40
> Okay seems to be an Invalidate_hex call missing somewhere

Actualyl i think this might not be sufficient, seems like  facing_ is cliseley tired to the animation code.

**Comment by CelticMinstrel** [comment] 2020-09-07 01:43
Does this result from a Lua API bug, or is it using store/unstore to change the facing of a unit?

It's true that facing is closely tied to the animation code, but as far as I recall, that's limited to setting it when an attack or movement animation plays. It _should_ work to arbitrarily change a unit's facing as long as they are simply standing on a single hex. Did you try the invalidate_hex call yet?

**Comment by gfgtdf** [comment] 2020-09-07 09:51
> Does this result from a Lua API bug, or is it using store/unstore to change the facing of a unit?

Its a lua api bug

> Did you try the invalidate_hex call yet?

Yes i did and it didn't work.

**Comment by CelticMinstrel** [comment] 2020-09-07 16:27
Hmm, that's unfortunate… so we need to figure out how to fix this but without breaking the requirement that a unit's facing is always correct during an attack (otherwise backstab and the like would break)… I'm not quite sure but I think there are at least two places in core Lua that are supposed to change the unit's facing, like in `[message]` for example.

**Comment by gfgtdf** [comment] 2020-09-07 16:32
> Hmm, that's unfortunate… so we need to figure out how to fix this but without breaking the requirement that a unit's facing is always correct during an attack

This is independent to our problem, our problem here is that the units image isn't shown correctly, not that the facing attribute of units is wrong.

**Comment by CelticMinstrel** [comment] 2020-09-07 16:35
Ohhh, I misunderstood the issue then? I'd say the title of this issue is pretty misleading then. Basically what's happening is that the facing key is correct but the image is wrong?

**Comment by gfgtdf** [comment] 2020-09-07 16:36
yes, the image corrects itself when you click on the unit, that why my first idea was to just add an the invalidate_hex() call, but that didn't seem to be enouth.

**Comment by AI0867** [comment] 2020-09-10 09:47
My guess would be that while invalidate_hex causes a redraw, it doesn't reset the animation and therefore the same image is used during the redraw.

**Comment by CelticMinstrel** [comment] 2020-09-10 13:04
There shouldn't be a need to use `[animate_unit]` if all you want to do is change the facing.

**Comment by AI0867** [comment] 2020-09-14 13:01
But it's intricately tied to it. Maybe we should just make the facing key read-only (or remove it entirely, as it's not synchronized) and have people use `[animate_unit]` to change it?

**Comment by CelticMinstrel** [comment] 2020-09-14 13:45
There shouldn't be a need to use `[animate_unit]` if all you want to do is change the facing. Plus, `[animate_unit]` itself writes to the facing key, so that needs to work.

**Comment by gfgtdf** [comment] 2020-09-14 14:29
I agree with celmin here, if we can make facing work like one would expect we should do just that.

**Comment by stevecotton** [comment] 2021-03-26 07:52
> yes, the image corrects itself when you click on the unit, that why my first idea was to just add an the invalidate_hex() call, but that didn't seem to be enouth.

It turned out to be a simpler bug than that - the C++ code already works, but `facing` was included in the list of stuff that Lua can handle without calling the slower C++ path.

**Comment by stevecotton** [comment] 2021-03-26 19:31
It's more complex than I thought. Although forcing the slow path works as a workaround, it wasn't the correct fix.

**Comment by Pentarctagon** [comment] 2021-07-26 03:10
Is the non-workaround likely to be possible to implement before 1.16?

**Comment by stevecotton** [comment] 2021-07-26 09:50
I'm not the person to answer @Pentarctagon's question - at the end of the PR above I realised that I didn't know enough about that part of the codebase.

**Comment by Pentarctagon** [comment] 2021-07-26 14:12
I don't follow - forcing the slow path does fix the issue though, doesn't it?

**Comment by stevecotton** [comment] 2021-07-26 14:29
Yes, it fixes it. I guess the remaining question is, will anyone volunteer (soon) to fix the fast path?

**Comment by Pentarctagon** [comment] 2021-07-27 01:43
I can at least do a bisect once I finish the copyright update thing, so maybe that will shed some light on the issue.

**Comment by Pentarctagon** [comment] 2021-07-27 18:29
Well, it's apparently been happening since before 1.15.0.  Unfortunately a Boost-related compilation error prevents me from being able to check further back.

**Comment by stevecotton** [comment] 2021-08-05 17:03
Reproduced on a build of 3c63b1e6de8ae913f7aa2c6b3d06021f29382787 (the commit that added the fast-path) with a cherry-pick of f6a32792d023d182d350b5a2ed9e469ad67484c8 (the fix to the Boost-related compilation error). The Yumi unit turns once, but not more than once.

**Comment by Pentarctagon** [comment] 2021-08-05 18:05
So the fast path never worked then?  Or at least never fully worked?

**Comment by stevecotton** [comment] 2021-08-06 07:54
It seems so.

**Comment by Pentarctagon** [comment] 2021-08-08 04:14
Unless using the slow path for the `facing` attribute is a particular performance concern that needs to be addressed, the fix would be to make it go back to using the previously working slow path, wouldn't it?  Maybe I'm missing something.

**Comment by CelticMinstrel** [comment] 2021-08-08 16:14
That would fix `[modify_unit]`, yes. However, it doesn't fix the underlying issue of assigning the `facing` key of a unit.

Essentially, `[modify_unit]facing=` not working is the symptom, but the actual bug is that the screen is not redrawn correctly when a unit's facing is changed (by assigning `facing`).

**Comment by stevecotton** [comment] 2021-08-13 11:01
I believe the underlying bug is that C++'s `unit::appearance_changed()` is only checked when the unit is moving, it's only called from `unit_moved::do_move()`.

We're looking at `facing` because it's the attribute that always affects the sprite. Any attribute that's accessible via an SUF can affect the sprite (https://wiki.wesnoth.org/AnimationWML#How_animations_are_chosen), but `facing` is the one that the engine handles automatically.

This bug affects setting the `hitpoints` and `max_hitpoints` attributes too, for example. I've just learnt that the Orcish Grunt's "heavy breathing" is an indication that that Grunt has less than 1/3 of its max HP remaining; the fast path doesn't update the sprite when either of those stats change.

**Comment by CelticMinstrel** [comment] 2021-08-14 01:33
So, is the solution to call `appearance_changed()` more often, or what?

**Comment by stevecotton** [comment] 2021-08-14 10:01
Pinging @Vultraz.

IIUC, someone who understands the drawing and animation loop needs to work out where to test `appearance_changed()`, and to unset the `appearance_changed_` flag when it has been acted upon. At the moment that happens in only one place, but when multiple places test the flag there needs to be some coordination between them about when to unset the flag. Looking at the file histories and given that we can't ask gfgtdf, from the currently active developers the two most likely to know this code seem to be @CelticMinstrel and @Vultraz.

I'm also wondering whether simply removing the fast-path from `[modify_unit]`'s implementation would be the best option for 1.16, combined with documenting that setting keys directly from Lua might not work.

**Comment by Pentarctagon** [comment] 2021-08-14 19:45
I don't know if anyone here would know this or not, but is the "slow path" for changing a unit's facing too slow for a realistic usecase (ie: not something like a hundred units sitting around randomly changing their facing)?  I'm mostly wondering if the speed improvement for this particular case is worth the additional code complexity.

**Comment by CelticMinstrel** [comment] 2021-08-14 21:23
I'm not sure what the actual speed difference is, but the slow path serializes the entire unit to WML, modifies that WML, then spawns a new unit in its place using the modified WML.

**Comment by stevecotton** [comment] 2021-08-14 21:52
I don't know what the speed difference is either, and don't want to speculate without someone doing the test.

> is the "slow path" for changing a unit's facing too slow for a realistic usecase (ie: not something like a hundred units sitting around randomly changing their facing)?

It's not just changing facing, it would also apply to changing a hundred units' hitpoints. However, I'd prefer to reduce code complexity, so it might be worth doing the speed test.

**Comment by AI0867** [comment] 2021-08-16 07:52
An interesting test case would be a dancefloor full of units bouncing around. (changing facing and/or animation every couple hundred milliseconds)

**Comment by CelticMinstrel** [comment] 2021-10-16 15:14
Yeah, I think we should switch those attributes to the slow path as a workaround until the root of the issue can be isolated.

**Comment by CelticMinstrel** [comment] 2021-10-17 06:19
I don't think there's anything wrong with the design of the fast path… the problem is with the animation system in my opinion.

I _think_ the fast path is also fine for some things, although I'm not quite sure… it's _possible_ I may have also run into this issue when trying to test the mainlining of the Dwarvish Miner?

Disabling the fast path entirely for 1.16 seems fine, if you want to play it safe, but I wouldn't remove it entirely. In fact, if we do that, I figure we could still roll it back out for a later 1.16.x if the animation issue can be fixed? It doesn't change API, after all; only implementation.

**Comment by stevecotton** [comment] 2021-11-05 20:41
Fixed by removing the fast path in #6223. Code that uses the LuaAPI may run into similar problems, but from the perspective of the WML API the issue is fixed.

**Closed by stevecotton** 2021-11-05 20:41 UTC
Labels: Bug, Blocker: New Stable, Graphics, Regression, Engine
