### ISSUE TITLE
Arabic names of units doesn't appear

### ISSUE THREAD

**Issue by hermestrismi** [wesnoth/wesnoth#8205] opened 2024-01-04 22:56 UTC
### Game and System Information

- **Version: 1.17.20**
- **Downloaded from: ichio**
- **Build info:**
- **OS: windows 10**

### Description of the bug

When the Arabic Translation is used, the menu help (units races, names, abilities,...) appears out of the screen. only the long names appear (which suggest that the sentences are printed but phased to the left too much).
I suggest adding an horizontal scrollbar to move this window to the left sothat the sentences will be readable.s.

### Steps to reproduce the behavior

1. open wesnoth with -- all languages,
2. choose Arabic translations,
3. open a campaign, then look for the information of any unit in the help section 

### Expected behavior

Sentences should be readable 

### Additional context

Although Arabic Translation is not completed, this will make the translations efforts even harder.!
[20240105_000402_mfnr.jpg](https://github.com/wesnoth/wesnoth/assets/107231570/c3c51fbc-9070-4270-989c-7a8fc36d590a)

**Comment by Pentarctagon** [comment] 2024-01-04 22:57
Can you add a screenshot of the issue?

**Comment by hermestrismi** [comment] 2024-01-04 23:05
> Can you add a screenshot of the issue?

![20240105_000402_mfnr.jpg](https://github.com/wesnoth/wesnoth/assets/107231570/2827c8c2-4ea8-4940-8682-3eb11b194852)

**Comment by hermestrismi** [comment] 2024-01-04 23:10
> Can you add a screenshot of the issue?

unfortunately, I can't say if this caused by the uncompleted translations or the fact that Arabic is a right-to-left language.
Still, I think that an horizontal scroll can make the player able to read the full name of the type of the unit (and other windows).

**Comment by Pentarctagon** [comment] 2024-01-04 23:12
@Vultraz do you have any ideas for what the issue might be?

**Comment by hermestrismi** [comment] 2024-01-04 23:29
![20240105_002514_mfnr.jpg](https://github.com/wesnoth/wesnoth/assets/107231570/b04937cd-81bc-4e41-bfbf-c85e6ab59a18)

further details:
if the sentence is "one word" it appears clear and complete,
if it is more than one, only a part appears. like 'Dwarvish St' Instead of 'Dwarvish Steelclad' which suggest that the name exist but out of the screen range.

**Comment by stevecotton** [comment] 2024-01-05 09:10
Probably a duplicate of #5600, although it's got a lot worse than it was in the screenshots for #5600.

**Comment by hermestrismi** [comment] 2024-01-05 11:07
> Probably a duplicate of #5600, although it's got a lot worse than it was in the screenshots for #5600.

Although Arabic and Hebrew are both right-to-left languages, Hebrew text doesn't appear very effected by this behavior. Also, the Hebrew sentences are not cut in the middle. otherwise, other features of the bug are the same in both cases

**Closed** 2024-01-20 13:28 UTC
Labels: Bug, UI, Help
