### ISSUE TITLE
modify_unit recall_cost vector::_M_range_check

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#7159] opened 2022-11-22 20:45 UTC
### Game and System Information

1.16.0

### Description of the bug

When running this action with side=2 or empty filter, chat area is filled with errors. When running with side=1, there are no visible errors. However, action of increasing recall cost works even despite errors.

### Steps to reproduce the behavior

Reproduced on 2p-clearing gushes with wesnoth.require("wml-utils").handle_event_commands(wml.load("~add-ons/EventLoader/action.cfg"))
```
[modify_unit]
    [filter]
		side=2
    [/filter]
    [object]
        [effect]
            apply_to="recall_cost"
            increase=10
            times="per level"
        [/effect]
    [/object]
[/modify_unit]
```

### Expected behavior

No visible errors.

### Additional context

https://discord.com/channels/231976805987385345/442775044590927873/1044512035431530506 has screenshot

**Comment by Wedge009** [comment] 2022-11-23 00:09
Possible to attach the screen directly?

**Comment by stevecotton** [comment] 2022-11-23 01:00
I'm not debugging this (other things to do), but my intuition is that there's a 1-based `side_` being used as the index of a 0-based array on line 2222 of unit.cpp:

https://github.com/wesnoth/wesnoth/blob/5ffa031e8e79b0e1e4b1cfb02302030ff6bb02b6/src/units/unit.cpp#L2222

**Comment by ProditorMagnus** [comment] 2022-11-23 07:19
![image](https://user-images.githubusercontent.com/7848963/203490916-49843596-1ea1-4d4d-b6b3-2f1c6065c5e2.png)

**Comment by redone9211** [comment] 2023-01-22 04:36
i am intrested in contributing in this issue, can you let me know how i can solve this issue.

**Comment by CelticMinstrel** [comment] 2023-01-22 04:47
Should be relatively easy, just add a range check, probably in `intf_add_modification`, and raise a proper Lua error that correctly describes the issue.

**Comment by stevecotton** [comment] 2023-01-22 04:59
@CelticMinstrel the bug here is that `[effect]apply_to="recall_cost"` is triggering that error, not the range check itself.

**Comment by redone9211** [comment] 2023-01-22 06:02
if possible can this issue be assigned to me, then we can figure out how exactly it can be resolved.

**Comment by CelticMinstrel** [comment] 2023-01-22 06:28
I suppose you could say there are multiple bugs, but an internal C++ error should not be exposed to Lua. Even if `[effect]apply_to="recall_cost"` throws an exception, it should be turned into something readable as a Lua error.

**Comment by stevecotton** [comment] 2023-01-22 06:30
@redone9211 welcome to the project. Here's an outline of how I'd do it, but I tend to add more tests than other developers, so this approach might not be the that best suits you.

It involves WML changing recall costs, so I'd start by seeing if we have any existing automated tests that check recall cost:
```
$ git grep -i recall.cost data/test/
data/test/scenarios/manual_tests/scenario-test.cfg:        recall_cost=42
```
The basic answer is that we don't have such a test. `manual_tests/scenario-test.cfg` is a big scenario that has lots of odd situations, but it's not a good starting point.

We do have a lot of automated tests that are doing something involving recalling units, and a couple of them are also using `[modify_unit]`. Looks like these would be a good starting point:
* `put_to_recall_and_modify` in data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/put_to_recall_and_modify.cfg
* `modify_unit_which_recall_list` in data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/test_modify_unit.cfg

Before writing a new test, work out how to run the existing tests. I've just realised that https://wiki.wesnoth.org/SoftwareTesting is in need of updating.

The line below will run non-interactive tests. `--no-log-to-file` is being discussed in #7310, and `--log-strict=warning` is needed for tests that should fail if an error message such as this `_M_range_check` is displayed. For this error, the test might just get stuck and need to be exited with ctrl+C.
```
wesnoth --no-log-to-file --nobanner --noaddons --log-strict=warning -u put_to_recall_and_modify -u modify_unit_which_recall_list
```

You can also run tests that are already listed in `wml_test_schedule` with `run_wml_tests`.  The `--filter recall` is expected to find 4 tests to run. Depending on which directory you build the Wesnoth executable in, you may need the `-p` option too.
```
run_wml_tests --clean --verbose --batch-disable --filter 'recall'
```

So I'd start off with writing a new test based on the existing tests, doing a `[modify_unit][effect]apply_to="recall_cost"` and failing the test if it generates an error. Then add in an assert that the unit's recall cost actually changed.

If I guessed correctly about the source of the error in https://github.com/wesnoth/wesnoth/issues/7159#issuecomment-1324419153 , changing the `side_` to `side_ - 1` would be the fix, ideally done with a named method that converts between side numbers and team numbers. However, just setting it to constant `0` and then seeing if the unit test runs without a warning would either confirm or rule out that line as being the bug.

It would be good to actually recall the unit in the test and check how much gold that costs, but https://wiki.wesnoth.org/DirectActionsWML#.5Brecall.5D doesn't seem to have an option for it. I thought there was a recall that did deduct gold, would have a look for it.

**Comment by CelticMinstrel** [comment] 2023-01-22 06:59
> It would be good to actually recall the unit in the test and check how much gold that costs, but https://wiki.wesnoth.org/DirectActionsWML#.5Brecall.5D doesn't seem to have an option for it. I thought there was a recall that did deduct gold, would have a look for it.

Aren't you looking for `[do_command]`?

**Comment by stevecotton** [comment] 2023-01-23 04:53
> I suppose you could say there are multiple bugs, but an internal C++ error should not be exposed to Lua. Even if `[effect]apply_to="recall_cost"` throws an exception, it should be turned into something readable as a Lua error.

Why would that be useful for this bug report? If the root cause is what I think it is, this is a simple off-by-one in C++; it will never throw an exception once fixed.

> Aren't you looking for `[do_command]`?

Thanks, yes `[do_command][recall]` should affect the player's gode.

**Comment by Muhammedsinanck** [comment] 2023-02-08 18:45
i am new open source, is this issue assigned to anybody. Please assign to me.

**Comment by stevecotton** [comment] 2023-02-09 05:05
Welcome to the project.

**Comment by Muhammedsinanck** [comment] 2023-02-09 07:20
I am new to open source , do you have any resources for this project ? what should i do first ?

**Comment by stevecotton** [comment] 2023-02-09 09:29
Without knowing more about what experience you have, I can't say where to look next; however, it might not be the right "first issue" for your current experience.

While this is labelled "good first issue", it's labelled that assuming that you're familiar with the game, have probably already created add-ons (a.k.a. mods) for it, and are looking for a good starting point to move from there to working on the engine itself. For working on this issue, you should already know both C++ and WML, and know what other stuff goes around the WML code snippet in the "steps to reproduce" in order to investigate what the engine is doing in a C++ debugger.

**Comment by Muhammedsinanck** [comment] 2023-02-09 13:35
I knew c++ , and but don't know WML . So can i learn it and contribute to this?. I didn't play  this game before  will look into it.

**Comment by Pentarctagon** [comment] 2023-02-13 03:16
It's certainly possible for you to learn it - WML is meant to be fairly easy to pick up.

**Comment by stevecotton** [comment] 2023-04-21 11:32
Fixed in #7549.

**Closed by stevecotton** 2023-04-21 11:32 UTC
Labels: Bug, WML, Good first issue

**Comment by gfgtdf** [comment] 2023-04-21 11:36
Should this be backported to 1.16?

**Comment by stevecotton** [comment] 2023-04-21 13:44
I'm against backporting it. In the circumstance where it shows an error message, it would cause OOS if used in a game with an old client, so I think it's better to leaving it consistently showing an error message on all client 1.16.x versions. It already works on 1.16.x in the case that:
* there's another side (possibly an AI side) with a higher number than the side whose unit is being modified, and
* that side has the same default recall cost as the current side.
