### ISSUE TITLE
1.14.5 UI bug with spectators eye

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#3701] opened 2018-11-10 19:01 UTC
Wesnoth v1.14.5 (MP at Official server)
Windows 7 x64 **with 125% system fonts**.

Window mode with resolution 1920x999 (as Wesnoth reported).

See attached image: bug with spectators eye in UI.

![bad_eye](https://user-images.githubusercontent.com/10855248/48304977-1ea52680-e534-11e8-9107-68f15cf1abad.png)

**Comment by jostephd** [comment] 2018-11-10 23:52
Duplicate of #3543. The fix will be in 1.14.6.

**Closed by jostephd** 2018-11-10 23:52 UTC
