### ISSUE TITLE
Window incorrectly resized when dismissing units

### ISSUE THREAD

**Issue by GuidoBartoli** [wesnoth/wesnoth#4877] opened 2020-04-27 12:22 UTC
### Game and System Information
Wesnoth 1.4.11 installed with flatpak on Linux Mint 19.3

### Describe the bug
When the recall dialog appear, if you have some units and start to dismiss them, when you dismiss the second to last one, the window is resized and the old one is kept in the background. The result are two super imposed windows with double borders caused by the different sizes. When the last unit is dismissed or the dialog closed, both windows disappear.

### To Reproduce

1. Load a game with some units available for recall
2. Open the recall dialog with ALT+R or with right click
3. Begin dismissing units until you remain with two units
4. Dismiss the one with the longest name
5. The window is redrawn smaller on top of the old one

### Expected behavior
The window should resize while the old one should disappear.

### Screenshots
Before:
![before](https://user-images.githubusercontent.com/16103676/80371541-5e7bdd00-8892-11ea-99ad-9efcab6bec9d.jpg)

After:
![after](https://user-images.githubusercontent.com/16103676/80371561-663b8180-8892-11ea-8388-2dd11f086cc3.jpg)

**Comment by AI0867** [comment] 2020-04-28 13:24
Looks like the window shrinks because `resilient` is shorter than `intelligent`, so less space is needed, but the map isn't redrawn after the window decides to shrink.

**Comment by gfgtdf** [comment] 2020-04-28 13:33
It's be better if the dialog  wouldn't resize at all here though.

**Comment by GuidoBartoli** [comment] 2020-04-28 13:40
Actually, it looks like a new smaller window is drawn on top of the previous one, so you see the border of the larger one underneath. It should simply use only one window and resize it if needed.

**Comment by Pentarctagon** [comment] 2020-05-10 21:44
Is there a way to tell a dialog to never resize itself?

**Comment by Pentarctagon** [comment] 2020-05-12 21:16
[An example save file](https://github.com/wesnoth/wesnoth/files/4618481/AToTB-The.Chase-Auto-Save1.gz):
* Dismiss Hann
* Dismiss Faren
* Dismiss Efran
* Dismiss Meowoc - the dialog now shows up as ![this](https://user-images.githubusercontent.com/3030250/81746342-edc8e900-946b-11ea-8161-e14871abaec2.png).

**Comment by gfgtdf** [comment] 2020-05-12 22:39
> Is there a way to tell a dialog to never resize itself?

I am not sure, to understand that one would first need to check why it rebuilds itself in the first place (in particular whether someone calls invalidate_layout or whtger maybe the Window is even fully recreated).

My main point is that even withy this bug changing dialogs size like this is a bad I. Particular if it results in the position of buttons changing like in your picture.


This particular case might be even more complex since dismissing a unit is a synced gamestate changing action and we might want to add a wml event (name="dismiss") at some point (afaik the only reason why we don't have that is the the wml event engine cannot really handle recall units as parameters) to let umc react on units vanishing this way. And I'm not sure whether having a dialog open during even proceccing would work.

**Comment by stevecotton** [comment] 2021-02-19 16:08
See also #3942 and parts of #5544.

**Comment by Wedge009** [comment] 2021-09-15 13:23
#4695 also seems to be a product of variable dialogue dimensions, although I can't recall if it has the same (lack of) redraw problem.

**Comment by mesilliac** [comment] 2022-07-14 01:57
I can't reproduce the changing of dimensions, but this should be fixed by #6855 even if the dialog size changes. Can anyone confirm?

**Comment by Wedge009** [comment] 2022-07-14 02:11
Confirming it was already resolved in 1.16.5 release, if not earlier.

**Closed** 2022-07-14 02:13 UTC
Labels: Bug, UI, Low Priority
