### ISSUE TITLE
[BUG] [Gamestate Inspector] Viewing Unit Data in Inspector UI shows Nothing

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7565] opened 2023-04-23 16:02 UTC
### Screenshot
![image](https://user-images.githubusercontent.com/5283677/233850584-7c1e4a35-a53c-41c4-9feb-3bc12aa9d816.png)

### Expected Behaviour
I see the unit data code

### Observed Case
This was HttT for me. Might be anything.

### Version Data
1. Wesnoth 1.17.16+dev (latest)
2. Github Download
3. Windows 10 (msys2)

### Extra Info
the vertical scroll is there, indicating the code is there...just not visible.

**Comment by Toranks** [comment] 2023-04-23 16:12
That already happened before, since we reported issues #7093  and #6879 , and it is related. It happens in several more sections (literally anywhere there is text and scrollbar), and depends on the length of the text the screen are trying to display.

**Comment by knyghtmare** [comment] 2023-04-23 16:13
> That already happened before, since we reported issues #7093 and #6879 , and it is related. It happens in several more sections (literally anywhere there is text and scrollbar), and depends on the length of the text the screen are trying to display.

In those cases, there was actually text...here I see an empty box (nothing)...I mean... really nice way to tell me everything degraded to something worse...

**Comment by Toranks** [comment] 2023-04-23 16:27
Yes, but I want to tell you that this bug that you mention already existed since I observed this type of bug. It is not something new.

**Comment by Wedge009** [comment] 2023-04-28 09:40
I'm pretty sure this is related to to the already-mentioned #7093. I notice whether or not something shows at all before scrolling seems to be dependent on the length of the text being shown (or rather, not being shown, in this case).

I agree that this is another duplicate report - some seem to be keen on filling GitHub with them. I also disagree that it's a Blocker. It's serious, yes, but not likely to be something an average player would run into - at least for the inspection, it's more likely they'd encounter the issue in the Add-Ons menu (#6879).

It should at least warrant a Windows label, if not be closed altogether in favour of the older reports.

**Comment by knyghtmare** [comment] 2023-04-28 15:30
Instead suggesting closing issues, why not actually fix it? :)

**Comment by CelticMinstrel** [comment] 2023-04-28 23:27
I don't think it warrants a Windows label, as I'm pretty sure I recall seeing this on MacOS as well.

I also thing it should be a blocker, because it's a fairly low-level thing that could affect almost anything. We know it affects the inspector and the credits. There's a similar issue in the add-ons manager too, though I'm not sure if that's the same thing.

However, this is a duplicate, yes. So we could close it as such.

**Comment by Wedge009** [comment] 2023-04-29 02:42
I have no experience on macOS, but I only encounter this in Windows. I've never seen it under Linux. What could allow Linux executables to render normally but not Windows and macOS?

It does seem like the inspect and add-on dialogues exhibit the same symptom, but for the moment we have them covered separately in the aforementioned issues #7093 and #6879. For that reason - and not because I just feel like closing issues for the sake of it - I'd prefer this one to be closed. If you think it should be marked as a blocker, I suggest adding the label to those issues.

**Comment by gfgtdf** [comment] 2023-04-29 02:45
I think i have also seen this under Linux

**Comment by CelticMinstrel** [comment] 2023-04-29 03:57
> What could allow Linux executables to render normally but not Windows and macOS?

Is there a possibility that your Windows machine uses a high-dpi monitor but your Linux machine uses an older 2k monitor? Or, you have mesilliac's scaling enabled on one machine but disabled on the other? My understanding of the issue is that it shouldn't occur if dpi-aware scaling is fully disabled. I haven't taken the time to verify that, though.

**Comment by Wedge009** [comment] 2023-04-29 04:02
I only have regular DPI and I disable all scaling. Windows machines run on 1920x1080 and 3840x2160, with Linux machine in between at 2560x1440. If you read #6879, mesilliac, doofus, Toranks, and myself - testing in Linux - could not replicate the issue.

As I highlighted in #7093, the regression was in between 1.17.5 and 1.17.6, which seems to coincide with mesilliac's work. So it doesn't appear to be a matter of a 'quick fix'.

**Comment by Toranks** [comment] 2023-04-29 09:24
> I also thing it should be a blocker, because it's a fairly low-level thing that could affect almost anything. We know it affects the inspector and the credits. There's a similar issue in the add-ons manager too, though I'm not sure if that's the same thing.
> 

As I've said several times on discord and in other issues, this is not a problem specific to certain sections, it affects EVERYTHING that has a large amount of text, and a scrollbar. Absolutely everything, at least in windows 7.

**Comment by CelticMinstrel** [comment] 2023-04-29 12:38
Does that mean you've seen it for example in the game description in Multiplayer Create?

**Comment by Toranks** [comment] 2023-04-29 12:59
I don't have any maps with a long enough description, but I've edited one of my own so that it does and it works fine on that screen. First place I've seen it works!

**Comment by CelticMinstrel** [comment] 2023-04-29 13:02
That's text that failed in another place? Is it possible it just wasn't long enough?

Anyway, that's beside the point which is that yes, this is a low-level fundamental problem that affects places we might not even think of. Even if that weren't the case, the gamestate inspect is actually a very important place. Just because we don't expect regular players to use it doesn't mean we should neglect it.

**Comment by sevu** [comment] 2023-06-02 18:24
This is printed to the log in the case of the inspector:
`20230602 20:13:10 error SDL: When creating texture from surface: Texture dimensions are limited to 16384x16384`

**Comment by Wedge009** [comment] 2023-06-03 01:56
That seems related to #7201. I couldn't trip that error when replicating this (still only in Windows) in current master.

**Comment by sevu** [comment] 2023-06-03 12:08
I do not have this  issue with the `units` section in the inspector.

It happens when I select in the inspector a menu item which has several pages of code, such as from ANL.
On 1920x1080 I get the error in the log, and an empty right side of the inspector with scrollbar.
The non-displaying menu items seem to have in common, that they have at the bottom of the screen, next to the button for the Lua console, a page counter.

With effectively 960x540 when using the x2 scaling, the program terminates instead:
```
20230603 13:49:18 warning draw/manager: exception std::length_error thrown during expose 0x7fff52eb2460
Caught general 'St12length_error' exception:
Text is too long to render
```

**Comment by Wedge009** [comment] 2023-06-03 22:53
> With effectively 960x540 when using the x2 scaling, the program terminates instead:

Again, isn't that the same result as #7201?

**Comment by sevu** [comment] 2023-06-03 23:04
Yes

**Comment by stevecotton** [comment] 2023-07-27 14:49
> I only have regular DPI and I disable all scaling. Windows machines run on 1920x1080 and 3840x2160, with Linux machine in between at 2560x1440. If you read #6879, mesilliac, doofus, Toranks, and myself - testing in Linux - could not replicate the issue. That is, at least for me, the symptom seems pretty consistent on Windows, irrespective of window size.

That's worrying, because I'm sure that I also tested on Linux back then. However, I'm now seeing it in a build that's current master (752e8788f5d19b1e79668bfc7c111d15ff4792cf) plus local changes unrelated to graphics.

**Closed** 2023-11-08 15:50 UTC
Labels: Bug, Blocker: New Stable, UI, Regression
