### ISSUE TITLE
Usability problemfor map/scenario editor (GNA #23335)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1455] opened 2017-05-08 09:46 UTC
**[Original submission](https://gna.org/bugs/index.php?23335)** by dret on 2015-02-28

Hi to all,

I would like to suggest an usability improvement for map/scenario editor.

In the new version there are some functions that appear normally to be  not active. But there's no informations about the way to activate them.

Cloud be useful to have a tooltip (above the icons) that explain better how to activate them.

Thanks!

Bye

(Reproduced on all)
Release: 1.12.x
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment] 2017-05-08 09:46
**Modified on 2015-02-28**

**dret wrote:**

> For example: for the Button "Side" could be usefull to have a tooltip that explain "To add new sides, please create a new scenario first. This option is located in "file" menu".

**Comment by wesnoth-bugs** [comment] 2017-05-08 09:46
**Modified on 2015-02-28**

**elvish_hunter wrote:**

> Since this is a feature request, I'm changing its severity to 1 - Wish.

**elvish_hunter changed severity:** 3 - Normal -> 1 - Wish

**Comment by stevecotton** [comment] 2020-08-18 14:14
Closing as a duplicate of #5070.

**Closed by stevecotton** 2020-08-18 14:14 UTC
Labels: Editor, Enhancement
