### ISSUE TITLE
Host Networked Game 

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3159] opened 2018-05-23 15:39 UTC
![game](https://user-images.githubusercontent.com/39015360/40435084-2ac1852c-5eb0-11e8-89af-f56afc4ceaa4.png)
There is obviously some text missing.

**Comment by sevu** [comment] 2018-05-23 15:57
The string is complete in the files - it's the UI which lacks space to display it.

**Comment by ProditorMagnus** [comment] 2018-06-01 23:29
The message is also misleading - server will keep running even after all users have left. It needs to be killed by system.

Additionally, windows at least starts another wesnothd if one was already running. I expect this would not happen with linux since port would already be in use.

**Comment by loonycyborg** [comment] 2018-06-02 08:36
The server is started with some flags that make it automatically stop when here are no players on it, but with a significant delay after this condition is true.

**Comment by soliton-** [comment] 2018-06-03 13:47
If the wesnothd instance started from wesnoth is not closing after all clients left (with some grace period) then that is a bug.

If windows can run several processes that listen on the same port that is a bug in windows since that makes no sense.

**Comment by loonycyborg** [comment] 2018-06-04 14:50
Autoshutown was indeed unimplemented. Fixed here: https://github.com/wesnoth/wesnoth/commit/4eea1b5f0d4a0de9155c23be8a5abe097cf23f09

**Comment by jostephd** [comment] 2019-05-13 11:21
Closing as a duplicate of #3443 (which was filed later, but discussion there is more relevant).

**Closed by jostephd** 2019-05-13 11:21 UTC
Labels: Bug, Confirmed, UI
