### ISSUE TITLE
Loading a local multiplayer game always results in side 1 running the turn

### ISSUE THREAD

**Issue by wuxiangjinxing** [wesnoth/wesnoth#7664] opened 2023-05-26 22:31 UTC
### Game and System Information

- **Version:** = 1.17.16
- **Downloaded from:** = wesnoth.org
- **Build info:**
- **OS:** = win11

### Description of the bug

When loading a save from a local mutliplayer game, no matter which side is running the turn when saving the game, after loading it will always be side 1 to run the turn.

### Steps to reproduce the behavior

1. Start a local multiplayer game (i.e. WCII)
2. Let side 1 finish its turn
3. Save the game when other sides are running the turn
4. Load the save, and you will see the turn is switched to side 1.

**Comment by gfgtdf** [comment] 2023-05-26 22:49
hmm i think we fixed this on in 1.17.17 already (which is already tagged)

**Comment by gfgtdf** [comment] 2023-05-26 22:53
Does it match  https://github.com/wesnoth/wesnoth/issues/7564 ?

At least the way to reproduce it seems to be the same so it would be strange if we didn't see this one.

**Comment by wuxiangjinxing** [comment] 2023-05-26 23:07
> hmm i think we fixed this on in 1.17.17 already (which is already tagged)



> Does it match #7564 ?
> 
> At least the way to reproduce it seems to be the same so it would be strange if we didn't see this one.

Yes I think these are the same issue.  Good to know it is fixed. (Is 1.17.17 released?)

**Comment by gfgtdf** [comment] 2023-05-27 00:29
> Yes I think these are the same issue. Good to know it is fixed. (Is 1.17.17 released?)

Hmm afaik yes but it was tagged nearly a week ago iirc, so it shouldn't take long

**Comment by Toranks** [comment] 2023-05-27 02:30
It was released a week ago

**Comment by knyghtmare** [comment] 2023-05-27 05:54
> It was released a week ago

For Windows. MacOS people still waiting.

**Comment by gfgtdf** [comment] 2023-05-30 12:04
Since this seems to be a dublicate of a  closed bug i'm closing  this, Feel free to comment if it still happens with 1.17.17 which is now officially  released.

**Closed by gfgtdf** 2023-05-30 12:04 UTC
Labels: Bug, Duplicate, MP
