### ISSUE TITLE
Backstab special causes WFL error with wesnoth.simulate_combat in AI context

### ISSUE THREAD

**Issue by mattsc** [wesnoth/wesnoth#2247] opened 2017-11-27 13:48 UTC
When a Lua AI uses wesnoth.simulate_combat with an attacker that has the backstab special, this causes the following error:
```
ERROR: TYPE ERROR: expected string but found null (null())
  enemy_of
  unit_at
  direction_from
formula type error: TYPE ERROR: expected string but found null (null())
```
This almost certainly also means that the backstab special is no evaluated correctly.  The problem does not happen if wesnoth.simulate_combat is called during the player's turn.

The error originates in https://github.com/wesnoth/wesnoth/blob/master/data/core/macros/abilities.cfg#L293 and according to an irc chat with @CelticMinstrel yesterday, the reason is that `other` in the equation is null in this context.

To reproduce, I have attached a save from a slightly modified version of the Fast Micro AI test scenario which uses only Thieves.  Just load, type `:droid` and stderr will be flooded with error messages of that type.

[Fast_Turn_1_backstab_bug.gz](https://github.com/wesnoth/wesnoth/files/1505999/Fast_Turn_1_backstab_bug.gz)

**Comment by gfgtdf** [comment] 2017-12-02 12:08
Note that this in a `[filter_opponent]`, so `other` is actually the attacker. I think the issue is that the attack is not on the map, i know the wiki says 

>  The first unit is the attacker; it does not have to be on the map

but from looking at the code this is wrong, it does store the attacks location (`attack::set_specials_context`) at some point and then tried to recover the unit from it. Note that the old backstab implementation did not use use the units attributes (facing) and worked purely with locations.

**Comment by mattsc** [comment] 2017-12-02 14:33
In the test case above, the AI does indeed work with a unit copy at different coordinates than where the actual unit is.  The same is true for the situation in which I originally found the problem, so that explanation makes sense.

As you (and the wiki) say, this used to work and would be a serious issue for some AIs if it is not be reinstated.  It's not that you cannot work around it by temporary placing the unit in the future attack location, but that procedure is slow.  The whole point of, for example, the "Fast Micro AI" is to be, well, fast when there are lots of units on the map.

**Comment by CelticMinstrel** [comment] 2017-12-02 16:19
Ideally the fix would be to not try to recover the unit from the location. I haven't looked at the code, does that seem viable @gfgtdf?

**Comment by gfgtdf** [comment] 2017-12-02 17:17
hmm not sure, i mean the obvious attempt would be just replacing that map_location& with a unit_ptr or unit*. The reason that it currently uses map_location is probably that the unit might be deleted/recreated by wml (note that the default wml way to change units stats is deleting+recreating of the unit object). So one would need to check how long these references are actually used/how often they are updates, in particular in the attack (not the attack prediction) code.

**Comment by CelticMinstrel** [comment] 2017-12-02 17:44
I think you'd need both the location and the unit here.

**Comment by gfgtdf** [comment] 2017-12-02 18:09
hmm no ,in this case the unit is just not on the map, (it migth be a 'private' lua unit) in which case unit.x and unit.y do contains the location from whihc we want to know 'how woudl the battle go if the unit were there' but unitmap.find(unit.loc()) would not give us the unti back

**Comment by CelticMinstrel** [comment] 2017-12-03 02:20
But I think it does also need to work if the unit is on the map but the location differs from the unit location. Does that work now (I'm guessing it does), and would it work with your proposed change?

**Comment by gfgtdf** [comment] 2017-12-03 03:43
Well this case of a unit that is on a map but ona  different location is somehow covered by the private lua unit case above, just copy the unit to a private lua unit and change the cooridnates of that copy. (this is in fact what the ai code in quetion does iirc).

The only thing that could go wrong with that is, that the the original unit is still on the map too, so for example if you move the unit by one hex with that technique and that unit has a filter like 'if an allied unit is adjacent' that filter would always return true since the copy woudl be adjacent to the original unit.


> It's not that you cannot work around it by temporary placing the unit in the future attack location, but that procedure is slow

I'm suprised to her that this is slow, in fact creating a private copy will usually copy the whole unit which i would expect be slower than just moving it around.

**Comment by mattsc** [comment] 2017-12-03 03:52
> I'm suprised to her that this is slow, in fact creating a private copy will usually copy the whole unit which i would expect be slower than just moving it around.

Well, it might not be slower if you do it once (I don't remember), but if you are testing out a lot of combinations of a small number of units, you only need to copy each of them once, and then simply change the coordinates of the private units.  I forgot the details, but I did the tests and that turned out to be way faster than anything else (at least anything I could come up with).  And, in fact, I need to make a copy of each unit at the beginning of the turn/move for other reasons anyway, so there's no overhead involved with that at all.

**Comment by CelticMinstrel** [comment] 2017-12-03 06:31
The ability to pretend the unit is somewhere other than its true location is built into the unit filter system, so there's no need to actually move the unit on the map for hypothetical tests, nor even to extract it and adjust its internal location. I'm not sure if it accounts for the possibility @gfgtdf mentions with adjacency filters, though; that might be something to double-check.

In any case, whether you use the built-in unit filter feature or some other workaround (which used to be necessary in Lua since the location faking wasn't exposed), it should work the same. Basically, all three methods (location faking, extracting, actually moving) need to give the same result.

This likely isn't directly relevant to the issue here, though, because you're not getting this error from `wesnoth.get_units`. Since it's something internal to `wesnoth.simulate_combat` and clearly has something to do with attack specials, the first place to look is probably the ability system, which is in units/abilities.?pp, or since it's weapon specials, possibly units/attacks.?pp. It's been awhile since I looked, but there should be functions testing if the ability is active, which then invoke unit filters and presumably produce this bug in the backstab case. Without looking, I'd guess the problem is either 1) the functions don't take a fake location (somewhat unlikely though?), or 2) the fake location is never passed in by `intf_simulate_combat` or otherwise gets "lost" somewhere in between.

**Comment by Vultraz** [comment] 2018-02-07 07:16
We really should get this fixed.

**Closed** 2018-03-05 05:10 UTC
Labels: Bug, Regression, WFL
