### ISSUE TITLE
Visual problems with halos on edge (GNA #21336)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1350] opened 2017-05-08 07:49 UTC
**[Original submission](https://gna.org/bugs/index.php?21336)** by beetlenaut on 2013-12-08

A halo that extends into the border of the map leaves copies of itself behind as you scroll the map. Part of the normal halo also detaches if you use the keys instead of the mouse scroll wheel.

(Reproduced on Linux)
Release: 1.11.7+dev
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:49
**Modified on 2013-12-08**

**beetlenaut added attachment:** [halo problem.jpg](http://gna.org/bugs/download.php?file_id=19433)

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:49
**Modified on 2013-12-19**

**shadowmaster wrote:**

> I can't reproduce this with halo/lighthouse-aura.png on y=1 in the test scenario. Do you have your own test case in WML you could attach?

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:49
**Modified on 2013-12-19**

**beetlenaut wrote:**

> I just discovered something: It only happens when Wesnoth is maximized. Did you try it that way?
> 
> 
> 
> I didn't bother making a test scenario because it seemed so easy to reproduce. Just stick a MOL on the edge of a map and scroll with the mouse wheel. (That's more reliable than the keyboard.)

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:49
**Modified on 2013-12-19**

**shadowmaster wrote:**

> I still can't reproduce it with the Mage of Light on the right edge, no matter the window resolution or whether it's fullscreen or not.
> 
> 
> 
> Perhaps mention whether you have map and unit standing animations enabled or not, the build architecture, operating system ("Linux" doesn't really say much) and window manager?

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:49
**Modified on 2013-12-19**

**beetlenaut wrote:**

> distro: openSUSE 13.1 (latest)
> 
> architecture: x86_64
> 
> desktop: Plasma (KDE)
> 
> window manager: KWin (default)
> 
> resolution: 2560x1440
> 
> animations: everything except haloing effects turned off in display settings
> 
> 
> 
> I had animations turned on, but they're off now, and I still see the same effect. I also tried turning off desktop compositing, but that didn't help either.

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:49
**Modified on 2014-01-21**

**ai0867 wrote:**

> I just reproduced this, but haven't found a way to do so reliably yet.

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:49
**Modified on 2016-08-29**

**wedge009 wrote:**

> Is this still an issue in 1.13? I don't think I've ever been able to replicate this problem.

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:49
**Modified on 2016-08-29**

**beetlenaut added attachment:** [halo problem 2.jpg](http://gna.org/bugs/download.php?file_id=28540)

**beetlenaut wrote:**

> Yes, this still happens on 1.13.5. I can't help you with reproducing it because it *always* happens on my machine. The window size doesn't matter. I tried a small window, a large window, maximized, and full screen mode. It doesn't matter how I scroll either: arrow keys, mouse wheel, center button. I uploaded a new image that shows more of the behavior. Maybe it will help.
> 
> (file #28540)

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:49
**Modified on 2016-08-30**

**wedge009 wrote:**

> Okay, I managed to replicate it pretty reliably. For me, it was a matter of making the window wider than the game map (the mage was on the left edge) and then scrolling the map up and down. Just as you had in the image in your last comment.
> 
> 
> 
> I have a feeling the transparency of the halo stretching beyond the game map edge has some bad interaction with the background.

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:49
**Modified on 2016-08-30**

**beetlenaut wrote:**

> Ah, I see. It *does* only happen when the window is larger than the game map. I guess the reason I could always reproduce it is just that my monitor was wider than all the maps I had tried it on.

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:49
**Modified on 2017-03-20**

**wedge009 changed status:** None -> Confirmed

**wedge009 wrote:**

> Reconfirming for 1.13.7+dev.

**Comment by Vultraz** [comment] 2017-06-27 10:30
Fixed on accelerated_rendering.

**Comment by Wedge009** [comment] 2017-07-01 03:28
Confirming resolved in AR branch.

**Comment by CelticMinstrel** [comment] 2018-10-14 18:19
Should this be reopened?

**Comment by Wedge009** [comment] 2018-10-15 05:02
Re-confirmed on 1.14 - was AR branch ever merged?

I think my master is broken because of add-ons or some other configuration producing errors.

**Comment by CelticMinstrel** [comment] 2018-10-16 02:53
AR was merged and then unmerged. That's why I asked if it should be reopened.

Did you force-reset your master branch to origin?

**Comment by Wedge009** [comment] 2018-10-16 12:16
That was before I knew about and fetched the big master switch, which josephd informed me about in another issue. I just rebuilt everything from scratch (purged all previously compiled objects) and find that this is still an issue on both master and 1.14.

**Comment by Wedge009** [comment] 2022-07-13 02:49
Seems to be resolved with #6855.

**Closed by Wedge009** 2022-07-13 02:49 UTC
Labels: Bug, Confirmed, Graphics, Fixed on AR branch
