### ISSUE TITLE
1.18 WC: WoCopredia has ugly double scrollbar

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#8576] opened 2024-03-17 21:56 UTC
As shown in the image, the "wocopedia" custom help dialog of World Conquest has an ugly double scrollbar.
![image](https://github.com/wesnoth/wesnoth/assets/4893136/f9f8d85b-ee40-4d01-86a2-c0e80d302b83)

**Comment by gfgtdf** [comment] 2024-03-17 21:58
I suspect this happened since the addition of the 3 new factions making the left side treeview  larger

It should have a scrollbar near the left treeview instead of the the whole dialog.-

**Comment by Wedge009** [comment] 2024-03-17 22:39
I don't know about gui2 layouts but wonder if it's a matter of changing how the scrolling areas are structured. ie Have the two panels - left-side tree view and main panel - as separate sections instead of one nested within the other.

**Comment by babaissarkar** [comment] 2024-03-20 06:23
This might be related :
```
[tree_view]
id = "treeview_topics"
    definition = "default"
    horizontal_scrollbar_mode = "never"
    vertical_scrollbar_mode = "never"
    indentation_step_size = 35
```

**Comment by babaissarkar** [comment] 2024-03-20 06:36
@gfgtdf How do I get all of the factions and everything else to show in the left treeview, like your screenshot? (I've none of them, it seems)
Steps to reproduce the bug would be good.

**Comment by gfgtdf** [comment] 2024-03-20 15:13
I think they are there by default. Maybe you forgot to select the WC2 era when starting the game? (Of course it won't show the wc2 factions when you are not plying with the wc2 era.)

**Comment by babaissarkar** [comment] 2024-03-20 16:54
@gfgtdf 
Not choosing WC era was causing it.

Seems like I've found a fix for the double scrollbar, it's being caused by this line :
https://github.com/wesnoth/wesnoth/blob/0331a02720687e67ada34003e961ef8002484d8f/data/campaigns/World_Conquest/gui/help_dialog.cfg#L10
Commenting this out stops the outer scrollbar (which was the top window container's scrollbar). Since it specified a max height, the window had no option but to enforce it's own scrollbar, which was unnecessary because the internal contents have their own scrollbar.

As for the treeview not showing a scrollbar, that was caused by the previous code block I mentioned :
https://github.com/wesnoth/wesnoth/blob/0331a02720687e67ada34003e961ef8002484d8f/data/campaigns/World_Conquest/gui/help_dialog.cfg#L67
Commenting this out reenables the treeview's vertical scrollbar.

Can you please comment out those two line and test around see if there are any related issues?

**Comment by Wedge009** [comment] 2024-03-20 22:45
Nice work. I hadn't played World Conquest before, took me a while to actually find the WC-specific Help. My display has enough vertical resolution that removing the maximum height makes the dialogue the full height of the Wesnoth window and does not have any scroll-bars. But I found that it's sufficient to just remove the 'never' for the vertical scroll-bar mode. It might make a difference in certain translations, but I found no harm in removing the 'never' for the horizontal scroll-bar mode either.

Would you be willing to submit a PR for this change?

**Comment by babaissarkar** [comment] 2024-03-21 03:53
@Wedge009 I've created a PR. Also, I'm setting the scrollbar mode to `auto` (since the default value is `always`, so the scrollbar gets shown even when there's not much content).

**Comment by babaissarkar** [comment] 2024-03-22 13:53
PR #8594 has been merged, so this can be closed.

**Closed** 2024-03-22 13:59 UTC
Labels: Bug, UI, Campaign WC

**Comment by Wedge009** [comment] 2024-03-22 21:42
Thanks for your efforts. FYI, if you use a keyword like resolves/closes/fixes #xxxx in the commit message, GitHub will automatically link the issue to the PR and close it as resolved when the PR is merged.
