### ISSUE TITLE
[DM] [Lua] Lua Error upon victory in DM S19 Showdown at the Northern Swamp

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6172] opened 2021-10-07 08:35 UTC
### Game and System Information
 - 1.15.18
 - Steam
 - Windows 10

### Describe the bug
There is a Lua error message that appears upon victory.

### To Reproduce
Kill Iliah-Malal in DM S19 with Delfador.

### Expected behavior
There should be no error.

### Screenshots
![image](https://user-images.githubusercontent.com/41433185/136348772-4f91a826-fbc4-4a6c-879e-ad6e400d9ab0.png)

### Savefiles
[DM-Showdown in the Northern Swamp-Auto-Save13.gz](https://github.com/wesnoth/wesnoth/files/7300492/DM-Showdown.in.the.Northern.Swamp-Auto-Save13.gz)

### Additional Inquiry
Does this mean something will go wrong if the campaign is continued? Is this an error that makes the continuation of the campaign not play out properly?

**Comment by bc722013** [comment] 2021-10-12 14:33
I ran into the same bug with the non-steam version on my Windows 8 laptop. 
In my case the error message appeared regardless whether I killed Iliah-Malal with Delfador or my undead unit (a Nightgaunt sprinkled with holy water too!).

**Comment by knyghtmare** [comment] 2022-01-12 23:18
[DM-Showdown in the Northern Swamp replay 20220113-051821.gz](https://github.com/wesnoth/wesnoth/files/7858556/DM-Showdown.in.the.Northern.Swamp.replay.20220113-051821.gz)

I think i should close this as this error seems non-existent to me

**Comment by knyghtmare** [comment] 2022-01-12 23:26
> Does this mean something will go wrong if the campaign is continued? Is this an error that makes the continuation of the campaign not play out properly?

I followed the steps to reproduce in my replay but doesn't happen. Maybe it got fixed along the way?

**Comment by Wedge009** [comment] 2022-01-12 23:35
I was only able to get the error with the file attached in the original report. So perhaps it's been resolved in the 1.16 release? I only last played DM in 1.14.17.

**Comment by knyghtmare** [comment] 2022-01-12 23:40
> I was only able to get the error with the file attached in the original report. So perhaps it's been resolved in the 1.16 release? I only last played DM in 1.14.17

Seems like it. Let's wait a day and then close since this error doesn't happen anymore.

**Comment by Descacharrado** [comment] 2022-01-13 09:56
It happened to me too in 1.15.17: https://youtu.be/u38_wMuVg6A?t=4004

**Comment by Wedge009** [comment] 2022-01-14 03:42
Sounds like it's resolved then. Thanks everyone.

**Closed by Wedge009** 2022-01-14 03:42 UTC
Labels: Bug, Confirmed, Campaign, Lua API, Regression
