### ISSUE TITLE
Flathub package can not be installed

### ISSUE THREAD

**Issue by tidux** [wesnoth/wesnoth#5251] opened 2020-10-31 19:31 UTC
```
Unable to install "Battle for Wesnoth":
Can't pull ref app/org.wesnoth.Wesnoth/x86_64/stable from child OCI
registry index: WRiting content object: Truncated tar archive
```

I have confirmed that my system has plenty of disk space and inodes free and my network connection is not dropping, so this appears to be a problem with the published archive.

**Comment by Pentarctagon** [comment] 2020-10-31 20:37
@loonycyborg Any thoughts about this?

**Comment by loonycyborg** [comment] 2020-11-01 23:50
I don't recall having such issues myself. Stable versions are built entirely on flathub.org and they maintain everything there so if it's some server issue it's they who can help with it. Most likely it's some bug in flatpak. Might be deep system issue too, check dmesg.

**Comment by Pentarctagon** [comment] 2020-11-02 06:10
The one other case I can find of this error (at least through google) is https://github.com/flatpak/flatpak/issues/3708 which there hasn't been any response to so far.

**Comment by grz0** [comment] 2021-02-04 17:53
I checked on Fedora 33 (flatpak-1.10.1-1.fc33.x86_64), and I could not reproduce this issue. I checked installation from fedora and from flathub.

**Comment by Pentarctagon** [comment] 2021-02-04 19:10
Closing then.

**Closed by Pentarctagon** 2021-02-04 19:10 UTC
Labels: Question, Upstream issue
