### ISSUE TITLE
Unit movement animation shadow artifact in southern hex /Tweak running animation facing (GNA #20195)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1319] opened 2017-05-08 07:14 UTC
**[Original submission](https://gna.org/bugs/index.php?20195)** by sleepwalker on 2012-09-23

I posted this in my animation dev thread.

There's a bug during movement between hexes where you for a moment see a dark spot on the hexes south of what the unit is moving on. This is an observation with the dwarf fighter when it is moving NE and NW. It might not be exclusive for the dwarf fighter but I have not tested other units... The artifact is tinted purple so I bet it is caused by the units shadow when it spills over into the southern hex it passes by.

Secondly I have a suggestion for running animations: Right now a units facing always defaults to the right when running either north or south... I'd like the unit to keep the facing it previously had before starting moving north or south.

For example: Imagine the unit will run 2 hexes SW, then 2 hexes S, then 2 hexes SW again to reach the hex of destination. As it is now the unit faces left, right and then left again which looks off to me.

(Reproduced on Windows 7)
Release: 1.10.3
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:14
**Modified on 2012-09-23**

**sleepwalker added attachment:** [bug.png](http://gna.org/bugs/download.php?file_id=16602)

**Comment by Pentarctagon** [comment] 2021-08-21 20:58
Closing given its age and that I can't reproduce this anymore.

**Closed by Pentarctagon** 2021-08-21 20:58 UTC
Labels: Bug, Graphics
