### ISSUE TITLE
Units no longer stand on keep while zoomed in/out

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#5974] opened 2021-07-22 21:58 UTC
### Game and System Information
 - 1.15.15
 - Steam
 - Windows

### Describe the bug
Units no longer stand on keep while zoomed in.

### To Reproduce
1. Put unit on keep.
2. Zoom in.

### Expected behavior
Unit stands on keep while zoomed in.

### Screenshots
![wows](https://user-images.githubusercontent.com/41817546/126714504-9187caa3-23ee-4889-bd16-2ed79ba44a7c.JPG)

### Additional context
https://user-images.githubusercontent.com/41817546/126714652-b9d532a2-75e8-40af-8a90-be03ef528a2f.mp4

**Comment by cooljeanius** [comment] 2021-08-17 23:32
Note that this applies to bridges, too

**Comment by Wedge009** [comment] 2021-09-08 13:21
Confirmed, and noting it happens in 1.14.17 release as well.

> Note that this applies to bridges, too

I assume you mean units standing on bridges? Wonder what's specific about these particular tiles, since I don't observe the issue elsewhere. Not that I use zoom normally.

**Comment by AI0867** [comment] 2021-09-09 10:59
Sounds like `[terrain]unit_height_adjust` is incorrectly scaled by zoom.

**Comment by Wedge009** [comment] 2021-09-09 11:24
I honestly don't know what `unit_height_adjust` is supposed to do, but in `data/core/terrain.cfg` I notice that most values for it are 0 or 3, but notably many bridge and keep tiles have values of 17, 20, or 22. Don't know if that's significant, though - Blame view shows that many of those values have been that way for 10/11 years or so. Perhaps something changed between 1.14 and 1.15 that affects the way this value is used?

@doofus-01 Wondering if any of this makes sense to you, perhaps you can assist since you've done a lot of the recent commits on this file, plus seem to have expertise in graphics in general.

**Comment by AI0867** [comment] 2021-09-09 19:57
If it happens in 1.14.17 as well, it's not something that changed between 1.14 and 1.15.

**Comment by Wedge009** [comment] 2021-09-09 21:43
Sorry, I thought I confirmed that it _wasn't_ in 1.14.

**Comment by cooljeanius** [comment] 2021-09-10 00:11
I saw it happen in 1.14

**Comment by Wedge009** [comment] 2021-09-10 00:14
Clarifying: yes it's in 1.14 as well. I just had a momentary lapse of memory when I suggested that something might have changed in between 1.14 and 1.15 to cause this.

**Comment by doofus-01** [comment] 2021-09-11 11:32
There was a similar problem for all animations with offsets, fixed in #5548 
I don't know if it's related, but it seems like it could be.

**Comment by Wedge009** [comment] 2021-09-11 13:49
I'm experimenting with `redraw_unit()` in `src\units\drawer.cpp`, where `unit_height_adjust` appears to be used, but I'm really not sure what's going on. Would appreciate it if others can have a look if/when they're able too.

**Comment by Wedge009** [comment] 2021-09-11 14:37
I'm not sure what the relationship is between these two calculations but the result is the same in my test scenario:
https://github.com/wesnoth/wesnoth/blob/8e140ec2b94dd645a37ab58a77aae29dff43c391/src/units/drawer.cpp#L153
https://github.com/wesnoth/wesnoth/blob/8e140ec2b94dd645a37ab58a77aae29dff43c391/src/units/drawer.cpp#L351-L353

Commentary immediately before the second one says:
https://github.com/wesnoth/wesnoth/blob/8e140ec2b94dd645a37ab58a77aae29dff43c391/src/units/drawer.cpp#L345-L346

I used the opening scenario of The Rise of Wesnoth to test. At maximum zoom of 400%, `zoom_factor` is 4.
* Jessene's height adjustment is 0 so doesn't change with zoom.
* Eldaric's height adjustment is 3 so a zoomed adjustment of 12 still looks reasonable.
* Haldric's height adjustment (on the castle keep) is 20, so 20 x 4 is 80... which is ridiculous since, if I recall correctly, the hex size is 72 pixels.

The calculation makes reference to `adjusted_params.offset` but in this scenario it's always 0. I suppose if it was non-zero, the calculation may work out to be something more reasonable. It doesn't look like this code (relating to zoomed height adjustment) has been changed for 7 years or so, so I suppose it's been an issue for at least that long.

**Comment by AI0867** [comment] 2021-09-13 11:35
> I used the opening scenario of The Rise of Wesnoth to test. At maximum zoom of 400%, `zoom_factor` is 4.
> 
> * Jessene's height adjustment is 0 so doesn't change with zoom.
> * Eldaric's height adjustment is 3 so a zoomed adjustment of 12 still looks reasonable.
> * Haldric's height adjustment (on the castle keep) is 20, so 20 x 4 is 80... which is ridiculous since, if I recall correctly, the hex size is 72 pixels.

At 4x zoom, a hex is 72*4 = 288 pixels, so an offset of 80 would not be strange. But the way you describe this, it seems like the zoom is applied twice?

Maybe create a terrain with a ridiculous offset of 72 pixels (so it's offset by exactly 1 hex), and see how zooming affects that.

**Comment by Wedge009** [comment] 2021-09-13 11:52
Oh, that's a good point about the tiles being scaled too... silly me.

Maybe it is a case of the offset being scaled by the zoom factor and then the the unit and tiles being scaled altogether. I'll try to have another look.

**Comment by Wedge009** [comment] 2021-09-13 13:01
If you're able, would appreciate testing of #6081. It looks right to me, at least.

**Closed** 2021-09-25 23:30 UTC
Labels: Bug, Confirmed, Graphics
