### ISSUE TITLE
Troll recall list gets deleted in SotBE

### ISSUE THREAD

**Issue by brirush84** [wesnoth/wesnoth#5983] opened 2021-07-25 16:26 UTC
### Game and System Information
 - What version of the game are you running?
    1.15.14
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
   The website
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - What OS are you running?
   Windows 10

### Describe the bug
During the battle Back Home, your troll recalls are assigned to Gruu. At the end of the fight, they are supposed to be transferred back to you. However, only trolls that were 'out' during the fight are transferred; all trolls that were never recalled are lost when playing the next scenario, Civil War.

### To Reproduce

1. First download this replay: https://www.wesnoth.org/forum/viewtopic.php?p=666765#p666765
2. Then check your recalls for Gruu during the fight
3. Lastly continue to the next scenario and check your recalls

### Expected behavior
I expected to have all the troll warriors and rocklobbers still on the recall list

### Screenshots
![image](https://user-images.githubusercontent.com/28042598/126906179-b10ec92a-a906-4141-8d20-1de8d28c21ab.png)

![image](https://user-images.githubusercontent.com/28042598/126906208-2f0b79ca-e7a1-4637-a440-c251c137ba37.png)

### Savefiles
If applicable, attach savefiles to help explain your problem. (To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.)
[SotBE-Back Home replay 20210724-114909.gz](https://github.com/wesnoth/wesnoth/files/6874198/SotBE-Back.Home.replay.20210724-114909.gz)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.

**Comment by cooljeanius** [comment] 2021-07-25 18:42
hm, I bet this is probably an issue in SotBEEE, too; I should check...

**Comment by knyghtmare** [comment] 2021-07-26 20:21
I checked the code. It seems that only Trolls on the map are transferred back and the ones in the recall list are just ignored. I haven't faced this bug before since in my playthroughs, I only had about 5 trolls veterans overall and those 5 would be recalled here.

**Comment by Wedge009** [comment] 2021-09-17 15:27
I suppose @ln-zookeeper isn't around any more as maintainer.

I'm still not too strong on WML, but it looks like this is the departure of the trolls:
https://github.com/wesnoth/wesnoth/blob/bd793bd6e84779e4a406f3a0b5caa54c7345a0ab/data/campaigns/Son_Of_The_Black_Eye/scenarios/14_Back_Home.cfg#L384-L406

Then they return under Grüü in turn 7:
https://github.com/wesnoth/wesnoth/blob/bd793bd6e84779e4a406f3a0b5caa54c7345a0ab/data/campaigns/Son_Of_The_Black_Eye/scenarios/14_Back_Home.cfg#L518-L545

And then at the end of the scenario they're supposed to be restored to the player (side 1):
https://github.com/wesnoth/wesnoth/blob/bd793bd6e84779e4a406f3a0b5caa54c7345a0ab/data/campaigns/Son_Of_The_Black_Eye/scenarios/14_Back_Home.cfg#L779-L794

Given the report and what's shown here, it does look like there's no way for the trolls in the original recall list to be restored to the player at the end of the scenario, aside from whatever recruits Grüü may have done earlier. I'm not sure how it should be in order accomplish a proper restoration of the troll veterans.

**Comment by knyghtmare** [comment] 2021-09-17 15:39
> `side=1,2,3 `

Hmm, it seems the troll veterans of all orcish allied sides are transferred to Gruu. I can restore the recalls to side 1, but side 1 will be getting all of the side 4 recalls, including the ones which originally belonged to sides 2 and 3. I don't suppose that will be a problem.

**Comment by Wedge009** [comment] 2021-09-17 15:49
From a player's point of view, having extra recalls rather than fewer is probably better.

I don't have any plans on replaying this campaign again any time soon, else I would consider doing some thorough testing.

**Comment by Descacharrado** [comment] 2022-06-15 17:33
Couldn't reproduce on 1.16 or 1.17

**Comment by knyghtmare** [comment] 2022-06-15 17:38
> Couldn't reproduce on 1.16 or 1.17

Have some trolls in Gruu's recall list when trying to reproduce, it occurs for those x,y=recall,recall units as they are lost...forever

**Comment by Descacharrado** [comment] 2022-06-15 17:47
Yes, I had trolls on my recall list and they were transferred to the next scenario as expected.

In other words, the code below seems to apply to the whole side 4 (units on the map and on the recall list) without issues. https://github.com/wesnoth/wesnoth/blob/bd475c50c1373ed6f2dbd9a8b41576524523bc18/data/campaigns/Son_Of_The_Black_Eye/scenarios/14_Back_Home.cfg#L789-L794

**Comment by cooljeanius** [comment] 2023-01-13 13:15
@Toranks says in #7280 that this is actually already fixed?

**Comment by cooljeanius** [comment] 2023-01-13 13:35
> Maybe a bisect is in order but it feels like too much work for something that already seems to be ok (at least for me).

All right actually never mind about the bisect; let's just close this now...

**Closed by cooljeanius** 2023-01-13 13:35 UTC
Labels: Bug, Campaign, Units
