### ISSUE TITLE
Feature Request: New Animation Features

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#6738] opened 2022-06-01 17:16 UTC
### Describe the desired feature

**It should be possible to place animations directly on hexes:**
Currently real animations can only be tied to units, that makes it hard to use big or persistent animations without any impact on gameplay especially on somewhat small maps because unit has to be placed somewhere where player or AI cant reach and sometimes finding such spots can be hard especially if there is a need for such animation in a very certain spot. 

**Animations shouldn't disappear if player no longer sees the hext that they are on (probably best as an option):**
When designing an animation that is going through the entire map and the map is somewhat long, it is almost certain that player will no longer see the hex and when that happens animation will also disappear.

**Comment by Alarantalara** [comment] 2022-06-02 00:22
The terrain_graphics tag already supports essentially everything mentioned.
[terrain_graphics]
  x=
  y=
 map="bunch of asterisks, periods and commas to specify the hexes where the animation will be rendered"
[image]
animations can be specified here
[/image]
[/terrain_graphics]

**Comment by Hejnewar** [comment] 2022-06-02 08:02
It does not. Because if I try to make animation moving throughout the entire map, the amount of required images will not be 4 but around 400 to make it look smooth if not more also it does not support any of the often needed tags, it will be just playing over and over again, there is not frequency, there are no offsets, there is no duration, there are no blends. 

If I try to make for example stampede, with unit [animation] tag it is really simple, just few frames and the code will take care of everything else and with this I'm not even completely sure that it can be ever made as smooth, probably can but the amount of work is on a completely different level as well as unnecessary weight bloat.

Honestly, if this was unnecessary, people wouldn't be using dummy units as a base to kind of hack in the possibility of doing just that, the fact that something is possible somewhere else doesn't mean that it is better.

**Comment by doofus-01** [comment] 2022-06-05 00:56
I'm familiar with terrain and unit animation WML, but I'm not sure if there is an existing solution to what you are asking for.  That is mostly because I don't understand _what_ you are asking for.  ("stampede"?)

Could you provide an example where animations can only be tied to units and not terrain, and where unit animations do not work?

**Comment by Hejnewar** [comment] 2022-06-06 06:46
"Stampede" basically in my mind it is bunch of animals running because something scared them. Do you remember the falcon fly / carpet fly animation? (issue #6589) It is pretty much this. To my knowledge there is no way to do this nicely or without tons of work while not using unit [animation] tag. 

> Could you provide an example where animations can only be tied to units and not terrain

I mean, is there [animation] tag for terrains? To my knowledge only [image] can be used and for me it is not good enough.

>  and where unit animations do not work?

Unit animations do not work in any place where there is no convinient place for units and they break immersion because you need to use dummy unit which can more often than not be found by a player. And this can be really limiting / problematic.

**Comment by CelticMinstrel** [comment] 2022-06-06 12:26
> I mean, is there [animation] tag for terrains? To my knowledge only [image] can be used and for me it is not good enough.

[image] is already an animation tag, as it supports the same progressive string syntax used in unit animations.

**Comment by doofus-01** [comment] 2022-06-11 12:01
> That said, I don't think there's any way to use separate [image] tags for each frame, or anything like that…

I'm not sure why you'd need a separate [image] tag for each frame, but maybe I'm misunderstanding something.

> To my knowledge only [image] can be used and for me it is not good enough.

In what way not good enough?  I see sprite sliding, like #6589, not being as convenient (though still possible with macros and IPFs).  Anything else?  Specifics would make this request clearer.

**Comment by Hejnewar** [comment] 2022-06-11 13:36
> In what way not good enough? I see sprite sliding, like #6589, not being as convenient. Anything else? Specifics would make this request clearer.

At this point I myself am not quiet sure if I'm understanding this correctly, so you are saying that image tag in terrain graphics or toplevel can already perform the same role? In general if something is not convenient enough but there are still people who try to use that by basically hacking in the functionality then I guess that alone would justify it. 

> (though still possible with macros and IPFs)

Can you provide an example of how you would do that? Because to be honest, I can't see myself doing that, because I just wouldn't know how. Even after reading the IPF wiki, which I just did.

**Comment by Alarantalara** [comment] 2022-06-11 14:02
Something like this (to move images around in a space):
"../misc/blank.png~CROP(0,0,w,h)~BLIT(real image, x, y)"

w,h are chosen to be: big enough to contain the real image + enough whitespace surrounding it to contain the real image relative to a chosen reference point (there are two options for the reference point, depending on which is easier to work with).
x, y locate the real image within the canvas as described

That covers one image, and then you chain them together for an animation like this:
"../misc/blank.png~CROP(0,0,w,h)~BLIT(real image 1, x, y):ms,
../misc/blank.png~CROP(0,0,w,h)~BLIT(real image 2, x, y):ms,
../misc/blank.png~CROP(0,0,w,h)~BLIT(real image 3, x, y):ms,
../misc/blank.png~CROP(0,0,w,h)~BLIT(real image 4, x, y):ms"
ms is the number of ms to show each frame and can be different for each

If the game engine is too slow for the amount of things you want to include, then you can prerender each frame from the command line and then use those.
There's no need for the images to be the same size either.

**Comment by Alarantalara** [comment] 2022-06-11 14:37
I think you could get almost all of the remaining ease of specifying animations with one addition to the progressive syntax:
`[#~#:N]`
It would be like existing ranges, but interpolated over N values linearly and rounded to the nearest integer,
so [2~10:5] would expand to [2,4,6,8,10]

It even handles opacity since the image path function for that can take an integer percent.

**Comment by Hejnewar** [comment] 2022-06-11 22:06
At this point Im probably good example, I'm stupid enough that I can't even get it t work properly, I managed to display image that was somewhat shifted to the side but thats about it:

```
    [item]
        x, y = 14,4
        image = "misc/blank.png~CROP(0,0,1000,1000)~BLIT(items/armor.png, 13, 5):100"
    [/item]
```
but neither of the other two worked for me (nothing even appeared), for example:
```
    [item]
        x, y = 14,4
        image = "misc/blank.png~CROP(0,0,1000,1000)~BLIT(items/armor.png, 14, 5):100
                 misc/blank.png~CROP(0,0,1000,1000)~BLIT(items/armor.png, 13, 6):100
                 misc/blank.png~CROP(0,0,1000,1000)~BLIT(items/armor.png, 12, 6):100
                 misc/blank.png~CROP(0,0,1000,1000)~BLIT(items/armor.png, 11, 6):100"
    [/item]
```
and I tried different things for like an hour to try and make it work. 

I'm a simple man, I just want to have a way to place animations that work, without having to put fake units into the game, or learning all of this (because there is very good chance that I wouldn't be able to learn this properly anyway, looking at the fact that for an art greenhorn, this interaction is described nowhere, with exception of this issue (probably low chance to be true but for my experience it is)), so please, give me simple way to do that, that even I can understand, because my ambition to have cool stuff is way higher than my actual art skill (or my understanding how art code works) and I have no idea why I have to learn all of that while units have it nice and simple.

**Comment by Alarantalara** [comment] 2022-06-12 01:33
If you're using the `item` tag, use `halo` instead of `image` for big animations like this. For `image`, everything is supposed to fit inside one hex.
Second, CROP requires the values be less than the source image. Blank is 640x480, so is the largest size you can use. For bigger canvasses than that, use SCALE_INTO. ie. ~SCALE_INTO(1000, 1000) for what you have above (CROP should be faster than SCALE for small images though, since it can just copy pixels in batches unlike SCALE)
Third, you forgot the commas.
Fourth, you've picked such a large value for scale that the image will vanish off the map when using halo, given the x value.

Putting it all together, you get this (I also changed the x values to make the animation more visible):
```
[item]
  x, y = 14, 20
  halo = "misc/blank.png~SCALE_INTO(1000,1000)~BLIT(items/armor.png, 14, 5):100,
    misc/blank.png~SCALE_INTO(1000,1000)~BLIT(items/armor.png, 23, 6):100,
    misc/blank.png~SCALE_INTO(1000,1000)~BLIT(items/armor.png, 32, 6):100,
    misc/blank.png~SCALE_INTO(1000,1000)~BLIT(items/armor.png, 41, 6):100"
[/item]
```
(See a short video of the result [here](https://drive.google.com/file/d/1KAgOHhXXyN7xb0nf07dh2xNPsjIY0syc/view?usp=sharing) (will probably delete in a few weeks since it's easy enough to recreate yourself if desired.)

The original discussion was around `terrain_graphics` as a tag, which has a few more tricks, including creating animations that can pass behind other terrain features, though it's a bit more complicated.

**Comment by Hejnewar** [comment] 2022-06-12 09:22
Thank you very much, I managed to recreate it and I see potential in it, there is still problem of smoothness which can be resolved by working on smaller numbers 9 pixels (currently 18) at a time should be good probably but I'm unsure if it will be enough to reach video level smoothness, it might be necessary to work on 4 pixels at a time. 

https://user-images.githubusercontent.com/41817546/173225346-5cebc0e9-793e-4d3d-bbe3-6a635ce1dc7c.mp4

In my opinion having an option to use this over other means is good but I would still advocate for lower entry level and more convenience.

**Comment by mesilliac** [comment] 2022-07-08 03:19
So i'm currently working on the halo system and this is sort of related. Regarding the requests in the OP:

1. The first request seems like it should be satisfied by using a halo attached to an item. For example the wesnoth test scenario you get if you run `wesnoth -t` has in it:
```
    [item]
        x,y=11,1
        halo="scenery/fire1.png~CS(0,0,50):150,scenery/fire2.png~CS(0,0,50):150,scenery/fire3.png~CS(0,0,50):150,scenery/fire4.png~CS(0,0,50):150,scenery/fire5.png~CS(0,0,50):150,scenery/fire6.png~CS(0,0,50):150,scenery/fire7.png~CS(0,0,50):150,scenery/fire8.png~CS(0,0,50):150"
    [/item]
```
this should be working since 2d7e0a074d62fd8f3274d498ce52dc949ffc4659 which i merged recently. Before that such animations would refuse to play unless another animation was playing.

2. I'm not sure if this works in master, but i'm working on something that should allow it when it's done. Halo animations will still be hidden if the tile they are attached to is shrouded, however.

**Comment by Alarantalara** [comment] 2022-07-08 03:46
For 2, `terrain_graphics` already has that feature because all the affected hexes are specified and so it just renders the ones that are still visible. There's a reason I suggested it first because it is more powerful, though it's a bit easier conceptually to use `halo` and `item`.

Also, if you want video level smoothness, the issue isn't the distance, but the time spent on each frame. Change all the `:100` to `:40` and it will seem smoother despite the distance moved remaining the same.
40 = 25fps
33 = 30fps (about the same as most live TV in North America)
17 ~= 60fps but might cause everything to slow down

For an example of 2, something from a campaign I started working on but never got to a point where I wanted to upload it:
https://drive.google.com/file/d/10xb5zgSZ8-nShtU03C8rcSPL_klO-dGm/view?usp=sharing
The WML for it is
```
[terrain_type]
    symbol_image=forest/pine-tile
    id=magic_circle
    editor_name= _ "Magic Circle"
    string=^Eyc
    aliasof=_bas
    editor_group=cat
[/terrain_type]
[terrain_graphics]
    map="
.,.,*,*,*,*,*,*,*
,.,*,*,*,*,*,*,*,*
*,*,*,*,*,*,*,*,*,*
,*,*,*,*,*,*,*,*,*
*,*,*,*,*,*,*,*,*,*
,*,*,*,*,*,*,*,*,*
*,*,*,*,*,*,*,*,*,*
,*,*,*,*,*,*,*,*,*
*,*,*,*,*,*,*,*,*,*
,*,*,*,*,*,*,*,*,*
*,*,*,*,1,*,*,*,*,*
,*,*,*,*,*,*,*,*,*
*,*,*,*,*,*,*,*,*,*
,*,*,*,*,*,*,*,*,*
*,*,*,*,*,*,*,*,*,*
,*,*,*,*,*,*,*,*,*
*,*,*,*,*,*,*,*,*,*
,*,*,*,*,*,*,*,*,*
*,*,*,*,*,*,*,*,*,*
,.,*,*,*,*,*,*,*
.,.,.,*,*,*,*"
    [tile]
        pos=1
        type=*^Eyc
    [/tile]
    [image]
        layer=-1
        name="circle.png,
              circle.png~PAL(981E0F>791609),
              circle.png~PAL(981E0F>5E1D14),
              circle.png~PAL(981E0F>823D33),
              circle.png~PAL(981E0F>CD7469),
              circle.png~PAL(981E0F>F4614E),
              circle.png~PAL(981E0F>DB2C15)"
    [/image]
[/terrain_graphics]
```

**Comment by mesilliac** [comment] 2022-07-09 02:10
Nice. That looks good, so terrain works well. I would say (1) should be technically fixed now. (2) should be fixed for unit animations when what i'm currently working on is merged.

After discussion on Discord there is also another request (3) that halo animations should use the animation specification format in WML as unit animations, allowing smooth movement and alpha blending, rather than specifying a series of still frames. That should probably be posted as a separare FR.

**Comment by mesilliac** [comment] 2022-07-29 06:17
For the issues stated in the OP, this should now be working. Aside from terrain animation which works fine as shown, overlay animations tied to map hexes are possible using `[item] halo=...`, which will now work independently of other animations. Animations also now keep playing even if the hex they are attached to goes out of view.

It might be worth opening a new issue for potential animation format improvements, if that's still considered important.

**Closed by mesilliac** 2022-07-29 06:17 UTC
Labels: Enhancement, Graphics
