### ISSUE TITLE
Planning mode units are invisible

### ISSUE THREAD

**Issue by EoZ8** [wesnoth/wesnoth#2906] opened 2018-04-16 05:14 UTC
Wesnoth 1.13.13

![image](https://user-images.githubusercontent.com/37751563/38791064-f9d9e5fa-4134-11e8-8081-c5f48dc2693c.png)

**Comment by Vultraz** [comment] 2018-04-16 05:16
Duplicate of #2124.

**Closed by Vultraz** 2018-04-16 05:16 UTC
