### ISSUE TITLE
please add a Show own move and best possible own moves options... (GNA #7018)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1081] opened 2017-05-08 01:43 UTC
**[Original submission](https://gna.org/bugs/index.php?7018)** by anonymous on 2006-09-16

In games played on the server, Ctrl-V and Ctrl-B (Show Enemy Moves & Best Possible Enemy Moves) do not work as would be expected.

On my turn, they correctly show the opponent's units' movement ranges. However, on the opponent's turn, _my_ units' movement ranges are shown instead. (This is apparently identical to how observers see the game and movements, if they use the hotkeys.)

I haven't tested with more than 2 players.

In games that are played locally, this problem is not present or visible, as it's either all-human players or human players against AI. (Maybe the AI is special-cased?)

(Reproduced on linux (all?))
Release: 1.1.9
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 01:43
**Modified on 2006-12-01**

**anonymous wrote:**

> See also bug #7899, these seem to share the same root cause.

**Comment by wesnoth-bugs** [comment] 2017-05-08 01:43
**Modified on 2007-04-09**

**anonymous wrote:**

> Cancel this bug report! I just realised this &quot;feature&quot; is very useful to also check where *your* units can move on your opponent's turn! The numbers really help get an idea of where units can go.
> 
> 
> 
> Of course, if we could have &quot;Show own moves&quot; and &quot;Best possible own moves&quot; behind separate hotkeys, with similar output as from Ctrl-V and Ctrl-B, we could view both our own and the enemy's moves, which would be splendid.
> 
> 
> 
> If you want to, treat this bug as a feature request for that instead. :-)

**Comment by wesnoth-bugs** [comment] 2017-05-08 01:43
**Modified on 2007-05-25**

**anonymous wrote:**

> See also bug #8883.
> 
> 
> 
> Please change this to a _feature request_, and change the title of this report to &quot;'Show own moves' and 'Best possible own moves'&quot;.
> 
> 
> 
> (I am the original reporter, and the original bug is still valid. I just would prefer fixing the bug in such a way that adds some useful functionality.)

**Comment by wesnoth-bugs** [comment] 2017-05-08 01:43
**Modified on 2007-08-03**

**boucman changed category:** Bug -> Feature Request

**boucman changed title:** Ctrl-V and Ctrl-B misbehaving in online games -> please add a Show own move and best possible own moves options...

**Comment by wesnoth-bugs** [comment] 2017-05-08 01:43
**Modified on 2007-08-04**

**anonymous wrote:**

> Thanks for the changes as requested in comment #3. :-)

**Comment by wesnoth-bugs** [comment] 2017-05-08 01:43
**Modified on 2009-10-24**

**anonymous wrote:**

> Also suggested in bug #11695.

**Comment by wesnoth-bugs** [comment] 2017-05-08 01:43
**Modified on 2010-01-08**

**teaser wrote:**

> Hi, this seems to be re-introduced, at least in 1.7.11, don't know about the stable branch.
> 
> 
> 
> /tsr

**Comment by jostephd** [comment] 2019-09-09 07:48
**Summary**: two different bug reports:

1. On my turn, they correctly show the opponent's units' movement ranges. However, on the opponent's turn, my units' movement ranges are shown instead. (This is apparently identical to how observers see the game and movements, if they use the hotkeys.)
2. please add a Show own move and best possible own moves options... - this one is a duplicate of #1133

**Comment by jostephd** [comment] 2019-09-09 07:52
Duplicate of #1133

**Closed** 2019-09-09 14:20 UTC
Labels: Enhancement, UI
