### ISSUE TITLE
Sidebar abilities display leaks shrouded information

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4456] opened 2019-10-12 23:42 UTC
### Game and System Information
 - What version of the game are you running?

master

### Describe the bug
Sidebar abilities are colored active/inactive when the mouseover hex is shrouded

### To Reproduce

1. `wesnoth -t`
2. Select the lich
3. Mouseover 35,5. The `submerge` ability is shown active
4. Mouseover 35,6. The `submerge` ability is shown inactive

### Expected behavior
Mouseover doesn't reveal information about shrouded hexes

### Screenshots
![2019-10-12-232830_85x252_scrot](https://user-images.githubusercontent.com/24784687/66708903-122edc80-ed48-11e9-9934-a7b289733cf5.png)![2019-10-12-232841_83x252_scrot](https://user-images.githubusercontent.com/24784687/66708904-15c26380-ed48-11e9-9a18-29014d22db8b.png)

### Additional context
It seems the code was last changed in #3929. Reverting that with `git revert 671f32aa62e5c5eedfc438fb7a6d17dd11f1cb94 845978dc9cb2e449f6c65856d43a405f63f98932` fixes the information leak (but reopens #3912, obviously).

**Comment by Wedge009** [comment] 2019-10-13 19:30
Is it a matter of adding a check on a given hex for whether or not it is fog/shroud-covered before updating the side-bar?

**Comment by blaf** [comment] 2019-10-13 19:42
> Is it a matter of adding a check on a given hex for whether or not it is fog/shroud-covered before updating the side-bar?

Yes it is. Created PR #4462

**Comment by Wedge009** [comment] 2019-10-13 19:49
Thanks for the quick response!

**Comment by Wedge009** [comment] 2021-09-09 04:00
Is there another way to check/test this issue? Looks like the test scenario has changed since this was reported - or at least I can't see any 35,5 at the first instance of the test any more.

**Comment by macabeus** [comment] 2022-01-26 01:32
@Wedge009 `29,13` and `29,14` are the updated tiles
<img src="https://user-images.githubusercontent.com/9501115/151088001-c22f9862-a855-4f1d-b6fb-0e34bf96317c.png" height="250px" /> <img src="https://user-images.githubusercontent.com/9501115/151088013-a33c8398-1f8e-4a19-8b19-fa578604295f.png" height="250px" />

**Comment by Wedge009** [comment] 2022-01-26 04:44
Thanks for that. Confirmed against 1.16.2+dev.

**Comment by Pentarctagon** [comment] 2022-09-04 22:21
Closing, since I can't reproduce the issue anymore (as of 507aa62e83b57851dae0a6916b82703bb3ae48b4).

**Closed by Pentarctagon** 2022-09-04 22:21 UTC
Labels: Bug, Confirmed, UI, Good first issue

**Comment by macabeus** [comment] 2022-09-05 07:14
@Pentarctagon Should we close the PR https://github.com/wesnoth/wesnoth/pull/6471 as well?

**Comment by Pentarctagon** [comment] 2022-09-05 15:53
Can you retest just to confirm it's fixed for you as well?
