### ISSUE TITLE
Fungus terrain bug (GNA #21971)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1388] opened 2017-05-08 08:32 UTC
**[Original submission](https://gna.org/bugs/index.php?21971)** by involution on 2014-04-25

There are several hexes on this map that appear on the game map to be of type hills + mushroom grove, but on mousing over the info bar states that they are just mushroom grove. 

25,15

18,7

13,14

6,4

just for example. Not sure if this is intended, just thought I would report.

(Reproduced on Linux Mint 16)
Release: 1.11.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 08:32
**Modified on 2014-06-07**

**fendrin changed status:** None -> Confirmed

**fendrin changed item group:** None of the others -> User Interface

**fendrin changed severity:** 2 - Minor -> 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 08:32
**Modified on 2014-06-07**

**fendrin wrote:**

> fendrin wesnoth:1.12 18282b542fe4 / data/core/terrain.cfg:
> 
> Fix bug #21971: visual glitch of terrains on 2p - Hornshark Island
> 
> http://git.io/PKI4Lw

**fendrin changed status:** Confirmed -> Fixed

**Comment by wesnoth-bugs** [comment] 2017-05-08 08:32
**Modified on 2014-07-15**

**shadowmaster closed the issue**

**Comment by wesnoth-bugs** [comment] 2017-05-08 08:32
**Modified on 2014-10-11**

**shadowmaster reopened the issue**

**shadowmaster changed status:** Fixed -> Postponed

**shadowmaster wrote:**

> Wintermute requested reverting the fix for this bug in the forums, at least for 1.12.x, since it causes too many problems for map designers:
> 
> 
> 
> http://r.wesnoth.org/viewtopic.php?p573664
> 
> 
> 
> Done in commits [76ba22b2b346cc0dc784d22532d288d612951312](://git.io/hFDh0w), [827a8bc2710f049f8dae54e447b59bca8d742fe9](s://github.com/wesnoth/wesnoth/commit/827a8bc2710f049f8dae54e447b59bca8d742fe9), and [cba8414f5a54c105adef830969b635b834c48bcd](://git.io/2KUuCQ) (1.12); and commit [7b708514c7be46ab1ca82bf30e1a45af07ecfca5](://git.io/jd098Q) (master).

**Comment by wesnoth-bugs** [comment] 2017-05-08 08:32
**Modified on 2014-10-11**

**shadowmaster wrote:**

> Correct forum link: http://r.wesnoth.org/p573664

**Comment by wesnoth-bugs** [comment] 2017-05-08 08:32
**Modified on 2016-07-23**

**gfgtdf changed status:** Postponed -> None

**Comment by soliton-** [comment] 2019-07-17 22:21
The Mushroom Grove terrain is not a bug in its current form.

However it's possible the visual representation can be improved to avoid misunderstandings like in this report and perhaps a new terrain that accounts for the base terrain properties could be added as discussed on the forum: https://r.wesnoth.org/t49996

**Comment by jostephd** [comment] 2019-08-11 17:01
Fixed in #4185.

**Closed by jostephd** 2019-08-11 17:01 UTC
Labels: Enhancement, UI
