### ISSUE TITLE
Item tool – not implemented or outdated tooltip?

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3301] opened 2018-07-02 01:44 UTC
The tooltip says:
>Left mouse button sets a new item or moves it vie drag and drop, right click clears. Not yet implemented

Current state is:
One can set items with it.
There is no drag and drop, rightclick calls the usual menu.

Is there more to come? Or should the text be updated? In any case, it seems to be at least halfway implemented.

**Comment by stevecotton** [comment] 2019-10-09 15:23
Duplicate of #1702

**Closed** 2019-10-22 01:02 UTC
Labels: Docs, Editor, Question
