### ISSUE TITLE
text is very tiny

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4908] opened 2020-05-20 23:58 UTC
on my latest 1.15.3 build a lot of dialogs currently look like this:

![image](https://user-images.githubusercontent.com/4893136/82508719-3f294600-9b06-11ea-8f3a-51a5fb6e0267.png)

when actually, there are supposed to look like this: 

![image](https://user-images.githubusercontent.com/4893136/82508789-6e3fb780-9b06-11ea-8c80-0166629c5356.png)

This only happens when the window is large enough. when i make the window smaller this problem goes away

**Comment by Pentarctagon** [comment] 2020-05-21 00:21
If you revert the commits from #4860, does the issue go away?

**Comment by gfgtdf** [comment] 2020-05-21 00:37
running `git revert 43de778c6aad87^..f3a472ab963a5f` and compiling will take a while

**Comment by Wedge009** [comment] 2020-05-21 01:46
That was my first thought too, that it might be related to the recent scaling efforts - before reading the description I thought it was a duplicate of the 'too small at super-high resolutions' issue.

**Comment by gfgtdf** [comment] 2020-05-21 02:20
Yes it does away if i revert the commits from my last post.

**Comment by Pentarctagon** [comment] 2020-05-21 02:29
@gwhitney Can you take a look at this and #4909?  If not, or if a solution is likely to take weeks or more, then these will need to be reverted on master in the mean time.

@gfgtdf The specific monitor resolution and pixel pitch, as well as the resolutions you changed Wesnoth to in order to trigger these bugs, will be useful to know.

**Comment by gwhitney** [comment] 2020-05-21 03:23
Looking right now; and yes, the monitor/window resolutions and pixel pitch would be very helpful to know.

**Comment by gwhitney** [comment] 2020-05-21 06:18
This one is more perplexing to me. The fact that it goes away at smaller resolutions makes sense;  the cutoff should be 1200x900, the resolution that was chosen at which the pixel pitch scaling would set in. (gfgtdf, does that seem to be the cutoff at which things go awry?). The only thing that I can think of is that screen_pitch_microns might be reporting an incorrect value for your screen. I don't suppose you can easily determine what the value of screen_pitch_microns is for you? And what your actual pixel pitch is in microns? I will prepare a pull request such that the changes from #4860 never make fonts smaller -- that should prevent gfgtdf's difficulty, but isn't the _real_ solution to the issue exposed here, which most likely is that screen_pitch_microns is incorrect. I don't know quite how to determine why and how it is incorrect  without being able to debug on gfgtdf's hardware; I can't reproduce this issue on mine. The question is whether only allowing fonts to scale larger, not smaller, is a satisfactory resolution of this problem to work with for now, in the maintainers' views.

**Comment by gwhitney** [comment] 2020-05-21 06:36
OK, you can try PR #4911. It should restore your font sizes (although it is not addressing why screen_pitch_microns is presumably incorrect on your system). Note that PR #4910 and #4911 are independent and each should address just the corresponding one of the two symptoms reported.

**Comment by gfgtdf** [comment] 2020-05-21 10:18
So im currently not on my computer so I cannot give details, but what I can tell you 
from here is that it runs unbuntu18 with a rather old screen of about 1000x1600 resolution connected with a VGA cable.

**Comment by gwhitney** [comment] 2020-05-21 17:40
I gather someone else was able to confirm that PR #4911 alleviated the symptom gfgtdf was encountering, hence it was merged? The 1600x1000 pixel dimensions gfgtdf reports is large enough to trigger the scaling. And given that it is "an old screen connected with a VGA cable," *maybe* what is happening is that the monitor dimensions are not properly getting reported back through the chain of OS to SDL to Wesnoth and CVideo::get_dpi_scale_factor() -- on which screen_pitch_microns is based -- is returning a spurious value. The key call is to SDL_GetDisplayDPI. If someone with the issue, like gfgtdf if it's feasible, could break in CVideo::get_dpi_scale_factor() and let us know the hdpi and vdpi it is returning as compared to the actual physical dpi of the monitor in question, that would be super useful. If it is way off, then if anyone has suggestions on how to tell whether to trust the return values of the SDL call, it would be very helpful -- I am not at all familiar with SDL. But I might be getting ahead of myself;  it's not certain that SDL_GetDisplayDPI is going awry, there could be some other problem with PR #4860. But it sure would be great to know.

**Comment by Pentarctagon** [comment] 2020-05-21 17:50
Highly related: #4913

**Comment by gwhitney** [comment] 2020-05-21 18:20
Yes, in fact I wonder what return code SDL_GetDisplayDPI() was returning on gfgtdf's system. Possibly just #4913 would have fixed this issue without #4911 (but there's no real harm in #4911, I doubt we ever really want to scale the fonts to take fewer pixels).

**Comment by gfgtdf** [comment] 2020-05-21 18:45
the output of the dsl call is hdpi 86.3806, vdpi 83.3438 , while the actual screen size is 47.5x30cm and has a 1680×1050 resolution.

**Comment by gwhitney** [comment] 2020-05-21 20:10
Thanks so much! I agree, SDL_GetDisplayDPI is producing reasonable values, maybe slightly on the small side. And the fact that they are less than 96 explains why the fonts are scaling down (all internal calculations are based on 96 dpi). So the code was actually "working" to try to achieve the nominal "design physical height" of the fonts. So actually I think that PR #4911, already merged, ensuring that fonts are never scaled down together with PR #4913 is the way to go. When you have a chance gfgtdf maybe you can confirm that PR #4911 alleviates your small fonts?

**Comment by gfgtdf** [comment] 2020-05-21 20:19
Yes this issue is fixed but https://github.com/wesnoth/wesnoth/issues/4909 is still a problem.

**Comment by Pentarctagon** [comment] 2020-05-21 21:08
I'll close this one then.

**Closed by Pentarctagon** 2020-05-21 21:08 UTC
Labels: Bug, UI
