### ISSUE TITLE
Add-on manager, text cut off if multiple dependencies are not yet installed

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4331] opened 2019-09-10 20:19 UTC
![grafik](https://user-images.githubusercontent.com/39015360/64647275-01bdd600-d419-11e9-8c50-46c9a0d21bae.png)
I'm pretty sure that there is something missing.

![grafik](https://user-images.githubusercontent.com/39015360/64647383-36319200-d419-11e9-9896-3497cdcf0db8.png)
Looks like the cut off only happens if there are multiple dependencies not yet installed.

**Comment by Earth-Cake** [comment] 2019-09-10 21:38
I can confirm this issue... but it happens to me in opposite way. If I have to install one dependency, the text is cut out.

/home/boban/Слике/screenshot#1-bug.png
/home/boban/Слике/screenshot#2-nobug.png

**Comment by Earth-Cake** [comment] 2019-09-10 21:40
I can confirm this... but to me it happens in opposite way. If there is one dependency to install, the text is cut off. Otherwise not.

![screenshot#1-bug](https://user-images.githubusercontent.com/52823609/64652513-56b31980-d424-11e9-9d8c-715ec66abd3b.png)

![screenshot#2-nobug](https://user-images.githubusercontent.com/52823609/64652541-6599cc00-d424-11e9-9ca3-1cc5174ebe68.png)

**Comment by jostephd** [comment] 2019-09-11 09:03
Duplicate of #3443?

**Comment by Earth-Cake** [comment] 2019-09-11 10:47
Seems so, but obviously another case.

**Closed** 2019-09-13 10:43 UTC
Labels: Add-ons, Bug, Duplicate, UI
