### ISSUE TITLE
Lobby doesn't refresh games list properly (GNA #19302)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1289] opened 2017-05-08 06:40 UTC
**[Original submission](https://gna.org/bugs/index.php?19302)** by gabba on 2012-01-18

This consistently reproduces the problem. I run all of these commands under gdb (managed by Eclipse) with debug builds, btw.

./wesnothd --verbose

./wesnoth --log-debug=whiteboard,engine,network,replay,unit --nomusic --server localhost

./wesnoth --log-debug=whiteboard,engine,network,replay,unit --nomusic --server localhost

Create a game with one client, join it with the other and start the game. Then quit it with both clients. Afterwards, one client or the other will have problems creating new games: the other won't be able to see them in the lobby.

(Reproduced on Ubuntu 10.04)
Release: 1.9.14+svn(52648)
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Wedge009** [comment] 2017-05-09 21:38
This import misses the entire conversation from http://gna.org/bugs/index.php?19302.

**Comment by Pentarctagon** [comment] 2021-08-12 04:56
Any idea what that conversation was at this point?

**Comment by Wedge009** [comment] 2021-08-12 05:09
Sadly not. I should have thought to copy it over if it was missing, though I understand we have a back-up of the old issues somewhere? (Off-line, but still better than nothing at all.)

**Comment by Pentarctagon** [comment] 2021-08-12 05:13
I vaguely remember that @CelticMinstrel might have access to it?  Not sure.

**Comment by soliton-** [comment] 2021-08-13 22:52
https://files.wesnoth.org/gna_bug_export_02052017.xml.gz

**Comment by CelticMinstrel** [comment] 2021-08-14 01:35
I _might_ have the GNA export somewhere on my old computer, but I'm not sure. Looks like soliton found it in any case. I seem to recall zookeeper also grabbed a copy when it was going down.

**Comment by Wedge009** [comment] 2021-08-14 09:38
Thanks, I think that's what I was remembering. Here's the rest of the GNA issue 19302:

@gab @ 2012-01-19 00:06:32 UTC:
> Easier way to reproduce the bug: create a game with the first client then immediately close it before anyone joins; your next game will not show in the lobby for the second client.

@fluffbeast @ 2012-01-22 02:30:34 UTC:
> I can confirm this.  Additionally, once one or both clients have quit the game, simple chatting breaks.  One client may see all messages doubled, and the other sees nothing at all.

retr0virus @ 2012-02-25 11:12:20 UTC:
> I can confirm the previous posts. Creating and closing the game will break the lobby. The players cannot see the others games or chat messages any longer.
> Whispering still works!
> The command-line output says error server: ERROR: Could not find game for player: marcel. (socket: 2)

> marcel is the hosting or message-sending player, 2 the socket that is used for that player.

> The error appears when creating or sending a message after creating/closing the first game.
> When a new player enters the lobby after that his name seems to appear twice in the list.
> Two different errors appear while he connects to the server or writes a message/creates a game:
> error network: Error socket: 17216176      not found in connection_map. Not sending...
> and error network: Error socket: 16813152      not found in connection_map. Not sending...

> All messages sent by this last entered player are doubled for him. All other players can read his messages.
> A game created by him is not seen.
> After he created a game (and I think after he closes the game) one of the other players playerlist disappeared.
> The others could no longer see his messages.
> Whispering still works. To the player with no playerlist too. Whispering with /msg playername message still works for the player without the list.

> Somewhen (possibly after the first player lost his player list or when the last player closed the game) the last player did no longer see his messages or name in the player list twice.

> My testcase was to create 3 players and join to the local lobby. The first created a game, the second joined and the first canceled the game. The fourth player joined to the lobby afterwards.
> Between all that I tried to send messages in the lobby with the results mentioned above.

gabba @ 2012-04-05 08:43:32 UTC:
> Marking as confirmed since this seems reproducible. Soliton, assigning to you since you're the one who knows most about the network - I don't know whether this is a client or server issue.

wedge009 @ 2017-03-19 23:41:27 UTC:
> Is this still confirmed for the redesigned MP lobby in 1.13.x? If it is a network issue it might still be, but the last contact on this issue was nearly five years ago, so it would be good to get an update.

wedge009 @ 2017-03-20 10:22:48 UTC:
> I couldn't reproduce this with 1.13.7+dev. Given this is so old I'm inclined to close this.

wedge009 @ 2017-03-20 10:49:59 UTC:
> How about that. While testing bug #15772 [GNA], I think I ran into this one. Entered a game without meaning to, exited immediately, then had an empty room. Retried the room and re-entered a different game, causing it to apparently hang on trying to enter the game. Interesting.

> So, sadly, looks like this is still an issue in 1.13.7+dev.

The issue was originally assigned to @soliton-. I'm leaving off the 'Confirmed' label until and unless we can reconfirm it now.

**Comment by Pentarctagon** [comment] 2021-08-14 18:22
I can at least say that I've never seen this in my local wesnothd testing during other issues, which often involved doing similar steps with two or three local clients.  So I'd be in favor of closing this as well.

**Closed** 2021-08-21 07:16 UTC
Labels: Bug, MP Lobby
