### ISSUE TITLE
RtL languages: flipped parens at the 'Language' menu.

### ISSUE THREAD

**Issue by ghost** [wesnoth/wesnoth#2626] opened 2018-03-10 21:27 UTC
Flipped parens at the 'Language' menu for a couple right-to-left languages _Arabiyyah_ and _Ivrit_.

![https://frupic.frubar.net/shots/36541.png](https://frupic.frubar.net/shots/36541.png)
[https://frupic.frubar.net/36541](https://frupic.frubar.net/36541)

![https://frupic.frubar.net/shots/36542.png](https://frupic.frubar.net/shots/36542.png)
[https://frupic.frubar.net/36542](https://frupic.frubar.net/36542)

TBfW `1.13.11` for macOS, official binaries `Wesnoth_1.13.11.dmg` (size 424.149.414b sha256 `aa5cea07f6465bf5fa41736f22f3141ea7db3c88fd3c3b08bdc3aff0c9a0cff1`). Using macOS High Sierra.

**Comment by Vultraz** [comment] 2018-03-11 03:17
Cannot repro. Though to be fair, the Arabic characters aren't loading for me.

**Comment by CelticMinstrel** [comment] 2018-03-11 05:03
I can't quite remember, but I _think_ I've seen this months ago.

**Comment by galegosimpatico** [comment] 2018-03-11 16:07
> [...] Arabic characters aren't loading for me.

😱

> I _think_ I've seen this months ago.

`git log -p | grep -i "arabic\|arabiyya\|hebrew\|ivrit\|rtl\|right.to.left"`? I'm not finding anything in this issue tracker.

Maybe I'll read the sources, but I was just testing prelaunch. Better not to add extraneous developers code to `master` until forking new `stable`..?

**Comment by CelticMinstrel** [comment] 2018-03-11 16:11
By saying I've seen it months ago I don't mean to imply that anything was done about it, simply that I recall looking at the languages list and noticing it.

**Comment by galegosimpatico** [comment] 2018-03-11 16:20
I'm AFK, though I spinned up @singalen's TBfW on my iPad to start a campaign while using right-to-left language )to see how deep could the issue be( and surprise, there parens are not swapped.

👽

**Comment by galegosimpatico** [comment] 2018-03-11 22:07
I added a console log of `data["language"]["label"]` in [line 75](https://github.com/wesnoth/wesnoth/blob/7bb4977ceeba2fe5e0c0615422ec84be536ece35/src/gui/dialogs/language_selection.cpp#L75) (recent `master`):

https://github.com/wesnoth/wesnoth/blob/7bb4977ceeba2fe5e0c0615422ec84be536ece35/src/gui/dialogs/language_selection.cpp#L70-L80

It is outputting like this:

```
Setting mode to 1280x800
Checking lua scripts... ok
System default language
Afrikaans
(al-ʿArabiyyah) العربية
Asturianu
Bahasa Indonesia
Български (Bulgarski)
```

There is no swapping to the standard output, yet at the same time there is the parens swapping in the game window, as in `1.13.11`.

<sub>Also the font is all in dark blue instead of white, but I think I've read about that at [the Discord server](https://discord.gg/battleforwesnoth) recently so that's not important.</sub>

**Comment by singalen** [comment] 2018-03-12 00:26
JFYI: iPad version uses a different (ancient!) versions of Pango/Cairo/everything.

**Comment by CelticMinstrel** [comment] 2018-03-12 02:45
So it could be an upstream bug?

**Comment by galegosimpatico** [comment] 2018-03-12 08:21
> So it could be an upstream bug?

I think you call _upstream_ what I call _third party depended libraries_, but yes I suppose I agree.

Poke @sofartin as it could be a problem in the mac version of a dependency?

**Comment by CelticMinstrel** [comment] 2018-03-13 23:57
I think you meant to poke @hrubymar10.

**Comment by hrubymar10** [comment] 2018-03-14 06:49
Well, I **can** reproduce it:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/2218817/37387006-0c9be5d8-275b-11e8-8d25-6883fe5a0d09.png">

Libraries used in 1.13.11 are from MacCompileStuff. This is release info (not from same version but with same libraries):
```
The Battle for Wesnoth version 1.13.11+dev (06e3c8ad7d-Modified)
Running on Apple macOS 10.13.4

Game paths
==========

Data dir:        /Users/USER/xcode/wesnoth/projectfiles/Xcode/build/Release/Wesnoth.app/Contents/Resources
User config dir: /Users/USER/Library/Application Support/Wesnoth_1.13
User data dir:   /Users/USER/Library/Application Support/Wesnoth_1.13
Saves dir:       /Users/USER/Library/Application Support/Wesnoth_1.13/saves
Add-ons dir:     /Users/USER/Library/Application Support/Wesnoth_1.13/data/add-ons
Cache dir:       /Users/USER/Library/Application Support/Wesnoth_1.13/cache

Libraries
=========

Boost:             1.60
OpenSSL/libcrypto: 1.0.2j  (runtime 1.0.2j)
Cairo:             1.12.16 (runtime 1.14.6)
Pango:             1.36.3  (runtime 1.40.1)
SDL:               2.0.7   (runtime 2.0.7)
SDL_image:         2.0.2   (runtime 2.0.2)
SDL_mixer:         2.0.2   (runtime 2.0.2)
SDL_ttf:           2.0.14  (runtime 2.0.14)
libpng:            1.6.10  (runtime 1.6.23)

Features
========

Experimental OpenMP support:    no
PNG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: no
Cocoa notifications back end:   yes
Growl notifications back end:   no
```

But, as you can see, compile versions of libs differs from runtime versions... AFAIK @galegosimpatico  used mine `Fix_xcode_dependencies` script so his runtime versions will also differ.



iOS' version Release info:
```
TBA
```

**Comment by CelticMinstrel** [comment] 2018-03-14 17:39
So does that make it somehow related to the difference between compiled and runtime versions? Or just the use of newer libraries (surely not!)?

**Comment by galegosimpatico** [comment] 2018-03-14 22:28
> But, as you can see, compile versions of libs differs from runtime versions... AFAIK @galegosimpatico used mine Fix_xcode_dependencies script so his runtime versions will also differ.

I did. Thanks for contributing that one!

```
$ brew info pango
pango: stable 1.40.14 (bottled), HEAD
[...]
$ brew info cairo
cairo: stable 1.14.12 (bottled), HEAD
[...]
$ brew info libpng
libpng: stable 1.6.34 (bottled), HEAD
[...]
```

When using GNU/Linux I know how to change quickly between different versions or patches of the third party library dependencies (https://github.com/wesnoth/wesnoth/commit/8b0d7e67998fa0382b4b6f53c8beb11b7f3e8744), however unfortunately I don't know yet how to do that when on macOS. I should learn that one day.

I hope the issue gets solved by itself.

🙂

**Comment by hrubymar10** [comment] 2018-03-15 06:20
I believe that this happens because of buggy pango-cairo. There are also other problems caused by this lib (thin fonts issue showed on discord). I’ll hopefully have more time during this weekend so I’ll try some “magic” with this lib.

**Comment by Wedge009** [comment] 2018-03-18 11:14
I'm using Cairo 1.14.6 on Windows, and Cairo 1.14.10 on Linux and don't have this, although my build and run-times versions are both 1.14.x. Could this be an OSX-specific thing?

**Comment by hrubymar10** [comment] 2018-03-18 11:23
It is macOS specific. Pango on macOS uses CoreFonts.

**Comment by hrubymar10** [comment] 2020-08-25 14:58
I cannot reproduce it with wesnoth 1.15.4 which uses Pango 1.45.3 .

![image](https://user-images.githubusercontent.com/2218817/91190701-27a8bd00-e6f4-11ea-9958-ef2c4d2960e1.png)

Closing...

**Closed by hrubymar10** 2020-08-25 14:58 UTC
Labels: Bug, UI, macOS
