### ISSUE TITLE
Python 3.12 highlights invalid escape sequence in wmlxgettext dependency

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#8867] opened 2024-05-13 16:56 UTC
```
Traceback (most recent call last):
  File "/tmp/wesnoth/data/tools/wmlxgettext", line 41, in <module>
    import pywmlx
  File "/tmp/wesnoth/data/tools/pywmlx/__init__.py", line 13, in <module>
    import pywmlx.state as statemachine
  File "/tmp/wesnoth/data/tools/pywmlx/state/__init__.py", line 1, in <module>
    from pywmlx.state.machine import setup
  File "/tmp/wesnoth/data/tools/pywmlx/state/machine.py", line 11, in <module>
    from pywmlx.state.wml_states import setup_wmlstates
  File "/tmp/wesnoth/data/tools/pywmlx/state/wml_states.py", line 27
    '''
    ^^^
SyntaxError: (value error) not enough values to unpack (expected 2, got 1)
```

**Comment by Pentarctagon** [comment] 2024-05-14 02:42
A couple months ago there was a very similar report from Iris also for wmlxgettext and Python 3.12:
```
18:25:31 iris@mia ~/Projects/Project Ethea/Ethea-i18n git:master % make pot-update
    POT     wesnoth-Invasion_from_the_Unknown.pot
Traceback (most recent call last):
  File "/Users/iris/Local/bin/wmlxgettext", line 41, in <module>
    import pywmlx
  File "/Users/iris/Projects/wesnoth/data/tools/pywmlx/__init__.py", line 13, in <module>
    import pywmlx.state as statemachine
  File "/Users/iris/Projects/wesnoth/data/tools/pywmlx/state/__init__.py", line 1, in <module>
    from pywmlx.state.machine import setup
  File "/Users/iris/Projects/wesnoth/data/tools/pywmlx/state/machine.py", line 165
    value = re.sub('\\\s*$', '', value)
                   ^^^^^^^^
SyntaxError: (value error) not enough values to unpack (expected 2, got 1)
make: *** [Invasion_from_the_Unknown/wesnoth-Invasion_from_the_Unknown.pot] Error 1
```
which was fixed in 4be9aa85849010e93a9a3b0f0701d0630e7b9368.

**Comment by sevu** [comment] 2024-05-14 13:47
Indeed deleting the comment solves it. Will push that later.

Interesting that this happens.

**Comment by Wedge009** [comment] 2024-05-14 22:52
At first glance I thought maybe the interpreter wasn't accepting comment blocks at a different indentation level to what is the then-current class block (for `WmlIdleState`). But it is strange that the current Python triggers an exception on this, but previous ones don't (maybe a deliberate design decision?).

**Comment by Elvish-Hunter** [comment] 2024-05-15 23:17
> I observe line 27 of https://github.com/wesnoth/wesnoth/blob/master/data/tools/pywmlx/state/wml_states.py to be a comment block.

Line 27 isn't a comment block, which in Python don't exist. It's code wrapped inside a multi-line string, so rules for escape characters still apply there.

> But it is strange that the current Python triggers an exception on this, but previous ones don't (maybe a deliberate design decision?).

Yes, it's a deliberate decision, although it should only raise a `SyntaxWarning` for now instead of a `SyntaxError`: https://docs.python.org/3/whatsnew/3.12.html.

**Comment by Wedge009** [comment] 2024-05-15 23:31
I'm still relatively new to Python so I might not know the exact terminology, but clearly the intention was to disable code as a comment - regardless of the syntactic detail, I already said this practice isn't good.

**Comment by Elvish-Hunter** [comment] 2024-05-19 16:23
Exactly. Every point of a string where there's a backslash can generate this kind of problem, because it starts an escape sequence, so that's why I suggested marking the string as raw: it forces backslashes to be interpreted as literal characters.
I'd try to fix it, but on Ubuntu 22.04 I don't have access to Python 3.12 (in the repositories there's 3.11 at most) and forcing an update to 24.04 before the first point release is available isn't recommended (there's an issue that can make Thunderbird unusable). It's better if someone else checks the fix.

**Comment by Pentarctagon** [comment] 2024-05-19 16:53
I use Mint, so it'll probably be at least a couple months until they have a version that's based on Ubuntu 24.04 available.

**Comment by Wedge009** [comment] 2024-05-19 17:45
I'm still waiting for proper ROCm support for Ubuntu 24.04 before switching to it. ):

**Comment by Wedge009** [comment] 2024-05-20 00:02
I tested Python 3.11 and 3.12 in Windows, confirmed the issue as reported, and confirm changing the block to a raw string resolves the issue without apparent change for Python 3.11.

I'd make a PR for this, but I'm still inclined to just remove the whole block instead.

**Comment by Pentarctagon** [comment] 2024-05-20 01:29
If it's just unused code and not meant as an example or to be part of documentation, then I think removing it is fine. Boggles my mind that Python doesn't have actual code comments though...

**Closed** 2024-05-21 12:55 UTC
Labels: Bug, Confirmed, WML Tools

**Comment by CelticMinstrel** [comment] 2024-05-21 12:57
> Boggles my mind that Python doesn't have actual code comments though...

It has comments, just not _block_ comments.
