### ISSUE TITLE
Game crashes when resetting HttT Blackwater Port replay to beginning

### ISSUE THREAD

**Issue by Marken-Foo** [wesnoth/wesnoth#5950] opened 2021-07-12 06:04 UTC
### Game and System Information
 - BfW version 1.15.14 from Steam
 - Windows 10

### Describe the bug
The game crashes when resetting a replay of Blackwater Port (from the mainline campaign Heir to the Throne) to the beginning.

### To Reproduce
1. Load replay of Blackwater Port (one replay provided).
2. Reach the end of the replay (skipping dialogue and animation is fine too)
3. The scenario victory popup displays (???)
4. The map is greyed out like at the end of a scenario.
5. Pressing the "reset to beginning" button for the replay, the game crashes. The relevant log entry is just:
> Caught general '25reset_gamestate_exception' exception:
> std::exception

### Expected behavior
It shouldn't crash, and I don't think the scenario victory/gold carryover popup should appear either - this seems to me to be related to the issue.

### Resources
Clicking the screen removes the popup, then clicking the "reset to beginning" button crashes the game.
![replaybug](https://user-images.githubusercontent.com/41288521/125238355-b2e56e00-e319-11eb-8a42-b1ca6f2e4afb.jpg)

Replay file:
[HttT-Blackwater Port replay 20210703-161305.gz](https://github.com/wesnoth/wesnoth/files/6798869/HttT-Blackwater.Port.replay.20210703-161305.gz)

**Comment by stevecotton** [comment] 2021-07-12 06:38
Confirmed using the replay of a unit test (`test_return`) on Linux with 1.17 (build from 182c911977).

**Comment by stevecotton** [comment] 2021-07-20 10:58
I'm getting diverted while debugging this, because it seems that some replays will show that dialog and some won't, even when the dialog was shown during the game itself.

The when the dialog isn't shown, the code seems to be looping and never exiting replay_controller::play_side_impl. In the cases that the dialog is shown, control has returned to campaign_controller::playsingle_scenario.
* replay_controller::play_side_impl
* playsingle_controller::play_side_impl
* play_controller::play_side
* play_controller::play_turn
* playsingle_controller::play_scenario_main_loop
* playsingle_controller::play_scenario
* campaign_controller::playsingle_scenario
* campaign_controller::play_game
* campaign_controller::play_replay
* game_launcher::play_replay
* game_launcher::launch_game

**Comment by stevecotton** [comment] 2021-07-20 12:49
Current suspicion - the carryover popup only appears (and this bug only happens) for replays that end by "turns over", or by the unit test mechanism.

**Comment by Pentarctagon** [comment] 2021-08-09 17:27
The stack trace when the exception is thrown is:
```
#0  0x00007ffff73e8672 in __cxa_throw () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000555555e4bde7 in playsingle_controller::reset_replay() (this=0x7fffffffc990) at src/playsingle_controller.cpp:706
#2  0x00005555564e4871 in playsingle_controller::hotkey_handler::reset_replay() (this=0x555558b01760) at src/hotkey/hotkey_handler_sp.hpp:94
#3  0x00005555569b7184 in hotkey::command_executor::do_execute_command(hotkey::hotkey_command const&, int, bool, bool) (this=0x555558b01760, cmd=..., press=true, release=false) at src/hotkey/command_executor.cpp:277
#4  0x00005555564dfc87 in play_controller::hotkey_handler::do_execute_command(hotkey::hotkey_command const&, int, bool, bool) (this=0x555558b01760, cmd=..., index=-1, press=true, release=false) at src/hotkey/hotkey_handler.cpp:276
#5  0x00005555569b7c5c in hotkey::command_executor::execute_action(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int, int, bool, display&) (this=0x555558b01760, items_arg=std::vector of length 1, capacity 1 = {...}) at src/hotkey/command_executor.cpp:444
#6  0x000055555630d538 in controller_base::execute_action(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int, int, bool) (this=0x7fffffffc990, items_arg=std::vector of length 1, capacity 1 = {...}, xloc=76, yloc=63, context_menu=false) at src/controller_base.cpp:449
#7  0x000055555630cf28 in controller_base::play_slice(bool) (this=0x7fffffffc990, is_delay_enabled=true) at src/controller_base.cpp:374
#8  0x0000555555e4ac5d in playsingle_controller::linger() (this=0x7fffffffc990) at src/playsingle_controller.cpp:530
#9  0x0000555555e4bafe in playsingle_controller::maybe_linger() (this=0x7fffffffc990) at src/playsingle_controller.cpp:666
#10 0x0000555555b55c3c in campaign_controller::playsingle_scenario(end_level_data&) (this=0x7fffffffd230, end_level=...) at src/game_initialization/playcampaign.cpp:212
#11 0x0000555555b560a5 in campaign_controller::play_game() (this=0x7fffffffd230) at src/game_initialization/playcampaign.cpp:278
#12 0x0000555555b61c94 in campaign_controller::play_replay() (this=0x7fffffffd230) at src/game_initialization/playcampaign.hpp:69
#13 0x0000555555b600fb in game_launcher::play_replay() (this=0x5555576ab810) at src/game_launcher.cpp:1028
#14 0x0000555555b5fe20 in game_launcher::launch_game(game_launcher::reload_mode) (this=0x5555576ab810, reload=game_launcher::reload_mode::RELOAD_DATA) at src/game_launcher.cpp:992
#15 0x00005555559a65b2 in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
    (args=std::vector of length 1, capacity 1 = {...}) at src/wesnoth.cpp:943
#16 0x00005555559a6f17 in main(int, char**) (argc=1, argv=0x7fffffffe598) at src/wesnoth.cpp:1107
```
which notably does not include in it `playsingle_controller::play_scenario_main_loop()` which is where the  `reset_gamestate_exception` is caught.

**Comment by gfgtdf** [comment] 2023-04-27 03:39
I think this was fixed by https://github.com/wesnoth/wesnoth/pull/7459

**Comment by soliton-** [comment] 2023-05-31 14:14
Reopen if it still happens.

**Closed by soliton-** 2023-05-31 14:14 UTC
Labels: Bug, Confirmed, Ready for testing, Replays
