### ISSUE TITLE
Right-click menu can be spawned more than one time

### ISSUE THREAD

**Issue by knowak** [wesnoth/wesnoth#2725] opened 2018-03-23 22:05 UTC
This is not a redrawing artifact, it's possible to close them all one by one hitting Escape... ( current master )

![screenshot from 2018-03-23 23-02-58](https://user-images.githubusercontent.com/611983/37855235-9c9bc7c6-2eee-11e8-9b01-dc5833fed5fa.png)

**Comment by JGelfand** [comment] 2018-03-25 23:39
So I looked into this a bit, and I think I found the issue.
This line creates a drop down menu without a callback_toggle_state_change argument. https://github.com/wesnoth/wesnoth/blob/76c2cbac46a6417bf15a52ce3c6589c0c3954c74/src/hotkey/command_executor.cpp#L404

I believe that the callback_toggle_state_change argument is responsible for closing the menu when there's a mouse click outside of it. At the very least, the [click_callback function](https://github.com/wesnoth/wesnoth/blob/76c2cbac46a6417bf15a52ce3c6589c0c3954c74/src/gui/dialogs/drop_down_menu.cpp#L41) appears to be responsible for detecting clicks outside of the dropdown menu. 

It looks like the solution here is to just pass the existing click_callback function into the drop down menu constructor, but I'm unfamiliar enough with std::function that I'm not sure how to do that.

**Comment by Wedge009** [comment] 2018-05-03 00:57
How do you reproduce this? I tried right-clicking repeatedly on the game map and don't get this. Does it still happen in 1.14.0?

**Comment by knowak** [comment] 2018-05-03 06:48
No, it's been fixed. Not sure which commit tho, it's not mentioned in any log message.

**Comment by Wedge009** [comment] 2018-05-03 08:38
Thanks for confirmation.

**Closed by Wedge009** 2018-05-03 08:38 UTC
Labels: Bug, UI
