### ISSUE TITLE
Editor palette background renders incorrectly

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2618] opened 2018-03-09 12:49 UTC
The editor's palette's background renders as solid black. The relevant area is outlined in white (added locally for debugging):
![whatisthis2](https://user-images.githubusercontent.com/3558659/37208034-ee61a5a4-23f3-11e8-8961-47d65967b4f0.PNG)

As far as I can tell, the issue is that the GUI1's widget's surface restorer is copying the framebuffer too early, or in some other fashion that makes it solid black. The background rect is set in `editor::palette_manager::adjust_size()`.

The issue is quite minor, and barely noticeable (except for the fact that it cuts off the palette's right border. I can't figure out how to fix that), so it's likely not worth fixing. If it isn't, it will be fixed for 1.15 when we switch to accelerated rendering and away from surface restoration.

**Comment by gfgtdf** [comment] 2018-03-10 12:15
make make a new githuib tag 'minor' instead of writing  [minor] in front of the bug ?

**Comment by Wedge009** [comment] 2019-10-15 23:20
I don't see this in 1.14.9.

**Comment by jostephd** [comment] 2019-10-16 05:13
Should be mostly resolved by 416c0f2734c2dbc2a935827e96d9a5d1d619167d. There's still black space at the bottom, is that a problem?

![2019-10-16-051140_1920x1080_scrot](https://user-images.githubusercontent.com/24784687/66889863-8335f480-efd3-11e9-8149-1932a1cea394.png)

**Comment by Vultraz** [comment] 2019-10-16 05:22
Yeah, you can see that the area with the buttons draw over black instead of the panel texture underneath.

**Comment by jostephd** [comment] 2019-10-16 06:00
Yeah, if I edit the editor theme to make the palette shorter, I can see what the background's supposed to be:

![2019-10-16-054717_173x86_scrot](https://user-images.githubusercontent.com/24784687/66891357-749e0c00-efd8-11e9-8179-40635f89a577.png)

This would be a little trickier when the last row of the palette isn't full. For example, in the water terrains:

![2019-10-16-054900_173x100_scrot](https://user-images.githubusercontent.com/24784687/66891436-b7f87a80-efd8-11e9-9d35-dee75df39ed0.png)

**Comment by mesilliac** [comment] 2022-07-14 01:48
Tested and this no longer occurs. I did see it previously so it was probably fixed by #6855.

**Closed by mesilliac** 2022-07-14 01:48 UTC
Labels: Bug, Confirmed, UI, Editor, Good first issue, Low Priority

**Comment by Wedge009** [comment] 2022-07-14 02:04
I think it's talking about how the bottom edge of the palette just keeps going, it doesn't get closed off properly. It's more to do with layout than with rendering, so I don't think #6855 made a difference here.

**Comment by mesilliac** [comment] 2022-07-14 02:24
It may have been an earlier change. I definitely was able to reproduce the black background issue before i started on the highdpi stuff, and can't reproduce it now.

The way the palette isn't closed at the bottom of the screen actually appears to be intentional. I had to leave it like that when i did the low-res theme fixes, as everything worked on the assumption that the palette extended to the very bottom. But those theme fixes might also have been what fixed this black background issue.

**Comment by Wedge009** [comment] 2022-07-14 02:28
Okay, I see now. It's black in 1.16.5 release but it's showing the grey background underneath in 1.17.5+dev.
