### ISSUE TITLE
Title Screen Refresh Crash

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#4447] opened 2019-10-10 08:31 UTC
After enough reloads, Wesnoth starts to lose components of its main menu and crashes if I continue reloading, number of reloads needed seems to be different for every user.

![Bug1](https://user-images.githubusercontent.com/41817546/66550438-b39a1080-eb45-11e9-9427-3ceacdb7014a.PNG)
![Bug2](https://user-images.githubusercontent.com/41817546/66550439-b39a1080-eb45-11e9-8d5f-b2c08610b29d.PNG)

Bug is present in 1.15 and 1.14.

**Comment by Pentarctagon** [comment] 2019-10-10 12:19
Stack trace: https://pastebin.com/itJb61Pr

**Comment by AI0867** [comment] 2019-10-10 16:05
Well, looks like memory corruption to me, and `hotkey_base` is null at some point.

**Comment by Wedge009** [comment] 2019-10-11 00:26
What's meant by 'reloading'? Loading a saved game?

**Comment by Wedge009** [comment] 2019-10-11 00:30
I got the missing wood texture after about 3 minutes and assertion failure maybe 1 minute after that. Continuously pressing F5 with each load.

**Comment by shikadiqueen** [comment] 2019-10-11 20:03
It's worth noting that you can just hold F5 instead of repeatedly pressing it.

I can reproduce the issue on 1.14.9+dev as well, so it's not specific to development. I'd expect the threaded loading screen to be involved somehow.

**Comment by jostephd** [comment] 2019-10-11 23:53
Is it worth trying on 1.12 or 1.10? Or on 1.14 with the loading screen threading disabled (as an uncommitted local change)?

**Comment by Pentarctagon** [comment] 2019-10-12 04:07
The latter sounds the most useful.

**Comment by Hejnewar** [comment] 2019-10-12 11:49
I tried and I was not able to reproduce this bug on 1.12.

**Comment by gfgtdf** [comment] 2019-10-12 12:28
> I'd expect the threaded loading screen to be involved somehow.

quie possible, it might be  point 3) at https://github.com/wesnoth/wesnoth/issues/3218

 > Is it worth trying on 1.12 or 1.10? Or on 1.14 with the loading screen threading disabled (as an uncommitted local change)?

you can actuall disable tzhe treaded losdingscreen withotu changing the source by adding `disable_loadingscreen_animation=yes` to the preferences file

**Comment by Pentarctagon** [comment] 2019-10-16 23:32
Also potentially related: #2698

**Comment by Hejnewar** [comment] 2021-06-22 13:39
This was probably fixed long time ago (or I just no longer get this bug) so Im closing it.

**Comment by Wedge009** [comment] 2021-06-22 14:34
@Hejnewar Do you mind giving it another try? I was able to replicate this reliably still, on 1.14.17 release, 1.15.14+dev (1.16 branch), and 1.17.0+dev (master). Each of them on both Linux and Windows 7. In all cases the segmentation fault happened fairly quickly (less than 30 seconds), although the development builds for Windows 7 took longest and resulted in an unresponsive window rather than a crash-to-desktop.

**Comment by Hejnewar** [comment] 2021-06-22 14:43
I actually tried for few minutes on 1.15.14 and 1.14.15 and nothing happened for me. Well if it happens for others then it should be open anyway.

**Comment by Wedge009** [comment] 2021-06-23 01:45
Would be good if someone else can confirm this then, because it might be just me (although my Windows and Linux machines are separate PCs).

**Comment by CelticMinstrel** [comment] 2021-06-23 02:55
I held down F5 and it looked like it crashed on the second reload (running almost-master on MacOS).

**Comment by mattsc** [comment] 2021-06-23 15:08
Also on a Mac, I pressed F5 individually 20 times and nothing happened, but holding it down causes a crash reproducibly after 2 to 5 reloads.

**Comment by Wedge009** [comment] 2021-06-23 22:35
To clarify, I also used the 'hold down' method. Sounds like there's some race condition if another refresh is run straight after a previous one.

**Comment by Pentarctagon** [comment] 2021-06-23 23:53
The loading screen is multi-threaded, so it would be interesting to see if this persists when that's disabled somehow.

**Comment by stevecotton** [comment] 2021-06-26 15:04
Replicated it on the current master branch, Linux build from b1245e26a7d61b459b413b886bdf5bd8eb6d721c, using the "hold down" method. It is a problem with the multi-threaded loading screen's threads, however the bug seems to be that calling handling any hotkey during `hotkey::load_hotkeys` is undefined behaviour.

The crash happens during this call in do_gameloop():

```
case gui2::dialogs::title_screen::RELOAD_GAME_DATA:
	gui2::dialogs::loading_screen::display([&config_manager]() {
		config_manager.reload_changed_game_config();
	});
	break;
```

Thread 1 is crashing with this stack trace:

* in the STL implementation of std::map for the hotkeys
* in hotkey::get_hotkey
* in gui2::event::sdl_event_handler::key_down
* in gui2::event::sdl_event_handler::handle_event
* in events::pump
* in gui2::window::show
* in gui2::dialogs::modal_dialog::show
* in gui2::dialogs::loading_screen::display
* in do_gameloop

At the same time, the other thread spawned by loading_screen::display is inserting data into that std::map:

* in the STL implementation of std::map for the hotkeys
* in hotkey::load_hotkeys
* in game_config_manager::init_game_config
* in game_config_manager::reload_changed_game_config

**Comment by Pentarctagon** [comment] 2021-06-26 18:14
I wonder if this is related to #2698

**Comment by stevecotton** [comment] 2021-06-27 17:21
I think we should retitle this "Crash processing keyboard input during loading screen", as it seems that the "hold" method, my stacktrace in [two comments above](#issuecomment-869015627) and Pentarctagon's stacktrace in [the second comment](#issuecomment-540545654) all point at that rather than the title screen.

**Comment by stevecotton** [comment] 2021-06-28 09:20
> the main reason why we have the threaded loading screen ... is Wesnoth's ability to react on user input (resizing of the window and closing the window)

Thanks to @gfgtdf for this comment above. A couple of options for fixing this:

* Add a mutex in `get_hotkey` and `load_hotkeys`. This will add overhead to every response to user interaction, but it's probably only negligable overhead.
* Capture input (definitely keyboard, might also need mouse events) in the loading screen without using the hotkey system.
* Extend the current `loading_screen::progress(loading_stage)` mechanism to either block the `pump()` thread or run a function in the `pump()` thread.

Assigning to myself while I look at the third one of those options.

**Closed** 2021-06-28 14:25 UTC
Labels: Bug, Confirmed, Engine

**Comment by Wedge009** [comment] 2021-06-28 15:23
Thanks. I haven't been able to replicate the issue since #5909.
