### ISSUE TITLE
1.17.6 Windows, Black Screen on Turn Dialog, and "Undo" not working

### ISSUE THREAD

**Issue by ShieldOfWesnoth** [wesnoth/wesnoth#6938] opened 2022-08-03 17:16 UTC
### Game and System Information

The Battle for Wesnoth version 1.17.6 x86_64
Running on Microsoft Windows 10 21H1 (10.0.19043) x86_64
Distribution channel: SourceForge

Game paths
==========

Data dir: C:\Program Files\Battle for Wesnoth 1.17.6
User config dir: C:\Users\USER\Documents\My Games\Wesnoth1.17
User data dir: C:\Users\USER\Documents\My Games\Wesnoth1.17
Saves dir: C:\Users\USER\Documents\My Games\Wesnoth1.17\saves
Add-ons dir: C:\Users\USER\Documents\My Games\Wesnoth1.17\data\add-ons
Cache dir: C:\Users\USER\Documents\My Games\Wesnoth1.17\cache

Libraries
=========

Boost: 1.79
Lua: 5.4.4
OpenSSL/libcrypto: 1.1.1o (runtime 1.1.1o)
Cairo: 1.17.6 (runtime 1.17.6)
Pango: 1.50.7 (runtime 1.50.7)
SDL: 2.0.22 (runtime 2.0.22)
SDL_image: 2.0.5 (runtime 2.0.5)
SDL_mixer: 2.0.4 (runtime 2.0.4)

Features
========

Lua console completion: yes
Win32 notifications back end: yes

Current video settings
======================

SDL video drivers: [windows] dummy
Window size: 1920x1061
Game canvas size: 1920x1061
Final render target size: 1920x1061
Screen refresh rate: 60

Current audio settings
======================

SDL audio drivers: [wasapi] directsound
Number of channels: 2
Output rate: 48000 Hz
Sample format: signed 16 bit little-endian
Sample size: 4096 bytes

Installed add-ons
=================

An_Orcish_Incursion: 1.0.3

### Description of the bug

Bug 1: When I have "Turn Dialog" enabled, the map around it turns completely black until the dialog box is dismissed. The top bar and sidebar are unaffected, but the _map_ is utterly blackened.  When the turn dialog box is dismissed, the map will remain black except for animated water hexes, and a few units and areas around them. Hovering over any unit dismisses most of the black covering the hexes, blackened hexes will "uncover" from the hex they're obscuring when hovered over with the cursor, and all of the blackness will go away when either hovered over with a cursor enough, or the map is scrolled away from it.
Bug 2: I try to press the "U" key, and the game does not Undo. I checked my Preferences to make sure the hotkey was still the same, and it was, but it refused to function. I tried this both yesterday with the Tutorial, and today with Caves of the Basilisk.  Unknown if Undo functionality still works at all in 1.17.6, other hotkeys for recruiting and recalling are still working fine.

### Steps to reproduce the behavior

1: Open an afflicted version of The Battle for Wesnoth (this bug report is for 1.17.6, but I've been experiencing near-identical manifestations of the black screen turn dialog error across multiple versions since _at least_ 1.14.4), on Windows 10 (the OS I use) if possible
2: Make sure that "Turn dialog" is enabled in your game preferences
3: Play either a campaign or MP scenario (mainline or UMC doesn't matter) long enough for a turn dialog to display at least once

I am not sure how to reproduce the "Undo" error-- pressing "u" simply doesn't undo moves that are normally allowed to be undone (ex. moving a unit to any hex on a map with Fog of War and Shroud disabled).

### Expected behavior

For no map or screen blackening to appear in a game session that was not deliberately programmed in by a developer, and to be able to use the "u" key to undo the moves it usually allows.

### Additional context

Forum thread with screenshots, an attached replay file, and more context: https://forums.wesnoth.org/viewtopic.php?t=56123
I was told to link it here, so I hope this is sufficient... I'd say more if I knew how the game's code worked.  I have seen the black screen bug on another similar Windows PC that I can't remember the specs of, but I am unsure if either of the bugs reported above exist on Mac or Linux.

**Comment by CelticMinstrel** [comment] 2022-08-03 17:47
Seems like bug 1 is intentional, but 1e7deb74348c30935ae27afb3bf6f42036ccd0cb fixes something related to it.

Bug 2 is #6898.

I think we can close this? Not doing it myself because I'm not 100% sure on the status of bug 1.

Also, for future reference, when you have two bugs, please open two separate issues.

**Comment by Pentarctagon** [comment] 2022-08-03 21:43
@mesilliac was able to reproduce the issue, and the commit you linked fixed the issue for him, so I think this can be closed.

**Closed** 2022-08-04 02:05 UTC
Labels: Bug

**Comment by mesilliac** [comment] 2022-08-04 07:27
I fixed the screen remaining black, but it still blanks the entire screen, and this seems to be part of the purpose.

It is not obvious at all that this is the purpose of the option. Perhaps the tooltip for the option should be clarified? It only says "Display a dialog at the beginning of your turn", nothing about hiding the screen.
