### ISSUE TITLE
Tag for adding help files. (GNA #13314)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1154] opened 2017-05-08 04:06 UTC
**[Original submission](https://gna.org/bugs/index.php?13314)** by zen_clark on 2009-04-03

(Reproduced on Any)
Release: 1.6-1.7
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment] 2017-05-08 04:06
**Modified on 2009-04-03**

**zen_clark wrote:**

> The campaign that I am working on would greatly benefit from being able to add sections/topics to the help files.
> 
> 
> 
> Something on the lines of [+help] functionality.

**Comment by CelticMinstrel** [comment] 2017-05-08 04:10
Duplicate of #1155.

**Closed by CelticMinstrel** 2017-05-08 04:10 UTC
Labels: enhancement, WML
