### ISSUE TITLE
Inconsistent cropping of images when they are larger than the hex they're on

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6118] opened 2021-09-27 10:21 UTC
### Game and System Information
 - Game version is 1.15.18
 - Steam download
 - Windows 10

### Describe the bug
When an image is placed on a hex and then scaled and cropped, the cropping of the images is inconsistent.

### To Reproduce
One way to reproduce the behavior:

1. Load the scenario SotA S20 North Knalga
2. Zoom in on the dwarf statues so that the images become larger than the hexes
3. Try scrolling back and forth around the map, removing and returning the statues from view.
4. Move the cursor over the statues
5. Repeat steps 3 and 4 to verify.

### Expected behavior
There should be no glitchy behavior. Parts of images should not reappear/disappear while you are playing and scrolling and zooming.

### Screenshots
Visual Evidence
![imagecrop5](https://user-images.githubusercontent.com/41433185/134890546-6f087341-00d5-426f-9cb8-4213b7336d63.gif)
![imagecrop2](https://user-images.githubusercontent.com/41433185/134890670-fbd8908c-9d94-45e2-9fea-b519e1de1542.gif)

### Savefiles
[SotA-North Knalga replay 20210925-131532.gz](https://github.com/wesnoth/wesnoth/files/7235452/SotA-North.Knalga.replay.20210925-131532.gz)

### Additional context
The WML code which places, scales, and crops the images in the example is [here](https://github.com/wesnoth/wesnoth/blob/ca90694141d8e2c5d2d1ea8afcfb071e9a439f12/data/campaigns/Secrets_of_the_Ancients/scenarios/20_North_Knalga.cfg#L233-L265)

**Comment by AI0867** [comment] 2021-09-27 10:47
Rather than a cropping issue, this could also be a z-order issue, that is, the game is unsure whether the [item] image should be above or below the neighbouring hex.

I suspect it's that the game does not account for an `[item]` being larger than the hex it's on, so redrawing the overlapping hex does not mark the `[item]` as dirty, and it's not redrawn over the hex.

**Comment by Wedge009** [comment] 2021-09-27 10:54
The scrolling of the first animation makes it hard to see what's going on, but at least the second example is clearer.

**Comment by cooljeanius** [comment] 2021-09-27 11:12
oh yeah I think I've noticed this with some unique villages in ANO, too

**Comment by max-torch** [comment] 2021-09-27 11:37
> The scrolling of the first animation makes it hard to see what's going on, but at least the second example is clearer.

In the first animation the scrolling is there on purpose:
When you scroll such that the image is out of view, and then scroll back where the image goes into view, the image is cropped again (if it was uncropped).
The two animations demonstrate slightly different separate behaviors/variants of the issue.

**Comment by Wedge009** [comment] 2021-09-27 12:22
In such a case I think static images would be better, but if they're both similar demonstrations that should be sufficient. I take it these artefacts only happen on statues unique to SotA - it's possible that it's related to #3950 and #3996 which also have sprites that go outside the bounds of a hex, but in both reports it appears that zooming isn't necessary to produce the problem.

**Comment by max-torch** [comment] 2021-10-02 03:41
The role zooming plays is that some sprites (the dwarf statues in this case) become larger than the hex they're on at closer zoom levels. Those mentioned issues probably have sprites that get larger than their hex at the default zoom. For this issue, the problem doesn't typically exist at default zoom.

**Comment by Wedge009** [comment] 2021-10-02 03:52
That sounds like a problem. I don't believe the sprites should be scaled such that they are relatively bigger than the tiles at different zoom levels. I wonder if it's similar to the problem with #5974.

**Comment by mesilliac** [comment] 2022-06-15 06:34
Is it intentional that the images are different sizes at different zoom levels?

The check internally (`is_in_hex` in picture.cpp) only checks whether the image fits into the hex at the default zoom level. It caches this and remembers it for all further checks.

If this bug doesn't happen at base zoom, it may also have been inadvertently fixed by the recent changes in scaled image handling in master.

**Comment by soliton-** [comment] 2022-06-15 08:30
I don't see how that could be intentional. The image should be the same relative size at any zoom level. Anything else doesn't make sense to me. So if that is how it works now then that sounds like this is fixed indeed.

**Comment by mesilliac** [comment] 2022-06-17 04:56
Well i reproduced it at the default zoom level so it has nothing to do with zoom. It looks like AI0867's explanation is correct.

Hovering over the item's hex redraws the item, which puts it on top. But when the hexes to the right are redrawn (by animation or by scrolling into view) they overwrite it, because hexes are drawn left-to-right and they don't know the item extends there.

So it's similar to those other issues linked above, but not the same as they aren't about items. Another similar issue: https://github.com/wesnoth/wesnoth/issues/6203

**Comment by mesilliac** [comment] 2022-07-23 05:06
I fixed this by simply fixing the masking to work on any image size. Items will always be cropped to hex no matter what size they are.

The correct solution for multi-tile images would be to use the terrain graphics system. But cropping these to hex looks okay, and fixes the flickering.

To be clear items were already being cropped to a single hex, just the cropping failed if they didn't match the hex size exactly.

**Comment by CelticMinstrel** [comment] 2022-07-23 21:16
> The correct solution for multi-tile images would be to use the terrain graphics system.

I wonder if those statues should be changed to use terrain graphics then?

**Comment by mesilliac** [comment] 2022-07-24 04:12
They should, but i don't know how to do that so i didn't.

I noticed some of them were a bit out of alignment as well (both before and after the masking fix).

**Closed** 2022-07-24 10:03 UTC
Labels: Bug, Graphics

**Comment by CelticMinstrel** [comment] 2022-07-28 17:46
They could also be changed to units if they're supposed to be impassable… though it from the screenshot it looks like that's not the case.

Anyone want to try changing them to terrain graphics? I think it shouldn't be too hard…

**Comment by mesilliac** [comment] 2022-07-29 03:33
They are impassable in the scenario. Except for one that gets demolished during the opening animation.
