### ISSUE TITLE
Map editor icons problem

### ISSUE THREAD

**Issue by dust5114** [wesnoth/wesnoth#2598] opened 2018-03-05 13:27 UTC
If font scaling is set to more than 110 %, then  tool icons disappear  in windowed mode. In fullscreen problems start at 145% of font scaling, but at 115% some map "toggle view" controls disappear. 
Version 1.13.11, Win 8.1, installed from prebuild installer.

**Comment by dust5114** [comment] 2018-03-05 16:52
Version  1.13.11

**Comment by CelticMinstrel** [comment] 2018-03-05 18:29
This can probably be counted as affecting the game too? Though it may not be as bad there.

**Comment by dust5114** [comment] 2018-03-05 18:40
@CelticMinstrel  Yes,  i looked at the game, same thing  with  map toggle icons if  using default theme.

**Comment by Vultraz** [comment] 2018-03-05 23:02
This has something to do with how GUI1 widgets calculate their sizes with zoom on, which then affects the size of the overlay image they try to load.

**Comment by CelticMinstrel** [comment] 2018-03-06 01:13
I wouldn't expect GUI1 to take font scaling into account when loading images, so if that's the cause, maybe that should be changed.

**Comment by Wedge009** [comment] 2019-10-15 23:12
This seems to be duplicate of #1604, albeit for editor buttons instead of the mini-map.

**Comment by Wedge009** [comment] 2019-10-22 11:09
No further input, closing in favour of #1604, this discussion can apply there too.

**Closed by Wedge009** 2019-10-22 11:09 UTC
Labels: Bug, Editor
