### ISSUE TITLE
It's possible to have scenario-specific tools active when editing a map, which can cause a crash

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#5883] opened 2021-06-23 02:45 UTC
### Describe the bug

If you have a regular map and a scenario map open, the tool isn't reset when you close the scenario map. Attempting to use the tool then causes a crash.

### To Reproduce

1. Open the map editor
2. Modify a few hexes, then create a new scenario with the file menu.
3. Select the units tool (or probably, any scenario-only tool)
4. Close the scenario from the file menu (close map)
5. You are now looking at the map from earlier, but the units tool is still active.
6. Click anywhere on the map, and watch Wesnoth crash.

Something else to consider: is it possible for this to happen when simply switching maps via the window menu?

### Expected behavior

If you switch to a map from a scenario for any reason, and the current tool is a scenario-only tool, it should revert you to the regular terrain tool.

**Comment by stevecotton** [comment] 2021-06-26 08:45
> Something else to consider: is it possible for this to happen when simply switching maps via the window menu?

No, it doesn't. However the reason for that is a hack that's never bothered me before, but might do now that I'll notice it: when switching maps that way, it always switches to the paint tool. That was added (but missed from the file->close path) in b41322f7102d0554c40038cabf316be69e00114d.

**Comment by Wedge009** [comment] 2021-09-15 10:54
Confirmed on 1.14.17 and 1.15.17+dev (1.16 beta).

**Comment by Wedge009** [comment] 2021-09-18 01:42
I'm not too familiar with the Editor so I was investigating this a bit deeper. It looks to me like there are four tools that become enabled when editing a scenario (as opposed to a plain map):
* Item Tool
* Village Tool
* Label Tool
* Unit Tool

Already confirmed the Unit Tool causes a crash in map-only mode, as per the original report. Item Tool and Label Tool, as less complex features, didn't seem to cause any problems using them in map mode. While Village Tool also didn't appear to do anything, when I generated a map and then tried to apply the Village Tool, I assume it encounters a similar confusion regarding its non-scenario state and likewise crashes.

I think resolving this might be beyond me, at least until I get a bit more familiarity with the Editor.

**Comment by Wedge009** [comment] 2021-09-18 02:08
The situation of switching between a map and a scenario seems to be handled appropriately, as steve pointed out - tools are enabled according to map vs scenario when this happens and the active tool is always reset to the common (to both map and scenario) Paint Tool whenever switching between windows (presumably to avoid the situation of having a scenario-specific tool active in a map window?).

It looks like the situation that's missed is when the scenario is closed and the window being switched to is a map.

I think `close_current_context()` handles the map/scenario closing:
https://github.com/wesnoth/wesnoth/blob/b5fa99c5a3831e7a532b692016a57f1cee2341ef/src/editor/map/context_manager.cpp#L1032-L1047

And `switch_context()` handles switching between windows, whether map or scenario:
https://github.com/wesnoth/wesnoth/blob/b5fa99c5a3831e7a532b692016a57f1cee2341ef/src/editor/map/context_manager.cpp#L1049-L1067

But I can't see what the latter is doing differently to ensure the active tool is reset. Maybe because it's not - the commit steve cited is in the Editor controller, not the context manager...?

**Comment by Wedge009** [comment] 2021-09-18 02:17
I was able to work-around the crash by re-using the reset to Paint Tool in the Close Map command. It's at least consistent with existing window switching behaviour and avoids the crash, even if it's a 'hack'.

**Closed** 2021-09-25 05:26 UTC
Labels: Bug, Confirmed, Editor, Good first issue
