### ISSUE TITLE
"Image doesn't fit on canvas" error in TRoW

### ISSUE THREAD

**Issue by inky17** [wesnoth/wesnoth#2912] opened 2018-04-17 04:01 UTC
In TRoW Scenario 7 (Return to Oldwood cutscene), the large Rithrandil portrait gives an "Image doesn't fit on canvas" error, and then you get sent back to the titlescreen.

(Wesnoth ver. 1.13.14, Windows 10 fullscreen, running Wesnoth at 1280x720 resolution.)

It looks like this issue was discussed in #1272 but that report is ancient so I don't know how relevant it is.
Here's a forum thread where MathBrush had the same issue: https://forums.wesnoth.org/viewtopic.php?f=4&t=47927

**Comment by Wedge009** [comment] 2018-05-03 02:57
Does this still happen in 1.14.0? I can't get this to happen even in 800x600 - the profile images are scaled appropriately.

**Comment by inky17** [comment] 2018-05-03 16:47
Just checked, yes it still happens on 1.14.0.

**Comment by Wedge009** [comment] 2018-05-03 17:06
Can you provide more detail on how to reproduce it?

**Comment by inky17** [comment] 2018-05-03 17:26
I just started TRoW and used :choose level to skip to scenario 7; the dialogue happens normally until Rithrandil is supposed to speak and that's when it gives the error.

**Comment by Wedge009** [comment] 2018-05-04 07:27
Okay, I finally managed to replicate this - I was mistakenly using 1280x768 instead of 1280x720. Confirmed on the latter, Windows and Linux, full screen vs window is not relevant.

I suspect it's very similar to #1272 even though the condition failure is different.

![canvas-error](https://user-images.githubusercontent.com/13679322/39616745-4c9c02ac-4fc0-11e8-9cbb-32d75da0e39f.jpg)

**Comment by dmontgrmry** [comment] 2018-05-08 14:38
Personally, from messing around with #3022, I believe that there is infact a bug in the underlying rendering code. However, because the lowest resolution is (I believe, please correct me if I am wrong) 800x600, it is not seen with many other portraits.

Specifically in `07_Return_to_Oldwood`, the WML includes `theme=Cutscene_Minimal`. Changing to `theme=Cutscene`, which adds a menu bar at the top seems to resolve this.

**Comment by Wedge009** [comment] 2018-05-08 15:07
Lowest supported resolution is currently 800x600, yes.

The minimal theme is, as I imagine the name suggests, for story scenes. I think this was introduced for 1.14. I'm not sure what's involved with the underlying gui2 layout for these themes.

@Vultraz Would you know what's going on here, please?

**Comment by CelticMinstrel** [comment] 2018-05-08 17:51
It's kinda a design flaw in the GUI2 framework. If it can't find sufficient space, it gives up and crashes. It's possible to remove the assert instead, but in that case the too-large element will not show up at all.

Most dialogs solve this by enclosing everything on a scroll panel, which causes all those annoying scroll bars to appear in most similar cases. I guess the message dialog doesn't do this (at least for the portrait).

This could likely be fixed by maxing the portrait dimensions either on the C++ or in the dialog or associated widget definitions, thus forcing the portrait to be scaled down if necessary. Maybe something in the image widget could fix this too.

**Comment by shikadiqueen** [comment] 2018-05-23 17:32
Could this be fixed in some way in 1.14, even if it's just by cropping or scaling the portrait in a way that satisfies the dialog's requirements?

**Closed** 2018-05-23 23:27 UTC
Labels: Bug, Campaign, Confirmed, Graphics, Stable 1.14
