### ISSUE TITLE
possible error in wml serialisation (GNA #21340)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1351] opened 2017-05-08 07:50 UTC
**[Original submission](https://gna.org/bugs/index.php?21340)** by beetlenaut on 2013-12-11

To reproduce: Open the map editor. Add a side, then add an Ancient Lich to the map. Save the map and exit the editor. Click on Multiplayer-->Local Game. You get an error message, and are returned to the main screen:

```

Unterminated quoted string, value '

' at <unknown>:354

```

The line number points to this line in the new map.cfg file:

```

      _"



Special Notes:" +

```

The string _is_ terminated, but there is a line break first, which seems to be causing the error message.

Playing or loading a campaign does not cause this error. An Ancient Lich in the map file does, but an Elvish Marksman does not, despite having the same Special Notes lines in its description.

(Reproduced on Linux)
Release: 1.11.7+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:50
**Modified on 2013-12-11**

**beetlenaut added attachment:** [test.map](http://gna.org/bugs/download.php?file_id=19453)

**beetlenaut added attachment:** [test.map.cfg](http://gna.org/bugs/download.php?file_id=19454)

**Comment by wesnoth-bugs** [comment] 2017-05-08 07:51
**Modified on 2013-12-29**

**fendrin wrote:**

> The problem is solved because the editor no longer writes complete wml saved units in the scenario files.
> 
> 
> 
> Still, this looks like a problem with the serialization.
> 
> Thus I keep the bug open and give it back to the unassigned pool.

**Comment by Pentarctagon** [comment] 2021-08-22 23:03
Closing due to lack of information as well as the only known way to reproduce the problem no longer exists.

**Closed by Pentarctagon** 2021-08-22 23:03 UTC
Labels: Bug, WML
