### ISSUE TITLE
persistent incorrect UI

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2228] opened 2017-11-21 21:21 UTC
See picture:
![persistent-incorrect-ui](https://user-images.githubusercontent.com/33452702/33097172-52c8a4fe-cf1a-11e7-8368-5af8e19f5515.png)
Active unit is dwarf. The highlighted area is where it could move...before moving (more on that below). If I move the mouse away from where dwarf stands, there is no "go to" path drawn.

Steps to reproduce (or at least how I got such result):
* plan a movement with the dwarf (many turns ago)
* droid the side
* wait a number of moves (droided dwarf will continue moving as you planned)
* just before dwarf should move, execute `droid 1` (taking side control back)
* you should get control of your side after dwarf finished movement. When you do, you will (probably) have a situation like on the picture above.

**Comment by GregoryLundberg** [comment] 2017-11-21 21:41
Duplicate of #2132. Fixed. Will be included 1.13.11

**Closed by GregoryLundberg** 2017-11-21 21:41 UTC

**Comment by vgaming** [comment] 2017-11-21 21:43
@GregoryLundberg sorry, I thought it's a rare case, didn't check tracker. Thx.

**Comment by vgaming** [comment] 2017-11-21 21:53
@GregoryLundberg Indeed I had an outdated wesnoth version. I've got a new bug right now anyway though (similarly looking), will report.

**Comment by GregoryLundberg** [comment] 2017-11-21 21:55
Please check for similar open or closed issues, before opening a new one

**Comment by vgaming** [comment] 2017-11-22 09:34
@GregoryLundberg of course. As I said, sorry, I thought I caught a rare case.
