### ISSUE TITLE
[units.wesnoth.org] Caribe and Hunter Caribe unit images are not shown.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#8538] opened 2024-03-12 05:29 UTC
## Bug Screenshot

![image](https://github.com/wesnoth/wesnoth/assets/5283677/e424784d-61c5-43ff-94a5-7e5fc17669da)

## Expected Behaviour
I can see what the Caribe and the Hunter Caribe looks like from the UWO and not just their shadows.

- https://units.wesnoth.org/1.17/mainline/en_US/mainline.html#Monsters

**Comment by ProditorMagnus** [comment] 2024-03-12 09:37
Then unit file should have image instead of shadow.

**Comment by soliton-** [comment] 2024-03-12 10:32
Duplicate of #7052.

**Closed by soliton-** 2024-03-12 10:32 UTC
Labels: Bug, Graphics, Units, Units Database
