### ISSUE TITLE
"Match History" on `1.17.22+dev` times out if you haven't played games yet

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#7988] opened 2023-10-25 18:04 UTC
### Game and System Information

- **Version:** v1.17.22+dev (ae4242a430e-Clean) x86_64
- **Downloaded from:** built from source
- **Build info:** ? built from source.
- **OS:** ArchLinux

### Description of the bug

The "Match History" is not possible to open for me. See "steps" below

### Steps to reproduce the behavior

1. Start Wesnoth v1.17.22+dev (ae4242a430e-Clean)
2. Choose an account that has no games on 1.17 yet, and log in into multiplayer
3. Click the button "Match History"

### Expected behavior

Something useful shows up

Actually observed:
* the UI freezes for 5 seconds, after which a modal window "timeout" it shown as on the screenshot
* closing the modal window opens another modal window (see screenshot). This window doesn't have any games that it should have. (Playing just 1 game will fix the behavior, and more than one last game will be shown, see below on that.)

### Additional context

In essence, there are two bugs: about a modal window for "match history" being opened at all after a "timeout", and about the fact that there's a timeout in the first place. My internet connection is pretty stable, there should be no timeouts, yet the timeout is reproducible.

Note that after I've played 1 game on the 1.17 server, the "Match History" started working, showing me more games than just that one new.

The bug looks very similar to what's being reported by @knyghtmare here: https://github.com/wesnoth/wesnoth/issues/7533#issuecomment-1520113286  I'm creating a dedicated issue here because the original issue there was different.

**Comment by Wedge009** [comment] 2023-10-25 21:52
>     2. Choose an account that has no games on 1.17 yet, and log in into multiplayer

I apparently have one match on record, just a test, but I also get the time-out message. On first opening it shows nothing, afterwards it shows the single match record.

>     * closing the modal window opens another modal window (see screenshot).

Where?

> The bug looks very similar to what's being reported by @knyghtmare here: [#7533 (comment)](https://github.com/wesnoth/wesnoth/issues/7533#issuecomment-1520113286) I'm creating a dedicated issue here because the original issue there was different.

I'm not sure how this differs from #7533. On first reading I thought this was the same. I remember testing this same issue some time ago because on selecting one of the other 'tabs' (maybe 'Modifications') the entire game would crash - but this has since been fixed.

**Comment by vgaming** [comment] 2023-10-25 22:01
Hi @Wedge009,

For me, it reproducibly was giving timeouts while I've had 0 games on a certain account, and then never timing out after I've played 1 game. (To be specific, at 0 games I've tried around 5 times, also twice during a single log-in I think.)

> I'm not sure how this differs from #7533.

The title and the first comment of issue #7533 seem to be all about the ability to cancel, I thought. My issue is about the fact that the timeout happens at all. With a stable internet connection, the request should succeed within 5 seconds, right? If that's true, that'd suggest that something is wrong in the logic part of it (without internet latency)

**Comment by Wedge009** [comment] 2023-10-25 22:38
It seems the behaviour is generally less-than-desirable, irrespective of the precise details of symptoms. While the original post of #7533 is more about an enhancement than the bug itself, I think it is all related and could have been discussed in the same report.

Anyway, it feels to me like it might not even be a time-out as such and there's a fixed delay between pressing the button and any dialogue appearing. That's really bad 'UX', which is what I think #7533 is trying to address.

Testing afresh again just now, at 67007768ec9:
1. Logged in to official MP server as myself.
2. Clicked Match History button.
3. Dialogue appears after about three seconds.

I haven't logged in for a long time, let alone test the Match History function. So I wonder if that initial time-out is because of the server delay in having to access my details after a long period. Either way, I think it's agreed that the current implementation isn't the best.

**Comment by Pentarctagon** [comment] 2023-10-25 23:29
There's no fixed delay - essentially it waits up to 5 seconds before timing out and returning control to the player. #7533 is to make it be up to the user to decide how long to wait before aborting the request.

For this issue, a random guess might be that it's incorrectly treating "no results" as "no response at all", but that wouldn't make sense if Wedge009 has a match and still got a timeout. Potentially an index needs to be added to speed up the query regardless though.

**Comment by Wedge009** [comment] 2023-10-25 23:54
Interesting. It might be an issue with server performance because trying again a third application session for today I got the time-out again:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/cafbc0f7-da9e-47a0-b066-16906b207904)
![image](https://github.com/wesnoth/wesnoth/assets/13679322/c7e6609f-846b-4daa-9e14-5091940abd67)

But closing and re-opening shows my single test match:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/60f8031c-01ea-47db-a1f9-ef5c6516dec2)

**Comment by Wedge009** [comment] 2023-10-26 00:04
Odd. Might be directly related to this issue, but I had Wesnoth idle while I was doing something else and then I got this:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/7911325f-2442-4307-8d1e-9911a0f4bdc3)

**Comment by Pentarctagon** [comment] 2023-10-26 19:04
Looks like the issue is the `order by game.START_TIME desc` part of
```
select 
  game.GAME_NAME, 
  game.START_TIME, 
  GROUP_CONCAT(CONCAT(player.USER_NAME, ':', player.FACTION)) as PLAYERS, 
  IFNULL(scenario.NAME, '') as SCENARIO_NAME, 
  IFNULL(era.NAME, '') as ERA_NAME, 
  IFNULL(GROUP_CONCAT(distinct mods.NAME), '') as MODIFICATION_NAMES, 
  case 
  when game.PUBLIC = 1 and game.INSTANCE_VERSION != 'trunk' 
  then concat('https://replays.wesnoth.org/', substring(game.INSTANCE_VERSION, 1, 4), '/', year(game.END_TIME), '/', lpad(month(game.END_TIME), 2, '0'), '/', lpad(day(game.END_TIME), 2, '0'), '/', game.REPLAY_NAME) 
  when game.PUBLIC = 1 and game.INSTANCE_VERSION = 'trunk' 
  then concat('https://replays.wesnoth.org/', game.INSTANCE_VERSION, '/', year(game.END_TIME), '/', lpad(month(game.END_TIME), 2, '0'), '/', lpad(day(game.END_TIME), 2, '0'), '/', game.REPLAY_NAME) 
  else '' 
  end as REPLAY_URL, 
  case 
  when game.INSTANCE_VERSION != 'trunk' 
  then SUBSTRING(game.INSTANCE_VERSION, 1, 4) 
  else 'trunk' 
  end as VERSION 
from wesnothd_game_info game 
inner join wesnothd_game_player_info player 
   on exists 
  ( 
    select 1 
    from wesnothd_game_player_info player1 
    where game.INSTANCE_UUID = player1.INSTANCE_UUID 
      and game.GAME_ID = player1.GAME_ID 
      and player1.USER_ID = 132039
  ) 
  and game.INSTANCE_UUID = player.INSTANCE_UUID 
  and game.GAME_ID = player.GAME_ID 
  and player.USER_ID != -1 
  and game.END_TIME is not NULL 
inner join wesnothd_game_content_info scenario 
   on scenario.TYPE = 'scenario' 
  and scenario.INSTANCE_UUID = game.INSTANCE_UUID 
  and scenario.GAME_ID = game.GAME_ID 
inner join wesnothd_game_content_info era 
   on era.TYPE = 'era' 
  and era.INSTANCE_UUID = game.INSTANCE_UUID 
  and era.GAME_ID = game.GAME_ID 
left join wesnothd_game_content_info mods
   on mods.TYPE = 'modification' 
  and mods.INSTANCE_UUID = game.INSTANCE_UUID 
  and mods.GAME_ID = game.GAME_ID 
group by game.INSTANCE_UUID, game.GAME_ID 
order by game.START_TIME desc 
limit 11 offset 0;
```
With the `order by` it gives an explain plan of
```
+------+--------------------+----------+--------+---------------------+-------------+---------+-----------------------------------------------------------+---------+----------------------------------------------+
| id   | select_type        | table    | type   | possible_keys       | key         | key_len | ref                                                       | rows    | Extra                                        |
+------+--------------------+----------+--------+---------------------+-------------+---------+-----------------------------------------------------------+---------+----------------------------------------------+
|    1 | PRIMARY            | scenario | ALL    | PRIMARY             | NULL        | NULL    | NULL                                                      | 4272062 | Using where; Using temporary; Using filesort |
|    1 | PRIMARY            | game     | eq_ref | PRIMARY             | PRIMARY     | 148     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID       | 1       | Using where                                  |
|    1 | PRIMARY            | era      | ref    | PRIMARY             | PRIMARY     | 550     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID,const | 1       | Using where                                  |
|    1 | PRIMARY            | mods     | ref    | PRIMARY             | PRIMARY     | 550     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID,const | 1       | Using where                                  |
|    1 | PRIMARY            | player   | ref    | PRIMARY,USER_ID_IDX | PRIMARY     | 148     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID       | 4       | Using where                                  |
|    2 | DEPENDENT SUBQUERY | player1  | ref    | PRIMARY,USER_ID_IDX | USER_ID_IDX | 152     | const,forum.game.INSTANCE_UUID,forum.game.GAME_ID         | 2       | Using index                                  |
+------+--------------------+----------+--------+---------------------+-------------+---------+-----------------------------------------------------------+---------+----------------------------------------------+
```
which is bad because the first entry says it's doing a full tablescan of a table with 4272062 rows.

Taking the `order by` out gives:
```
+------+--------------------+----------+--------+---------------------+-------------+---------+-----------------------------------------------------------+---------+----------------------------------------------+
| id   | select_type        | table    | type   | possible_keys       | key         | key_len | ref                                                       | rows    | Extra                                        |
+------+--------------------+----------+--------+---------------------+-------------+---------+-----------------------------------------------------------+---------+----------------------------------------------+
|    1 | PRIMARY            | scenario | ALL    | PRIMARY             | NULL        | NULL    | NULL                                                      | 4272062 | Using where; Using temporary; Using filesort |
|    1 | PRIMARY            | game     | eq_ref | PRIMARY             | PRIMARY     | 148     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID       | 1       | Using where                                  |
|    1 | PRIMARY            | era      | ref    | PRIMARY             | PRIMARY     | 550     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID,const | 1       | Using where                                  |
|    1 | PRIMARY            | mods     | ref    | PRIMARY             | PRIMARY     | 550     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID,const | 1       | Using where                                  |
|    1 | PRIMARY            | player   | ref    | PRIMARY,USER_ID_IDX | PRIMARY     | 148     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID       | 4       | Using where                                  |
|    2 | DEPENDENT SUBQUERY | player1  | ref    | PRIMARY,USER_ID_IDX | USER_ID_IDX | 152     | const,forum.game.INSTANCE_UUID,forum.game.GAME_ID         | 2       | Using index                                  |
+------+--------------------+----------+--------+---------------------+-------------+---------+-----------------------------------------------------------+---------+----------------------------------------------+
```
and completes almost instantly.

**Closed** 2023-10-27 19:44 UTC
Labels: Bug, Confirmed, Blocker: New Stable, MP Lobby

**Comment by Wedge009** [comment] 2023-10-27 23:46
Has this been deployed to the server? Testing at 2023-10-27 ~23:45 UTC, I got the 'time-out' error dialogue on first attempt for today.

**Comment by Pentarctagon** [comment] 2023-10-28 00:52
It's been deployed to 1.17, but not trunk.

**Comment by Wedge009** [comment] 2023-10-28 01:53
I don't know what gets used where. I just build from master and connect to the official server. I suppose I should wait then.

**Comment by Pentarctagon** [comment] 2023-10-28 02:08
+dev clients get redirected to trunk automatically, so to get to the 1.17 server you'd need to manually enter the correct port (which I've once again forgotten).

**Comment by Wedge009** [comment] 2023-10-28 03:00
I was trying to retest this, but seems I can't get any connection to a server, from 1.16 or 1.17, official or development builds. https://status.wesnoth.org/ says master is down, but if that page is accurate I should still be able to access on 1.16, right?

**Comment by Wedge009** [comment] 2023-10-28 14:33
I'm guessing I should wait for things to settle down. Trying in 1.17.22+dev now (about 14:30 UTC) yields `Received error from server: Error retrieving game history.` Trying in 1.17.22 official release still gives me time-out message. Status page says all servers are up.

**Comment by Pentarctagon** [comment] 2023-10-28 14:46
Testing against the trunk server doesn't really tell me anything since I don't know when it was last rebuilt. Might need to add some logging in to see what it's actually doing for the 1.17 server though, since the query should definitely complete in under 5 seconds now.

**Comment by Wedge009** [comment] 2023-10-28 21:42
I just wondered if there was ongoing weirdness withe server. Results unchanged as at 2023-10-28 21:40 UTC. For 1.17.22 release I got two time-out messages and then near-instant responses once the query was cached.

Let me know if/when that logging gets set-up and I can retest.

**Comment by Pentarctagon** [comment] 2023-10-28 22:02
Any logging for this wouldn't be something you'd see on the client - it'd be server-side logs.

**Comment by Wedge009** [comment] 2023-10-28 22:04
Yes, I meant server-side logging. Because I presume when you tested the recent change previously, you weren't seeing time-outs.

**Comment by Pentarctagon** [comment] 2023-10-28 22:20
Well, I can only actually test this on the actual server after it's been rebuilt, since locally I have nowhere near enough data to make the query take more than 5 seconds.

**Comment by Pentarctagon** [comment] 2023-10-28 23:30
#7998

**Comment by Wedge009** [comment] 2023-11-02 22:59
Retested 1.17.22+dev @ 6cc717042db at 2023-11-02 22:54 UTC.

Retested 1.17.22 official build at 2023-11-02 22:55 UTC.

In both cases, the match history returned (from human perspective) practically instantaneously. So looks like the improved queries are live on the server now?

**Comment by Pentarctagon** [comment] 2023-11-03 00:28
They should be.
