### ISSUE TITLE
Time of day randomization doesn't work

### ISSUE THREAD

**Issue by kallaballa** [wesnoth/wesnoth#3542] opened 2018-09-11 11:09 UTC
Multiplayer games with ToD randomization enabled always start at dawn.

**Comment by jyrkive** [comment] 2018-09-11 11:17
Duplicate of #3515.

**Closed by jyrkive** 2018-09-11 11:17 UTC

**Comment by kallaballa** [comment] 2018-09-11 11:34
at least it's now findable with the right terms :). Thx for deduplicating
