### ISSUE TITLE
Load Game UI: Minimap breaks out of its area

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7087] opened 2022-11-04 10:36 UTC
The screenshot says it all.

![image](https://user-images.githubusercontent.com/5283677/199952316-bc541775-d399-4a46-bb4d-ab80835ac20d.png)

Windows 10 Msys2 Compiler
Battle for Wesnoth v1.17.9+dev (26adbf44167) x86_64

**Comment by soliton-** [comment] 2022-11-04 10:47
Would be useful to have a save game to reproduce with.

**Comment by knyghtmare** [comment] 2022-11-04 12:33
[EI-Do or Die-Auto-Save3.gz](https://github.com/wesnoth/wesnoth/files/9938232/EI-Do.or.Die-Auto-Save3.gz)
[EI-Do or Die-Auto-Save2.gz](https://github.com/wesnoth/wesnoth/files/9938234/EI-Do.or.Die-Auto-Save2.gz)
[EI-Do or Die.gz](https://github.com/wesnoth/wesnoth/files/9938236/EI-Do.or.Die.gz)

> Would be useful to have a save game to reproduce with.

The addon is called "Eastern Invasion Revised" (to load a save file)

**Comment by stevecotton** [comment] 2022-11-05 10:53
Might be dependent on screen size - for me it happens with almost any map (any whose width/height ratio is large enough) except for the ones that don't show a map.

Linux (Debian Unstable) with two monitors (happens on both). The game gets window sizes:
* 3840 x 2077
* 2560 x 1398

**Comment by stevecotton** [comment] 2022-11-05 11:48
I tried reverting a3b6f57e4da0f0fadd24fb50e1c23a47290626ee, which changed the layout but the issue still occurs (use the horizontal scrollbar that was removed in that commit, and you'll see the map move out of the left edge of the dialog).

@Vultraz, please would you comment about this?

**Comment by Toranks** [comment] 2023-03-31 08:10
Possibly related, I see this glitch many often

https://user-images.githubusercontent.com/40789364/229063536-08b2f465-7410-47f0-aa1b-5c1eccdc1b25.mp4

**Comment by mesilliac** [comment] 2023-10-28 12:41
Just as a quick note, #7982 probably stops the minimap from drawing outside the window border, as now windows can only draw to their interior.

It doesn't fix the layout problems however.

**Comment by stevecotton** [comment] 2023-10-28 13:14
Although the map draws now inside, for me the vertical divider between game list and preview pane now moves left and right when selecting different games. Tempted to mark this issue fixed and open a new lower-priority one for the new behavior, as while it should be fixed, it's IMO acceptable enough to fix after 1.18.0.

**Comment by gfgtdf** [comment] 2023-10-28 13:22
We can also just remove the blocker label. I think that even if now no longer draws over the window it probably still draws over it's area since there is supposed to be a small gap between the minimap image and the border of the dialoag.So I wouldn't consider this one fixed

**Comment by Wedge009** [comment] 2024-05-02 23:14
@stevecotton I'm not familiar with the milestone convention but I hope it's okay to move this to 1.19 given 1.18 is already out.

**Comment by Wedge009** [comment] 2024-05-25 06:51
For those who encountered this, suggest re-testing in master (1.19) after 5e3a86f7abbfcb48d4c55f4e275fe81fc4a0372a.

**Comment by Wedge009** [comment] 2024-08-09 23:04
Still no feedback on whether or not this is still an issue, but suggest re-testing after 6fff6de906085e00eee062b785d4e159bb3ee723.

**Closed** 2024-08-12 02:47 UTC
Labels: Bug, UI, Medium Priority
