### ISSUE TITLE
Wesnoth occasionally crashes in MP

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#6250] opened 2021-11-02 17:27 UTC
### Game and System Information
 - What version of the game are you running? 1.16.0
 - Where did you download it from? Flatpak
 - What OS are you running? Ubuntu 20.04

### Describe the bug
Wesnoth ocassionally instacrashes with "wesnoth: src/gui/widgets/listbox.cpp:183: void gui2::listbox::set_row_shown(const boost::dynamic_bitset<>&): Assertion `shown.size() == get_item_count()' failed." in the command line (I run it from flatpak command line). It happened when I tried to quit the game I observed and another time just waiting the game to start

**Comment by Wedge009** [comment] 2021-11-03 05:48
This looks like a duplicate of #6233.

**Closed by Wedge009** 2021-11-03 05:48 UTC
Labels: Bug, Duplicate, MP, MP Lobby, UI
