### ISSUE TITLE
Level up removes loyal overlay from unit

### ISSUE THREAD

**Issue by DisherProject** [wesnoth/wesnoth#4058] opened 2019-04-29 18:41 UTC
(Version 1.15.0 on Windows 10)

To reproduce, you can load this game save...

[2p — Caves of the Basilisk-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/3128733/2p.Caves.of.the.Basilisk-Auto-Save1.gz)

... and then attack the Blood Bat with your Elvish Fighter. You'll see the loyal overlay is removed after the advancement.

**Comment by sevu** [comment] 2019-04-30 18:18
When a unit levels up, it looses changes which were made to it directly
The new data is determined by:
- the new unit type
- the [traits], [objects] and amlas the unit had (and still has) … in fact, the part which you can see in debug mode in the [modifications] block

A bit unclear is how the attributes like hp, moves etc. are treated… but many are overwritten on level up by the above.

**Comment by jostephd** [comment] 2019-05-06 22:01
I can reproduce this in SP without mods, just by letting a loyal unit advance. Looks like a regression, so reopening.

See also https://forums.wesnoth.org/viewtopic.php?f=21&t=39771&start=30#p634215

**Comment by jostephd** [comment] 2019-05-06 22:06
To be clear - I started EI S1, let the loyal unit advance, and it lost its silver ring overlay. That's a regression with respect to 1.14, regardless of what changes may have been done under the hood.

**Comment by gfgtdf** [comment] 2019-05-06 23:25
I think the underlying change was most likeley an intentional change to fix the overlay [effect] in particular for [remove_object]. So it's probably best to.fix this in the wml.

**Comment by GregoryLundberg** [comment] 2019-05-07 14:41
Sounds to me like a design oversight. There is no "permanent" option for "overlay" to indicate whether it should be removed when the unit advances,

**Comment by sevu** [comment] 2019-05-07 20:31
Do the `[unit_overlay]` and `[remove_unit_overlay]` tags treat things differently?

**Comment by gfgtdf** [comment] 2019-05-07 21:30
> Do the [unit_overlay] and [remove_unit_overlay] tags treat things differently?

Yes unit overlays added via unit_overlay are supposed to be removed via [remove_object], remove_unit_overlay only exists for comparability.

**Comment by spixi** [comment] 2019-05-13 00:13
Wouldn't it make more sense, when loyal units always get that overlay?
What about having a `overlay_image=` key in `[trait]`?

This would make the `{IS_LOYAL}` boilerplate unnecessary. (You maybe remember `{MAGENTA_IS_THE_TEAM_COLOR}`, which is now superfluous. A little bit off-topic, but moving the description for specials and abilities to adding a description key to `[special]` and `[ability]` would also help to tet rid of the `WEAPON_SPECIAL_*` and `ABILITY_*` marcos.

**Comment by newfrenchy83** [comment] 2019-05-13 08:23
And how dping for hero overlay, must i crete a hero trait and repla trait_loyal by trait_hero for all hero in core,  and impose rhat of addon develloper, my splution is not ideal but have advantage to replace overlays multiple by simgle overlay naturelly persistznt without using [modification s].

**Comment by spixi** [comment] 2019-05-16 18:50
I guess, this is the line responsible for the removement of the overlay:

https://github.com/wesnoth/wesnoth/blob/e3728be0eaf8f5d999cd5eafc6736aa17d52682e/src/units/unit.cpp#L918

**Comment by newfrenchy83** [comment] 2019-05-16 21:53
i already try to use in https://github.com/wesnoth/wesnoth/pull/4069/commits/0dbb2c0b606cab34ac2623b174ee38e98d03f3a4 but this code is necessary for resolve accumulation of overlay after each advancement. i try to solve that in https://github.com/wesnoth/wesnoth/pull/4081

**Comment by spixi** [comment] 2019-05-17 00:19
I started some stuff here: https://github.com/spixi/wesnoth/tree/issue_4058

**Comment by jostephd** [comment] 2019-07-21 01:14
Can we fix this in time for 1.15.0?

**Comment by newfrenchy83** [comment] 2019-07-21 09:39
i don't know, i already added this https://github.com/wesnoth/wesnoth/pull/4081 PR for make overlays a single container image and fix this .s

**Comment by CelticMinstrel** [comment] 2019-07-22 02:38
> Yes unit overlays added via unit_overlay are supposed to be removed via [remove_object], remove_unit_overlay only exists for compatability.

Um, if this is the case, then `[remove_unit_overlay]` should be calling `remove_modification`. Otherwise you can't call it backwards-compatible, given that it was (as far as I know) originally intended to remove overlays added by `[unit_overlay]`.

(To clarify, it should call `remove_modification`, then manually remove the overlay if it's still present.)

**Comment by newfrenchy83** [comment] 2019-07-28 18:58
i pull this https://github.com/wesnoth/wesnoth/pull/4193

**Comment by newfrenchy83** [comment] 2019-07-29 12:21
the main problem that came from the accumulation of a copy of the same image in overlays after each advancement, the best way is to limit the addition to images that are not already present rather than to make overlays non persistent

**Comment by stevecotton** [comment] 2019-08-08 19:23
There are three open PRs with various methods of fixing this (#4198, #4088 and the open-but-rejected 4097). I think we can choose between #4198 and #4088 by the question "can we deprecate `{IS_LOYAL}`, and make it not add the overlay even in the 1.15 branch?"

* Taking the solution in #4088 means that the effect of `[unit]overlays=` is lost if the unit levels. The current implementation of `{IS_LOYAL}` is `[unit]overlays=`.
* Taking the solution in #4198 means that the effect of `[unit]overlays=` continues to work when the unit levels.

I prefer the solution in #4088, but can't see a way to reimplement the `{IS_LOYAL}` macro without making it at least as complex as #4198. I'm assuming `{IS_LOYAL}` might appear before `[modifications]`, after `[modifications]` or in a `[unit]` with no `[modifications]` tag, therefore it can't blindly be implemented as `[+modifications][object][effect]`.

**Comment by CelticMinstrel** [comment] 2019-08-09 01:16
The only case that `[+modifications][object][effect]` would break is if you have `{IS_LOYAL}` followed by `[modifications]`, since amending a non-existent tag just opens a new tag.

If the unit constructor were modified to merge all `[modifications]` tags, then that would cover that case.

Another option would be to deprecate `{IS_LOYAL}` and create a new macro that goes _inside_ `[modifications]`, maybe `{OVERLAY_LOYAL}` or something?

**Comment by stevecotton** [comment] 2019-08-09 01:35
The effect of #4088 is to make `{TRAIT_LOYAL}` be the macro that goes inside `[modifications]` and adds the overlay.

**Comment by newfrenchy83** [comment] 2019-08-09 08:27
But for the hero, {TRAIT_LOYAL} must be replaced by {TRAIT_HERO}, and i have a question: if a overlay is deleted by [remove_unit_overlay], the image don't be back e after advancement if trait don't also delete ?

**Comment by CelticMinstrel** [comment] 2019-08-10 00:39
@stevecotton A couple concerns with that approach...

1. What places that use `{TRAIT_LOYAL}` but not `{IS_LOYAL}`? I would suspect there are quite a few of those.
2. For loyal, rolling the overlay into the trait is fine, because those units probably already had the trait. But for the hero status, that's gonna create potential issues with randomly-generated traits. If a `{TRAIT_HERO}` is added, it should be implemented with `[object]`, not `[trait]`.
3. As @newfrenchy83 mentions it might be necessary to have some special cases in `[remove_unit_overlay]` to detect this situation and remove the trait/object, for backwards compatibility. There would be a deprecation message on them, of course.

**Comment by stevecotton** [comment] 2019-08-10 12:28
A list of places in mainline that use IS_HERO without TRAIT_LOYAL. (This isn't a response to the previous message, just a list while thinking about it).

* Delfador's Memoirs uses OBJECT_LOYAL extensively in characters.cfg
* SoF S1's caravans
* THoT's Dulcatulos
* TSG S3's Ethiliel, when she first appears (she becomes loyal when she joins side 1)
* Tutorial's tutors (Delfador and Galdrad)
* WoV's Vank uses IS_HERO but OBJECT_LOYAL
* WoV S3 has one enemy unit with IS_HERO but OBJECT_LOYAL
* WoV S12's Gribbel, who was the leader (not the IS_HERO) in S3
* one unit in scenario-test.cfg

**Comment by CelticMinstrel** [comment] 2019-08-10 20:37
It can't be a response to my message, since I was talking about places that use `TRAIT_LOYAL` without `IS_LOYAL`. ;p

**Comment by stevecotton** [comment] 2019-08-17 19:09
I think this issue is ready to close - there are related changes that are still in development, but the original bug is fixed in 1.15.0.

**Closed** 2019-08-25 20:33 UTC
Labels: Needs more info, Regression, UI
