### ISSUE TITLE
Single character hotkeys not working

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#1893] opened 2017-08-10 22:37 UTC
As of https://github.com/wesnoth/wesnoth/commit/47ddc3724a6a28a0bedf7d8131ced2183fa718d3
on Win 7 x64

Single character hotkeys are not working (such as : and ` and . and any letters, and any singles using shift)
Combinations still work (ie, ctrl + s, etc), tab still works

bisected at:
(Hotkeys working)
 https://github.com/wesnoth/wesnoth/commit/3f287b9098462529acdd8d36c9d28fe2c92b0b9e

(Hotkeys not working)
 https://github.com/wesnoth/wesnoth/commit/98648ddf636bf4725d17334addac57850c478315

Seems likely introduced in:
https://github.com/wesnoth/wesnoth/commit/047120e2fa45cdb589c2aedaa4a20048c6f46605

**Comment by gfgtdf** [comment] 2017-08-10 23:44
does it work if you remove the `event.text.text[31] == 0 && ` line from https://github.com/wesnoth/wesnoth/blob/master/src/hotkey/command_executor.cpp#L524 ?

**Comment by CelticMinstrel** [comment] 2017-08-10 23:59
If I recall correctly, I already have this fixed locally.

**Comment by sigurdfdragon** [comment] 2017-08-12 00:12
> does it work if you remove the event.text.text[31] == 0 && line from https://github.com/wesnoth/wesnoth/blob/master/src/hotkey/command_executor.cpp#L524 ?

nope

**Comment by sigurdfdragon** [comment] 2017-08-12 14:40
fixed, thanks

**Comment by sevu** [comment] 2017-08-14 22:06
I'm having this problem on Linux with 1fe8ed3a13 (built from today) and without using an old preferences file.

**Comment by Wedge009** [comment] 2017-08-16 08:53
@sevu Can you give any specific examples where you're having difficulty? I'm just playing around with default hot-keys in Windows 7 and they seem to be working on the title screen and main game map. I just recompiled at 50818594.

**Comment by sevu** [comment] 2017-08-16 21:41
Things like _u_ for undoing or  : for debug mode don't work in the scenario. alt+r or ctrl+p work fine, and arrow keys too. In the title screen I see no issues, _e_ for launching the editor works there as well.
(still at 1fe8ed3)

**Comment by Wedge009** [comment] 2017-08-17 00:12
: works for me, as does u. Can anyone else give this a go? I will check if running on Linux makes any difference.

**Comment by Wedge009** [comment] 2017-08-17 02:07
How bizarre. I can confirm this on Linux (just rebuilt at 44207559). Anyone on OSX have the same issue? Anyone have any idea why this would be a seemingly OS-related problem?

**Comment by CelticMinstrel** [comment] 2017-08-20 03:07
So, does reverting 5c701f207b173f03b6abddc89d5165e20116f14a fix the problem? And, what if you revert the commit that's referenced from that commit's message? (Note: Reverting 5c701f207b173f03b6abddc89d5165e20116f14a is not the right move; reverting both might be an option, though not ideal as we'd then return to the problem of ö not working as a hotkey.)

**Comment by gfgtdf** [comment] 2017-08-20 11:18
I have also observed this on windows (appveyor build)

**Comment by Wedge009** [comment] 2017-08-20 12:27
Which commands?

**Comment by gfgtdf** [comment] 2017-08-20 12:43
lua console, commandmode. But i don't see how the associated command is important here.

**Comment by sevu** [comment] 2017-08-20 13:34
with just reverting 5c701f2:
: for command line works
u for undoing works
d works
ctrl+d works
_m, ctrl+m, alt+m for chat all don't work_
shift+c for creating units in debug works
I can't get lua console. With my keyboard, I would have to pres shift+´ twice to get that sign (it's a dead key). I never used lua console, I don't know if it worked once.
_Reassigning the hotkey for lua console to d didn't open it either_

Command mode is listed in the preferences as _:_ ( I think that's better to read, but don't know if this has an effect. At some point in 1.13 it was _shift + ._)

**Comment by CelticMinstrel** [comment] 2017-08-20 20:48
Huh, that's strange that combos with Ctrl and Alt don't work. I'd guess that pressing shift+` followed by space might get you the console, not quite sure though. Really odd that it doesn't work when reassigned to d, unless it's a conflict with the previous meaning of d or something weird like that.

**Comment by sevu** [comment] 2017-08-20 20:55
But with ctrl+t or ctrl+p worked, an _m_ alone not, seems more like a problem with the chat.

When reassigning d didn't have the old effect anymore

**Comment by sevu** [comment] 2017-08-20 21:19
shift+` followed by space produces the right sign in a text field, but doens't toggle the console
(still with reverted 5c701f2)

**Comment by CelticMinstrel** [comment] 2017-08-20 21:43
I hate to recommend reverting the last thing Aginor did for the project, but I'm seriously considering that this might be the only way to fix these issues once and for all. There's still the minor problem that Aginor's work presumably also fixed some issues, though, so we'd probably still need to work on those (unless we can decide that maybe they aren't issues after all).

**Comment by Wedge009** [comment] 2017-08-21 06:17
@gfgtdf I needed to know which command you had trouble with so that I can try it myself, because Windows seemed fine to me. But I can confirm that ` doesn't work for the Lua Console. But then nothing seems to work for Lua Console no matter what I assign to it (including combinations). So I wonder if it's separate issue...

@sevu I wonder if that's a keyboard locale issue. Key for command mode was : (colon) in 1.12, and it's that way again now in 1.13, but in earlier releases it was ; (semi-colon) because in US and similar keyboards : is entered as shift+; . On US keyboards, shift+. is > (greater-than).

@CelticMinstrel How much reverting are we talking about here? I know a lot of good work was done for the hot-keys for the SDL2 migration... but I know there's still a lot of crazy things to handle between key codes, scan codes, keyboard locales, language locales, etc.

**Comment by gfgtdf** [comment] 2017-08-21 11:24
It's probably this one: https://github.com/wesnoth/wesnoth/pull/1003/commits/92ca7fdb5eb11c04b191359892517ea22d9f4491 . Not sure whether the sholw pr or just that commit though.

**Comment by Wedge009** [comment] 2017-08-21 11:47
Ah, I forgot it requires debug mode. Well, in that case, my Windows build can open the Lua Console with the default ` key. So... we have the same situation as before then? I can confirm this is an issue in Linux, but not Windows.

**Comment by CelticMinstrel** [comment] 2017-08-21 12:21
@Wedge009 - I'm talking about #1003, basically. Between this issue and the other one regarding single-character hotkeys (that they don't trigger the key-up event that will stop scrolling if they are assigned to that), I'm starting to wonder if the advantages of that PR are outweighed by the problems.

Also, by the way, apparently ; is typed with the shift key on some keyboards, so shift+; is not a great hotkey.

**Comment by Wedge009** [comment] 2017-08-21 12:53
Oh right, I remember #1003, though I don't know everything it was supposed to do aside from the GUI2 fixes.

I only mentioned the : vs ; issue with respect to the default key for bringing up the command console and pointing out that : was shift+; on US keyboards. I wasn't saying that it should be made the default key for command console.

**Comment by jyrkive** [comment] 2017-08-24 20:49
I'm also hit by this issue, most likely ever since 5c701f207b173f03b6abddc89d5165e20116f14a. I'm on Windows 10.

**Comment by Wedge009** [comment] 2017-08-24 23:27
Which keys are you trying? I've yet to find any issue on Windows, but I'm on 7.

**Comment by jyrkive** [comment] 2017-08-25 04:21
@Wedge009 Writable characters, such as "a" and ":" are broken. Non-writable ones like Esc work.

**Comment by Wedge009** [comment] 2017-08-25 07:20
I can only find a being used at the title screen - that works for me on Windows and Linux, just rebuilt at d0a8f0a8. Re-assigning a to something in the actual game also works for me (on Windows only).

: works for me in Windows only, but that's because it's entered as Shift+; on US keyboards - it's not a single key. Makes me wonder if this is a locale-related problem.

**Comment by jyrkive** [comment] 2017-08-25 07:29
":" isn't a single key in the Finnish keyboard either. It's Shift+.

**Comment by Wedge009** [comment] 2017-08-25 07:41
...and you're saying it doesn't work in Windows 10?

**Comment by jyrkive** [comment] 2017-08-25 08:10
Yes.

**Comment by aginor** [comment] 2017-08-25 10:01
The patch below fixes it for me.

The patch reverts the length check in command_executor and moves the matching logic into hotkey_item.cpp (where all of the other matching logic is implemented).

I've tested this with assigning "ö" to deselect hex and by using the "n" for next unit. I can also confirm that space works again.

```
Index: src/hotkey/hotkey_item.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/hotkey/hotkey_item.cpp	(revision d0a8f0a8588403741885a66e842ae9dde41bd340)
+++ src/hotkey/hotkey_item.cpp	(revision )
@@ -26,6 +26,7 @@
 
 #include <SDL.h>
 #include <key.hpp>
+#include <serialization/unicode.hpp>
 
 
 static lg::log_domain log_config("config");
@@ -301,7 +302,7 @@
 		if (text == ":") {
 			mods = mods & ~KMOD_SHIFT;
 		}
-		return text_ == text && mods == mod_;
+		return text_ == text && utf8::size(utf8::string(event.text.text)) == 1 && mods == mod_;
 	}
 
 	return false;
Index: src/hotkey/command_executor.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/hotkey/command_executor.cpp	(revision d0a8f0a8588403741885a66e842ae9dde41bd340)
+++ src/hotkey/command_executor.cpp	(revision )
@@ -29,7 +29,6 @@
 #include "display.hpp"
 #include "quit_confirmation.hpp"
 #include "show_dialog.hpp"
-#include "serialization/unicode.hpp"
 
 #include "utils/functional.hpp"
 
@@ -522,15 +521,6 @@
 			event.type == SDL_MOUSEBUTTONDOWN ||
 			event.type == SDL_TEXTINPUT;
 
-	if(event.type == SDL_KEYDOWN) {
-		unsigned mods = event.key.keysym.mod;
-		if(!CKey::is_uncomposable(event.key) && !(mods & KMOD_CTRL) && !(mods & KMOD_ALT) && !(mods & KMOD_GUI)) {
-				return;
-		}
-	} else if(event.type == SDL_TEXTINPUT && !(event.text.text[31] == 0 && utf8::size(utf8::string(event.text.text)) == 1)) {
-		return;
-	}
-
 	execute_command(hotkey::get_hotkey_command(hk->get_command()), executor, -1, press);
 	executor->set_button_state();
 }
```

**Comment by jyrkive** [comment] 2017-08-25 10:03
@CelticMinstrel Please look into the patch above.

**Comment by GregoryLundberg** [comment] 2017-08-25 12:29
Do that as a PR, please. Looks good to me.

**Comment by aginor** [comment] 2017-08-25 23:50
I don't know the full context so the patch above might not be what's fully needed. I'll leave it for @CelticMinstrel and @jyrkive to apply and commit it if it suits their intent.

**Comment by CelticMinstrel** [comment] 2017-08-26 02:44
Looks good to me. I'll probably give it a try tomorrow.

**Comment by aginor** [comment] 2017-08-26 07:46
@gfgtdf this updated patch works around your issues with `. It's however a rather awkward hotkey on a Swedish layout (and presumably most non-English layouts).

It's extending the same logic as is already used to make ":" be treated in a special way.

```
Index: src/hotkey/command_executor.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/hotkey/command_executor.cpp	(revision d0a8f0a8588403741885a66e842ae9dde41bd340)
+++ src/hotkey/command_executor.cpp	(revision )
@@ -29,7 +29,6 @@
 #include "display.hpp"
 #include "quit_confirmation.hpp"
 #include "show_dialog.hpp"
-#include "serialization/unicode.hpp"
 
 #include "utils/functional.hpp"
 
@@ -522,15 +521,6 @@
 			event.type == SDL_MOUSEBUTTONDOWN ||
 			event.type == SDL_TEXTINPUT;
 
-	if(event.type == SDL_KEYDOWN) {
-		unsigned mods = event.key.keysym.mod;
-		if(!CKey::is_uncomposable(event.key) && !(mods & KMOD_CTRL) && !(mods & KMOD_ALT) && !(mods & KMOD_GUI)) {
-				return;
-		}
-	} else if(event.type == SDL_TEXTINPUT && !(event.text.text[31] == 0 && utf8::size(utf8::string(event.text.text)) == 1)) {
-		return;
-	}
-
 	execute_command(hotkey::get_hotkey_command(hk->get_command()), executor, -1, press);
 	executor->set_button_state();
 }
Index: src/hotkey/hotkey_item.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/hotkey/hotkey_item.cpp	(revision d0a8f0a8588403741885a66e842ae9dde41bd340)
+++ src/hotkey/hotkey_item.cpp	(revision )
@@ -26,6 +26,7 @@
 
 #include <SDL.h>
 #include <key.hpp>
+#include <serialization/unicode.hpp>
 
 
 static lg::log_domain log_config("config");
@@ -161,7 +162,7 @@
 		base = std::dynamic_pointer_cast<hotkey_base>(keyboard);
 		std::string text =  std::string(event.text.text);
 		keyboard->set_text(text);
-		if (text == ":") {
+		if (text == ":" || text == "`") {
 			mods = mods & ~KMOD_SHIFT;
 		}
 	}
@@ -298,10 +299,10 @@
 	if (event.type == SDL_TEXTINPUT) {
 		std::string text = std::string(event.text.text);
 		boost::algorithm::to_lower(text);
-		if (text == ":") {
+		if (text == ":" || text == "`") {
 			mods = mods & ~KMOD_SHIFT;
 		}
-		return text_ == text && mods == mod_;
+		return text_ == text && utf8::size(utf8::string(event.text.text)) == 1 && mods == mod_;
 	}
 
 	return false;
```

**Comment by Elvish-Hunter** [comment] 2017-08-26 08:39
> this updated patch works around your issues with `. It's however a rather awkward hotkey on a Swedish layout (and presumably most non-English layouts).

I can confirm that both the backtick (`) and the tilde (~) are terrible characters to use with an Italian layout, since they're missing on the keyboard. While at least on Linux they can be typed with the AltGr key (AltGr + ' = `; AltGr + ì = ~), on Windows this cannot be done, and users are forced to use the Alt codes (so Alt + 96 = `; Alt + 126 = ~).

**Closed** 2017-08-28 01:43 UTC
Labels: blocker, bug, confirmed, linux, UI

**Comment by CelticMinstrel** [comment] 2017-08-28 01:46
Fortunately ` is something that most people will never need to use. The Lua console in-game is also accessible from the gamestate inspector, and while the hotkey is also available at the titlescreen, that opens a console for the application Lua kernel which very few people need to care about.

Come to think of it, maybe there should be a way to open a console for the mapgen Lua kernel... though I guess there's always the option of doing so from within the script.

**Comment by sigurdfdragon** [comment] 2017-08-28 18:17
can confirm hotkeys working post 45c8c256cccb299eab861d4e6f5712b72f200ada on Win 7

**Comment by Wedge009** [comment] 2017-09-01 10:20
Thanks @aginor for dropping by, I didn't mean to drag you back into this.

Looks like the fix is already confirmed, but I'll add my confirmation for both Windows 7 and Linux.

**Comment by gfgtdf** [comment] 2017-09-01 13:05
> Fortunately ` is something that most people will never need to use. The Lua console in-game is also accessible from the gamestate inspector

This reasoning is simply wrong, noone will use a way that requires a keypress and a click to open the lua console if it can also be done via a simple hotkey.

**Comment by CelticMinstrel** [comment] 2017-09-01 14:01
That doesn't change the fact that most people won't even need it in the first place. And those who do need it but lack a ` key and don't want the extra click can always reassign the hotkey.

**Comment by sevu** [comment] 2017-09-12 13:04
Just want to confirm that this is fixed for me too.
Opening the lua console works as well.
