### ISSUE TITLE
Windows logging observations (1.17.16)

### ISSUE THREAD

**Issue by Slayer95** [wesnoth/wesnoth#7619] opened 2023-05-10 21:05 UTC
### Game and System Information

- **Version:**
1.17.16
- **Downloaded from:**
https://ufpr.dl.sourceforge.net/project/wesnoth/wesnoth/wesnoth-1.17.16/wesnoth-1.17.16-win64.exe
- **Build info:**
Default
- **OS:**
Windows 7x64 SP1

### Description of the bug

There seems to be lots of confusion about how logging works and/or ought to work in Windows. This issue aims to:
1. Document behavior in Development version.
2. Provide a place to discuss which parts of the current behavior are ok, wrong, unintuitive, etc.

### Steps to reproduce the behavior

N/A

### Expected behavior

- Bugs and usability problems should get issues opened.
- Correct behavior should be documented.
- Breaking changes vs 1.16 should be highlighted (e.g. 1.16. uses stdout.)

### Additional context

# Stdio:
Wesnoth uses stderr (info written to test-err.txt)
``wesnoth.exe --userdata-path --wnoconsole --wnoredirect > test-out.txt 2>test-err.txt``

Wesnoth does not use stderr
``wesnoth.exe --wnoconsole --wnoredirect --userdata-path > test-out.txt 2>test-err.txt``

Adding ``--userdata-path`` last cancels ``--wnoconsole``
Adding ``--log-to-file`` cancels ``--wnoredirect``
Adding ``--no-log-to-file`` cancels ``--wnoconsole``

stdio is used only if both ``--wnoconsole`` and ``--wnoredirect`` are active.

# Windows GUI (Double-click on customized program shorcut)

a) ``--userdata-path``
b) ``--userdata-path --wnoredirect``

![imagen](https://github.com/wesnoth/wesnoth/assets/4925744/0346a4bb-682a-47de-a093-3e3133cda014)

Adding ``--wnoconsole`` causes the console window not to pop up.

# Console (``cmd``):
```
echo off & cls
wesnoth.exe --userdata-path
Battle for Wesnoth v1.17.16 x86_64
Started on Wed May 10 15:44:59 2023

Automatically found a possible data directory at: C:\Program Files\Battle for Wesnoth 1.17.16
D:\.default\Documents\My Games\Wesnoth1.17

wesnoth.exe --userdata-path --wnoconsole

wesnoth.exe --userdata-path --wnoredirect
Battle for Wesnoth v1.17.16 x86_64
Started on Wed May 10 15:45:18 2023

Automatically found a possible data directory at: C:\Program Files\Battle for Wesnoth 1.17.16
D:\.default\Documents\My Games\Wesnoth1.17

wesnoth.exe --userdata-path --wnoconsole --wnoredirect
```

# Console (``Git for Windows``)
```
W7@W7PC MINGW64 /c/Program Files/Battle for Wesnoth 1.17.16
$ ./wesnoth.exe --userdata-path

W7@W7PC MINGW64 /c/Program Files/Battle for Wesnoth 1.17.16
$ ./wesnoth.exe --userdata-path --wnoconsole

W7@W7PC MINGW64 /c/Program Files/Battle for Wesnoth 1.17.16
$ ./wesnoth.exe --userdata-path --wnoredirect

W7@W7PC MINGW64 /c/Program Files/Battle for Wesnoth 1.17.16
$ ./wesnoth.exe --userdata-path --wnoconsole --wnoredirect
Battle for Wesnoth v1.17.16 x86_64
Started on Wed May 10 16:14:25 2023

Automatically found a possible data directory at: C:\Program Files\Battle for Wesnoth 1.17.16
D:\.default\Documents\My Games\Wesnoth1.17

```

(Git for Windows displays stdio)

**Comment by Pentarctagon** [comment] 2023-05-10 21:24
IMO both `--wnoconsole` and `--wnoredirect` should be removed and their functionality tied directly to the `--log-to-file`/`--no-log-to-file` options.

**Comment by ProditorMagnus** [comment] 2023-05-10 21:37
I get impression these flags are to choose exactly one of
1) log to file
2) log to fake console (not sure how its called properly)
3) log to console

As GUI 1) should be used. As doubleclick 2) should be used. As command line 3) should be used.

For me it looks like --no-log-to-file does not make sense, it does not specify whether to pick 2) or 3).

**Comment by Slayer95** [comment] 2023-05-10 21:54
Related: https://github.com/wesnoth/wesnoth/issues/7310

Also noticed this from ``wesnoth.exe --help`` (Introduced in 3bc6a293f7d5)

```
  --no-log-to-file                log output is written to standard error
                                  rather than to a file.
  --log-to-file                   log output is written to a file even if it
                                  would normally go to standard output/error.
                                  Cancels the effect of --no-log-to-file
                                  whether implicit or explicit.
```

It's claimed that ``--log-to-file`` overrides ``--no-log-to-file``. However, in ``master``, it's ``--no-log-to-file`` that overrides ``--log-to-file`` (``terminal_force == true`` causes ``write_to_log_file`` to be ignored).

https://github.com/wesnoth/wesnoth/blob/01f28b12aea57c969e0331eb38af5dde1bac9cfa/src/wesnoth.cpp#L1119-L1134

**Comment by Pentarctagon** [comment] 2023-05-10 22:14
@ProditorMagnus Your options 2 and 3 are the same thing I think? For Windows it will check if it was started from a console and if not it will create one for Wesnoth to use, but both should be proper consoles.

**Comment by Slayer95** [comment] 2023-05-10 22:27
> @ProditorMagnus Your options 2 and 3 are the same thing I think? For Windows it will check if it was started from a console and if not it will create one for Wesnoth to use, but both should be proper consoles.

Yeah. Before thoroughly testing for this issue, I was also under the impression that 2 and 3 would be different, but they work just the same way.

**Comment by CelticMinstrel** [comment] 2023-05-10 23:52
Slightly related: #7575 

It's not about logging, but it _is_ about options seemingly not doing what they're documented to do.

**Comment by Slayer95** [comment] 2023-05-14 20:31
Untested, but ``--no-log-to-file`` should now equivalent to the ``--wnoredirect --wnoconsole`` combination after 0f55036.

Documentation still probably needs improvement.

**Comment by Pentarctagon** [comment] 2023-05-14 22:00
So that would be someone on Windows testing that redirection with `>` works as expected then?

**Comment by Slayer95** [comment] 2023-05-14 22:31
> So that would be someone on Windows testing that redirection with > works as expected then?

Can't currently build it myself, I am afraid.

**Comment by Pentarctagon** [comment] 2023-05-15 00:22
@Wedge009 would you be able to build current master and check?

**Comment by soliton-** [comment] 2023-05-15 15:17
What happens if you add `2>&1` to the end?

**Comment by Wedge009** [comment] 2023-05-15 17:52
Same behaviour.

**Comment by Pentarctagon** [comment] 2023-05-15 18:18
What happens if you remove these lines and then retest with `wesnoth --no-log-to-file > out.txt 2>&1`: https://github.com/wesnoth/wesnoth/blob/master/src/log_windows.cpp#L114-L125

**Comment by Wedge009** [comment] 2023-05-16 07:52
Removing those lines the redirection seems to work as expected. stdout and (presumably) stderr get written to `out.txt` and the command prompt returns immediately upon execution.

As an aside, just as well I got home on the weekend and am not planning to travel again till the end of the year. No other Windows devs available? (:

**Comment by Pentarctagon** [comment] 2023-05-16 14:35
Nice, thanks. It sounds like that could fix #7500 as well, given you said "the command prompt returns immediately upon execution".

**Comment by CelticMinstrel** [comment] 2023-05-16 17:52
> Nice, thanks. It sounds like that could fix #7500 as well, given you said "the command prompt returns immediately upon execution".

Um, I think the part in quotes is literally the definition of #7500, meaning that it's not fixed at all.

**Comment by Pentarctagon** [comment] 2023-05-16 18:44
I think I'm not understanding what that means then. Doesn't "return immediately upon execution" mean that it executes and then the prompt is shown again?

**Comment by Wedge009** [comment] 2023-05-16 22:45
I'm not sure exactly what the reporter means with 'echo' in #7500. But to clarify:

1. `C:\...\x64-Release>wesnoth --no-log-to-file > out.txt 2>&1`
2. Wesnoth GUI runs, stdout and stderr is written to `out.txt` instead of the console.
3. Immediately after step 1 is executed, the console prompt returns: `C:\...\x64-Release>`

**Comment by Wedge009** [comment] 2023-05-16 22:47
Uh oh. I just ran `wesnoth --no-log-to-file` and nothing shows in the console - I also checked the default log location and nothing is written there either.

**Comment by Pentarctagon** [comment] 2023-05-16 22:56
That'd be on current master?

**Comment by Wedge009** [comment] 2023-05-16 23:06
Current master with your modification described above (same as #7632).

**Comment by Pentarctagon** [comment] 2023-05-16 23:48
And if you add those lines back, then:
* When run from an existing console, the output is present but not redirected.
* When it creates a console when run from a shortcut, the output is present but not redirected.
?

**Comment by Wedge009** [comment] 2023-05-17 03:01
When restoring to master:

* Yes, `wesnoth --no-log-to-file > out.txt 2>&1` results in stdout and stderr on the console, no redirection. I also have to press `Enter` to restore the command prompt.
* I never tried from a short-cut. I assume it would be the same behaviour as directly from the console.

**Comment by Pentarctagon** [comment] 2023-05-17 04:49
I'm confused then - previously you said that:

> Removing those lines the redirection seems to work as expected. stdout and (presumably) stderr get written to out.txt and the command prompt returns immediately upon execution.

Does that mean that redirection works as expected, but when not redirecting nothing appears on the console?

**Comment by Wedge009** [comment] 2023-05-17 06:36
On master: redirection does **not** work, but `--no-log-to-file` on its own works as expected.

Removing the lines you indicated: redirection _does_ work, but then `--no-log-to-file` on its own does not work.

> Does that mean that redirection works as expected, but when not redirecting nothing appears on the console?

Yes, when removing the lines you indicated.

**Comment by CelticMinstrel** [comment] 2023-05-17 13:55
> Doesn't "return immediately upon execution" mean that it executes and then the prompt is shown again?

Immediately means immediately, not after the game has finished executing. It means the prompt is shown as the game is starting up. If console output is on, that also mean output from Wesnoth _follows_ the prompt, which once Wesnoth exits makes it look as though it's hanging, because you appear to not have a prompt – however, it's accepting input and you can type whatever. You'd get a new prompt if you just press enter.

**Comment by Pentarctagon** [comment] 2023-05-17 14:50
Ah, alright, I misread that issue then.

For this issue, it sounds like what's needed is to somehow have the log output go both to stderr (for redirection) and CONOUT (for display) at the same time?

**Comment by Pentarctagon** [comment] 2023-05-24 16:33
It looks like the main issue is that there isn't any way in the logger to do this sort of duplication, since the log output is written directly to a stream (either std::cerr or the log file ostream). Otherwise it would (probably?) be fairly simple to take the text to be written out and write it both to the std::cerr and to CONOUT.

**Comment by CelticMinstrel** [comment] 2023-05-24 18:02
I don't think it's hard to make a C++ streambuf that behaves like `tee`, if that's what you want.

**Comment by Pentarctagon** [comment] 2023-05-24 18:52
From what Iris said on Discord yesterday, it sounded like it would be quite difficult:
> (alternatively you could try to do what i was trying to do a couple years ago and figure out how to do a 2-way pipe in a cross-platform fashion, i wish you luck on that though)
> i don't quite remember the result of my research, because i was trying to figure out a way to make it work on windows too (and iirc that was even more complicated)
> if you know the tee  command, i was essentially trying to make wesnoth do a cross-platform tee

Maybe this would be less complicated since it only needs to work on Windows?

**Comment by CelticMinstrel** [comment] 2023-05-25 02:12
I don't know what exactly `tee` does (in terms of how it's implemented), but a custom C++ streambuf is not all that difficult, and a streambuf that forwards all its input to two other streambufs seems like it wouldn't be much work at all.

I don't know how you'd get the effect of `tee` by using WinAPI or POSIX. I don't know if doing so would provide a performance benefit over a custom streambuf.

**Comment by soliton-** [comment] 2023-05-25 14:11
> Ah, alright, I misread that issue then.
> 
> For this issue, it sounds like what's needed is to somehow have the log output go both to stderr (for redirection) and CONOUT (for display) at the same time?

I don't think so. Seems unexpected/unwanted and confusing to see output when you redirect it. Either there is a way to detect redirection (which redirection? stdout/stderr/stdin? all of them? maybe just check if stderr is a tty?) and disable console redirection in that case or removing `-w[no]console` was a mistake and should be reverted since you need it to stop wesnoth from overriding your own redirections.

**Comment by Pentarctagon** [comment] 2023-05-25 14:49
It's unexpected from a macOS/Linux perspective, but for Windows this appears to be the intended model - printing to CONOUT (displays on console, can't redirect) and printing to stderr/stdout (doesn't display on console, can be redirected) are separate things. I don't know why `--w[no]console` would need to be re-added though, since that was only about whether to attach a console or not. `--wnoredirect` would be the one that might need to be re-added.

**Comment by soliton-** [comment] 2023-05-25 16:37
`--wnoredirect` is pretty much equivalent to `--no-log-to-file`, no? The redirection to console part overrides whatever redirections the caller did when opening CONOUT$. Certainly you also need to not log to file or that will also override your redirections but that option still exists.

Since microsoft itself uses two different workarounds (https://learn.microsoft.com/en-us/archive/blogs/junfeng/how-to-make-an-application-as-both-gui-and-console-application) that do not involve writing to both CONOUT$ and stdout I don't think that is the intended model or expected behavior by users.

**Comment by Pentarctagon** [comment] 2023-05-25 16:49
The two options listed there are essentially:
* Distribute two copies of wesnoth.exe, one built with the GUI subsystem flag and the other built with the Console subsystem flag.
* Require using another "editbin" executable to swap that flag on wesnoth.exe manually.
Neither of which are particularly intuitive either.

**Comment by Pentarctagon** [comment] 2023-05-25 17:20
So as far as I can tell, there's two approaches:
* Output to both stdout and CONOUT.
* Output only to one at a time, and have an option to allow choosing which to use.

There are a couple uses of std::cin in wesnoth.cpp, but I don't think they actually work? The console wasn't kept open waiting for input the last time a user had an issue and tried running cwesnoth.cmd.

**Comment by soliton-** [comment] 2023-05-25 17:36
I don't know what opening CONIN$ exactly means in our case. On Linux running a background process and trying to read from the terminal will get the process stopped by the kernel. No clue what happens on windows. Having multiple processes compete for input is generally not a good idea.

**Comment by CelticMinstrel** [comment] 2023-05-25 18:25
> Require using another "editbin" executable to swap that flag on wesnoth.exe manually.

I think I actually like this approach best. It would be part of the build process, so once it's working, it would Just Work.

**Comment by soliton-** [comment] 2023-05-25 18:47
Does it work though? It seems to me calling a GUI app is like starting a background process (next prompt is displayed, input should go to the console so you can type the next command) so presumably the console either closes right after starting wesnoth in the background or it stays open anyway and waits for the next command?

**Comment by Pentarctagon** [comment] 2023-05-25 18:48
Requiring a regular player to use EDITBIN to alter an executable sounds pretty terrible if we want them to actually be able to do that.

My point before though is that the use of std::cin doesn't actually stop the console from closing - just recently a person tried using cwesnoth.cmd to be able to see output on the console and that console instantly closed.

**Comment by soliton-** [comment] 2023-05-25 18:50
Umm, none of the workarounds are done by the user.

**Comment by Pentarctagon** [comment] 2023-05-25 18:51
Then there's no reason to use EDITBIN in the first place - the build process could just use the Console subsystem flag directly.

**Comment by soliton-** [comment] 2023-05-25 18:54
You'll have to bring that up with the visual studio devs. Presumably there is a reason why it's done the way it's described there.

**Comment by soliton-** [comment] 2023-05-25 19:41
I really don't care what provides ildasm. If it's not visual studio then whatever other SDK or whatever. The point is that all workarounds are done by the devs not by the user.

**Comment by Slayer95** [comment] 2023-05-28 04:32
> tried using cwesnoth.cmd to be able to see output on the console and that console instantly closed.

Works for me both in 1.16.9 and 1.17.16. Is it possible the issue that user experienced also caused ``cwesnoth`` to close?

![imagen](https://github.com/wesnoth/wesnoth/assets/4925744/3a119468-0b15-403a-bd2a-84b16b2b23dd)

**Closed** 2023-05-29 05:08 UTC
Labels: Bug, Windows, Command Line
