### ISSUE TITLE
Titltescreen not fully redrawn after exiting a game.

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#7467] opened 2023-03-22 00:03 UTC
### Game and System Information

Version: 1.17.14+dev

### Description of the bug

Background somehow not redrawn, see the attached  picture (behind the button and behind the hint of the day)

### Steps to reproduce the behavior

1) Start a game
2) Do somwething, i don't remember what i did
3) Exit to titlescreen.

### Additional context

![image](https://user-images.githubusercontent.com/4893136/226768147-8f0882d3-4330-436c-902b-ac382078f50e.png)

**Comment by Wedge009** [comment] 2023-03-22 00:04
I know you've been away for a while, but this is a duplicate of #6988.

**Closed by Wedge009** 2023-03-22 00:04 UTC
Labels: Bug, Graphics
