### ISSUE TITLE
[1.17.x] [Add-ons Manager Client] [UI] Add-ons description "vanishes" when using scroll bar.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6879] opened 2022-07-17 00:29 UTC
### Game and System Information

- **Version:** Battle for Wesnoth v1.17.5+dev (91983c8c875-Modified) x86_64
- **Downloaded from:** Github
- **Build info:** Battle for Wesnoth v1.17.5+dev (91983c8c875-Modified) x86_64 | Msys2
- **OS:** Windows 10

### Description of the bug

The addon's description just vanishes when scrolling to view the full description within the addons-client.

### Steps to reproduce the behavior

1. Open client
2. Connect to addons server. View addon descriptions which are very long.
3. Attempt to see the full description
4. Be amazed how the whole description goes black.

### Expected behavior

I can read the whole addon description like in 1.16.5 addons client

### Additional context

Log file was nuked with this

```java
20220717 06:22:51 error gui/layout: grid [] place: Failed to place a grid, we have (0,675) space but we need (292,30) space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui210addon_listE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui25panelE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'addon_manager'.
20220717 06:22:51 warning display: window::draw called with drawing suspended
20220717 06:22:51 warning display: window::draw called with drawing suspended
20220717 06:22:51 warning display: window::draw called with drawing suspended
20220717 06:22:51 warning display: window::draw called with drawing suspended
20220717 06:22:51 warning display: window::draw called with drawing suspended
20220717 06:22:51 warning display: window::draw called with drawing suspended
20220717 06:22:52 warning display: window::draw called with drawing suspended
20220717 06:22:52 warning display: window::draw called with drawing suspended
20220717 06:22:52 warning display: window::draw called with drawing suspended
20220717 06:22:52 warning display: window::draw called with drawing suspended
20220717 06:22:52 warning display: window::draw called with drawing suspended
20220717 06:22:52 warning display: window::draw called with drawing suspended
20220717 06:22:52 warning display: window::draw called with drawing suspended
20220717 06:22:52 warning display: window::draw called with drawing suspended
20220717 06:22:52 warning display: window::draw called with drawing suspended
20220717 06:22:52 warning display: window::draw called with drawing suspended
20220717 06:22:52 warning display: window::draw called with drawing suspended
20220717 06:22:52 error gui/general: vertical_scrollbar [_vertical_scrollbar] recalculate: Can't recalculate size, force a window layout phase.
20220717 06:23:03 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:03 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:04 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:04 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:04 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:05 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:05 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:05 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:05 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:05 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:05 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:07 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:07 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:08 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:08 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:08 error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.
20220717 06:23:25 error gui/layout: grid [] place: Failed to place a grid, we have (0,675) space but we need (292,30) space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui210addon_listE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui25panelE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'addon_manager'.
20220717 06:23:25 warning display: window::draw called with drawing suspended
20220717 06:23:25 warning display: window::draw called with drawing suspended
20220717 06:23:25 warning display: window::draw called with drawing suspended
20220717 06:23:25 warning display: window::draw called with drawing suspended
20220717 06:23:26 warning display: window::draw called with drawing suspended
20220717 06:23:26 warning display: window::draw called with drawing suspended
```

**Comment by knyghtmare** [comment] 2022-07-17 00:31
Screenshot Proof
As you can see...the whole text has gone missing
![image](https://user-images.githubusercontent.com/5283677/179378531-a57c630b-ed2f-4395-b295-385e0c100aa7.png)

**Comment by knyghtmare** [comment] 2022-07-17 00:35
Also, hovering the mouse over the horizontal scroll bar...breaks the whole UI....
![image](https://user-images.githubusercontent.com/5283677/179379185-8cc01579-0360-45ae-a369-02d3365b44f6.png)

**Comment by Wedge009** [comment] 2022-07-17 06:18
Has this been worked on recently? There aren't as many add-ons published for 1.17 and Capture the Flag is the longest one I could find. However, even reducing my window size to 1680x1050 to get scroll bar on the description I don't see anything amiss.

Why is your build marked modified? I tested against f2ef9393524 'clean'.

**Comment by doofus-01** [comment] 2022-07-17 21:23
Using bc94f37f767, I cannot reproduce this.

**Comment by mesilliac** [comment] 2022-07-19 01:46
Does this change if you change the screen size? The addons UI has poor definition at certain screen sizes.

Particularly: if you make the screen/window small enough that the addons manager uses the smaller-form layout, without the separate description panel, does it still happen?

**Comment by knyghtmare** [comment] 2022-07-19 12:18
Still happens with (2e28ed4617a-Modified) x86_64

```java
20220719 18:16:13 error gui/layout: grid [] place: Failed to place a grid, we have (0,678) space but we need (272,30) space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui210addon_listE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui25panelE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'addon_manager'.
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 warning display: window::draw called with drawing suspended
20220719 18:16:13 error gui/general: vertical_scrollbar [_vertical_scrollbar] recalculate: Can't recalculate size, force a window layout phase.
```

**Comment by knyghtmare** [comment] 2022-07-19 12:19
> Particularly: if you make the screen/window small enough that the addons manager uses the smaller-form layout, without the separate description panel, does it still happen?

Yes

**Comment by mesilliac** [comment] 2022-07-19 12:36
Hmm. I also get all these errors and warnings, but the text does appear correctly for me.

There is a bunch of cleanup to do (also relating to things like these warnings). It's quite possible when the needed cleanup is done it will fix this issue.

**Comment by mesilliac** [comment] 2022-08-07 23:56
Does this still happen in current master? I haven't done anything explicitly to fix it, but several things have changed.

**Comment by knyghtmare** [comment] 2022-08-26 06:57
Yes
```java
20220826 14:40:03 error gui/layout: grid [] place: Failed to place a grid, we have (0,675) space but we need (292,30) space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui210addon_listE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui25panelE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui27dialogs13addon_managerE' with the id 'addon_manager'.
20220826 14:40:04 error gui/general: vertical_scrollbar [_vertical_scrollbar] recalculate: Can't recalculate size, force a window layout phase.
```

**Comment by Wedge009** [comment] 2023-01-11 07:10
@knyghtmare I would say that you're really only entitled to remove Unconfirmed tags if someone else _besides_ the original reporter can confirm the issue.

That aside, I realise now this is likely the same issue as #7093, which is probably why the rest of us (I'm assuming mesilliac and doofus were also testing in Linux) could not replicate it earlier.

**Comment by Wedge009** [comment] 2023-01-11 08:23
I can confirm this now, but only on Windows. It is indeed the same issue as #7093.

**Comment by knyghtmare** [comment] 2023-01-11 08:25
So, what's the duplicate and what's the one that stays open?

**Comment by Toranks** [comment] 2023-01-11 18:55
Both are actually different errors with the same cause. The ideal would be a merger of reports (this is possible?). It affects inspect console, help, [message], addons, and ultimately anything with a scroll bar, and only on Windows. It doesn't happen on linux.

**Comment by Wedge009** [comment] 2023-12-18 23:16
I can't replicate this in 1.17.24 release. Related issues #7093, #7565, #7655 are closed. Anyone else still encountering this?

**Comment by Pentarctagon** [comment] 2024-01-13 20:24
You can't reproduce the issue on Windows?

**Comment by Pentarctagon** [comment] 2024-01-18 16:41
Well, I'll go ahead and close this then - if anyone is still encountering this, feel free to re-open.

**Closed by Pentarctagon** 2024-01-18 16:41 UTC
Labels: Bug, Confirmed, Blocker: New Stable, UI, Regression, Medium Priority
