### ISSUE TITLE
Using Ctrl-F to go to Full screen and back renders wesnoth window blank

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#2050] opened 2017-09-28 17:04 UTC
X11, GNU/Linux, SDL 2.0.5.

Steps to reproduce:

1. Start Wesnoth in windowed mode
2. Press Ctrl-F from main screen
3. Press again
4. Wesnoth goes back to windowed mode, but its window is filled with black and no controls or anything are visible.

Hovering mouse around reveal button one by one and eventually window is redrawn and all content goes back in place. Sometimes windows goes all black while in fullscreen mode too.

**Comment by GregoryLundberg** [comment] 2017-09-28 17:15
Cannot reproduce the blank/black screen. I see it go black but repaint properly a moment later.

I am seeing random crashes using the steps above;

```
[lundberg@lundberg-arch ~]$ ./wesnoth/wesnoth
Battle for Wesnoth v1.13.10 (3df86a0f6c-Clean)
Started on Thu Sep 28 12:12:27 2017

Automatically found a possible data directory at /home/lundberg/wesnoth

Data directory:               /home/lundberg/wesnoth
User configuration directory: /home/lundberg/.config/wesnoth
User data directory:          /home/lundberg/.local/share/wesnoth/1.13
Cache directory:              /home/lundberg/.cache/wesnoth

Setting mode to 1440x845
Checking lua scripts... ok
Segmentation fault (core dumped)
[lundberg@lundberg-arch ~]$ ./wesnoth/wesnoth
Battle for Wesnoth v1.13.10 (3df86a0f6c-Clean)
Started on Thu Sep 28 12:13:06 2017

Automatically found a possible data directory at /home/lundberg/wesnoth

Data directory:               /home/lundberg/wesnoth
User configuration directory: /home/lundberg/.config/wesnoth
User data directory:          /home/lundberg/.local/share/wesnoth/1.13
Cache directory:              /home/lundberg/.cache/wesnoth

Setting mode to 800x600
Checking lua scripts... ok
*** Error in `./wesnoth/wesnoth': free(): invalid pointer: 0x00007f91b9421000 ***
Aborted (core dumped)

```

**Comment by Arcanister** [comment] 2017-09-28 17:32
What SDL version do you use? Your free message suggests SDL 2.0.6.

**Comment by GregoryLundberg** [comment] 2017-09-28 17:39
```
[lundberg@lundberg-arch ~]$ yaourt -Q sdl2
extra/sdl2 2.0.6-1

```

**Comment by Arcanister** [comment] 2017-09-28 17:41
I think it could be related with dbd6695 
Before this commits Wesnoth would just crash on startup immediately with 2.0.6

**Comment by Wedge009** [comment] 2017-09-29 06:21
I only get the issue in Linux, and I'm still running SDL 2.0.5. Flipping between window and full-screen, I alternate between this black screen issue and #2035. There may be a connection there. Maybe with #2041 as well.

**Comment by Arcanister** [comment] 2017-09-29 07:27
In both cases Wesnoth window doesn't redraw properly immediately after changing state.
Behavior between Ctrl-F and Check-box differ though, I don't get black screen with checkbox. Either it's because when using mouse to click it causes additional window events, or code which handles Ctrl-F is different from code which handles checkbox in Wesnoth.

**Comment by Wedge009** [comment] 2017-09-29 07:33
The similarity is with respect to the underlying graphical problem, not the method of switching to/from full-screen. It seems to me that finding and resolving the cause for one will resolve it for the other, so until we know otherwise I would consider these two symptoms to be the same issue.

I'd agree with the idea that the mouse-click events may cause some additional interaction avoiding the black-out issue.

**Comment by Pentarctagon** [comment] 2017-09-29 18:24
This doesn't occur for me either.  Wesnoth info: https://i.imgur.com/C4Y2BSn.png

**Comment by Wedge009** [comment] 2017-10-14 05:39
As agreed with @CelticMinstrel, closing this as duplicate of #2035 and #2041.

**Closed by Wedge009** 2017-10-14 05:39 UTC
Labels: bug, confirmed, duplicate, Graphics, linux, UI
